### ISSUE TITLE
Add test execution time to wptreport.json format

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#10026]
This was suggested in # #9972.

Basically the execution time is the timestamp of the `test_end` event minus the timestamp of the `test_start` event. So to fix this look in `tools/wptrunner/wptrunner/formatters.py`, add a `time` field to the data and populate it with the execution time per test.

**Comment by manikishan** [comment]
Can I work on it?

**Comment by jgraham** [comment]
Yes.

**Comment by foolip** [comment]
This would be great!

**Comment by marimeireles** [comment]
Hey, @manikishan 
Are you still working on this?
Thanks.

**Comment by manikishan** [comment]
No,sorry I would not be able to work on it now.
Sorry.

**Comment by marimeireles** [comment]
I could try to fix this, if you don't mind.

**Comment by jgraham** [comment]
Go for it.

**Comment by foolip** [comment]
@marimeireles do you still intend to work on this?

**Comment by marimeireles** [comment]
Hey,
Not in the moment, sorry!

**Comment by foolip** [comment]
Oh yay, @gsnedders for president! @jugglinmike @Hexcles, have you seen this show up in runs yet? How much does it change the wptreport size?

**Comment by jugglinmike** [comment]
Yup, the data is being collected!

    $ ssh bocoup-wptd-build-master 'sudo -u wptdmaster cat /mnt/buildmaster-data/chunk-results/f556cda8f3ab2c14851a63ecd3def3c03de8182d/edge-17-windows-10-sauce/10_of_100.json | python -m json.tool | head -n 10'
    {
        "results": [
            {
                "duration": 3385,
                "message": null,
                "status": "PASS",
                "subtests": [],
                "test": "/css/css-writing-modes/background-size-document-root-vrl-004.html"
            },
            {

I don't have a great way to check the size of the final reports, though, since we remove them immediately following successful upload.

**Comment by Hexcles** [comment]
I will have the numbers soon (fixing a bug in receiver now).

**Comment by jgraham** [comment]
wptreport is not optimized for size, if we are concerned about non-compressed size there's definitely changes we could make. What's the motivation there?

**Comment by foolip** [comment]
There's a request size limit in the wpt.fyi receiver, and we're not miles away from it. Hopefully this doesn't push it over the limit.

**Comment by Hexcles** [comment]
@foolip we only transport the compressed form

Adding a field like this wouldn't blow the compressed size up too much due to the nature of dictionary-based compression algorithms.

**Comment by foolip** [comment]
Well, with enough precision the numbers will be increasingly random, and not compress as well.
