### ISSUE TITLE
Travis logs for Firefox jobs make it hard to see how far in the 10 cycles it ran

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#10028]
In https://github.com/w3c/web-platform-tests/pull/8922 the Firefox job failed, but it's very hard to figure out from the logs how far in the 10 iterations it got:
https://travis-ci.org/w3c/web-platform-tests/jobs/352958109

**Comment by foolip** [comment]
@jgraham, I noticed this again in https://github.com/w3c/web-platform-tests/pull/10191. Seems like the test names are never printed, is that surprising? Where would be the right place to add it?

**Comment by stephenmcgruer** [comment]
We no longer use Travis, this seems obsolete.
