### ISSUE TITLE
css/css-tables/table-model-fixup-2.html is racy, plus doesn't reflect the spec or implementations.

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/wpt#10165]
This was brought to my attention because of https://bugzilla.mozilla.org/show_bug.cgi?id=1445164.

The test is failing intermittently on Firefox, but I see the same intermittent behavior in WebKit too (when the system is under high load in particular). Furthermore, all browsers agree on failing different tests, yet this test doesn't reflect the changes made in https://github.com/w3c/csswg-drafts/issues/508.

Anyway, the racy test is:

```html
    <div>
        <x-table style="width: 400px">
            <x-tr><x-td><img block src="../support/blue32x32.ico" target=a /></x-tr>
            <img src="../support/blue32x32.ico" table-row target=b />
        </x-table>
    </div>
    <script>
        assertEqualOffsetWidths('a','b');
    </script>
```

Which relies on the image being loaded while `offsetTop` is being computed, which is not necessarily the case. The failure happens because if the image has not loaded, Firefox and WebKit at least doesn't consider it a replaced element, and thus the rule the test is trying to test doesn't apply.

Looks like the test could just be rewritten to wait onload before doing the checks instead of doing the checks inline as the page loads.

**Comment by emilio** [comment]
Note that there are other tests that are very similar to that one which are in theory racy. In practice these don't fail intermittently because by the time we get to them the image has already loaded and is in the cache from the first `img` test (the one in the comment above).

**Comment by FremyCompany** [comment]
Or I can use test_promise and wait for the image to be loaded before running the actual test. 
That's probably even safer.

**Comment by jgraham** [comment]
The way this test is writted is pretty weird in general; it doesn't seem necessary to depend on `offsetTop` forcing layout if you just load everything and do the tests from the `onload` handler.

**Comment by rocallahan** [comment]
> I guess the solution is to use a data uri to store the icon, would that work safely for every browser?

That won't work because data: URIs still go through an asynchronous load path, at least in Firefox and it should be true in other browsers too per spec.

**Comment by MatsPalmgren** [comment]
I will update the test to reflect the spec [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1694729).
I also discovered that it doesn't really test what it claims to be testing in half the sub-tests, so I'll amend it to fix that too.

(I haven't tried to address the "intermittent failure" issues described above though.)
