### ISSUE TITLE
RTCRtpHeaderExtensionParameters missing members are not tested

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#10253]
https://github.com/w3c/webrtc-pc/pull/1816 made two members of [RTCRtpHeaderExtensionParameters](https://w3c.github.io/webrtc-pc/#dom-rtcrtpheaderextensionparameters) required, and this could be tested here:
https://github.com/w3c/web-platform-tests/blob/172fe9d52634f70dd2810c4a859acd1aa6dc365a/webrtc/RTCRtpParameters-headerExtensions.html#L58

(This test passes all the members, 3 tests that each omit one of them would do the trick.)

**Comment by dontcallmedom** [comment]
closing per https://github.com/web-platform-tests/wpt/pull/10282#pullrequestreview-171316415 (RTCRtpHeaderExtensionParameters are only read from the platform, not meaningfully modified)
