### ISSUE TITLE
Say something useful when someone tries to run a testdriver test with wpt serve

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt#10330]
Testdriver tests can only be run using wpt run. I think we should provide some sort of message indicating this is the case when someone tries to run the test using wpt serve.

cc/ @foolip @jgraham WYT?

**Comment by foolip** [comment]
@kereliuk, what do you think we should do, concretely?

**Comment by jugglinmike** [comment]
In gh-11173, I'm proposing that we don't force the test to fail but instead allow authentic human input and react accordingly. As described in the patch, that would allow test authors and visitors to http://w3c-test.org to validate testdriver.js-powered tests.

**Comment by lukebjerring** [comment]
Even if Mike's tweak lands (👍 by the way, Mike), we should have some docs @ https://web-platform-tests.org/writing-tests/testdriver.html which explain that there are differences between `run` and `serve` for this case.

**Comment by foolip** [comment]
@kereliuk, can you look into adding such documentation?

**Comment by jugglinmike** [comment]
Since gh-11173 introduces the new behavior for `wpt serve` contexts, and since that hasn't been merged yet, it's probably best for me to add the documentation that @lukebjerring has requested to that patch. I'll do that later today.

**Comment by jugglinmike** [comment]
Actually, it looks like that patch already updates the documentation:

```diff
--- a/docs/_writing-tests/testdriver.md
+++ b/docs/_writing-tests/testdriver.md
@@ -5,7 +5,9 @@ order: 8.5
 ---
 
 testdriver.js provides a means to automate tests that cannot be
-written purely using web platform APIs.
+written purely using web platform APIs. Outside of automation
+contexts, it allows human operators to provide expected input
+manually.
 
 It is currently supported only for [testharness.js][testharness]
 tests.
```

I'll follow up about potential improvements on the pull request.

**Comment by foolip** [comment]
Included in [Ecosystem Infra 2018 Q4 OKRs](https://docs.google.com/document/d/1UKuPaQm2YGHYEfbrrYBHoCUGAVhyQZEp8nE09qT7vYg/edit#heading=h.jwokykbtd9cq).

I think we can use `navigator.webdriver` for this, somehow.

**Comment by mdittmer** [comment]
_Ping from your friendly neighbourhood ecosystem infra rotation_

Any updates on this, @gsnedders?

**Comment by gsnedders** [comment]
@jugglinmike worked on this a while ago in #11173, and that's had some more activity recently.

**Comment by gsnedders** [comment]
#11173 landed, so this is fixed.
