### ISSUE TITLE
Multiple 'Exposed' attributes unhandled by idlharness.js

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#10338]
e.g. From https://wicg.github.io/budget-api/

    [Exposed=Window]
    partial interface Navigator {
        [SameObject] readonly attribute BudgetService budget;
    };

https://github.com/w3c/web-platform-tests/pull/10337 improved the error message somewhat, but  we should be applying the `Exposed` to the nested members and asserting that it's a subset of the original interface's exposure set.

**Comment by foolip** [comment]
[Exposed] on partial interfaces is allowed, https://heycam.github.io/webidl/#Exposed says "If [Exposed] appears on a partial interface or partial namespace, then the partial’s own exposure set must be a subset of the exposure set of the partial’s original interface or namespace."

**Comment by foolip** [comment]
https://github.com/w3c/web-platform-tests/pull/10337 is about multiple `Exposed` extended attributes syntactically (in the AST) but the example given has just one.

So the issue may not be with duplication as such, but with how idlharness.js merges extended attributes for partial interfaces?

https://github.com/w3c/web-platform-tests/blob/89daad32c029798b7203a36f21598fcba470e07d/resources/idlharness.js#L628

However, I'm afraid I can't spot the bug, because it seems to (correctly) just forward the extended attributes to all of the members, and the extended attributes on non-partial interfaces aren't propagated like that (they usually say something about the interface itself). So where's the duplication coming from?

**Comment by lukebjerring** [comment]
The spot you link to is correct. The issue is that the `extAttrs` for partials are copied to the main interface (not just to the members inside the partial).
Instead, they should be asserted to be a subset of the existing attribute (if present).

**Comment by lukebjerring** [comment]
So, taking a stab at this, using https://github.com/tidoust/reffy-reports/blob/master/whatwg/idl/webusb.idl as an example.

    [Exposed=(DedicatedWorker,SharedWorker), SecureContext]
    partial interface WorkerNavigator {
      [SameObject] readonly attribute USB usb;
    };

Produced

> "DedicatedWorker exposed on partial WorkerNavigator interface, but not on main interface."

Sure enough, `DedicatedWorker` is not exposed on `WorkerNavigator`. I'm not convinced I'm solving anything, just more yak shaving...

**Comment by foolip** [comment]
OK, sounds like a bug in either WebUSB or HTML.

**Comment by foolip** [comment]
Hmm, nothing https://heycam.github.io/webidl/#Exposed in suggests that `Exposed=(DedicatedWorker,SharedWorker)` should work at all. @domenic, do you know if things have changed in the land of `Exposed`?

**Comment by domenic** [comment]
Sorry, why wouldn't that work? Seems fine to me...

**Comment by lukebjerring** [comment]
> If [Exposed] appears on a partial interface or partial namespace, then the partial’s own exposure set must be a subset of the exposure set of the partial’s original interface or namespace.

`DedicatedWorker` isn't in the exposure set of the original `WorkerNavigator` interface.

**Comment by domenic** [comment]
I see. That seems like a bug in the definition of exposure set; if Worker is the exposure set, then all globals which inherit from WorkerGlobalScope should be there too. Right?

**Comment by foolip** [comment]
> Sorry, why wouldn't that work? Seems fine to me...

Where are the allowed keywords defined? The string "DedicatedWorker" only appears in an example in the Web IDL spec.

**Comment by domenic** [comment]
https://html.spec.whatwg.org/#dedicated-workers-and-the-dedicatedworkerglobalscope-interface

**Comment by foolip** [comment]
Aha, well then presumably the problem is that `Worker` isn't expanded correctly to the different kinds of workers. If it was, then `Exposed=(DedicatedWorker,SharedWorker)` would be a subset.

**Comment by domenic** [comment]
Yeah, that's what I was trying to get at in https://github.com/web-platform-tests/wpt/issues/10338#issuecomment-395458867. It seems like https://heycam.github.io/webidl/#dfn-exposure-set should be corrected to do that sort of expansion.

**Comment by lukebjerring** [comment]
Ah, thanks Dom. so, when "fixing" this, I'm going to make the resolution of each partial interface wrap itself in a test, so that failing one partial only _partially_ (hehe) breaks things.

At the same time, I'll assert a subset, and expand `Worker` into `ServiceWorker` and `DedicatedWorker`. Are there other expansions I should be aware of?

**Comment by lukebjerring** [comment]
chromium CL: https://chromium-review.googlesource.com/c/chromium/src/+/1091210
