### ISSUE TITLE
Add support for cascading IDL dependencies to idlharness.js

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#10347]
For new / separate specs, often dependencies on the original interface are created, e.g. when `partial`-ing out an existing interface. Often, that interface also inherits other interfaces, and can be a nightmare to isolate/filter.

Several things can happen in attempt to resolve the problem:

- We end up with a 'mock' of the interface, e.g. `idl_array.add_untested_idls('interface Document {};');`
- We import massive files like `dom.idl` in their entirety
- We filter imports, but end up filtering the whole dep chain

None of these is desirable or robust, nor documented. 

Resolving this issue would entail formalized behaviour of the framework for dependencies (and, optionally mocks) in a way that reduces boiler-plate and mitigates test breakages for changes to dependencies.

**Comment by foolip** [comment]
@lukebjerring, should we consider this resolved by https://github.com/web-platform-tests/wpt/pull/10381?

**Comment by lukebjerring** [comment]
(1 year later...) Yes, we should.
