### ISSUE TITLE
Testdriver: tabs switch frequently when invokes multiple actions

### ISSUE THREAD

**Issue by Honry** [web-platform-tests/wpt#10398]
I encountered this issue when trying to automate test at https://github.com/w3c/web-platform-tests/pull/10396/files#diff-52f806f8477bda3b3246226c740e6cb9

When invokes multiple `test_driver` actions, the runner will switch tab pages between test page and testharness_runner.html immediately and frequently(one action one switch).

**Comment by kereliuk** [comment]
Good catch, I'll take a look at this tomorrow.

**Comment by foolip** [comment]
@kereliuk, should this be priority:roadmap, and has the state of things changed in the intervening months? Seems like this is the same window switching that's the reason that fullscreen can't be automated still?

**Comment by kereliuk** [comment]
Will put on the list for this week, I think the priority should stay the same for now.

**Comment by foolip** [comment]
I came across this in https://github.com/web-platform-tests/wpt/issues/12621. It makes it hard to see what's happening, and all that switching back and forth must have effects that may interfere with the tests. It's also the reason for https://github.com/web-platform-tests/wpt/issues/7281.

@gsnedders, I'm wondering if we should bump the priority of this to "real soon now" and perhaps do together with https://github.com/web-platform-tests/wpt/issues/13183. Can you describe what it would take to change this?

**Comment by jgraham** [comment]
I"m not 100% sure that's necessary. What's undoubtedly required is to stop sending commands to the parent window as the test runs. But it looks like that's possible without merging the windows into one. Maybe I'm missing something though.

**Comment by gsnedders** [comment]
@jgraham if we're sending all the messages to the current window, what use does the parent window have?

**Comment by jgraham** [comment]
Not having the window is possible but it's a larger change than required to fix this, with a different set of tradeoffs.

**Comment by gsnedders** [comment]
@jgraham the parent window is used to receive the results of the testsuite, which would then need to go to the test window (given WebDriver would be listening to messages on the test window), what else?

**Comment by gsnedders** [comment]
@jgraham responded to the above question at https://w3.logbot.info/testing/20181008#c446175

**Comment by mdittmer** [comment]
_Ping from your friendly neighbourhood ecosystem infra rotation_

If this is `priority:roadmap` should it have an assignee?

**Comment by foolip** [comment]
This was fixed by https://github.com/web-platform-tests/wpt/pull/13419
