### ISSUE TITLE
cite attribute test fails for the wrong reason

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#1042]
On line 39 https://github.com/w3c/web-platform-tests/blob/master/html/semantics/grouping-content/the-blockquote-element/grouping-blockquote.sub.html#L39

The test fails.

``` js
{actual: "blehblah", resolved: document.location.protocol + "//" + document.location.host + "/blehblah"},
```

It seems there should be the local context of the file for the path, aka the start of `document.location.pathname` without the final file.

A link in `http://example.com/foo/bar/blah.html` with the following markup

``` html
<a href="blehblah">boo</a>
```

would link to `http://example.com/foo/bar/blehblah`

A way to fix the test is to just test with '/' 

{actual: "/blehblah", resolved: document.location.protocol + "//" + document.location.host + "/blehblah"},
or to extract the file from the `document.location.pathname` part, but a bit more annoying to do.

**Comment by Honry** [comment]
Close it as the file has been removed in https://github.com/web-platform-tests/wpt/pull/1684.
