### ISSUE TITLE
Figure out what causes untracked *.html files to end up in the root of the w3c-test.org repo clone 

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#10476]
When browsing the root of http://w3c-test.org/ and the backing local filesystem on the host, a number of different untracked *.html files sometimes end up there — files that are under version control in subdirectories of the root. The problem is apparently caused by the https://github.com/w3c/github_sync script that we use for syncing w3c-test.org with the repo master branch and for syncing the http://w3c-test.org/submissions area with pull requests.

See also #10475

**Comment by foolip** [comment]
This is still happening, but @bmac has now set up http://web-platform-tests.live/ which I think we'll soon begin using, and it's deployed in a different way which makes it very unlikely this problem will be relevant to fix. Closing.
