### ISSUE TITLE
encoding/utf-32.html seems wrong

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#10588]
In particular not defaulting to UTF-8 for XML doesn't seem like something that standard supports.

cc @inexorabletash

**Comment by inexorabletash** [comment]
Without paging all the algorithms in... I believe that the content is not being interpreted as either XML or HTML - it ends up treated as plain text. (Which is non- or under- specified?)

* Big Endian BOM: `00 00 FE FF` - no UTF-8 or -16 BOM, doesn't sniff, so plain text, windows-1252
* Little Endian BOM: `FF FE 00 00` - UTF-16LE BOM, so UTF-16, doesn't sniff?, so plain text
* Big Endian no BOM: `00 00 00 3C` - no UTF-8 or -16 BOM, doesn't sniff, so plain text, windows-1252
* Little Endian no BOM: `3C 00 00 00` - no UTF-8 or -16 BOM, doesn't sniff, so plain text, windows-1252

Content types served with the tests probably make this more complicated, though - again, would need to go through the algorithms. Unsure if we'd even make it as far as trying to parse as UTF-8 XML, or what we do if that path is taken and we fail super early.

**Comment by inexorabletash** [comment]
i.e. agreed that the expectations encoded in the file are non-obvious, and more investigation is needed

**Comment by annevk** [comment]
(This issue was supposed to be closed from 315b16be16977448d33165f0dc538f00dac0ecd5 but that did not work, at least not as quick as I wanted.)
