### ISSUE TITLE
add tests for <img crossorigin> / img.crossOrigin

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#1066]

**Comment by foolip** [comment]
Spec is https://html.spec.whatwg.org/multipage/embedded-content.html#the-img-element

3 years later, looks like this is still missing. semantics/embedded-content/the-img-element/relevant-mutations.html does involve the attribute, but it a tangential way, and I can't find any others, just a bunch of tests for the script element with the crossorigin attribute.

**Comment by kaixinjxq** [comment]
@foolip, seems these two files [redirect-to-url-with-credentials.https.html](https://github.com/web-platform-tests/wpt/blob/master/fetch/security/redirect-to-url-with-credentials.https.html) and [image-loads.html](https://github.com/web-platform-tests/wpt/blob/master/fetch/cross-origin-resource-policy/image-loads.html) have tested it.

**Comment by foolip** [comment]
Thanks @kaixinjxq, you're right. Those tests came from https://github.com/web-platform-tests/wpt/pull/8976 and https://github.com/web-platform-tests/wpt/pull/11171, so thanks @youennf!
