### ISSUE TITLE
Testdriver calls cannot return any values

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt#10716]
Currently there is no capability in the infrastructure for testdriver to return any information after the call.

For instance, if we want to use testdriver to get the current window size, there is no way to return that information to the testharness.

**Comment by jgraham** [comment]
I agree that could be a problem, but the motivating example isn't very covincing. In particular, why is a test changing the browser window size? What's the use case that you're trying to solve?

**Comment by gsnedders** [comment]
From IRC:


15:05 < gsnedders> kereliuk: what's the plan with https://github.com/w3c/web-platform-tests/issues/10716?
15:30 < kereliuk> gsnedders: I have something on a local branch that works at least for the window commands I've sent PRs for
15:31 < kereliuk> I have the protocol method return a python thing. Serialize that with json.dumps and throw it in the completion message.
15:31 < kereliuk> Then use JSON.parse to put it back into the JS object and attach it to the pending_resolve
15:31 < kereliuk> WYT?

Will respond below…

**Comment by gsnedders** [comment]
@jgraham I don't know about size, but certainly other things related to window management are necessary for testing things like the Page Visibility API.

**Comment by gsnedders** [comment]
@kereliuk yeah, that probably seems as reasonable as anything else (sorry, I got distracted by getting off the train a week ago!)

**Comment by foolip** [comment]
@kereliuk, is this still needed for some API? Is it blocking https://github.com/web-platform-tests/wpt/pull/10749 and https://github.com/web-platform-tests/wpt/pull/10747?

**Comment by foolip** [comment]
Demoting this to backlog as it's not clear which APIs we need it for. Existing PR is at https://github.com/web-platform-tests/wpt/pull/11080 and can be revived when needed for some other work.

**Comment by LukeZielinski** [comment]
A use-case recently came up in the context of WebAuthN - to be able to inspect the credentials that exist on a test device and that authenticating with the wrong key fails.

Still backlog priority, will revisit once such tests are closer to reality.
