### ISSUE TITLE
/workers/semantics/structured-clone/* are disabled in Mozilla and WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#10799]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/workers/semantics/structured-clone/dedicated.html | mozilla webkit | disabled: true [ Skip ] | None None
/workers/semantics/structured-clone/shared.html | mozilla webkit | disabled: true [ Skip ] | None None

Possibly these tests are doing too many things and would work better if split up to several tests.

**Comment by zcorpan** [comment]
Doesn't look very good for Chromium either:

https://test-results.appspot.com/dashboards/flakiness_dashboard.html#testType=webkit_layout_tests&tests=external%2Fwpt%2Fworkers%2Fsemantics%2Fstructured-clone%2F

**Comment by zcorpan** [comment]
This should be fixed by @surma's PR https://github.com/w3c/web-platform-tests/pull/9218

**Comment by cdumez** [comment]
@zcorpan Sure, will try.

**Comment by cdumez** [comment]
Test is flaky for us:
/Volumes/Data/cdumez/WebKit/OpenSource/WebKitBuild/Debug/layout-test-results/imported/w3c/web-platform-tests/workers/semantics/structured-clone/dedicated-actual.txt
8585PASS Object Blob object, Blob paired surrogates (invalid utf-8) 
8686PASS Object Blob object, Blob empty 
8787PASS Object Blob object, Blob NUL 
88 FAIL File basic assert_equals: lastModified expected 42 but got 1526665571776
 88FAIL File basic assert_equals: lastModified expected 42 but got 1526665823670
8989PASS FileList empty 
9090PASS Array FileList object, FileList empty 
9191PASS Object FileList object, FileList empty

**Comment by cdumez** [comment]
Printing out lastModified like this does not give stable results.

**Comment by zcorpan** [comment]
Ok. Did you import from today i.e. including #9218?

It seems the test expects 42 and webkit gives something else. Bug?

**Comment by cdumez** [comment]
Yes it is the latest version of the tests. Yes it is a bug in WebKit that the value is not 42). Still the test is flaky when it fails in WebKit because it prints out a timestamp when failing.

**Comment by zcorpan** [comment]
I see. We could make it not flaky by doing an if check and calling assert_unreached instead of assert_equals. Or by fixing the bug. ☺

**Comment by cdumez** [comment]
Yes, I am looking into fixing the WebKit bug.

**Comment by cdumez** [comment]
Ok, the tests are unskipped in WebKit and the file serialization bug is fixed. Thanks for updating the tests.

**Comment by zcorpan** [comment]
Thanks to @surma for fixing these tests. ☺

**Comment by zcorpan** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1464805

**Comment by zcorpan** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=855009
