### ISSUE TITLE
/IndexedDB/keypath-exceptions.htm is disabled in Mozilla and WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#10793]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/IndexedDB/keypath-exceptions.htm | mozilla webkit | disabled: feature is incomplete [ Skip ] | https://bugzilla.mozilla.org/show_bug.cgi?id=1404274 None

**Comment by inexorabletash** [comment]
Is it flaky or just disabled?

If flaky, if you can give me a couple logs (pass/fail) I can probably puzzle it out.

**Comment by zcorpan** [comment]
" disabled: feature is incomplete " for mozilla, and "skip" for webkit. But it seems nicer to have the tests fail if the feature is not supported so it doesn't need to be disabled. I haven't yet investigated this test, I can take a closer look next week.

**Comment by inexorabletash** [comment]
In FF52 I get 3 pass / 3 fail, harness OK. 

I'm not sure what's actionable on the test - should it just be enabled with failures in Moz?

**Comment by inexorabletash** [comment]
Deflaked in 0f6860b863dd90ea1580de7f11d0cd2872f1713c
