### ISSUE TITLE
/html/dom/dynamic-markup-insertion/opening-the-input-stream/010.html is disabled in Mozilla and flaky in WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#10795]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/html/dom/dynamic-markup-insertion/opening-the-input-stream/010.html | mozilla webkit | disabled [ Failure Timeout ] | https://bugzilla.mozilla.org/show_bug.cgi?id=1139795 None

**Comment by zcorpan** [comment]
@jgraham any idea on how to fix this test?

**Comment by zcorpan** [comment]
@jgraham assigning this to you for now. I can come back to this later this year if it hasn't been fixed.

**Comment by TimothyGu** [comment]
The test in question was removed in https://github.com/web-platform-tests/wpt/pull/12634.
