### ISSUE TITLE
/IndexedDB/idbdatabase-createObjectStore-exception-order.htm is disabled in Mozilla and flaky in WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#10792]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/IndexedDB/idbdatabase-createObjectStore-exception-order.htm | mozilla webkit | disabled [ Pass Failure ] | https://bugzilla.mozilla.org/show_bug.cgi?id=1336639 https://webkit.org/b/172243

**Comment by zcorpan** [comment]
cc @inexorabletash and @pwnall

**Comment by inexorabletash** [comment]
I'll try and take a look.

(Best guess from code inspection is that the browsers are not following the spec to the letter and so the work done in the setTimeout() races with the abort() call actually aborting the transaction, rather than the abort being processed immediately.)

**Comment by inexorabletash** [comment]
Hrm, in FF52 at least the failure is due to the error bubbling up to window.onerror. Fixed by either 

```js
setup({allow_uncaught_exception:true});
``` 
or:
```diff
@@ -8,9 +8,11 @@
 <script>
 
 indexeddb_test(
-  (t, db, txn) => {
+  (t, db, txn, rq) => {
     db.createObjectStore('s');
 
+    rq.onerror = e => { e.preventDefault(); };
+
     txn.onabort = () => {
```

**Comment by inexorabletash** [comment]
I had thought that FF was removing the event bubbling for IDB since the other browsers hadn't implemented it yet (although we plan to in Chrome)
