### ISSUE TITLE
/WebCryptoAPI/generateKey/* are disabled/flaky in Mozilla Chromium WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#10794]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/WebCryptoAPI/generateKey/test_successes_RSA-OAEP.https.html | mozilla chromium webkit | disabled [ Pass Timeout ] [ Pass Failure ] | https://bugzilla.mozilla.org/show_bug.cgi?id=1279799 https://crbug.com/787971 None

Edit: also:

* /WebCryptoAPI/generateKey/test_successes_RSA-PSS.https.html
* /WebCryptoAPI/generateKey/test_successes_RSASSA-PKCS1-v1_5.https.html
* /WebCryptoAPI/generateKey/successes_RSA-OAEP.https.worker.html
* /WebCryptoAPI/generateKey/successes_RSA-PSS.https.worker.html
* /WebCryptoAPI/generateKey/successes_RSASSA-PKCS1-v1_5.https.worker.html

**Comment by zcorpan** [comment]
@andypaicu @foolip @Hexcles any thoughts on what, if anything, we can do with this test?

The test has this warning
```html
<p>
    <strong>Warning!</strong> RSA key generation is intrinsically
    very slow, so the related tests can take up to
    several minutes to complete, depending on browser!
</p>
```

**Comment by foolip** [comment]
How long does it take to generate a single RSA key? Is the test just trying to generate too many and needs to be split?

**Comment by zcorpan** [comment]
For me it seems to take around 1s per subtest, and this has 156 subtests, so yeah, splitting it up to multiple files (or `variant`s) seems reasonable.

**Comment by Hexcles** [comment]
This is also tracked in Chromium by the way: https://crbug.com/787971

Splitting the tests seems a reasonable way. Apparently `timeout: long` isn't enough.

**Comment by zcorpan** [comment]
I think it would work to use `<meta name="variant" content="?1-10">` to run the first 10 tests, and 11-20 and so on.

**Comment by zcorpan** [comment]
@Hexcles yep, my report picked that up :)

**Comment by jgraham** [comment]
Make sure you test this in Firefox; iirc the generation is slower in Gecko for some (I think intentional) reason.

**Comment by zcorpan** [comment]
For me it seems slightly faster in Firefox, but of course it can depend on the device under test. If 10 subtests is still too much we can do 5 or so. But let's try 10 first.

**Comment by zcorpan** [comment]
@Hexcles can you update TestExpectations for chromium?

@cdumez can you update TestExpectations for webkit?

Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1470130 for gecko.

**Comment by Hexcles** [comment]
@zcorpan done https://chromium-review.googlesource.com/c/chromium/src/+/1110738

**Comment by zcorpan** [comment]
Commented in https://bugs.webkit.org/show_bug.cgi?id=182396
