### ISSUE TITLE
[css-backgrounds] 2 border-image-slice-00[ 5 | 7 ].htm tests with bad linkage to 9grid40-30-20-10-lime.png

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#10808]
http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-slice-005.htm
(wrong filename!): it should be 9grid40-30-20-10-lime.png and not 9grid40-30-20-10-red.png

http://test.csswg.org/suites/css-backgrounds-3_dev/nightly-unstable/html4/border-image-slice-007.htm
This test is currently the only test in the CSS3 Backgrounds and 
Borders test suite testing the 'fill' reserved keyword.

**Comment by TalbotG** [comment]
https://w3c-test.org/css/css-backgrounds/border-image-slice-005.htm

https://w3c-test.org/css/css-backgrounds/border-image-slice-007.htm

**Comment by smfr** [comment]
These also have missing images in the refs:
css/css-backgrounds/css3-border-image-repeat-repeat.html
css/css-backgrounds/css3-border-image-repeat-stretch.html

**Comment by TalbotG** [comment]
[css-backgrounds-3] border-image-slice-007 bad linkage to its border-image-source
http://lists.w3.org/Archives/Public/public-css-testsuite/2016Dec/0000.html
December 1st 2016

[css-backgrounds-3] border-image-slice-005 bad linkage to its border-image-source
http://lists.w3.org/Archives/Public/public-css-testsuite/2016Dec/0004.html
December 1st 2016

[css-backgrounds] css3-border-image-repeat-stretch test 
http://lists.w3.org/Archives/Public/public-css-testsuite/2017Sep/0001.html
September 21st 2017

There are a few *border-image-* and some other border tests that should be checked and then, if required, corrected.


css-border-radius-002.html test
http://web-platform-tests.live/css/css-backgrounds/css-border-radius-002.html
should be removed entirely since a reference can not be created for it.

**Comment by TalbotG** [comment]
> css-border-radius-002.html test
> http://wpt.live/css/css-backgrounds/css-border-radius-002.html
> should be removed entirely since a reference can not be created for it.

"I will remove the test, the reference and the 
yy.png image [and yyy.png] from the repository in 1 week from now (on May 30th 2020)."
https://lists.w3.org/Archives/Public/public-css-testsuite/2020May/0000.html

**Comment by TalbotG** [comment]
> (wrong filename!): it should be 9grid40-30-20-10-lime.png and not 9grid40-30-20-10-red.png

It's most likely/probably a correct filename. The "red" and "lime" most likely refer to the center of the border-image itself. Therefore...

I will soon (before May 30th 2020) fix the tests
[css-backgrounds-3] border-image-slice-005
[css-backgrounds-3] border-image-slice-007
by replacing them with:
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-005-GT.html
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-007-GT.html

Also will fix 2 others with
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-shorthand-002-GT.html
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-shorthand-003-GT.html

I will create reference files for all 4 tests.

**Comment by TalbotG** [comment]
https://github.com/web-platform-tests/wpt/pull/23808

**Comment by TalbotG** [comment]
> These also have missing images in the refs:
> css/css-backgrounds/css3-border-image-repeat-repeat.html
> css/css-backgrounds/css3-border-image-repeat-stretch.html

I am working on fixing those too right now and also make those tests more precise:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/css3-border-image-repeat-repeat-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/css3-border-image-repeat-repeat-GT-ref.html

**Comment by TalbotG** [comment]
http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/css3-border-image-repeat-stretch-GT.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/reference/css3-border-image-repeat-stretch-GT-ref2.html

**Comment by TalbotG** [comment]
September 26th 2020 recap

Corrections and improvements in 
css/css-backgrounds/css3-border-image-repeat-repeat.html
css/css-backgrounds/reference/css3-border-image-repeat-repeat-ref.html
css/css-backgrounds/css3-border-image-repeat-stretch.html
css/css-backgrounds/reference/css3-border-image-repeat-stretch-ref.html
have been done in the **merged PR** https://github.com/web-platform-tests/wpt/pull/25240

Removal of css-border-radius-002.html and related files has been 
done in the **merged PR** https://github.com/web-platform-tests/wpt/pull/23881

Corrections and improvements in 
css/css-backgrounds/border-image-shorthand-002
css/css-backgrounds/border-image-shorthand-003
have been done in the PR https://github.com/web-platform-tests/wpt/pull/25802 . Merging PR25802 will allow me to close https://github.com/web-platform-tests/wpt/pull/21445

Fixing and improving border-image-slice-00[ 5 | 7 ].htm tests will 
require more time, maybe 2-4 weeks ...

**Comment by TalbotG** [comment]
I closed #21445 and now I'm closing this Issue.
