### ISSUE TITLE
Add big red warning to /tools/runner/index.html

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#10843]
I've heard from multiple people who have tried to use http://w3c-test.org/tools/runner/index.html and run into various problems, without realizing it's not a well-supported way to run WPT.

We should discourage its use with a warning, so that people only use it if they really want to.

**Comment by akansha2608** [comment]
Hi @foolip I would like to work on it , can you help me how to proceed with this issue? 

Thanks

**Comment by foolip** [comment]
Sure, that would be great! The source is at https://github.com/web-platform-tests/wpt/blob/master/tools/runner/index.html, so you'll need to add some prominent warning there about this runner not supporting everything that `./wpt run` does. Linking to https://github.com/web-platform-tests/wpt/labels/runner as known issues would be good.

**Comment by foolip** [comment]
Thanks for working on this, @akansha2608!
