### ISSUE TITLE
Consider a non-.org domain to host the test suite on

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#10924]
See https://github.com/w3c/web-platform-tests/pull/10891#issuecomment-387649102 for rationale.

**Comment by annevk** [comment]
(This is for the public-facing version, i.e., `http://w3c-test.org/`.)

**Comment by annevk** [comment]
That's our long term plan for Encoding defaulting. Rather than letting it be locale-dependent.

**Comment by hsivonen** [comment]
After the earlier comments, Gecko has changed to treat `com`/`net`/`org` the same way as new vanity domains, so `org` vs. `live` should make no difference. (Those used to be different.)

Now on both the three original generic TLDs and new vanity TLDs, all these types of _unlabeled_ content are treated as `windows-1252`:

* ASCII.
* Actual `windows-1252` that has enough content not to be confused with other Latin legacy encodings.
* Content that uses a wide range of upper-half bytes to represent a caseless non-Latin script that is not supported by the Web platform (notably legacy font hacks from pre-iPhone/Android-era India).
* UTF-8.
