### ISSUE TITLE
Move tools/html5lib and tools/six into tools/third_party

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#10922]
It would be nice to move these so all the upstream projects we have live in tools/third_party (plus resources/webidl2); note I'm not considering `pywebsockets` as upstream as we've already forked it, upstream is unmaintained, and we're likely to fork it further, hence it should live in tools/.

**Comment by Hexcles** [comment]
@gsnedders  Can I take the chance and ask what customization have we done to `pywebsockets`? The [history](https://github.com/w3c/web-platform-tests/commits/master/tools/pywebsocket) isn't very helpful...

We switched to upstream `pywebsockets` in Blink without knowing this, and so far we haven't observed any new failures.

**Comment by gsnedders** [comment]
@Hexcles I think https://github.com/w3c/web-platform-tests/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a is it.
