### ISSUE TITLE
Revisit LICENSE.md?

### ISSUE THREAD

**Issue by plehegar** [web-platform-tests/wpt#11009]
The current [LICENSE.md](https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md) comes from history in W3C around test suites and hasn't been looked at in the past 4 years at least.

We should look at it again and see if it still makes sense. If not, we need to figure out what would make sense. and then a transition path from the current one to a new one.

**Comment by jgraham** [comment]
(I am not an expert, etc.)

The only transition path in terms of changing licences would be to adopt the only the BSD variant currently allowed. Relicensing wpt is effectively impossible, since there is no copyright assignment and there are such a large number of contributors.

I'm all in favour of dropping the W3C Test License part though; I don't think anyone uses that in practice.

**Comment by foolip** [comment]
There is also [CONTRIBUTING.md](https://github.com/w3c/web-platform-tests/blob/master/CONTRIBUTING.md), which I do not fully understand. @plehegar, can you explain in lay terms what that means, and how it relates to the license, if at all?

**Comment by plehegar** [comment]
The first is the grant of license, which basically gives us the right to relicense under the original BSD license, effectively replacing the current LICENSE.md if we'd like to. I could check to see if we still need to have it but I would guess so, except that we could give the right to relicense to more than just W3C.
The second part is a disclaimer. not sure if we need this.

**Comment by foolip** [comment]
@plehegar, by "the original BSD license", do you mean something other than the "W3C 3-clause BSD License" in LICENSE.md?

**Comment by wseltzer** [comment]
@foolip yes, I believe we could switch to just the 3-clause BSD license instead of the current dual-license. (Anyone who was using tests under the W3C Test Suite License would be able to continue to do so.)

**Comment by foolip** [comment]
@wseltzer, that sounds great, do you want to prepare a PR to trim LICENSE.md so that we get it exactly right?

**Comment by annevk** [comment]
I looked into providing the PR for this, taking https://opensource.org/licenses/BSD-3-Clause as inspiration. However, that suggests you need to start with

> Copyright <YEAR> <COPYRIGHT HOLDER>

which is something that we currently lack. Would

> Copyright 2018 web-platform-tests contributors

work?

**Comment by foolip** [comment]
I think the idea is to trim LICENSE.md to just contain https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md#w3c-3-clause-bsd-license verbatim, but waiting for PR from @wseltzer or @plehegar instead of trying it myself :)

**Comment by annevk** [comment]
Sure, but that wouldn't comply with the official license format as far as I can tell. It also seems strange to preserve the W3C prefix.

**Comment by foolip** [comment]
@annevk do you mean a format that GitHub expects?

**Comment by annevk** [comment]
That the license, as per https://opensource.org/licenses/BSD-3-Clause, should be in.

**Comment by foolip** [comment]
There are a bunch of other minor differences too, like "source code" vs. "works" and "COPYRIGHT OWNER" vs. "COPYRIGHT HOLDER".

The label of the license is presumably not part of the license and could be dropped, but this bit is part of the license itself: "Neither the name of the W3C nor the names of its contributors may be used to endorse or promote products derived from this work without specific prior written permission."

@plehegar @wseltzer, do you believe any change to that is required/desired?

**Comment by foolip** [comment]
Ping @plehegar @wseltzer, any progress on this?

**Comment by wseltzer** [comment]
I'm sorry, but PSIG (the Patents and Standards Interest Group, which gathers IP lawyers) wants to discuss further, and proposes to do so at their July 9 meeting. I have recommended that we use the second of the dual licenses -- the W3C 3-clause BSD, because we're not aware of any continuing (or past) need for the protection against claims of conformance, but I think we owe them the opportunity to discuss and raise concerns. If there's other input from here to that discussion, I'll share that then, Thanks.

**Comment by foolip** [comment]
Thanks @wseltzer, please keep us posted! The question in https://github.com/web-platform-tests/wpt/issues/11009#issuecomment-392473208 and whether "W3C nor the names of its contributors" can be replaced by "web-platform-tests project nor the names of its contributors" are also questions that I'd like to see addressed.

**Comment by annevk** [comment]
@wseltzer see https://github.com/web-platform-tests/wpt/pull/11191#issuecomment-394059712. In particular:

> [T]hat variant doesn't have the copyright line and refers to the W3C twice, which seems weird if this is meant to be BSD. Are those considered identical enough for projects to use it without issue?

The lack of a copyright line seems pretty problematic, not sure about wording differences.

**Comment by wseltzer** [comment]
Per conversation with @foolip I'm filing two pull requests against license.md, one dropping from the dual license to the W3C 3-clause BSD; the other replacing with the straight 3-clause BSD (which differs only in not having the named copyright holder W3C). PSIG has given non-objection to the W3C 3-clause BSD. If that would still cause legal hiccups, then we can probably persuade them of the vanilla 3-clause.

**Comment by jugglinmike** [comment]
We may be able to resolve these issues using WPT's new RFC process:

https://github.com/web-platform-tests/rfcs/pull/18

**Comment by jayvdb** [comment]
I note that the PyPI source distributions do not contain a `LICENSE` file (at least two I checked).  It is highly desirable that they are included, usually by adding it to `MANIFEST.in`.

**Comment by foolip** [comment]
Finally resolved via https://github.com/web-platform-tests/rfcs/pull/18 and https://github.com/web-platform-tests/wpt/pull/11191, thanks everyone!
