### ISSUE TITLE
/encoding/* are disabled in Chromium and WebKit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11015]
https://bocoup.github.io/wpt-disabled-tests-report/

/encoding/legacy-mb-tchinese/big5/big5-encode-form-errors-extBa.html

and

/encoding/legacy-mb-tchinese/big5/big5-encode-form-errors-extBb.html

should be split up, maybe similarly to how it was done in https://github.com/w3c/web-platform-tests/pull/10984

**Comment by zcorpan** [comment]
Maybe also many other encoding tests.

**Comment by Hexcles** [comment]
Sorry, it seems like 1000 (code points?) per test is still too many for some tests.

It takes about 30 seconds to run each split test using content_shell (which is faster than full Chrome) on my workstation (which is faster than Chromium bots). The following tests still [time out in Chromium](https://chromium-review.googlesource.com/c/chromium/src/+/1081123):

```

 external/wpt/encoding/legacy-mb-japanese/euc-jp/eucjp-encode-href-errors-han.html?10001-10000
 external/wpt/encoding/legacy-mb-japanese/euc-jp/eucjp-encode-href-errors-hangul.html?10001-10000
 external/wpt/encoding/legacy-mb-japanese/shift_jis/sjis-encode-href-errors-han.html?10001-10000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?15001-16000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?16001-17000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?17001-18000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?18001-19000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?19001-20000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?20001-21000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?21001-22000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?22001-23000
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-han.html?23001-last
 external/wpt/encoding/legacy-mb-tchinese/big5/big5-encode-href-errors-hangul.html?10001-10000
```

Also, there seems to be a bug in generating the indexes: the range "10001-10000" is probably wrong.

**Comment by zcorpan** [comment]
Thanks. Would 100 subtests be OK?

**Comment by zcorpan** [comment]
I managed to introduce a bug in some of the encoding tests (`../../ranges.js` should be `../../resources/ranges.js`). Fixing.
