### ISSUE TITLE
More info on "GENERATED CONTENT - DO NOT EDIT"

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#11109]
imported IDL files currently say:

```
// GENERATED CONTENT - DO NOT EDIT
// Content of this file was automatically extracted from the Payment Request API spec.
// See https://link.to.spec 
```

In addition to a link to the spec, what would be more helpful would be a link to the project that's actually doing the import.
 
cc @lukebjerring, @foolip

**Comment by marcoscaceres** [comment]
as an aside, the generated content updates should probably come form a "-bot", and not from @lukebjerring's account.

**Comment by foolip** [comment]
So far the PRs actually have been prepared by @lukebjerring and not a bot, but yeah, when PRs are being auto-created it should be by a bot account.

**Comment by foolip** [comment]
@marcoscaceres I've submitted https://github.com/tidoust/reffy-reports/issues/16, would that and an interfaces/README.md explaining the setup resolve this?

**Comment by foolip** [comment]
Added README in https://github.com/web-platform-tests/wpt/pull/12295.

**Comment by foolip** [comment]
Linking to that README from https://github.com/tidoust/reffy-reports/pull/17.

**Comment by foolip** [comment]
@marcoscaceres README changes have landed now:
https://github.com/web-platform-tests/wpt/blob/master/interfaces/README.md
https://github.com/tidoust/reffy-reports/blob/master/README.md

Do you think that is sufficient, or should the boilerplate itself link to something, as suggested in https://github.com/tidoust/reffy-reports/issues/16?

**Comment by marcoscaceres** [comment]
I'm not sure tbh. I think we might just ride this out and see if people complain or get confused.

**Comment by foolip** [comment]
It's being fixed in https://github.com/tidoust/reffy/commit/cadc77757bf510519ef1bcb2cea213aae4181731 and https://github.com/tidoust/reffy/pull/114

**Comment by foolip** [comment]
This has now been fixed and changes have propagated to wpt.
