### ISSUE TITLE
/workers/name-property.html is flaky in chromium webkit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11185]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/workers/name-property.html | chromium webkit | [ Timeout Failure Pass ] [ Pass Failure ] | https://crbug.com/815116 https://webkit.org/b/184453

cc @domenic

Using `await` on each `fetch_tests_from_worker` at least ought to result in stable order of subtests.

**Comment by zcorpan** [comment]
@domenic can you update TestExpectations for chromium?

Don't know Ryan's github handle; commented in https://bugs.webkit.org/show_bug.cgi?id=184453

**Comment by domenic** [comment]
I don't have time to update the TestExpectations myself, but I'd suggest filing a bug on crbug.com to get it into the worker teams' triage queue.

**Comment by zcorpan** [comment]
It looks like it has been enabled in chromium by now. (Fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=721219 I think.)

I commented in the WebKit bug again.
