### ISSUE TITLE
Failing in all browsers test in dom/nodes/Element-matches.html

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#11212]
`In-document Element.matches: Universal selector, matching all descendants of the specified reference element (with refNode Element): *` in https://wpt.fyi/results/dom/nodes/Element-matches.html seems suspicious.

**Comment by domenic** [comment]
Same problem with the sibling file, Element-webkitMatchesSelector.html

**Comment by foolip** [comment]
Source is here:
https://github.com/web-platform-tests/wpt/blob/91d7e29edf7e68ec7b0c1f17d1ea0ebbb1a29b7b/dom/nodes/selectors.js#L442

This was last touched by @Ms2ger in https://github.com/web-platform-tests/wpt/commit/6ceec439c15e6843d90ea9b4e9c3d0e8de907736, ages ago.

**Comment by foolip** [comment]
Actually, it's https://github.com/web-platform-tests/wpt/blob/ccd35804dbdc6e37763a4b980e048c5f5fdf7c39/dom/nodes/selectors.js#L451

Don't know how I ended up at that older commit through the GitHub UI...

**Comment by Ms2ger** [comment]
Possibly related: https://github.com/web-platform-tests/wpt/pull/1577

This is more of a Selectors test; cc @tabatkins @fantasai

**Comment by foolip** [comment]
A problem I noticed trying to debug this is that selectors.js is written as if `element.matches` can still take more than one argument, with this bit of comment:
```
 * expect.matches(selector, context)    // Only where refNodes is not specified
 * expect.matches(selector, refNodes)
 * expect.matches(selector)             // Only if neither context nor refNodes is specified
```

And it's written to test `find()` and `findAll()`, which never came to be.
