### ISSUE TITLE
/workers/semantics/multiple-workers/* are flaky/disabled in chromium webkit

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11222]
http://bocoup.github.io/wpt-disabled-tests-report/

Investigate what's up with this test:

Path | Products | Results | Bugs
-- | -- | -- | --
/workers/semantics/multiple-workers/003.html | chromium webkit | [ Failure Timeout ] [ Skip ] | https://crbug.com/655458 None

These can detect if `Worker` or `SharedWorker` are not defined, and fail the test.

**Comment by zcorpan** [comment]
@nhiroki can you update TestExpectations for chromium?

@cdumez can you update TestExpectations for webkit?

**Comment by nhiroki** [comment]
@zcorpan Thank you for letting me know. I updated the test expectations for Chromium ([commit](https://github.com/chromium/chromium/commit/3c916a5e84db524eadcec06d32b6e2a884f6c4c7))

**Comment by zcorpan** [comment]
I think there isn't anything more to do for this issue for now. That WebKit doesn't support nested workers is tracked in https://bugs.webkit.org/show_bug.cgi?id=22723
