### ISSUE TITLE
No tests for presentational table attributes

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#11235]
In https://crbug.com/703053 I looked for tests for `<table background>` but couldn't find any. https://software.hixie.ch/utilities/js/live-dom-viewer/saved/5974 is an ad-hoc test.

In https://html.spec.whatwg.org/multipage/rendering.html#tables-2, at least the `background`, `bgcolor` and `bordercolor` attributes on `table` and related elements appear to be untested. They could easily be tested using reftests. For example:

Test:
```html
...
<table background=/images/green.png>
...
```

Ref:
```html
...
<table style="background-image:url(/images/green.png)">
...
```

**Comment by kaixinjxq** [comment]
@foolip, I am glade to create these tests.

**Comment by foolip** [comment]
@kaixinjxq, thanks, please enjoy! :)
