### ISSUE TITLE
[Presentation API] Add test for starting presentations on two distinct displays

### ISSUE THREAD

**Issue by mfoltzgoogle** [web-platform-tests/wpt#11233]
This is to track adding a test case to the controlling-ua suite that alllows start() to succeed twice on the same controlling page, to start two distinct presentations on two presentation displays.

Note that implementation limitations in Chrome may prevent this from currently passing for all display types.

**Comment by mfoltzgoogle** [comment]
CC @tomoyukilabs

**Comment by tomoyukilabs** [comment]
@mfoltzgoogle Okay, I'll submit a PR to address this issue. Thanks!

**Comment by mfoltzgoogle** [comment]
Looks good - I left a couple of minor comments on the tests. I will look forward to verifying them in Chrome.

**Comment by tomoyukilabs** [comment]
Thanks, @mfoltzgoogle!
