### ISSUE TITLE
Migrate Travis CI to GitHub Apps

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#11278]
Like https://github.com/whatwg/meta/issues/96, and possible we can learn from that issue, or vice versa.

**Comment by foolip** [comment]
This is blocked on us transitioning from travis-ci.org to travis-ci.com, which is blocked on Travis making that possible while preserving build history. I forwarded some Travis support replies in https://groups.google.com/a/chromium.org/d/msg/ecosystem-infra/fb2H4CMlqN0/I8gjvD2wCQAJ. Leaving as priority:roadmap as it was "coming months".

**Comment by mdittmer** [comment]
@foolip any movement from Travis?

**Comment by mdittmer** [comment]
_Friendly ecosystem infra rotation ping_

This issue has gotten stale. Any updates @foolip?

**Comment by foolip** [comment]
We are now able to do this, and we've already migrated the wpt.fyi repo. @web-platform-tests/admins does anyone have concerns about completing the transition for all other repos? The process is described in  https://docs.travis-ci.com/user/open-source-repository-migration/ and the only thing to keep in mind is cron jobs. If there are cron jobs, they have to be deleted and recreated, *and* there has to be a commit to the branch they're attached to after they're created. This will only impact results-analysis, however.

**Comment by zcorpan** [comment]
No concerns from me 🙂

**Comment by foolip** [comment]
Done in https://github.com/web-platform-tests/wpt/issues/14499, I forgot I had opened this issue.

**Comment by zcorpan** [comment]
OK. So this can be closed? Reopen if I misunderstood.

**Comment by foolip** [comment]
Yes, I just pressed the wrong button :)
