### ISSUE TITLE
Ownership of @wpt-pr-bot, its heroku app, etc.

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#11275]
Hey folks,

Now that we migrated the wpt-pr-bot repo here, I'd like to transfer the @wpt-pr-bot github user and heroku app and stop maintaining the project altogether. There's a bunch of work coming up once consensus builds around what to do with OWNERS files, etc., and I don't have the time to do this work pro bono anymore.

Please figure out who is going to handle this going forward. You'll need:

- [x] a Heroku account,
- [x] a credit card,
- [ ] figuring out how to get free open source credit to run the app from Heroku (I'll make intros),
- [x] a new email address for the bot.

This is not urgent, but I'd like to have it figured out before July, or before we change the name and/or structure of OWNERS file, whichever comes first.

**Comment by foolip** [comment]
@tobie, thanks for the heads up, I'll sort out ownership of this one way or the other. @jgraham do you have opinions on what the outcome is?

**Comment by jgraham** [comment]
Not specific opinions, but I would like this to have some shared ownership, rather than being only accessible to Mozilla or Google and/or Bocoup employees, or similar. Assuming we continue on Heroku, I don't know what the process should be for getting someone to foot the (presumably zero) bill.

**Comment by foolip** [comment]
I'd also prefer shared ownership, although having a main responsible person would still be good. Shared ownership kinda depends on https://github.com/web-platform-tests/wpt/issues/10668. @jugglinmike FYI.

**Comment by zcorpan** [comment]
I'm happy to be the responsible person. Shared ownership SGTM, but also I can own this until we figure out how shared ownership should work.

**Comment by foolip** [comment]
@zcorpan will set this up and Bocoup will maintain it.
