### ISSUE TITLE
[URL] Parsing `about:blank` against `base` can't give failure

### ISSUE THREAD

**Issue by rmisev** [web-platform-tests/wpt#11287]
The PR #10955 changed testing requirements slightly. But I think the following pattern is incorrect::
> ... if `failure` is true, parsing `about:blank` against `base` must give failure.

The `base` is required to be valid, so this parsing should not return failure.

I guess there must be `input`, not `base`, i.e.:
> ... if `failure` is true, parsing `about:blank` against **`input`** must give failure.

The testing code uses `input` as well:
https://github.com/web-platform-tests/wpt/blob/f696c249c6d41c32bdc04d0bec688ee00228a0cf/url/failure.html#L20-L22

/cc @domenic @annevk

**Comment by annevk** [comment]
Yeah, that's right. I can swap that.
