### ISSUE TITLE
Remove OWNERS who have not joined the web-platform-tests org

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#11293]
As reported in https://github.com/web-platform-tests/wpt/pull/11201#issuecomment-393226129, everyone who is currently in any OWNERS file has been invited to the web-platform-tests org.
 
Currently, 74 people have not accepted the invite, and cannot be added to reviews by wpt-pr-bot.

Plan:
1. Ping those 74 people on this issue and ask them to accept the invite
1. After 2 weeks, ping the remaining people once more
1. After 2 more weeks, remove the non-responders from OWNERS files.

**Comment by foolip** [comment]
@jgraham @tobie, before I go ahead with the first pinging, do you think this makes sense?

**Comment by foolip** [comment]
Doing a preview of the ping, only the first 50 are highlighted, so probably that's the limit on the number of people who can be mentioned in a single comment. Need to take that into account.

**Comment by jgraham** [comment]
I think this is fine. I think in general I might be in favour of proactively removing inactive people from OWNERS files (e.g. in components with more than 10 PRs in the last 12 months, but where the owner has not done any reviews in that time), and this seems much more gentle than that.

**Comment by foolip** [comment]
Yep, I've considered something like that as well, and it's probably a fairly simple script to write. Maybe as the next round :) I'll go ahead and ping people on this issue now.

**Comment by foolip** [comment]
@alsemenov @aogilvie @atanassov @ayg @beidson @bethge @bradkemper @bsittler @cabanier @chaals @chenxix @chunywang @cptvitamin @danielweck @deepak-sa @dominiccooney @dumbmatter @edenchuang @engelke @eric-carlson @EvgenyAgafonchikov @fleizach @hakatashi @halindrome @hallvors @haoxli @hshiozawa @jdsmith3000 @jernoble @JianfengXu @jonathanKingston @Jxck, please see the issue description and visit https://github.com/orgs/web-platform-tests/invitation to accept the invitation, to be able to perform reviews in web-platform-tests. Thank you!

**Comment by foolip** [comment]
@kangxu @khaledhosny @klausw @kristijanburnik @kwkbtr @LeonScroggins @louaybassbouss @luser @minxhuang @nattokirai @nikosandronikos @odinho @omo @pozdnyakov @ronkorving @rsolomakhin @rubys @scottlow @sgrekhov @shishimaru @shs96c @SimonSapin @snsk @spanicker @svillar @tagawa @tantek @tcole3 @therealglazou @timvolodine @toji @tyoshino @uysalere @Volker-E @web-flow @xiaojunwu @xinliux @yunxiaoxie @zhaozihao @zhorvath @zolkis please see the issue description and visit https://github.com/orgs/web-platform-tests/invitation to accept the invitation, to be able to perform reviews in web-platform-tests. Thank you!

Everyone, I will lock this conversation as any further comments will spam a lot of people. Please ping me on any other issue or email me if there are concerns.

**Comment by foolip** [comment]
Now done with a few exceptions. Final bits will be done in https://github.com/web-platform-tests/wpt/issues/11915 to avoid any more spam here. Thanks everyone!
