### ISSUE TITLE
Unhandled errors during promise test doesn't fail the test

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#11347]
In https://chromium-review.googlesource.com/c/chromium/src/+/1082434#27 @henbos and @guidou discovered an issue with a test. Note the seemingly unnecessary try/catch in this test:

```js
promise_test(async t => {
    const caller = new RTCPeerConnection();
    const callee = new RTCPeerConnection();
    const localStream = await navigator.mediaDevices.getUserMedia({audio:true});
    caller.addTrack(localStream.getTracks()[0]);
    const ontrackResolver = new Resolver();
    callee.ontrack = e => {
      try {
        assert_equals(e.track.id, localStream.getTracks()[0].id,
                      'Local and remote track IDs match.');
        assert_equals(e.streams.length, 0, 'No remote stream created.');
        ontrackResolver.resolve();
      } catch (ex) {
        ontrackResolver.reject(ex);
      }
    };
    await exchangeOffer(caller, callee);
    await ontrackResolver.promise;
  }, 'addTrack() with a track and no stream makes ontrack fire with a track and no stream.');
```

It seems unnecessary because usually with `promise_test` the `t.step_func` wrapping of `async_test` callbacks can be avoided. But not always. Here, `t.step_func` is still needed, as failed asserts will be a harness error.

Could we treat unhandled exceptions and unhandled promise rejections as part of the current `promise_test` instead? I don't know what to do with mixed `async_test` and `promise_test`, or about the fact that `promise_test` is implemented on top of `async_test`.

@jugglinmike @jgraham thoughts?

**Comment by foolip** [comment]
Also, a simpler demo of the problem: https://jsbin.com/ruyudoz/1/edit?html,output. Code is:
```js
promise_test(t => {
  return new Promise((resolve, reject) => {
    t.step_timeout(() => {
      assert_true(false);
      resolve();
    });
  });
}, 'will fail fast');

promise_test(t => {
  return new Promise((resolve, reject) => {
    step_timeout(() => {
      assert_true(false);
      resolve();
    });
  });
}, 'will time out with harness error');
```

**Comment by henbos** [comment]
I think not tying the event handler explicitly to the test is problematic. Even if promise_test() ensures only one test is executed at a time, there is no guarantee that a previous test has been properly cleaned up and that no previously assigned event handlers will not fire.

For example,
test1 listens for pc.ontrack and asserts some things, it gets the track as expected and finishes the test.
test2 does something else, and while awaiting something pc.ontrack from test1 unexpectedly fires again and this time fails the assert.

Maybe `pc.ontrack = t.step_func(e => { assert_blah(); });` is the way to go?

**Comment by foolip** [comment]
That will fix your problem, yes. But I think this kind of mistake will become more common the more common `promise_test` becomes, so some way of either not requiring it or leading people to this solution would be great.

**Comment by jugglinmike** [comment]
@foolip I'd like to make sure I understand. Could the problem also be stated as: "Unhandled errors cause harness errors instead of test failures"?

**Comment by foolip** [comment]
@jugglinmike, yes, that's another way to put it.

**Comment by henbos** [comment]
Yes the error is never surfaced and we get a timeout, the fact that an assertion failed being lost on us.

**Comment by foolip** [comment]
Ah, right, it's a timeout with harness error, and the way we deal with timeouts in Chromium (let them time out "externally") means that the harness error never shows up anywhere.

**Comment by henbos** [comment]
Yes, and Chromium-wise we end up having to expect the entire file to timeout, losing all other test coverage of that file, so it's pretty bad. I ended up wrapping the events in t.step_func() and it worked pretty neat.

**Comment by jugglinmike** [comment]
> @jugglinmike, yes, that's another way to put it.

I don't think we can confidently assign an unhandled error to an asynchronous test. Although in @foolip's example, it seems like we could simply find the currently-running Promise test, that would confuse @henbos' event handler example (the uncaught error would be assigned to the second test).

To me, a harness error seems preferable because it more clearly reflects the fact that something is wrong with the way the test has been authored. Test authors who want to use `promise_test` can generally avoid this by making the Promise wrapper as simple as possible and expressing assertions following `await` expressions (or within reaction handlers).

```diff
 promise_test(async t => {
     const caller = new RTCPeerConnection();
     const callee = new RTCPeerConnection();
     const localStream = await navigator.mediaDevices.getUserMedia({audio:true});
     caller.addTrack(localStream.getTracks()[0]);
     const ontrackResolver = new Resolver();
-    callee.ontrack = e => {
-      try {
-        assert_equals(e.track.id, localStream.getTracks()[0].id,
-                      'Local and remote track IDs match.');
-        assert_equals(e.streams.length, 0, 'No remote stream created.');
-        ontrackResolver.resolve();
-      } catch (ex) {
-        ontrackResolver.reject(ex);
-      }
-    };
+    callee.ontrack = e => ontrackResolver.resolve(e);
     await exchangeOffer(caller, callee);
-    await ontrackResolver.promise;
+    cost e = await ontrackResolver.promise;
+    assert_equals(e.track.id, localStream.getTracks()[0].id,
+                  'Local and remote track IDs match.');
+    assert_equals(e.streams.length, 0, 'No remote stream created.');
   }, 'addTrack() with a track and no stream makes ontrack fire with a track and no stream.');
```

Another way of thinking about this is that callbacks and Promises are different paradigms, so authors should choose one and stick to it. See also https://github.com/w3c/web-platform-tests/pull/10933

**Comment by henbos** [comment]
It's not obvious to me why the order would be different in the above example, in both cases "resolve promise (inside of event firing), resolve promise" happens. But I guess there are no guarantee which promise's then() is executed first, if at the beginning of a task execution cycle multiple events are resolved? Or are promises resolved at the end of the cycle?
In any case, the above example is from experience in Chromium.

**Comment by foolip** [comment]
The order in which event and promise callbacks are invoked is very well defined, if not entirely easy to understand. Testing the order of those things is very reasonable, to tell the difference between 'resolve *promise* and queue a task to fire a simple event named "foo"' and 'queue a task to: resolve *promise* and fire a simple event named "foo"'.

**Comment by zcorpan** [comment]
If you want uncaught errors or promise rejections to fail the test, you can use single page tests (but then you're limited to one test per file).

e.g. test.any.js
```js
assert_true(true, 'is single page test');
Promise.resolve().then(() => {
  assert_true(true, 'no step_func');
  setTimeout(() => {
    assert_true(false, 'fail the test');
    done();
  }, 0);
});
```
