### ISSUE TITLE
./wpt run takes a long time waiting for the manifest to update

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#11356]
`./wpt run firefox foo/` is suddenly much slower. This is seemingly because of the manifest update step getting much slower, seemingly because `chardet` is now installed in the venv.

**Comment by foolip** [comment]
@gsnedders, can you bisect your way to which commit made it slower, or do you already know?

**Comment by gsnedders** [comment]
Maybe caused by 0989f187820 updating requests which now depends on chardet instead of vendoring it?

**Comment by gsnedders** [comment]
This may have just been triggered by a release on PyPI and no change on our side?

**Comment by gsnedders** [comment]
Right, so it's caused by `venv.install("requests")` in `tools/wpt/run.py`.

And that's been there since 27434fabeee, and the `requests` unvendoring release happened a few days after that, so maybe we've just always been really slow at the manifest update in `wpt run` since then?

**Comment by foolip** [comment]
Why did updating the manifest get slower, though? Does the new version of `requests` or `chardet`have a performance regression, or something?

**Comment by gsnedders** [comment]
@foolip `html5lib` defaults to falling back to running `chardet` if it can't determine the character encoding (and hasn't had one provided), per step seven of the spec. And this takes a lot of time.

**Comment by gsnedders** [comment]
(This isn't that problematic, it's a simple fix of passing `useChardet=False`, but it still seems to be slow locally, compared with `./wpt manifest`.)

**Comment by gsnedders** [comment]
I suspect much of the difference is running `./wpt manifest --work` instead of `./wpt manifest` and my not having the cleanest working copy. Except it's still vastly slower than `./wpt manifest --work` is. Um.

**Comment by gsnedders** [comment]
It's as if it's always rebuilding it? Hmm. That would explain the perf, but I don't understand how that happens in the code.

**Comment by gsnedders** [comment]
So, in summary:

 * It's super slow for me locally currently because it uses `--work` and I have the built output of the CSS testsuite in my working copy, which don't exist in the cached (and uploaded) copies.
 * `./wpt run` causes it to run with with chardet installed, which is slow (fixed by https://github.com/web-platform-tests/wpt/pull/11385)
 * we always take the slow case for XML parsing with our custom object, which is comparatively slow (also fixed by https://github.com/web-platform-tests/wpt/pull/11385)

**Comment by gsnedders** [comment]
I'm going to close this in favour of some more specific issue about improving caching, to be opened in a moment.

**Comment by gsnedders** [comment]
Also, to note, #11385 made it (in the CSS built testsuite case) 47% quicker!
