### ISSUE TITLE
web-platform-tests.org site structure: remove appendices

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#11514]
"Appendices" and "A load of other useful resources." is mystery meat and doesn't invite clicking it.

Maybe "New to GitHub? Check out this introduction." at top-level and maybe put test templates under "Writing tests".

cc @gsnedders

**Comment by foolip** [comment]
https://web-platform-tests.org/appendix/index.html still exists. @jugglinmike do you have thoughts on how to improve this?

**Comment by jugglinmike** [comment]
@zcorpan's suggestion sounds good to me. Here's a patch for that: gh-18260
