### ISSUE TITLE
Document who the org admins are

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#11548]
@annevk asked on IRC, "can we host a list of admins somewhere?"

Currently @web-platform-tests/admins contains: @foolip @gsnedders @Hexcles @jdm @jgraham @plehegar @sideshowbarker @thejohnjansen @tobie @youennf @zcorpan

This is somewhat related to https://github.com/web-platform-tests/wpt/issues/11473.

I suggest that we check in the list of both this team and the reviewers team somewhere in the repo, and auto-update it. This is the only way to make it publicly visible.

Would that work?

**Comment by zcorpan** [comment]
That would work for me, but I think we should put it in the "meta" repo (when we create it).

**Comment by foolip** [comment]
Yes, I agree.

**Comment by gsnedders** [comment]
Anyone who is a member of the org can load https://github.com/orgs/web-platform-tests/teams/admins/members and see the list there, FWIW

**Comment by foolip** [comment]
Oh... I thought you had to be an admin. In that case, we just need to link to that URL from somewhere :)

**Comment by Hexcles** [comment]
> In that case, we just need to link to that URL from somewhere

Yes. Something like "if you run into problems (e.g. need to force merge a PR), contact an admin: ..."

**Comment by gsnedders** [comment]
@foolip there's a setting for the team that controls that, it was already set to "visible", *shrugs*

**Comment by jugglinmike** [comment]
Documenting this information is one part of gh-10832. Even now, before it has been merged, that patch demonstrates the trouble with documentation of externally-managed configuration: it goes out of date.

I was not aware that GitHub provided a listing. That seems preferable to an out-of-date text file. The drawbacks are that it is not publicly accessible and cannot be version controlled. [There are tools that would let us manage administrators via public and version-controlled text files](https://www.terraform.io/docs/providers/github/r/team_membership.html), but I don't know if anyone besides me thinks that is beneficial. Would anyone here like to see such a solution in WPT?

**Comment by foolip** [comment]
Documented in https://web-platform-tests.org/admin/.
