### ISSUE TITLE
Support multiple document roots in wpt serve

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#11554]
Servo uses a [config](https://github.com/servo/servo/blob/master/tests/wpt/config.ini) that has multiple document roots. I have not figured out a way to replicate this setup when using the `./wpt serve` tool, which only supports using a single document root.

**Comment by foolip** [comment]
@jdm, can you say more about what this is used for? Are there kinds of tests that can't be written because of this?

**Comment by jdm** [comment]
Servo has non-upstreamed tests in a separate document root. There was some reason I was using `./wpt serve` to run the server rather than our usual test harness when I filed this issue, but I can't remember why at this time.

**Comment by foolip** [comment]
@jdm, should we close this issue, then? :)

**Comment by jgraham** [comment]
I think this issue is reasonable to keep open.

**Comment by jdm** [comment]
What I needed was the ability to run non-upstreamed tests in other browsers to verify compatibility. It would be nice if the wpt server supported this

**Comment by foolip** [comment]
Ah, to graft some directory into what `wpt serve` runs, to fix stuff before really moving them into wpt? FWIW, we've had a somewhat related request in Chromium, which is to enable wptserve in directories outside of our wpt import directory. @Hexcles FYI.
