### ISSUE TITLE
assert_throws doesn't allow arbitrary JS objects

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#11556]
See https://github.com/web-platform-tests/wpt/pull/11496#discussion_r195466654

cc/ @saschanaz

**Comment by domenic** [comment]
This now exists, as `assert_throws_exactly(obj, stuff)`, as of https://github.com/web-platform-tests/wpt/commit/993b25d482cb0e76458f384f4a23541506a10563!
