### ISSUE TITLE
Parsing tests for CSS UI Level 3 fail in testharness 

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#11598]
The tests introduced by #10700 all fail in https://test.csswg.org/harness/results/css-ui-3_dev/grouped/, because the `resources/parsing-testcommon.js` file cannot be found.

I don't fully understand the rules for finding these files, but we must be running afoul of them.

@plinss @mrego

**Comment by plinss** [comment]
All resources need to use an absolute path, so `/resources/parsing-testcommon.js` instead

**Comment by frivoal** [comment]
@plinss but in this case, parsing-testcommon.js is not in the top level resource folder, it is only shared between a few tests in this test suite, and is in a resource sub-folder next to the test. Is it impossible to share a JS file without making it global and shared accross the entire test suite?

**Comment by plinss** [comment]
See my edited comment above, locally shared files need to be in a `support/` folder relative to the test so the build system can copy them into the proper place.

**Comment by frivoal** [comment]
@plinss thanks. Submitted https://github.com/web-platform-tests/wpt/pull/11619 to fix that.
