### ISSUE TITLE
WebRTC test is flaky in Chromium

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#11695]
Running the following command shows that the WebRTC test named `RTCPeerConnection-setLocalDescription.html` is flaky in Chromium (version 66.0.3359.181):

    ./wpt run --verify chrome webrtc/RTCPeerConnection-setLocalDescription.html

Here's the relevant output:

> #### /webrtc/RTCPeerConnection-setLocalDescription.html ###
> |                                                       Subtest                                                       |          Results           |                                                            Messages                                                           |
> |---------------------------------------------------------------------------------------------------------------------|----------------------------|-------------------------------------------------------------------------------------------------------------------------------|
> |                                                                                                                     | OK                         |                                                                                                                               |
> | `Calling createOffer() and setLocalDescription() again after one round of local-offer/remote-answer should succeed` | FAIL                       | `assert_not_equals: Expect session description to be defined got disallowed value undefined`                                  |
> | `Switching role from answerer to offerer after going back to stable state should succeed`                           | FAIL                       | `assert_not_equals: Expect session description to be defined got disallowed value undefined`                                  |
> | `onsignalingstatechange fires before setLocalDescription resolves`                                                  | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected "onsignalingstatechange;setLocalDescription;" but got "setLocalDescription;onsignalingstatechange;"` |
>
> #### Unstable results ##
>
> |                         Test                         |                              Subtest                               |          Results           |                                                            Messages                                                           |
> |------------------------------------------------------|--------------------------------------------------------------------|----------------------------|-------------------------------------------------------------------------------------------------------------------------------|
> | `/webrtc/RTCPeerConnection-setLocalDescription.html` | `onsignalingstatechange fires before setLocalDescription resolves` | **FAIL: 9/10, PASS: 1/10** | `assert_equals: expected "onsignalingstatechange;setLocalDescription;" but got "setLocalDescription;onsignalingstatechange;"` |
> 
> ::: Running tests in a loop 10 times : FAIL
> :::
> ::: Test verification FAIL
> :::

@henbos I don't know if this indicates a bug in Chromium or an issue with the test. Since we recently discussed a very similar test in gh-11347, I thought you might be in a better position to say. Would you mind taking a look?

**Comment by fippo** [comment]
is that still an issue in canary? this looks like https://bugs.chromium.org/p/chromium/issues/detail?id=848768

**Comment by jugglinmike** [comment]
I can't say because I'm unable to run Canary locally

**Comment by agouaillard-cosmo** [comment]
@soareschen can you take a look?

**Comment by dontcallmedom** [comment]
AFAICT it is no longer flaky, so closing the issue
