### ISSUE TITLE
[css-contain] Clarifying how contain:style subtree scoping affects ::before and ::after

### ISSUE THREAD

**Issue by muhammedyusuf-sermet** [web-platform-tests/wpt#11934]
As established in the spec (https://github.com/w3c/csswg-drafts/issues/2483), Style Containment suggests that content property is scoped to the subtree.

https://github.com/web-platform-tests/wpt/blob/828cbf6461e1b36ff5ff02310cb7d6749125b57c/css/css-contain/quote-scoping-001.html#L13-L28

Above test applies style containment to div element, and expects the quotes in the span element to be contained, and thus the quotes for div should not be affected by whatever is going on inside the contained part. However, both ::before and ::after elements of the div are in fact part of the subtree, meaning they are in contained part as well. So, the expected results of this test case should be A19, and it seems like it doesn't actually test the contain:style.

(CC @frivoal)

**Comment by muhammedyusuf-sermet** [comment]
Thank you for your response!

I agree that the change you suggested should solve this issue for all cases. Additionally, I think, we might need to update the expected result for below case;

quote-scoping-002: Expected value should be AZZ, I believe. Because the span element will read the past and continue from there, meaning it should complement A with Z.

**Comment by muhammedyusuf-sermet** [comment]
@frivoal Sorry about my late response. Of course, I'd be happy to. I just created a pull request for the changes we discussed here.

Thank you!

**Comment by frivoal** [comment]
fixed by https://github.com/web-platform-tests/wpt/pull/12417
