### ISSUE TITLE
Firefox failing due to disallowed network requests

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#12083]
At around 21:45 UTC today (according to results reported by TaskCluster), tasks involving Firefox Nightly began to fail consistently. Each reported errors describing disallowed network requests during startup, e.g.:

>     pid:206(B FATAL ERROR: Non-local network connections are disabled and a connection attempt to location.services.mozilla.com (52.16.107.9) was made.

I've also observed this problem in tasks triggered from a fork of WPT.

Previously, this type of failure has been explained by changes to the custom "preferences" file installed during the invocation of `wpt run` (see gh-10436 and gh-11679). In this case, however, there has been no new release that would explain the change.

@jgraham @ahal Do you have any thoughts about what's causing this?

**Comment by foolip** [comment]
I see it in https://tools.taskcluster.net/groups/RXr-LSSdTjanQwtClz9A9g/tasks/ETfGHaS4TYGYUASvaBrn8g/runs/0/logs/public%2Flogs%2Flive.log

There's "Installing browser" in the logs, but seemingly no way to tell what version was installed, so if this was caused by an update of Firefox Nightly, it seems we can't get a bisect range.

Will give this priority:roadmap on the assumption that it'll be blocking getting Taskcluster results into wpt.fyi.

**Comment by jugglinmike** [comment]
Another source of variation is the preferences file. From those logs:

>     Installing test prefs from https://hg.mozilla.org/mozilla-central/archive/tip.zip/testing/profiles/

This problem could be a result of changes to those files rather than (or in addition to) a new release of Nightly

**Comment by ahal** [comment]
It's not necessarily even a change to testing/profiles. Someone just has to add a new Firefox feature that pings the external network and then forget to disable said feature in CI. Though if anyone did this, they would cause wpt to fail in Mozilla's CI as well and get backed out. So I'm not sure why this is failing here :/

**Comment by jgraham** [comment]
This seems to be passing now, so I wonder if there's just a window where the downloaded prefs don't match the build.

**Comment by jugglinmike** [comment]
Yup: 105 Firefox TaskCluster tasks have completed since last night (EDT), and not one of them has reported a disallowed network access attempt.

> I wonder if there's just a window where the downloaded prefs don't match the build.

If that's correct, then we may see this on any given release of Nightly. How about we keep this issue open for a bit, in case it is a recurrent problem?

Thanks for the quick response, @foolip, @ahal, and @jgraham!

**Comment by jugglinmike** [comment]
I'm going to close this issue since there is nothing more to be done. It will serve the purpose of documentation just as well when closed, and we can re-open if the problem recurs.
