### ISSUE TITLE
Selectively testing commits to `master`

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#12116]
Today, we are running all of WPT in experimental releases of Chrome and Firefox for every commit to `master` via [the TaskCluster service](https://taskcluster.net). (We hope to gather up the results from these tasks for publication on https://wpt.fyi).

Moving forward, we would like to *also* run all of WPT in stable releases of those two browsers. This does not need to occur for every commit to `master`; only commits designated by [an external "announcer" system](https://docs.google.com/document/d/1hh6aRMvn5PgiXI_afJg3biS4iXeuWXhOXmt01EPFDG0/edit#heading=h.dgw388893y39) need to trigger these jobs.

**Comment by jugglinmike** [comment]
From [the TaskCluster documentation](https://docs.taskcluster.net/docs/reference/integrations/taskcluster-github/docs/taskcluster-yml-v1#tags)

> The core of Taskcluster-Github's operation is this: when an event occurs on Github, such as a push or a pull request, it loads .taskcluster.yml from the commit specified in the event, renders it with JSON-e, and then calls Queue.createTask for each of the specified tasks.

In order to trigger TaskCluster, we will need to perform some git operation in the GitHub-hosted repository. Tagging the desired commit seems like the most appropriate operation. Which part of the system ought to be responsible for that?

- The revision announcer could push tags whenever it identifies an "interesting" commit
- TravisCI (acting via a cron job) could query the revision announcer on a regular interval and push tags as necessary

There are trade-offs here, so I'm wondering what @jgraham and @mdittmer think.

**Comment by jugglinmike** [comment]
> Presumably merely tagging won't trigger the Taskcluster integration

It ought to, in theory. [The GitHub docs on the "push" event state that it is fired for tags](https://developer.github.com/webhooks/#events), and [TaskCluster's GitHub integration has code for that case](https://github.com/taskcluster/taskcluster-github/blob/017b9e0a98d72a5527a35ca4cd3dc3d9caf16583/src/api.js#L67).

[I've filed an issue to see if this use case is supported](https://github.com/taskcluster/taskcluster-github/issues/263), but your suggestion for an "announcement branch" is a more common scenario and more likely to be supported.

**Comment by jgraham** [comment]
Yeah, I think a tag or a branch would both work. If the revision announcer can just create an approproate ref of some sort, that seems like a perfect system; it will integrate with the current taskcluster scheduling with few changes.

If we wanted to do this earlier than that is ready, we could create an explicit decision task (this will eventually be requried for PRs anyway) and just have it check if e.g. the current PR is the first merged PR since midnight UTC using the GH API.

**Comment by foolip** [comment]
This was done in https://github.com/web-platform-tests/wpt/pull/12679.

**Comment by foolip** [comment]
I've filed https://github.com/web-platform-tests/wpt/issues/12907 about the branch maintenance.
