### ISSUE TITLE
Use the manifest for directory listing in wptserve

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#12224]
Looking at a directory like http://web-platform-tests.live/fetch/api/basic/, it's frustratingly difficult to get to the actual tests because of the `.any.js` files. Same for `.window.js` and http://web-platform-tests.live/dom/interfaces.html, which per the manifest should actually be two tests, see https://wpt.fyi/results/dom.

The fix for this could be a customized directory listing in wptserve, to use the manifest instead of the filesystem. Perhaps behind a flag list `--manifest-listing`, suggested by @lukebjerring.

@bmac @jugglinmike FYI.

**Comment by jgraham** [comment]
This is a duplicate of #7191 afaict except that it proposes a particular solution (which has various tradeoffs). I don't think we need two issues for this problem.
