### ISSUE TITLE
[HTTP/2.0] H2 Server tests can't be run on Travis

### ISSUE THREAD

**Issue by dhdavvie** [web-platform-tests/wpt#12256]
HTTP/2.0 requires the ALPN TLS extension, which in turn requires OpenSSL 1.0.2+. Unfortunately, Travis [does not currently support](https://docs.travis-ci.com/user/languages/python/) OpenSSL 1.0.2+ (under the 'Development releases support' heading), which means that the HTTP/2.0 server functional tests cannot be run on Travis currently. I don't really know what can be done about this, suggestions?

**Comment by jgraham** [comment]
So one obvious option is to gate running these tests on moving CI to TaskCluster where we get to choose our own environment.

**Comment by foolip** [comment]
@jugglinmike will be experimenting a bit with running the equivalent of ci_stability on Taskcluster. Mike, is there an issue for that?

**Comment by stephenmcgruer** [comment]
@foolip Can this be closed since we no longer use Travis, or is it still an issue with Taskcluster?

**Comment by jgraham** [comment]
Not an issue with TC, but we haven't updated the default configuration to actually enable H2 yet.

**Comment by stephenmcgruer** [comment]
Ack. I think that is covered by https://github.com/web-platform-tests/wpt/issues/13532, so closing this one. Please re-open if I'm wrong.
