### ISSUE TITLE
Compress the JSON output in Taskcluster tasks

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#12265]
For unknown reasons, Taskcluster disabled the [server-side auto compression](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-S3-origin) for the task artifacts (hosted on taskcluster-artifacts.net).

For each run we have tens of large JSON files; each of them is about tens of MB. Based on my observations in the results receiver, although the full report can take up to nearly 300MB, the gzipped form is only ~10MB (due to lots of duplicated strings). We can really benefit from compressing the artifacts.

In addition to performance gains, compressing the reports will also give me a much larger safety margin against various AppEngine runtime limits in the results receiver (e.g. max fetch size, timeout, ...). It's much easier to change the task definition to compress the output than to hack around the limits using async queues etc.

Again, this is mostly about `wpt_report.json`. I can either compress the report in place, or produce another compressed copy of the report. I'll try the former first as I'll probably be the only consumer of these artifacts in the near future, unless anyone objects my PR :)

**Comment by jgraham** [comment]
@djmitche Do we know why taskcluster isn't compressing these files? I thought (inaccurately) that certail file types were automatically compressed (maybe I'm thinking of the older blobber infrastructure).

**Comment by jgraham** [comment]
Looks like we are automatically compressing logs bug not .json files.

**Comment by djmitche** [comment]
Sorry for the late answer!  I think the different workers work differently.  It looks like docker-worker doesn't compress anything but the logs, as you've noticed.  So this isn't a change.  I don't think we changed anything in the cloudfront configuration, but I'm less confident about that one.  From that link, it doesn't look like there's actually anything to configure in CloudFront -- it just does this automatically when the relevant conditions apply.

I think that unless there's an expectation that HTTP client libraries (other than curl) will automatically decompress these files, it's probably best to compress the artifacts themselves, and give them a suitable filename (.bz2, .zstd, etc.) to make their content clear.
