### ISSUE TITLE
xhr/overridemimetype-unsent-state-force-shiftjis is now at odds with the XHR spec.

### ISSUE THREAD

**Issue by wisniewskit** [web-platform-tests/wpt#12289]
With the recent overrideMimeType changes, the WPT xhr/overridemimetype-unsent-state-force-shiftjis is now invalid (since the mimetype override is cleared as the XHR is opened in step 12).

I'm not sure if this means that the spec is now no longer web-compatible, however.

**Comment by foolip** [comment]
@annevk

**Comment by annevk** [comment]
Sigh, I guess that's why we never cleared `overrideMimeType` state? Does any implementation follow the specification? I thought at least Edge did.

**Comment by foolip** [comment]
https://wpt.fyi/results/xhr/overridemimetype-unsent-state-force-shiftjis.htm?labels=experimental isn't too illuminating, but does suggest *some* difference between Edge and the others.

**Comment by annevk** [comment]
I verified that Edge indeed behaves this way, but in retrospect it seems better to align with the other browsers, especially given the situation on mobile. I'll create some PRs to fix the tests and specification.

**Comment by annevk** [comment]
PRs created.
