### ISSUE TITLE
contain-size-012.html legitimately fails if antialiased serifs are clipped by its `overflow:hidden`

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt#12362]
The test [contain-size-012.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-012.html) fails on Firefox for Windows, with the only difference being on the left fringes of serifs on the "P" of "Pass", as reported here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1474848

I think this is a test bug -- the testcase has the word "Pass" wrapped in `overflow:hidden`, and it looks like the font happens to have serifs which create antialiased ink-overflow off the left side of the content box, and those antialiased serifs get correctly clipped by the `overflow:hidden` wrapper.  In contrast, the reference case doesn't have `overflow:hidden` so nothing is clipped.

So: the test's expectations of pixel-for-pixel accuracy are incorrect here. CC test-author @mrego

**Comment by dholbert** [comment]
Here's a screenshot with the 2 mismatching pixels highlighted in red boxes (showing that they're on the left edge of the "P" serifs):
![screenshot of failure in Firefox's reftest-analyzer](https://user-images.githubusercontent.com/426803/43863310-2c4bbd3e-9b11-11e8-9563-c65919549447.png)

And here's a screenshot of the zoomed-in pixel grid (from reftest analyzer), focusing on the upper mismatching pixel (it's the center pixel of the grid):
![reftest-failure-zoomed](https://user-images.githubusercontent.com/426803/43863459-954c3fa2-9b11-11e8-988a-1f43d4eb13da.png)

As you can barely see, it's white in the testcase (shown in upper-left half of the pixel) vs. faint yellow in the reference case (shown in bottom-right of the pixel).  rgb values are displayed alongside, too.  It seems pretty clearly an antialiased fringe, which is correctly clipped by `overflow:hidden` in the testcase.

**Comment by mrego** [comment]
I guess the simplest solution is to use a new reference that has `overflow: hidden`.
However I'm wondering if this don't affect other tests that has `overflow: hidden` too: contain-size-001.html, contain-size-002.html, contain-size-003.html, contain-size-004.html, contain-size-005.html, contain-size-006.html, contain-size-007.html, contain-size-008.html, contain-size-009.html, contain-size-010.html and contain-size-012.html.

@dholbert could you check if you have simliar issues for those or not? Thanks.

**Comment by dholbert** [comment]
You're right - I do get the failure for other tests, though not quite for the exact set you noted.  But I think there are good reasons that the other ones are unaffected, as noted in the bottom half of this post.

I see the same failure (with only those two antialiased pixels mismatching) on these tests:
* contain-size-001.html
* contain-size-002.html
* contain-size-003.html
* contain-size-004.html
* contain-size-006.html
* contain-size-012.html

For the other tests that you thought would be affected, I think it makes sense that they're not because:
* For contain-size-005.html: the reference case has `overflow:hidden` which performs the same clipping.
* For contain-size-007.html through 010.html: the testcase's `overflow:hidden` might not be having any effect at all (because the testcase is applying it to a table-row-group / table-row / table-[header/footer]-group, which I don't think is something that can be scrolled... at least, if I change `hidden` to `scroll`, I don't see any scrollbars show up, in Firefox or Chrome).

**Comment by dholbert** [comment]
(BTW, the test contain-size-011.html also fails in Firefox, but for [unrelated reasons, which is a real Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1482173 ).)

**Comment by dholbert** [comment]
So I guess I should be tagging @frivoal for thoughts here, since he wrote most of the tests that are failing here -- the first three being:
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-001.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-002.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-003.html

@frivoal: the testcase-only `overflow:hidden` usage is problematic in this family of tests right now, because there may be antialiased fringes on the characters in "PASS", which *legitimately* get clipped if you wrap them in an `overflow:hidden` box.  (see screenshots at the top of this issue)

It looks like you're using `overflow:hidden` as an easy way of detecting whether or not we collapsed away the size to 0 (because if we do that, then overflow:hidden will cause us to wrap and clip a 0-sized box, and PASS will be missing).  This makes sense, but it does have this problem with clipping antialiased fringes.

I assume we'd like to leave the existing "../reference/pass_if_pass_below.html" reference case  unmodified, since that's used quite a lot.  So perhaps we should create a copy of it which is exactly the same but with "PASS" having `position:absolute;overflow:hidden`?  That would be a more accurate/precise reference case for these `contain-size` testcases.

**Comment by mrego** [comment]
Ok, thank you very much for all the info I'm afraid I won't have the time to fix this soon as I'm going on holidays. But if once I'm back it's not fixed I'll take care of it.

**Comment by frivoal** [comment]
@dholbert Sorry for the slow follow up. I agree with your conclusions, so I've filed the https://github.com/web-platform-tests/wpt/pull/12485 PR to fix this. Review welcome.

**Comment by dholbert** [comment]
@frivoal Thank you! The changes look good to me, so I marked it as "accepted". (Not sure what the precise protocol is RE merging/etc -- I'll leave that to you or others.)
