### ISSUE TITLE
Image not found in CSS built test suite

### ISSUE THREAD

**Issue by mrego** [web-platform-tests/wpt#12371]
Hi @plinss, we have a css-containt test that fails to load the image in the built test suite:
http://test.csswg.org/harness/test/css-contain-1_dev/single/contain-size-013/format/html5/

It uses an image with the following absoulte path: `/css/support/60x60-red.png`.

Could we serve that folder `/css/support/` so we don't need to duplicate the image once more in a subfolder under `/css/css-contain/`.
There are 39 copies of that image right now in the repository.

Thanks!

**Comment by TalbotG** [comment]
+1

**Comment by plinss** [comment]
Done.

Sorry for the delay, I’ve been swamped with work.
