### ISSUE TITLE
parsing-testcommon.js not fetched

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#12419]
Many writing-modes tests fail just because functions being called are not fetched. Examples given:
http://test.csswg.org/harness/test/css-writing-modes-3_dev/direction-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/direction-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-combine-upright-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-combine-upright-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-orientation-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-orientation-valid/
and there are many more tests like those

**ReferenceError: Can't find variable: test_invalid_value**
can be read in the Message column and also be found in browsers' javascript consoles.

**Comment by foolip** [comment]
@ewilligers can you take a look?

**Comment by gsnedders** [comment]
This is due to them being in `resources` which the build system doesn't know about; they'd need to be in `support` for the build system to copy them around.

**Comment by TalbotG** [comment]
Philip,
How do you add a label to an issue? Do you have to be on a privilege list? As the reporter of this issue, I can not do this.

**Comment by gsnedders** [comment]
@TalbotG You have to have write access to the repo, IIRC.

**Comment by foolip** [comment]
@gsnedders I checked before and that's not the case, and probably wasn't the case at the time of the repo move either, since I pinged a lot of people who had write access then in issue 11568.

**Comment by gsnedders** [comment]
@foolip I mean to add labels to issues, which per https://help.github.com/articles/repository-permission-levels-for-an-organization/ needs write access.

**Comment by TalbotG** [comment]
Philip,

I received your invitation to join @web-platform-tests . Thank you. I should now be able to add label to issues that I report.

**Comment by foolip** [comment]
I'm not sure if org membership is enough, let me know if it doesn't work.

**Comment by TalbotG** [comment]
@ewilligers 
Eric, has this issue really been fixed? I ask because I still get a reference error:
**ReferenceError: test_invalid_value is not defined**
when I try the following 10 tests:

http://test.csswg.org/harness/test/css-writing-modes-3_dev/direction-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/direction-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-combine-upright-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-combine-upright-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-orientation-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/text-orientation-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/unicode-bidi-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/unicode-bidi-invalid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/writing-mode-valid/
http://test.csswg.org/harness/test/css-writing-modes-3_dev/writing-mode-invalid/

**Comment by ewilligers** [comment]
Links like the following show success:
http://test.csswg.org/harness/test/css-ui-3_dev/cursor-invalid/

My best guess for why the links show success for css-ui but not css-writing-modes:
The css-ui tests were initially checked in using support/ where the css-writing-modes tests were initially checked in using resources/

Now all the tests use /css/support so all the tests should be consistently passing or failing.

**Comment by gsnedders** [comment]
Looking at a random writing-modes tests linked above, it uses `<script src="resources/parsing-testcommon.js"></script>` which isn't what https://github.com/web-platform-tests/wpt/blob/master/css/css-writing-modes/parsing/text-orientation-valid.html uses. I presume the testsuite hasn't been rebuilt on the server?

**Comment by TalbotG** [comment]
> the testsuite hasn't been rebuilt on the server

That is also what I thought.

I do not know when the testsuite is supposed to be rebuilt or under which conditions.

**Comment by gsnedders** [comment]
@plinss ^^

**Comment by TalbotG** [comment]
**Several test suites have not been rebuilt** on the server:

The **last time** these 3 test suites

http://test.csswg.org/suites/css-backgrounds-3_dev/

http://test.csswg.org/suites/css-multicol-1_dev/

http://test.csswg.org/suites/css-writing-modes-3_dev/

have been built was **on August 7th** while the zip file (nightly-unstable.zip) is built on every day.

**Comment by plinss** [comment]
Normally the test suites get rebuilt every night around midnight pacific time. A while back I added the svg test suite to the build (by request) and apparently it's been breaking the build. I turned the svg test suite off until I have time to figure out why it's breaking the build.
