### ISSUE TITLE
Remove tests for XRStageBoundsPoint (optionally add historical tests)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#12445]
https://github.com/immersive-web/webxr/commit/f18249b3d34281d8c816d436099aa0a4c5b3501e removed XRStageBoundsPoint from the spec and https://github.com/web-platform-tests/wpt/pull/12442 removed the idlharness tests.

But there's still a test here:
https://github.com/web-platform-tests/wpt/blob/db532d16883ceb1909285b263948ffffc968f1fd/webxr/resources/webxr_util.js#L47

In addition to removing this, it would be good to add a historical.html which asserts that `self.XRStageBoundsPoint` doesn't exist, similar to this:
https://github.com/web-platform-tests/wpt/blob/master/speech-api/historical.html

**Comment by akansha2608** [comment]
Hi @foolip , i would like to work on it , can you please tell me how to proceed with this ?

Thanks

**Comment by foolip** [comment]
@akansha2608, sure you'll just have to remove that single line of code I linked. I think it's probably find to not add an historical test to check for the absence of `window.XRStageBoundsPoint` actually, because it looks like the interface didn't reach the stable version of any browser. (Checked using http://web-confluence.appspot.com/#!/)
