### ISSUE TITLE
write unit tests for handlers in tools/serve

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12452]
#12450 was caused by a very simple bug in tools/serve which would've trivially been catched by a simple unit test. We should have unit tests for all the handlers in tools/serve.

**Comment by qiuzhong** [comment]
If nobody takes this task, I'm interested in working on this. The following handles in `tools/serve/server.py` needs unit tests for testing coverage.
* HtmlWrapperHandler
* WorkersHandler
* WindowHandler
* AnyHtmlHandler
* SharedWorkersHandler
* ServiceWorkersHandler
* AnyWorkerHandler

**Comment by gsnedders** [comment]
@qiuzhong You're more than welcome to; I don't think any of us are going to get around to this soon!

**Comment by qiuzhong** [comment]
Since PR #14004 landed, can we close this issue?
