### ISSUE TITLE
Update Selenium Version

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt#12456]
The current selenium version installed by the virtualenv is not up to date.
With a newer version we can use excecute_cdp_cmd in executor selenium, which can be used with testdriver.

**Comment by foolip** [comment]
https://pypi.org/project/selenium/ says that the latest version is 3.14.0, and that's what tools/wptrunner/requirements_chrome.txt says too. Is there another place that's used for running Chrome?

**Comment by foolip** [comment]
Hmm, that package is Python bindings, maybe Selenium itself is elsewhere?

**Comment by kereliuk** [comment]
The Selenium version is indeed the most recent. I was mistaken by the RemoteWebdriver object being instantiated and I compared it to the Chrome Webdriver object :)
