### ISSUE TITLE
[css-contain] contain-style-counters-003-ref: "digit" to be replaced with "number"

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#12509]
@frivoal 

https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/reference/contain-style-counters-003-ref.html

at line 16:

(...) is the digit 20.

to replace with 

(...) is the number 20.

**Comment by frivoal** [comment]
fixed by 99c4f1dd3b4
