### ISSUE TITLE
[css-text] css3-text-line-break-baspglwj-096 does not fetch csstest-ascii-webfont.woff

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#12514]
http://test.csswg.org/suites/css-text-3_dev/nightly-unstable/html/css3-text-line-break-baspglwj-096.htm

Firefox 52.9.0 ESR and Chromium 68.0.3440.75 report respectively in their javascript console that
http://test.csswg.org/suites/css-text-3_dev/nightly-unstable/html/support/csstest-ascii-webfont.woff
is "404 Not Found (...) downloadable font: download failed" or "Failed to load resource: the server responded with a status of 404 (Not Found)"

The test is nevertheless sufficiently robust to report if `<div id="breakable">` broke into 2 line boxes, making offsetHeight greater than 30. In other words, the test may be reliable, trustworthy even if csstest-ascii-webfont.woff is not fetched and not loaded.

**Comment by frivoal** [comment]
This was fixed by 3750472d5f9cb9fbeca82d42b175a703a83959f6
