### ISSUE TITLE
CSSOMString needs to be defined but is gone from cssom.idl in reffy-reports

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#12515]
In https://github.com/w3c/csswg-drafts/commit/08860d449be888547017dcd88531fc68f6faf882 @tabatkins changed CSSOM so that both of the `CSSOMString` definitions in https://drafts.csswg.org/cssom/#cssomstring-type are on equal footing, and as a result neither of them gets treated by Reffy as an IDL block. This caused `typedef USVString CSSOMString` to disappear from cssom.idl in https://github.com/tidoust/reffy-reports/commit/bbbcccbfc13d9a628dee77a299f2a0632993d963.

When this change is brought in, every test that depends on cssom.idl will need to define CSSOMString in some other way.

Alternatively, we could add it as a known string type in webidl2.js itself, here:
https://github.com/w3c/webidl2.js/blob/91bba911e5a316b96a1b8d2cd8475ec0ccd703b5/lib/webidl2.js#L18

@saschanaz, might you have thoughts on the best way to proceed here?

**Comment by saschanaz** [comment]
The string type list in webidl2.js is [to process relavant Web IDL syntax](https://heycam.github.io/webidl/#prod-StringType), so probably it shouldn't be there.

```
StringType ::
    ByteString
    DOMString
    USVString
```

**Comment by foolip** [comment]
Unfortunately I'll have to agree that makes sense, so we can't push the problem down to webidl2.js.

I think what we should do is include `typedef DOMString CSSOMString` in cssom.idl manually somehow, because a separate cssom-CSSOMString.idl for just that would be annoying. I think we'll do it as part of https://github.com/foolip/wpt-idl-importer then.

**Comment by foolip** [comment]
Fixing this in the import step now: https://github.com/tidoust/reffy-reports/pull/29

**Comment by foolip** [comment]
Fixed now.
