### ISSUE TITLE
Selenium executor uses wrong viewport size for reftests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12578]
From executorselenium.py:

```
self.protocol.webdriver.set_window_size(600, 600)
```

This is the selenium.webdriver method, which sets the outer size of the browser window, and not the size of the viewport (including any scrollbars).

**Comment by mdittmer** [comment]
_friendly ping_ @gsnedders did 3b99513 get merged?

**Comment by gsnedders** [comment]
@mdittmer No, was waiting on responses from some on #7598 (need to ping them), and needs changes in Gecko to actually work everywhere.
