### ISSUE TITLE
./wpt check-stability fails with ManifestVersionMismatch if older MANIFEST.json is present

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#12635]
After https://github.com/web-platform-tests/wpt/pull/12563 some PRs have been failing like this when running check-stability:

```
+./wpt check-stability firefox:nightly --output-bytes 3145728 --metadata /home/travis/meta/ --install-fonts
browser_setup
INFO:/home/travis/build/web-platform-tests/wpt/tools/ci:# Firefox (nightly) #
INFO:/home/travis/build/web-platform-tests/wpt/tools/ci:# Firefox (nightly) #
INFO:/home/travis/build/web-platform-tests/wpt/tools/ci:Testing web-platform-tests at revision b5f28dc229d27f1599abe541d53890693249c6aa
INFO:/home/travis/build/web-platform-tests/wpt/tools/ci:Testing web-platform-tests at revision b5f28dc229d27f1599abe541d53890693249c6aa
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/home/travis/build/web-platform-tests/wpt/tools/wpt/wpt.py", line 132, in main
    rv = script(*args, **kwargs)
  File "/home/travis/build/web-platform-tests/wpt/tools/ci/check_stability.py", line 252, in run
    ignore_changes, skip_tests)
  File "/home/travis/build/web-platform-tests/wpt/tools/ci/check_stability.py", line 192, in get_changed_files
    manifest_path=manifest_path)
  File "/home/travis/build/web-platform-tests/wpt/tools/wpt/testfiles.py", line 212, in affected_testfiles
    wpt_manifest = load_manifest(manifest_path)
  File "/home/travis/build/web-platform-tests/wpt/tools/wpt/testfiles.py", line 193, in load
    wpt_manifest = manifest.load(wpt_root, manifest_path)
  File "/home/travis/build/web-platform-tests/wpt/tools/manifest/manifest.py", line 239, in load
    rv = Manifest.from_json(tests_root, json.load(f), types=types, meta_filters=meta_filters)
  File "/home/travis/build/web-platform-tests/wpt/tools/manifest/manifest.py", line 183, in from_json
    raise ManifestVersionMismatch
tools.manifest.manifest.ManifestVersionMismatch
```

(From https://travis-ci.org/web-platform-tests/wpt/jobs/419337736#L600)

The PRs are running code where `CURRENT_VERSION` is 5, so this must mean there's a MANIFEST.json on disk with version 4. Exactly how it got there I don't know, but it's a situation that should be handled. Steps to reproduce:
```
curl --location https://github.com/web-platform-tests/wpt/releases/download/merge_pr_12493/MANIFEST-7abda4e7227b65fba2452980d106ed5f11d51b2b.json.gz | gunzip > MANIFEST.json
./wpt check-stability firefox:nightly
```

(Works even if not on a branch with changes.)

https://github.com/web-platform-tests/wpt/issues/12589 is a similar issue, comment https://github.com/web-platform-tests/wpt/issues/12589#issuecomment-414987261 is relevant.

As discussed there, the fix ought to be making manifest.py handle this, so that `./wpt check-stability` has the same behavior as `./wpt run`.

**Comment by foolip** [comment]
@gsnedders I'll be OOO for the rest of the week, might you have time to look at this?

**Comment by foolip** [comment]
Known affected PRs:
https://github.com/web-platform-tests/wpt/pull/12530
https://github.com/web-platform-tests/wpt/pull/12542
https://github.com/web-platform-tests/wpt/pull/12555
https://github.com/web-platform-tests/wpt/pull/12556

I will try to get those merged without blocking on a fix for this.

**Comment by TimothyGu** [comment]
As I noted on IRC, purging the cache worked for the two PRs I tried it on.

**Comment by Hexcles** [comment]
I'm not sure if it's safe to purge all cache.

**Comment by foolip** [comment]
Can someone paste how to purge the cache, for others that need it? (This issue has repro steps so don't need to experiment on Travis.)

**Comment by Hexcles** [comment]
One can purge cache for an individual build, or drop all cache: https://travis-ci.org/web-platform-tests/wpt/caches

**Comment by TimothyGu** [comment]
> I'm not sure if it's safe to purge all cache.

What possible harm could it do other than longer build time?

**Comment by TimothyGu** [comment]
The Travis CI cache page doesn't display all PR branches however. If you need to get it working _now_, here's the equivalent `curl` command:

```sh
# the number of the pull request
PRID=12016
# you can find the token through any request to api.travis-ci.org in DevTools
YOUR_TOKEN=yourtoken

curl "https://api.travis-ci.org/repo/644577/caches?branch=PR.$PRID" \
  -X DELETE \
  -H 'Pragma: no-cache' \
  -H 'Origin: https://travis-ci.org' \
  -H 'Travis-API-Version: 3' \
  -H 'Cache-Control: no-cache' \
  -H "Authorization: token $YOUR_TOKEN"
```

I'm still pretty convinced that purging all cache is the right thing to do here.

**Comment by gsnedders** [comment]
Did someone purge all caches? The master cache is much smaller than it was a few days ago when we first started discussing this.

**Comment by Hexcles** [comment]
Yes. We did yesterday.

**Comment by gsnedders** [comment]
Is this therefore fixed and can be closed?

**Comment by TimothyGu** [comment]
Probably. Can always reopen if there are remaining issues.

**Comment by foolip** [comment]
The same will happen next time we bump the manifest version, so fixing this is still important, but not urgent.

**Comment by foolip** [comment]
@gsnedders, should this be assigned to you, do you plan to work on it? I'm going to assume not, so I'll downgrade priority, leaving assigned to you just in case.

**Comment by foolip** [comment]
`./wpt check-stability` is not even a command any longer, so this is stale. (Maybe the problem still exists, but I filed the issue and am not curious enough to find out.)
