### ISSUE TITLE
/infrastructure reftests fail in Firefox on macOS

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12699]
/infrastructure/reftest/reftest_match.html
/infrastructure/reftest/reftest_or_0.html
/infrastructure/reftest/reftest_wait_0.html

all fail on macOS locally, due to /infrastructure/reftest/green.html being rendered with a rounded corner in the bottom right (due to the OS window styling? why wouldn't it affect the other pages then, though?)

**Comment by gsnedders** [comment]
https://gist.githubusercontent.com/gsnedders/fadcc35d961b9958a2a4805fc194d03d/raw/a34283b2cc30f9d3cc1f83012678df704fcc3752/firefox.log is a log from running `/intrastructure`

**Comment by foolip** [comment]
In https://dev.azure.com/foolip/wpt/_build/results?buildId=150&view=logs I had them all passing in Firefox Nightly without doing anything in particular. @gsnedders, does it still fail for you?

**Comment by gsnedders** [comment]
I think it might be a HiDPI or hardware acceleration issue?

**Comment by mdittmer** [comment]
@gsnedders you still seeing this or should it be closed?

**Comment by gsnedders** [comment]
WFM.
