### ISSUE TITLE
WindowsError does not exist on non-Windows

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#12693]
https://github.com/web-platform-tests/wpt/pull/9652 added an `except WindowsError` clause, but if there's an error raised in the `try` block on non-Windows, you get

```
  File "/tools/manifest/vcs.py", line 19, in git
    except WindowsError:
NameError: global name 'WindowsError' is not defined
```

CC @csnardi

**Comment by gsnedders** [comment]
Oh I thought I'd fixed this. Obviously not. :(
