### ISSUE TITLE
Update epochs/* branch from reliable infrastructure

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#12907]
In [Run stable and beta releases on TaskCluster](https://github.com/web-platform-tests/wpt/pull/12679) epochs/daily and epochs/weekly branches are used to trigger runs. These are created by https://github.com/foolip/wpt-epochs-branch-updater and that script is run on a loop on my workstation.

That branch management should either be made part of https://github.com/web-platform-tests/wpt.fyi/tree/master/revisions or the glue service should be hosted somewhere reliable.

@mdittmer

**Comment by foolip** [comment]
Work tracked in these two issues:
https://github.com/web-platform-tests/wpt.fyi/issues/551
https://github.com/web-platform-tests/wpt-pr-bot/issues/41

**Comment by lukebjerring** [comment]
I believe the pr-bot work's been done - @mdittmer, status update?

**Comment by mdittmer** [comment]
This work was completed by https://github.com/web-platform-tests/wpt-pr-bot/pull/44
