### ISSUE TITLE
tools/wpt testsuite exceptionally slow on Windows

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#12934]
This is largely down to https://github.com/web-platform-tests/wpt/issues/11386; it could possibly be worked around by using a more up-to-date revision after #12182 landed which means in the common-case we don't actually read all the files.

**Comment by foolip** [comment]
@gsnedders, is this a necessary part of https://github.com/web-platform-tests/wpt/issues/13342, or why priority:roadmap?

**Comment by gsnedders** [comment]
It's technically not necessary, *but* if we actually want decent test coverage (versus skipping large amounts) it is needed.

**Comment by jgraham** [comment]
We could also port the caches from #12553 to the case where we use git hashes. In particular the mtime cache still makes sense in that case and will likely be faster than starting the git binary on windows. But that would need to be tested empircally of course.

**Comment by Hexcles** [comment]
I think #14924 should largely alleviate this issue? Tentatively closing this, but feel free to reopen.
