### ISSUE TITLE
WPT CLI: --headless / --no-headless

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13005]
Spinoff from https://github.com/web-platform-tests/results-collection/issues/603.

As a user of `./wpt run`, it would be great to be able to not have a lot of windows be created, as it makes it hard to do other work while the tests are running.

I would propose that `--headless` is the eventual default with `--no-headless` as the opt-out, but having the ability to enable it is the first step.

**Comment by Hexcles** [comment]
Or `Xvfb`

**Comment by jugglinmike** [comment]
Resolved via gh-13076

**Comment by foolip** [comment]
If it wasn't clear from this issue and linked issues, we currently don't use headless, `--no-headless` is passed in tools/ci/taskcluster-run.py and in the [Buildbot setup](https://github.com/web-platform-tests/results-collection/blob/c9bcecc592404f5cb0a6dd31163e9e9e6d0ec7c4/src/master/wpt_run_step.py#L102).

But it sounds like if we want to test using headless, we have command line arguments that make that possible.

**Comment by whimboo** [comment]
Oh ok. Then some other environmental settings might cause those problems. Sorry for bothering you on this issue then, and thanks for clarifying!

**Comment by foolip** [comment]
@jgraham can you help @whimboo find log files? Maybe we're not logging enough, or linking them clearly enough?

@gsnedders do you know the screen resolution and browser size we use in all cases? Is it only 600x600 as the browser size which we set or reftests, and everything else is haphazard?

**Comment by jgraham** [comment]
The logs are https://tools.taskcluster.net/groups/Zr_bW3aPRDKtdc48BidQ7Q

**Comment by whimboo** [comment]
Ok, sorry for the noise here. This will clearly be the last comment to close out the discussion. Given that xvfb is used to run the wdspec tests, I finally know why we are failing. Currently I'm reworking all the window manipulation commands, which should hopefully make us be green for the upcoming Firefox 65 release.
