### ISSUE TITLE
Include date of Firefox Nightly in wpt_report.json

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13052]
The Firefox Nightly version will be something like "64.0a1" but that doesn't change for each build. In the UI the date is included.

@jgraham, is there any way we could get this information?

**Comment by jgraham** [comment]
Yeah, [mozversion](https://firefox-source-docs.mozilla.org/mozbase/mozversion.html) can get it from the application.ini file, assuming we know the path to the actual firefox binary (which we do in our setup, but don't in general e.g. if `firefox` is actually a shell script)

**Comment by foolip** [comment]
@Hexcles, I realize there might be an existing and somewhat serious problem here. If the results receiver uses the version to reject cases where the different chunks got different versions of the browsers, it's possible we have already accepted runs that are for a mix of browser version. WDYT, what's the priority of fixing this?

**Comment by foolip** [comment]
Yep, that's the problem I meant.

**Comment by mdittmer** [comment]
_Ping from your friendly neighbourhood ecosystem infra rotation_

If this is `priority:roadmap` should it have an assignee?

**Comment by foolip** [comment]
@jgraham do you reckon this is an easy fix?

**Comment by foolip** [comment]
This issue is just about "get the date into the file", then we can start least know when we're getting a mix of browser versions.

**Comment by lukebjerring** [comment]
IIRC, https://github.com/web-platform-tests/wpt.fyi/pull/1068 covered being more lenient with inconsistent version (build).

**Comment by foolip** [comment]
With `browser_build_id` and `browser_changeset` now included in the reports for Firefox I consider this fixed. We could detect runs with mixed versions in wpt.fyi using this.
