### ISSUE TITLE
wptrunner sometimes falsely reports "Servers failed to start" and fails to start

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#13081]
Symptoms: sometimes after starting `wptrunner` using `./wpt run ...`, the process gets stuck here:

```
 0:20.04 INFO Starting http server on 127.0.0.1:8000
 0:20.04 INFO Starting http server on 127.0.0.1:8001
 0:20.06 INFO Starting https server on 127.0.0.1:8443
```

And after a short while the following exception is raised:

```
 0:50.20 INFO Closing logging queue
 0:50.20 INFO queue closed
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/usr/local/google/home/robertma/github/wpt/tools/wpt/wpt.py", line 129, in main
    rv = script(*args, **kwargs)
  File "/usr/local/google/home/robertma/github/wpt/tools/wpt/run.py", line 505, in run
    rv = run_single(venv, **kwargs) > 0
  File "/usr/local/google/home/robertma/github/wpt/tools/wpt/run.py", line 512, in run_single
    return wptrunner.start(**kwargs)
  File "/usr/local/google/home/robertma/github/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 326, in start
    return not run_tests(**kwargs)
  File "/usr/local/google/home/robertma/github/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 186, in run_tests
    test_environment.ensure_started()
  File "/usr/local/google/home/robertma/github/wpt/tools/wptrunner/wptrunner/environment.py", line 207, in ensure_started
    ", ".join("%s:%s" % item for item in failed))
EnvironmentError: Servers failed to start: 127.0.0.1:8889
```

However, a manual check (before the process exits) shows that the server is up and running on 8889.

I've double checked there are no processes listening on these ports before starting `./wpt run`. The failure seems flaky, only happening around half of the time. And I've only seen failures for ports 8888 & 8889 so far (ws & wss), but I'm not sure if it's a coincidence.

The failure was also observed on Travis: https://travis-ci.org/web-platform-tests/wpt/jobs/430614161

**Comment by jdm** [comment]
This sounds like what we've been dealing with in https://github.com/servo/servo/issues/20734, which we tracked down to a locked mutex in https://github.com/servo/servo/pull/21741. We were planning on upstreaming that change once we've kicked the tires in servo and gecko for a bit.

**Comment by jdm** [comment]
That being said, we have not observed the failure at all in Servo since merging that change, so we're pretty optimistic at this point.

**Comment by Hexcles** [comment]
Interesting. Thanks, @jdm !

The issue you linked to doesn't quite fit the symptoms I observed. In my case, the servers seemed to be alive and respond just fine, whereas the issue you linked to seemed to be non-responsiveness (possibly because of deadlocks).

That said, this is a flaky failure, and I've only managed to reproduce a couple times and my observation might not be totally accurate.

**Comment by foolip** [comment]
@Hexcles, https://github.com/web-platform-tests/wpt/pull/13091 and follow-ups have been merged. Can you try to repro this again? If it does repro, can you set a priority?

**Comment by Hexcles** [comment]
I just tried a dozen times locally and haven't been able to reproduce the issue. The reliability of test startup is at least drastically improved, if not completely fixed. Closing the issue.
