### ISSUE TITLE
http://w3c-test.org/submissions/ not working

### ISSUE THREAD

**Issue by GPHemsley** [web-platform-tests/wpt#13180]
It looks like the automatic postings of pull requests to http://w3c-test.org/submissions/ is no longer working. The last listing there is #11169, which is from May 25, 2018.

Could this be fallout from the project move?

**Comment by foolip** [comment]
@sideshowbarker, do you think this could be fallout from the move? Does w3c-test:mirror still work?

**Comment by gsnedders** [comment]
This seems to be working again?
