### ISSUE TITLE
Duplicate file name for contain-size-fieldset-001-ref.html

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#13222]
https://github.com/web-platform-tests/wpt/pull/13198 introduced a reference file that duplicates one in https://github.com/web-platform-tests/wpt/tree/master/css/vendor-imports/mozilla/mozilla-central-reftests/contain. This makes the lint complain, and wasn't caught in #13198. This is blocking Servo's nightly sync process, and is becoming tiresome to clean up when it keeps happening.

**Comment by gsnedders** [comment]
Caused by #9171.
