### ISSUE TITLE
[css-contain] Incorrect tests: contain:size does not suppress baselines

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#13252]
@mrego These 3 tests are incorrect, because they assume that `contain:size` affects baseline alignements, but that't not true.

The spec says this:

> When calculating the size of the containing element, it must be treated as having no contents.
> [...] 
> Then, its contents must then be laid out into the containing element’s resolved size.
> 
> Note: size containment does not suppress baseline alignment. See layout containment for that.

https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-button-001.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-flexbox-001.html
https://github.com/web-platform-tests/wpt/blob/master/css/css-contain/contain-size-grid-001.html

**Comment by frivoal** [comment]
They were introduced by this commit: https://github.com/web-platform-tests/wpt/commit/af6293eecd7db39b8f696be1b051f329db7cc87f

**Comment by mrego** [comment]
I'll fix this in Chromium directly while updating the code to the new behavior.
PR #13254 contains the changes on the tests and it'll be automatically merged, once the Chromium change is approved and landed.

**Comment by mrego** [comment]
This should be fixed now by #13254.
