### ISSUE TITLE
"No Taskcluster jobs started for this pull request" comments are noisy

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13280]
All PRs submitted by people who are not members on the web-platform-tests org are getting comments on their PRs like this one:
https://github.com/web-platform-tests/wpt/pull/13275#issuecomment-425749320

One comments is posted per failure. This is noisy, and also doesn't tell people what they need to do to resolve the issue.

@jgraham, do we need to restrict Taskcluster to collaborators? If we do, won't we have to invite people to the org *before* the get their first PR merged in order to spot regressions?

**Comment by jgraham** [comment]
Per https://docs.taskcluster.net/docs/manual/using/github we can set up the permissions to allow anyone to start PR tasks. What it doesn't say at least on the main page is how to do that :)

**Comment by foolip** [comment]
Using https://tools.taskcluster.net/quickstart/ it seems like "allowPullRequests: public" is how. I'll send a PR.

**Comment by foolip** [comment]
Send https://github.com/web-platform-tests/wpt/pull/13282.
