### ISSUE TITLE
Re-enable Windows CI

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#13342]
We should get CI running on Windows again.

The first stage of this should be getting all the tools/ unit tests and infrastructure/ tests running, even if we have to mark large amounts of these as XFAIL.

**Comment by foolip** [comment]
Plan A is to use Azure Pipelines. Basic tests can be run on Windows Server, but Windows 10 would be needed to test that Edge works.

**Comment by gsnedders** [comment]
And to be clear, for those not following along with what I say in multiple different places: I don't view testing Edge so high priority, because the majority of Windows-specific bugs we've historically had have been in the lower level code than the browser-specific code.

**Comment by gsnedders** [comment]
Mostly been waiting on #14300 getting something running on Windows. That's mostly working now, so I guess we should try basing the work here off of that, and just running things we can on Windows Server on the MS hosted agents.

**Comment by lukebjerring** [comment]
@gsnedders - any progress on this?
