### ISSUE TITLE
Add tests for getSynchronizationSources for both audio and video.

### ISSUE THREAD

**Issue by henbos** [web-platform-tests/wpt#13364]
Video was added here: https://github.com/w3c/webrtc-pc/pull/1986.
getSSRCs is definitely testable. getCSRCs requires a media server and is not testable in WPT.

**Comment by dontcallmedom** [comment]
https://github.com/web-platform-tests/wpt/blob/master/webrtc/RTCRtpReceiver-getSynchronizationSources.https.html now handles video, so closing
