### ISSUE TITLE
Avoid window.open in the test runner

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#13418]
From https://github.com/web-platform-tests/wpt/pull/12885#issuecomment-419240394 (@domenic, @TimothyGu).

See also discussion in https://github.com/web-platform-tests/wpt/issues/10398#issuecomment-427525644.

Note this is complicated for executors using WebDriver by the lack of any window management (beyond `close`) in WebDriver; see https://github.com/w3c/webdriver/issues/1138.

**Comment by foolip** [comment]
Reopening as https://github.com/web-platform-tests/wpt/pull/14496 was merged.
