### ISSUE TITLE
Circleci is failing due to missing configuration

### ISSUE THREAD

**Issue by progers** [web-platform-tests/wpt#13454]
I have my first WPT pull request: https://github.com/web-platform-tests/wpt/pull/13441

It is failing circleci:
https://circleci.com/gh/web-platform-tests/wpt/8?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Here's the error:
```
#!/bin/sh -eo pipefail
# Missing Configuration
false
Exited with code 1
```

I think this error is in the circleci integration and not with the patch.

**Comment by foolip** [comment]
Sorry about that, I've commented in all affected PRs about my mishap, and that the failure can be ignored. If you touch that PR in any way that retrigger checks, then CircleCI will not show up. It's also fine to merge with the failing check in place, as it's not blocking.
