### ISSUE TITLE
Stability checker causing Travis CI to time out

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#13513]
See https://travis-ci.org/web-platform-tests/wpt/builds/440987637

**Comment by foolip** [comment]
This is different from https://github.com/web-platform-tests/wpt/issues/7660 in that the job only took 16 minutes, but it timed out due to no output. From the end of the logs:
```
INFO:/home/travis/build/web-platform-tests/wpt/tools/ci:Starting tests


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

@jgraham, can you investigate?

**Comment by jgraham** [comment]
I wonder if this is related to the change in default formatter; I tried to ensure that the PR jobs were unaffected, but maybe missed this one.
