### ISSUE TITLE
Support async setup()

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13522]
https://github.com/web-platform-tests/wpt/issues/7188 added async cleanup for testharness.js.

There are also cases where it makes sense to delay the start of tests:
 - `idl_test` loads resources from interfaces/ in a dummy "idl_test setup" test
 - https://github.com/web-platform-tests/wpt/issues/13192 depends on webfonts being loaded
 - many tests wait for the window load event

For such cases, to avoid either waiting in every test individually, or to have an initial dummy test, it would be useful to let `setup()` take promise-vending functions, and delay the start of the tests until it has resolved.

@jugglinmike

**Comment by jugglinmike** [comment]
@foolip has mentioned two strategies for asynchronous test setup. The first, "waiting in every test individually" works for `async_test`:

```js
const whenReady = someAsynchronousCode();

async_test((t) => {
  whenReady.then(t.step_func(() => {
    // conformance test goes here
  }, t.unreached_func('Setup failed'));
});
```

The second, "have an initial dummy test" relies on serial sub-test execution and therefore only works for `promise_test`:

```js
promise_test(someAsynchronousCode, 'set up, please ignore');

promise_test(() => {
  // conformance test goes here
});
```

There's a third alternative for test authors looking to use asynchronous setup logic today, one that works for both APIs and does not require repetition: [the `explicit_done` setting](https://github.com/web-platform-tests/wpt/blob/master/docs/_writing-tests/testharness-api.md#setup).

```js
setup({
  explicit_done: true
});

someAsynchronousCode()
  .then(() => {
    async_test((t) => {
      // conformance test goes here
    });

    done();
  }, (err) => test(() => { throw err; }));
```

Having API-level support would be still nice, though, since the third alternative is only slightly less annoying.

**Comment by foolip** [comment]
Ah, right, I didn't consider the third option, that might come in handy to fix https://github.com/web-platform-tests/wpt/issues/13192.

If we made this a built-in behavior of setup(), then we would still have to do something non-obvious for async_test that are created while the async setup is happening, either fall over with a harness error, or just not invoke the first step until later. Neither would be great, so perhaps there's a third way here too? :)

**Comment by jugglinmike** [comment]
My cold robot-like solution would be to disallow `async_test` whenever a setup function returned a promise.

**Comment by foolip** [comment]
Right, that's be the "fall over with a harness error" option I had in mind.

**Comment by foolip** [comment]
Discussed at TPAC: https://docs.google.com/document/d/1_d2xUBgNn6nmiIXM6m9zSLjzYhvDS4LMrmgoxMQJKuU/edit#bookmark=id.otucb52ckvsx

If we call it `promise_setup` and disallow running any `test` or `async_test` afterwards, this would work.

**Comment by foolip** [comment]
But I'd still like to keep the option of just calling it `setup()` on the table, and having the behavior depend on the return value.

**Comment by foolip** [comment]
I have an action item to prepare an RFC for this. Having had a good night's sleep after TPAC, I'm not so much a fan of what I suggested in https://github.com/web-platform-tests/wpt/issues/13522#issuecomment-532103652. Underlying it is a notion that we could eventually do the same with `test`, but that's not very plausible, rather that's effectively an idea to rename `test` to `sync_test` and `promise_test` to `test`. I won't pursue that, but I think such an undertaking would be the right time to name this something other than `promise_setup`.

**Comment by jugglinmike** [comment]
We can see the need for this feature in a handful of tests related to service workers which define a subtest titled, "initialize global state" (or put differently, "setup"):

    $ git grep -li 'initialize global state'
    fetch/api/request/destination/fetch-destination-iframe.https.html
    fetch/api/request/destination/fetch-destination-no-load-event.https.html
    fetch/api/request/destination/fetch-destination-prefetch.https.html
    fetch/api/request/destination/fetch-destination-worker.https.html
    fetch/api/request/destination/fetch-destination.https.html
    service-workers/service-worker/embed-and-object-are-not-intercepted.https.html
    service-workers/service-worker/fetch-event-redirect.https.html
    service-workers/service-worker/fetch-request-fallback.https.html
    service-workers/service-worker/fetch-request-xhr.https.html
    service-workers/service-worker/fetch-response-taint.https.html
    service-workers/service-worker/import-scripts-updated-flag.https.html
    service-workers/service-worker/multipart-image.https.html
    service-workers/service-worker/navigation-redirect.https.html
    service-workers/service-worker/redirected-response.https.html
    service-workers/service-worker/referrer-policy-header.https.html
    service-workers/service-worker/resources/fetch-canvas-tainting-tests.js
    service-workers/service-worker/respond-with-body-accessed-response.https.html
    service-workers/service-worker/update-missing-import-scripts.https.html
    service-workers/service-worker/webvtt-cross-origin.https.html
    service-workers/service-worker/worker-interception-redirect.https.html

**Comment by jugglinmike** [comment]
Here's a WPT RFC for this feature https://github.com/web-platform-tests/rfcs/pull/32

**Comment by stephenmcgruer** [comment]
Is this done, given https://github.com/web-platform-tests/rfcs/pull/32 is merged and https://github.com/web-platform-tests/wpt/pull/20187 landed? Or is this issue meant to cover more?

@foolip

**Comment by foolip** [comment]
When I filed this I wasn't clear on the details of how this would look, but yes, `promise_setup` resolved this.
