### ISSUE TITLE
css-flexbox-row-* tests fail on Chrome in Buildbot+Taskcluster

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#13539]
These four tests are failing in Chrome only, and only in wpt's infrastructure, not in Chromium:
* /css/css-flexbox/css-flexbox-row-reverse-wrap-reverse.html
* /css/css-flexbox/css-flexbox-row-reverse-wrap.html
* /css/css-flexbox/css-flexbox-row-wrap-reverse.html
* /css/css-flexbox/css-flexbox-row-wrap.html

Screenshots in https://github.com/web-platform-tests/wpt/issues/13539#issuecomment-430803695

Edit: original description before screenshots were found:
<details>
This can be seen by clicking "show history" in these two views:

https://wpt.fyi/results/css/css-flexbox/css-flexbox-row-reverse-wrap-reverse.html?product=chrome[buildbot,experimental]
![image](https://user-images.githubusercontent.com/498917/47008069-dca5e200-d139-11e8-8b5b-3dd07fbf4c38.png)

https://wpt.fyi/results/css/css-flexbox/css-flexbox-row-reverse-wrap-reverse.html?product=chrome[taskcluster,experimental]
![image](https://user-images.githubusercontent.com/498917/47008008-b4b67e80-d139-11e8-9f7d-4b41bbcd1704.png)

Although, the pattern is the same, so that's very suspicious. @mdittmer am I seeing different things interleaved? Is this https://github.com/web-platform-tests/wpt.fyi/issues/394?

Understanding the failure is really blocked on https://github.com/web-platform-tests/wpt.fyi/issues/57.
</details>

**Comment by foolip** [comment]
Context: [web-platform-tests that fail only in Chrome (from wpt.fyi data)](https://groups.google.com/a/chromium.org/d/msg/blink-dev/Met12DiCxVE/sQfo5UHQBgAJ) thread on blink-dev.

**Comment by foolip** [comment]
In that same thread, after the discovery of a nice accident, we can actually view the results:
https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml#logurl=https://taskcluster-artifacts.net/cHFVBzPHR1ylzr6MpVl7_A/0/public/results/log_tbpl.log

Here's the test and ref image extracted:
![image](https://user-images.githubusercontent.com/498917/47118442-89ca4880-d267-11e8-859c-4e17d8157789.png)
![image](https://user-images.githubusercontent.com/498917/47118471-a23a6300-d267-11e8-9728-324ce1b9bc83.png)

I'm not sure what this means without debugging the tests. There are however four tests with this same failure mode/pattern:
/css/css-flexbox/css-flexbox-row-reverse-wrap-reverse.html
/css/css-flexbox/css-flexbox-row-reverse-wrap.html
/css/css-flexbox/css-flexbox-row-wrap-reverse.html
/css/css-flexbox/css-flexbox-row-wrap.html

The failures don't happen in Chromium. I'll update the bug description to match.

@cbiesinger if you have any ideas about what might be causing this it'd be much appreciated.

**Comment by gsnedders** [comment]
Is there any reason why these tests are using the full-width glyphs anyway? Just for the sake of deterministic character widths?

**Comment by davidsgrogan** [comment]
I rewrote these to not use any text. They pass everywhere now. https://wpt.fyi/results/css/css-flexbox?label=master&label=experimental&aligned&q=css-flexbox-row

**Comment by foolip** [comment]
Thanks @davidsgrogan!
