### ISSUE TITLE
Single-byte encoding tests time out in Firefox

### ISSUE THREAD

**Issue by hsivonen** [web-platform-tests/wpt#13557]
`textdecoder-fatal-single-byte.*.html` tests time out in the Firefox runs reported at wpt.fyi. It appears to me that the underlying functionality being tested should pass the tests, so it would be good to adjust the harness not to time out.

**Comment by foolip** [comment]
Is the test just a bit slow perhaps? @annevk

**Comment by stephenmcgruer** [comment]
There's still a crazy number of subtests there (~7k), but looking at wpt.fyi it looks like these no longer time out on Firefox. Please re-open if I'm wrong!
