### ISSUE TITLE
[css-text] css/css-text/text-indent/text-indent-percentage-001.xht checks for deprecated behavior

### ISSUE THREAD

**Issue by szager-chromium** [web-platform-tests/wpt#13581]
This commit:

https://github.com/web-platform-tests/wpt/pull/11373

... added tests to verify the newly-spec'ed behavior, but it didn't update the pre-existing test that verifies the deprecated behavior.

**Comment by szager-chromium** [comment]
Also this test:

external/wpt/css/CSS2/text/text-indent-percent-001.xht

**Comment by emilio** [comment]
FWIW @MatsPalmgren is fixing these in https://bugzilla.mozilla.org/show_bug.cgi?id=1453298.

**Comment by frivoal** [comment]
This is handled by PR #13721

**Comment by faceless2** [comment]
wpt/css/CSS2/text/text-indent-011.xht
wpt/css/CSS2/text/text-indent-103.xht
wpt/css/CSS2/text/text-indent-104.xht
wpt/css/CSS2/css1/c547-indent-001.xht

Also use the old definition for percentages and need updating.
