### ISSUE TITLE
WorkerGlobalScope is checked in Picture-in-Picture idlharness tests

### ISSUE THREAD

**Issue by beaufortfrancois** [web-platform-tests/wpt#13598]
According to https://wpt.fyi/results/picture-in-picture/idlharness.window.html?label=stable&aligned=true, it looks like `WorkerGlobalScope` interface is checked. This seems like a bug as the Picture-in-Picture API is not exposed to workers.

```
WorkerGlobalScope interface: existence and properties of interface object	
```

cc: @lukebjerring

**Comment by lukebjerring** [comment]
Will take a look when I get a chance - likely the `add_dependency_idls` making a mistake.
cc @foolip who is also and `idlharness` wizard.

**Comment by lukebjerring** [comment]
OK, so this is because all dependencies are considered equal.
Consider us A having defined `A : B`, and B is defined in another file. 

    interface B {};
    B includes Z;
    C includes Z;

The code knows B is a dep, sees `B includes Z` and says `Z` is now a dependency.
Then it sees `C`, which includes dep `Z`, so `C` must be a dep too (wrong!)

**Comment by beaufortfrancois** [comment]
https://wpt.fyi/results/picture-in-picture/idlharness.window.html?products=chrome&label=experimental does not show `WorkerGlobalScope interface: existence and properties of interface object` anymore. I think we can close this issue.
