### ISSUE TITLE
WPT test runner links to http test instead of https tests

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#13591]
In the results table, the links generated for each test that is run seem to default to http://. It would be nice if, it the test is ".https.html", it correctly links to "http://".

**Comment by marcoscaceres** [comment]
To be clear, talking about: 
https://w3c-test.org/tools/runner/index.html

And:

<img width="861" alt="screenshot 2018-10-18 16 50 16" src="https://user-images.githubusercontent.com/870154/47133768-eaa06200-d2f5-11e8-8f93-8b25c682909a.png">

**Comment by foolip** [comment]
@marcoscaceres the in-browser runner isn't really well maintained. May I ask what you're using it for, if it's something we should support in `./wpt run` directly?

**Comment by marcoscaceres** [comment]
Until just before I filed this bug, we had an issue in Gecko where it was not possible to start other browsers from `./mach wpt`:
https://bugzilla.mozilla.org/show_bug.cgi?id=1500001

That's fixed now, tho I've not tried it yet. 

Further,  #6565 is preventing me from doing `./wpt run` still - so that's another thing that leads me to the online version.  

Additionally, it's challenging to get people to install WTP - and particularly super hard to get it running on mobile devices (obviously, it's not going to be installed on a phone, but you need a server somewhere to run whatever you can). For companies like Samsung, where they don't have a desktop browser, it's easier for me to send them a link with instructions for how to run a test suite.

**Comment by marcoscaceres** [comment]
(instructions for running on mobile devices would be awesome too - if anyone has done that. Particularly interested in running the marionette tests on mobile or on the Android SDK or iOS Simulator, so to get an accurate result set for mobile devices)

**Comment by foolip** [comment]
@Hexcles has run Chrome and UC on Android. Not clear if it still works, but docs here: https://web-platform-tests.org/running-tests/chrome_android.html

**Comment by Hexcles** [comment]
@jgraham do you know the status of marionette (or Gecko in general) on Android?

**Comment by marcoscaceres** [comment]
@foolip thanks for the link to the docs! Sorry for not spotting that.
