### ISSUE TITLE
htmlallcollection test fails when loaded directly

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#13625]
The test has a `<div id="log">` that comes _after_ the `<script>` that runs the tests.   That means that when logging is enabled (e.g. loading the test directly) testharness doesn't find the log container, since it hasn't been parsed yet when the test runs.  It then creates a new `<div id="log">` and inserts it into the DOM, which changes the contents of document.all and the test fails.  On the other hand, when running in a harness logging is typically turned off so none of this happens.

@foolip

**Comment by foolip** [comment]
Oh, now I understand, and this is a difference between running manually and understand automation that I was not aware of. I'm pretty sure I might have made this mistake elsewhere too, I guess one could look for it by check if two elements with `id=log` exist at the end of testing.

Context: https://groups.google.com/forum/m/#!topic/mozilla.dev.platform/LMnQq-yqbxg

**Comment by foolip** [comment]
This seems like the kind of mishap that might amuse or inspire @jugglinmike.

**Comment by bzbarsky** [comment]
Fwiw, I suspect  just moving the log container before the script and adjusting test expectations would work here, but I have not had a chance to verify that.

**Comment by foolip** [comment]
As I feared, the test depends on the number of divs in the document, and that's probably why the div is at the end in the first place. Putting it at the beginning affects most of the tests. @jgraham, is there a way to prevent the logging div from being created at all? I could rejig things to work with it, but presumably this isn't the only test that could react badly to a div being inserted...

**Comment by bzbarsky** [comment]
> Putting it at the beginning affects most of the tests.

I would put it right before the `<script>`.  That will only affect a few of the tests; you can find the relevant ones by searching for "23"  and "24" in the test.
