### ISSUE TITLE
external/wpt/css/css-flexbox/percentage-heights-003.html does not test the right thing

### ISSUE THREAD

**Issue by cbiesinger** [web-platform-tests/wpt#13656]
https://github.com/web-platform-tests/wpt/blob/master/css/css-flexbox/percentage-heights-003.html

@gregwhitworth fyi

This test has a column flexbox with an indefinite size, but expects that the flex item size is considered definite. I am fairly sure this is incorrect, per https://drafts.csswg.org/css-flexbox/#definite-sizes item 2 the flexbox needs a definite main size.

**Comment by gsnedders** [comment]
Argh, I am the worst reviewer. I'd forgotten too much detail by the time someone wrote a test for the issue.
