### ISSUE TITLE
Use GitHub's duplicated 3dbc08a982 results to audit for flaky tests 

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#13675]
GitHub's issues yesterday resulted in [major run duplication](https://wpt.fyi/test-runs?sha=3dbc08a982), which is a good chance to try and spot potentially flaky tests.

Example:
https://wpt.fyi/results/2dcontext/line-styles/lineto_a.html?sha=3dbc08a982&max-count=10&label=experimental&product=firefox

**Comment by foolip** [comment]
@AutomatedTester you might be interested in this as well.

**Comment by foolip** [comment]
Too much time has passed for this to be useful, if we want to look for flaky tests we can trigger new duplicate runs.
