### ISSUE TITLE
Assign only one reviewer automatically at a time, in a round-robin fashion

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#13686]
Currently the @wpt-pr-bot assigns all owners of the affected tests as reviewers for a PR, which often becomes a long list. During the TPAC F2F, @lukebjerring raised the point that having too many reviewers might reduce the likelihood of a PR getting reviewed (everyone thinks someone else will review), and it's very noisy for everyone.

Hence, @lukebjerring proposed to change wpt-pr-bot so that we select one reviewer for a PR at a time, in a round-robin fashion.

**Comment by andreastt** [comment]
I appreciate being notified on all new changes to the tests I’m primarily responsible for, even if it means I don’t get around to doing the review first. 

If it really is a problem that too many people get notified and those notified have no intention of performing reviews, perhaps they should not be reviewers?

A middle way solution would be to have a syntax that allows certain people to always be included as reviewers, and a round-robin styled approach for those listed as suggested:

```
always_reviewers:
  - foo
suggested_reviewers:
  - bar
  - baz
```

I don’t know, but this suddenly becomes very complicated.

**Comment by foolip** [comment]
My suggestion for a first version of this is to keep assigning reviewers as we have been, and to additionally assign one of the reviewers as the assignee. Then, document in https://web-platform-tests.org/reviewing-tests/email.html how to write mail filters for all reviews vs. just the ones you've been assigned.

**Comment by gsnedders** [comment]
I think there's a few somewhat awkward issues here:

* Deciding when to reassign,
* How to deal with people being unavailable (either OOO short-term on vacation or longer parental leave etc.), and
* What to do with people who repeatedly don't review (which is somewhat linked to the previous item, given there may be good reasons for them not to!).

**Comment by foolip** [comment]
> Deciding when to reassign

As a first cut, never. The person who sent the review will have to make noise until someone takes notice.

> How to deal with people being unavailable

Low tech solution is to remove from META.yml when leaving and add back when coming back. Any in-tree solution would cause the same amount of churn, so only other option is to maintain this state somewhere else, like maybe in a wiki page.

> What to do with people who repeatedly don't review

Remove from `suggested_reviewers`.

**Comment by lukebjerring** [comment]
FYI, https://github.com/web-platform-tests/wpt-pr-bot/pull/51 is an open PR to match @foolip's proposed change (use the assignee field). It won't be merged if there's any objections to the proposal.

**Comment by mdittmer** [comment]
https://github.com/web-platform-tests/wpt-pr-bot/pull/51 now merged. @lukebjerring @foolip should this issue be closed?

**Comment by lukebjerring** [comment]
Yes, closing as fixed.
