### ISSUE TITLE
Consider removing reviewers who haven't reviewed in over a year

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#13702]
We currently have 63 reviewers who have had a review requested of them on a PR created in the past year but who haven't reviewed anything; some of these looking quickly are people who no longer work on the web platform.

If we want to look at new ways of assigning reviews, we should probably start looking into trimming the META.yml lists.

**Comment by gsnedders** [comment]
And the following people haven't reviewed in the past year, but have had less than four reviews requested of them:

@BenjaminSchaaf @bigbluehat @chaals @ChumpChief @cptvitamin @darrnshn @farre @g-ortuno @gkellogg @joedow-42 @jtangelder @musingvirtual @robman @SummerLW @szager-chromium @theres-waldo @titzer @wolenetz

Ideally, can these people indicate as to whether they remain interested?

And finally, people with [4,9] review requests:

@alphan102 @aogilvie @bemjb @ChrisParis @clelland @eric-carlson @fmarier @hober @inikulin @jacobrossi @jdashg @jeisinger @jonathanKingston @luser @mastahyeti @paezagon @rsheeter @scottgonzalez @staktrace @toji @tschneidereit @Wafflespeanut

**Comment by wafflespeanut** [comment]
I'm sorry. When I signed up, I thought I could spend time for this, but I literally can't (at least for now). You can remove me. Thanks :)

**Comment by jeisinger** [comment]
would we lose coverage for some directories? e.g. for referrer policy, there just haven't been more changes..

**Comment by tschneidereit** [comment]
I won't be able to spend meaningful amounts of time on WPT reviews in the
foreseeable future, so it makes sense to remove me from the reviewer list.

**Comment by tomalec** [comment]
I'm sorry, I'm also not able to dedicate much time for reviewing, so it makes lot of sense to remove me from the list. Thanks.

**Comment by gsnedders** [comment]
@jeisinger right, which is why we won't want to remove all the people with few requests, but quite where we draw the line is pretty much arbitrary

**Comment by staktrace** [comment]
Feel free to remove me as well. Thanks!

**Comment by fmarier** [comment]
You can also remove me. I don't think I'll have much time for reviews in the foreseeable future.

**Comment by andrenatal** [comment]
You can remove me too. I won't have enough time to dedicate to wpt. Thanks!

**Comment by chrislo** [comment]
You can also remove me, I'm afraid I don't have the time available to review at the moment.

**Comment by gkellogg** [comment]
Please remove me, I’m not involved in web platform. 

Gregg Kellogg

**Comment by musingvirtual** [comment]
Hello. So someone just added me to the organization and then I got 20 review requests in 3 hours. 

I do have the time to review the occasional request specifically for the set of tests I'm responsible for, which is what I believed I was signing up for.

I do not have the time to review 6 requests an hour that apply to the entire project, and if that's the only option then I'm going to have to decline further involvement.

Can someone clarify if there's any way to manage the amount of review requests we are getting?

**Comment by mastahyeti** [comment]
Feel free to remove me.

**Comment by foolip** [comment]
@gsnedders, can you share the script you used? Perhaps we can set that up to be run on an ongoing basis. I'll prepare a PR to remove the people who have explicitly asked to be removed in this issue.

**Comment by gsnedders** [comment]
@foolip https://gist.github.com/gsnedders/6049409ca4e35f420db2b157d39c07c4 and then just doing various things with the data it creates

**Comment by foolip** [comment]
As added context, in a [WPT survey](https://docs.google.com/document/d/1b3suZ9TAZ2Y0nn5X6_bgEoIAYG5j2v_ap473ZF1SeaU/edit?usp=sharing), getting PRs reviewed came up as a major pain point. This was discussed at [TPAC](https://github.com/web-platform-tests/wpt/wiki/TPAC-2018) and we decided we would try [Assign only one reviewer automatically at a time, in a round-robin fashion](https://github.com/web-platform-tests/wpt/issues/13686) as a fix. When we do that, it'll be more of an expectation to get timely reviews, so it makes sense to trim the list of suggested reviewers a bit ahead of time.

*However*, not having reviewed anything in the past year isn't itself a problem at all, anyone who wants to review more in the future should stick around :)

**Comment by gsnedders** [comment]
@musingvirtual I can only see one review requested of you, looking with  `review-requested:user` `reviewed-by:user`; are you sure you aren't watching the repo and getting notifications for everything?

**Comment by foolip** [comment]
Oh, no, I wonder if that's just the default and everyone has been getting a torrent of email? Everyone, please let us know if you got subscribed to everything too. https://web-platform-tests.org/reviewing-tests/email.html has a tip for how to filter review requests.

**Comment by Hexcles** [comment]
Reviewers have write access, right?

> When you’re given push access to a repository, we automatically watch the repository for you.

https://blog.github.com/2012-08-06-notifications-stars/#auto-watch

I do remember un-watching the wpt repo manually.

**Comment by foolip** [comment]
Ah, so at least it's "just" reviewers, not everyone who has joined the org, and just wpt, not all other repos.

**Comment by foolip** [comment]
I've asked GitHub support this:

> Giving people write access (by adding to a team) without subscribing?
>
> Hi,
>
> https://github.com/web-platform-tests/wpt is a large repository with many, many contributors and reviewers, where most people are only interested in some subset of it. In https://github.com/web-platform-tests/wpt/issues/13702 we learned that people are being automatically subscribed to the repository when they are added to the reviewers team, and that some have been confused by this and thought they were expected to review all PRs.
> 
> Is it possible to add people to a team without subscribing them to the repo? We have a bot which assigns reviewers.

**Comment by foolip** [comment]
GitHub support replies:
> Thanks for reaching out! The automatic subscription setting is a user-controlled setting. You can let your users know about this setting:
>
> https://help.github.com/articles/watching-and-unwatching-repositories/#unwatching-all-repositories-that-you-have-push-access-to
>
> The title here is a bit misleading & we have an issue open with the team about this. This setting will not unwatch all the repos you're currently watching. It will just stop automatically subscribing you to new repos.

So no setting on the side of the inviter :/

**Comment by wolenetz** [comment]
Please keep me as a reviewer, for wpt in /media-source but not other portions of this repo.
