### ISSUE TITLE
[css-values] calc-unit-analysis test execution

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#13713]
@dbaron 

It seems to me that 

[calc-unit-analysis test](http://w3c-test.org/css/css-values/calc-unit-analysis.html)

[calc-unit-analysis test](http://test.csswg.org/suites/css-values-3_dev/nightly-unstable/html/calc-unit-analysis.htm)

are not providing the standard expected output, like test results. All I see is 

> Running, 18 complete, 0 remain

**Comment by gsnedders** [comment]
Ah, the problem is the `run` function gets called twice (once at the end of the script, once on load).

We should probably also make it more obvious when `testharness.js` has new tests created once it believes it has already completed, rather than this behaviour!

**Comment by qiuzhong** [comment]
Moreover, if there is only 1 test in `run()`, the test results will be showed up correctly. But if there're 2 or even more tests in `run()`, then this issue happened.
