### ISSUE TITLE
Un-.tentative the with-options postMessage() tests

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#13736]
https://github.com/web-platform-tests/wpt/tree/5a792b6bf4e0d39f2b65301b592dffffa8bd9b15/webmessaging/with-options should not have .tentative as https://github.com/whatwg/html/pull/3800 got merged.

**Comment by dtapuska** [comment]
Chromium tentative change:
https://chromium-review.googlesource.com/c/chromium/src/+/1301841
