### ISSUE TITLE
vh-support-margin test incorrect

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#13834]
@FremyCompany 

[vh-support-margin.html](http://w3c-test.org/css/css-values/vh-support-margin.html)

[vh-support-margin.html](http://test.csswg.org/suites/css-values-3_dev/nightly-unstable/html/vh-support-margin.htm)

I propose to
a) add html, body {height: 100%;} 
or 
b) add #target {height: 100vh;}
to your test.

**Comment by FremyCompany** [comment]
I agree. 
Option "a" seems the best since it doesn't involve using vh units (and prevents two failures to lead to a right)

**Comment by TalbotG** [comment]
François,
Unfortunately, I am not be able to create+submit a pull request or approve one because I do not know how to do this. But I presume that @frivoal can help you with that.

**Comment by FremyCompany** [comment]
You fork the repo, clone it locally, make the change, push to your fork, then return to GitHub that will propose you to create a pull request for the change you just pushed. Just did it, but anyone should be able to do that.
