### ISSUE TITLE
[webdriver] "Execute Script" test is flaky in Firefox

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#13882]
While validating [a set of new tests](https://github.com/web-platform-tests/wpt/pull/13880), [TravisCI reported that `test_abort_by_user_prompt_twice[confirm]` is flaky in Firefox](https://travis-ci.org/web-platform-tests/wpt/jobs/450032894):

    ERROR:/home/travis/build/web-platform-tests/wpt/tools/ci:## Unstable results ##
    ERROR:/home/travis/build/web-platform-tests/wpt/tools/ci:|                     Test                     |                  Subtest                   |          Results           |                   Messages                   |
    ERROR:/home/travis/build/web-platform-tests/wpt/tools/ci:|----------------------------------------------|--------------------------------------------|----------------------------|----------------------------------------------|
    ERROR:/home/travis/build/web-platform-tests/wpt/tools/ci:| `/webdriver/tests/execute_script/execute.py` | `test_abort_by_user_prompt_twice[confirm]` | **FAIL: 9/10, PASS: 1/10** | `NoSuchAlertException: no such alert (404):` |

I've been able to reproduce this locally with the following command:

    $ ./wpt run --verify --no-manifest --log-mach - firefox webdriver/tests/execute_script/execute.py 

Context:

    $ git rev-parse HEAD
    ffeba23ebd16b9adb2e0e2b5fe6923fef9bb9e5e
    $ firefox --version
    Mozilla Firefox 63.0

**Comment by jugglinmike** [comment]
The behavior under test is currently being discussed:

https://github.com/w3c/webdriver/issues/1153

Improvements to this test should probably wait until consensus is reached

**Comment by whimboo** [comment]
So the problem here was most likely related to a situation when a user prompt has been shown during script evaluation. The referred WebDriver classic issue has been discussed quite some time ago and we also fixed that in Firefox shortly after. So lets close this issue.
