### ISSUE TITLE
w3c-test.org not updating

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#13913]
I've tried to check the mirror service a few times, but it doesn't seem to be updating:

http://w3c-test.org/submissions/

For instance, I just submitted 13912, but it ain't showing up.

**Comment by foolip** [comment]
@sideshowbarker FYI

But try web-platform-tests.live. It's not yet ready to depend on, but probably works better than w3c-test.org on average.

**Comment by sideshowbarker** [comment]
> I've tried to check the mirror service a few times, but it doesn't seem to be updating:
> 
> http://w3c-test.org/submissions/
> 
> For instance, I just submitted 13912, but it ain't showing up.

I’ll take a look and see if there’s any chance to get it working again. But the fact is it’s been completely broken for quite a long time now, as far as I know.

**Comment by sideshowbarker** [comment]
> But try web-platform-tests.live. It's not yet ready to depend on, but probably works better than w3c-test.org on average.

There’s no http://w3c-test.org/submissions/ equivalent on web-platform-tests.live, and no immediate plans for an equivalent.

**Comment by marcoscaceres** [comment]
Ok, maybe we should remove mention of it from the README?

**Comment by sideshowbarker** [comment]
> Ok, maybe we should remove mention of it from the README?

Actually I think I managed to fix it. It should be working as expected now — both in that it should once again automatically create new directories in http://w3c-test.org/submissions/ for every new PR, and also on-demand if you do a `w3c-test:mirror` comment to any existing PR

**Comment by marcoscaceres** [comment]
Awesome, thank you!
