### ISSUE TITLE
unsupported-encodings.any.js expects XHR text response to default to windows-1252

### ISSUE THREAD

**Issue by hsivonen** [web-platform-tests/wpt#14082]
Fails in Gecko:
https://wpt.fyi/results/encoding/unsupported-encodings.any.worker.html?label=experimental
https://wpt.fyi/results/encoding/unsupported-encodings.any.html?label=experimental

The test uses XHR:
https://github.com/web-platform-tests/wpt/blob/master/encoding/unsupported-encodings.any.js

XHR spec says the default is UTF-8:
https://xhr.spec.whatwg.org/#text-response

Test wrongly expects the default to be windows-1252.

**Comment by hsivonen** [comment]
CC @annevk, @inexorabletash

**Comment by inexorabletash** [comment]
Yeah, even the passing "${label} with no BOM should decode as windows-1252" cases are probably actually decoding as UTF-8 in Gecko, and the data (effectively ASCII) doesn't distinguish.

I have a resource loader decoding fix for blink for the other incorrect default issue poked at recently, but it doesn't handle the XHR case - different code paths. I'd be happy with a WPT fix here and a crbug.
