### ISSUE TITLE
geolocation-API/getCurrentPosition_IDL.https.html async_test failed after removing the timeout

### ISSUE THREAD

**Issue by qiuzhong** [web-platform-tests/wpt#14118]
In #11120, `timeout` is suggested to remove from `async_test`. 

As part of this goal, PR #14094 was filed. However, a geolocation-realated [test](https://github.com/web-platform-tests/wpt/blob/master/geolocation-API/getCurrentPosition_IDL.https.html) failed after `timeout` was removed. To make that PR pass in CI, this test was reverted. This issue is filed specially for this test.

**Comment by qiuzhong** [comment]
In the async_test of this html, the timeout was set 20000 ms, which exceeds the default value (10000 ms). Try to add `<meta name=timeout content=long>` in the html head.

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/14227.
