### ISSUE TITLE
lh-rlh-on-root-001.html : 3 corrections to make

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#14160]
@frivoal 

The 3 corrections to make are emboldened.

line 48 is:
 assert_approx_equals( f_s, initial_f_s, 1, "the lh unit on the root element's font-size property uses font metrics corresponding to the initial values of the font or line-height properties");

line 48 should be instead:
 assert_approx_equals( f_s, initial_**l_h**, 1, "the lh unit on the root element's font-size property uses font metrics corresponding to the initial values of the font or line-height properties");

- - - - - -

line 54 is:
 assert_approx_equals( f_s, initial_f_s, 1, "the rlh unit on the root element's font-size property uses font metrics corresponding to the initial values of the font or line-height properties");

line 54 should be instead:
 assert_approx_equals( f_s, initial_**l_h**, 1, "the rlh unit on the root element's font-size property uses font metrics corresponding to the initial values of the font or line-height properties");

- - - - - -

line 74 is:
 assert_approx_equals( f_s, initial_f_s * 2, 1, "the lh unit on the root element's font-size property actually works as a unit and doesn't merely cause a fallback that doesn't take the number of units into account");

lin 74 should be instead:
 assert_approx_equals( f_s, initial_**l_h** * 2, 1, "the lh unit on the root element's font-size property actually works as a unit and doesn't merely cause a fallback that doesn't take the number of units into account");

**Comment by TalbotG** [comment]
https://github.com/web-platform-tests/wpt/pull/15030

**Comment by frivoal** [comment]
Fixed by #15030
