### ISSUE TITLE
[wpt] `test_wpt.py` is flaky

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#14179]
The test titled `test_run_firefox` in `tools/wpt/tests/test_wpt.py` intermittently fails. I can't reproduce the failure locally, but we witnessed it in TravisCI during the review of gh-14178.

<details>
  <summary>Output of failing test</summary>

    tests/test_browser.py ..                                                 [  5%]
    tests/test_run.py .................                                      [ 48%]
    tests/test_wpt.py .....F.sss..........                                   [100%]
    =================================== FAILURES ===================================
    _______________________________ test_run_firefox _______________________________
    manifest_dir = '/tmp/tmpR8JUXI'
        @pytest.mark.slow
        @pytest.mark.remote_network
        @pytest.mark.xfail(sys.platform == "win32",
                           reason="Tests currently don't work on Windows for path reasons")
        def test_run_firefox(manifest_dir):
            # TODO: It seems like there's a bug in argparse that makes this argument order required
            # should try to work around that
            if is_port_8000_in_use():
                pytest.skip("port 8000 already in use")
        
            if sys.platform == "darwin":
                fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "browsers", "nightly", "Firefox Nightly.app")
            else:
                fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "browsers", "nightly", "firefox")
            if os.path.exists(fx_path):
                shutil.rmtree(fx_path)
            with pytest.raises(SystemExit) as excinfo:
                wpt.main(argv=["run", "--no-pause", "--install-browser", "--yes",
                               # The use of `--binary-args` is intentional: it
                               # demonstrates that internally-managed command-line
                               # arguments are properly merged with those specified by
                               # the user. See
                               # https://github.com/web-platform-tests/wpt/pull/13154
                               "--binary-arg=-headless",
                               "--metadata", manifest_dir,
                               "firefox", "/dom/nodes/Element-tagName.html"])
            assert os.path.exists(fx_path)
            shutil.rmtree(fx_path)
    >       assert excinfo.value.code == 0
    E       assert 1 == 0
    E        +  where 1 = SystemExit(1,).code
    E        +    where SystemExit(1,) = <ExceptionInfo SystemExit tblen=2>.value
    tests/test_wpt.py:190: AssertionError
    ----------------------------- Captured stdout call -----------------------------
    Running 1 tests in web-platform-tests

</details>

**Comment by foolip** [comment]
I've seen something like this involving `SystemExit` on Travis as well, but I don't know which PR it was.

**Comment by jugglinmike** [comment]
While re-trying the job for that pull request, TravisCI timed out:

    tests/test_browser.py ..                                                 [  5%]
    tests/test_run.py .................                                      [ 48%]
    tests/test_wpt.py .....
    No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
    Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
    The build has been terminated

Taken together, these failures suggest that the process of generating the manifest and downloading Firefox are just at the limits of what the TravisCI VMs are capable of. The tests themselves haven't changed, but we have received some patches to the related infrastructure over the past week:

    $ git log -i --grep manifest --after 2018-11-15 --oneline
    fc9918e Update manifest before tests
    cb7be19 Pass the manifest file directly into wpttest.from_manifest
    8d520f0 Fix the cache lifecycle
    770229a Add manifest caches for the mtime and gitignore rules
    4011c5f Update the gitignore implementation to work as an iterator filter
    1ca46e0 Use testfile mtimes to pre-filter files iterated over for the manifest update

For easier cross-referencing, that's revisions fc9918e, cb7be19, 8d520f0, 770229a, 4011c5f, and 1ca46e0.

@jgraham / @andreastt Do you think these changes could explain new inconsistencies in TravisCI's behavior?

**Comment by jgraham** [comment]
I think those patches should mostly only affect things if you update the manifest from the worktree rather than using the git data, which I don't think these tests do, although there are some changes in the shared code that could make a difference. So far I haven't seen any problems with the patches on gecko infra where they definitely are used, but that doesn't mean they can't break in a more resource-constrained environment.

**Comment by foolip** [comment]
Calling it backlog until we learn how often this happens.

**Comment by foolip** [comment]
This test was also failing in https://travis-ci.com/web-platform-tests/wpt/jobs/170830906 for https://github.com/web-platform-tests/wpt/pull/14852, but possibly in a different manner:
<details>
<summary>logs</summary>

```
=================================== FAILURES ===================================
_______________________________ test_run_firefox _______________________________
manifest_dir = '/tmp/tmpNMdZi1'
    @pytest.mark.slow
    @pytest.mark.remote_network
    @pytest.mark.xfail(sys.platform == "win32",
                       reason="Tests currently don't work on Windows for path reasons")
    def test_run_firefox(manifest_dir):
        # TODO: It seems like there's a bug in argparse that makes this argument order required
        # should try to work around that
        if is_port_8000_in_use():
            pytest.skip("port 8000 already in use")
    
        if sys.platform == "darwin":
            fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "browsers", "nightly", "Firefox Nightly.app")
        else:
            fx_path = os.path.join(wpt.localpaths.repo_root, "_venv", "browsers", "nightly", "firefox")
        if os.path.exists(fx_path):
            shutil.rmtree(fx_path)
        with pytest.raises(SystemExit) as excinfo:
            wpt.main(argv=["run", "--no-pause", "--install-browser", "--yes",
                           # The use of `--binary-args` is intentional: it
                           # demonstrates that internally-managed command-line
                           # arguments are properly merged with those specified by
                           # the user. See
                           # https://github.com/web-platform-tests/wpt/pull/13154
                           "--binary-arg=-headless",
                           "--metadata", manifest_dir,
                           "firefox", "/dom/nodes/Element-tagName.html"])
        assert os.path.exists(fx_path)
        shutil.rmtree(fx_path)
>       assert excinfo.value.code == 0
E       assert 1 == 0
E        +  where 1 = SystemExit(1,).code
E        +    where SystemExit(1,) = <ExceptionInfo SystemExit tblen=2>.value
tests/test_wpt.py:192: AssertionError
----------------------------- Captured stdout call -----------------------------
Running 1 tests in web-platform-tests
STDERR: Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/python/2.7.14/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/testrunner.py", line 220, in init_timeout
    self.send_message("init_failed")
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/testrunner.py", line 214, in send_message
    self.command_queue.put((command, args))
  File "/opt/python/2.7.14/lib/python2.7/multiprocessing/queues.py", line 100, in put
    assert not self._closed
AssertionError
Loading initial page http://web-platform.test:8000/testharness_runner.html failed. Ensure that the there are no other programs bound to this port and that your firewall rules or network setup does not prevent access.\eTraceback (most recent call last):
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 132, in load_runner
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 180, in dismiss_alert
    f()
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 132, in <lambda>
    self.dismiss_alert(lambda: self.marionette.navigate(url))
AttributeError: 'MarionetteTestharnessProtocolPart' object has no attribute 'marionette'
Traceback (most recent call last):
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/testrunner.py", line 141, in start_runner
    runner.run()
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/testrunner.py", line 86, in run
    self.setup()
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/testrunner.py", line 73, in setup
    self.executor.setup(self)
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 657, in setup
    self.protocol.testharness.load_runner(self.last_environment["protocol"])
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 132, in load_runner
    self.dismiss_alert(lambda: self.marionette.navigate(url))
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 180, in dismiss_alert
    f()
  File "/home/travis/build/web-platform-tests/wpt/tools/wptrunner/wptrunner/executors/executormarionette.py", line 132, in <lambda>
    self.dismiss_alert(lambda: self.marionette.navigate(url))
AttributeError: 'MarionetteTestharnessProtocolPart' object has no attribute 'marionette'
Ran 0 tests finished in 205.0 seconds.
  • 0 ran as expected. 0 tests skipped.
No tests ran
```
</details>

The "AttributeError: 'MarionetteTestharnessProtocolPart' object has no attribute 'marionette'" bit is new and looks like it could be a simple typo. But I'm not sure why it doesn't always happen then. @jgraham
