### ISSUE TITLE
matchMedia.xht should not check that the event argument is a MediaQueryList

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#14429]
The specification was changed to say that the event listener argument is a MediaQueryListEvent instead: https://drafts.csswg.org/cssom-view/#evaluate-media-queries-and-report-changes

The assertions should use `assert_class_string` to verify that the object is a MediaQueryListEvent instead.

**Comment by M-ZubairAhmed** [comment]
Hi @jdm , would you please tell me what needs to be done in this issue

**Comment by jdm** [comment]
@M-ZubairAhmed https://github.com/web-platform-tests/wpt/blob/master/css/cssom-view/matchMedia.xht is a test for the behaviour of [this specification](https://drafts.csswg.org/cssom-view/#evaluate-media-queries-and-report-changes). The test [here](https://github.com/web-platform-tests/wpt/blob/36baff5e6981e5a235ed1c5f13b45ffed241770b/css/cssom-view/matchMedia.xht#L151-L155) should verify that `x` is actually a MediaQueryListEvent object, and that the various properties of the event that the specification describes are the expected values.
