### ISSUE TITLE
flake8 complains about executorservo.py using bare 'except'

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#14448]
Example: https://travis-ci.org/web-platform-tests/wpt/jobs/466313586#L776

```
py27-flake8 create: /home/travis/build/web-platform-tests/wpt/tools/.tox/py27-flake8
py27-flake8 installdeps: -rrequirements_flake8.txt
py27-flake8 installed: configparser==3.5.0,enum34==1.1.6,flake8==3.6.0,flake8-polyfill==1.0.2,mccabe==0.6.1,pep8-naming==0.7.0,pycodestyle==2.4.0,pyflakes==2.0.0
py27-flake8 run-test-pre: PYTHONHASHSEED='866516015'
py27-flake8 runtests: commands[0] | flake8 --append-config=py27-flake8.ini
./wptrunner/wptrunner/executors/executorservo.py:125:9: E722 do not use bare 'except'
```

The regression was probably introduced by #14242. @jgraham @georgeroman we can fix the code, change revert #14242, or skip this check (in that line or globally). This is currently blocking all changes modifying `tools/` from landing.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/14242 did have this failure originally: https://travis-ci.org/web-platform-tests/wpt/builds/460151731

@jdm, I think that because @servo-wpt-sync has admin rights, it was able to do this. Can we reduce it to write access only?

**Comment by jdm** [comment]
I'm pretty sure we established that admin access was required, but I can't remember why.

**Comment by jgraham** [comment]
It was required when the strategy was to merge all the PRs in a sequence without waiting for travis &c. to run. But that isn't the strategy now, so it may not be required any more.

**Comment by gsnedders** [comment]
@jgraham It seems to be the strategy, given  #14242 landed despite CI failures?

**Comment by jdm** [comment]
I've downgraded the bot's access to write; I think that should be fine.

**Comment by foolip** [comment]
@jdm, excellent, thank you!
