### ISSUE TITLE
Safari Tech Preview version string inconsistent with other products

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#14465]
Noticed in https://github.com/lukebjerring/wpt/pull/8/checks?check_run_id=39929938

> safari-Technology Preview (Release 70, 13607.1.13)-mac-10.13

**Comment by lukebjerring** [comment]
cc @Hexcles @jugglinmike as this is likely to impact infra other that the WPT checks.

**Comment by foolip** [comment]
This is the string that SafariDriver reports, minus a leading "Included with Safari ". I think we should parse/normalize it in code that processes the reports, as opposed to changing wpt, as any transform might lose information.

For "safari-Technology Preview (Release 70, 13607.1.13)-mac-10.13" I'd suggest turning it into "safari-preview-70-mac-10.13".

**Comment by Hexcles** [comment]
Chatted a bit about this with Luke. One issue with the proposal above is that "preview-70" still can't be parsed by the dashboard (which expects something like a semvar). We were thinking "safari-70-preview" but it immediately sounds weird.

Safari Tech Preview really has its own versioning system, independent from the stable Safari shipped with macOS/iOS. If we move "preview" to the end, it sounds more similar to "Chrome 70 dev", which in reality is not the case. A better example would be some earlier Tech Preview, e.g. Tech Preview 13 has nothing to do with Safari 13. So at least point we were thinking about making "Safari Tech Preview" a separate product from "Safari", but that has its own downsides & inconsistency.

**Comment by foolip** [comment]
Can't we just extract product=safari, channel=preview and version=70, and create labels and directory names based on that? The directory names presumably don't really matter at all, so as long as they will be different for stable and preview it's fine?

https://storage.googleapis.com/wptd-results/7750d1636f8ca88a35b1008f12097adf69f46adb/chrome-72.0.3626.14_dev-linux-18.04-ccdbe5c339/report.json has this `run_info`:
```json
    {
        "bits": 64,
        "browser_channel": "dev",
        "browser_version": "72.0.3626.14 dev",
        "debug": false,
        "has_sandbox": true,
        "linux_distro": "Ubuntu",
        "os": "linux",
        "os_version": "18.04",
        "processor": "x86_64",
        "product": "chrome",
        "revision": "7750d1636f8ca88a35b1008f12097adf69f46adb",
        "verify": false,
        "version": "Ubuntu 18.04",
        "wasm": false
    }
```

Something is presumably already parsing "72.0.3626.14 dev" to separate the version from the channel, so more of that?

**Comment by Hexcles** [comment]
@foolip yeah we can do that. Although we don't in fact have a field for "channel", it is just a label. If written as product "specs" (wpt.fyi terms), we will then have:
* `safari-13[stable]`
* `safari-70[preview]`

I guess my question is: would this seem confusing? That the two version numbers for stable & preview are totally unrelated to each other?

**Comment by jugglinmike** [comment]
My vote is for a distinct "Safari Technology Preview" product. That seems like the most accurate (and transparent!) way to describe the release history of that browser. To the extent that it appears inconsistent, that's something we should attribute to Apple's release process--not a wpt.fyi implementation detail we need to abstract away.

**Comment by foolip** [comment]
I don't really see why it matters that the version tracks are different matter, it's the 3-tuple (browser, channel, version) + perhaps OS that identified a release, so isn't it fine that things can be ambiguous or confusing when you omit some information?

**Comment by mdittmer** [comment]
@lukebjerring @foolip per discussion in sand up today. Do we want to mark this "closed, won't fix"?

**Comment by lukebjerring** [comment]
@Hexcles is going to normalize it to `safari-70 (13706.1.13)`, which I'll end up treating as
- BrowserName: `safari`
- BrowserVersion: `70`

Special-casing overlapping product names, or other weird stuff, is worse than having version mismatching between `experimental` and `stable`

**Comment by foolip** [comment]
I do still think we should fix this in code that handles the reports. We presumably already have the previous form of the string in reports, and won't be able to forever avoid any product-specific parsing of versions in wpt.fyi.

**Comment by Hexcles** [comment]
@lukebjerring if we want to keep the version string intact, we have to loosen the assumptions made on the wpt.fyi side, most importantly drop all the heuristics for semvar (e.g. in `shared.VersionPrefix`) and opt for a simple prefix match. The tradeoff is that specs like `chrome-6` will match Chrome 60~69 again. Let me post a PR on wpt.fyi to show what it'd look like.

**Comment by foolip** [comment]
Can we not extract a part of the version string that we take to be the main component, which is parts separated by periods? 1.2.3 or 34.7a or 19r4 all fit that. Then prefix match but require matching whole parts and not partial parts?

(The extra info (WebKit version) in the Safari strings would just be for humans to look at.)

**Comment by Hexcles** [comment]
We currently store verbatim version strings from wptreport in Datastore. We can extract the "main component" of the version string and store it as a separate field for querying, or we can use drastically different Datastore queries for different browsers to filter by versions at query time.

@lukebjerring you initially wrote the heuristics for browser versions. I vaguely remember it was to avoid matching Chrome 60 when users asked for Chrome 6. Would it really be that bad if we do a dumb prefix matching? (One inconvenience of verbatim STP versions + prefix matching is that users need to type `safari-Technology Preview 60` as the spec.)

**Comment by lukebjerring** [comment]
I'm confused why we think we need to preserve the original string. It's not meaningful to us in its raw form.
The channel doesn't need to be kept; we just did that so that the original string could be kept. If we ditch the original string anyway, then there's no reason to try not to stray further. 
Let's just extract the semantic information and store it to serve the query use-cases we need it for. The original string can live in the raw report if we ever need it.

**Comment by Hexcles** [comment]
> Let's just extract the semantic information and store it to serve the query use-cases we need it for. The original string can live in the raw report if we ever need it.

Hold on a sec: my tentative #14484 would change the version string in the raw report. If we want to preserve it in the report, then wpt isn't the right place to normalize it; we need to do it on the wpt.fyi side.
