### ISSUE TITLE
wpt run produces an empty file for a report when no tests are executed

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#14471]
Relates to https://github.com/web-platform-tests/wpt/pull/14156

#14354 collapsed `tests-affected` into a flag for `wpt run`, which in the case of no affected tests is causing Taskcluster to produce an empty report file. In turn, we create a check for wpt.fyi that never resolves (since a run never gets created).

e.g. https://github.com/web-platform-tests/wpt/pull/14454

**Comment by foolip** [comment]
Whatever the solution is, the should be possible to tell the difference between no tests being affected, and no results being produced due to an infra error.

**Comment by lukebjerring** [comment]
@Hexcles and I were discussing this. It seems to me that it would be highly preferable to still produce a valid JSON blob in the report file, for which the results field is empty, rather than a fully empty file.

@jgraham - I'm under the impression this isn't as trivial as described. One suggestion I made was that we execute a canonical "strawman" placeholder test that produces a "no tests found" message, in the case that none of the requested tests are in the manifest, which would cause the remainder of the mozlog behaivours to produce content. On a scale of `1` to `Very bad idea`, where does this sit?

**Comment by lukebjerring** [comment]
On further inspection, we don't need to have any tests actually run; we just need to coax the command line into thinking it should still try when `--affected` is passed.

**Comment by Hexcles** [comment]
The approach above (as implemented in either #14630 or #14649) solves the common case of this issue: `wpt run --affected` with no tests affected. We still don't have easy ways to solve an edge (but not extremely rare) case (I think originally reported by @jugglinmike ): if something goes wrong before the suite starts (like uncaught exceptions or errors during setup), we would still produce an empty (and hence invalid) JSON file. This edge case is hard to fix and presumably requires some fiddling with `mozlog`.
