### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14499]
We now have the ability to migrate individual repos in the web-platform-tests org from travis-ci.org to travis-ci.com, and we have already migrated wpt.fyi as a trial. Old links and build history are preserved.

There isn't a strong reason to migrate *now*, but we eventually have to. One upside is that we get the new [Checks API](https://developer.github.com/v3/checks/) integration which is also what Azure Pipelines uses. The Travis integration isn't very fancy, but it's a small improvement. Example from wpt.fyi:
https://github.com/web-platform-tests/wpt.fyi/pull/910/checks?check_run_id=40636708

@web-platform-tests/admins I would like to do this migration org-wide. If I do not hear concerns within a week I'll go ahead.

**Comment by Hexcles** [comment]
Just a reminder that you'd need to change the "required checks" for protected branches after migration.

**Comment by foolip** [comment]
Yep. There are also details about cron jobs that I'll take care of.

**Comment by foolip** [comment]
I will do this now, one day earlier than planned, to give a few more days to clean up the mess if I break stuff.

**Comment by foolip** [comment]
The most recent PR is now https://github.com/web-platform-tests/wpt/pull/14600, any PRs created after then but before the transition is complete need to be inspected so they're not blocked on checks that will never run.

**Comment by foolip** [comment]
The app is now installed org-wide instead of just for wpt.fyi. Following the documentation in https://docs.travis-ci.com/user/open-source-repository-migration/ to migrate each individual repo.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/13352 has finished running on travis-ci.com, and I sent https://github.com/web-platform-tests/wpt/pull/14603 to test the full set of tests.

I've changed the required check from "continuous-integration/travis-ci" to "Travis CI - Pull Request", but unfortunately that makes it show up as required on all existing PRs as well. https://github.com/web-platform-tests/wpt/pull/14600 is an example of this, now in the state "Required statuses must pass before merging". I'll see if there's a way to trigger the runs without closing and reopening all PRs.

**Comment by foolip** [comment]
For master, https://github.com/web-platform-tests/wpt/runs/42781561 was the first job to run after the change, followed by https://github.com/web-platform-tests/wpt/runs/42784876. The worked as intended:
https://github.com/web-platform-tests/wpt/releases/tag/merge_pr_14570
https://github.com/web-platform-tests/wpt/releases/tag/merge_pr_13352

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/14603/checks?check_run_id=42779464 shows what the new checks will look like. Closing that test PR now.

**Comment by foolip** [comment]
There doesn't appear to be anything in https://octokit.github.io/rest.js/#api-Checks to trigger just Travis checks for a PR. Still looking for a way to resolve https://github.com/web-platform-tests/wpt/issues/14499#issuecomment-448594887.

**Comment by foolip** [comment]
Per https://travis-ci.community/t/trigger-build-on-pr-via-api/825/2 it doesn't look like there's a way with the Travis API either.

**Comment by foolip** [comment]
The migration is now complete for all repos in the org, but the remaining work is to make sure that nobody is confused by their PRs being blocked.

**Comment by foolip** [comment]
<details>
<summary>Script that I wrote to find PRs that are blocked on a missing "Travis CI - Pull Request" check</summary>

```js
'use strict';

const octokit = require('@octokit/rest')();

// https://github.com/octokit/rest.js/#pagination
function paginate(method, parameters) {
  const options = method.endpoint.merge(parameters);
  return octokit.paginate(options);
}

function getChecksForRef(ref) {
  // no pagination because of https://github.com/octokit/rest.js/issues/1161
  return octokit.checks.listForRef({
    owner: 'web-platform-tests',
    repo: 'wpt',
    ref,
    per_page: 100,
  }).then(r => r.data.check_runs);
}

async function getStatusesForRef(ref) {
  const statuses = await paginate(octokit.repos.listStatusesForRef, {
    owner: 'web-platform-tests',
    repo: 'wpt',
    ref,
    per_page: 100,
  });

  // Statuses are in reverse chronological order, so filter out all but the
  // first for each unique context string.
  const seenContexts = new Set;
  return statuses.filter(status => {
    const context = status.context;
    if (seenContexts.has(context)) {
      return false;
    }
    seenContexts.add(context);
    return true;
  });
}

async function checkPRs() {
  const prs = await paginate(octokit.pulls.list, {
    owner: 'web-platform-tests',
    repo: 'wpt',
    state: 'open',
    sort: 'updated',
    direction: 'desc',
    per_page: 100,
  });

  console.log(`Found ${prs.length} open PRs`);

  for (const pr of prs) {
    const commits = (await octokit.pulls.listCommits({
      owner: 'web-platform-tests',
      repo: 'wpt',
      number: pr.number,
      per_page: 100,
    })).data;


    if (commits.length >= 100) {
      console.log(`Too many commits: ${pr.html_url}`);
      continue;
    }

    // only look at the final commit
    const commit = commits[commits.length - 1];

    const checks = await getChecksForRef(commit.sha);
    const travisCheck = checks.find(c => c.name === 'Travis CI - Pull Request');
    if (travisCheck) {
      continue;
    }

    const statuses = await getStatusesForRef(commit.sha);
    const travisStatus = statuses.find(s => s.context === 'continuous-integration/travis-ci/pr');
    const tcStatus = statuses.find(s => s.context === 'Taskcluster (pull_request)');

    if (travisStatus && tcStatus) {
      // the `mergeable` state isn't included in the PR list, so fetch it again.
      const mergeable = (await octokit.pulls.get({
        owner: 'web-platform-tests',
        repo: 'wpt',
        number: pr.number,
      })).data.mergeable;

      if (mergeable === false) {
        console.log(`Merge conflicts: ${pr.html_url}`);
      } else if (travisStatus.state === 'success') {
        // High prio: had passing Travis status check
        console.log(`Passing on travis-ci.org: ${pr.html_url}`);
      } else {
        console.log(`Failing on travis-ci.org: ${pr.html_url}`);
      }
    } else {
      // These PRs are so old that they aren't worth poking.
      //console.log(`Missing Travis or Taskcluster status: ${pr.html_url}`);
    }
  }
}

async function main() {
  octokit.authenticate({
    type: 'token',
    token: process.env.GH_TOKEN
  });

  await checkPRs();
}

main();
```
</summary>

It only lists PRs that have *both* an old travis-ci.org status and a Taskcluster status, since PRs predating Taskcluster were already blocked. I went through the list until I got to PRs that haven't been updated in the past two weeks.

**Comment by foolip** [comment]
I am not going to poke more PRs manually, but I'll list the output of the script now, so that they all get backlinks here to help understand the problem:

Found 468 open PRs
Failing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14468
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/13906
Too many commits: https://github.com/web-platform-tests/wpt/pull/14300
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/14321
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/14400
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/14390
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14377
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14384
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14383
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14364
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14037
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/7940
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13272
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14336
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14302
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14245
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14297
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13720
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14255
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14279
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14278
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14246
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14163
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14271
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14260
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14197
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14174
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14149
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14074
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14110
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14109
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/14095
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13302
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/12950
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13965
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13973
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13964
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13688
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/12221
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13873
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13428
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/13510
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13808
Failing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13632
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13715
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/10548
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13271
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13650
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13658
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13649
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13109
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13575
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13572
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/12933
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13534
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13474
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13275
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13530
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13461
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13529
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13524
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13477
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13202
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13385
Merge conflicts: https://github.com/web-platform-tests/wpt/pull/13362
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13365
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13306
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/5280
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13178
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13238
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13027
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13189
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13142
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13061
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13031
Failing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13010
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/13030
Passing on travis-ci.org: https://github.com/web-platform-tests/wpt/pull/12972
Too many commits: https://github.com/web-platform-tests/wpt/pull/271

**Comment by foolip** [comment]
Alright, with that I declare the migration complete!

**Comment by foolip** [comment]
Everyone, if you find your way here trying to find out why your PR is blocked on Travis, either make some change (e.g. rebase) to your branch and push it again, or just close and reopen the PR. If you still can't get Travis to run+pass, please let me know.

**Comment by foolip** [comment]
For lack of a better place, I'll explain an oddity that's happened here. After I discussed the trouble we had with the changed check name with Travis support, they enabled an internal setting on our repo to send *both* statuses and checks. That caused PRs to have two Travis entries, one "Travis CI - Pull Request" (check) and one "continuous-integration/travis-ci/pr" (status).

This was the case over the holiday. I asked Travis to undo it yesterday, and https://github.com/web-platform-tests/wpt/pull/14766 is the last PR which got both.
