### ISSUE TITLE
Regressions from "Make testharness tests run in a top-level browsing context"

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14495]
https://github.com/web-platform-tests/wpt/pull/13966 caused regressions in many tests, and @beaufortfrancois reported regressions in https://wpt.fyi/results/picture-in-picture?label=experimental.

Exact diff for Chome+Firefox experimental:
- Chrome: https://wpt.fyi/results/?label=experimental&product=chrome%5Btaskcluster%5D%405dd605cdfa&product=chrome%5Btaskcluster%5D%40c522b884f7&diff
- Firefox: https://wpt.fyi/results/?label=experimental&product=firefox%5Btaskcluster%5D%405dd605cdfa&product=firefox%5Btaskcluster%5D%40c522b884f7&diff

Diff spanning the change and more for Safari experimental:
https://wpt.fyi/results/?label=experimental&product=safari%5Bexperimental%5D%40e4a221e6c4&product=safari%5Bexperimental%5D%4048d5d5033d&diff

**Comment by domenic** [comment]
It seems like in some cases it may have helped though, e.g. https://wpt.fyi/results/keyboard-lock?label=experimental&product=chrome%5Btaskcluster%5D%405dd605cdfa&product=chrome%5Btaskcluster%5D%40c522b884f7&diff . This indicates many other tests may have been suffering from the same problems as the ones that prompted the original issue.

**Comment by jgraham** [comment]
I think I would have preferred not to revert this since it looks like it's probably a net win. However issues for regressions should certainly be top priority (I'm looking at the PiP tests now but I'm not sure what's going wrong).
