### ISSUE TITLE
Multiple same-name subtests not always triggering a harness error

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt#14533]
E.g., http://w3c-test.org/css/css-values/calc-unit-analysis.html

**Comment by mdittmer** [comment]
Further context:

The link claims 18 tests, but only 9 results inside the results script tag. When these tests are run and the results are sent to a JSON report, 18 subtest entries (not 9) appear, along with test status of `OK`. [Example run report](https://storage.googleapis.com/wptd-results-staging/48d5d5033d2f634125d0ae2dd494d68f8d01de79/chrome-72.0.3626.14_dev-linux-18.04-f7742a2216/report.json).

**Comment by jugglinmike** [comment]
Taking a look now!

**Comment by lukebjerring** [comment]
@jugglinmike - did you end up looking into this?

**Comment by jugglinmike** [comment]
I did! I'll follow up with a few patches shortly

**Comment by jugglinmike** [comment]
This is a result of tests which erroneously declare sub-tests following harness-level completion. In the interest of speed and stability, I think the best we can do (beyond being more careful when writing tests) is silently ignore those sub-tests. That's what I'm proposing in gh-15634, anyway.

**Comment by foolip** [comment]
I've reviewed/merged https://github.com/web-platform-tests/wpt/pull/15634, closing this.
