### ISSUE TITLE
Many PRs blocked due to failing Taskcluster stability checks

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14564]
With https://github.com/web-platform-tests/wpt/issues/14165 resolved, Taskcluster was made a required check again on Dec 12. Since then, many PRs have become blocked on a Taskcluster failure:

wpt-chrome-dev-stability failures:
- https://github.com/web-platform-tests/wpt/pull/14400
- https://github.com/web-platform-tests/wpt/pull/14531

wpt-firefox-nightly-stability failures:
- https://github.com/web-platform-tests/wpt/pull/14420
- https://github.com/web-platform-tests/wpt/pull/14469
- https://github.com/web-platform-tests/wpt/pull/14536

wpt-chrome-dev-stability + wpt-firefox-nightly-stability failures:
- https://github.com/web-platform-tests/wpt/pull/13906
- https://github.com/web-platform-tests/wpt/pull/14417
- https://github.com/web-platform-tests/wpt/pull/14519
- https://github.com/web-platform-tests/wpt/pull/14551

Some issues filed:
- https://github.com/web-platform-tests/wpt/issues/14433
- https://github.com/web-platform-tests/wpt/issues/14434

Authors of those PRs, please comment here to say whether the failure was related to your changes. If we have too many PRs blocked for unrelated reasons, we'll have to reconsider.

**Comment by jgraham** [comment]
All but one seems to be an actual stability check failure, so if there's a problem here it isn't with Taskcluster as such, but with the stability checking.

**Comment by foolip** [comment]
The trouble would be if we have so much pre-existing flakiness that an unreasonable number of PRs would be blocked on pre-existing flakiness. I don't know where to draw the line, filed this issue to start collecting cases of it happening.

If it's too bad, I think we'd have to get our hands on data about which tests are most frequently affected and which of those are most flaky, and fix those.

**Comment by jgraham** [comment]
Fixing flaky tests seems like a good idea for many reasons.

**Comment by frivoal** [comment]
For #14551, I've restarted it a couple of times by pushing a rebased commit, and I believe that it was once reported as firefox flakiness, and twice as Chrome's. But I've never been able to reproduce locally, and while instability in a basic non animated layout reftest isn't totally impossible if the browser engine happens to have some kind of non deterministic bug, it is pretty unlikely. So I don't know what's causing this, but I'm pretty sure it isn't the test itself.

**Comment by foolip** [comment]
Self-assigning so that at least I'll check in later to see how many PRs are blocked on stability.

**Comment by lukebjerring** [comment]
cc @Hexcles

**Comment by foolip** [comment]
This keeps being the main time sink when monitoring https://ecosystem-infra-rotation.appspot.com/, showing up as "blocked export PRs."

@lukebjerring @KyleJu do you think anything beyond the currently planned work on flakiness metadata will be needed to resolve this? More concretely, will the flakiness still show up as blocked exports and require us to add the metadata, or do we need to block Chromium CLs from landing? There's probably a tricky balance here between the amount of human involvement on our side vs. how much overhead there is for Chromium devs trying to get stuff landed and just using WPT because it's the default thing to do. Disincentives for using WPT would be bad :)

**Comment by foolip** [comment]
Closing this, work is underway to not block on known flakiness.
