### ISSUE TITLE
Don't store affected tests ignore list in command line arguments

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#14560]
The idea was to separate out the logic in the code from configuration about which files should and should not be included. But in practice this led to the regression addressed in #14559 where the code changed but the configuration was not wired into the new code. Additionally, we've never needed to change this configuration, and generally found that it's more maintainable to put things directly in the Python code rather than requiring wrapper shell scripts to set options.

**Comment by qiuzhong** [comment]
@jgraham , If we should not store affected tests ignore list in command line arguments, then can we update the `--ignore-rules` option or remove it if possible?
https://github.com/web-platform-tests/wpt/blob/b6d9f766aaea899da6b1c6d585f2e68f996a3c39/tools/wpt/testfiles.py#L303-L308

I don't think it's fine to keep this option to let users enter the ignore rules in command line. It might cause some problems, see #15436.
