### ISSUE TITLE
Document how to write crash tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14602]
@progers was wondering if/how to write crash tests in web-platform-tests. I wrote:
> I'd say just structure it like a reftest or a testharness.js test that does as little as necessary, and runs as long as necessary for the crash to happen if the bug is there. For testharness.js, that may mean a pretty vacuous async_test or similar, but a dummy assert wouldn't really make it clearer what the test is for.

If others agree with this, we should document it.

**Comment by jgraham** [comment]
If you structure things as a single-page test then you possibly just need to call done() at some point before the timeout. One can also imagine making `.crash.` tests that work like testharness tests except that they can't time out only pass (but maybe it should be a different type altogether that doesn't require having a testharness script).

**Comment by foolip** [comment]
https://github.com/web-platform-tests/rfcs/pull/33 should resolve this.

**Comment by stephenmcgruer** [comment]
That rfc merged a while ago, and https://web-platform-tests.org/writing-tests/crashtest.html exists, so I think this is fixed?
