### ISSUE TITLE
Monitor Azure Pipelines runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14763]
Azure Pipelines was enabled in https://github.com/web-platform-tests/wpt/issues/13818. We should monitor runs to notice if it stops working for some reason, like https://github.com/web-platform-tests/wpt/issues/14210 for Taskcluster.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/issues/14860 is one bit of breakage that monitoring should capture.

**Comment by foolip** [comment]
I still need to do this.

**Comment by foolip** [comment]
I'm making some efforts in https://github.com/foolip/wpt-stats. Detecting when things have failed is pretty easy, but how to make it actionable and who should monitor it is less easy.

**Comment by stephenmcgruer** [comment]
This falls under @LukeZielinski 's monitoring/metrics efforts, but I'm not sure what the priority is for Azure Pipelines runs. Luke - feel free to downgrade to backlog.

**Comment by stephenmcgruer** [comment]
We did some work on monitoring in Q2 (see https://github.com/ecosystem-Infra/wptmon), but we never added Azure Pipeline support and do not currently have plans to move wptmon past an experiment. As such, dropping to backlog and removing Luke.

**Comment by foolip** [comment]
Nothing to do here, really.
