### ISSUE TITLE
Daily runs of Safari Technology Preview on Azure Pipelines

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14836]
In https://github.com/web-platform-tests/wpt/pull/14752 I attempted to enable full runs of Safari Technology Preview on Azure Pipelines, triggered by the epochs/daily branch.

As described in https://github.com/web-platform-tests/wpt/pull/14752#issuecomment-452928106 it didn't work, so this issue is to continue investigating until fixed.

**Comment by foolip** [comment]
On my own fork (foolip/wpt) I tried pushing the current epochs/daily branch (commit 9d21b523b4959f402769d58248e4587fda7f39ff) and that did correctly trigger a build:
https://dev.azure.com/foolip/wpt/_build/results?buildId=343

I then pushed the same commit to the master branch. That *doesn't* cause another Azure Pipelines "CI build" to start, which is consistent with https://github.com/web-platform-tests/wpt/pull/14752#issuecomment-452928106 and suggests that the order of branches updating is the key.

I do see webhooks for both push events being delivered to https://dev.azure.com/foolip/_apis/public/hooks/externalEvents, but these aren't the webhooks that should be used, and I don't see the same installed for this repo.

@lukebjerring do you know of a way to check what webhooks for creating check suites were delivered to a GitHub app?

**Comment by foolip** [comment]
I found it: https://github.com/organizations/web-platform-tests/settings/apps/wpt-fyi-status-check/advanced

But I don't think I can see the same for the Azure Pipelines app, since it isn't our own. I can't tell from the webhook delivery logs if two checks are created when one branch follow another, because there are too many. @lukebjerring do you know, or can you tell from logs?

**Comment by lukebjerring** [comment]
So, as discuss offline: exactly one check suite gets created _when the commit is pushed_. Updating a ref (or a branch, or anything else) to include/set HEAD to the commit doesn't trigger a new check suite.

I think we need to move this pipeline into a daily-triggered pipeline, and tweak it to sync to the SHA provided by the announcer (https://wpt.fyi/api/revisions/epochs).

**Comment by foolip** [comment]
Azure Pipelines does support cron jobs, I could try that.

**Comment by foolip** [comment]
I added a cron job for 14:45 UTC which was triggered:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=3626

Unfortunately it didn't work because of https://github.com/web-platform-tests/wpt/issues/14860.

@mdittmer if we trigger using a cron job, at what time is it safe to assume epochs/daily has been updated? 00:05 UTC?

**Comment by foolip** [comment]
@lukebjerring I have another potential fix for this which is simple but confusing if not documented. The only reason Azure Pipelines is currently reacting to all push events is because that is the default. The azure-pipelines.yml is then read to figure out what to really do, if anything. I've overridden this in dev.azure.com to only consider pushes for epochs/daily.

Now, if GitHub still creates the check suite/run when the master branch is pushed this won't help, but possibly Azure Pipelines gets some webhook which will cause it to act on this. Remains to see if that happens and if the build ends up associated with a check run or not.

**Comment by foolip** [comment]
This doesn't seem to have worked, it seems that no build was triggered for Azure Pipelines, suggesting that GitHub did nothing because it had already processed this commit.

**Comment by foolip** [comment]
I've posted https://github.community/t5/GitHub-API-Development-and/Can-the-Checks-API-be-used-to-trigger-two-runs-when-two-pushed/m-p/17777#M688 about the problem at hand. I'll give up on something that integrates with the Checks API for now and look for workarounds. I'll revert the config changes done in https://github.com/web-platform-tests/wpt/issues/14836#issuecomment-456222296 so that there are at least no-op runs that we could try retriggering as one possible mechanism.

**Comment by foolip** [comment]
@lukebjerring looking at https://developer.github.com/v3/activity/events/types/#checkrunevent and https://developer.github.com/v3/checks/suites/#rerequest-check-suite, it appears that as a normal user of the GitHub API, only a whole check suite can be restarted. There's an event for when a check run is restarted, but that seems tied to the pull request UI and trying to send this event directly to GitHub or the CI system probably won't work, or at least probably isn't intended to work.

A cron job trigger together with https://github.com/web-platform-tests/wpt.fyi/pull/1054 might be the shortest path at this point.

**Comment by foolip** [comment]
Some good news is that the scheduled builds are kicking off and completing, here's the one for the current epochs/daily commit: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=4441

**Comment by foolip** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=vsts is what we should use to poke https://github.com/web-platform-tests/wpt.fyi/pull/1054.

**Comment by lukebjerring** [comment]
OK, https://github.com/web-platform-tests/wpt.fyi/pull/1054 has now landed, so I think a cron job (daily pipeline) that has a final job of POSTing to https://staging.wpt.fyi/api/checks/azure/{build ID} is our best bet.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=4589 is the latest, `curl -v -X POST https://staging.wpt.fyi/api/checks/azure/4589` printed "Azure build artifacts retrieved successfully". Let's hope that also works when done immediately after the PublishBuildArtifacts@1 task, I'll prepare a PR to see.

**Comment by foolip** [comment]
YEEEEEEEESSSS! https://staging.wpt.fyi/results/?sha=66355d4d7f&label=experimental

That was from manual poking, PR to do it from pipeline in the works.

**Comment by foolip** [comment]
This should work next UTC midnight, but leaving the issue open until confirmed. I'll trigger a build on master now to see if it's likely to work.

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=4722 is looking promising.

**Comment by foolip** [comment]
Calling this done, we have two runs now, the last of which was entirely automated:
https://wpt.fyi/results/?sha=66355d4d7f
https://wpt.fyi/results/?sha=388ba3a049

@thejohnjansen @mustjab please pass along a THANK YOU and maybe some cake to the Azure Pipelines team for making this possible.

**Comment by foolip** [comment]
Note also how the version changed from 73 to 74, that's https://github.com/foolip/safari-technology-preview-updater actually working :)
