### ISSUE TITLE
Pin the versions of Python packages needed for tox tests

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#14891]
https://github.com/web-platform-tests/wpt/issues/14889 appears to have been possible because the version of hypothesis used changed without human oversight. Dependencies that are tracked without any version are in all of our tox.ini files, here excluding third party ones:

resources/test/tox.ini
tools/wpt/tox.ini
tools/wptrunner/tox.ini
tools/tox.ini

Extracting out the deps into requirements_tox.txt and adding them to .pyup.yml should fix this.

**Comment by foolip** [comment]
@web-platform-tests/wpt-core-team, do you know of reasons why this might be a bad idea?

**Comment by gsnedders** [comment]
No. We should do this. Dunno if we want separate requirements lists for `tox` file? Probably we don't need to?

**Comment by foolip** [comment]
What do you mean by separating requirements? Having one per tox.ini as opposed to one with the union of deps?

**Comment by foolip** [comment]
This is now 80% fixed. What remains is an unpinned html5lib in `resources/test/tox.ini` and this list in `tools/tox.ini`:
https://github.com/web-platform-tests/wpt/blob/dc4f48817c58362c4dbe4a8b2a8189cdc400a8f2/tools/tox.ini#L7-L13
