### ISSUE TITLE
html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-side-effects-ignore-opens-during-unload.window.html looks buggy

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#14909]
The test says does a load in an iframe and during the beforeunload event sets up a Promise to run the actual test bits that involve calling `document.open`.

The test has a comment that claims that this should happen before the ignore-opens-during-unload counter is decremented, because microtasks run during "clean up after running script".

But microtasks only run during "clean up after running script" if the JavaScript execution context stack is empty.  In this case it's not.  Indeed, setting `iframe.src` from script calls into https://html.spec.whatwg.org/multipage/iframe-embed-object.html#the-iframe-element:process-the-iframe-attributes-3 which calls https://html.spec.whatwg.org/multipage/iframe-embed-object.html#process-the-iframe-attributes which calls https://html.spec.whatwg.org/multipage/iframe-embed-object.html#otherwise-steps-for-iframe-or-frame-elements which calls into https://html.spec.whatwg.org/multipage/browsing-the-web.html#navigate which in step 8 calls https://html.spec.whatwg.org/multipage/browsing-the-web.html#prompt-to-unload-a-document and fires beforeunload.  This is all happening sync, while the script that set src is on the stack.  So there is _not_ a microtask checkpoint at the end of the event listener firing.

How exactly does Chrome pass this test?   @TimothyGu @domenic

**Comment by bzbarsky** [comment]
The right way to test this if we really need the entry global to be the subframe is probably to enter script inside the subframe (e.g. via a string setTimeout call on it) and then do the src set from that script.

**Comment by TimothyGu** [comment]
By this logic https://github.com/web-platform-tests/wpt/blob/master/html/webappapis/dynamic-markup-insertion/opening-the-input-stream/bailout-side-effects-synchronous-script.window.js would need to be changed as well, as it  uses `Promise.resolve` to a similar end.

**Comment by TimothyGu** [comment]
> The right way to test this if we really need the entry global to be the subframe

I might be mistaken but it seems like we want the entry realm of the test to _not_ be the subframe, which is the whole point of calling `Promise.resolve` in the top frame. Indeed, what we want to test here is that the URL doesn’t change, _despite_ the fact that the entry document is different from the document itself and `document.open()` would ordinarily be effective.

**Comment by bzbarsky** [comment]
> If Firefox is indeed completely synchronous from src

It is.
