### ISSUE TITLE
Use a window manager when running test jobs via xvfb 

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#14938]
I investigated some WebDriver test failures for Firefox as shown on [wpt.fyi](https://wpt.fyi/results/webdriver/tests?label=master&label=experimental) the last days, and noticed that the window manipulation tests (fullscreen, maximize, minimize, set window rect) mostly fail for me also locally when I use `xvfb` and having no window manager installed. By that config at least Firefox cannot correctly set those modes. Related here was also an earlier discussion at https://github.com/web-platform-tests/wpt/issues/13005#issuecomment-438199267. 

Installing and using a window manager like `fluxbox` in combination with `xvfb` made it work for me.

As @jgraham pointed me out now the `wpt` setup doesn't make use of a window manager: https://github.com/web-platform-tests/wpt/blob/master/tools/ci/start.sh#L30

So it would be great to get this command updated to also include the usage of a simple window manager like fluxbox.

**Comment by jgraham** [comment]
I think there are two parts here

1) Check what's installed in the docker image. If there isn't a WM installed we will need to install one, and rebuild the docker file, so hopefully there is?
2) Write the code in `tools/ci/start.sh` to actually start the WM. https://stackoverflow.com/questions/41298489/xvfb-start-or-attach-a-window-manager-to-xvfb might be useful for the latter.

**Comment by foolip** [comment]
@mcatanzaro this seems like it could be relevant for your work on Epiphany. Will you need a real window manager there as well?

**Comment by foolip** [comment]
@whimboo since you've started work on this I marked it as priority:roadmap and assigned to you. Hope that's OK. It means that it someone will ask about progress if it's inactive for 60 days.

**Comment by whimboo** [comment]
Sure, once we agreed on a window manager we can continue here. I only would need someone to build and upload the docker image because I don't have permissions.

**Comment by mcatanzaro** [comment]
> @mcatanzaro this seems like it could be relevant for your work on Epiphany. Will you need a real window manager there as well?

I just haven't gotten around to trying to make the tests work headless yet. It's high on my TODO. I'm just always a little swamped.

I would expect that using a real window manager might lead to more accurate test results in all browsers, so it seems desirable, but when running tests locally I'd want them to run headless to avoid disruption. Both ways seem valuable.

**Comment by whimboo** [comment]
> I just haven't gotten around to trying to make the tests work headless yet. It's high on my TODO. I'm just always a little swamped.

Please note that this issue is not about getting it working for headless, but as web-platform-tests are currently run via xvfb in CI automation. Maybe that doesn't affect you given that Epiphany isn't tested in this configuration.

**Comment by foolip** [comment]
We're trying to work out how to test Epiphany in CI, that's the background here :)

**Comment by whimboo** [comment]
PR #14981 got merged, so we make use of `fluxbox` as window manager for now. If there is something which is not supported and needed later, we can always switch to a different one later.

With the next job on master we should see way more green tests for wdspec in regards of fullscreen/maximized/minimized/set window rect commands.
