### ISSUE TITLE
Consider re-enabling logging for test names for --verify jobs

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#15039]
While checking for logs of my work on #14981, I noticed that no test names are reported. That makes it actually hard to identify a test which failed.

I asked @jgraham and I he thinks that we might want to reconsider adding those log lines now that the tests run on TaskCluster and not Travis CI anymore. As such we don't run into the log limits.

**Comment by foolip** [comment]
@whimboo which logs are these? The test names are included in the default logger at least, has it disappeared from some other logger?

**Comment by jgraham** [comment]
This is for `--verify`

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/15074 might be enough here

**Comment by foolip** [comment]
@whimboo is this resolved for you now?

**Comment by whimboo** [comment]
Do you have a link to a verify log? I haven't had the need to push a PR since I reported this issue.

**Comment by whimboo** [comment]
Just had a upstream PR today: https://tools.taskcluster.net/groups/UmbvZ82hQDKoueqE3OMDPQ/tasks/CVDp03uVQVyMnpRUdPXHdw/runs/0/logs/public%2Flogs%2Flive.log

So this looks fine. Thanks!
