### ISSUE TITLE
infrastructure/reftest/size-ref.html flaky on Azure/Edge

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#15159]
In https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5357 (before https://github.com/web-platform-tests/wpt/pull/14300 was landed) /infrastructure/reftest/size-ref.html failed.

https://gist.github.com/foolip/d4b8dc5e236ebcf0cf10b28bf50684da is the edge.tbpl.log.

Pasting that into https://hg.mozilla.org/mozilla-central/raw-file/tip/layout/tools/reftest/reftest-analyzer.xhtml reveals that the output was "innerWidth x innerHeight: 600x601" instead of the expected "innerWidth x innerHeight: 600x600":
![download](https://user-images.githubusercontent.com/498917/51982795-418e0980-2497-11e9-9b11-92f0fd1000b0.png)

The size of this image is also 600x601.

**Comment by foolip** [comment]
Interesting, this might be flaky.

In https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=5605 for https://github.com/web-platform-tests/wpt/pull/15196 the test unexpectedly passed.

**Comment by gsnedders** [comment]
It's not that surprising, resizing is a bit weird and complicated and OS dependent to start with, especially if we're dealing with anything where there isn't an integral scaling factor (though I'd be surprised if this were the case for what we're running on Azure?).

**Comment by gsnedders** [comment]
One thing that might be worth trying is moving the window to some constant location before we start trying to resize it?

**Comment by gsnedders** [comment]
@foolip is there any way to just trigger a large number of runs now and see if it's at all stable?

**Comment by foolip** [comment]
Sure, you can push a branch that uses parallel jobs like all_edge but each does the same steps.

**Comment by gsnedders** [comment]
@foolip do you know if this flakiness went away after the above PR?

**Comment by foolip** [comment]
@gsnedders no, I haven't checked.

**Comment by foolip** [comment]
We're no longer running this configuration.
