### ISSUE TITLE
HTMLButtonElement CEReactions tests are incorrect for boolean attributes

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#15167]
@kaixinjxq can you take a look? They have the same problem as was noticed and fixed in the review of https://github.com/web-platform-tests/wpt/pull/14711.

**Comment by kaixinjxq** [comment]
@domenic, actually I've fixed this in https://github.com/web-platform-tests/wpt/pull/14491/commits/54b38c385768f24934f0cb7e70581897f996d05d, could you help review it?
