### ISSUE TITLE
Taskcluster logs too verbose to find the import part (the end)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#15171]
With https://github.com/web-platform-tests/wpt/pull/15074 fixed it's possible to diagnose more failures `./wpt run --verify` as in https://github.com/web-platform-tests/wpt/issues/14862#issuecomment-459125799, but https://github.com/web-platform-tests/wpt/pull/15123 also had a failed wpt-firefox-nightly-stability job:
https://tools.taskcluster.net/groups/I0dpLuNmS8OGEj60JhOyPw/tasks/YhSVoGCVTdCzfzK3jgZvLw/runs/0/logs/public%2Flogs%2Flive.log

The logs are so long that clicking "Follow log" doesn't scroll to the end. Opening the raw logs slows down my browser and I can't scroll to the end. I had to save it to disk and use `tail -f1000` to see the good bits.

@jgraham ideas?

**Comment by jgraham** [comment]
Yeah, that log seems to be 200Mb uncompressed, so I imagine it doesn't work well in a browser. The size was why we didn't have the full logging on in the first place, although we were more concerned with Travis limitations than anything else. In the long term it would be good to get the summary into the status check directly. However it's not clear what to do to solve the general case; most of the output is duplicate so one could imagine some trick to only provide output for the first run and the subsequent runs where the test result hasn't been seen before, but that would require a little work.

**Comment by foolip** [comment]
I'll close this in favor of https://github.com/web-platform-tests/wpt/issues/15412.
