### ISSUE TITLE
Some dynamic import test code doesn't agree with the test description

### ISSUE THREAD

**Issue by jonco3** [web-platform-tests/wpt#15182]
See this code and its equivalent in string-compilation-nonce-module.html:

https://github.com/web-platform-tests/wpt/blob/09c7c724f76a6512d829c20a5b84d0fabba661eb/html/semantics/scripting-1/the-script-element/module/dynamic-import/string-compilation-nonce-classic.html#L37-L43

The description says that this use of setTimeout to execute the import should work but the code passes window.unreached as first argument of then() rather than window.continueTest.

I think the description is correct and the then() parameters are wrong.  @domenic is that right?

**Comment by domenic** [comment]
Yeah, I think your diagnosis is correct. I will send a PR to fix.

**Comment by domenic** [comment]
Oh, you fixed this in https://github.com/web-platform-tests/wpt/commit/8ecb503bc748ded75e7f5c224b95344a2966eeb9, I see! OK, I'll close this then, and thanks again.
