### ISSUE TITLE
Failing Fullscreen API tests on detached frames

### ISSUE THREAD

**Issue by tzik** [web-platform-tests/wpt#15290]
I have a question around [element-request-fullscreen-active-document.html](https://github.com/web-platform-tests/wpt/blob/master/fullscreen/api/element-request-fullscreen-active-document.html) and [document-exit-fullscreen-active-document.html](https://github.com/web-platform-tests/wpt/blob/master/fullscreen/api/document-exit-fullscreen-active-document.html).

IIUC, they call [requestFullscreen](https://fullscreen.spec.whatwg.org/#dom-element-requestfullscreen) and [exitFullscreen](https://fullscreen.spec.whatwg.org/#exit-fullscreen) from a detached frame, and these are spec'ed to return a rejected Promise. These tests ensure that the result is actually a rejected Promise.

However, after the [PromiseReject](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-rejectpromise) step changed the promise state to "rejected" and the following [Promise.prototype.catch](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-promise.prototype.catch) tries to enqueue the rejection handler through  [PerformPromiseThen](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-performpromisethen), [EnqueuJob](https://html.spec.whatwg.org/multipage/webappapis.html#enqueuejob(queuename,-job,-arguments)) [checks if we can run script](https://html.spec.whatwg.org/multipage/webappapis.html#check-if-we-can-run-script) before it puts the rejection handler into the microtask queue.
Then, as the document of the detached frame is not [fully active](https://html.spec.whatwg.org/multipage/browsers.html#fully-active), the rejection handler is not actually queued nor invoked.

So IMO, these tests is not relevant. WDYT?

**Comment by tzik** [comment]
https://github.com/whatwg/fullscreen/issues/67 is a previous discussion.
@annevk @foolip @zcorpan: do you guys have any insight on this?

**Comment by annevk** [comment]
The tests seem relevant, but they might have the wrong pass condition.

I also did not realize we have "check if we can run script" as that seems to solve https://github.com/whatwg/html/issues/2621?

**Comment by tzik** [comment]
> The tests seem relevant, but they might have the wrong pass condition.
Hmm, but, there's no way to extract the result from the promise to verify it.

@domenic: Can we clarify [the step 2 of EnqueueJob](https://html.spec.whatwg.org/multipage/webappapis.html#enqueuejob(queuename,-job,-arguments))?
On [V8 implementation](https://chromium.googlesource.com/v8/v8.git/+/c4411b0be8d81af1bbbe4f9c546cdbc0a521ccfa/src/builtins/builtins-promise-gen.cc#982) of [EnqueueJob](https://html.spec.whatwg.org/multipage/webappapis.html#enqueuejob(queuename,-job,-arguments)) for [PerformPromiseThen](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-performpromisethen), it uses the promises' environment for "some appropriate environment settings object". That is, a stale promise on an inactive document should not run its handler.
Instead, if the handler's one is appropriate, it runs even on the stale promise.

```html
<!doctype html>
<iframe id="frame"></iframe>
<div id="out"></div>
<script>
let iframe = document.getElementById('frame');

// |resolved| is created on the iframe's environment, which is navigated away soon.
let resolved = iframe.contentWindow.Promise.resolve();
iframe.src = '/x.html';

iframe.onload = () => {
  // If the "appropriate environment settings object" at EnqueueJob is |resolved|'s one,
  // the handler does not run and we'll not see "Reachable?".
  // If the "appropriate environment settings object" is |handler|'s one, the handler rus.
  let handler = () => {
    document.getElementById('out').textContent = "Reachable?";
  };
  resolved.then(handler);
};
</script>
```
https://jsfiddle.net/pbu2w5kr/

**Comment by zcorpan** [comment]
If something should not happen, you can use `assert_unreached('it happened')` if it does, and maybe wait for some other event that is guaranteed to come afterwards to end the test.

**Comment by domenic** [comment]
The plan of record is at https://github.com/whatwg/html/issues/1426#issuecomment-340071080

**Comment by tzik** [comment]
Thanks for the pointer.

> It looks like reviewing earlier threads the following would be the most consistent:
> * PromiseResolveThenableJob(promiseToResolve, thenable, then): should choose [[Realm]] of `then`
> * PromiseReactionJob (reaction, argument): should choose [[Realm]] of reaction.[[Handler]] when reaction.[[Handler]] exists; otherwise it is unobservable (no user code is called)

So, the handler's [FunctionRealm](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-getfunctionrealm) or its constructor's FunctionRealm seem relevant here.
Let me try updating V8 impl instead of modifying the test or fullscreen spec.

**Comment by tzik** [comment]
V8 starts using the handler's realm for promise reactions if it's available.
That should match the plan of the spec update.
