### ISSUE TITLE
[css-text][quirks] quirks/vertical-align-in-quirks.html is misplaced

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#15354]
@kojiishi it looks like you authored this test:

/quirks/vertical-align-in-quirks.html

It should not be in the /quirks/ directory since it is not testing the quirks mode standard.

If there's a standards-mode version of the test somewhere, it should be moved to that location.

Also the title of the test should be fixed.

**Comment by kojiishi** [comment]
It is testing quirks renders the same way as the standard mode for `vertical-align`. I don't know where such tests should go. If you have suggestions, happy to take.

**Comment by zcorpan** [comment]
The same place a test for vertical-align in standards mode should go. I'm not sure where that is. Maybe CSS2/linebox/ ? cc @gsnedders

**Comment by kojiishi** [comment]
It's not testing `vertical-align` at all, because the test and the ref are the same.

**Comment by zcorpan** [comment]
It's testing that vertical-align is implemented correctly in quirks mode, yes?

**Comment by kojiishi** [comment]
Not really. It uses `vertical-align`, but compares with the same document in standard mode, so the test passes as long as UA renders the same way in both modes. UA that doesn't support `vertical-align` will pass.

It's a test for a bug where Blink rendered `vertical-align` differently only in quirks mode.

**Comment by zcorpan** [comment]
Sure but it would then fail a lot of other tests that test `vertical-align` (in standards mode). The point of the test, surely, is to test `vertical-align`, it's not just accidentally using `vertical-align` while actually testing something else.

It's not testing any requirement in the Quirks standard, so it shouldn't be in `quirks/`.

**Comment by gsnedders** [comment]
> It's not testing any requirement in the Quirks standard, so it shouldn't be in `quirks/`.

@zcorpan we've had historical tests added for things that were never in any spec for implementation-specific features, and this doesn't seem any different to that (this is a historical behaviour that was never specified for quirks), so I don't have a strong preference between `quirks/` and `css/CSS2/linebox/`.

**Comment by zcorpan** [comment]
Hmm. Yeah, I think you're right. How about putting it in `quirks/historical/` and we can put more such tests in there? Then the spec could have a non-normative section on historical quirks, and point to the tests.

I didn't realize this was an actual quirk that was dropped from Chromium.

**Comment by gsnedders** [comment]
I'm just going by what @kojiishi said above: "It's a test for a bug where Blink rendered `vertical-align` differently only in quirks mode." :)

**Comment by zcorpan** [comment]
Hmm, looking at https://chromium-review.googlesource.com/c/chromium/src/+/1320529 - it looks like there was an incorrect assumption in the code. So this would be more like a normal regression test for a bug than a "historical.html" test.

The reason I filed this is that the Quirks standard links to the tests using Bikeshed `wpt` feature, and Bikeshed gives an error if there exists a test that is not linked from the spec, and I don't know where to put this in the spec.

**Comment by zcorpan** [comment]
I'll put this in `historical/` anyway, seems OK.

**Comment by zcorpan** [comment]
https://github.com/web-platform-tests/wpt/pull/15381
