### ISSUE TITLE
Proposal to remove a Payment Request test case

### ISSUE THREAD

**Issue by rsolomakhin** [web-platform-tests/wpt#15396]
Hi @marcoscaceres ,

I don't think Chrome can ever pass this test, because it's impossible to change the state of a promise after the iframe that created it has navigated away.

https://github.com/web-platform-tests/wpt/blob/85614961e6ee65fe339a7a8e770499c80cccae28/payment-request/rejects_if_not_active.https.html#L69

Would it be OK to remove this test case?

--Rouslan

**Comment by marcoscaceres** [comment]
We should probably talk with @domenic, as it feels like something browsers need to support. It doesn’t seem too crazy to imagine the tested situation happening in real life.

**Comment by marcoscaceres** [comment]
This actually works now.
