### ISSUE TITLE
Bless more PaymentRequest tests 

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#15434]
Based on https://github.com/web-platform-tests/wpt/pull/15386#issuecomment-463841819 the following can be "bless"'ed

- https://github.com/web-platform-tests/wpt/tree/master/payment-request/payment-request-show-method-manual.https.html
- https://github.com/web-platform-tests/wpt/tree/master/payment-request/payment-request-multiple-show-manual.https.html
- https://github.com/web-platform-tests/wpt/tree/master/payment-request/show-method-optional-promise-rejects-manual.https.html

**Comment by danyao** [comment]
The first two tests are fixed in https://github.com/web-platform-tests/wpt/pull/15424.

**Comment by marcoscaceres** [comment]
Awesome, updated tests look great. Thanks for the update!

**Comment by marcoscaceres** [comment]
Closed via https://github.com/web-platform-tests/wpt/issues/15434
