### ISSUE TITLE
Incorrect test of computed value on user-select

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#15456]
https://github.com/web-platform-tests/wpt/blob/master/css/css-ui/parsing/user-select-computed.html, as introduced by #15313 , is incorrect and incomplete:

1. it claims that the computed value of `auto` is `auto`, while [the spec says](https://drafts.csswg.org/css-ui-4/#valdef-user-select-auto):

  > The computed value of auto is determined as follows:
  > 
  > * On the ::before and ::after pseudo elements, the computed value is none
  > * If the element is an editable element, the computed value is contain
  > * Otherwise, if the computed value of user-select on the parent of this element is all, the computed value is all
  > * Otherwise, if the computed value of user-select on the parent of this element is none, the computed value is none
  >  * Otherwise, the computed value is text 

2. It does not tests this part:
  > on editable elements [...] the computed value is always contain regardless of the specified value

**Comment by ewilligers** [comment]
Apologies for messing up the test.

Based on day's resolution in https://github.com/w3c/csswg-drafts/issues/3344, the `auto` test no longer needs to change.

What was the decision regarding editable elements? Does being editable affect computed value or only used value?

**Comment by frivoal** [comment]
Spec updated according to that resolution, which means the test is no longer incorrect.
