### ISSUE TITLE
Special case testdriver.js when detecting affected tests

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#15485]
IIRC, `testharness.js` is treated specially in the heuristics for detecting affected tests (whenever it's modified almost all tests are affected). I think we need to do the same for `testdriver.js` as its use increases.

**Comment by foolip** [comment]
@LukeZielinski can you take a look at this? Does touching testdriver.js currently cause stability checks to time out, or how much margin do we have?

A similar case is idlharness.js where @lukebjerring added code to run more affected tests, but in that case we don't expect the number of tests to ever go much beyond the total number of specs/directories.

**Comment by lukebjerring** [comment]
https://github.com/web-platform-tests/wpt/pull/13392 is the change mentioned

**Comment by LukeZielinski** [comment]
So empirically (https://github.com/web-platform-tests/wpt/pull/16852) the stability checks were not run for a no-op change to testdriver.js. Although it's kind of surprising, since (as you said) only `resources/testharness*` is excluded in `testfiles.py`.

Is there some other configuration at play here?

**Comment by foolip** [comment]
@jgraham do you know why touching testdriver.js won't end up running any tests? I'm pretty sure it once did, and I haven't changed it or been aware of a change.

**Comment by foolip** [comment]
Ping @jgraham on https://github.com/web-platform-tests/wpt/issues/15485#issuecomment-499041527.

**Comment by gsnedders** [comment]
@foolip they were in #20674; no idea why they weren't in #16852.

**Comment by stephenmcgruer** [comment]
Marking roadmap due to inactivity (and lack of concern about inactivity)
