### ISSUE TITLE
infrastructure Firefox tests failing on Travis

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#15728]
#15721 ([Travis job](https://travis-ci.com/web-platform-tests/wpt/jobs/183097178)), #15723 ([Travis job](https://travis-ci.com/web-platform-tests/wpt/jobs/183119872)), and #15726 ([Travis job](https://travis-ci.com/web-platform-tests/wpt/jobs/183122570)) have all failed on the infrastructure tests on Travis CI in Firefox, all getting one unexpected error:

```
TEST-UNEXPECTED-CRASH | /infrastructure/assumptions/cookie.html | expected OK
```

**Comment by gsnedders** [comment]
Awkwardly, I can't manage to reproduce this locally.

This seems to have started earlier today though…

**Comment by Hexcles** [comment]
Also #15730 ([job](https://travis-ci.com/web-platform-tests/wpt/jobs/183227311#L790))

**Comment by alcooper91** [comment]
I'm hitting this with #15735 ([Job](https://travis-ci.com/web-platform-tests/wpt/jobs/183509540)) as well.

**Comment by gsnedders** [comment]
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1534765 for this, no idea how to debug this :/

**Comment by gsnedders** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1533539 makes it sound like it's a Firefox without Pulseaudio issue. So installing Pulseaudio should fix this?
