### ISSUE TITLE
Removing `-support` naming convention

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#15749]
When identifying tests, the WPT infrastructure ignores files whose name (not including extension) ends in `-support`. Today, only 13 files meet that criteria:

<details>
  <summary><code>$ git ls-files | grep '\-support\.'</code></summary>

    WebIDL/ecmascript-binding/constructors-support.html
    css/css-values/vh-calc-support.html
    css/css-values/vh-support.html
    css/css-values/vh-zero-support.html
    dom/traversal/traversal-support.js
    event-timing/resources/event-timing-support.js
    eventsource/eventsource-onmessage-realm-support.htm
    fullscreen/rendering/fullscreen-pseudo-class-support.html
    html/semantics/forms/resetting-a-form/reset-form-event-realm-support.html
    html/syntax/parsing/DOMContentLoaded-defer-support.js
    html/the-xhtml-syntax/parsing-xhtml-documents/xhtml-mathml-dtd-entity-support.htm
    html/webappapis/scripting/events/resources/compiled-event-handler-settings-objects-support.html

</details>

The infrastructure *also* ignores files placed within subdirectories named "resources", "tools", or "support". That approach is far more common:

    $ git ls-files | grep -E '(/|^)(resources|tools|support)/.*\.(html?|xht)' | wc -l
    851

I'd like remove the infrastructure that recognizes the `-support` file name pattern and relocate the files that rely on it to an appropriately-named subdirectory. My motivation is to reduce the learning curve for contribution and limit the number of ways to express the same thing. In addition, four of the `-support` files listed above appear to actually be tests. If so, they are evidence that the naming scheme is prone to accidental opt-in.

Does anyone know of a reason why this simplification cannot or should not be made? @gsnedders or @jgraham, perhaps?

**Comment by gsnedders** [comment]
Yeah, this seems a bit surprising. Totally happy to drop this.

**Comment by foolip** [comment]
@gsnedders is this straightforward? Can I assign to you and plan to fix in the coming months?

**Comment by Ms2ger** [comment]
I guess this is fine, though I don't think we particularly need to start moving these tests. I expect the actual support files will end up in the default case in `SourceFile.manifest_items()` and be treated as support files anyway.
