### ISSUE TITLE
Misleading documentation of .asis feature

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#15804]
The *Tests Requiring Full Control Over The HTTP Response* section in https://web-platform-tests.org/writing-tests/server-features.html says:

> For full control over the request and response the server provides the ability to write `.asis` files; these are served as literal HTTP responses. It also provides the ability to write Python scripts that have access to request data and can manipulate the content and timing of the response. For details see the wptserve documentation.

This makes it sound like one could use `.asis` files to write Python scripts, which doesn't seem to be the case.

@jugglinmike FYI.

**Comment by jugglinmike** [comment]
In addition to extending that text, commit 8119bc10583682676a3db9806c82ed4044e88e13 inserted a paragraph break between the description of the "asis" feature and the "Python handlers" feature. The docs now read:

> For full control over the request and response, the server provides the ability to write `.asis` files; these are served as literal HTTP responses. In other words, they are sent byte-for-byte to the server without adding an HTTP status line, headers, or anything else. This makes them suitable for testing situations where the precise bytes on the wire are static, and control over the timing is unnecessary, but the response does not conform to HTTP requirements.
>
> The server also provides the ability to write [Python "handlers"](python-handlers/index)--Python scripts that have access to request data and can manipulate the content and timing of the response. Responses are also influenced by [the `pipe` query string parameter](server-pipes).

@foolip do you think that will be enough to prevent confusion?

**Comment by foolip** [comment]
Yep, that resolves the confusion, thanks @jugglinmike!
