### ISSUE TITLE
How to write a test that verifies the tab crashes when code is run?

### ISSUE THREAD

**Issue by guest271314** [web-platform-tests/wpt#15816]
Revisited https://github.com/w3c/media-source/issues/190 after activity at https://github.com/w3c/mediacapture-record/issues/4. Cannot recollect what did to avoid tab crashing at Chromium re https://bugs.chromium.org/p/chromium/issues/detail?id=820997, was several OS's ago. However, the issue persists when running code that does not crash the tab at Firefox https://github.com/guest271314/MediaFragmentRecorder. Firefox outputs the expected result; a single `.webm` file where the media fragments are recorded into a single video.

Specifically, at Chromium/Chrome trying to capture stream of `<video>` using `HTMLMediaElement` `captureStream` and passing that `MediaStream` to a `MediaRecorder` instance where the `<video>` `.src` is set to a `MediaSource` instance crashes the tab. 

How to write a wpt test that verifies the tab crashes?

**Comment by jdm** [comment]
I'm confused; why do we want a test that a) causes a crash, b) verifies that a crash occurred? Shouldn't the purpose of the test be to verify the behaviour of the browser when it does not crash, and the fact that the browser crashes is treated as a failure?

**Comment by guest271314** [comment]
@jdm However you want to phrase the test is fine. The fact is that the code described at the OP causes Chromium to crash. Filed a Chromium bug and an issue at MediaSource repository at GitHub. The issue persists. Yes, the tab crashing should be treated as a failure. The question is does wpt have a procedure to verify that the tab crashes when the code is run?

**Comment by jdm** [comment]
@guest271314 WPT does recognize when crashes occur. It's not a property of the test, but the test harness.

**Comment by guest271314** [comment]
@jdm 

> WPT does recognize when crashes occur.  It's not a property of the test, but the test harness.

Can you link to how to compose or an example of such a WPT test where the crash is recognized?

**Comment by jdm** [comment]
It is automatic. It is not a specific property of the test.

**Comment by guest271314** [comment]
@jdm This code https://plnkr.co/edit/K21jI533alufdgwabQN2?p=preview will output expected result (a `<video>` element where the `.src` is set to a `Blob URL` where the underlying data is a `webm` file consisting of the recorded media fragements) at Firefox 65, crash the tab at Chromium 72. 

The relevant API's tested are `MediaSource` and `MediaRecorder`. 

Should the test be composed as Asynchronous Tests or Promise Tests at https://web-platform-tests.org/writing-tests/testharness-api.html?

**Comment by guest271314** [comment]
@jdm Here is the test with `"normal"` property of `harness_timeout` set to `60*10000`

```
<!DOCTYPE html>
<html>

<head>
  <title>Test recording media fragments using MediaSource and MediaRecorder</title>
  <script src="testharness.js"></script>
  <script src="testharnessreport.js"></script>
  <meta name="timeout" content="long">
</head>

<body>
  <p id="test">click</p>
  <script>
    function testMediaSourceMediaRecorder() {
      return new Promise((resolve, reject) => {
        const test = document.getElementById("test");
        const captureStream = mediaElement =>
          !!mediaElement.mozCaptureStream ? mediaElement.mozCaptureStream() : mediaElement.captureStream();
        class MediaFragmentRecorder {
          constructor({
            urls = [],
              video = document.createElement("video"),
              width = 320,
              height = 280
          } = {}) {
            if (urls.length === 0) {
              throw new TypeError("no urls passed to MediaFragmentRecorder");
            }
            return (async() => {
              video.height = height;
              video.width = width;
              video.autoplay = true;
              video.preload = "auto";
              video.controls = true;
              const chunks = [];
              let duration = 0;
              let media = await Promise.all(
                urls.map(async({
                  from,
                  to,
                  src
                }, index) => {
                  const url = new URL(src);
                  // get media fragment hash from `src`
                  if (url.hash.length) {
                    [from, to] = url.hash.match(/\d+/g);
                  }
                  return {
                    blob: await fetch(src).then(response => response.blob()),
                    from,
                    to
                  }
                }));
              for (let {
                  from,
                  to,
                  blob
                }
                of media) {
                await new Promise(async(resolve) => {
                  let recorder;
                  const blobURL = URL.createObjectURL(blob);
                  video.addEventListener("playing", e => {
                    const mediaStream = captureStream(video);
                    recorder = new MediaRecorder(mediaStream, {
                      mimeType: "video/webm;codecs=vp8,opus"
                    });
                    recorder.start();
                    recorder.addEventListener("stop", e => {
                      resolve();
                      console.log(e);
                    }, {
                      once: true
                    });
                    recorder.addEventListener("dataavailable", async(e) => {
                      console.log(e);
                      chunks.push(await new Response(e.data).arrayBuffer());
                      URL.revokeObjectURL(blobURL);
                    });
                    video.addEventListener("pause", e => {
                      if (recorder.state === "recording") {
                        recorder.stop();
                      } else {
                        recorder.requestData();
                      }
                      console.log(video.played.end(0) - video.played.start(0), video.currentTime - from, video.currentTime);
                      duration += video.currentTime - from;
                    }, {
                      once: true
                    });
                  }, {
                    once: true
                  });
                  video.addEventListener("canplay", e => video.play(), {
                    once: true
                  });
                  video.src = `${blobURL}#t=${from},${to}`;
                })
              };
              video.load();
              return {
                chunks,
                duration,
                width,
                height,
                video
              }
            })()
          }
        }
        let urls = [{
          src: "https://upload.wikimedia.org/wikipedia/commons/a/a4/Xacti-AC8EX-Sample_video-001.ogv",
          from: 0,
          to: 4
        }, {
          src: "https://mirrors.creativecommons.org/movingimages/webm/ScienceCommonsJesseDylan_240p.webm#t=10,20"
        }, {
          from: 55,
          to: 60,
          src: "https://nickdesaulniers.github.io/netfix/demo/frag_bunny.mp4"
        }
        ];

        test.addEventListener("click", _ => 
        new MediaFragmentRecorder({
            urls
          })
          .then(({
              chunks,
              duration,
              width,
              height,
              video
            }) => {
                let recorder, mediaStream;
                console.log(chunks, duration);
                const mediaSource = new MediaSource();
                const mimeCodec = "video/webm;codecs=vp8,opus";
                const sourceOpen = e => {
                  console.log(e);
                  const sourceBuffer = mediaSource.addSourceBuffer(mimeCodec);
                  sourceBuffer.addEventListener("updateend", e => {
                    console.log(e, video.currentTime, mediaSource);
                  });
                  if (chunks.length) {
                    sourceBuffer.appendBuffer(chunks.shift());
                  }
                }
                const handleWaiting = e => {
                  console.log(e, video.currentTime, recorder && recorder.state);
                  mediaSource.sourceBuffers[0].abort();
                  mediaSource.sourceBuffers[0].timestampOffset = video.currentTime;
                  if (chunks.length) {
                    mediaSource.sourceBuffers[0].appendBuffer(chunks.shift());
                  } else {
                    try {
                      if (recorder.state === "recording") {
                        recorder.stop();
                        video.removeEventListener("waiting", handleWaiting);
                        mediaSource.endOfStream();
                        console.log(video.currentTime, duration, mediaSource.duration);
                      }
                    } catch (e) {
                      console.error(e.stack);
                      console.trace();
                    }
                  }
                }
                mediaSource.sourceBuffers.addEventListener("addsourcebuffer", e => console.log(e));
                video.addEventListener("canplay", e => {
                  console.log(video.readyState, video.paused);
                  if (video.paused) {
                    video.play();
                  }
                  console.log(e, duration, video.buffered.end(0), video.seekable.end(0), video.duration, mediaSource.duration);
                });
                video.addEventListener("playing", e => {
                  mediaStream = captureStream(video);
                  mediaStream.addEventListener("inactive", e => console.log(e));
                  recorder = new MediaRecorder(mediaStream, {
                    mimeType: "video/webm;codecs=vp8,opus"
                  });
                  recorder.addEventListener("dataavailable", e => {
                    let media = document.createElement("video");
                    media.width = width;
                    media.height = height;
                    media.controls = true;
                    document.body.appendChild(media);
                    media.src = URL.createObjectURL(e.data);
                    resolve(1);
                  });
                  recorder.addEventListener("stop", e => console.log(e));
                  recorder.start();
                  console.log(e, duration, video.buffered.end(0), video.seekable.end(0), video.duration, mediaSource.duration);
                }, {
                  once: true
                });
                video.addEventListener("waiting", handleWaiting);
                video.addEventListener("pause", e => console.log(e));
                video.addEventListener("stalled", e => console.log(e));
                video.addEventListener("loadedmetadata", e => console.log(e));
                video.addEventListener("loadeddata", e => console.log(e));
                video.addEventListener("seeking", e => console.log(e));
                video.addEventListener("seeked", e => console.log(e));
                video.addEventListener("durationchange", e => console.log(e));
                video.addEventListener("abort", e => console.log(e));
                video.addEventListener("emptied", e => console.log(e));
                video.addEventListener("suspend", e => console.log(e));
                mediaSource.addEventListener("sourceopen", sourceOpen);
                video.src = URL.createObjectURL(mediaSource);
              })
            )
      })
    }

    promise_test(function(t) {
      return testMediaSourceMediaRecorder().then(function(result) {
        assert_equals(result, 1, "Result should be 1, resolved in MediaRecorder dataavailable event at MediaSource endOfStream")
      });
    }, "Test recording media fragments using MediaSource and MediaRecorder");
  </script>
</body>
</html>
```



The issue is the after `click` on element the HTML redirects to test report document which crashes.

**Comment by jdm** [comment]
@guest271314 If the test does not crash, the assertion will be checked and the test will pass or fail based on it. If the browser crashes at any point during test execution, the test will report an unexpected crash result.

**Comment by guest271314** [comment]
> If the browser crashes at any point during test execution, the test will report an unexpected crash result.

@jdm How to reproduce the result you describe? Due to recent autoplay policy updates at browsers to commence the test requires user action, in the current test a click on an element. The test report page (redirect to from test page) is not reached.

Did consider launching Chromium and Firefox with autoplay policies disabled so the test would automatically run. Would that be feasible? Or would that require all users who run the test to set the same preferences?

**Comment by jdm** [comment]
When running tests via https://github.com/web-platform-tests/wpt#running-tests-automatically instead of http://w3c-test.org/ (or similar in-browser testing), it happens automatically.

**Comment by guest271314** [comment]
@jdm Ok. How to create a pull request which adds the test to each of the relevant wpt directories (see https://github.com/w3c/mediacapture-record/issues/4#issuecomment-474023431.)?

**Comment by jdm** [comment]
@guest271314 Duplicating the test isn't valuable. It's best to choose which one is most relevant and put it there.

**Comment by guest271314** [comment]
@jdm Am not certain if the issue is `MediaSource` or `MediaRecorder`. Though if `MediaRecorder` is not included in the code to record the stream rendered at `<video>` element where `.src` is set to special `MediaSource` `Blob URL`  the tab does not crash. That leaves https://github.com/web-platform-tests/wpt/tree/master/mediacapture-fromelement and/or https://github.com/web-platform-tests/wpt/tree/master/mediacapture-record as being the source of the bug. The tab crashes when `.captureStream()` is called on the `<video>` element with the specialized `MediaSource` `Blob URL` set at `.src`, therefore the correct directory at this time appears to be mediacapture-fromelement. How to create the appropriate pull request to include the test in that directory?

**Comment by jdm** [comment]
@guest271314 If you're looking for assistance with creating a pull request, I recommend the [github documentation](https://help.github.com/en/articles/creating-a-pull-request).

**Comment by guest271314** [comment]
@jdm The issue that causes the crash appears to be setting `.timestampOffset` of `MediaSource`, not media capture from element

`Uncaught DOMException: Failed to set the 'timestampOffset' property on 'SourceBuffer': The timestamp offset may not be set while the SourceBuffer's append state is 'PARSING_MEDIA_SEGMENT'.`

**Comment by guest271314** [comment]
@jdm Read the document. Still not sure what to do at this point.  The pull request is at https://github.com/guest271314/web-platform-tests/commit/0da0c1e93f7994b57391f321ffdfed0eb3328575

**Comment by jdm** [comment]
You will probably want to follow the steps at https://help.github.com/en/articles/creating-a-pull-request-from-a-fork.

**Comment by guest271314** [comment]
@jdm It looks as though the commit was merged into an existing pull request https://github.com/web-platform-tests/wpt/pull/9963?

**Comment by jdm** [comment]
@guest271314 That happened automatically because you had an open PR based off of the master branch of your fork, and you made a pull request from the guest271314-patch-1 branch of your fork to your master branch and merged it. You will need to run `git reset --hard 4ec675380896ad787270e4a46430d691fbb6f786` on your master branch and force push it to your fork in order to remove the extra commits from that pull request.

**Comment by guest271314** [comment]
@jdm Been a while since used `git` at terminal. Will try.

**Comment by guest271314** [comment]
@jdm Used the suggested code. Will read the documents before trying to create pull request again.

FYI Ironically while attempting to reduce the code that produced the crash created a version which outputs the same expected result at Firefox and Chromium/Chrome without crashing.

The occurred when 1) the `SourceBuffer.mode` is set to `"segments"` 2) a buffer is appended to `SourceBuffer` 3) `timestampOffset` is set. 

`mediaSource.sourceBuffers[0].appendBuffer(chunks.shift());` within `"waiting"` event also caused error.

**Comment by guest271314** [comment]
@jdm Using code that outputs first part of expected result (playback of media fragments recorded using `MediaRecorder` is sequence at a single `<video>` element) still using `SourceBuffer.mode` set to `"sequence"` still crashes browser tab at Chromium when `HTMLMediaElement.captureStream()` is called with `<video>`  `.src` set to `MediaSource`. There are two separate issues. Will try to separate the concerns and make two tests.

**Comment by guest271314** [comment]
@jdm Created test for `HTMLMediaElement.captureStream()` where `.src` is set to `MediaSource`. When `addtrack` event of `MediaStream` is dispatched the tab crashes. 

Not sure if the issue is related to Issue 141906: Disable 'Save Video As' option in right-click menu for elements using Media Source API https://bugs.chromium.org/p/chromium/issues/detail?id=141906, https://src.chromium.org/viewvc/chrome/trunk/src/webkit/media/webmediaplayer_impl.cc?r1=151151&r2=151150&pathrev=151151.

How should the pull request be created to avoid the issue that occurred above?

**Comment by guest271314** [comment]
Chromium issue  https://bugs.chromium.org/p/chromium/issues/detail?id=943484&q=component%3AInternals%3EMedia%3ESource

**Comment by Pehrsons** [comment]
FWIW this is how it looks when the harness comes across a crash in Mozilla's infra:
https://treeherder.mozilla.org/#/jobs?repo=try&selectedJob=229277411&revision=91e87e10c3e3e78ad839364be244d66ac5705024

**Comment by guest271314** [comment]
@Pehrsons  This bug has been ongoing for some time now. The code at the linked Chromium issue narrows code down to `MediaStream` (`HTMLMediaElement.captureStream()`) portion of the bug. When first tried at plnkr the tab crashed at first `addtrack` event. Just tried again and the tab crashed at second `addtrack` event. 

Not entirely sure if the tab crashing is due to `MediaSource` or `MediaStream` implementation, or both, at Chromium.

What is the correct approach to writing this test and creating the corresponding pull request?

**Comment by guest271314** [comment]
@Pehrsons Can you reproduce the tab crash described at Chromium/Chrome using this code https://bugs.chromium.org/p/chromium/issues/attachmentText?aid=384847?

**Comment by jdm** [comment]
@guest271314 You will want to follow the second instructions that I linked which opens a full request against this repository instead of your fork.

**Comment by guest271314** [comment]
@jdm Tried again https://github.com/guest271314/web-platform-tests/pull/3/commits

**Comment by guest271314** [comment]
@jdm This is the commit that is the pull request https://github.com/guest271314/web-platform-tests/blob/20ee21bb602846e4335a7e4e72835a85a193b9de/media-source/mediasource-htmlmediaelement-capturestream.html. How to proceed?

**Comment by jdm** [comment]
@guest271314 https://github.com/web-platform-tests/wpt/compare/master...guest271314:master will allow you to create a pull request against this repository from any branch that exists on your fork.

**Comment by guest271314** [comment]
@jdm This is the pull request https://github.com/web-platform-tests/wpt/pull/15963. There is probably an issue. Can you review the request and suggest the necessary changes?

**Comment by jdm** [comment]
I am not a good person to review it, since I am not familiar with the APIs being tested.

**Comment by guest271314** [comment]
@jdm  Was referring to the pull request itself, not the API's being tested. This code https://github.com/web-platform-tests/wpt/pull/15963/commits/4ec675380896ad787270e4a46430d691fbb6f786 is essentially a duplicate of https://github.com/web-platform-tests/wpt/pull/15963/commits/cc69d844995a973785df73ab6157253a239ac8a4. The latter is the code that should be incorporated into `media-source` and/or `mediacapture-fromelement` directories. This code https://github.com/web-platform-tests/wpt/pull/15963/commits/0fdd2368c1402795e665d19da9205beb07b3653d is already an open pull request at wpt.

**Comment by guest271314** [comment]
@jdm Your feedback has been helpful.

**Comment by guest271314** [comment]
@Pehrsons https://github.com/w3c/mediacapture-record/issues/166
