### ISSUE TITLE
Reorganizing documentation (2019)

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#15824]
The project's documentation (available online at https://web-platform-tests.org) has grown somewhat disorganized over the past few years. @zcorpan and I are planning to reorganize the content to address some of [the issues that have been filed](https://github.com/web-platform-tests/wpt/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) and recognize the perspective gained from [the 2018 WPT survey](https://docs.google.com/spreadsheets/d/1HFFXXxVhGy0sT4BAzvegIb-rfGgQHaT5ZjTMO_bggQE). To give a sense for what we have in mind, [here's a diagram of the current site's organization](https://user-images.githubusercontent.com/677252/54238586-41017d80-44ef-11e9-9320-b8f766a0885f.png), and [here's a version that describes some modifications](https://user-images.githubusercontent.com/677252/54238589-43fc6e00-44ef-11e9-9a53-faac75e76898.png).

We recognize a bit of tension between the different ways we could conduct this work and submit the result. The preferred git workflow includes many small, targeted patches. However, restructuring a large body of text in a holistic way will tend towards more wide-spanning change sets. Taking a cue from [similar work @gsnedders conducted back in 2017](https://github.com/gsnedders/wpt-docs/issues?utf8=%E2%9C%93&q=), we're going to collaborate on a restructuring from a fork of WPT.

The fork is: https://github.com/bocoup/wpt-docs 

And the site can be viewed at: https://bocoup.github.io/wpt-docs/ 

Feedback about the high-level approach as well as any specific issues are of course welcome.

**Comment by jugglinmike** [comment]
Here's an affinity diagram which groups the 2018 survey responses according to theme:

![affinity-annotated](https://user-images.githubusercontent.com/677252/54566770-3429d180-49a8-11e9-8a73-6cf03f1daa52.png)

Each item includes a number prefixed with the letter "U". This is a user identifier and describes the row in [the survey response spreadsheet](https://docs.google.com/spreadsheets/d/1HFFXXxVhGy0sT4BAzvegIb-rfGgQHaT5ZjTMO_bggQE) from which the item was derived.

We intentionally omitted responses to questions for new ideas in order to keep the diagram focused on patterns in users' direct experience.

/cc @jorydotcom since she helped put the survey together. Thanks, Jory!

**Comment by foolip** [comment]
@jugglinmike should this issue be closed now?

**Comment by jugglinmike** [comment]
Among the improvements we identified here, there's still one that hasn't been merged: gh-17189. It's in the late stage of review, though, so I don't think there's any value in keeping this issue open.
