### ISSUE TITLE
RTCRtpTransceiver.https.html - check that stop() fires mute and removetrack events.

### ISSUE THREAD

**Issue by jan-ivar** [web-platform-tests/wpt#15846]
Tests https://github.com/w3c/webrtc-pc/issues/1812.

**Comment by dontcallmedom** [comment]
done in https://github.com/web-platform-tests/wpt/commit/2a0747508e5f45d449616207e89ddd7b83abc13d#diff-2878d90936c40c4a1eb3e3d833ee9155
