### ISSUE TITLE
Use eventFired in buffer-full-add-after-full-event test to avoid flakiness

### ISSUE THREAD

**Issue by hawkinsw** [web-platform-tests/wpt#15849]
@yoavweiss

I have been looking at buffer-full-add-after-full-event test for a while today and realized that it might be possible to fight the test's flakiness by using the eventFired flag a second time as a more robust way to wait for the random resource to be loaded in clearAndAddAnotherEntryToBuffer. I made the change locally and it seems to work decently. If you would be amenable to fixing the test in such a way, I'd be happy to submit a PR and get your feedback. 

Thanks!
Will

**Comment by yoavweiss** [comment]
The change you have in mind is not 100% clear to me, but a PR of your change might be the best and easiest way to explain it :)

On my end, I haven't seen flakiness since I added an extra task, but admittedly, that's not ideal. Are you still seeing flakiness in the current version? If so, I agree that fixing it is important.

**Comment by whh8b** [comment]
Adding @mstange is a person to watch this.

**Comment by whh8b** [comment]
> The change you have in mind is not 100% clear to me, but a PR of your change might be the best and easiest way to explain it :)
> 
> On my end, I haven't seen flakiness since I added an extra task, but admittedly, that's not ideal. Are you still seeing flakiness in the current version? If so, I agree that fixing it is important.

Unfortunately we are still seeing some oddity with the tests. It seems to be timing-related, but honestly I don't know since I'm relatively new to this code. 

I am going to send you a quick little PR and see what you think. Like you said, seeing the code is probably the best way to explain :-)

**Comment by whh8b** [comment]
@yoavweiss Just FYI: I proposed a change that *should* resolve the issue. I'd love your thoughts.
