### ISSUE TITLE
'unhandledrejection' in payment-request/updateWith-method-pmi-handling-manual.https.html

### ISSUE THREAD

**Issue by danyao** [web-platform-tests/wpt#15861]
The individual test cases in [payment-request/updateWith-method-pmi-handling-manual.https.html](https://github.com/web-platform-tests/wpt/blob/master/payment-request/updateWith-method-pmi-handling-manual.https.html) seem to pass all test assertions, but still end up with a test harness error due to an `unhandledrejection` event firing.

I can't figure out where the unhandled rejection comes from. All of these tests call `PaymentRequestUpdateEvent.updateWith(invalidDetails)`, where `invalidDetails` contains an invalid payment method identifier. This causes the update to be aborted with a `RangeError` and rejects `request.[[showPromise]]`, both are expected according to the [spec][spec]. The test verifies this rejection with `await promise_rejects(t, new RangeError(), showPromise);`.  What's strange is that the test report shows a pass for the test but with a harness error:

```
Harness status: Error

Failed to construct 'PaymentDetailsUpdate': Invalid payment method identifier format
undefined:undefined:undefined
```

[spec]: https://w3c.github.io/payment-request/#update-a-paymentrequest-s-details-algorithm

It's also weird that the last test case on the page doesn't exhibit this behavior. The only difference between it and the others is that it calls `done()` right after the test method ([here][testcode]). I wonder if this is a race condition between `done()` and the `unhandledrejection` event handler triggering.

[testcode]: https://github.com/web-platform-tests/wpt/blob/master/payment-request/updateWith-method-pmi-handling-manual.https.html#L133

Because of this problem, the test page has to be reloaded after each test case. I'd like to fix it, but need help figuring out where the unhandled rejection comes from.

@marcoscaceres any ideas?

**Comment by marcoscaceres** [comment]
>  I wonder if this is a race condition between done() and the unhandledrejection event handler triggering.

Yes, that's definitely a bug... but not *the bug*.  

Looking into it.

**Comment by marcoscaceres** [comment]
This is really odd.... it's also as if Chrome is throwing an exception on `updateWith()`, but it's not actually throwing one. Testing in Safari, the test seems to work ok (they don't actually support the RangeError, but aborting works as expected). 

Firefox is sadly broken still so can't even test the first part.  

Sending a patch... but it doesn't seem to help. But at least the test runs in Safari.

**Comment by marcoscaceres** [comment]
Ok, sent https://github.com/web-platform-tests/wpt/pull/15891 ... at least it fixes the `done()` one.

**Comment by marcoscaceres** [comment]
If you figure it out, I’d be super interested to hear what is wrong. It’s likely the test, but I’m also at a loss.

**Comment by gsnedders** [comment]
@danyao pinning seems to be some global thing, which isn't that useful for a single test bug :)

**Comment by danyao** [comment]
Oops sorry I didn't realize this. Thanks @gsnedders!

**Comment by marcoscaceres** [comment]
Closing, as this test no longer exists.
