### ISSUE TITLE
Taskcluster isn't running any jobs on master after switching to Checks API

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#16026]
All jobs are empty no-op because `./wpt test-job` only produces `lint` and `manifest_upload`.

Example:
https://tools.taskcluster.net/groups/US_q1KYrQwCC4iA1taLBMw/tasks/CF899lETREeQKJdH9GZQZQ/runs/0/logs/public%2Flogs%2Flive.log#L122
(from https://github.com/web-platform-tests/wpt/runs/83097404)

**Comment by Hexcles** [comment]
I can also confirm this is NOT caused by #16021 . Runs before that also had the same issue.

**Comment by Hexcles** [comment]
Still broken after the revert. Perhaps #15724 was the culprit? cc @gsnedders

**Comment by Hexcles** [comment]
The tricky thing is: how do verity a setup would work on master? Shall we make a fork of wpt with everything (checks, apps, etc.) wired up to verify CI changes?

**Comment by jgraham** [comment]
That's basically what I did to test out the migration of manifest upload to the actions API (although that case was even harder because not everywhere has actions enabled).

**Comment by jgraham** [comment]
Should be fixed by #16030

**Comment by gsnedders** [comment]
https://wpt.fyi/runs?label=master&max-count=100&from=2019-03-18T00%3A00 shows plenty of TC runs again, closing.
