### ISSUE TITLE
Move chrome_android to ExecutorWebDriver by default

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#16056]
Split out of https://github.com/web-platform-tests/wpt/issues/12374. Primarily waiting for someone with `chrome_android` working to test this all works before changing the default.

**Comment by Hexcles** [comment]
I can take a look. Do I just need to change the base class?

**Comment by gsnedders** [comment]
See caf4aa367ef. This is probably roughly similar.
