### ISSUE TITLE
Move Edge to edge_webdriver by default

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#16054]
Split from https://github.com/web-platform-tests/wpt/issues/12374:

> Edge is mostly waiting for Windows 10 RS5 to rollout to more users (given plenty of people still don't have it)

I don't know if we should flip the switch now? I know @foolip has been having problems, but I don't know if they're actually worse with this than Selenium.

**Comment by foolip** [comment]
This is the setup we use in Azure Pipelines anyway, so I say let's do it. The only reason I could see not to is if @mustjab or @thejohnjansen think the trouble we're having in Azure Pipelines wouldn't occur if we used Selenium instead.

**Comment by gsnedders** [comment]
Or if we care about older releases of Edge, I guess.

**Comment by foolip** [comment]
I don't think that would be worth keeping working, but I'll let @mustjab and @thejohnjansen speak to that.

**Comment by thejohnjansen** [comment]
I have no reason to believe that the issues with Azure Pipelines would not occur if we used Selenium instead, and I also don't think we should worry about older releases of Edge... :-)

**Comment by thejohnjansen** [comment]
So, I think this should be fine.

**Comment by foolip** [comment]
@gsnedders please go ahead :)

**Comment by foolip** [comment]
@gsnedders given that we're now using edgechromium on Azure Pipelines it won't matter all that much, but this would probably still be nice cleanup. Lowering prio though.

**Comment by foolip** [comment]
This is about EdgeHTML (Edge 12-18) and there's a new product called "edgechromium" for Edge 79+. Closing because I don't think we should be doing any cleanup for EdgeHTML, only eventually remove support.
