### ISSUE TITLE
web-platform-tests.org should feature wpt.fyi

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#16089]
Recently, I learned from a few Chromium developers that they were not aware of wpt.fyi, only web-platform-tests.org.

Apparently, web-platform-tests.org has done a good SEO job so it's relatively easy to find. We should feature wpt.fyi on web-platform-tests.org in a dominant place.

**Comment by foolip** [comment]
We should probably also link it in the README.md prominently, unless that is collapsed into just a pointed to web-platform-tests.org.

**Comment by jugglinmike** [comment]
Resolved via gh-18328
