### ISSUE TITLE
Collect screenshots from Edge on Azure Pipelines

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#16121]
https://github.com/web-platform-tests/wpt/pull/16107 is merged, but did not include the `--log-wptscreenshot` bit needed to save screenshots.

Since this hasn't been tested on Windows or with Edge before, some validation is probably a good idea before just merging a change for that to master.

**Comment by foolip** [comment]
@Hexcles

**Comment by Hexcles** [comment]
Isn't `--log-wptscreenshot` already there before that change? https://github.com/web-platform-tests/wpt/pull/16107/files#diff-79a889188c51195ad1884f90e264f03cR189 I think it was added by me.

**Comment by foolip** [comment]
Oh. So, maybe this will work already? I guess we'll see after the first scheduled run that succeeds.

**Comment by foolip** [comment]
It worked!

https://staging.wpt.fyi/results/css/css-tables/border-conflict-resolution.html?run_id=5662320726376448&run_id=6029620302315520&run_id=6076783594045440&run_id=6735801362677760
