### ISSUE TITLE
No recent stable Firefox runs on wpt.fyi

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#16132]
https://wpt.fyi/runs?max-count=100&label=stable

There haven't been any Firefox runs since March 12.

**Comment by LukeZielinski** [comment]
@jgraham Hi James, are you able to take a look?

**Comment by jgraham** [comment]
So there are at least two problems here. One is that we accidentially broke running epoch branches for a while; that was https://github.com/web-platform-tests/wpt/pull/16117. The other issue seems to be that we're trying to download geckodriver from the wrong location on beta/stable c.f. https://tools.taskcluster.net/groups/cG42DIXlS8qiHTMF0P5jSQ/tasks/fj5cgxa4QE66yuZqgIDEeQ/runs/0/logs/public%2Flogs%2Flive.log

**Comment by jgraham** [comment]
Sorry, not geckodriver, the test prefs.

**Comment by foolip** [comment]
https://tools.taskcluster.net/groups/cG42DIXlS8qiHTMF0P5jSQ is the most recent run, found via https://api.github.com/repos/web-platform-tests/wpt/commits/ea8b7ff29a15265e3bf73364f49e22426a5b97d5/statuses.

**Comment by Hexcles** [comment]
Any updates? Looks like we are still not getting any Firefox stable runs.

**Comment by jgraham** [comment]
I landed https://github.com/web-platform-tests/wpt/pull/16176 but since we only get stable runs once a day, it's hard to be sure if it made a difference.

**Comment by foolip** [comment]
We're running Edge and Safari stable every 6 hours on Azure Pipelines now, perhaps we should increase the cadence for Taskcluster as well just to iterate more quickly in cases like this? Also makes a fluke missing run less serious.

**Comment by Hexcles** [comment]
Looks like we have stable runs https://wpt.fyi/results/?run_id=5818496017498112&run_id=5378137953140736&run_id=5279026683838464&run_id=5419764172193792

Thanks, @jgraham !

**Comment by foolip** [comment]
Yay, thanks @jgraham!
