### ISSUE TITLE
edge_webdriver includes '\r' (CR) in some test names

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#16187]
Failure examples are mostly from [WebCryptoAPI/generateKey](https://wpt.fyi/results/WebCryptoAPI/generateKey), especially those with query params. e.g. `successes_RSA-OAEP.https.any.html?1-10` becomes `successes_RSA-OAEP.https.any.html?1-10\r` in edge_webdriver.

This is preventing wpt.fyi from ingesting the run because [GCS doesn't allow CR or LF in paths](https://cloud.google.com/storage/docs/naming#objectnames).

Also, this is the first time I see the error and there's been only one instance since we started running edge_webdriver. Here's the build: ~~https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=11520~~ https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=12809&view=results

**Comment by Hexcles** [comment]
Raising to "urgent" as this is now *always* happening.

**Comment by Hexcles** [comment]
cc @foolip

**Comment by gsnedders** [comment]
In the *test names* in wptreport.json?

**Comment by gsnedders** [comment]
Looking at the wptreport.json data in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=11520 I can't find `successes_RSA-OAEP.https.any.html?1-10\r`?

**Comment by Hexcles** [comment]
@gsnedders yes, the `"test"` field in `wptreport.json. That was probably a bad example; try searching for "successes_RSA-OAEP.https.any.html?101-110\r" (it's in `wpt_report_16.json`).

**Comment by gsnedders** [comment]
I still can't find that in that Azure job? Only "test": "/WebCryptoAPI/generateKey/successes_RSA-OAEP.https.any.html?101-110"?

**Comment by Hexcles** [comment]
I might've lost myself among multiple Azure tabs and pasted the wrong link.

Here's a newer build where you can also see the issue: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=12809&view=results

**Comment by Hexcles** [comment]
Found some stack trace when `\r` was seen in test names:

```
Unterminated string constant
Traceback (most recent call last):
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 282, in _run
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 358, in do_testharness
    self.script_resume % format_map, async=True)
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 38, in execute_script
    return method(script)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 642, in execute_async_script
    return self.send_session_command("POST", "execute/async", body)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 508, in send_session_command
    return self.send_command(method, url, body)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 472, in send_command
    raise err
JavascriptErrorException: javascript error (500): Unterminated string constant
```

**Comment by Hexcles** [comment]
FWIW, Edge stable on BuildBot is working fine: https://wpt.fyi/results/WebCryptoAPI/generateKey?q=successes_RSA-OAEP.https.any.html&run_id=5637912473370624&run_id=5103254845259776&run_id=5136145704812544&run_id=5729575162085376

**Comment by Hexcles** [comment]
Downgrading this to backlog because although we haven't figured out why this is happening, it's been worked around on the wpt.fyi side by https://github.com/web-platform-tests/wpt.fyi/pull/1274

**Comment by foolip** [comment]
This applies to EdgeHTML (Edge 12-18) which we're not running any longer, so no bugs around it are realistically ever going to be fixed. Closing.
