### ISSUE TITLE
Run wptrunner tests on python 3 on macOS

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#16207]
Ref #10128.

The macOS bot on Azure has python 3.7 installed, but wptrunner is broken (even more) there because of #16178. Once that's fixed, it should be as simple as adding `py37-*` to the `envlist` in `tools/wptrunner/tox.ini`.

**Comment by Ms2ger** [comment]
CC @foolip

**Comment by Hexcles** [comment]
> The macOS bot on Azure has python 3.7 installed

I'm not a Mac power user. What is the de-facto/recommended way to get Python 3 on macOS? Homebrew?

**Comment by Ms2ger** [comment]
`brew install python` (which means python3) was the suggestion I got, but that failed because it was already installed.

**Comment by foolip** [comment]
Does that mean the `python3` binary already exists? If so I guess it's installed by Azure Pipelines, and some steps to make it the default python is all that's needed?

**Comment by Ms2ger** [comment]
No, what's needed is fixing #16178, so we don't hit SyntaxErrors when running the tests under python 3.7. Once that's done, it should be as simple as adding py37-* to the envlist in tools/wptrunner/tox.ini. (TC runs python 3.6, which isn't affected.)

**Comment by gsnedders** [comment]
#20725 resolved this.
