### ISSUE TITLE
WPT Lint Failed due to OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#16224]
Exported CL failed at the Lint task - https://github.com/web-platform-tests/wpt/pull/16165

The Lint failures are as follow:
https://tools.taskcluster.net/groups/akeNchveQKal63tO-kI8HQ/tasks/eGOFUk-7SWu7zBnQ6bOfHA/runs/0/logs/public%2Flogs%2Flive.log

Seems to be an infrastructure issue

**Comment by KyleJu** [comment]
@Hexcles

**Comment by KyleJu** [comment]
#h16210  another instance related to this bug

**Comment by Hexcles** [comment]
Whatever the bug was, it seems someone has fixed it. All the blocked PRs passed lints after being rebased.
