### ISSUE TITLE
[wptrunner] option to --binary-arg cannot accept argument containing leading dash

### ISSUE THREAD

**Issue by hawkinsw** [web-platform-tests/wpt#16232]
If the user wants to give an argument to `--binary-argument` that contains a leading dash (e.g., `-devtools`), it is not recognized (thanks to argparse). No amount of escape characters help -- they make argparse happy, but wptrunner copies them verbatim to the command it issues when starting the binary.

The fix is easy and I have a patch that I will be publishing immediately after filing this bug. 

Thanks for all the great work that you do maintaining this system!

Will

**Comment by gsnedders** [comment]
wontfix for the reason described in #16233
