### ISSUE TITLE
Figure out cross-browser webxr testing story

### ISSUE THREAD

**Issue by Manishearth** [web-platform-tests/wpt#16294]
Currently the webxr tests use an `XRTest` interface from Chromium, which wraps Chromium's internal `MockVRService` implementation

(which eventually goes through `mojo` APIs that I haven't yet been able to fully chase down)

Currently Chromium's `XRTest` only allows for spinning up and shutting down XR devices, but presumably it will need more stuff, like pose emulation.

Perhaps we should work together on a common well-documented `XRTest` API that supports all of this, allowing us to write tests that can handle things like pose information and input? I'm planning on writing an `XRTest` for Servo that hooks into our VR backends with a dummy backend that can be sent pose information, among other things, but I don't want to make additions to `XRTest` without coordinating with others.

cc @toji @klausw  @asajeffrey

**Comment by Manishearth** [comment]
Ah, this is being done at https://github.com/immersive-web/webxr-test-api 

Probably should be mentioned in a readme somewhere

**Comment by svillar** [comment]
@Manishearth I've seen some activity at the [webxr-test-api ](https://github.com/immersive-web/webxr-test-api) although not much and the webxr WPT are still chromium specific. What's the status of this work?

**Comment by Manishearth** [comment]
@svillar the tests are not chromium specific? They work fine for us on Servo, we just implement that API

**Comment by Manishearth** [comment]
update: Since this issue was filed I've worked with Alex and we've improved the testing API in https://github.com/immersive-web/webxr-test-api

**Comment by svillar** [comment]
> @svillar the tests are not chromium specific? They work fine for us on Servo, we just implement that API

I meant that there is just one implementation in WPT which is chromium specific. IMHO this should be kept downstream. I'll add the implementation in WebKit too.

**Comment by Manishearth** [comment]
> I meant that there is just one implementation in WPT which is chromium specific

Right, this is due to a quirk of chromium's build system IIRC. Other browsers should just implement the XRTest interface as a regular interface, the intent is _not_ for everyone to check in browser-specific JS code.

If you can keep the Webkit implementation in webkit, that would be good.
