### ISSUE TITLE
Infra: Can't close a PR

### ISSUE THREAD

**Issue by alvestrand** [web-platform-tests/wpt#16316]
This CL doesn't close when I close it:

https://github.com/web-platform-tests/wpt/pull/13902

Can someone figure out why?
Tagging @foolip

**Comment by gsnedders** [comment]
I would guess some GitHub bug, or a dodgy connection (on either end!) meaning the close button press didn't get processed?

**Comment by foolip** [comment]
I also can't close it. One thing that's unusual about the PR is the number of commits and files touched. Seems like there's a GitHub bug here.

**Comment by foolip** [comment]
I've sent this message to GitHub:
> As reported in https://github.com/web-platform-tests/wpt/issues/16316, we seem to have a PR which can't be closed:
> https://github.com/web-platform-tests/wpt/issues/16316
> 
> I tried closing it now and it first seems to succeed, but when reloading it's still open. Seems likely to be a GitHub bug.

**Comment by foolip** [comment]
GitHub support asked me if there were any errors in the console when trying to close the PR, and I just got back to them saying there isn't. Still unable to close the PR.

**Comment by foolip** [comment]
Resolved with some help from GitHub support: https://github.com/web-platform-tests/wpt/pull/13902#issuecomment-538756277
