### ISSUE TITLE
[pointerevents] pointerlock/pointerevent_coordinates_when_locked.html assumes pointerlockchange event is synchronous

### ISSUE THREAD

**Issue by graouts** [web-platform-tests/wpt#16406]
Cc'ing @EiraGe as the author of this test.

I wonder if there is an issue in the way the test at pointerevents/pointerlock/pointerevent_coordinates_when_locked.html is written. The pointer commands (via `new test_driver.Actions()`) are all dispatched in one command and thus rely on the `pointerlockchange` events to be delivered synchronously after calling `div1.requestPointerLock()` in the `pointerdown` event handler.

The [spec for `pointerlockchange`](https://w3c.github.io/pointerlock/#pointerlockchange-and-pointerlockerror-events) says this:

> Two events are used to communicate pointer lock state change or an error in changing state. They are named pointerlockchange and pointerlockerror. If pointer lock is entered or exited for any reason a pointerlockchange event must be sent.
>
> User agents must deliver these events by queuing a task to fire an event of the appropriate name with its bubbles attribute [DOM4] set to false to the pointer lock target element's node document.

As such I think the test is in error and the pointer commands should be split in two batches:

1. First, pointermove and pointerdown
1. Second, after pointer lock was granted, fire additional pointermove and the final pointerup.

If that is deemed correct, I'm happy to file a PR to rectify this.

**Comment by graouts** [comment]
This was found as part of https://bugs.webkit.org/show_bug.cgi?id=197007.

**Comment by EiraGe** [comment]
My understanding is the test are sending 10 moves after the down, so it will still work if the lock change happen in the middle. But feel free to change it to whatever you think is correct.

**Comment by EiraGe** [comment]
Ok, I think I figure something out.
As @graouts pointed out:
On Safari, requestPointerLock doesn't work within a "pointerdown" event handler. 
On Firefox, the additional moves must be send separately.

And also the target area seems too large that I got "move target out of bounds" error with Safari

I'll send a PR to fix the test.
