### ISSUE TITLE
Question about testing function's instance length

### ISSUE THREAD

**Issue by xtuc** [web-platform-tests/wpt#16420]
In WebAssembly JS API tests, we usually ensured that the functions had the correct length (number of arguments).

However, I'm not able to find similar length tests for other JS APIs. For instance `fetch.length` seems to vary across implementation and it's not tested here.

Is there are reason about it? Otherwise I'm happy to add that specific test.

**Comment by gsnedders** [comment]
Is this not tested by idlharness.js? Specifically in this case, the test it generates with the name "Window interface: operation fetch(RequestInfo, RequestInit)" contains a test for this.
