### ISSUE TITLE
Possible race condition in get_free_port

### ISSUE THREAD

**Issue by georgeroman** [web-platform-tests/wpt#16754]
I am experimenting with WebDriver in Servo and came across with what might be a race condition in the [`get_free_port`](https://github.com/servo/servo/blob/master/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/base.py#L39) function. That is, sometimes when `wptrunner` runs the tests in parallel, two webdriver instances get assigned the same port.
You can find all the details here: https://github.com/servo/servo/issues/22619#issuecomment-490587018.

**Comment by jdm** [comment]
This may be a symptom of how Servo's integration with the webdriver server is different from other browsers. My understanding is that other browsers have a separate server that spawns instances of the browser, whereas Servo has the server integrated directly into each instance of the browser. If there are multiple threads starting multiple browsers, maybe we could use a mutex inside [this code](https://github.com/servo/servo/blob/a6c7fc426cfe3b96a3494432883d07d439d19b50/tests/wpt/web-platform-tests/tools/wptrunner/wptrunner/browsers/servodriver.py#L97-L98) to avoid the race.

**Comment by gsnedders** [comment]
I do wonder if every usage of `get_free_port` is racy in the face of parallel test execution?

This code has annoyed me for a long time, because it seems prone to raciness and there are multiple ways this could fail (heck, some other process could open that port!). It would definitely be nice to fix this more generally, though I don't really know how…

**Comment by gsnedders** [comment]
From @georgeroman in #16819:

> I think [every usage ] is [racy] since every usage of the function follows the same pattern of getting the first available port followed by saving the chosen port in `excluded_ports`.

So reopening for everywhere else.

**Comment by gsnedders** [comment]
And for those wondering why we don't just use port "0" (i.e., let the system assign us a port): this is used when we need to pass an argument in (typically as a subprocess command-line argument) giving the port to use.
