### ISSUE TITLE
Variant tests with parens and pipes in URL fail to run on Safari

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#17027]
https://wpt.fyi/results/html/dom?run_id=264030002&run_id=248260003&run_id=262080001&run_id=234440001 has the four variants of Safari on macOS that we currently run: stable + preview on Azure Pipelines and Buildbot.

All of them fail `/html/dom/interfaces.https.html?exclude=(Document|Window|HTML.*)` and `/html/dom/interfaces.https.html?include=(Document|Window)` like this:

```
ERROR message: Could not parse requested URL 'https://web-platform.test:8443/html/dom/interfaces.https.html?include=(Document|Window)'
Traceback (most recent call last):
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 282, in _run
    self.result = True, self.func(self.protocol, self.url, self.timeout)
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 351, in do_testharness
    protocol.webdriver.url = url
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 20, in inner
    return func(self, *args, **kwargs)
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 521, in url
    return self.send_session_command("POST", "url", body)
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 508, in send_session_command
    return self.send_command(method, url, body)
  File "/Users/kazooie/worker/macOS_Chunked_Runner/build/tools/webdriver/webdriver/client.py", line 472, in send_command
    raise err
InvalidArgumentException: invalid argument (400): Could not parse requested URL 'https://web-platform.test:8443/html/dom/interfaces.https.html?include=(Document|Window)'
```

Python on macOS doesn't like `https://web-platform.test:8443/html/dom/interfaces.https.html?include=(Document|Window)`, and I suspect it's because of the parenthesis or pipe characters.

@zcorpan do you know where this pipe character is put into the manifest? I'd like to try escaping it as `%7C` to see if that fixes the problem.

**Comment by gsnedders** [comment]
That's not Python on macOS not liking that, it's the WebDriver server (in this case in SafariDriver) responding with 400 Bad Request. @burg? I presume it's something like using a URL parser that treats the pipe character as invalid (which it is per RFC3986, for example).

**Comment by zcorpan** [comment]
From what I understand of https://url.spec.whatwg.org/#query-state the pipe character is a validation error but does not return failure (i.e., it should parse successfully).

So I think there are multiple ways to address this problem, not mutually exclusive:

* Fix SafariDriver's URL parser
* URL-encode the URL so that invalid characters are URL-escaped before entering the manifest
* Change tests to have valid URL strings in `<meta name=variant content=...>`
* Previous point + lint checker

**Comment by gsnedders** [comment]
If I'm reading the URL spec correctly, there's no valid URL equivalent to `https://web-platform.test:8443/html/dom/interfaces.https.html?include=(Document|Window)` (escaping it doesn't provide an equivalent URL, which is part of https://github.com/whatwg/url/issues/369).

**Comment by foolip** [comment]
@gsnedders in this instance does it matter if the URL is considered equivalent, as long as the code that parses `include=(Document|Window)` (where?) handles the URL correctly?

Regardless, if the bug is in SafariDriver and it only affects a few tests, leaving this blocked on a SafariDriver fix might be reasonable. @burg can you file a bug, or should one be filed through https://feedbackassistant.apple.com/?

**Comment by burg** [comment]
Please file via the feedback assistant. I’m on parent leave until August.

**Comment by foolip** [comment]
https://wpt.fyi/results/html/dom?run_id=352740001&run_id=376000001 shows that this works in WebKitGTK but not Safari.

@clopez could you look into this and file an issue for safaridriver, or for WebKit if you can spot the problem there?

**Comment by gsnedders** [comment]
IIRC, @burg filed a Radar issue for this.

**Comment by burg** [comment]
I have filed an issue and haven't looked into it yet.

**Comment by foolip** [comment]
Alright, great! Is there a public ID for it in case I want to reference it?

**Comment by burg** [comment]
It's tracked internally as rdar://problem/55240821 <rdar://problem/55240821>

**Comment by burg** [comment]
Sorry about the crazy wait on this one. If all goes well, the fix should be out with Safari Technology Preview 106.

**Comment by foolip** [comment]
Sweet, thanks for fixing this, Brian!

**Comment by foolip** [comment]
It looks like this was already fixed in STP 105:
https://wpt.fyi/results/html/dom?run_id=510170002&run_id=503710001

Yay!

**Comment by burg** [comment]
Oops, yes this was recently fixed. 

Brian (he/him)
