### ISSUE TITLE
Chrome fails infrastructure/testdriver/actions/actionsWithKeyPressed.html on Mac

### ISSUE THREAD

**Issue by georgeroman** [web-platform-tests/wpt#17296]
https://github.com/web-platform-tests/wpt/pull/17212 fails the infrastructure tests due to an unrelated test failure occurring in [`actionsWithKeyPressed.html`](https://github.com/web-platform-tests/wpt/blob/81fc948a5e4138c0aba22e3f670789f7ac0f99c1/infrastructure/testdriver/actions/actionsWithKeyPressed.html). It seems that this test was added quite recently: https://github.com/web-platform-tests/wpt/pull/16475.

```
 ▶ Unexpected subtest result in /infrastructure/testdriver/actions/actionsWithKeyPressed.html:
  │ FAIL [expected PASS] TestDriver actions: actions with key pressed
  │   → assert_array_equals: lengths differ, expected 3 got 1
  │ 
  │     at Test.<anonymous> (http://web-platform.test:8000/infrastructure/testdriver/actions/actionsWithKeyPressed.html:64:34)
  │     at Test.step (http://web-platform.test:8000/resources/testharness.js:1594:25)
  └     at http://web-platform.test:8000/resources/testharness.js:1634:32
```

**Comment by Hexcles** [comment]
I checked out #17212 and couldn't find this failure. Did it go away after you retried/rebased?

**Comment by georgeroman** [comment]
It’s in the second failed build (Azure Pipelines (infrastructure/ tests: macOS)) from here: https://github.com/web-platform-tests/wpt/pull/17212/checks?check_run_id=149123620

**Comment by Hexcles** [comment]
`infrastructure/testdriver/actions/elementPosition.html` also fails on Chrome for macOS.

**Comment by Hexcles** [comment]
Reopening this because #17415 did not fix the issue, but only worked around it.

**Comment by stephenmcgruer** [comment]
So the entire directory was skipped in https://github.com/web-platform-tests/wpt/pull/18934 (Sep 2019), due to https://bugs.chromium.org/p/chromedriver/issues/detail?id=3114

Then https://bugs.chromium.org/p/chromedriver/issues/detail?id=3114 was fixed in https://github.com/web-platform-tests/wpt/pull/19555 (Oct 2019) and the tests re-enabled in https://github.com/web-platform-tests/wpt/pull/19497

In short, this seems fixed.
