### ISSUE TITLE
Azure Pipelines scheduled triggers need to be migrated to YAML

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#17342]
Looking at triggers in the pipeline editor today I see this:
![image](https://user-images.githubusercontent.com/498917/59497921-abcaa800-8e94-11e9-809c-8d4d33c9432e.png)

> You can no longer define scheduled triggers in the editor. Instead, you must add schedules to your YAML file. For more information, see https://go.microsoft.com/fwlink/?linkid=2080841 

However, the link leads to https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema and I can't see any documentation on how to migrate the schedule triggers to YAML.

@mustjab @thejohnjansen could you ask if this already works but isn't documented, or what we should do?

It appears that the scheduled runs are still getting triggered, but this could turn urgent if at any point they stop working, since the workaround before has been to make an edit and save them again.

**Comment by foolip** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#scheduled-triggers says:

> Scheduled builds are not yet supported in YAML syntax. After you create your YAML build pipeline, you can use pipeline settings to specify a scheduled trigger.

Hopefully this isn't true :)

**Comment by 1VIP** [comment]
CONTRIBUTING.md

**Comment by foolip** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#scheduled-triggers has been updated now, I'll try to put a PR together.

**Comment by foolip** [comment]
I've sent https://github.com/web-platform-tests/wpt/pull/18442, and when I went to remove the triggers in the screenshot at the top of this issue, I found they weren't there, not even in a disabled state. @thejohnjansen @mustjab did either of you remove them while trying to debug https://github.com/web-platform-tests/wpt/issues/18397? It doesn't matter since they'll be replaced, but it is odd because in my safari-technology-preview-updater repo I had to remove them manually.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18442 didn't work, a build should have been triggered 06:15 UTC (15 minutes ago) but wasn't.

**Comment by foolip** [comment]
Since the trigger originally configured in the Azure DevOps UI are no longer there, fixing this has become urgent :(

**Comment by foolip** [comment]
There's some chance the reason it didn't work was because the epochs/six_hourly branch wasn't updated in time. The configuration was on master, but locally I didn't see the epochs/six_hourly ref update a bit after 06:00, and looking at webhook activity it looks like it might have been updated at 06:32.

Waiting for another 6 hours to see if the next one will be triggered.

**Comment by foolip** [comment]
(The possible reason being that if the configuration isn't on the branch being triggered, it doesn't work.)

**Comment by foolip** [comment]
To verify that the configuration is working at all currently I've triggered a manual build for Edge Dev, Edge Canary, Safari and Safari Technology Preview: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=27211

**Comment by foolip** [comment]
Alright, it worked, https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=27268 is in progress!
