### ISSUE TITLE
WebDriver tests: Module already imported so cannot be rewritten

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#17384]
We are seeing `PytestAssertRewriteWarning` (see [assertion rewrite](https://docs.pytest.org/en/latest/assert.html#assert-introspection)) thrown by `pytest` from some files `webdriver/tests/`.

One example:
```bash
./wpt run --log-mach - --log-mach-level debug chrome /webdriver/tests/add_cookie/user_prompts.py /webdriver/tests/back/back.py
```

In the logs, you'll see:
```
<undetermined location>
  Module already imported so cannot be rewritten: tests.support.fixtures
```

**Comment by whimboo** [comment]
@Hexcles is that still happening for you?

**Comment by whimboo** [comment]
I've run the command as given in the initial comment and I'm not able to reproduce. If you still see it please re-open.
