### ISSUE TITLE
test_file_protocol has one too many slash in the expected file URI?

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#17385]
https://github.com/web-platform-tests/wpt/blob/376e2a8250c3824b794ec518ab320d8a82cedf95/webdriver/tests/navigate_to/navigate.py#L37

e.g. if doc root is `/var/wpt`, the expected URI would be `file:////var/wpt`, but if I'm reading the Appendix B & D.1 of [RFC 8089](https://tools.ietf.org/html/rfc8089) correctly, it should be `file:///var/wpt` instead?

**Comment by Hexcles** [comment]
@whimboo who wrote that test

**Comment by Hexcles** [comment]
also `test_get_current_url_file_protocol` in `webdriver/tests/get_current_url/get.py`

**Comment by whimboo** [comment]
Thanks for filing the issue! I'm going to fix that via https://bugzilla.mozilla.org/show_bug.cgi?id=1561196.

**Comment by whimboo** [comment]
This got merged 10 days ago.
