### ISSUE TITLE
Help needed about 2 tests in URL

### ISSUE THREAD

**Issue by hyspace** [web-platform-tests/wpt#17420]
Hi all,

I'm running the URL tests in this repository of an implementation of *WHATWG URL Living Standard*.

I have question about 2 URL tests.

1. 
```json
  {
    "input": "https://%e2%98%83",
    "base": "about:blank",
    "href": "https://xn--n3h/",
    "origin": "https://xn--n3h",
    "protocol": "https:",
    "username": "",
    "password": "",
    "host": "xn--n3h",
    "hostname": "xn--n3h",
    "port": "",
    "pathname": "/",
    "search": "",
    "hash": ""
  },
```
https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json#L4689

In this test, expected output of the hostname is `xn--n3h`. It is output of [Host parsing](https://url.spec.whatwg.org/#host-parsing) section.
In this section, the hostname will be *percent decoded* to `â\u0098\u0083` first, and then apply *domain to ASCII*. In [IDNA Table](https://unicode.org/Public/idna/12.1.0/IdnaMappingTable.txt), `\u0098` and `\u0083` match the row
```
0080..009F    ; disallowed                             # 1.1  <control-0080>..<control-009F>
```
A according to [IDNA processing](https://www.unicode.org/reports/tr46/#ProcessingStepMap), `disallowed` character should cause *failure* of processing.
Failure in *domain to ASCII* process will then cause the URL parsing failure.
> If asciiDomain is failure, validation error, return failure.

However, in this test, the result of parsing should be *successful*. I do not understand how can I get correct host value `xn--n3h`.

2.
```json
  {
    "input": "https://faß.ExAmPlE/",
    "base": "about:blank",
    "href": "https://xn--fa-hia.example/",
    "origin": "https://xn--fa-hia.example",
    "protocol": "https:",
    "username": "",
    "password": "",
    "host": "xn--fa-hia.example",
    "hostname": "xn--fa-hia.example",
    "port": "",
    "pathname": "/",
    "search": "",
    "hash": ""
  },
```
https://github.com/web-platform-tests/wpt/blob/master/url/resources/urltestdata.json#L3703

In this test, `https://xn--fa-hia.example/` is the expected output of parsing.
However, the [C# Library of IDNA mapping](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.idnmapping.getascii?view=netframework-4.8) returns `https://fass.example/` as result.
I also tried some punycode converter, like [punycoder](https://www.punycoder.com/) and [idna-converter](http://idna-converter.com/?decoded=https%3A%2F%2Ffa%C3%9F.ExAmPlE%2F&encoded=&doencode=Encode+%3E%3E), they also return `https://fass.example/` as result.
I test this URL in all major browsers, when I open `https://faß.ExAmPlE/`, I will goto `https://fass.example/`.
Is it something new that none of the existing implementation have caught up with?

Thanks!

**Comment by gsnedders** [comment]
cc @annevk

**Comment by annevk** [comment]
@hyspace there's a mistake in the way you percent-decode. The result should be `☃` (U+2603).

In particular step 4 of the host parser first obtains the bytes from the string and then UTF-8 decodes those. You appear to instead use [isomorphic decode](https://infra.spec.whatwg.org/#isomorphic-decode).

**Comment by annevk** [comment]
As for the second example, Firefox and Safari go to `https://faß.example/` for me. This is a difference between IDNA2003 and IDNA2008 which Chrome has not yet aligned on: https://bugs.chromium.org/p/chromium/issues/detail?id=694157.

**Comment by hyspace** [comment]
Thanks @annevk. 
In first test, with your help, I figured out that
I did percent-decode wrong, and I missed step *UTF-8 decode without BOM*

In second test, I'm still a little confused since from [.Net Documentation](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.idnmapping.getascii?view=netframework-4.8#System_Globalization_IdnMapping_GetAscii_System_String_):

> * When run on Windows 8, it supports the 2008 version of the IDNA standard outlined by RFC 5891: Internationalized Domain Names in Applications (IDNA): Protocol.
> * When run on earlier versions of the Windows operating system, it supports the 2003 version of the standard outlined by RFC 3490: Internationalizing Domain Names in Applications (IDNA).

The test environment I used is *Windows 10* so it should use *IDNA2008*.
But according to your explanation and the result I got, it seems using *IDNA2003*.

I think I need to further investigate second one and I may need to talk to *.Net Core*.

Thanks for your help!

**Comment by annevk** [comment]
Maybe "supports" means "can be instructed to support" and doesn't necessarily indicate a default? Reading through https://www.unicode.org/reports/tr46/ might also help here (which is what the URL Standard references as IDNA2008 isn't fully compatible with what user agents need to do).
