### ISSUE TITLE
Should we still have applet attribute reflection tests?

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#17559]
`html/dom/reflection-obsolete.html` tests attribute reflection on `<applet>`, but `<applet>` has been removed from specs (and from non-Safari browsers), as far as I can tell.  Shouldn't this test also be updated?

@domenic @annevk

**Comment by domenic** [comment]
Yes, we should remove tests for applet reflection, IMO.

**Comment by annevk** [comment]
Posted #17570 to fix this.
