### ISSUE TITLE
[css-text] incorrect title / assert in line-break-anywhere-008.html

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#17596]
As far as I can tell, the behavior of css/css-text/line-break/line-break-anywhere-008.html is correct, but the title and the assert meta are wrong, and probably copied-pasted over from a different test.

Could you fix this, or if I'm wrong, explain where I'm wrong?

**Comment by javifernandez** [comment]
Oh, the title is indeed wrong; the test isn't related to break-all, at all. 
It should be something like "CSS Text Test: line-break: anywhere"

As a matter of fact, the line-break-anywhere-007.html test is affected  by the same typo.
I'll send a PR to fix the error.

**Comment by javifernandez** [comment]
PR ready for review

https://github.com/web-platform-tests/wpt/pull/17999
