### ISSUE TITLE
raw/endraw don't work in documentation

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#17687]
https://web-platform-tests.org/writing-tests/server-features.html has, for example,

> The substitution syntax uses `{% raw %}{{ }}{% endraw %}` to delimit items for substitution.

I'm guessing #16458 broke this; cc @jugglinmike @Hexcles

**Comment by jugglinmike** [comment]
Yup, that's right. Thanks for letting me know! Patch at gh-17737
