### ISSUE TITLE
Move MANIFEST.json

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#17727]
I was reading https://github.com/web-platform-tests/wpt/issues/6168#issuecomment-307684350 and that suggested MANIFEST.json isn't maintained, but it being available in the root makes it an attractive target for people to build stuff on. If it's still not maintained we should do something about that, e.g., move it to its own repository as @jgraham suggests.

**Comment by jgraham** [comment]
I think there's a misunderstanding here. `MANIFEST.json` is still maintained and used, it's the web-based runner under `tools/runner` that isn't maintained and could maybe be split out of the project.

**Comment by sideshowbarker** [comment]
> I think there's a misunderstanding here. `MANIFEST.json` is still maintained and used

Yeah, sorry I should have been more clear about that when I originally wrote https://github.com/web-platform-tests/wpt/issues/6168#issuecomment-307684350

> it's the web-based runner under `tools/runner` that isn't maintained and could maybe be split out of the project

Yeah

**Comment by annevk** [comment]
Feel free to close / rename this. Just trying to make sure there were no loose ends.
