### ISSUE TITLE
Bug(s) in white-space-pre-wrap-trailing-spaces-006.html

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#17955]
I see a major problem in white-space-pre-wrap-trailing-spaces-006.html:

The behavior that it is testing is not required by the spec. It is **allowed** to collapse hanging preserved spaces that overflow the line, but it is not required to do so. The test should at least be written with `<meta name=flags content="may">`. But is is probably even better to remove it, since that behavior, while allowed, is not encouraged, and having a (failing) test would encourage browsers to implement it. Another way would be to re-write it to pass regardless of whether the overflowing spaces are collapsed or not (but for example to fail if all the end of line spaces, including those that don't overflow, get collapsed).

If we decide not to delete it, there are still some minor issues with it:
* The style contains both `.test span { background: red; }` and `.test span { background: green; }`. I believe the first one should just be deleted.
* The `.ref` element contains a `<span>` which isn't styled. I think that extra markup could be removed.

**Comment by javifernandez** [comment]
I guess the best idea would be to remove the test, indeed. 

I'm afraid that these tests are also affected by a similar issue, though:

- trailing-ideographic-space-001.html
- trailing-ideographic-space-002.html
- trailing-ideographic-space-003.html

I find this interoperability issue quite annoying for these tests; maybe we should look for n alternate approach to verify the correct handling of trailing spaces.

**Comment by frivoal** [comment]
-001 -002 are with `white-space:normal`, and the rule is different in that case, so it is fine.
-003 has two references, one for each behavior, so it's fine too.
