### ISSUE TITLE
Are developers on their own when tests at Chromium browser produce a crash?

### ISSUE THREAD

**Issue by guest271314** [web-platform-tests/wpt#17960]
While testing code at Chromium browser that uses `HTMLMediaElement.captureStream()` and `MediaRecorder` where the tab crashes when the code is run, spanning several versions of Chromium browser. Have filed at least two issues at GitHub https://github.com/w3c/media-source/issues/190, including this repository https://github.com/web-platform-tests/wpt/issues/15816, and https://bugs.chromium.org to address the problem.

Am trying to make sense of this comment at a Chromium issue [Issue 943484: Tab crashes when HTMLMediaElement.captureStream() is called on <video> with MediaSource Blob URL set at src]( https://bugs.chromium.org/p/chromium/issues/detail?id=943484#c11)

> You must use the official Google Chrome build. We don't provide support for Chromium. If the crash doesn't reproduce in Chrome you're on your own unfortunately. I was trying with the HTML file you provided in c#0.

A plain reading of that comment implies that developers should not bother testing code at Chromium browser, as even when a crash  occurs testing code at Chromium browser no fixes for those crashes will be undertaken by Chromium authors if and when a bug is filed; have an implicitly pre-determined status of `WontFix` even if not explicitly marked with that status.

If that is in fact the case, can Web Platform Tests README https://github.com/web-platform-tests/wpt/blob/master/README.md be updated to clearly state that tests at Chromium browser that produce crashes are null and void?

**Comment by jdm** [comment]
I'm not sure why the README should contain any text about the impact of tests on certain browsers. Tests are designed to be able to be run in any browser, and how the test results are interpreted are up to users and developers of that browser.

**Comment by guest271314** [comment]
@jdm What is the point of running tests for a browser when whatever issues that are encountered will not be fixed by the authors of the source code of the browser? Tests for testing sake?

**Comment by jdm** [comment]
That's something that should be left to the judgement of the people running the tests. This repository is the wrong place to make policy about which browsers should have results discounted.

**Comment by guest271314** [comment]
@jdm If true and correct, what the comment essentially states that when Chromium crashes, for any reason, developers are on their own. Users "must" use the branded version of Chromium source code, Google Chrome, for any tests to have any value. 

> This repository is the wrong place to make policy about which browsers should have results discounted.

Consider the case of browser that is named, for example, "Crash". The browser loads, though every method defined in the source code of the browser the developer executes crashes the browser tab. No fixes for those crashes will be forthcoming. Unless the developer decides to use the branded version of "Crash", "Don't Crash With Branding". If decide to write such a browser, and its branded counterpart, from scratch, will this repository include tests for "Crash"?

**Comment by jdm** [comment]
If the developers for "Crash" want to submit tests that verify properties of web standards to this repository, then sure. There are not tests for particular browsers; there are tests for web standards that can be run in any conforming browser.

**Comment by guest271314** [comment]
@jdm Not everyone uses Chrome, for a variety of reasons

- https://github.com/CHEF-KOCH/Chromium-hardening

- https://github.com/Eloston/ungoogled-chromium

particularly where they are limited to 32-bit machines and run *nix

[**Updates to Google Chrome Linux support**](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/FoE6sL-p6oU)

> ​The intention is that those users will not use a non-updating Chrome​, but choose Firefox (if it is updating) or any other updating browser instead. Using Chrome on those system is a security risk.
> However, you should search for a Chromium alternative as some distributions may maintain an updating 32 bit edition of Chromium. You will not be able to use Flash (I think) or play H.264 or DRM protected videos, but those are not "low-end web/mail" anyway, so you should be fine.
> 
> Please, remember that Google is a business and the very low market share of Chrome users that use 32 bit Linux probably does not justify its maintenance cost.

[Google Is Ending Chrome support for 32-bit Linux, Ubuntu 12.04 And Debian 7](https://itsfoss.com/google-ending-chrome-32-bit/)

> Installing Google Chrome on Ubuntu 32-bit is not a possibility anymore.

Some of the additional reasons users might choose to use Chromium instead of Chrome

[**What Is The Difference Between Google Chrome And Chromium Browser?**
Google Chrome uses the source code of Chromium.](https://fossbytes.com/difference-google-chrome-vs-chromium-browser/)

> **Usage tracking and crash reporting**
> Unlike Chromium, Google has added the crash reporting and send usage statistics options. Chrome sends data to Google servers. It includes general data like information about your device and OS, Chrome settings, visited websites having malware, search queries, etc. This allows Google to throw suggestions, results, and ads that are relevant to you.
> 
> **Non-optional tracking**
> Google Chrome installer includes a randomly generated token. The token is sent to Google after the installation completes in order to measure the success rate.
> 
> Google also uses the RLZ identifier to track a user on Google Search and while using the address bar. The RLZ identifier stores information – in the form of encoded strings – like the source of chrome download and installation week. It doesn’t include any personal information, and it’s used to measure the effectiveness of a promotional campaign. Chrome downloaded from Google’s website doesn’t have the RLZ identifier. The source code to decode the strings is made open by Google.

Morning cup of Chromium crash Issue [986148: MediaRecorder at Chromium 77.0.3854.3 crashes tab when attempting to record a specific .mp3](https://bugs.chromium.org/p/chromium/issues/detail?id=986148).

**Comment by guest271314** [comment]
@jdm Not everyone uses Chrome, for a variety of reasons

- https://github.com/CHEF-KOCH/Chromium-hardening

- https://github.com/Eloston/ungoogled-chromium

particularly where they are limited to 32-bit machines and run *nix

[**Updates to Google Chrome Linux support**](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-dev/FoE6sL-p6oU)

> ​The intention is that those users will not use a non-updating Chrome​, but choose Firefox (if it is updating) or any other updating browser instead. Using Chrome on those system is a security risk.
> However, you should search for a Chromium alternative as some distributions may maintain an updating 32 bit edition of Chromium. You will not be able to use Flash (I think) or play H.264 or DRM protected videos, but those are not "low-end web/mail" anyway, so you should be fine.
> 
> Please, remember that Google is a business and the very low market share of Chrome users that use 32 bit Linux probably does not justify its maintenance cost.

[Google Is Ending Chrome support for 32-bit Linux, Ubuntu 12.04 And Debian 7](https://itsfoss.com/google-ending-chrome-32-bit/)

> Installing Google Chrome on Ubuntu 32-bit is not a possibility anymore.

Some of the additional reasons users might choose to use Chromium instead of Chrome

[**What Is The Difference Between Google Chrome And Chromium Browser?**
Google Chrome uses the source code of Chromium.](https://fossbytes.com/difference-google-chrome-vs-chromium-browser/)

> **Usage tracking and crash reporting**
> Unlike Chromium, Google has added the crash reporting and send usage statistics options. Chrome sends data to Google servers. It includes general data like information about your device and OS, Chrome settings, visited websites having malware, search queries, etc. This allows Google to throw suggestions, results, and ads that are relevant to you.
> 
> **Non-optional tracking**
> Google Chrome installer includes a randomly generated token. The token is sent to Google after the installation completes in order to measure the success rate.
> 
> Google also uses the RLZ identifier to track a user on Google Search and while using the address bar. The RLZ identifier stores information – in the form of encoded strings – like the source of chrome download and installation week. It doesn’t include any personal information, and it’s used to measure the effectiveness of a promotional campaign. Chrome downloaded from Google’s website doesn’t have the RLZ identifier. The source code to decode the strings is made open by Google.

Morning cup of Chromium crash: [Issue 986148: MediaRecorder at Chromium 77.0.3854.3 crashes tab when attempting to record a specific .mp3](https://bugs.chromium.org/p/chromium/issues/detail?id=986148).

**Comment by jdm** [comment]
@guest271314 I understand that. I'm not passing any judgement on what browser you or anybody else uses. This repository of cross-browser tests is the wrong place to try to set down policy about how the results of those tests should be interpreted in browsers that could run them. If you want to continue that conversation, you will need to do that with the developers of the browser.

**Comment by guest271314** [comment]
@jdm This issue does not request for a policy to be set down. The request is specifically for updating the README of this repository to include a note for the purpose of _informing_ developers who perform tests at Chromium browser and file issues and/or PR's at this repository of  

> We don't provide support for Chromium. If the crash doesn't reproduce in Chrome you're on your own unfortunately. 

without any judgment as to whether that statement is true and correct, so that the developers are _well-informed_ if and when they and anyone else decides to run the tests relevant to Chromium browser. That is not asking for a policy to be set down. That is asking for transparency.

**Comment by guest271314** [comment]
@jdm Transparency meaning the opposite of NOT informing users of a browser API that their PII biometric data is being recorded and sent to a remote web service https://bugs.chromium.org/p/chromium/issues/detail?id=816095; https://github.com/w3c/speech-api/issues/56.

**Comment by Hexcles** [comment]
Since you're well aware of the difference between Chrome & Chromium, here's the `--help` text for you:

```
  --product {chrome,chrome_android,chrome_ios,edgechromium,edge,edge_webdriver,firefox,firefox_android,ie,safari,sauce,servo,servodriver,opera,webkit,epiphany}                                                                                               
                        Browser against which to run tests
```

At no point have we claimed that Chromium is an officially supported "product" by the wpt tooling (although some Chromium developers do run wpt against Chromium occasionally with elaborate non-default CLI flags with good understanding of what they are doing). If you see any publicly discoverable docs (e.g. the top-level README or web-platform-tests.org, not code comments) that suggest you to use Chromium, you can send a PR to remove that. Otherwise, I'm closing the issue.

**Comment by guest271314** [comment]
> Since you're well aware of the difference between Chrome & Chromium, here's the `--help` text for you:
> 
> ```
>   --product {chrome,chrome_android,chrome_ios,edgechromium,edge,edge_webdriver,firefox,firefox_android,ie,safari,sauce,servo,servodriver,opera,webkit,epiphany}
>                         Browser against which to run tests
> ```
> 
> At no point have we claimed that Chromium is an officially supported "product" by the wpt tooling (although some Chromium developers do run wpt against Chromium occasionally with elaborate non-default CLI flags with good understanding of what they are doing). If you see any publicly discoverable docs (e.g. the top-level README or web-platform-tests.org, not code comments) that suggest you to use Chromium, you can send a PR to remove that. Otherwise, I'm closing the issue.

@Hexcles The PR section of this repository contains far more than one reference to Chromium browser. This https://github.com/web-platform-tests/wpt/pull/18052


> Feature: https://www.chromestatus.com/feature/6678921049276416Bug: 679813Change-Id: If8e29e17b171ef52a9f372feaa6e8526006596d3Reviewed-on: https://chromium-review.googlesource.com/1714887WPT-Export-Revision: 11a481a64e61f2cea8892d77f98fdde2dc96ddd3
> --

 is but one example from 4 hours ago.

This issue is requesting that the language be made abundantly clear at the README of this repository.

> At no point have we claimed that Chromium is an officially supported "product" by the wpt tooling

should be shortened to the language:

> wpt DOES NOT test Chromium browser.

Whether you act according to what you stated or not, that is, close all PRs referencing Chromium whatsoever is up to your and yours. This issue just asks for clarity and transparency from this point foward, by including the already reference language described above, similar to https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1837292/comments/6

> This means that packaging issues will be looked at, but issues with the
> browser's behaviour should be reported upstream (and yes upstream as a
> vendor doesn't officially support Chromium, only Chrome, so it's likely
> that the first thing that they will ask is whether the issue is
> reproducible with Chrome).

the essential portions of the reply being that even though the site includes the name Chromium https://bugs.chromium.org/p/chromium/ the site actually does not support Chromium or have any mandate, obligation, and are not likely to try to fix Chromium bugs. IF a developer does decide to fix a Chromium bug, it is at their own discretion

> https://launchpad.net/~chromium-team mostly handles Ubuntu-specific packaging, and bug triaging and forwarding to upstream, on a best-effort basis, because of limited manpower.

**Comment by guest271314** [comment]
@Hexcles IF a developer decides to test at Chromium browser AND contribute their tests to wpt, they should be immediately aware that the bug MUST be reproducible at Chrome in order for the bug to have any significance as to this reprository, as indicated at the language at the linked reply at previous comment. 

That is, if wpt has any consideration for users of Chromium browser who MIGHT decide to contribute to wpt. IF contributions by users of Chromium that also are able to reproduce code at Chrome are NOT a consideration for wpt members, then do nothing; which could include the potential for confusion as to why the term "chromium" is referenced more than once at PRs; else, make it clear that if Chromium is used to perform tests, for there to be significance to those tests, per the scope of this repository, the test results MUST be reproducible at Chrome, one of the browsers that this repository does support, and to ignore the fact that the term "chromium" is referenced at PRs more than once, the reason WHY the term "chromium" is mentioned at PRs is beyod the control of wpt.

**Comment by guest271314** [comment]
@Hexcles 

>  If you see any publicly discoverable docs (e.g. the top-level README or web-platform-tests.org, not code comments) that suggest you to use Chromium, you can send a PR to remove that. Otherwise, I'm closing the issue.

You do not get to determine what this issue is filed for. If you are expecting individuals to simply KNOW that all references to Chromium do not mean anything related to the browser Chromium, and even if they did, wpt has decided to not test for Chromium browser. That _should_ be a simple matter to add to the README. Such a one-line note improves transparancy, avoids confusion and would not affect any other parts of wpt documentations. To NOT include such a statement at the README shows lack of concern for the matter. Which is your prerogative.

Your list of references to Chromium to delete from this repository: https://github.com/web-platform-tests/wpt/search?q=Chromium&unscoped_q=Chromium

A cursory glance at the list includes code to fetch Chromium browser https://github.com/web-platform-tests/wpt/blob/e6f4a5f5aea6ccc358ccda8e54a9fbac95731e7d/tools/wpt/browser.py

>     def _chromium_chromedriver_url(self, chrome_version):
>         try:
>             # Try to find the Chromium build with the same revision.
>             omaha = get("https://omahaproxy.appspot.com/deps.json?version=" + chrome_version).json()
>             revision = omaha['chromium_base_position']
>             url = "https://storage.googleapis.com/chromium-browser-snapshots/%s/%s/chromedriver_%s.zip" % (
>                 self.chromium_platform_string(), revision, self.platform_string())
>             # Check the status without downloading the content (this is a streaming request).

The docs you refer to are pointless in this case, as the Chromium browser source code itself is requested. Kindly delete that file and the remainder of the list from this repository to act consistent with your policy decision

> not code comments) that suggest you to use Chromium

as the request for Chromium browser by this repository is more than a suggestion; it is code used to use the Chromium browser by wpt.

**Comment by guest271314** [comment]
@Hexcles Well, per your word, have you began deleting all PR referencing and Chromium code in this repository?

**Comment by guest271314** [comment]
>  If you see any publicly discoverable docs (e.g. the top-level README or web-platform-tests.org, not code comments) that suggest you to use Chromium, you can send a PR to remove that. 

@Hexcles The requested PR https://github.com/web-platform-tests/wpt/pull/18073

**Comment by Hexcles** [comment]
> @Hexcles Well, per your word, have you began deleting all PR referencing and Chromium code in this repository?

I never mentioned "PR" or "code". Specifically, the word "Chromium" in those PRs you referred to actually means the Chromium project (instead of the Chromium browser), from which the Chrome product is built; the code you referred to is implementation details.

I have done my best explaining. Sorry if you still can't understand or disagree.
