### ISSUE TITLE
Assertion message stability

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#17974]
gh-17946 introduced insability in the error message of a failing test. This kind of volatility is tolerated by WPT's stability checker, but (as noted in the reverting pull request) it causes problems in Chromium's build system. [We reverted the change to preserve functionality in Chromium.](https://github.com/web-platform-tests/wpt/pull/17973)

In order to avoid this problem in the future, WPT's stability check should be made more strict or Chromium's infrastructure should be made more forgiving.

Is surfacing non-deterministic values reason enough to allow this kind of instability? Or there other reasons to allow it?

@Hexcles would it even be feasible to change Chromium's infrastructure?

**Comment by Hexcles** [comment]
There was also a discussion a year ago in #10246 .

@LukeZielinski is working on using wptrunner directly in Chromium, which might give us the chance to overhaul the baseline/expectation system.

**Comment by jugglinmike** [comment]
Thanks for the link. @Hexcles. That answers my question conclusively: WPT does **not** guarantee stability of failure messages.

This difference with Chromium is a source of tension, though (as demonstrated by gh-17973). It's good to know that resolving it may be technically feasible soon! @LukeZielinski is fixing this on your radar?

**Comment by LukeZielinski** [comment]
Yes I think making subtest message comparison less strict in Chromium is a good thing. I do plan to address this somehow as part of integrating WPT into Chromium CI, although no concrete plans yet.

**Comment by WeizhongX** [comment]
This has been addressed by https://github.com/web-platform-tests/rfcs/blob/master/rfcs/expected_fail_message_tag_for_subtests.md.

Mark as complete.
