### ISSUE TITLE
Potential race condition in resource timing nested-context-navigations-iframe.html test

### ISSUE THREAD

**Issue by hawkinsw** [web-platform-tests/wpt#17983]
This is regarding the `"Test that iframe navigations are not observable by the parent, even after history navigations by the parent"` test specifically. 

During this test, the sequence of page changes looks something like this:

1. Outer window is `resources/iframe-navigate-back.html`
1. It contains an iframe and that iframe loads `resources/document-that-navigates.html`
1. `document-that-navigates.html` immediately `loads document-navigated.html`

That final page sends a "navigated" event that kicks off a subsequent page load to `resources/navigate_back.html`. Using the `history.back()` method, `navigate_back.html` directs the browser to load `document-navigated.html` for a second time. At this time, the test is waiting to hear another "navigated" event. Only when that event is received will the test be able to determine whether it passes or fails.

Unfortunately, if the second load of `document-navigated.html` is satisfied by a cache of some kind, the HTML spec does not require that the page's javascript functions be invoked. See https://html.spec.whatwg.org/#traverse-the-history-by-a-delta. In this case, the test times out.

 @yoavweiss @sefeng-mozilla

**Comment by yoavweiss** [comment]
Thanks for digging into this!



> Unfortunately, if the second load of `document-navigated.html` is satisfied by a cache of some kind, the HTML spec does not require that the page's javascript functions be invoked. See https://html.spec.whatwg.org/#traverse-the-history-by-a-delta. In this case, the test times out.

What do you mean by "cache of some kind" - is that the HTTP cache? 
I don't see the behavior of not running JS when the page is fetched from the cache in traverse the history by a delta. Any pointers to the specific text that says that?

**Comment by hawkinsw** [comment]
> Thanks for digging into this!
> 
> > Unfortunately, if the second load of `document-navigated.html` is satisfied by a cache of some kind, the HTML spec does not require that the page's javascript functions be invoked. See https://html.spec.whatwg.org/#traverse-the-history-by-a-delta. In this case, the test times out.
> 
> What do you mean by "cache of some kind" - is that the HTTP cache?
> I don't see the behavior of not running JS when the page is fetched from the cache in traverse the history by a delta. Any pointers to the specific text that says that?

The cache, in our case, is one that potentially stores pages from the history and makes navigating by back and forward much faster. 

I believe that the discrepancy is that going back/forward in the history is handled by traversing the history by a delta and browsing to a new page is handled by the navigate method that (eventually) invokes an HTML parser that will cause certain javascript to execute and events to fire. (https://html.spec.whatwg.org/#navigate, https://html.spec.whatwg.org/#process-a-navigate-response, https://html.spec.whatwg.org/#navigate-html).

**Comment by hawkinsw** [comment]
I'd love to have @smaug---- weigh in on what I said. He's away this week so his response may be delayed.

**Comment by yoavweiss** [comment]
> The cache, in our case, is one that potentially stores pages from the history and makes navigating by back and forward much faster.

Oh, so when the BFCache is involved, JS is not executed when going back to the page... I get the issue you're running into now. I'll re-review in that light

**Comment by yoavweiss** [comment]
Hmm, looks like this was resolved by https://github.com/web-platform-tests/wpt/commit/c7cc6fdae3d7b44e5fa6c9950b9b8b4a4b395746

**Comment by hawkinsw** [comment]
I didn't realize that we had two-way sync with wpt and, yes, there was a commit on our end. I was proposing this fix since I thought that it was a more robust solution, but I am okay with the one that got merged as long as it works!

**Comment by yoavweiss** [comment]
I think it works although I'm not sure if that behavior (BFcache disabled in the presence of onunload events) is actually specified somewhere.

**Comment by hawkinsw** [comment]
> I think it works although I'm not sure if that behavior (BFcache disabled in the presence of onunload events) is actually specified somewhere.

In "Unloading documents" (https://html.spec.whatwg.org/multipage/browsing-the-web.html#unloading-documents) step 9 of "To unload a Document document, optionally given a recursiveFlag:" specifies that the salvageable flag is set to false if there is an unload event handler. In Step 11.3 of that same section, it is specified that the document is discarded if the salvageable flag is set to false.

Subsequently, when the browser "Traverse[s] the History" back to that page (https://html.spec.whatwg.org/#traverse-the-history), the first step checks whether history entry still holds a valid document. In this case, since it was discarded, the answer is "no" and the browser "navigates" to the document via the traditional means of loading a page.

**Comment by yoavweiss** [comment]
Thanks for the pointers!

**Comment by hawkinsw** [comment]
It was fun to learn and investigate the spec! I love this!
