### ISSUE TITLE
[css-text] Missing "should" flag in css-text i18n tests

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#17996]
The `wpt/css/css-text/i18n/css3-text-line-break-baspglwj-*.html` ( from -003 to -119) tests  and `css3-text-line-break-opclns-*.html` tests check the behavior of the BA and OP line breaking class. The tests are correct, but the BA and OP classes are **tailorable**. [UAX 14 has this to say](https://www.unicode.org/reports/tr14/tr14-43.html#TailorableBreakingRules) about tailorable classes and rules:
> The following rules and the classes referenced in them provide a reasonable default set of line break opportunities. Implementations should implement them unless alternate approaches produce better results for some classes of text or applications.

The tests should therefore use `<meta name=flags content=should>`.

I'm happy to apply the fix myself, unless i18n folks want to handle it some other way to preserve synchronization with some other repo.

Note: `wpt/css/css-text/i18n/css3-text-line-break-baspglwj-*.html` from -001 to -002 and -120 to -131 do not have this problem, as they test the **non-tailorable** SP, ZW, GL and WJ classes.

@r12a @xfq

**Comment by r12a** [comment]
See https://github.com/web-platform-tests/wpt/issues/17995#issuecomment-514287933 which mentions that these test files are out of date, anyway.  I don't object to the addition of the meta element, but it would save effort to add to the new files.

**Comment by frivoal** [comment]
It's an easy fix to do on this side, so I'll make it to avoid further confusion (such as [this discussion in bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1568219)). The same should be applied to your tests in the i18n repo, so that we don't regress when updating.
