### ISSUE TITLE
[css-text] verifying the behavior of WJ, ZW, GL, and ZWJ line breaking classes for values of white-space other than normal

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#17997]
[css-text says](https://drafts.csswg.org/css-text-3/#line-break-details):
> line breaking behavior defined for the WJ, ZW, GL, and ZWJ line-breaking classes in [UAX14] must be honored. 

`wpt/css/css-text/i18n/css3-text-line-break-baspglwj-*.html` -002 and from -120 to -131 test that, but only for `white-space: normal`.

Each of these test could easily be expanded to have several assertions instead of one, verifying the same thing on the several values of `white-space` that allow for wrapping (`normal`, `pre-line`, `pre-wrap`, and `break-spaces`).

I'm happy to apply the fix myself, unless i18n folks want to handle it some other way to preserve synchronization with some other repo.

cc @r12a @xfq

**Comment by r12a** [comment]
See #17995 (comment) which mentions that these test files are out of date.

**Comment by frivoal** [comment]
As for #17995 and #17996, it would be good to have the updated i18n tests, but until we do, these ones are easy to fix, so fixing it here. @xfq, before updating the tests in wpt with the improved i18n version, please make sure that you have an equivalent fix upstream as well, so that we don't regress.
