### ISSUE TITLE
WebRTC callback methods need WPT tests

### ISSUE THREAD

**Issue by alvestrand** [web-platform-tests/wpt#18236]
While the callback methods have been deprecated in favor of their promise-based brethren, it is still part of the WebRTC API; thus, they should have WPT tests.

More details in https://github.com/w3c/webrtc-pc/issues/2022 (closed)

**Comment by fippo** [comment]
https://wpt.fyi/results/webrtc/legacy/simplecall_callbacks.https.html?label=experimental&label=master&aligned
-- results look like expected.
