### ISSUE TITLE
GitHub Actions stalled in the "Waiting to run" state

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#18286]
We landed gh-17680 under the assumption (and [limited observation](https://github.com/web-platform-tests/wpt-actions-test/pull/8)) that GitHub Actions run consistently for all of GitHub's `pull_request` events over the lifetime of a pull request. Reviewing recent performance of that Action shows that this is not the case. That's a problem because consistency is important for the application we have in mind (submission preview).

I've created a ticket with GitHub support and included the text below. I'll update this issue as I learn more.

/cc @jgraham @sideshowbarker

> Hello,
> 
> My project [1] recently added a GitHub Workflow for the `pull_request` event. The Workflow's only Action frequently stalls in the "Waiting to run" state. This is not consistent--the Action does occasionally run as expected for pull request events.
> 
> I don't know a way to analyze this at scale, but my limited research suggests that this may be related to the state of the branch. Specifically, this seems to occur when a commit is force-pushed and when the branch is deleted.
> 
> Is this a fundamental limitation of the GitHub Actions feature? If so, can the status be updated to indicate the finality of this state? If not, can you speak to the likelihood of the problem being solved?
> 
> Thanks for your help!
> 
> [1] https://github.com/web-platform-tests/wpt

**Comment by jugglinmike** [comment]
Still no response from GitHub, but I have been able to learn a bit more.

This week, [GitHub announced a new Continuous Integration service built on the Actions feature](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/). I've been experimenting with that a bit, and the improved UI gives more insight as to what's going wrong (or at least, what will go wrong [when we migrate to the new system](https://github.com/web-platform-tests/wpt/pull/18359)).

It looks like the built-in "checkout" action is attempting to fetch the GitHub-created git ref at `refs/pull/XX/merge`, even when configured to fetch `master`. That seems like a mistake to me, but this functionality is all so new that it's tough to know what's intended. [I've filed an issue with the maintainers to find out.](https://github.com/actions/checkout/issues/5)

**Comment by jugglinmike** [comment]
The maintainers of that Action got back to me very quickly, and it looks like this was just a misunderstanding about the documentation. Following some experimentation on the demo repository, it's looking like this is just a case of incorrect configuration. gh-18393 should resolve the problem.

**Comment by jugglinmike** [comment]
As I filed the pull request above, GitHub's support staff replied to my request
for help:

> GitHub Support (GitHub Developer Support)
>
> Aug 12, 6:44 PM UTC
>
> Hi Mike,
>
> Thanks for reaching out! I see that you recently updated your repository's workflows to the new YAML syntax:
>
> https://github.com/web-platform-tests/wpt/tree/master/.github/workflows
>
> If you're still running into this "Waiting to run" state for these workflow executions, could you please share a link with us so we can take a look and provide input? Thanks

Here's my response:

> Thanks for getting back to me!
>
> The new UI correctly communicates the final (failed) state of the Workflow, so you can consider this issue resolved.
>
> In case you're curious, the associated log also helped us verify that it was indeed a problem with delete branches. Better still, the introduction of a dedicated "checkout" Action means that we can configure the system to work as we intended:
>
> https://github.com/web-platform-tests/wpt/pull/18393
>
> Thanks again,
>
> Mike

**Comment by foolip** [comment]
@jugglinmike closing per your "you can consider this issue resolved" in that reply.
