### ISSUE TITLE
GitHub Actions "neutral" exit code is incorrectly interpreted as failure

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#18392]
As of today, GitHub Actions that we've designed to signal a "neutral" status are being reported as failing. The only change in this repository that coincides with the unexpected behavior is [our migration to the latest "beta" release of the service](https://github.com/web-platform-tests/wpt/pull/18359). That makes me suspect a regression, so I've reported the problem in the GitHub Community Forum:

https://github.community/t5/GitHub-API-Development-and/GitHub-Actions-quot-neutral-quot-exit-code-is-incorrectly/m-p/29051

**Comment by jugglinmike** [comment]
No response from GitHub yet, but the failing status continues to confuse contributors. As of gh-18417, we're temporarily reporting "success" for these cases since that's more accurate. We'll revert that change once the underlying issue with GitHub has been resolved.

**Comment by jugglinmike** [comment]
A fellow GitHub user has [observed](https://github.community/t5/GitHub-API-Development-and/GitHub-Actions-quot-neutral-quot-exit-code-is-incorrectly/m-p/29332#M2581) that this feature may have been intentionally removed:

> The neutral exit code isn't mentioned in the [new documentation](https://help.github.com/en/articles/workflow-syntax-for-github-actions), so I don't think it's supported anymore.

We still haven't received word from a GitHub representative, though.

**Comment by jugglinmike** [comment]
[A GitHub employee has confirmed via Twitter](https://twitter.com/ethomson/status/1163899559279497217):

> We did, we'll have a different neutral exit strategy.  `exit 78` seems unique, but isn't.  (eg, `git merge` exits with the number of conflicts encountered.)

It sounds like the neutral status will be supported in the future, so maybe we ought to keep this issue open until that's available.

**Comment by foolip** [comment]
We're no longer using the neutral code for GitHub Actions, and I doubt it's coming back to GitHub Actions. It makes more sense with the generic GitHub Checks API, where actions can be taken to resolve such inconclusive checks.
