### ISSUE TITLE
Azure Pipelines macOS jobs failing with "Hosted Agent lost communication with the server"

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18669]
This has happened a fair bit lately. The way I noticed it was looking at https://wpt.fyi/runs and seeing runs where just one of Safari stable (blue) and Technology Preview (purple) would run.

Another way to find them is to filter https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1 by failing jobs and looking at scheduled builds. Here are all the occurences I can find:
- [build 28578](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28578) (all tests: Safari 2)
- [build 28540](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28540) (all tests: Safari 3)
- [build 28447](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28447) (all tests: Safari Technology Preview 1)
- [build 28387](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28387) (all tests: Safari Technology Preview 3)
- [build 28201](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28201) (all tests: Safari Technology Preview 1)
- [build 28131](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28131) (all tests: Safari Technology Preview 4)
- [build 28037](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28037) (all tests: Safari 1
- [build 27453](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=27453) (all tests: Safari Technology Preview 1)
- [build 26531](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=26531) (all tests: Safari 4)
- [build 26259](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=26259) (all tests: Safari Technology Preview 1)
- [build 26206](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=26206) (all tests: Safari 3 + Technology Preview 4)
- [build 26147](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=26147) (all tests: Safari Technology Preview 2)
- [build 25895](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=25895) (all tests: Safari Technology Preview 4)
- [build 25743](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=25743) (all tests: Safari Technology Preview 1)
and 4)

The earliest is July 31, but there may have been more builds that just aren't retained. I'll click retain on all of the above.

The problem usually happens at "Run tests" step, but for [build 28578](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28578) it was at the Checkout step. The logs have never provided any clues, because they just cut off before there's anything interesting.

@thejohnjansen @mustjab this looks like an Azure Pipelines infra problem. Is there anything we could do to help diagnose this? I'd suspect that we're running out of memory or something, but that doesn't explain the case when it happened during checkout.

@gsnedders FYI.

**Comment by foolip** [comment]
Increasing the number of jobs from 4 to 5 in https://github.com/web-platform-tests/wpt/issues/18671 didn't fix this, https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28645 is going to fail in the same manner for job "all tests: Safari 2". I started seeing "Azure Pipelines 2 lost communication with the server" pretty early in the run, and it hasn't finally failed yet, but I'm quite sure it will.

**Comment by foolip** [comment]
It happened on https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=29005 which was the daily Safari stable run.

**Comment by mustjab** [comment]
@foolip Following up with Azure pipelines team, will let you know what we find.

**Comment by foolip** [comment]
A few more that I spotted today, didn't go digging for an exhaustive list:
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30021
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30047

**Comment by foolip** [comment]
@mustjab did you hear back from the Azure Pipelines team?

**Comment by mustjab** [comment]
@foolip I filled an internal ticket with Pipeline team to investigate this issue, haven't heard back yet. Do you have a list of recent jobs that failed due to this issue?

**Comment by foolip** [comment]
@mustjab I haven't been monitoring the Safari results as closely lately, but here are the 3 failures I can find in October:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=32949
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=33184
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=33783

**Comment by foolip** [comment]
Looking for gaps in https://wpt.fyi/runs?label=master&label=azure is another way to gauge how much it's happening. Note that there have been failing Edge runs too, in case you want to look into that.

**Comment by mustjab** [comment]
@foolip The Mac run issues appear to be due to machine running out of resources. The Azure pipeline team is going to add more logging to confirm that, but would it be possible to break down the failing step to small ones to workaround this issue?

**Comment by foolip** [comment]
Do you know what kind of resource exhaustion would cause this to happen? Is it running out of memory? Or is there some kind of watchdog in place, where pegging the CPU for a long time would cause this?

We could try just increasing the number of chunks from 5 to 10, but I think we "only" have 20 parallel VMs so we'd run out of capacity of we're running both Safari stable and preview at the same time as some pull request needs testing.

**Comment by mustjab** [comment]
Initial investigation appears to point to machines running out of memory. Is there anything we can do on test end to reduce memory footprint?

**Comment by foolip** [comment]
@mustjab, interesting! Does Azure Pipelines collect any stats from the agents as they're running that we could look at, or would we have to start a background process to monitor memory usage and regularly print it to stdout? If we could know if it's the python process or Safari that's growing large, that'd give clues for what to investigate next.

**Comment by foolip** [comment]
@mustjab also, I'm curious if it's possible to get artifacts out of an agent that has run out of memory, or if printing things to the logs before OOM is the only way? If we could "stream" artifacts then we could take screenshots of the Activity Monitor over time :)

**Comment by foolip** [comment]
Saw it happen again now on https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34864.

**Comment by foolip** [comment]
Happened in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34944 too, also in chunk 2 after about the same amount of time. Maybe there's some test there that uses a lot of memory...

**Comment by foolip** [comment]
This happened in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35048 and https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35068 as well.

I've triggered https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35073 to run `vm_stat` every minute to see what memory growth looks like.

**Comment by foolip** [comment]
I've also manually retriggered the failed runs to see if we can get results to fill in the gaps:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35074
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35075

**Comment by foolip** [comment]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35073 reproduced the problem in job 2 and 5, with the `vm_stat` logging, yay!

A sample of the output from "all tests Safari Technology Preview 1":
```
2019-10-23T20:03:05.0450430Z > Mach Virtual Memory Statistics: (page size of 4096 bytes)
2019-10-23T20:03:05.0451050Z > Pages free:                             1714166.
2019-10-23T20:03:05.0451580Z > Pages active:                            523666.
2019-10-23T20:03:05.0451820Z > Pages inactive:                          283384.
2019-10-23T20:03:05.0452060Z > Pages speculative:                       347770.
2019-10-23T20:03:05.0452210Z > Pages throttled:                              0.
2019-10-23T20:03:05.0452490Z > Pages wired down:                        275783.
2019-10-23T20:03:05.0452830Z > Pages purgeable:                          23020.
2019-10-23T20:03:05.0453020Z > "Translation faults":                  13323433.
2019-10-23T20:03:05.0454060Z > Pages copy-on-write:                     205878.
2019-10-23T20:03:05.0454280Z > Pages zero filled:                     10573194.
2019-10-23T20:03:05.0454510Z > Pages reactivated:                          308.
2019-10-23T20:03:05.0454710Z > Pages purged:                                84.
2019-10-23T20:03:05.0455310Z > File-backed pages:                       705855.
2019-10-23T20:03:05.0455620Z > Anonymous pages:                         448965.
2019-10-23T20:03:05.0455820Z > Pages stored in compressor:                   0.
2019-10-23T20:03:05.0456040Z > Pages occupied by compressor:                 0.
2019-10-23T20:03:05.0456280Z > Decompressions:                               0.
2019-10-23T20:03:05.0456440Z > Compressions:                                 0.
2019-10-23T20:03:05.0456730Z > Pageins:                                 669282.
2019-10-23T20:03:05.0456930Z > Pageouts:                                     0.
2019-10-23T20:03:05.0457140Z > Swapins:                                      0.
2019-10-23T20:03:05.0457330Z > Swapouts:                                     0.
```

The "Pages free:" number is probably a good place to start. 1714166 pages is ~7GB free.

The initial values:
```
job 1: 2019-10-23T20:03:05.0451050Z > Pages free:                             1714166.
job 2: 2019-10-23T20:00:11.1752870Z > Pages free:                             1805371.
job 3: 2019-10-23T19:59:49.1933410Z > Pages free:                             1817957.
job 4: 2019-10-23T19:59:41.6214160Z > Pages free:                             1825136.
job 5: 2019-10-23T20:03:14.5684490Z > Pages free:                             1774477.
```

And the final values:
```
job 1: 2019-10-23T21:42:14.0025900Z > Pages free:                             1472470.
job 2: 2019-10-23T20:18:12.6852840Z > Pages free:                             1314056.
job 3: 2019-10-23T21:37:57.6381420Z > Pages free:                             1177468.
job 4: 2019-10-23T21:46:50.2138770Z > Pages free:                             1415510.
job 5: 2019-10-23T20:49:18.5369440Z > Pages free:                             1157131.
```

So... I don't think this is a memory problem, the jobs that lost communication aren't even the ones with the least amount of memory left, and it's >5GB free anyway.

**Comment by foolip** [comment]
Looking at the timestamps instead:
<table>
<tr><th>job</th><th>first</th><th>last</th><th>delta</th></tr>
<tr><td>1</td><td>2019-10-23T20:03:04.7903630Z</td><td>2019-10-23T21:43:05.4066580Z</td><td>100 min</td></tr>
<tr><td>2</td><td>2019-10-23T20:00:10.9870590Z</td><td>2019-10-23T20:18:25.4154710Z</td><td>18 min</td></tr>
<tr><td>3</td><td>2019-10-23T19:59:49.0202120Z</td><td>2019-10-23T21:38:14.4852100Z</td><td>98 min</td></tr>
<tr><td>4</td><td>2019-10-23T19:59:41.4368640Z</td><td>2019-10-23T21:46:55.0410820Z</td><td>107 min</td></tr>
<tr><td>5</td><td>2019-10-23T20:03:14.2027950Z</td><td>2019-10-23T20:49:25.1956120Z</td><td>46 min</td></tr>
</table>

So, job 2 and 5 stopped producing any output much earlier than the run time shown in the Azure Pipelines UI would suggest.

Even if `./wpt run` got stuck, the `vm_stat.sh` should still have been running and producing output.

@mustjab this suggests that something has broken in the communication between the agent and the Azure Pipelines infrastructure. Other than printing to the console, is there any one way to show proof of life for an agent? Other than running out of memory, what might cause the connection to fail? Are we producing too much log output, perhaps?

**Comment by foolip** [comment]
There mere size probably isn't the problem, the logs for job 2 and 5 where they end is still smaller than the full logs of the successful jobs.

**Comment by mustjab** [comment]
Thanks for this info! Updated ticket with pipeline team with info, they're still investigating and i'll let you know as soon as i hear back from them.

**Comment by foolip** [comment]
Thanks @mustjab! I'll keep monitoring this to see if things always seem to hang at the same point or not. If they do, then that's something to start from.

**Comment by foolip** [comment]
@mustjab one thing I've had in the back of my mind for a while and which might also help mitigate this issue is to increase runs of Edge and Safari from every 6 hours to every 3. Since we only trigger if something has changed that wouldn't be a 2x increase in load but actually 1.5, going by the commit distribution since mid-2017.

It's wouldn't change the required parallel builds, but still, do you think that'd be acceptable? Microsoft is sponsoring this capacity, after all.

**Comment by mustjab** [comment]
Sounds good, the machines that we maintain are running 24/7 so don't expect much increase in cost.

**Comment by foolip** [comment]
Great, let's try it!

**Comment by foolip** [comment]
This continues to happen, https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=36734 is a recent case. Running more often means it's not a huge problem when one fails, but when Safari stable fails it's more noticeable.

@mustjab have you heard anything on the internal issue tracking this?

**Comment by mustjab** [comment]
The ticket with pipeline team is still active and is under investigation. They haven't been able to repro this issue yet and it looks like by the time we share failed runs they don't have enough info to determine the root cause.

**Comment by foolip** [comment]
It reproduces for us regularly, so if there's any debugging we can add to our live jobs to help find the cause, we can absolutely do that.

**Comment by mustjab** [comment]
Do you have data on how often we see this issue in Mac runs? They do have a capacity issue on Macs that they're working to address.

**Comment by foolip** [comment]
I don’t have a script, but every time I look I can find instances in the past few days, so I would estimate it happens with at least 5% of runs.

@stephenmcgruer monitoring might help answer questions like this, although realistically distinguishing different failure causes would be more work than it’s worth. Still, I’m pretty sure this is the most common cause right now, so just counting successful runs would do the trick.

**Comment by mustjab** [comment]
@foolip Got an update from Azure Pipeline team that they've made some internal changes to make this issue less likely to happen, have you seen any recent failures due to this issue?

**Comment by foolip** [comment]
@mustjab it has always been easy to find recent cases each time I've looked, but now it's not. https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=39216 from Dec 19 is the latest epochs/three_hourly run with any failure in STP, and it wasn't for this reason. I didn't look further back than that.

There are have been ~35 successful runs since then, so I would call this fixed. Many thanks for helping push this internally!

**Comment by mustjab** [comment]
Glad to see that his is fixed now, sorry it took so long. Thanks for your patience on this.
