### ISSUE TITLE
Hosted Windows Client pool is only running 5 concurrent jobs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18671]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=28606 is taking much more time than usual as only 5 jobs are running at the same time:
![image](https://user-images.githubusercontent.com/498917/63680848-d3bf7b80-c7f4-11e9-9c5e-68508a3071f3.png)

Here's a screenshot of https://dev.azure.com/web-platform-tests/_settings/agentpools:
![image](https://user-images.githubusercontent.com/498917/63680900-ea65d280-c7f4-11e9-9f06-ee12034edbe3.png)

So there are 5 jobs running and 10 queued.

https://dev.azure.com/web-platform-tests/_settings/agentpools?poolId=7&view=agents claims there are 13 online agents, which is less than the expected 20, but still most of them are idle.

@mustjab can you investigate?

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/18632 may make this less likely, but that's a guess.

**Comment by foolip** [comment]
Oops, posted on the wrong issue, https://github.com/web-platform-tests/wpt/pull/18632 has no relation to this.

**Comment by mustjab** [comment]
@foolip The pipeline that we've setup to create Windows VMs is setup to create 20 VMs with a custom script that we run to register agents with WPT project and it looks like some of the agent setup tasks are failing. I've updated pipeline to create 25 VMs and will monitor for failures, but this should give us enough agents to run jobs.

**Comment by foolip** [comment]
Thanks @mustjab! I'll go ahead and close this, can revisit if it happens again.
