### ISSUE TITLE
GitHub Action intermittently fails to label pull requests

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#18704]
The GitHub Action named "Synchronize the Pull Request Preview" which ran for gh-18602 failed with the following message:

    INFO:__main__:Adding label
    INFO:__main__:Issuing request: POST https://api.github.com/repos/web-platform-tests/wpt/issues/18602/labels
    Traceback (most recent call last):
      File "tools/ci/update_pr_preview.py", line 253, in <module>
        code = main(sys.argv[1])
      File "tools/ci/update_pr_preview.py", line 225, in main
        github.add_label(pr_number, active_label)
      File "tools/ci/update_pr_preview.py", line 161, in add_label
        request(url, 'post', json_data=data)
      File "tools/ci/update_pr_preview.py", line 65, in request
        resp.raise_for_status()
      File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/web-platform-tests/wpt/issues/18602/labels
    ##[error]Docker run failed with exit code 1

Reviewing recently-filed pull requests, this appears to be an intermittent error. At first, I thought it was because the pull request comes from a fork. Even though [we explicitly tested for that](https://github.com/web-platform-tests/wpt/pull/17680), the GitHub Actions beta has recently undergone some drastic changes. But gh-18619 demonstrates that it's still possible for this GitHub Action to run under these conditions.

Since [we know GitHub Actions to be unstable](https://github.com/web-platform-tests/wpt-pr-bot/issues/77#issuecomment-525386655) and since this particular Action doesn't influence the "mergeable" status of the pull requests, we may want to wait until the feature leaves "beta" before researching much further.

**Comment by foolip** [comment]
This looks like it's probably an issue with the GitHub API's availability, rather than anything about GitHub Actions. Could it be a quota issue?

**Comment by foolip** [comment]
Are there other PRs from forks where this worked?

**Comment by foolip** [comment]
Have you also found PRs where the PR owner does have write access to the wpt repo and still uses a fork, as is the case with https://github.com/web-platform-tests/wpt/pull/18602? I don't expect that difference matters, but... dunno?

**Comment by foolip** [comment]
Argh :)

I wonder if retrying gh-18602 will "fix" the problem? If so it might suggest we need retry logic.

**Comment by foolip** [comment]
This job is no longer running.
