### ISSUE TITLE
Leverage the GitHub deployments for PR mirroring

### ISSUE THREAD

**Issue by lukebjerring** [web-platform-tests/wpt#18769]
@jugglinmike has been implementing a PR-mirroring behaviour for web-platform-tests.live.

This technique involves a special label, `pull-request-has-preview`, but there's no link provided to the user on the PR itself. It should be a small leap to get the GitHub action to [create a deployment via the GitHub API](https://developer.github.com/v3/repos/deployments/#create-a-deployment) and then set the status when the action completes.

**Comment by lukebjerring** [comment]
cc @foolip who originally investigated feasibility.

**Comment by foolip** [comment]
@lukebjerring do you have a PR on wpt.fyi that shows this in action?

**Comment by lukebjerring** [comment]
It's a WIP for wpt.fyi, but here's the appearance of successfully calling the API from a local branch:
https://github.com/web-platform-tests/wpt.fyi/pull/1442#event-2597229330

**Comment by jugglinmike** [comment]
The feature is not currently deployed to a stable URL. (The documentation incorrect claims otherwise, so I've filed gh-18772 to avoid further confusion until we find the new home)

**Comment by foolip** [comment]
@jugglinmike are you going to use the deployments API for wptpr.live deployments, i.e., can I assign this to you? There might be some stuff to copy from https://github.com/web-platform-tests/wpt/pull/18773.

**Comment by stephenmcgruer** [comment]
The wptpr.live code was launched (albeit for same-repo - no forks - only atm), and uses the deployment API. So this doesn't seem relevant anymore.
