### ISSUE TITLE
canceling-an-animation.html has a harness error in all browsers

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18932]
https://staging.wpt.fyi/results/web-animations/timing-model/animations/canceling-an-animation.html?run_id=227500002&run_id=259130004&run_id=253190002&run_id=247230003

Chrome and Edge have a harness error saying "The user aborted a request" and Firefox and Safari say "The operation was aborted".

@birtles @flackr @graouts @stephenmcgruer any idea what's going on here?

Context: consistent harness error usually indicate a problem with the test, and there aren't very many of them. It would be nice if there were none and we could add tooling to prevent them from being introduced.

**Comment by graouts** [comment]
This is due to this test:

```javascript
test(t => {
  const animation = createDiv(t).animate(null);
  const promise = animation.ready;
  animation.cancel();
  assert_not_equals(animation.ready, promise);
}, 'The ready promise should be replaced when the animation is canceled');
```

The `ready` promise is rejected when calling `cancel()` and there is no code handling that promise's rejection. I suppose we could add:

```javascript
promise_rejects(t, 'AbortError', promise, 'Cancel should abort ready promise');
```

**Comment by foolip** [comment]
Aha, thanks @graouts!

If there are other tests that check that `animation.cancel()` rejects then just `animation.cancel().catch(() => {})` would probably be fine here. But are there?

**Comment by foolip** [comment]
Oh, sorry, it's not the return value of `animation.cancel()` that is rejected, it's the `animation.ready` promise.

**Comment by graouts** [comment]
@birtles does it sound right to you to make this change?

**Comment by stephenmcgruer** [comment]
It sounds right to me, if that helps :). Canceling an animation runs the [reset an animation's pending tasks](https://drafts.csswg.org/web-animations-1/#reset-an-animations-pending-tasks) steps, which includes rejecting the ready promise.

**Comment by graouts** [comment]
I updated the test, I think this closes this issue.

**Comment by foolip** [comment]
Thanks @graouts, your fix worked!
https://wpt.fyi/results/web-animations/timing-model/animations/canceling-an-animation.html?run_id=306910002&run_id=297330004&run_id=308180006

**Comment by graouts** [comment]
That's what I like to hear! Next step is to fix this last assertion in Safari.

**Comment by birtles** [comment]
> @birtles does it sound right to you to make this change?

The change seems fine. I'm not sure if I agree with having the test harness error on unhandled Promise rejections, however.
