### ISSUE TITLE
Safari builds fail on web-share/share-sharePromise-internal-slot.https.html

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#18995]
STP on Azure Pipelines has been failing job 2 recently:
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30405
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30444
- https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30470

These are not the same failure mode as https://github.com/web-platform-tests/wpt/issues/18669, although I spotted some more of that too.

https://gist.github.com/foolip/d1cb47b31c7c50d859d4bb7f1ffa4e71 is the end of the logs for the first listed build, and the other two are similar.

It started happening right after https://github.com/web-platform-tests/wpt/pull/18967 was landed, so this is probably a persistent failure that won't go away, and thus urgent.

**Comment by foolip** [comment]
The test where everything falls apart is https://github.com/web-platform-tests/wpt/blob/master/web-share/share-sharePromise-internal-slot.https.html, which uses `test_driver.bless()`. A familiar pattern from https://github.com/web-platform-tests/wpt/issues/18635.

**Comment by Hexcles** [comment]
Interestingly, this test also trips a DCHECK on Chrome, which I'm not sure whether is a coincidence: https://crbug.com/1002514

**Comment by foolip** [comment]
This is probably also the cause for failure for Safari stable:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30446

(Logs too big to view online, and don't know how to open huge textfiles in ChromeOS.)

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/19003 merged, these two builds will tell if that was enough to recover:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30562
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=30563

**Comment by foolip** [comment]
Success! https://wpt.fyi/results/?sha=e2498db8b0&max-count=10

**Comment by foolip** [comment]
https://wpt.fyi/results/web-share/share-sharePromise-internal-slot.https.html?sha=857ac64cb1&label=pr_head (for https://github.com/web-platform-tests/wpt/pull/19004) showed that running just that test doesn't fail. So probably there's bad state that this test runs into, caused by some previous test.

**Comment by foolip** [comment]
This is happening again in https://github.com/web-platform-tests/wpt/pull/20878, need to put back the `--exclude` for this test.

**Comment by stephenmcgruer** [comment]
Similar to the other issue I commented on today, it's not clear to me we should be tracking this. The bug here is that we can't handle Safari crashing during runs - the actual testing crashing is a WebKit bug to be filed, surely? The real issue here is https://github.com/web-platform-tests/wpt/issues/19620 (which tracks handling Safari crashing).

**Comment by foolip** [comment]
Yes, given a WebKit bug we could link to that instead and close this.

**Comment by gsnedders** [comment]
Closing this as #27427 has meant we don't need to maintain a blocklist of tests; the rest of the issue here is a safaridriver one (probably rdar://74197601).
