### ISSUE TITLE
Message for unhandled promise rejection is not very helpful

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19021]
In https://github.com/web-platform-tests/wpt/issues/18932 there was a harness error that said "The user aborted a request" or "The operation was aborted". This turned out to be because of an unhandled promise rejection and fixed in https://github.com/web-platform-tests/wpt/pull/19001.

That it was an unhandled promise rejection wasn't at all clear. That's because the handling of this is to simply use `event.reason.message` as the message:
https://github.com/web-platform-tests/wpt/blob/152adb0185fcfa41ef244355b275a197c3c45f55/resources/testharness.js#L3368-L3399

Prefixing the error with "Unhandled rejection" would really help.

@web-platform-tests/wpt-core-team for opinions.

**Comment by Ms2ger** [comment]
At least in theory, the messages are not guaranteed to be stable. Adding the extra text makes sense to me.

**Comment by foolip** [comment]
Toying with it in https://github.com/web-platform-tests/wpt/pull/19092 to see how much it affects.

**Comment by jugglinmike** [comment]
Assertion messages are not considered stable, but Chromium currently depends on them to some extent: gh-17974
