### ISSUE TITLE
[IndexedDB] Remove `lastModifiedDate`

### ISSUE THREAD

**Issue by brettz9** [web-platform-tests/wpt#19275]
The test at https://github.com/web-platform-tests/wpt/blob/453453af2e854b13228cab2da314cc2a4d1ffc86/IndexedDB/structured-clone.any.js#L291-L292 is now outdated per https://github.com/w3c/IndexedDB/pull/300

**Comment by zcorpan** [comment]
Should instead test in https://github.com/web-platform-tests/wpt/blob/master/IndexedDB/historical.html that this property is not supported.

**Comment by inexorabletash** [comment]
Oops, thanks for catching this. I thought I'd checked for lastModifiedDate usage in WPT, guess I failed.

**Comment by brettz9** [comment]
No worries on my account! Thanks!
