### ISSUE TITLE
Chrome Dev runs on Taskcluster are consistently failing

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19297]
Discovered by seeing a lot of red in https://github.com/web-platform-tests/wpt/commits/master and confirmed no recent results on https://wpt.fyi/runs, now investigating.

**Comment by foolip** [comment]
The failures begun with 2e176421fca7bc3644bd39846305922a848c2b58 which was the merge of https://github.com/web-platform-tests/wpt/pull/19229.

https://tools.taskcluster.net/groups/MZqDqP19TmSOjxsv0qeJqw is that first failure on Taskcluster. Screenshot:
![image](https://user-images.githubusercontent.com/498917/65600760-0c43a800-dfa1-11e9-8bd8-01d3fed971c2.png)

wpt-chrome-dev-reftest-1 failed with "Task timeout after 7200 seconds. Force killing container."

**Comment by foolip** [comment]
The successful run before that was https://tools.taskcluster.net/groups/fwiwJe9RSQ22S1HaAZaE-g.

**Comment by foolip** [comment]
The versions of Chrome installed weren't the same, and in fact bumped from 78 to 79, package names were 78.0.3904.17 to 79.0.3921.0.

The versions of chromedriver downloaded were https://chromedriver.storage.googleapis.com/78.0.3904.11/chromedriver_linux64.zip and https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/698801/chromedriver_linux64.zip respectively.

This all makes it very likely that the cause is a change in the Chromium tree, or possible we're using an incompatible version of ChromeDriver.

@JohnChen0 are you aware of any recent regression that would explain this?

**Comment by foolip** [comment]
The chromedriver version to download is determined here:
https://github.com/web-platform-tests/wpt/blob/a4a77d8841d2f874653f0594dae72dec4cb1299a/tools/wpt/browser.py#L534-L586

So it looks like we're falling back to `_chromium_chromedriver_url`, presumably because chromedriver hasn't been released for 79 yet?

**Comment by foolip** [comment]
https://chromedriver.storage.googleapis.com/LATEST_RELEASE_78 returns "78.0.3904.11" and https://chromedriver.storage.googleapis.com/LATEST_RELEASE_79 is 404, so I think this is the root cause.

Unfortunately we don't have a way to pin Chrome, so I'm not sure how to work around this. We could install beta instead and use the experimental flags, that's currently at 78.0.3904.21 which is very close to what the dev channel was before this breakage.

**Comment by foolip** [comment]
I've filed https://bugs.chromium.org/p/chromedriver/issues/detail?id=3150.

**Comment by JohnChen0** [comment]
I am not aware of any recent changes in Chrome or ChromeDriver that should cause this. ChromeDriver from https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/698801/chromedriver_linux64.zip is expected to be compatible with Chrome version 79.0.3921.0.

I tried running tests under webdriver directory locally on my Linux box using the latest build of Chrome and ChromeDriver. I saw two tests timeout (webdriver/tests/switch_to_window/alerts.py and webdriver/tests/permissions/set.py), while the other tests gave expected results.

I'm currently running a larger set of tests to see what happens.

**Comment by foolip** [comment]
Running the first shard of reftests using the same command line as is used in Taskcluster might reproduce the problem, or at least that's what I'd try first.

**Comment by lukebjerring** [comment]
This issue is likely also causing infrastructure/ test failures on PRs, like https://tools.taskcluster.net/groups/Ob8TSf1GTFm2vIddmPEvfg/tasks/KI7gmJRqSgKQdVdpegKnPw/runs/0/logs/public%2Flogs%2Flive.log#L1754

**Comment by foolip** [comment]
Some investigation happening in https://github.com/web-platform-tests/wpt/pull/19332.

**Comment by foolip** [comment]
I think https://github.com/web-platform-tests/wpt/pull/19360 will have "fixed" this, and I've started a postmortem in https://github.com/web-platform-tests/wpt/issues/19362.

The root cause is still unknown.

**Comment by foolip** [comment]
Closing this to open a new issue about getting Chrome Dev unpinned again.
