### ISSUE TITLE
Unreviewed commits on master

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19311]
These 3 commits from May 14 seem to have landed without going through review:
39e5c2b4a6da7d2a619364b556c5ec59a934c89b
e0fd5d58eb5697dae077cf091fe2f74f64f63701
68ceaae7aecf1afbc7f0698ee6ba8c6c7097363d

I noticed because for the first and last there are wpt.fyi runs:
https://wpt.fyi/runs?sha=39e5c2b4a6da7d2a619364b556c5ec59a934c89b
https://wpt.fyi/runs?sha=68ceaae7aecf1afbc7f0698ee6ba8c6c7097363d

The total diff introduced by these commits:
```diff
--- a/tools/ci/website_build.sh
+++ b/tools/ci/website_build.sh
@@ -56,12 +56,12 @@ git config --global user.name "wpt-pr-bot"
 
 # Prepare the output directory so that the new build can be pushed to the
 # repository as an incremental change to the prior build.
-mkdir --parents docs/_build/html
+mkdir -p docs/_build/html
 cd docs/_build/html
 git init
 git fetch --depth 1 ${remote_url} gh-pages
 git checkout FETCH_HEAD
-git rm -r .
+git rm -rf .
 
 # Build the website
 cd ../..
@@ -78,7 +78,7 @@ touch .nojekyll
 # Publish the website by pushing the built contents to the `gh-pages` branch
 git add .
 
-if ! git diff --exit-code --quiet --staged ; then
+if git diff --exit-code --quiet --staged ; then
   echo No change to the website contents. Exiting without publishing.
 
   exit ${neutral_status}
```

@gsnedders @jugglinmike do either of you know what happened here? Doesn't branch protection prevent this from happening?

**Comment by foolip** [comment]
5612fb4f2c1bb60561a54cf670eaa971d01d0214 is in this same category (wpt.fyi runs labeled master that don't have merge_pr_* tags) and explained by https://github.com/web-platform-tests/wpt/pull/16806. So it looks like @gsnedders was pushing to master in order to fix the docs build.

Leaving open to confirm.

**Comment by foolip** [comment]
Just a few more to check, but is 78384fb41b6f678b2d9a3ebc2bf9f0fdbc1277c2 is another. @sideshowbarker I've looked through PRs but can't find anything, and https://api.github.com/search/issues?q=type:pr+is:merged+repo:web-platform-tests/wpt+sha:78384fb41b6f678b2d9a3ebc2bf9f0fdbc1277c2 doesn't return any either.

Do you think you accidentally pushed this directly to master?

**Comment by jugglinmike** [comment]
> it looks like @gsnedders was pushing to master in order to fix the docs build.

That's correct. Sam and I were working closely together on this. We would of course prefer not to treat `master` as a testing ground, but it was unavoidable in this case.

We'd previously vetted the patch and its integration with GitHub using the `master` branch of an independent repository/GitHub project. The issues we were ironing out were related to details that were only apparent when using the canonical repository.

**Comment by foolip** [comment]
The final commit on my list to investigate was c717f05c53ebd6c08d0800833674e36933d323e5, which I explained in https://github.com/web-platform-tests/wpt/pull/18717#issuecomment-529815898 I accidentally pushed directly to master.

If @sideshowbarker's https://github.com/web-platform-tests/wpt/commit/78384fb41b6f678b2d9a3ebc2bf9f0fdbc1277c2 was also a mistake, then perhaps we should enforce branch protection for admins as well.

Nothing very bad has happened as a consequence of this so far, but it does mean that there are some runs in wpt.fyi which were from master for which we can't get a copy of the manifest from releases in this repo. @Hexcles FYI.

**Comment by sideshowbarker** [comment]
> If @sideshowbarker's [78384fb](https://github.com/web-platform-tests/wpt/commit/78384fb41b6f678b2d9a3ebc2bf9f0fdbc1277c2) was also a mistake

Looking at 78384fb, I see the commit was associated with https://github.com/hoojaoh/web-platform-tests/pull/1565, which is a push from the ["pull" bot](https://github.com/apps/pull) that got merged in the **hoojaoh:master** branch of the **hoojaoh/web-platform-tests** for. At this point, I don’t actually have any idea what happened there. I guess the bot pulled some change that had already been committed to master?

Or maybe that’s all irrelevant, since it was change to a branch on fork. I guess maybe GitHub associated it with that PR because it was the only PR it could find to associate it with?

Anyway, regardless, at this point, I don’t actually recall anything about 78384fb.

> then perhaps we should enforce branch protection for admins as well

I think we should enforce branch protection for admins, regardless. I thought we were already doing that, actually. I don’t see any reason why we shouldn’t.

But would enforcing branch protection for admins also have prevented the push from that bot?

**Comment by foolip** [comment]
In https://github.com/web-platform-tests/wpt/settings/branch_protection_rules/1493 I just tried checking this checkbox:
![image](https://user-images.githubusercontent.com/498917/66375251-36d42e80-e9ad-11e9-9b1b-34592a092a75.png)

However, as a result it's not longer possible to admin merge a PR, that is the following UI no longer appears on a PR like https://github.com/web-platform-tests/wpt/pull/19377:
![image](https://user-images.githubusercontent.com/498917/66375368-89154f80-e9ad-11e9-8c0a-d9dfb13b114c.png)

So I've unchecked it again. It would be great to get to a state where we never need to override a failing Taskcluster status, and perhaps with @KyleJu's work to annotate known flakiness we'll get close, but for now we still need to admin merge.

There isn't anything actionable in this issue and I've already asked about or accounted for the unreviewed commits, so closing this.

@web-platform-tests/admins FYI.

**Comment by foolip** [comment]
Oops, I just produced two more commits. I was using the VS Code GitHub integration and had set my upstream to 'master' when I tried to push the branch and create a pull request. I reverted immediately but it resulting in these two commits: 9e1d0a26f155ccb088d342b0036e535d033423c1, f3c657a4d9410c25f0e3c54149cb0e16a0d8c2d6

Sorry!

**Comment by foolip** [comment]
Hah, I did it again! This time I blame the GitHub web UI:
https://github.com/web-platform-tests/wpt/commit/4c854cc5c691210bf631bfce23a0f50ddb06f4b8#commitcomment-35674629
