### ISSUE TITLE
WPT logo: differences in size between with-background and without-background

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#19326]
https://github.com/web-platform-tests/wpt/tree/master/images/wpt-logo

The ones with a background have spacing around the logo, but the ones with transparent background do not. This makes them not so interchangeable. (This is probably my fault.)

Should we make this consistent? cc @foolip @gsnedders @isaacdurazo

**Comment by foolip** [comment]
Yes please :)

Also we can delete the orange one if we don't plan to use it anywhere.

**Comment by isaacdurazo** [comment]
The background color is not intended to be "part" of the logo, it just shows us how it looks in such context. We included a file without background so you could maybe add the background color using CSS, and we have a file with the background color so we know how to use it and how it would look.

**Comment by ZHEL12** [comment]
加上qq群；933241376

**Comment by prsmahajan** [comment]
Hi, I would like to work on this issue, Can I get started with this?

**Comment by foolip** [comment]
@prsmahajan absolutely, feel free to send a PR for it. Do you know where to start, which files to change and all?

**Comment by prsmahajan** [comment]
I want to know, what's the problem you're facing and where to start from?

**Comment by foolip** [comment]
@prsmahajan if you take a look at https://raw.githubusercontent.com/web-platform-tests/wpt/master/images/wpt-logo/wpt-logo-darkblue-bg.svg and https://raw.githubusercontent.com/web-platform-tests/wpt/master/images/wpt-logo/wpt-logo-darkblue.svg side-by-side you'll notice the shapes aren't aligned.

Fixing this would be a matter of making sure that the path data in both files use the same numbers and that the only difference between them is the colors.

**Comment by ZHEL12** [comment]
ok
---原始邮件---
发件人:&quot;Paras ***@***.***&gt;
发送时间:2021年6月8日 星期二 下午3:24
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [web-platform-tests/wpt] WPT logo: differences in size between with-background and without-background (#19326)



Hi,&nbsp;I&nbsp;would&nbsp;like&nbsp;to&nbsp;work&nbsp;on&nbsp;this&nbsp;issue,&nbsp;Can&nbsp;I&nbsp;get&nbsp;started&nbsp;with&nbsp;this?

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;commented.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.

**Comment by prsmahajan** [comment]
Do you want to change the color or the size of the svg icon?

**Comment by foolip** [comment]
@prsmahajan we'd want to keep the colors of each icon as they are, but make the sizes consistent between them all, so that if one replaces one with another, the "WPT" symbol is in exactly the same place.

**Comment by prsmahajan** [comment]
In which of the directories are the svg logo located?

**Comment by foolip** [comment]
They're in https://github.com/web-platform-tests/wpt/tree/master/images/wpt-logo

**Comment by prsmahajan** [comment]
Where are the images being used?

**Comment by prsmahajan** [comment]
The issue is already solved senior, there's no issue in size!

**Comment by foolip** [comment]
@prsmahajan, thanks, I've asked @zcorpan to review https://github.com/web-platform-tests/wpt/pull/29305.

**Comment by prsmahajan** [comment]
Thansk @foolip

**Comment by prsmahajan** [comment]
Is there any issues for me?

**Comment by GAURAV1-ui** [comment]
Can @foolip can I solve this issue?

**Comment by ijishnupr** [comment]
hey can i solve this issue?

**Comment by zcorpan** [comment]
No need to ask, just submit a PR. See https://github.com/web-platform-tests/wpt/pull/29305#issuecomment-858030708 for guidance. Thanks!

**Comment by Neelam-meena** [comment]
Hi, I'm interested in resolving this issue. Can I begin working on adding spacing to the transparent background logos?

**Comment by TheGEN1U5** [comment]
Hey, I am interested in resolving this issue. But, it seems to me that the sizes of the logos are already consistent ( #46186 ). I have verified it in GIMP, the dimensions of the SVGs are the same and no extra spacing is visible. Could someone please check this and close the issue if it has been resolved?

**Comment by zcorpan** [comment]
Yeah https://github.com/web-platform-tests/wpt/pull/46186 fixed this. Closing.
