### ISSUE TITLE
Postmortem: Chrome Dev 78→79 broke PR and master runs

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19362]
**Owner**: @stephenmcgruer 
**Postmortem Created**: 2019-09-27 05:03 EST
**Status**: Published
**Issue**: https://github.com/web-platform-tests/wpt/issues/19297

**Impact**: When the Chrome Dev channel moved from 78 to 79, full runs on Taskcluster (for wpt.fyi) stopped working, and infrastructure/ tests on PRs that trigger those began failing. This led to 2.5 days of a complete outage for Chrome Dev results (until we pinned to the working 78), and delayed the upgrade from 78 to 79 by over a month.

**Root Cause**: A [Chromium change](https://chromium.googlesource.com/chromium/src/+/b4f3df4e77ba1f79717d44b5068cb36f7537332f) to use X11 shared-memory capabilities failed to work in the Taskcluster environment specifically (working correctly in all other known environments). This change would then cause the browser under test to crash.

**Timeline in UTC**:
- 2019-09-24 17:55: [last successful Taskcluster run with 78.0.3904.17](https://tools.taskcluster.net/groups/fwiwJe9RSQ22S1HaAZaE-g) started
- Exact time unknown: [google-chrome-unstable_current_amd64.deb](https://dl.google.com/linux/direct/google-chrome-unstable_current_amd64.deb) rolls to 79
- 2019-09-24 19:15: [first failing run with 79.0.3921.0](https://tools.taskcluster.net/groups/MZqDqP19TmSOjxsv0qeJqw) started
- 2019-09-24 19:15 **OUTAGE BEGINS**
- 2019-09-25 12:28: [Chrome Dev runs on Taskcluster are consistently failing](https://github.com/web-platform-tests/wpt/issues/19297) reported
- 2019-09-25 12:52: [No official chromedriver available for Chrome Dev 79 (breaking web-platform-tests)](https://bugs.chromium.org/p/chromedriver/issues/detail?id=3150) reported
- 2019-09-26 17:15: [Use Chrome beta for infrastructure/ tests (temporarily)](https://github.com/web-platform-tests/wpt/pull/19331) attempt unsuccessful
- 2019-09-26 17:24: [Add --verbose flag for chromedriver](https://github.com/web-platform-tests/wpt/pull/19332) attempt to diagnose the issue with logging and then short-circuiting suspect code.
- 2019-09-27 05:07: [Identified that the screenshot command is failing](https://github.com/web-platform-tests/wpt/pull/19332#issuecomment-535787368)
- 2019-09-27 08:50: [[Taskcluster] pin Chrome Dev to 78.0.3904.17](https://github.com/web-platform-tests/wpt/pull/19360) landed, [Taskcluster run](https://tools.taskcluster.net/groups/SLncRCynRBi5FbiMvctnaQ) triggered
- 2019-09-27 09:23: [PR infrastructure/ tests confirmed passing again](https://github.com/web-platform-tests/wpt/pull/18830#issuecomment-535895032)
- 2019-09-27 10:22: [First Chrome Dev run back on wpt.fyi](https://wpt.fyi/results/?run_id=334000024), 2 days and 15 hours after [previous run](https://wpt.fyi/results/?run_id=322140003)
- 2019-09-27 11:14: [Upgrade to Chrome Dev 79 (pinned to 78)](https://github.com/web-platform-tests/wpt/issues/19367) filed
- 2019-09-28 21:47: [[Taskcluster] unpin Chrome Dev version](https://github.com/web-platform-tests/wpt/pull/19387) draft to continue debugging
- 2019-10-09 22:40: stephenmcgruer@ picks up debugging this, using [this](https://github.com/web-platform-tests/wpt/pull/19609) test CL, and starts adding logging
- 2019-10-12 05:36: stephenmcgruer@ determines root cause must originate from a Chromium change, [starts bisecting](https://github.com/web-platform-tests/wpt/pull/19609/commits/ffb380cfc427fbb1ca6df8fa80343e4dd9e6d35b) Chromium versions.
- 2019-10-12 19:17: Bisect [blames set of 4 chromium commits](https://github.com/web-platform-tests/wpt/issues/19367#issuecomment-541190979), suspect CL identified
- 2019-10-15 16:46: Tip-of-tree Chromium with change backed out confirms suspect CL
- 2019-10-15 19:19: [Chromium bug filed](https://crbug.com/1014629)
- 2019-10-21 14:45: Chromium bug [pinged](https://crbug.com/1014629#c5) due to lack of response
- 2019-10-21 18:55: stephenmcgruer@ connects with CL author, begins [trying patches](https://github.com/web-platform-tests/wpt/pull/19609/commits/0a9bea5d18bcb1ea61bde71f566813be110b302f)
- 2019-10-22 13:27: A [successful patch](https://github.com/web-platform-tests/wpt/pull/19609/commits/ab60b8fb41364e3de7182b76aedfefad804e6a9f) is found
- 2019-10-22 23:37: Patch [lands in Chromium](https://chromium.googlesource.com/chromium/src/+/5b0db30b175344e49c43605872a39af4b27430dc)
- 2019-10-24 18:46: Patch merged back to Chromium M79 branch
- 2019-10-30 17:36: Next Chromium M79 release happens, WPT is [unpinned](https://github.com/stephenmcgruer/web-platform-tests/commit/db37de0d7a3664550d8c1192e84a72a6f82a98db).
- 2019-10-30 17:36 **OUTAGE ENDS**

**Lessons Learnt**

*Things that went well*

- Despite lack of tooling, bisecting Chromium builds on Taskcluster was actually fairly simple - [bisect-builds.py](https://cs.chromium.org/chromium/src/tools/bisect-builds.py) spits out a URL which can (with small hacking) be given to the `run_tc.py` script to use.
- Once the Chromium author was alerted, they were both eager to help fix it and able to quickly identify what the likely problem was.

*Things that went poorly*

- We don't run Chrome Canary for [wpt.fyi](https://wpt.fyi), so did not spot the issue when it actually landed in Chromium.
- It took 2.5 days and a custom PR to pin the Chrome release to M78.
- Since pinning to M78 stopped the obvious bleeding, the work to upgrade to M79 was put to one side for nearly 2 weeks, resulting in [wpt.fyi](https://wpt.fyi) ultimately being behind Chrome Dev for over a month.
- Running the WPT docker image locally was unable to reproduce the bug, despite the fact that docker is supposed to be a self-contained runtime. (It turns out that shared memory privileges bleed through from the host).
- The Chromium bug went un-addressed for almost a week, as the assignee was out of office.

*Where we got lucky*

- (No known entries)

**Action Items**

- [ ] [Mechanism to pin browser versions](https://github.com/web-platform-tests/wpt/issues/19386) _(type=mitigate, owner=???)_
- [ ] [Investigate running Chrome Canary for wpt.fyi](https://github.com/web-platform-tests/wpt.fyi/issues/406) _(type=detect, owner=???)_

**Comment by foolip** [comment]
With infrastructure/ working again in https://github.com/web-platform-tests/wpt/pull/18830#issuecomment-535895032 I'll go around and tell people on PRs if they need to retry Taskcluster.

**Comment by foolip** [comment]
`is:pr is:open updated:>2019-09-24T00:00:00Z -status:success` is the search to go through...

**Comment by stephenmcgruer** [comment]
Eugh, this is why one should do postmortems as soon as possible afterwards. @foolip @Hexcles can you take a look and see if any other action items come to mind for you? All the things I can think of seem a little 'one off' as opposed to addressing a structural issue.

**Comment by foolip** [comment]
@stephenmcgruer I'd say a release process for Chrome+ChromeDriver Dev, so that web developers can rely on Chrome Dev for their testing if they like. What happened here is that we started getting the tip-of-tree chromedriver and while the mismatch wasn't the cause of the breakage, we might have had more time if there was a dev channel for chromedriver. The flip side, however, is that we would have noticed later.

**Comment by stephenmcgruer** [comment]
Sorry, it's not clear to me why having a release process'd chromedriver would have helped here. The bug was in chrome, not chromedriver, and we were able to pin chrome to avoid the problem. I didn't feel a time pressure (indeed, I think lack of time pressure was a bug here that caused us to let this lie for too long), can you explain further?

**Comment by foolip** [comment]
OK, so the mismatched chromedriver was merely a red herring in my initial investigation and not really part of them problem. Let's wait for it to actually break something before calling it out as an action item :)

By "might have had more time" I mean that if chromedriver breaks then having a chromedriver dev release channel would cause us to notice later.

**Comment by stephenmcgruer** [comment]
This post-mortem is now complete. Neither action item have been completed, but they do have issues tracking them, so closing this.

**Comment by Hexcles** [comment]
Update: we now have landed https://github.com/web-platform-tests/wpt/pull/24904 , which will hopefully help us detect such issues sooner.
