### ISSUE TITLE
Mechanism to pin browser versions

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19386]
For both Chrome Dev and Safari Technology Preview, new versions have occasionally had so serious bugs that we've had to revert to using an older version in Taskcluster and Azure Pipelines respectively. See, https://github.com/web-platform-tests/wpt/issues/17186 + https://github.com/web-platform-tests/wpt/issues/19362 for those cases, and https://github.com/web-platform-tests/wpt/pull/17187 + https://github.com/web-platform-tests/wpt/pull/19360 for how the actual pinning was done.

Pinning by directly changing the code that installs the browser works (if you know about it) but I want to propose something similar to requirements.txt to encode the version information, while retaining the ability to just say "latest" when pinning isn't wanted.

This could layer on top of ideas that @jgraham has to pass the browser download URL to wptrunner, and picking the version in a decision task to ensure the same version is tested in every shard.

Advantages:
- easier to pin in response to some breakage if the mechanism exists and is regularly exercised
- this or the supporting code for it would make it easier to get runs of browser version N and N+1 from same state of WPT for comparison

Whether pinning the WebDriver versions is valuable I don't know, so not suggesting that now.

cc @jugglinmike who spent some effort on reproducible builds for https://github.com/web-platform-tests/results-collection.

**Comment by ExE-Boss** [comment]
Looks like **Chrome Dev** now has another bug that needed pinning: <https://github.com/web-platform-tests/wpt/issues/28209> (PR <https://github.com/web-platform-tests/wpt/pull/28238>)

**Comment by foolip** [comment]
Yep. I think @jgraham and I discussed this the last time. One problem is that Firefox Nightly is updated twice a day, so there would have to be at least two commits a day in wpt just bumping the browser versions, more if we bump Chrome and Firefox independently.

At the time I suggested putting the binaries in the Docker image, which would avoid downloading them for each job.

@jgraham have I forgotten some considerations?

**Comment by jgraham** [comment]
I think it's useful to have a mechanism to pin the browser, but pinning by default feels like a lot of overhead compared to any advantage; when something breaks you still have to figure out that it's a browser bug and work out what was the last working version. Of course pinning puts that in the commit history, which is easier than looking at the run logs, but if the tradeoff is 3+ PRs per day just to update the pinned versions it's not worthwhile.

**Comment by foolip** [comment]
I'm going to go ahead and close this since we're not looking at a general mechanism, but something different for each browser. We already pin STP, and the way it would for for Chrome or Firefox would be different.

The most recent breakage is fixed anyway.
