### ISSUE TITLE
Don't use asynchronous test to check MathMLElement onevent attributes

### ISSUE THREAD

**Issue by fred-wang** [web-platform-tests/wpt#19500]
cc @rwlbuis @bkardell 

In mathml/relations/html5-tree/clipboard-event-handlers.tentative.html
and  mathml/relations/html5-tree/math-global-event-handlers.tentative.html 

@bzbarsky suggested we used the following instead:

    var callbackCalled = false;
    function callback() {
          callbackCalled = true;
    }
    doStuffThatShouldCallCallback();
    assert_true(callbackCalled);

**Comment by bzbarsky** [comment]
So concretely, in `math-global-event-handlers.tentative.html` the code could be:

        test(() => {
          const element = document.createElementNS(
            "http://www.w3.org/1998/Math/MathML",
            "math"
          );
          let target = undefined;
          element[name] = (e) => {
            target = e.currentTarget;
          });

          element.dispatchEvent(new Event(withoutOn));
          assert_equals(target, element,
                                 "The event must be fired at the <math> element");
        }, `${name}: dispatching an Event at a <math> element must trigger element.${name}`);

in place of the current `async_test` bit.
