### ISSUE TITLE
Should allow python wpt tests have different test results for different browsers

### ISSUE THREAD

**Issue by LanWei22** [web-platform-tests/wpt#19523]
For some key codes, Chrome and Firefox have different values,
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values

In third_party/blink/web_tests/external/wpt/webdriver/tests/perform_actions/key_events.py, the reason it fails on Chrome but not Firefox is they have different code value for key "Meta", we should allow to get the browser name in the python wpt tests and expect different value for each browser.

**Comment by Hexcles** [comment]
Looping in some authors of the file @whimboo @jimevans 

If the key codes are not standardized across browsers (or the discrepancy is recognized in some spec?), it makes sense to plumb the product into `key_events.py`. I'm not familiar with that code so it's not obvious to me what's the best flow to plumb that data. Could you provide some suggestions?

**Comment by whimboo** [comment]
I assume https://github.com/w3c/webdriver/issues/1457 is the related issue for the WebDriver spec. Discussion should happen over there.

**Comment by Hexcles** [comment]
@whimboo is it the case that if https://github.com/w3c/webdriver/issues/1457 is accepted, then all browsers will produce the same keycodes? If so, then yes we can close this issue and address the spec issue instead. If we still expect browsers to produce different keycodes for the same keys, then this is still a valid discussion to have.

**Comment by whimboo** [comment]
This was fixed a while ago via https://github.com/web-platform-tests/wpt/pull/40992.
