### ISSUE TITLE
idl_test is not mentioned in documentation for idlharness.js

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#19604]
https://web-platform-tests.org/writing-tests/idlharness.html describes various APIs, but not the ones used in actual tests like https://github.com/web-platform-tests/wpt/blob/9bd69017a2c73af9902c9d5556770cbde0a26bbc/css/cssom-view/idlharness.html#L24.

**Comment by Hexcles** [comment]
I ran into this today. @foolip IIRC you reviewed much of it. Would you be able to write some docs for it?

We do have some comments for this API though:
https://github.com/web-platform-tests/wpt/blob/7c50c216081d6ea3c9afe553ee7b64534020a1b2/resources/idlharness.js#L3196-L3209

**Comment by annevk** [comment]
I think I fixed most of this in e867131b48f11ad6fd335f0df21050451d1aa054. Not sure if @foolip saw that or if there's something remaining?

**Comment by foolip** [comment]
I did miss that! https://web-platform-tests.org/writing-tests/idlharness.html#testing-idl-fragments looks great actually. I don't think the API is great, but the docs point out what to look out for regarding the order of dependencies.
