### ISSUE TITLE
Restart Safari after timeout/error

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#19620]
At the moment we fail to even send delete session if the HTTP client has hung because httplib fails to send it because it's already waiting on a response. We should do better.

**Comment by foolip** [comment]
This should resolve https://github.com/web-platform-tests/wpt/issues/18634 and https://github.com/web-platform-tests/wpt/issues/18635.

**Comment by foolip** [comment]
This might have avoided https://github.com/web-platform-tests/wpt/pull/20878, where we failed after "CRITICAL Max restarts exceeded".

**Comment by foolip** [comment]
Yep, https://github.com/web-platform-tests/wpt/pull/20878#issuecomment-567899281 looks like this issue, "Could not create a session: The Safari instance is already paired with another WebDriver session."

**Comment by gsnedders** [comment]
Likely would also resolve #18995.

**Comment by francisx-x** [comment]
OK AYUDARON DEMASIADO PERO NO MAS QUE YO ;) cansancio(era demaciado loo que me hacian)
