### ISSUE TITLE
Instructions for getting started on macOS are very error-prone

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19753]
I have a new MacBook Pro running macOS 10.14.6 and I've tried to follow https://web-platform-tests.org/running-tests/from-local-system.html to run https://github.com/web-platform-tests/wpt/pull/19750 locally.

The way you first notice that there's a problem is the "virtualenv must be installed and on the PATH" error. Attempting `pip install virtualenv` reveals that `pip` is missing, so I start from there:
- `python -m ensurepip` doesn't work, requires `sudo`.
- That installs pip 6.1.1 in /usr/local/bin/pip
- `pip install virtualenv` also doesn't work, needs to be `sudo pip install virtualenv` or `pip install --user virtualenv`.
  - Side distraction: pip says "You are using pip version 6.1.1, however version 19.3 is available. You should consider upgrading via the 'pip install --upgrade pip' command." and I did `sudo pip install --upgrade pip`. 
- I did `pip install --user virtualenv` which puts the binary in ~/Library/Python/2.7/bin/virtualenv. I had that on my PATH but for other reasons, the docs don't say so.

`no_proxy='*' ./wpt run --yes --no-manifest-update --manifest MANIFEST.json --metadata infrastructure/metadata/ --log-tbpl - --log-tbpl-level info --channel preview safari infrastructure/` then failed like this:
```
Traceback (most recent call last):
  File "/Users/foolip/web-platform-tests/wpt/_venv/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/cli/main_parser.py", line 12, in <module>
    from pip._internal.commands import (
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/commands/__init__.py", line 6, in <module>
    from pip._internal.commands.completion import CompletionCommand
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/commands/completion.py", line 6, in <module>
    from pip._internal.cli.base_command import Command
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 18, in <module>
    from pip._internal.download import PipSession
  File "/Users/foolip/web-platform-tests/wpt/_venv/lib/python2.7/site-packages/pip/_internal/download.py", line 17, in <module>
    from pip._vendor.cachecontrol.caches import FileCache
ImportError: No module named caches
CRITICAL:tools.wpt.utils:('/Users/foolip/web-platform-tests/wpt/_venv/bin/pip', 'install', '--prefer-binary', '-r', u'/Users/foolip/web-platform-tests/wpt/tools/wpt/../wptrunner/requirements.txt') exited with return code 1
CRITICAL:tools.wpt.utils:
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/foolip/web-platform-tests/wpt/tools/wpt/wpt.py", line 143, in main
    venv = setup_virtualenv(main_args.venv, main_args.skip_venv_setup, props)
  File "/Users/foolip/web-platform-tests/wpt/tools/wpt/wpt.py", line 123, in setup_virtualenv
    venv.install_requirements(path)
  File "/Users/foolip/web-platform-tests/wpt/tools/wpt/virtualenv.py", line 125, in install_requirements
    self.pip_path, "install", "--prefer-binary", "-r", requirements_path
  File "/Users/foolip/web-platform-tests/wpt/tools/wpt/utils.py", line 49, in call
    return subprocess.check_output(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('/Users/foolip/web-platform-tests/wpt/_venv/bin/pip', 'install', '--prefer-binary', '-r', u'/Users/foolip/web-platform-tests/wpt/tools/wpt/../wptrunner/requirements.txt')' returned non-zero exit status 1
```

I don't know what went wrong there. `git clean -fdx` fixes it. I *think* I might have run `./wpt run` once before I upgraded pip, and perhaps I had a copy of the wrong pip in my _venv folder?

I also note that the Azure Pipelines setup uses `sudo easy_install pip` instead of `sudo python -m ensurepip`. I don't know if there's a difference.

The specifics of the above will probably quickly become stale. However, what should be true is:
- Steps for getting started on macOS should work out of the box
- Doing those steps slightly out of order shouldn't cause everything to blow up
- Ideally `./wpt run` should point at the docs when some dependency is missing

@jugglinmike FYI

**Comment by foolip** [comment]
A good example of `./wpt run` telling you clearly what to do is when you haven't updated /etc/hosts. It says:

```
Missing hosts file configuration. Run

./wpt make-hosts-file | sudo tee -a /etc/hosts
```

Similar messages for missing `pip` and `virtualenv` that work on Windows, macOS and Debian/Ubuntu would be *great*.

**Comment by foolip** [comment]
I'm self-assigning this to fix the documentation, then @Hexcles will try the instructions on a new MacBook Pro.

**Comment by foolip** [comment]
There's some great background in https://github.com/web-platform-tests/wpt/pull/16670 on the current docs. @jugglinmike and @gsnedders should probably review any fix for this issues to make sure I do t mess it up.

**Comment by foolip** [comment]
I tried to builds to compare [`sudo easy_install pip`](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35271), which is now used on Azure Pipelines, to [`sudo python -m ensurepip`](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35272), which is what the docs recommend modulo the `sudo`.

It looks like they both install the binary at `/usr/local/bin/pip` and right now the version for both approaches is 19.1.1, so I wonder if they are the same thing underneath.

**Comment by foolip** [comment]
https://setuptools.readthedocs.io/en/latest/easy_install.html says that `easy_install` is deprecated and that you should use `pip`. That's funny when trying to install `pip`, but it suggests we should keep recommending `python -m ensurepip`. I'll try switching Azure Pipelines to that to ensure that it works.

**Comment by foolip** [comment]
@Hexcles helped try `python -m ensurepip` in https://github.com/web-platform-tests/wpt/pull/19927#issuecomment-546733677.

Can you also try it with `--user` and see if that does anything useful?

**Comment by Hexcles** [comment]
https://github.com/web-platform-tests/wpt/pull/19932#issuecomment-546735156

**Comment by foolip** [comment]
Closing, https://web-platform-tests.org/running-tests/from-local-system.html#macos-setup is actually pretty short and OK now.
