### ISSUE TITLE
Edge Dev runs are not very reliable

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19772]
Looking at https://wpt.fyi/runs, Edge Dev runs have often been missing lately. Because Edge Dev is in the set that we use for the wpt.fyi front page, this is pretty serious, each failure delays the front page updating by 6 hours.

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34764 is the most recent failure, and it looks from the logs of "all tests: Edge Dev 9" like Edge never even started correctly, EdgeDriver thinks it crashed.

**Comment by foolip** [comment]
This seems a lot like https://github.com/web-platform-tests/wpt/issues/18044 which just went away. Now it's back :)

**Comment by foolip** [comment]
It is also a lot like https://github.com/web-platform-tests/wpt/issues/19005...

**Comment by mustjab** [comment]
@foolip It does look like on that machine Edge kept crashing, do we save any of the dump files into run artifacts? 

When i look at the cleanup script, i see that we're failing to find uninstaller for Edge Dev channel: 
Failed to unstall Edge from C:\Program Files (x86)\Microsoft\Edge Dev\Application. ERROR= Cannot bind argument to parameter 'Path' because it is null.

While on machines where Dev channel runs worked, i see this:
Uninstall: C:\Program Files (x86)\Microsoft\Edge Dev\Application\79.0.301.2\Installer\setup.exe --uninstall --msedge-dev --system-level --force-uninstall

I'll need to make a change to install/uninstall scripts to log more information to ensure that install/uninstall works as expected.

**Comment by foolip** [comment]
@mustjab other than the logs and things we move into `$(Build.ArtifactStagingDirectory)` I don't think anything can be recovered.

Is there more verbose logging to files that we should enable? We could then make sure they are saved even on failure.

**Comment by mustjab** [comment]
@foolip I was able to login to failing machine and inspect it's state and found that it had an instance of Edge process running that we couldn't close. This blocked uninstall of Edge to cleanup the folder properly, which affected Edge setup in subsequent runs.

I'll send a PR to add more logging and copy setup log files to artifacts folder to help us debug failures in the future.

**Comment by foolip** [comment]
Thanks @mustjab for the quick diagnostics and fix! I've already merged it, but leaving this open to see it working as intended for a few days before closing.

**Comment by mustjab** [comment]
@foolip Let me know if it doesn't work and i can investigate again on Monday.

**Comment by foolip** [comment]
Unfortunately, the next build after this fix still failed:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34848

**Comment by foolip** [comment]
I've started https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34854 to retry it.

**Comment by foolip** [comment]
I think perhaps what happened there is that the restart logic kicked in, because the cleanup step failed.

**Comment by foolip** [comment]
The restart kicked in in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34870, manifesting as "w10c000009 lost communication with the server". That led to the wpt.fyi hook not being run, but all the results were collected.

I got the results into wpt.fyi by running `curl -f -s -S -d "artifact=edge-dev-results" -X POST https://wpt.fyi/api/checks/azure/34870` manually.

Not sure if this is a good idea or not. @mustjab when there are unkillable Edge processes still running, do you think the results are suspect, or would it be a good idea to upload them to wpt.fyi anyway?

**Comment by mustjab** [comment]
Looks like when we hit this issue then the results from that machine are unreliable. I'll login to failed machine and collect memory dump to see if we can identify the root cause of this issue.

**Comment by foolip** [comment]
OK, let's not automatically submit those results to wpt.fyi then. https://wpt.fyi/results/?run_id=346070001 is the run that I manually poked the endpoint for.

[Comparing it with the previous run](https://wpt.fyi/results/?q=is%3Adifferent&run_id=322960001&run_id=346070001) shows that mostly it's regressions, and some I checked are in the form of missing results.

I'll rename the product of that run to 'badedge' to avoid it showing up on the dashboard and analysis.

**Comment by foolip** [comment]
Anyway, the good news is that Edge Dev runs have been pretty reliable over the weekend, and with the change https://github.com/web-platform-tests/wpt/pull/19792 seem capable of recovering from a bad state. So I'll resolve this. Many thanks, @mustjab!

**Comment by foolip** [comment]
Alright, the suspect run no longer appears in https://wpt.fyi/runs/?sha=43aa377085.
