### ISSUE TITLE
Investigate upstreaming simulcast loopback test page as WPT test

### ISSUE THREAD

**Issue by jan-ivar** [web-platform-tests/wpt#19778]
[TPAC ACTION](https://www.w3.org/2019/09/18-webrtc-minutes.html#ActionSummary): Florent to investigate upstreaming his simulcast loopback test page as WPT test

cc @Orphis

**Comment by fippo** [comment]
We have a bunch of simulcast tests in https://wpt.fyi/results/webrtc/simulcast?label=experimental&label=master&aligned
