### ISSUE TITLE
`sudo safaridriver --enable` not working for Safari stable

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19845]
Just as [not running latest release of Safari Technology Preview](https://github.com/web-platform-tests/wpt/issues/17186) was resolved, the same [underlying issue with `sudo safaridriver --enable`](https://github.com/web-platform-tests/wpt/issues/17186#issuecomment-529862851) has begun affecting the daily Safari stable runs.

The [first failing build](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35019) shows this in the logs:
> SessionNotCreatedException: session not created (500): Could not create a session: You must enable the 'Allow Remote Automation' option in Safari's Develop menu to control Safari via WebDriver.

(Compare to the [last successful build](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=34943).)

Probably the system version of Safari stable has changed.

@burg FYI

**Comment by foolip** [comment]
[Manual build to double check that it's really broken on master](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35036) &ndash; it is.

[Manual build to check if upgrading to macOS Mojave fixes the problem](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35037) &ndash; it doesn't.

**Comment by foolip** [comment]
In [this test](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35038), `safaridriver --version` says "Included with Safari 13.0.1 (13608.2.11.1.10)". That is exactly the same as for the [last successful run](https://wpt.fyi/results/?run_id=324930001), so now I don't have any hypothesis for what's changed. I can't find any detailed information about the agent (VM) in Azure Pipelines logs to judge if the OS might have had a minor upgrade.

**Comment by foolip** [comment]
I brought back an old plist hack in https://github.com/web-platform-tests/wpt/pull/19846 and it seems to be working.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/19846 has been merged and https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35044 is a manually triggered run of master for both Safari stable and TP. That should reveal if we're in a good state again.

**Comment by foolip** [comment]
Alright, we're good again. https://wpt.fyi/results/?diff&filter=ADC&run_id=324930001&run_id=313710016 shows no major regression between the old and new runs, probably mostly explained by actual changes to the tests and flakiness.

Downgrading the priority and updating title to match.

**Comment by foolip** [comment]
@burg do you have some idea of what happened here, and how likely it is that the safaridriver for Safari stable will get into the same state as STP was between 92 and 93, where no workaround at all for `sudo safaridriver --enable` seemed possible?

**Comment by burg** [comment]
The next major release will include both fixes for —enable.

**Comment by foolip** [comment]
That's great, thanks @burg! I guess that'll be Safari 13.1 in ~6 months? Will safaridriver remain unchanged until then, or at least not roll in the changes that caused the problem in STP 92?

**Comment by foolip** [comment]
This is fixed now with a workaround, I'll close this and revert the workaround when it's no longer needed, probably when the runs break because it no longer works.

**Comment by foolip** [comment]
It looks like the workaround no longer works with macOS Catalina: https://github.com/web-platform-tests/wpt/pull/21628#issuecomment-585096435
