### ISSUE TITLE
Implement assert_precondition (RFC)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19844]
This issue is to implement [RFC #16: 'PRECONDITION_FAILED' subtest result (status)
](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/assert_precondition.md)

There are at least two parts to this:
- [mozlog needs to support PRECONDITION_FAILED test and subtest status](https://bugzilla.mozilla.org/show_bug.cgi?id=1589056) in mozilla-central
- [Add assert_precondition helper and PRECONDITION_FAILED subtest status](https://github.com/web-platform-tests/wpt/pull/16689) here in wpt

Then there will be many tests that could be updated a few of them included in https://github.com/web-platform-tests/wpt/pull/16689.

**Comment by foolip** [comment]
The wpt side of this change should also update the documentation added in https://github.com/web-platform-tests/wpt/pull/19628.

**Comment by foolip** [comment]
The mozlog changes are up for review in https://phabricator.services.mozilla.com/D50175

**Comment by foolip** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1589056 is now done, and the next step is for @jgraham to release mozlog 5.0.

**Comment by foolip** [comment]
https://pypi.org/project/mozlog/5.0/ is now released, thanks @jgraham!

**Comment by foolip** [comment]
Oops, we're going to get these errors:
```
ERROR: mozrunner 7.6.0 has requirement mozlog~=4.2.0, but you'll have mozlog 5.0 which is incompatible.
ERROR: mozprofile 2.3.0 has requirement mozlog~=4.2.0, but you'll have mozlog 5.0 which is incompatible.
ERROR: mozversion 2.1.0 has requirement mozlog~=4.0, but you'll have mozlog 5.0 which is incompatible.
```

@jgraham how can we resolve this? Do those also need new releases to fix this? Shall I send a mozilla-central patch that bumps the minor version of each?

**Comment by foolip** [comment]
Discussed on IRC. I've sent https://phabricator.services.mozilla.com/D50595.

**Comment by foolip** [comment]
Those three packages now have updated releases. Thanks @jgraham!

**Comment by foolip** [comment]
mozlog itself updated in https://github.com/web-platform-tests/wpt/pull/19884

**Comment by foolip** [comment]
This came up at our [improving interop with WPT](https://drive.google.com/open?id=1MsgJLrBxMtBL1bqC4wPCY2Xf45NM5wU5) talk at https://webkit.org/meeting/ today.

When this is resolved, if there are tests that pass spuriously in WebKit, or that fail when they shouldn't have been run, then `assert_precondition` could be used to allow filtering out those cases in wpt.fyi.

@cdumez @othermaciej @smfr @rniwa do you have specific cases for me to look at? I could try fixing a few of those as part of proving that this all works end-to-end.

**Comment by smfr** [comment]
Any test in ambient-light, battery-status, bluetooth, vibration on Safari.

**Comment by foolip** [comment]
Thanks @smfr, I've included one spurious vibration pass in https://github.com/web-platform-tests/wpt/pull/19993 to show how it works, and *that* it works.
