### ISSUE TITLE
Edge Canary runs failing on installation step

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19878]
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35156 failed all the Edge Canary jobs quickly on the installation step.

The logs say:
```
##[section]Starting: Install Edge Canary
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.151.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\Agent\_work\_temp\a4738d61-a670-40f3-8630-7fbc1d370734.ps1'"
##[error]Failed to install Edge Canary at C:\Users\localuser\AppData\Local\Microsoft\Edge SxS\Application
##[error]At C:\Agent\_work\_temp\a4738d61-a670-40f3-8630-7fbc1d370734.ps1:16 char:3
+   Throw "Failed to install Edge Canary at $edgePath"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to insta...SxS\Application:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to install Edge Canary at C:\Users\localuser\AppData\Local\Microsoft\Edge SxS\App 
   lication

##[error] 

##[error]PowerShell exited with code '1'.
##[section]Finishing: Install Edge Canary
```

**Comment by foolip** [comment]
I've manually triggered https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35171 to try just Edge Canary again. That failed in the same way, so this is probably persistent.

@mustjab since the Edge Canary runs aren't the ones that show up on wpt.fyi by default (should they be?) I don't know what the priority of this should be, but not calling it urgent for now.

**Comment by foolip** [comment]
@stephenmcgruer this is the latest case of me looking at wpt.fyi/runs many times a day where we'd need better monitoring to keep things in shape if I were to look away.

**Comment by foolip** [comment]
Same failure in https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35179, so by now I think we can confidently say this is persistent.

**Comment by mustjab** [comment]
I'm testing a fix to this. The change is in cleanup code, so will require two runs to confirm it:

Run1 (expect failures): https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35216 
Run2 (expect it to pass): https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35218

**Comment by foolip** [comment]
@mustjab it looks like there's now some other problem, with jobs not starting at all. Can you take a look?

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35328
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35341

**Comment by mustjab** [comment]
@foolip Looks like our job to re-create Windows VMs, which we run 3 times a week, failed early this morning and we ended up with no agents in the Windows machine pool.

I'm re-running the VM creation job right now, will let you know when it completes.

**Comment by foolip** [comment]
Thanks @mustjab! If it isn't a quick fix can you file an issue to track it?

**Comment by mustjab** [comment]
New VMs are generated now. The error was due to us changing ownership of the Azure subscription, which led to us not able to delete old set of VMs, so creation of new VMs failed.

**Comment by mustjab** [comment]
The issue is already fixed with an update to our pipeline for creating new VMs. Next scheduled VM refresh is on Wednesday, i'll keep an eye on it to make sure it goes smoothly.

**Comment by foolip** [comment]
Does that mean there won't be any Edge Dev/Canary runs before Wednesday? The Edge Dev runs in particular hold back the wpt.fyi frontpage, so if manually triggering VM creation is possible that'd be great. Sorry if this is a hassle :/

**Comment by mustjab** [comment]
No, all runs should be back to normal now, I've manually triggered the pipeline and we have 25 VMs up and running.

**Comment by foolip** [comment]
@mustjab thank you, that's great!
