### ISSUE TITLE
[WebCryptoAPI] Tests in worker contexts define zero subtests

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#19875]
The tests in the `derive_bits_keys/` subdirectory are defined as ["multi-global" test](https://web-platform-tests.org/writing-tests/testharness.html#multi-global-tests), so they are run in Window and Worker contexts. They use a generative technique to define subtests, but in the Worker context, zero subtests are defined. Because no assertion is made about the number of subtests which should be created, this results in the test being interpreted as a passing ["single page test"](https://web-platform-tests.org/writing-tests/testharness-api.html#single-page-tests). This is evident in [the results published on wpt.fyi](https://wpt.fyi/results/WebCryptoAPI/derive_bits_keys?label=master&label=experimental&aligned).

A change is coming to testharness.js which will change the results for these tests to be a harness error: https://github.com/web-platform-tests/rfcs/pull/28

@jimsch I don't think the current results are desired. If the tests are expected to verify conformance Worker contexts, then they should include an assertion that at least one subtest is generated. If there is no expectation for the behavior under test in Worker contexts, then they should not be expressed as multi-global tests.

Can you let me know if either of those interpretations is correct?

**Comment by jimsch** [comment]
I have not any idea how to go about fixing this, but I believe from what I read in the pointers that the first statement is correct.  The tests are expected to be run in both contexts and they are expected to be independently validated in both.

**Comment by jugglinmike** [comment]
This seems to result from a peculiarity of WPT's "multi-global" feature. The `done` function is invoked immediately from the code generated to run these tests, so the harness reports results before all the subtests have been declared.

There's an ad-hoc solution to correct this test, but the right solution may be to modify the infrastructure instead. I've submitted a patch to correct these tests (gh-19904), a patch to document the harness's behavior (gh-19905), and an issue to discuss changing the harness (gh-19908).

**Comment by foolip** [comment]
@jugglinmike https://github.com/web-platform-tests/wpt/pull/19904 is merged, so I'll close this. https://github.com/web-platform-tests/wpt/issues/19908 is the potential follow-up.

Please reopen if this was not right.
