### ISSUE TITLE
[docs] Rename "testdriver.js Tutorial"

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#19892]
For https://web-platform-tests.org/writing-tests/testdriver-tutorial.html I expected to find a tutorial about how to use testdriver.js, but it's a tutorial about how to extend testdriver.js. This is explained at the top, but maybe the page title could be more specific? "How to extend testdriver.js" ?

cc @gsnedders @jugglinmike @foolip

**Comment by jgraham** [comment]
I think an even more pressing problem is that there isn't a tutorial on how to write a testdriver test. Although extending testdriver is a thing that people may reasonably want to do, you'd have to hope that it's not the common case compared to writing a test. The generated docs don't talk about how to use the `Actions` api at all (unless I'm missing something).

But yes, I agree with the premise of this issue that the title should be changed.

**Comment by foolip** [comment]
@LukeZielinski thoughts?

**Comment by LukeZielinski** [comment]
Renaming sgtm.

@jgraham This talks (albeit briefly) about what testdriver is for, and also mentions the `Actions` api: https://web-platform-tests.org/writing-tests/testdriver.html?highlight=testdriver

Happy to take suggestions for how to expand that doc as well.

**Comment by jgraham** [comment]
Oh right. I saw `action_sequence`— which is something you shouldn't use — in big letters and didn't notice that the text underneath suggested using a different API. I think not mentioning `action_sequence` at all would help or at least just making the docs say something like "this is an internal API; authors are expected to use the Actions builder instead", and have a seperate page or section for the actions builder.

**Comment by LukeZielinski** [comment]
Ahh ok. Cool, I can make these changes.
