### ISSUE TITLE
[css-text] Should word-break property be applied to wrapped line-boxes ?  

### ISSUE THREAD

**Issue by javifernandez** [web-platform-tests/wpt#19903]
Let's consider the following test case (which is extracted from the word-break-break-all-inline-006.html test):

`<div style="font-family: monospace; width: 6.1ch;">aaaa<span stylle=" word-break: break-all;">bbbbbbbbbbb</span>ccccc</div>
`

This DOM implies the generation of 3 inline-boxes, one for each word ('aaaa', 'bbbbbbbbbbb' and 'ccccc'). Before applying the line-breaking rules, all the inline-boxes are contained in a single line-box. 

However, when the text is processed according to the [word breaking rules](https://drafts.csswg.org/css-text-3/#word-break-property) the second inline-box (' bbbbbbbbbbb') is broken, honoring the [break-all](https://drafts.csswg.org/css-text-3/#valdef-word-break-break-all) value, and wrapped to the next two lines.

Since the broken text is now contained into new line-boxes, and considering the original inline-box has its own style, I assume two new inline-boxes are created for these pieces of the broken word. The question is whether these new inline-boxes should have a copy of the style rules of the original inline-box. 

The behavior of the different browsers differ when loading this test case:

<table>
<tr><td>WebKit</td><td>Firefox</td><td>Chrome</td><td>Chrome (legacy)</td></tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/2230241/67608285-da805580-f787-11e9-9f58-f97aead1cb75.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/67608278-d05e5700-f787-11e9-9da4-0ca48e3177ee.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/67608278-d05e5700-f787-11e9-9da4-0ca48e3177ee.png"/></td>
<td><img src="https://user-images.githubusercontent.com/2230241/67608285-da805580-f787-11e9-9f58-f97aead1cb75.png"/></td>
</tr>
</table> 

The expected result currently defined for the [word-break-break-all-inline-006.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/word-break/word-break-break-all-inline-006.html) is the one rendered by WebKit and Chrome, but using the legacy layout engine. 

Both Firefox and Chrome fail when running this test, as it's detected by the wpt.fyi bots:

https://wpt.fyi/results/css/css-text/word-break/word-break-break-all-inline-006.html?label=experimental&label=master&aligned

It's worth mentioning that in all the cases, it seems that 'word-break: break-all' is applied to the text in the first and second lines, since the 'bbbbbbbbbbb' is wrapped in 3 different lines. However, in the case of Firefox and Chrome, the last piece of the broken word is part of another clone of the original inline-box, hence, it has also word-break: break-all rule. This fact is what causes the different behavior, since WebKit and Chrome (legacy) seems to consider this last piece of text as not part of the same line than the following word ('ccccc').

I'm not sure what is the correct behavior in this case. I think WebKit and Chrome (legacy) considers that since word-break: break-all doesn't apply to the whole line ('ccccc' inline-box has not that rule in its own style), the text is not broken despite it overflows. However, Chrome and Firefox consider that, since the last 'bbb' text has a breaking opportunity at the end, honoring word-break: break-all, we can take it and avoid the overflow. 

I appreciate any feedback on this issues.
Thanks in advance.

**Comment by kojiishi** [comment]
I think Gecko and Blink (ng) are correct. We resolved not to define before the last "b" or after, but "c" should not overflow.

**Comment by jfkthame** [comment]
The [spec for `break-all`](https://drafts.csswg.org/css-text-3/#valdef-word-break-break-all) says that:

> Breaking is allowed within “words”: specifically, in addition to soft wrap opportunities allowed for normal, any typographic character units resolving to the NU (“numeric”), AL (“alphabetic”), or SA (“Southeast Asian”) line breaking classes [UAX14] are instead treated as ID (“ideographic characters”) for the purpose of line-breaking.

My interpretation is that in this example, all the _b_'s have the `break-all` value, so the boundary between the last _b_ and the first _c_ is treated as <ID, AL>, and a break is permitted. It's as if the _b_'s were CJK ideographs.

However, there was debate about this, with the alternative view being that the behavior at the element boundary should be determined by the `word-break` value of the nearest common ancestor, and for the time being it has been left undefined in CSS. See discussion in https://github.com/w3c/csswg-drafts/issues/3897.

**Comment by javifernandez** [comment]
I have two questions:

1- What does "undefined" exactly means in this case ? is there or now a breaking opportunity after the last 'b' ? I guess the spec needs some edit to clarify this in any case, as the issue #3897 still has the NeedsEdits label.

2- What part of the spec I should take as reference to implement the "but 'c' should not overflow' part ?

**Comment by jfkthame** [comment]
> I have a few additional questions:
> 
> 1- What does "undefined" exactly means in this case ? is there or now a breaking opportunity after the last 'b' ? I guess the spec needs some edit to clarify this in any case, as the issue #3897 still has the NeedsEdits label.

I believe the spec is currently unclear, as discussed in w3c/csswg-drafts#3897. By my interpretation of `break-all`, there is a break opportunity after the last "b", but by the alternative interpretation some people favored, there isn't; and the most recent CSS WG discussion resolved to leave it undefined for now, per https://github.com/w3c/csswg-drafts/issues/3897#issuecomment-532057510.

> 2- What part of the spec I should take as reference to implement the "but 'c' should not overflow' part ?

https://drafts.csswg.org/css-text-3/#line-breaking says that "the UA must minimize the amount of content overflowing a line by wrapping the line at a soft wrap opportunity, if one exists".

Regardless of the interpretation of `word-break:break-all` at the edge of the span (which determines whether or not there's a break opportunity after the last "b"), there must be an opportunity between the last two "b"s; by taking this break, the overflow would be avoided. So the test (and the Webkit / legacy Chrome rendering) appears to be incorrect, AFAICS.

So the two arguably-correct results, depending on the undefined issue at the boundary, would be either

    aaaabb
    bbbbbb
    bbb
    ccccc

or

    aaaabb
    bbbbbb
    bb
    bccccc

> 3- Is the word-break-break-all-inline-006.html test correctly defined then ?

No, according to my current understanding.

**Comment by frivoal** [comment]
Sorry for staying silent this long on this bug.

I agree with https://github.com/web-platform-tests/wpt/issues/19903#issuecomment-546934290, the two allowed renderings are:

    aaaabb
    bbbbbb
    bbb
    ccccc

and

    aaaabb
    bbbbbb
    bb
    bccccc

The reftest should be modified to allow both, I'll make a PR.

**Comment by frivoal** [comment]
https://github.com/web-platform-tests/wpt/pull/20576 should solve this.

**Comment by javifernandez** [comment]
I agree on closing this issue thanks to #20576
