### ISSUE TITLE
Timeouts with WebKitGTK tests on taskcluster

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt#19961]
Runs with WebKitGTK on taskcluster time out from time to time (Maybe a 40% of the runs).

This is a summary of the last runs with the nightly channel for webkitgtk from branch ```epochs/daily```
* Oct 27 [TC run](https://tools.taskcluster.net/groups/WQvdvH3fRzCXwcFmiMwI3Q) for 2a8f52c037: Timeout in testharness-16
* Oct 26 [TC run](https://tools.taskcluster.net/groups/RdSCO0lKRuCj-J3WWtMh3g) for 5e02df432f: OK
* Oct 25 [TC run](https://tools.taskcluster.net/groups/WNJcxtw3Qomj-Ut1-ef8vQ) for 378214a209: Failure on testharness-1
* Oct 24 [TC run](https://tools.taskcluster.net/groups/GW3pxCk-SCCzRLAP6eTDcQ) for bee8fe0740: Timeout in testharness-16
* Oct 23 [TC run](https://tools.taskcluster.net/groups/BI7czojERwKxip01qk4MKA) for e68120da0f: OK
* Oct 22 [TC run](https://tools.taskcluster.net/groups/GJUbbUR0QzagFis5lKacvg) for 4c52e76f29: OK
* Oct 21 [TC run](https://tools.taskcluster.net/groups/VMFcLpICRjKc7aL3q7PWlA) for fee6738f95: Timeout in testharness-16
* Oct 20 [TC run](https://tools.taskcluster.net/groups/MTcwFpndQ4mO7ukm8WA5Nw) for 02fae42fbd: Timeout in testharness-16
* Oct 19 [TC run](https://tools.taskcluster.net/groups/EIR-p9pMTvOKAt7fPni-5w) for 4e9c00e23f: Failure on testharness-1
* Oct 18 [TC run](https://tools.taskcluster.net/groups/V0ydT7rURme2XilJfb1JTQ) for 42b683c0fa: Timeout in testharness-16
* Oct 17 [TC run](https://tools.taskcluster.net/groups/JKkvpeI9R6m0uFx8h6FXQw) for 96e065ccc5: Timeout in testharness-16
* Oct 16 [TC run](https://tools.taskcluster.net/groups/U--_OUjrSISXP9l9KvyniQ) for 1a58533866: OK

//cc @foolip @jgraham

**Comment by clopez** [comment]
After landing the match logger in #19814 that adds timestamps I can see that its timing out  because the whole step is taking too long, but not because some specific test hangs.

For example, let's analyze the first two logs for testharness-16:

``` 
$ wget --compression=auto https://queue.taskcluster.net/v1/task/V5LZI2nRQR2n16NspOmwoA/runs/0/artifacts/public/logs/live_backing.log -O 2a8f52c037_wpt-webkitgtk_minibrowser-nightly-testharness-16.log

$ wget --compression=auto https://queue.taskcluster.net/v1/task/cTjKhqHjS1yaTYv-LP58zw/runs/0/artifacts/public/logs/live_backing.log -O 5e02df4_wpt-webkitgtk_minibrowser-nightly-testharness-16.log

$ tail -2 2a8f52c037_wpt-webkitgtk_minibrowser-nightly-testharness-16.log 
[taskcluster 2019-10-28 02:04:14.319Z] === Task Finished ===
[taskcluster 2019-10-28 02:04:14.320Z] Unsuccessful task run with exit code: -1 completed in 7237.054 seconds

$ tail -2 5e02df4_wpt-webkitgtk_minibrowser-nightly-testharness-16.log 
[taskcluster 2019-10-27 02:01:55.100Z] === Task Finished ===
[taskcluster 2019-10-27 02:01:56.713Z] Successful task run with exit code: 0 completed in 7115.816 seconds
```

The first one failed due to timeout, and the second one finished OK, but with a very small margin (7115 seconds vs 7200 timeout)

To dig further into this I have created a [python script to analyze the logs and better understand](https://people.igalia.com/clopez/wptbug/19961/analize_times_wpt_mach_log.py) where the bulk of the time comes from, and I think the root cause of this timeouts are the ```encoding/legacy-mb-korean/euc-kr``` tests that take too much with WebKitGTK.


```
$ python analize_times_wpt_mach_log.py 5e02df4_wpt-webkitgtk_minibrowser-nightly-testharness-16.log 
The total time was of 6356.7 seconds (1.77 hours), with a total of 1710 tests ran

$ python analize_times_wpt_mach_log.py --filter-test-name-include-string=encoding/legacy-mb-korean/euc-kr 5e02df4_wpt-webkitgtk_minibrowser-nightly-testharness-16.log 
The total time was of 4125.5 seconds (1.15 hours), with a total of 418 tests ran

$ python analize_times_wpt_mach_log.py --filter-test-name-exclude-string=encoding/legacy-mb-korean/euc-kr 5e02df4_wpt-webkitgtk_minibrowser-nightly-testharness-16.log 
The total time was of 2231.2 seconds (0.62 hours), with a total of 1292 tests ran
```

So, basically WebKitGTK is spending:

 * 1.77 hours in running all the tests from `testharness-16`. From which:
   * 1.15 hours is in running the tests from `testharness-16` that contain the string ```encoding/legacy-mb-korean/euc-kr``` in the test name
   * 0.62 hours is in running all the other tests from `testharness-16` (those that don't contain the string ```encoding/legacy-mb-korean/euc-kr``` in the test name)
 

1.15 hours for running the tests from ```encoding/legacy-mb-korean/euc-kr``` is too much.
Chrome and Firefox run those ```encoding/legacy-mb-korean/euc-kr``` tests in less than 15 minutes.

```
$ python  analize_times_wpt_mach_log.py --filter-test-name-include-string=encoding/legacy-mb-korean/euc-kr chrome-testharness-16.log 
The total time was of 854.7 seconds (0.24 hours), with a total of 418 tests ran

$ python  analize_times_wpt_mach_log.py --filter-test-name-include-string=encoding/legacy-mb-korean/euc-kr firefox-testharness-16.log 
The total time was of 680.9 seconds (0.19 hours), with a total of 418 tests ran
```

**Comment by clopez** [comment]
I have opened https://bugs.webkit.org/show_bug.cgi?id=203544 on the WebKit side to track and fix this issue

**Comment by foolip** [comment]
Great find! Those tests have a huge number of subtests, so that may have something to do with it..

**Comment by foolip** [comment]
@clopez this is persistent, right? Is there no workaround that'd give us results back? @smfr was asking today at https://webkit.org/meeting/ how often WebKitGTK is run, and I had to admit there's a problem right now. But target is daily WebKitGTK experimental and weekly WebKitGTK stable. (STP runs 8 times a day, and Safari stable runs daily.)

**Comment by clopez** [comment]
This has been consistently timing out, but I hope it will get better now that https://bugs.webkit.org/show_bug.cgi?id=203544 have been fixed. If it doesn't get better I'm afraid I will ask just for raising the taskcluster timeout value. Let's wait a few days to see how it behaves now that it has landed.

**Comment by gsnedders** [comment]
@clopez does this look better now?

**Comment by foolip** [comment]
@clopez is out for a few weeks. @psaavedra who should we poke instead?

**Comment by psaavedra** [comment]
Sorry for the delay in the reply. I didn't see the message until few moments ago. I think those issues was related with timeouts triggered by  the WebDriver for WebKitGTK and related with what  @carlosgcampos was working on  during the last week:

* https://bugs.webkit.org/show_bug.cgi?id=204503  (landed)

Basically, he switched the remote inspector to plain sockets because  the current implementation with  DBus was too much slow

**Comment by carlosgcampos** [comment]
I think this was about the system fonts fallbacks, which already landed. The WebDriver switch to plain sockets will help too for sure. WebDriver tests with many subtests that were timing out before should be super fast now.

**Comment by clopez** [comment]
I think this is fixed now. Runs of WebKitGTK are [happening on a daily basis](https://wpt.fyi/runs?label=master&max-count=100&product=webkitgtk) without more timeout issues
