### ISSUE TITLE
Edge Dev runs failing due to MSEdgeDriver/MSEdge version mismatch

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#19975]
The Edge Dev runs have been failing persistently for ~24h, starting just as https://github.com/web-platform-tests/wpt/issues/19878 was resolved and possibly related to the fix for that, which included https://github.com/web-platform-tests/wpt/pull/19898 and [regenerating the VMs](https://github.com/web-platform-tests/wpt/issues/19878#issuecomment-547130813).

Failures so far from oldest to newest:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35341 (2 jobs failed)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35364 (10 jobs failed)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35372 (3 jobs failed)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35382 (4 jobs failed)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35389 (4 jobs failed)
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=35398 (3 jobs failed)

The failure mode appears to be new:
```
 0:33.69 WARNING Failed to start protocol connection
 0:33.69 WARNING Traceback (most recent call last):
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\protocol.py", line 48, in setup
    self.connect()
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 230, in connect
    self.webdriver.start()
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 429, in start
    value = self.send_command("POST", "session", body=body)
  File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 480, in send_command
    raise err
SessionNotCreatedException: session not created (500): session not created: This version of MSEdgeDriver only supports MSEdge version 80

Remote-end stacktrace:

Backtrace:
	Ordinal0 [0x01381F43+1580867]
	Ordinal0 [0x013028D1+1059025]
	Ordinal0 [0x012809F5+526837]
	Ordinal0 [0x01211515+70933]
	Ordinal0 [0x0120E619+58905]
	Ordinal0 [0x0120BCCD+48333]
	Ordinal0 [0x0122D087+184455]
	Ordinal0 [0x0122CE8D+183949]
	Ordinal0 [0x0122AEEB+175851]
	Ordinal0 [0x01212F3A+77626]
	Ordinal0 [0x01213FB0+81840]
	Ordinal0 [0x01213F49+81737]
	Ordinal0 [0x0131C757+1165143]
	GetHandleVerifier [0x01419776+503942]
	GetHandleVerifier [0x01419494+503204]
	GetHandleVerifier [0x01420B77+533639]
	GetHandleVerifier [0x0141A032+506178]
	Ordinal0 [0x0131438C+1131404]
	Ordinal0 [0x0131E92B+1173803]
	Ordinal0 [0x0131EA93+1174163]
	Ordinal0 [0x0131D995+1169813]
	BaseThreadInitThunk [0x76270419+25]
	RtlGetAppContainerNamedObjectPath [0x7734662D+237]
	RtlGetAppContainerNamedObjectPath [0x773465FD+189]
```

This happens over and over until "Max restarts exceeded". The key bit seems to be "This version of MSEdgeDriver only supports MSEdge version 80".

@mustjab can you take a look? I've labeled this as urgent because it holds back the wpt.fyi frontpage, which is now stuck at https://github.com/web-platform-tests/wpt/commit/cbd8c8ca92, from Mon Oct 28 08:39:49 2019 UTC.

@stephenmcgruer FYI another thing that monitoring should catch early.

**Comment by mustjab** [comment]
Looks like our Canary runs downloaded WebDriver binary v80 and subsequent runs on the same machine for Dev channel, which is still at v79, are failing. We'll need to add removal of msedgedriver.exe to our cleanup script.

**Comment by foolip** [comment]
Ah, that makes sense. So much to clean up :)

**Comment by stephenmcgruer** [comment]
Ah excellent, this lets me test a theory. https://ecosystem-infra-rotation.appspot.com/ has a section for wpt.fyi stable runs (and experimental), but I can see atm that it is green. Looks like it doesn't check for Edge, that should be a reasonably straight-forward fix.

Which is still not automated alerting; that's still on my further-out radar

**Comment by foolip** [comment]
@mustjab https://wpt.fyi/runs has recovered now, did you do something or was it the weekly VM refresh that got things back on track?

**Comment by mustjab** [comment]
Yes, I've re-created VMs and also ran my change to cleanup Edge driver binaries (PR: https://github.com/web-platform-tests/wpt/pull/20023).

**Comment by foolip** [comment]
Edge Dev runs in https://wpt.fyi/runs have recovered, so I'll close this issue now. Thanks @mustjab!
