### ISSUE TITLE
[docs] published docs require horizontal scrolling on mobile

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#20014]
Attempting to read through https://web-platform-tests.org/writing-tests/making-a-testing-plan.html on a Pixel 3 is hard because the page is just a little bit wider than the viewport, requiring scrolling. Scrolled to the rightmost edge in this screenshot to demonstrate:

![Screenshot_20191031-065409](https://user-images.githubusercontent.com/498917/67922538-48bf8080-fbab-11e9-96af-ee6e843be772.png)

@jugglinmike

**Comment by frehner** [comment]
this looks like it's an issue with the default theme being used. https://github.com/bitprophet/alabaster/issues/139

the fix appears to be simple - 

```css
div.body {
    min-width: auto;
    max-width: auto;
}
```

are you ok with me adding that inside a `custom.css` file in the `/docs/assets/` folder?

**Comment by stephenmcgruer** [comment]
@frehner I am far from a web developer, but assuming that it doesn't affect rendering on wider screens that seems fine to me, and I would happy review such a patch, thanks! :)

**Comment by frehner** [comment]
PR created! Added an additional selector to help prevent the video from being wider than 100%.

**Comment by frehner** [comment]
actually, I just realized that I solved the horizontal scrolling on the homepage, but not on the actual page that is linked in the original issue. 

I'll look into fixing that as well.
