### ISSUE TITLE
css/css-animations/keyframes-remove-documentElement-crash.html causes a harness failure

### ISSUE THREAD

**Issue by graouts** [web-platform-tests/wpt#20020]
The test at [css/css-animations/keyframes-remove-documentElement-crash.html](http://web-platform-tests.live/css/css-animations/keyframes-remove-documentElement-crash.html) causes a harness failure because it removes the `<body>` element:

```
[Error] TypeError: null is not an object (evaluating 'root.appendChild')
	(anonymous function) (testharness.js:2987)
	(anonymous function) (testharness.js:3026)
	(anonymous function) (testharness.js:196)
	(anonymous function) (testharness.js:2776)
	forEach (testharness.js:3489)
	(anonymous function) (testharness.js:2773)
	all_complete (testharness.js:2643)
	(anonymous function) (testharness.js:2655)
	(anonymous function) (testharness.js:2446)
```

I'm not sure what the right way would be to address this given the test design. It does seem somewhat arbitrary that this test exists in the WPT suite though.

Tagging the author of the test @lilles, its reviewer @mstensho, other Blink developers working on Web Animations @stephenmcgruer @flackr and all-around knowledgeable person @birtles.

**Comment by stephenmcgruer** [comment]
Interestingly, it seems to work ok under `wpt run` (I presume, based on https://wpt.fyi/results/css/css-animations/keyframes-remove-documentElement-crash.html?label=master&label=experimental&aligned&q=css%2Fcss-animations%2Fkeyframes-remove-documentelement-crash.html).

I think it's worth taking a quick look at it from the infra side, to understand what the difference is there.

In terms of whether the test 'belongs' in WPT, we've historically chosen to accept tests like this as they test valid spec behavior without being browser specific. That is, any implementation which failed this test would be against spec.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/rfcs/pull/33 is adding proper support for crash tests in WPT and then this could probably be rewritten to not use testharness.js and thus avoid the problem entirely.

There are differences between `./wpt run` and navigating to a test on wpt.live, but exactly what the relevant difference is here I don't know.
