### ISSUE TITLE
`./wpt` commands won't work on Fedora which has no `python` binary

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#20035]
In https://github.com/web-platform-tests/wpt/pull/19940#discussion_r341174482, it became clear that the documentation we have wouldn't work for Fedora, and to get `./wpt run` working would require having `python` on the path, which apparently no Fedora package provides.

@clopez wrote:

> I have tested this on a docker image of fedora31 and unfortunately that is not enough.
> Issues:
>   * `/usr/bin/python` doesn't exist anymore on fedora. Possible workarounds:
>     * Tell the user to create the symlink with: ```sudo ln -s /usr/bin/python2 /usr/bin/python```
>     * We update the shebangs on all the python scripts in the wpt repository to use `/usr/bin/python2` or `/usr/bin/python2.7` instead of `/usr/bin/python`. I think is maybe better `/usr/bin/python2.7` because IIRC some versions of Mac (previous to Catalina) didn't had a ```python2``` symlink/binary, but they had a ```python2.7``` one
>   * The package python2-virtualenv doesn't exist anymore.  Possible workaround:
>      * Tell the user to install it via pip with ```pip2 install virtualenv```
> 
> So the instructions would be:
> 
> ```
> sudo dnf install python2 python2-pip
> sudo ln -s /usr/bin/python2 /usr/bin/python
> pip2 install virtualenv
> ```
> 
> However, I don't like the idea of telling the user to create a symlink in `/usr/bin`. Maybe we should consider changing the shebangs on our python scripts. I tested to change it only on the main one (`./wpt`) and it seems to work:
> ```diff
> diff --git a/wpt b/wpt
> index a24bc83a91..bc9924a9e0 100755
> --- a/wpt
> +++ b/wpt
> @@ -1,4 +1,4 @@
> -#!/usr/bin/env python
> +#!/usr/bin/env python2.7
>  
>  if __name__ == "__main__":
>      from tools.wpt import wpt
> ```
> 
> BTW, is there any plan to migrate the codebase to python3?

Python 3 is tracked by https://github.com/web-platform-tests/wpt/issues/8820.

**Comment by rakuco** [comment]
@clopez is this still valid for you? Fedora provides a `python-unversioned-command` that ships a `python` symlink to `python3`. I've been running `wpt` here on Fedora with no issues related to this.

**Comment by clopez** [comment]
Its not an issue for me anymore.
However, perhaps is worth documenting that package on the wpt docs ( docs/running-tests/from-local-system.md ) and recommend to install it on fedora.
