### ISSUE TITLE
Enable more features in STP

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#20057]
https://github.com/web-platform-tests/wpt/blob/ac527a6087fc4c16a81ab001470d9e4e114c94b9/tools/ci/azure/install_safari.yml#L11

@smfr what addition things should we enable here?

**Comment by stephenmcgruer** [comment]
Marking priority roadmap based on our current focus of getting useful, reliable data for Safari - and part of that is knowing the 'correct' set of flags to turn on for Safari TP.

**Comment by stephenmcgruer** [comment]
I think without evidence that there are more preferences we should turn on here (which we haven't got), 6 months later is a reasonable time to close this.

Of course we'd still love to hear if there are preferences we are missing, and would be happy to turn them on :).
