### ISSUE TITLE
Remove reftest.list files?

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt#20060]
I think reftest.list files are a [vestige of Mozilla imports](https://developer.mozilla.org/en-US/docs/Mozilla/QA/web-platform-tests#Metadata) and aren't used any more. Should they be removed to avoid confusion?

wpt % find . -name reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/background/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/color4/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/text3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/filters/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/contain/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/will-change/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/selectors4/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/align3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/ui3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/values3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/ib-split/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/text-decor-3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/writing-modes-3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/sizing/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/conditional3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/break3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/flexbox/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/css21/replaced-sizing/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/css21/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/counter-styles-3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/transforms/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/variables/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/shapes1/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/images3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/fonts3/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/ruby/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/masking/reftest.list
./css/vendor-imports/mozilla/mozilla-central-reftests/multicol3/reftest.list
./css/css-backgrounds/background-attachment-local/reftest.list
./css/css-backgrounds/background-size/vector/empty/reftest.list
./css/css-backgrounds/background-size/vector/reftest.list

**Comment by jgraham** [comment]
There is a plan to remove the vendor-imports directory but it would help not to make other changes to it in the interim. AFAIK it's OK to remove the other `reftest.list` files.

**Comment by foolip** [comment]
I closed this with https://github.com/web-platform-tests/wpt/pull/20066, but @jgraham is there an issue that @smfr can follow about vendor-imports being merged into wpt proper?
