### ISSUE TITLE
Some tests for define() in CustomElementRegistry.html doesn't match spec

### ISSUE THREAD

**Issue by EdgarChen** [web-platform-tests/wpt#20091]
Like,

https://github.com/web-platform-tests/wpt/blob/fee4534917ef1f0a38706a9975c0348088edb2c4/custom-elements/CustomElementRegistry.html#L220-L230

Test expects only "prototype" property is getting from constructor, but according to the spec,

https://html.spec.whatwg.org/multipage/custom-elements.html#dom-customelementregistry-define
> 14.7 Let disabledFeaturesIterable be Get(constructor, "disabledFeatures"). Rethrow any exceptions.

> 14.11 Let formAssociatedValue be Get( constructor, "formAssociated"). Rethrow any exceptions.

"disabledFeatures" and "formAssociated" are also from the constructor.

Or spec meant to get them from the prototype, like callbacks?

@annevk @domenic @rniwa

**Comment by domenic** [comment]
These tests were likely not updated when those new features were added. Updating them would be great.

**Comment by EdgarChen** [comment]
I will send a PR to udpate the tests. Thanks.
