### ISSUE TITLE
Chrome crashes on Community-TC

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#20133]
We started Taskcluster migration (https://bugzilla.mozilla.org/show_bug.cgi?id=1574668) and now we are seeing widespread Chrome crashes on the new Community-TC instance.

Example: https://community-tc.services.mozilla.com/tasks/aMcaEBP4RIKa_EbrE30xJw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FaMcaEBP4RIKa_EbrE30xJw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L550

This [PR](https://github.com/web-platform-tests/wpt/pull/19570) has both Taskcluster and Community-TC jobs. Note that the crash only happens on Community-TC. After checking a few other jobs, it seems the crash is widespread on Community-TC.

**Comment by Hexcles** [comment]
cc @jgraham

**Comment by Hexcles** [comment]
We are *certain* that Chrome is failing to start in Docker:
> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted

which is a rather common problem, c.f. [Puppeteer troubleshooting doc](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker).

We have a few **workarounds on the Docker side** as seen [here](https://forums.docker.com/t/dockerizing-chrome-security-questions/45614):
> Run the container with: --privileged
> Run with: --cap-add SYS_ADMIN
> Run with: --security-opt seccomp:unconfined
> Run with: --security-opt seccomp:[chrome.json](https://github.com/jessfraz/dotfiles/blob/master/etc/docker/seccomp/chrome.json)

Our understanding is that they have increasing security levels. The first one is easy to do on Community-TC, but particularly bad security-wise, because it gives Docker containers RW access to `/sys` and `/dev` on the host, allowing a container to pollute the host easily (e.g. using `sysctl` or `dd` to `/dev`). The hosts are NOT reset between tests on Taskcluster. A good long-term solution is to use a custom seccomp profile, which may require building our own worker image as it is not configurable otherwise, and currently there is no self served way to build a worker image.

Alternatively, we could **disable Chrome sandboxing**. This is in fact better security-wise: we have password-less sudo inside Docker, so anyone can get root in a PR already. By disabling Chrome sandboxing, we are not loosening the container isolation at all, so we are not opening up new vulnerabilities. However, it is unclear whether it'd affect web-observable behaviours (I'm checking with the Chrome team). If not, I think this might be the best tradeoff.

**Comment by Hexcles** [comment]
None of the aforementioned workarounds were used previously. We are not sure why it used to work, but have a theory that a different sandboxing mechanism was used because of old kernel version.

On the old taskcluster.net instance, github-worker runs a 14.04-based image. According to [Chromium docs](https://chromium.googlesource.com/chromium/src.git/+/master/docs/linux_sandboxing.md#sandbox-types-summary), user namespace sandbox is only used on kernel >= 3.8. Yet 14.04 shipped 3.13, so we are not sure...

**Comment by Hexcles** [comment]
We have two immediate fix candidates:

* https://github.com/web-platform-tests/wpt/pull/20134 turn on priviledged mode
* https://github.com/web-platform-tests/wpt/pull/20136 disable Chrome sandboxing

**Comment by stephenmcgruer** [comment]
We believe that bc83451 should resolve this, by disabling the Chrome sandbox when running under the new taskcluster instances. Long term, we should investigate adding support to TaskCluster for custom seccomp profiles, but hopefully this puts out the fire for now.

🔥 <-- 🚒
