### ISSUE TITLE
TaskCluster has a big queue and its slowing down processing the checks on pull requests

### ISSUE THREAD

**Issue by clopez** [web-platform-tests/wpt#20256]
This issue comes from: https://github.com/web-platform-tests/wpt/pull/20232#issuecomment-553491703

Since the move to the new community taskcluster it has been observed that it has a bigger queue and that processing pull-requests takes more time than desired.

A possible solution to this is to give more [priority on taskcluster](https://community-tc.services.mozilla.com/docs/manual/tasks/priority) to the jobs related to pull-requests, so those are processed first than then the ones related to pushes on branches.

Right now, the queue is of 286. Check https://community-tc.services.mozilla.com/worker-manager (at the bottom where it says ```proj-wpt/ci``` the number of pending jobs)

//cc @foolip @jgraham

**Comment by clopez** [comment]
@jgraham I'm assigning this to you by request of @foolip.

**Comment by jgraham** [comment]
@djmitche Is reduced capacity an expected effect of the transition? Is there some way to quantify it (obviously we could try to use historical timings from the tasks themselves, but maybe there's something easier)?

**Comment by djmitche** [comment]
Is the issue that jobs are taking longer, or that there are fewer works?

**Comment by foolip** [comment]
What we observe is that it takes longer for tasks to start, which might be because there are fewer workers overall, a limit on the number of parallel tasks, or something like that.

**Comment by djmitche** [comment]
An easy fix might be to increase the [number of workers](https://github.com/mozilla/community-tc-config/blob/master/config/projects.yml#L433).  A good indication of that would be seeing 40 running workers simultaneously

**Comment by clopez** [comment]
> An easy fix might be to increase the [number of workers](https://github.com/mozilla/community-tc-config/blob/master/config/projects.yml#L433). A good indication of that would be seeing 40 running workers simultaneously

How that can be seen? If you go to https://community-tc.services.mozilla.com/provisioners/proj-wpt/worker-types/ci and you click on sort worker by "task state", it only sorts the current page.. you have to go through all the pages to see the ones running...  and there are many pages.

**Comment by djmitche** [comment]
Yeah, it's pretty bad, sorry.  We're working on that :)

Here's a short script that can list all of the workers via the API.  This can be tweaked or its output filtered through `jq` to find the running workers.

```python
import json
import sys
import os
import urllib.request


def main():
    # rootUrl = os.environ["TASKCLUSTER_ROOT_URL"]
    workerPoolId = sys.argv[1]
    # apiUrl = rootUrl + "/api/worker-manager/v1/workers/" + workerPoolId
    apiUrl = "https://worker-manager.taskcluster.net/v1/workers/" + workerPoolId
    continuationToken = None

    while True:
        url = apiUrl + "?limit=100"
        if continuationToken:
            url += "&continuationToken={}".format(continuationToken)
        with urllib.request.urlopen(url) as res:
            data = json.loads(res.read())
            for worker in data["workers"]:
                print(json.dumps(worker, sort_keys=True, indent=4))
            if "continuationToken" in data:
                continuationToken = data["continuationToken"]
            else:
                break


main()
```

**Comment by clopez** [comment]
Nice!
```
$ python3 x.py proj-wpt/ci|grep "state.*running"|wc -l
40
```
It seems its full

**Comment by djmitche** [comment]
Cool -- want to make a PR to bump that to, say, 80?

**Comment by clopez** [comment]
I prefer to leave that to @jgraham 
I don't know the implications (on resources spent/etc) of raising the number of works

**Comment by djmitche** [comment]
Sounds good.

**Comment by foolip** [comment]
The maximum number of parallel builds we have should be the weekly runs, when if there was also just a commit to master we’d have 3 Chrome channels, 3 Firefox channels and 2 WebKitGTK channels running. With 22 tasks per build (task group) that’s... 176.

To also be able to keep testing PRs at the same time we’d need at least 180.

**Comment by jgraham** [comment]
So the question is how the capacity compares to the previous capacity — which I think we agree was fine — not what's the theoretical maximum we might use. I don't remember if the old setup had a limit other than the global limits applying to Firefox CI.

In any case I'm happy to make a PR to raise the maximum capacity to 80.

**Comment by jgraham** [comment]
There are a few other things that will help here:
* Finish the decision task work so we are using the workers more efficiently (not spinning up workers for jobs that won't run)
* Ensure that periodic runs are scheduled for times when there aren't many PRs i.e. weekends

**Comment by foolip** [comment]
The peak demand is at UTC midnight between Sunday and Monday, at which time there might be some people who are getting to work in APAC, but I'd guess is probably still a pretty good time. If we have trouble we could look at some stats for when during the weekend PR activity is at its lowest and pick that time.

**Comment by foolip** [comment]
At every UTC midnight there will be 3 parallel builds in addition to whatever was triggered by master commits, so 80 will probably make the queuing time acceptable.

However, if we want to budget the peak usage (as opposed to total usage as before) then we should probably run Taskcluster on a schedule as well to not trigger lots of runs when many PRs are quickly. This can happen when Chromium's exporter recovers from a failure, or when I review and land a lot of @autofoolip PRs at once.

**Comment by jgraham** [comment]
One idea I had, which is a little engineering work, but possible, is to make the epoch builds run in series rather than in parallel; you'd set things up so that the Firefox jobs would depend on the Chrome jobs and the WebKit jobs would depend on the Firefox jobs (and the dependency would be just that they had run, not that they had succeeded). So there are a bunch of options here, just need to work out how much of a problem we have and how best to address it.

**Comment by djmitche** [comment]
Some thoughts based on my experience:
* Things tend to "just work out" and within an order of approximation you (well, Mozilla) are paying for the time the tasks take, whether in parallel or series.
* Workers are started dynamically, so a maxCapacity is really just a limit on total dollars per minute spent.  If your load is spiky, it's fine to have a maxCapacity that suits the spikes (say 80%), and just run fewer workers at other times.
* Usually the most important metric (and the one at the beginning of this thread) is end-to-end time.  That includes both time waiting for tasks to find a worker, but also time waiting for things that run in series or depend on one another.  So for example serializing builds will increase your E2E while not substantially decreasing the total cost.
* Priorities can help: make the tasks where someone is waiting for results (PRs?) higher priority than the tasks that are providing long-term results (scheduled jobs?).
* Don't over-think this. :)

**Comment by jgraham** [comment]
I had fully forgotten about the priority field. Yes, we should definitely arrange things so that the priority of PR jobs is higher than master runs is higher than epoch runs, or something like that (maybe master and epoch should be the same).

**Comment by Hexcles** [comment]
> Finish the decision task work so we are using the workers more efficiently (not spinning up workers for jobs that won't run)

BTW, do we have an issue tracking this?

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/19401 was just merged, so no tracking required :)

Giving higher priority to PR tasks would be great though. @jgraham can you do a thing?

**Comment by LukeZielinski** [comment]
Periodic checkin: glancing at https://community-tc.services.mozilla.com/worker-manager I see ~40 pending tasks for `proj-wpt/ci` which seems reasonable. This issue (as stated) seems resolved, but maybe we can carve off a new backlog issue for setting task priority?

**Comment by Hexcles** [comment]
I remember we reached out to TaskCluster. I forget whether we determined it was a one-off hiccup or added more resources to the pool, but the backlog was indeed resolved.
