### ISSUE TITLE
[css-values] min() and max() tests don't follow the spec unit ordering

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt#20287]
css/css-values/minmax-length-percent-serialize.html has, for example:

``
test_valid_length_percent('min(1px + 1%)', 'min(1px + 1%)');
``

https://drafts.csswg.org/css-values-4/#sort-a-calculations-children says that units are sorted with % before lengths, so the output should be ``min(1% + 1px)``

**Comment by smfr** [comment]
@xiaochengh

**Comment by xiaochengh** [comment]
The test expectation has been fixed. We can close the issue now.

**Comment by stephenmcgruer** [comment]
Closing based on https://github.com/web-platform-tests/wpt/issues/20287#issuecomment-555852138; @smfr please re-open if you think it's still wrong.
