### ISSUE TITLE
[infra] Getting errors related to epochs workflow on my personal fork

### ISSUE THREAD

**Issue by mrego** [web-platform-tests/wpt#20392]
This week I updated my WPT fork with the usual commands:
```
$ git fetch upstream
$ git merge upstream/master
$ git push origin master
```

Since then I'm getting notifications via mail with subject `[mrego/wpt] Run failed: epochs - master (8e98be7)` every 3 hours more or less.
They point to things like https://github.com/mrego/wpt/runs/315387152

It seems that workflow was added somehow recently (see #19873), but I don't get why it's running on my personal fork, or why I'm getting this errors. Any help is appreciated. Thanks!

CC @Ms2ger @foolip

**Comment by Hexcles** [comment]
Looks like the epoch update action isn't behind a flag checking the main repo. This is indeed very annoying for people forking the repo (we have 1.8k forks FWIW).

**Comment by mrego** [comment]
I'm still getting this kind of errors: https://github.com/mrego/wpt/commit/3f54787efedc027ed449961173ffd572d79de46e/checks

Do I need to do anything special on my fork? Thanks.

**Comment by foolip** [comment]
@mrego you'll need to rebase as well if your branch was started before the problem was fixed on wpt master, which it looks like it was.

**Comment by mrego** [comment]
I rebased the master branch on my fork, but I'm still getting the mails with the errors, this is very weird so probably I'll kill my fork and create it again. :-)

The mails I get look like this:
> **[mrego/wpt] Run failed: manifest - master (ff11f93)**
>
> Run failed for master (ff11f93)
>
>Repository: mrego/wpt
>Workflow: manifest
>Duration: 3.0 seconds
>Finished: 2019-12-02 09:00:56 UTC
>
> [View results](https://github.com/mrego/wpt/commit/ff11f93316527e37ec580adca01a9cf0a58a297e/checks)
> Jobs:

> **[mrego/wpt] Run failed: epochs - master (ff11f93)**
>
> Run failed for master (ff11f93)
>
> Repository: mrego/wpt
> Workflow: epochs
> Duration: 3.0 seconds
> Finished: 2019-12-02 09:11:24 UTC
>
> [View results](https://github.com/mrego/wpt/commit/ff11f93316527e37ec580adca01a9cf0a58a297e/checks)
> Jobs:

The *View results* link they point too doesn't show any error.
