### ISSUE TITLE
Missing Chrome and Firefox stable wpt.fyi runs

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#20551]
The latest wpt.fyi run that included Safari, Chrome and Firefox is [1df8c00](https://wpt.fyi/results?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&sha=1df8c00a83).

Since then, there have been [20bb1ca](https://wpt.fyi/results?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&sha=20bb1ca5db), [5df56b2](https://wpt.fyi/results?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&sha=5df56b25e1), and [9c100c3](https://wpt.fyi/results?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&sha=9c100c3900), all of which contain only Safari runs.

**Comment by stephenmcgruer** [comment]
These should be triggered from `refs/heads/epochs/daily` I believe; I suspect the decision task graph work broke this.

**Comment by stephenmcgruer** [comment]
Hrm, I am somewhat confused. If we go [back to November 26th](https://github.com/web-platform-tests/wpt/commits/epochs/daily?after=9c100c390010017d95b2295c1b126f4378171b14+69), we can see a commit ([5454021b](https://github.com/web-platform-tests/wpt/commit/5454021b2ea6f85014606a2178a8fd26f1fa5f40)) which ran a [taskcluster push](https://community-tc.services.mozilla.com/tasks/groups/FE3nWU7hSEKXhSTNWG3fbA), where picking any [individual task](https://community-tc.services.mozilla.com/tasks/KtKZ3L46Sja6A0o2jQSpHw) shows it has `\"ref\":\"refs/heads/epochs/daily\"`.

But if we look at November 30th, we find that epochs was [pushed to 5df56b25e1](https://github.com/web-platform-tests/wpt/commit/5df56b25e1cb81f81fe16c88be839f9fd538b41e/checks?check_suite_id=336091754), but looking at [that commits page](https://github.com/web-platform-tests/wpt/commits/epochs/daily) and grabbing the [Taskcluster push linked there](https://community-tc.services.mozilla.com/tasks/groups/JTizX0kISmSsMqiqrAiElg), and looking at the ref there of some random task we get `\"ref\": \"refs/heads/master\"`.

So Taskcluster didn't trigger for epochs? I'm looking at the new `.taskcluster.yml` atm, trying to understand how that might have happened (but could be red herring?)

**Comment by stephenmcgruer** [comment]
I just pushed to `triggers/chrome_stable` to see what would happen. Monitoring https://github.com/web-platform-tests/wpt/commits/triggers/chrome_stable; I would expect to see a TC run happen for `refs/heads/triggers/chrome_stable`.

**Comment by stephenmcgruer** [comment]
As far as I can tell, nothing happened. https://github.com/web-platform-tests/wpt/commits/triggers/chrome_stable shows a bunch of Azure Pipeline runs going (which I think are from the actual master commit), but the TaskCluster run that [is listed](https://community-tc.services.mozilla.com/tasks/groups/Br3MDJ3BTE6AsggT_WGexw) is also old and appears to be for `refs/head/master`.

**Comment by stephenmcgruer** [comment]
Pushing `triggers/firefox_nightly` to see.

**Comment by stephenmcgruer** [comment]
Firefox nightly works?!

https://github.com/web-platform-tests/wpt/commits/triggers/firefox_nightly shows https://community-tc.services.mozilla.com/tasks/ZGai_M8ZSxa9T3k3AQJBRg which has a ref of `refs/heads/triggers/firefox_nightly` ...

**Comment by stephenmcgruer** [comment]
This is interesting. If we look at the commit for 5df56b25e1, it has an error [in a comment](https://github.com/web-platform-tests/wpt/commit/5df56b25e1cb81f81fe16c88be839f9fd538b41e/#commitcomment-36206673) at 7:36pm EST November 30th. That is the same time as the [action that pushed that sha to the epoch branches](https://github.com/web-platform-tests/wpt/commit/5df56b25e1cb81f81fe16c88be839f9fd538b41e/checks?check_suite_id=336091754) happened. 

Again it [happens again](https://github.com/web-platform-tests/wpt/commit/9c100c390010017d95b2295c1b126f4378171b14#commitcomment-36213783) for 9c100c3, again matching the epoch action timestamp.

**Comment by stephenmcgruer** [comment]
I managed to find a log of the events github has sent, by looking at the dispatched events for [one of our webhooks](https://github.com/web-platform-tests/wpt/settings/hooks/33233499) (that only listens to pushes).

`event.sender.login` for the epoch push is `github-actions[bot]`, and I'll bet my hat Taskcluster won't accept that as an email...

**Comment by stephenmcgruer** [comment]
This was hopefully fixed by https://github.com/web-platform-tests/wpt/pull/20561, we will see from today's daily push to epochs.

**Comment by rakuco** [comment]
Looks like it -- [28b0967](https://wpt.fyi/results?label=master&label=stable&max-count=1&product=chrome&product=firefox&product=safari&sha=28b096731f) includes Safari, Firefox and Chrome.
