### ISSUE TITLE
Missing WebKitGTK experimental wpt.fyi runs

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#20552]
The latest WebKitGTK run is [1df8c00](https://wpt.fyi/results/?sha=1df8c00a83&label=master&label=experimental&max-count=1&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) from November 29 at the time of writing.

**Comment by stephenmcgruer** [comment]
Is suspect this is related to https://github.com/web-platform-tests/wpt/issues/20551 and likely has the same root cause (I think the decision task work broke `refs/heads/epochs/daily`).

cc @jgraham

**Comment by stephenmcgruer** [comment]
This was hopefully fixed by https://github.com/web-platform-tests/wpt/pull/20561, we will see from today's daily push to epochs.

**Comment by rakuco** [comment]
[28b0967](https://wpt.fyi/results?label=master&label=experimental&max-count=1&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk&sha=28b096731f) includes WebKitGTK again, so I guess it worked!
