### ISSUE TITLE
Edge canary has not run since Dec 1st

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#20584]
Based on https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk, Edge Canary last ran for 9c100c3 on Dec 1st. (It is expected to run daily).

**Comment by stephenmcgruer** [comment]
Did some reading, I believe Edge canary is meant to run from `epochs/three_hourly`. Looking at https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1, every run on branch `epochs/three_hourly` since Dec 1st is showing a spinny blue pending icon.

Looking at an example run, the Edge Dev part is just spinning saying 'Waiting for an available agent'.

**Comment by mustjab** [comment]
We have an automated job that runs every Sunday to re-create Windows VMs and the job succeeded, but looks like installation of the Azure pipelines agents on these VMs failed, so none of them appear on as available. I've manually re-run the job to recreate VMs and will ensure that we have them ready to handle queued jobs today.

**Comment by mustjab** [comment]
Jobs should be running now, our token used to add agents to the pool has expired, so i've renewed it and re-created all Windows VMs. Let me know if you still see issues.
