### ISSUE TITLE
html/syntax/parsing/html5lib_menuitem-element.html might be checking for the wrong number of whitespaces

### ISSUE THREAD

**Issue by pshaughn** [web-platform-tests/wpt#20592]
Every browser seems to be failing this test on the same one case (shown as three because of calling it different ways), with a string that differs from expectation only by whitespace. This leads me to think the test might just not be expecting the right amount of whitespace.

**Comment by annevk** [comment]
This seems to have gotten fixed by https://github.com/web-platform-tests/wpt/commit/cf7f8ae932fcc0db24161e640541aa023486243f. At least per wpt.fyi all browsers pass this test.
