### ISSUE TITLE
webmessaging tests with postMessage API

### ISSUE THREAD

**Issue by aogilvie** [web-platform-tests/wpt#206]
I have tried to fix a few issues with some of the tests with /webmessaging, there are still some outstanding issues.

I just want to leave a quick message for those that might stumble upon them.

Most are caused by the messages being sent from testharness.js that arrive before the actual message being tested. Therefore, without proper testing of either data type or data itself the test were failing.

**Comment by foolip** [comment]
Sounds like this was about bugs in the tests at https://wpt.fyi/webmessaging to begin with? I've taken a look at it seems like all tests pass in at least one browser, which is better than expected. Are there still bugs to be fixed here?

@mdittmer @lukebjerring this is a typical case where the interop view would have come in handy :)
