### ISSUE TITLE
CI check for generated tests doesn't include conformance-checkers/tools/picture.py

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#20649]
See https://github.com/web-platform-tests/wpt/pull/20629

For other parts of wpt there is a CI check to run the scripts that generate tests and makes sure it doesn't cause the diff to change, thereby checking that generated tests aren't edited directly. It appears that it doesn't do this for `conformance-checkers/tools/picture.py` at least.

cc @sideshowbarker @jgraham

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/28832.
