### ISSUE TITLE
w3c-test.org doesn't have a sane HTTP_NOTSAMESITE_ORIGIN

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#20706]
I'm not sure whether this should be filed here or in some other issue tracker.  @jgraham do you know, by any chance?

http://w3c-test.org/html/browsers/origin/cross-origin-objects/cross-origin-objects.html times out in Safari and Firefox because on that page `get_host_info().HTTP_NOTSAMESITE_ORIGIN` is returning `"http://not-web-platform.test"` which is not actually a thing.

I suspect this server never got updated after <https://github.com/web-platform-tests/wpt/pull/17873>, since the `not-w3c-test.org` hostname is in fact a thing and does resolve to the test stuff.  So presumably that just needs to be stashed in the `hosts[alt]` bits... @jugglinmike @Hexcles

**Comment by jgraham** [comment]
I'm not sure if anyone is actively maintaining w3c-test.org at this point. The intent is that one should use http://wpt.live instead, but I'm not exactly sure whether all the PR mirroring parts of that are in place yet. However that does fix this issue; maybe we should more actively promote that site, or make w3c-test.org redirect.

**Comment by bzbarsky** [comment]
> The intent is that one should use http://wpt.live instead

Hmm.  Should wpt.fyi point to that, then?

**Comment by sideshowbarker** [comment]
If/when we do actually have the PR mirroring set up on wpt.live, I can change w3c-test.org to just redirect to wpt.live.

In the meantime, if there’s anything broken in how w3c-test.org is how behaving, I can make time to fix it.

**Comment by Hexcles** [comment]
> Hmm. Should wpt.fyi point to that, then?

Given that https://github.com/web-platform-tests/rfcs/pull/36 has passed, yes wpt.fyi should point to wpt.live. And I did.

Note that wptpr.live isn't fully functioning yet, AFAIK. @stephenmcgruer

**Comment by bzbarsky** [comment]
> And I just changed it.

Awesome, thank you!  For my purposes, that's probably enough to resolve this.
