### ISSUE TITLE
How to test origin policy?

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#20773]
[Origin policy](https://wicg.github.io/origin-policy/) has moved from a model where the response contains `Sec-Origin-Policy: policy-name` and the browser fetches `/.well-known/origin-policy/policy-name`, to one where the response contains `Origin-Policy: allowed=("policy-name")` and the browser fetches `/.well-known/origin-policy`, then checks the resulting JSON document's `"id"` field.

This causes a problem when attempting to write tests, since there is only one WPT origin, but we generally need a varying origin policy per test. Previously we could just have each test send a different `policy-name` and stuff all of the origin policies into https://github.com/web-platform-tests/wpt/tree/master/.well-known/origin-policy . But now that won't work; we need the single `/.well-known/origin-policy` endpoint to respond differently for each test.

I am especially concerned about how to deal with multiple tests running in parallel, which is something that e.g. Chromium does, at least for local development (and probably on CI too). That seems like it would rule out approaches based on remembering what the last test requested was, and then sending the right response when `/.well-known/origin-policy` is requested.

One way out would be if we changed the origin policy spec to send a Referrer: https://github.com/WICG/origin-policy/issues/65.

Another crazy idea is generating a sub-origin per test and then doing most of the work in an iframe pointing to that sub-origin. Is that feasible with current infrastructure?

Do the WPT experts have any ideas for this?

**Comment by domenic** [comment]
It looks like https://github.com/web-platform-tests/wpt/pull/13272 may have added some large (?) number of origins, but I can't decipher the Python enough to tell exactly what those origins are or how many there are, and @jugglinmike's [request](https://github.com/web-platform-tests/wpt/pull/13272#issuecomment-452389758) to document them doesn't seem to have happened.

It's possible we can reuse those origins though, if our total number of tests ends up less than that many.

**Comment by Hexcles** [comment]
We do have a lot of origins available (`./wpt make-hosts-file | wc -l` says 60+).

This also sounds related to @npm1 's feature request the other day: being able to specify the origin where a test should run.

**Comment by Hexcles** [comment]
By the way, does the browser send cookies when downloading `/.well-known/origin-policy`? If so, I suppose you could store a token for the stash server in cookies?

**Comment by domenic** [comment]
Cookies are currently under debate, heh. https://github.com/WICG/origin-policy/issues/21

It's also possible this may become a moot point as the move to a single-`/.well-known` URL model might have been premature: https://github.com/WICG/origin-policy/issues/66

**Comment by Hexcles** [comment]
I see https://github.com/WICG/origin-policy/issues/66 has been closed (fixed?). @domenic so does that mean this has become moot?

**Comment by domenic** [comment]
No; we fixed the problem with the single `/.well-known` URL model so are sticking with it, and thus we still have some testing issues.

My current plan (may prototype today?) is to have each test use an iframe to a distinct host, and hope we write fewer tests than WPT provides hosts. Maybe I'll write some lint tooling to make sure no origin policy tests reuse a host that another origin policy test reused, I dunno.

**Comment by domenic** [comment]
I'd like to write a python handler that responds to requests to `/.well-known/origin-policy` and serves different files from `/origin-policy` depending on what hostname is being requested. Would anyone more familiar with the server infrastructure be able to give me tips?

My main unknown is how to make wptserve respond to extension-less requests; the rest seems like just reading docs for how to serve files and inspect request URL components and such,

**Comment by Hexcles** [comment]
I don't think we can have a normal [Python file handler](https://web-platform-tests.org/writing-tests/python-handlers/index.html) for this, as the filename has to end with `.py`. We'd need to register a global route. See a similar use case https://github.com/web-platform-tests/wpt/issues/14707

@jgraham this is yet another `.well-known` use case.

**Comment by domenic** [comment]
I have something working on my local machine. I am suspicious that the ~60 valid hostnames may not suffice for the number of tests I am going to write; I've used up 16 already on just parsing tests for two policy items, CSP and FP.

Potential mitigations, off the top of my head:

* Share hostnames between multiple tests. For example, I could have both invalid CSP and invalid FP in the same origin policy/hostname, under the assumption that it's unlikely for invalid CSP to suddenly cause invalid FP to be treated as valid.

* Add more hostnames.

**Comment by domenic** [comment]
I've realized that using the existing subdomains is not going to work, because then origin policies installed in one test will interfere with other tests being run on that origin. (E.g., an origin policy that includes a CSP for blocking image loading will cause all image-related tests run on that origin to mysteriously fail, if the image-related test runs after the origin policy test.) So I opened #21705 to just add new subdomains.
