### ISSUE TITLE
Community-TC (pull_request) check failure

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#20803]
Dear fellow advanced github colleagues,

An increasing number of pull requests in /web-platform-tests/ involving my tests are, I presume, being ignored (or are not mergeable) because of a check failure named
Community-TC (pull_request) . I do not understand what is failed, how and why it fails and I do not understand what I can do or what is expected from me. Please help me.

Involved PRs are:

https://github.com/web-platform-tests/wpt/pull/18214 : this one has even been approved!

https://github.com/web-platform-tests/wpt/pull/18602

https://github.com/web-platform-tests/wpt/pull/19735

https://github.com/web-platform-tests/wpt/pull/20028

https://github.com/web-platform-tests/wpt/pull/20030

https://github.com/web-platform-tests/wpt/pull/20032

https://github.com/web-platform-tests/wpt/pull/20033

and I'm afraid there will be more when I submit more tests in additional PRs. Again christmas-please help me understand or fix these...

**Comment by jdm** [comment]
I believe all of these pull requests need to be rebased in order for the check to pass.

**Comment by TalbotG** [comment]
Josh,
Thank you for your quick response.
Do you know how I can rebase such pull requests? Can you elaborate on this?

**Comment by jdm** [comment]
You need to fetch the latest changes from the upstream repository and use the git rebase command to rebase each branch on top of the more recent upstream commits. After that you will need to force push the branches, and then the taskcluster checks should start working.

**Comment by TalbotG** [comment]
The following comes from an email I got from @frivoal who deserves all of the credits. I am putting this information in this Issue so that such **instructional step-by-step information on how to fix this problem** will not be lost and will remain available and useful+valuable for others (like me), for github newbies and in case I forget (we're all getting older ...).

This "Community-TC (pull_request)" check failure probably boils down to the fact that the pull requests I set were based on a (somewhat) old version of web platform tests, and the checks are newer, and they fail to find what they want.

The solution was to update my pull requests to start from a newer point in wpt.

Steps to correct:

**Step 1) Save any unsaved work in progress**

`cd path/to/where/you/put/wpt`
`git status`

If it comes clean, go to step 2)
If it shows unsaved changes, then I needed to make a copy of these files somewhere outside of my wpt repository, then drop those unsaved changes from my repo with `git reset --hard`


**Step 2) Update my copy of wpt**
 
`git checkout master`
`git pull upstream master`

**Step 3) Rebase each branch**

For each pull request, assuming it is on a branch called CSS4Pseudo-GT-PRd
 
`git checkout CSS4Pseudo-GT-PRd`
`git rebase master`
`git push -f origin CSS4Pseudo-GT-PRd`

This has indeed solved this "Community-TC (pull_request)" check failure problem.

Again, all credits and thank you must go to @frivoal .

**Comment by frivoal** [comment]
I think we can close this now, since the problem for the pull requests reported is resolved.

**Comment by frivoal** [comment]
Note to anyone attempting to follow the steps indicated in https://github.com/web-platform-tests/wpt/issues/20803#issuecomment-567208355: these assume that the local repository has been set up as indicated in https://web-platform-tests.org/writing-tests/github-intro.html. If not, the names of the remote repositories (`origin` and `upstream`) may be different.
