### ISSUE TITLE
updated tests for validationMessage inconsistent with the spec

### ISSUE THREAD

**Issue by kontomondo** [web-platform-tests/wpt#20825]
Changes from https://github.com/web-platform-tests/wpt/pull/20663 introduce an issue for `validationMessage`. When a custom error is set (via `setCustomValidity`) and the element is disabled, the test expects `validationMessage` to be the custom error. The spec on the other hand implies that it should be an empty string.

Per https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-validationmessage

>If this element is not a *candidate for constraint validation* or if this element satisfies its constraints, then return the empty string.

and

>A submittable element is a *candidate for constraint validation* except when a condition has *barred the element* from constraint validation. (For example, an element is barred from constraint validation if it is an object element.)

and

>Constraint validation: If an element is disabled, it is *barred from constraint validation*.

would result in an empty message, yet the updated test expects the custom error to show.

Either the tests or the spec would need to be updated, as at the moment they're conflicting,

fyi @tkent-google @domenic

**Comment by tkent-google** [comment]
You're right.  It's a bug of #20663 
@mfreed7 Would you fix this please?

**Comment by TimothyGu** [comment]
I provided a fix in #21014.

**Comment by mfreed7** [comment]
Thanks for the fix!
