### ISSUE TITLE
multiTouchPointsWithPause.html is causing infrastructure tests to fail

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#20838]
e.g. from https://community-tc.services.mozilla.com/tasks/D-fhX_u9ReGDAzOqRyAdrw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FD-fhX_u9ReGDAzOqRyAdrw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```
/infrastructure/testdriver/actions/multiTouchPointsWithPause.html
  ERROR /infrastructure/testdriver/actions/multiTouchPointsWithPause.html - invalid argument: TouchEnd and TouchCancel must not have any touch points.
  (Session info: chrome=80.0.3987.16)
```

This is currently blocking all infra PRs.

**Comment by jgraham** [comment]
Also multiTouchPointsReleaseSecondPoint.html on mac

**Comment by stephenmcgruer** [comment]
Note; the tests were disabled in db7735a94c60d9b04d80035d76a723762de38c5c

**Comment by stephenmcgruer** [comment]
Re-enabled in https://github.com/web-platform-tests/wpt/pull/20952; the tests appear to pass now.
