### ISSUE TITLE
[css-color] lab() tests fail to specify the first value as a percentage

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt#20993]
The various lab color tests (css/css-color/lab-*) fail to specify the first value as a percentage, therefore none of them parse according to the grammar in https://www.w3.org/TR/css-color-4/#specifying-lab-lch

@svgeesus

**Comment by svgeesus** [comment]
Yeah, the tests were written at s time that the spec only allowed a number.

But also, I was told by @frivoal at the A Coruña meeting that I was too hasty changing `L` at that it should allow either a number or a percentage.

So it seems I need to fix the spec, and also duplicate all the tests so that both forms are tested.

**Comment by smfr** [comment]
I thought we resolved that lab/lch/gray took lightness as a percentage (https://github.com/w3c/csswg-drafts/issues/4648)?

**Comment by svgeesus** [comment]
@frivoal could you explain what you said at the meeting, that either number or percent should be allowed?

@smfr yes we did

**Comment by frivoal** [comment]
@svgeesus Now, now... What did I say at the meeting… I think I remember, but I'm not 100% sure, so if anybody has a different recollection, please correct me.

@tabatkins (I think) had insisted that we must accept percentages, not just raw numbers, and @svgeesus had insisted that allowing 0.5 to mean the same as 50% in this context would be a problem, given that this is different from how raw numbers had been used for Lab in other contexts.

From there, it seemed that the conclusion that was drawn and (reluctantly) edited in by @svgeesus was that only percentages should be allowed. However, allowing both percentages and numbers, with numbers being in the 0–100 range (not the 0–1 range) is also a solution, which @svgeesus thought was being objected to, but actually wasn't, so we may be able to switch to that.

**Comment by svgeesus** [comment]
OK well meanwhile I just made a PR on WPT to add the percent as required by the spec currently. If we make percent optional then I will dup the tests to have the non-percent form, but at least now the spec and tests are aligned.

**Comment by svgeesus** [comment]
Closing as PR on WPT has now been merged.
