### ISSUE TITLE
Allow arbitrary XML files

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#2101]
presto-testo contains a couple of test suites of XMLish web platform features that use arbitrary XML; per `web-platform-tests/docs/test-format-guidelines.md` tests must be in HTML, XHTML, or SVG. Arbitrary XML is therefore disallowed. We should probably allow arbitrary XML because:
- arbitrary XML needs tested,
- this gives us far better test coverage for things like XPath, which like it or not are part of the platform, and
- we already have loads of arbitrary XML files in the repo, as well as some which are MathML.

**Comment by gsnedders** [comment]
Given we already have so much in the repo, I suggest we treat this as a documentation bug.

**Comment by foolip** [comment]
@gsnedders, you mean that this already works for reftests, and just isn't documented?

**Comment by gsnedders** [comment]
@foolip this already works for everything, AFAIK? should check.

**Comment by jugglinmike** [comment]
@gsnedders I'd like to help out, but I can't find any examples of "arbitrary XML" tests. There are 210 files with an extension of `.xml` that don't specify an `xhtml` namespace:

    $ git ls-files | grep -Ei '\.xml$' | xargs grep -Li xhtml | wc -l
    210

Among those, a few contain the strings "match" or "testharness", but none of them are tests:

    $ git ls-files | grep -Ei '\.xml$' | xargs grep -Li xhtml | xargs grep -E 'match\b|testharness'
    html/tools/html5lib_test.xml:    <script src="/resources/testharness.js"></script>
    html/tools/html5lib_test.xml:    <script src="/resources/testharnessreport.js"></script>
    html/tools/html5lib_test_fragment.xml:    <script src="/resources/testharness.js"></script>
    html/tools/html5lib_test_fragment.xml:    <script src="/resources/testharnessreport.js"></script>

Am I looking in the wrong place? Or maybe misunderstanding the intent of this issue?

**Comment by gsnedders** [comment]
@jugglinmike I think most of the "arbitrary XML" cases still include the HTML namespace so they have have the script/link elements, though this appears to only be:

```
css/CSS2/other-formats/xml/background-19.xml
css/css-namespaces/prefix-003.xml
css/css-namespaces/prefix-004.xml
css/css-namespaces/prefix-005.xml
```

I think the real intent of this issue was clarifying the documentation here?

**Comment by gsnedders** [comment]
Ah, no.
