### ISSUE TITLE
Question: is cygwin a supported platform?

### ISSUE THREAD

**Issue by ricea** [web-platform-tests/wpt#21180]
I'd like to drop cygwin support from pywebsocket, but I won't do that if cygwin is officially supported by web platform tests.

**Comment by Hexcles** [comment]
At least it's not the recommended way to run tests on Windows. @jgraham do you happen to know? cc @mustjab in case folks at Microsoft use cygwin (I suspect not)

**Comment by jgraham** [comment]
I am somewhat concerned that the windows development environment for gecko is using cygwin, and so dropping support might break that.

**Comment by jgraham** [comment]
https://ftp.mozilla.org/pub/mozilla.org/mozilla/libraries/win32/MozillaBuildSetup-Latest.exe is an installer for that environment if we need to test. Full instructions at https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Windows_Prerequisites

**Comment by gsnedders** [comment]
@jgraham That says Mozilla uses MSYS, so not cygwin. I strongly suspect cygwin support is irrelevant.

**Comment by stephenmcgruer** [comment]
Mozilla docs include:

> The build may fail if you have Cygwin installed. Make sure that the MozillaBuild directories (/c/mozilla-build and subdirectories) come before any Cygwin directories in your PATH environment variable. If this does not help, remove the Cygwin directories from PATH, or try building on a clean PC with no Cygwin.

So yeah, I would agree that looks like Cygwin is not required for Gecko on Windows.

Let's make this official (though I don't think it requires an rfc). I'm cc-ing the major folks involved below (feel free to add people) - if nobody objects by next Monday let's say Cygwin is not supported.

cc @mustjab @foolip @Hexcles @jgraham @gsnedders

**Comment by stephenmcgruer** [comment]
No replies over 10 days later, so I'm closing this.

@ricea - feel free to consider cygwin unsupported.
