### ISSUE TITLE
[css-grid] Expected height in grid-percentage-rows-indefinite-height-002.html does not seem to consider the set border

### ISSUE THREAD

**Issue by karstenw-ro** [web-platform-tests/wpt#21197]
In this [test](https://github.com/web-platform-tests/wpt/blob/master/css/css-grid/grid-definition/grid-percentage-rows-indefinite-height-002.html), the expected height of the grid container of [second test case](https://github.com/web-platform-tests/wpt/blob/a5e2efd90b6766f33e94d92e1858a68f8c40c977/css/css-grid/grid-definition/grid-percentage-rows-indefinite-height-002.html#L32) does not seem to consider it's border.

While it's first and third row should have a height of 25px each, the height of the second element should be 10px ((25px + 25px)*0.2). This would already reach the total expected height of the container (60px). However the [border of the element](https://github.com/web-platform-tests/wpt/blob/a5e2efd90b6766f33e94d92e1858a68f8c40c977/css/css-grid/grid-definition/grid-percentage-rows-indefinite-height-002.html#L13) adds an additional 10px.

**Comment by gsnedders** [comment]
cc/ @mrego

**Comment by mrego** [comment]
No, it's fine. The height is 25px + 25px plus the border 10px, so it's 60px.
Then the 20% is resolved later, and the 2nd row has 10px size (20%*50px).

All this is explained at https://blogs.igalia.com/mrego/2018/08/10/changes-on-css-grid-layout-in-percentages-and-indefinite-height/.
Also this is failing in Firefox as the following bug is not solved yet: https://bugzilla.mozilla.org/show_bug.cgi?id=1481876
