### ISSUE TITLE
Firefox stopped support for transferControlToOffscreen()

### ISSUE THREAD

**Issue by guest271314** [web-platform-tests/wpt#21205]
FYI Firefox recently stopped supporting `transferControlToOffscreen()` for an as-yet undiclosed reasons
[canvas.transferControlToOffscreen() throws "NS_ERROR_NOT_IMPLEMENTED" Exception](https://bugzilla.mozilla.org/show_bug.cgi?id=1609238)

> Thanks for the report!
> Unfortunately we've stopped exposing support for transferControlToOffscreen for now, even with the pref.
> [Bug 1390089](https://bugzilla.mozilla.org/show_bug.cgi?id=1390089) tracks the work to re-enable it.

wpt `OffscreenCanvas` tests where `transferControlToOffscreen()` is executed should be expected to fail at Firefox until support is resumed.

**Comment by gsnedders** [comment]
This doesn't seem actionable? Yes, they'll fail, but so do plenty of other tests in Firefox.
