### ISSUE TITLE
Should frameset names be in a window's named properties?

### ISSUE THREAD

**Issue by pshaughn** [web-platform-tests/wpt#21249]
https://github.com/web-platform-tests/wpt/blob/2f346208c2a115a601b580e7869fe112b97c4246/html/browsers/the-window-object/named-access-on-the-window-object/named-objects.html#L50-L58
but https://html.spec.whatwg.org/#dom-window-nameditem-filter still lists frameset elements. 

I think this might be due to a typo in https://github.com/whatwg/html/pull/1869 since the PR comment indicates getting rid of framesets but in the actual commit framesets are still in the list.

**Comment by gsnedders** [comment]
I'd suggest raising a bug on the HTML spec?

**Comment by pshaughn** [comment]
That's sorted then; nothing to change on the test side.
