### ISSUE TITLE
Azure Pipelines sometimes fail during git checkout 

### ISSUE THREAD

**Issue by npm1** [web-platform-tests/wpt#21275]
Error message: `Git checkout failed with exit code: 128`
Example: https://github.com/web-platform-tests/wpt/pull/21271/checks?check_run_id=399440609

**Comment by npm1** [comment]
Hm ok the bot was able to land the PR, so not sure what was going on. I don't see this issue in other PRs, so it may just be a flake? Feel free to close.

**Comment by gsnedders** [comment]
@npm1 it's not a blocking job, so it can land without; #16537 has been running into this too so I don't know what's up :/

**Comment by Hexcles** [comment]
This seems like an intermittent issue. I'm tentatively downgrading this to roadmap.

**Comment by stephenmcgruer** [comment]
Do we know if this has happened again? Nobody owns this, so `roadmap` is the wrong priority; downgrading to backlog - but I'm tempted to close it.

**Comment by npm1** [comment]
I haven't seen this recently. Closing.
