### ISSUE TITLE
[docs] assert_throws_*() are missing documentation; deprecate assert_throws()

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#21288]
There is no docs for the new functions introduced in https://github.com/web-platform-tests/wpt/issues/11726 ([RFC 29](https://github.com/web-platform-tests/rfcs/pull/29)).

@bzbarsky said in https://github.com/web-platform-tests/rfcs/pull/29#issuecomment-576526134

> Fwiw, it would also help if people stopped adding new `assert_throws`. 

The docs should say that `assert_throws` is deprecated to help with this.

Similarly for `promise_rejects_*()` and `promise_rejects()`.

**Comment by stephenmcgruer** [comment]
There is some documentation being added in https://github.com/web-platform-tests/wpt/pull/21294

Note that the PR doesn't currently mark `assert_throws` as deprecated; it instead goes the route of removing it entirely (which seems reasonable to me).

**Comment by bzbarsky** [comment]
I updated testharness-api.md to document the new functions in https://github.com/web-platform-tests/wpt/pull/21762 and it looks like https://web-platform-tests.org/writing-tests/testharness-api.html has picked up those changes.

@zcorpan is there something else to be done here?

**Comment by zcorpan** [comment]
Nope, I would say this is fixed. Thanks @bzbarsky !
