### ISSUE TITLE
Remove css/css-regions?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#21304]
@clopez noted that https://wpt.fyi/results/css/css-regions is almost entirely failing in all browsers.

Most of the tests were written a long time ago in https://github.com/w3c/csswg-test/commits/master/css-regions-1.

Is any browser engine team planning to implement CSS Regions? If not, we should remove these tests.

@astearns @rachelandrew you are listed in META.yml, what are your thoughts?

**Comment by clopez** [comment]
Some info about current support:
* Safari (and other WebKit based browsers) removed support in 2017: https://lists.webkit.org/pipermail/webkit-dev/2017-July/029315.html
* Chrome removed it long before: https://www.chromestatus.com/feature/5655612935372800
* Firefox never implemented it.

The page can-i-use not longer lists it as supported for any recent version of any browser: https://caniuse.com/#feat=css-regions (only for old IE)

**Comment by astearns** [comment]
These tests can be removed.

**Comment by foolip** [comment]
Thanks @astearns, I'll go ahead and send a PR for that.
