### ISSUE TITLE
Lint against new assert_throws usages

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#21356]
In #21350 / #21353 @bzbarsky did an awesome job almost eliminating the ambiguous `assert_throws`. (And kudos to @stephenmcgruer for the reviewing and shepherding!)

We should prevent any further usage of them from creeping into the codebase, by adding a lint rule, plus a safelist for all existing usages that we can slowly whittle down over time.

**Comment by bzbarsky** [comment]
See https://github.com/web-platform-tests/wpt/pull/21294

**Comment by domenic** [comment]
Well, I should have known you all were already on it :). I'll close this since that seems well underway.
