### ISSUE TITLE
Improve docs on assert_throws_*

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#21399]
Might be good to improve the docs around:

 * assert_throws()
 * assert_throws_js()
 * assert_throws_exactly()

In testharness.js and also in the docs. It's not clear when to choose one over the other. Happy to help make any changes, but I don't yet fully grasp the differences between them.

**Comment by stephenmcgruer** [comment]
You're absolutely correct, thanks for the issue :). We have a tracking issue already at https://github.com/web-platform-tests/wpt/issues/21288, and @jgraham has some WIP docs in their PR at https://github.com/web-platform-tests/wpt/pull/21294 . Feel free to take a look and make some suggestions!
