### ISSUE TITLE
Tests not running for IE11 on Windows 10

### ISSUE THREAD

**Issue by NbhosaleInstart** [web-platform-tests/wpt#21433]
Running wpt IE js tests for IE11 version 11.592.18362.0  on Windows 10 gives the following errors. Tried webdrivers versions `IEDriverServer_x64_3.0.0`, `IEDriverServer_x64_3.12.0` and `IEDriverServer_x64_3.9.0` 

>python wpt.py run ie js
>Running 14 tests in web-platform-tests
>
>ERROR Unsupported test type reftest for product ie
>ERROR Unsupported test type testharness for product ie
>ERROR Unsupported test type crashtest for product ie
>Ran 0 tests finished in 0.0 seconds.
>  ΓÇó 0 ran as expected. 0 tests skipped.
>
>CRITICAL No tests ran

**Comment by gsnedders** [comment]
IE11 has never been supported by wptrunner aside from for the wdspec tests; none of the other test types have ever been supported.

It seems unlikely we'll add support, and the willingness to accept any patch would depend on how big it is (though I expect it would affect more code than is worthwhile, for a browser the tests would almost never be run against).

**Comment by Hexcles** [comment]
I don't think there's anything we can action on here, closing the issue.
