### ISSUE TITLE
Are wpt-firefox-nightly-stability WebXR tests running as expected?

### ISSUE THREAD

**Issue by klausw** [web-platform-tests/wpt#21563]
While looking at results for my autogenerated PR https://github.com/web-platform-tests/wpt/pull/21556, I noticed that the wpt-firefox-nightly-stability tests were taking a long time, and the results from the live log looked confusing. I'm not familiar with this test runner, is this expected or is something going wrong? Feel free to close this as "working as intended" if appropriate, but this looked a bit odd and potentially wasteful to me.

For example, most tests report "navigator.xr is undefined" and "specified 2 'cleanup' functions, and 1 failed" apparent errors, and show FAIL/ERROR in logs. This would be expected if the WebXR API isn't supported in this build, but in that case it seems strange and a bit inefficient to re-run the tests 10 times and counting them all as successful, assuming I'm interpreting the `Running tests in a loop 10 times : PASS` message correctly.

For context, here are some links from the task runner:

https://community-tc.services.mozilla.com/tasks/groups/W-FiSLwMQUOFf0d3cq2bdw
https://community-tc.services.mozilla.com/tasks/DoZrQL35TW67WvtKTo3oiQ

https://community-tc.services.mozilla.com/tasks/DoZrQL35TW67WvtKTo3oiQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FDoZrQL35TW67WvtKTo3oiQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

```
xr_session_promise_test@https://web-platform.test:8443/webxr/resources/webxr_util.js:53:18
@https://web-platform.test:8443/webxr/xrWebGLLayer_viewports.https.html:62:24
  NOTRUN XRWebGLLayer reports a valid viewports for inline sessions
  ERROR /webxr/xrWebGLLayer_viewports.https.html - Test named 'XRWebGLLayer reports a valid viewports for immersive sessions' specified 2 'cleanup' functions, and 1 failed.
  FAIL XRWebGLLayer reports a valid viewports for immersive sessions - promise_test: Unhandled rejection with value: object "TypeError: can't access property "test", navigator.xr is undefined"
xr_promise_test@https://web-platform.test:8443/webxr/resources/webxr_util.js:11:15

[...]

23:50.11 INFO ### /webxr/xrWebGLLayer_viewports.https.html ###
23:50.11 INFO |                             Subtest                             | Results |                                                           Messages                                                          |
23:50.11 INFO |-----------------------------------------------------------------|---------|-----------------------------------------------------------------------------------------------------------------------------|
23:50.11 INFO |                                                                 | ERROR   |                                                                                                                             |
23:50.11 INFO | `XRWebGLLayer reports a valid viewports for immersive sessions` | FAIL    | `promise_test: Unhandled rejection with value: object "TypeError: can't access property "test", navigator.xr is undefined"` |
23:50.11 INFO | `XRWebGLLayer reports a valid viewports for inline sessions`    | NOTRUN  |                                                                                                                             |
23:50.11 INFO 
23:50.11 INFO ::: Running tests in a loop 10 times : PASS
23:50.11 INFO ::: Running tests in a loop with restarts 5 times : PASS
23:50.11 INFO ::: Running tests in a loop 10 times with flags chaos_mode_flags=3 : PASS
23:50.11 INFO ::: Running tests in a loop with restarts 5 times with flags chaos_mode_flags=3 : PASS
23:50.11 INFO :::
23:50.11 INFO ::: Test verification PASS
23:50.11 INFO :::
[taskcluster 2020-02-04 01:43:51.598Z] === Task Finished ===
[taskcluster 2020-02-04 01:43:51.750Z] Successful task run with exit code: 0 completed in 1530.317 seconds
```

**Comment by stephenmcgruer** [comment]
Hey Klaus,

Based on your description, this is working as intended. The goal of the Firefox (and Chrome) stability checks are to make sure that tests are not flaky; they do not check whether the test passes or not. So a consistent FAIL result 10 times is a PASS for the stability check :).

We do separately get real results for each browser (check the `wpt-chrome-dev-results` and `wpt-chrome-dev-results-without-changes` tasks), compute regression stats on them, and make them available on wpt.fyi (look for a check on the GitHub PR called `wpt.fyi - chrome[experimental] Chrome Results` - it is created once we have results from TaskCluster). So far we have made this check non-blocking, since its perfectly valid to add a test that fails in some browser. We have plans this year to start adding a few failure cases for it, such as introducing a test that has a harness error in all browsers.

Hopefully that (over?) answers your question; feel free to re-open if I've misunderstood :)
