### ISSUE TITLE
Minmax serialization tests are incorrect.

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/wpt#21599]
`css/css-values/minmax-number-serialize.html` and co. don't look correct to me.

**Comment by emilio** [comment]
Err, pressed enter too early.

https://drafts.csswg.org/css-values-4/#parse-a-calculation mentions the simplification process, which should apply. So we shouldn't serialize the whole expression as these tests imply.

cc @xiaochengh @tabatkins

**Comment by emilio** [comment]
We resolved on that behavior here: https://github.com/w3c/csswg-drafts/issues/4399#issuecomment-556160413

**Comment by xiaochengh** [comment]
Those tests were added before the resolution, and hence out of sync.

We should revise them.

**Comment by tabatkins** [comment]
(I'm working on these now, btw, just in case anyone else was planning on spending time on it.)

**Comment by smfr** [comment]
It looks like this was fixed up in https://github.com/web-platform-tests/wpt/commit/53876e32d827db82f4b7af38053529302c243d40 ?

**Comment by tabatkins** [comment]
Ah, yes, thanks.
