### ISSUE TITLE
Make the web-based runner work with the "Major new manifest version (v8): path trie edition" change

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#21623]
We need to update the http://web-platform.test:8000/tools/runner/index.html web-based runner to work with the *"Major new manifest version (v8): path trie edition"* change from #16537, which was merged in 31c0f5e but subsequently reverted (by me) in 68e755c.

And going forward, we need to ensure  we never again merge another change that breaks the http://web-platform.test:8000/tools/runner/index.html web-based runner. Because with #16537 (31c0f5e), we once again — as we’ve done pretty much every other time we made changes to the manifest-generation code — merged a change without any of us (including me) stopping to think to take time to test it against the http://web-platform.test:8000/tools/runner/index.html runner.

And so once again we completely broke the behavior of that runner, as well as the https://wpt.live/tools/runner/index.html and at http://w3c-test.org/tools/runner/index.html deployments of it.

For better or worse, a significant number of people — including browser implementors — use the wpt.live and w3c-test.org remote instances of the web-based runner in their testing. So when we break the runner and those deployments of it, that affects a lot of people. And (in my experience) it typically affects those people when they’re trying to run tests in order to complete some other task they’re in the midst of some relatively urgent need to get done. So under those circumstances, the breakage can be extremely frustrating for them.

See also https://github.com/web-platform-tests/wpt/issues/21625

**Comment by stephenmcgruer** [comment]
Do you consider this fixed with the work @jgraham did in https://github.com/web-platform-tests/wpt/pull/21633/commits/5c557bbb2fbeace98edf2efd76079f4830a818ed ?

(Which doesn't cover the automated testing part, but that should be covered by https://github.com/web-platform-tests/wpt/issues/16551)

**Comment by stephenmcgruer** [comment]
Tentatively closing based on previous comment.
