### ISSUE TITLE
Add automated testing of the http://web-platform.test:8000/tools/runner/index.html web-based runner

### ISSUE THREAD

**Issue by sideshowbarker** [web-platform-tests/wpt#21625]
31c0f5e from #16537 completely broke the http://web-platform.test:8000/tools/runner/index.html  runner, leaving it completely unusable, and none of us even noticed — in large part because we don’t have any internal test automation in place to do even any very basic smoke testing for it.

So, we need to add some internal automated testing of that runner to ensure we never again marge in any change that cause regressions in its basic behavior.

At least and in particular, we must ensure we aren’t regressing that web-based runner’s manifest-consumption behavior when we make changes to the manifest-generation code — because basically every single time we’ve ever touched that code, we’ve regressed the web-based runner.

See also https://github.com/web-platform-tests/wpt/issues/21623

**Comment by stephenmcgruer** [comment]
I know I asked you to file this, and I'm so sorry, but I just found https://github.com/web-platform-tests/wpt/issues/16551 -_-. As usual, we had all the forewarning we needed - from us - that we should have had testing for this.
