### ISSUE TITLE
tools/pywebsocket: making pywebsocket to upstream instead of fork

### ISSUE THREAD

**Issue by quasi-mod** [web-platform-tests/wpt#21749]
We are currently working on python 3 compatible version of pywebsocket, which is hosted [here](https://github.com/GoogleChromeLabs/pywebsocket3). We would like to use this new pywebsocket3 in WPT as git submodule, but it seems like WPT currently holds pywebsocket as a fork.

Looking at the log, it looks as though patch [70f1c9](https://github.com/web-platform-tests/wpt/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a) is the only patch applied after being forked, and was wondering if we could make pywebsocket3 to submodule again, if we apply this patch to pywebsocket3. 

We would like to know:
- In which test is the feature on patch 70f1c9 used?
- Is it OK if we make pywebsocket3 an upstream instead of a fork?

Thanks.

(Mentioning: @jgraham)

**Comment by stephenmcgruer** [comment]
cc @svillar and @ziransun as an FYI

**Comment by Hexcles** [comment]
I'm strongly in favour of un-forking pywebsocket (which implies switching to pywebsocket3 in this case).

With @quasi-mod 's permission, here's the [design doc](https://docs.google.com/document/d/1hX-R0G-jnfPs2c-neMqqOj5HcLGKAV1_6sqYrkvRKeI/preview) for pywebsocket3, which looks promising to me. @quasi-mod can probably shed more light on pywebsocket vs pywebsocket3.

I'm hoping that this will be a drop-in replacement without breaking any API, although we probably want to move the code back into `third_party` again and of course fix the import paths. I don't think this needs a RFC though. cc @jgraham

**Comment by Hexcles** [comment]
FWIW here's a list of recent pywebsocket PRs in this repo: https://github.com/web-platform-tests/wpt/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Apywebsocket

**Comment by quasi-mod** [comment]
A quick explanation about pywebsocket3

# overview
pywebsocket3 is basically a python 2/3 compatible version of pywebsocket.
It is hosted as a different GitHub repository, since it removes some of the features from the original pywebsocket.

# diff from the original pywebsocket
It has the following major differences from the original pywebsocket:
- Adds support for python 3.x
- Drops support for python 2.6< (python 2.7 is the only supported python 2.x)
- Drops support for non-standardized extensions (e.g. DeflateFrameExtensionProcessor)
- Drops support for old websocket standards (hixie75, hybi08)

For the standalone server:
- It drops support for pyOpenSSL since ssl module became a built-in module for python since v2.7
    - also drops related functions for this (_import_ssl(), _import_pyopenssl()).

# benefits
- python 3 compatibility
- drops deprecated features

I tested replacing pywebsocket3 in WPT locally, and the only change I needed to make was the ssl configurations (wpt/serve/serve.py uses the old _import_ssl and _import_pyopenssl [here](https://github.com/web-platform-tests/wpt/blob/master/tools/serve/serve.py#L597)) (tested on python 2). I am more than willing to make the tweaks (and of course, the path to new pywebsocket3) to get pywebsocket3 running on WPT.

**Comment by quasi-mod** [comment]
CC: @ricea @yutakahirano

**Comment by ricea** [comment]
Another major diff is the removal of support for running as an Apache module. We don't use that for anything, so we have dropped support.

**Comment by Ms2ger** [comment]
This seems like a good change, but if we reintroduce submodules, we'd probably need an RFC for that at least.

**Comment by stephenmcgruer** [comment]
It would really help to know, before we file such an RFC, why we don't use submodules today for our existing third_party dependencies.

**Comment by jgraham** [comment]
We don't use submodules because the amount of grief they caused when we did was phenomenal. It pushes work onto every user to keep them up to date, adds special cases to automatic sync, etc. I'm a-priori strongly opposed to any change that requires us to reintroduce submodules.

I too would really like to unfork pywebsocket, but I strongly prefer using a subtree to do the import, just like we do for other third party libraries, so that from the point of view of users the files look like any other files in the repo.

**Comment by Hexcles** [comment]
`git subtree` in `third_party` sounds good to me.

**Comment by quasi-mod** [comment]
+1 on `git subtree`. 

Is the feature added in patch commit [70f1c9](https://github.com/web-platform-tests/wpt/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a) still used in WPT? If there is need, I will make a patch for this in pywebsocket3.

**Comment by quasi-mod** [comment]
I have opened a PR #21845 to add pywebsocket 3 to third_party directory, and also update wpt/serve/serve.py to use pywebsocket 3.

**Comment by Hexcles** [comment]
As suggested by @stephenmcgruer , I created a PR to revert 70f1c91935512d14a3d7bd91203a3fd899d8063a : #21868 . I just pushed it to a few trigger branches and we'll see if there's any difference in results.

**Comment by Hexcles** [comment]
Based on results from #21868 , it does not seem like the feature added by us is used anymore.

**Comment by quasi-mod** [comment]
Pasting this for the record.

From @ricea in #21868
> > I strongly suggest that we figure out _why_ Chrome has 231 more passes. We don't want to accidentally let bad behavior (if thats what Chrome has) through.
> 
> I think this is the Chrome behaviour which is making the difference: https://bugs.chromium.org/p/chromium/issues/detail?id=949763. I can prioritise changing that if it helps.

**Comment by gsnedders** [comment]
To note, there's a bunch more discussion about dropping https://github.com/web-platform-tests/wpt/commit/70f1c91935512d14a3d7bd91203a3fd899d8063a in the draft PR (#21868).

**Comment by gsnedders** [comment]
#21845 landed so this is done, right?
