### ISSUE TITLE
Consider adding a way to pass a global to assert_throws_dom

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#21809]
Now that we have the JS and DOM cases clearly separated, it's worth thinking about ways to test that exceptions come from the right global in the DOM case.  Possible options:

1) Allow (or require?) passing a `new DOMException("", name)` instead of just the name string.  The code could then compare the `.constructor` on the two things.  The drawback is that silly message arg, and the general length.
2) Allow passing a trailing argument for the global, either a required one or defaulting to `self`.  The compare `.constructor` to `global.DOMException`.
3) Allow passing a (clearly required) leading argument for the global.

Other options?  Preferences?

**Comment by bzbarsky** [comment]
One issue with adding the trailing argument is that callers who are not passing a description right now would have to start passing one (e.g. undefined to keep the current behavior).

That said, I suspect most users of assert_throws_dom do not need to pass a non-default global, so this may still be the right tradeoff.

**Comment by bzbarsky** [comment]
OK, looks like options 2 and 3 do _not_ work, because at least some tests test that an exception is thrown in a navigated-away-from window.  And in that case passing in a global is no good, because the WindowProxy will now point to the new Window.  So it seems like we really do need to pass in the relevant DOMException constructor somehow.

**Comment by guest271314** [comment]
Perhaps you can provide the reason this test https://wpt.fyi/results/2dcontext/fill-and-stroke-styles/2d.pattern.image.broken.html?product=chrome-81.0.4044.17%20dev-linux-18.04%5Bpr_head%5D%4018dd6bdded&product=chrome%5Bexperimental%2Cmaster%5D&diff&filter=ACU now does not throw at Chromium using the generated test where the test should throw an exception? 

Running this test locally will not throw an exception at all at Firefox or Chromium.

Adjusting the code to set `src` of an `<img>` to `"data:,"` ("no data"; `0` width, `0` height) Chromium will throw a DOM exception named `"InvalidStateErr"` however per https://heycam.github.io/webidl/#idl-DOMException (https://github.com/web-platform-tests/wpt/pull/21686#issuecomment-584228057) `"INVALID_STATE_ERR"` is evidently part of web platform.

Setting aside for a moment the fact that the generated test fails to throw an exception, and modifying the test only throws an exception at Chromium, not Firefox, within the scope of this issue what name would or should be passed to `DOMException()`, `"InvalidStateErr"` or `"INVALID_STATE_ERR"`, and why?

**Comment by bzbarsky** [comment]
I have no idea why you are asking me why some random test does not throw in some random browser.  ;)   That said, glancing briefly at how that test is run in Firefox CI (or not, as the case may be), https://bugzilla.mozilla.org/show_bug.cgi?id=1016482 may be relevant.  And looking at the test, it probably needs to wait for the image to finish loading, and be in an error state, before calling `createPattern`.

For the rest, the exception name is "InvalidStateError", and that is what should be passed to the `DOMException` constructor.  "InvalidStateErr" is not a thing at all.  "INVALID_STATE_ERR" is the name of a numeric code.  `assert_throws_dom` will accept either an exception name or the name of the numeric code, or the numeric code itself (`11` in this case) and has tables for mapping between them.  The `DOMException` constructor only accepts the exception name.

None of that has anything to do with this issue, though; so now I am going to hide both of our comments.
