### ISSUE TITLE
Lint failure: how to read error message

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#21842]
@gsnedders Sam, 
Would it be possible for you to look at 
selection-* tests be5e211
reverted active-selection-019-ref.html 9ab577b
removed active-selection-014* 9801bb4
in https://github.com/web-platform-tests/wpt/pull/20800
and then tell me 
- what is wrong or incorrect with these pull requests
- how do you get to actually read/view an error message when Continuous Integration Lint test fails (after clicking the Details link of Community-TC and after reaching
https://community-tc.services.mozilla.com/tasks/TjBWlzR4QTeP5O7uFY5BLA )
- how come when I apply the `wpt lint ` program (just before git-push-ing the branch), no lint error were found or reported but, inside the CI, the Lint test fails

I am trying to become git-autonomous and git-independent when dealing with/managing Lint errors/failures. I have read 
[Fixing lint errors](http://web-platform-tests.org/writing-tests/lint-tool.html#fixing-lint-errors)

Thank you

**Comment by gsnedders** [comment]
FWIW, I'm not currently working on WPT, so hopefully someone else can help; looking quickly I suspect it's the base-commit of the branch that's broken, so if you try rebasing or merging master then hopefully it'll pass?

**Comment by TalbotG** [comment]
Sam,
Thank you for your reply. I will try rebasing.
step-by-step instruction information on how to git-rebase branches
https://github.com/web-platform-tests/wpt/issues/20803#issuecomment-567208355

I will close this issue here in 4 days from now.

**Comment by TalbotG** [comment]
I am closing this. From now on, whenever I stumbled on a Community-TC test failure that has a cryptic Lint failure, I will try to rebase and git-rebase the branch.
