### ISSUE TITLE
Missing tests for @page sizes "JIS-B5" and "JIS-B4"

### ISSUE THREAD

**Issue by felipeerias** [web-platform-tests/wpt#21858]
The test cases in `css/css-page/page-size-*` are missing tests for two values of the `size` property of the `@page` rule: "JIS-B5" and "JIS-B4".

These values represent two Japanese standard paper sizes:
  - JIS B5 is 182mm wide by 257mm high
  - JIS-B4 is 257mm wide by 364mm high

They are specified in the "CSS Paged Media Module Level 3" spec:
* https://www.w3.org/TR/css-page-3/#typedef-page-size-page-size

**Comment by felipeerias** [comment]
Entry in the Chromium feature dashboard:
* https://chromestatus.com/feature/5112328557166592#

Chromium bug (merged):
* https://crbug.com/1047642

**Comment by mrego** [comment]
Tests have been merged, thanks.
