### ISSUE TITLE
Set up a periodic job to regenerate the certficates

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#21968]
We currently update the certs on an as-needed basis. But with browsers, notably Safari, adding stricter time limits on cert expiry, we should set up a GitHub action or similar that regenerates the certs and opens a PR with the updated certs. This could run once a month and generate certs that are valid for a year. If we don't do this it's pretty likely we're going to end up with an outage when our certs are unexpectedly rejected in some browsers.

**Comment by stephenmcgruer** [comment]
@jgraham Do you have a list of the certs we would need to update, as well as an example them being updated previously? (I can probably look at the git history for the latter, once I know the list). Happy to put some time into creating a GitHub action for this.

cc @Hexcles as an FYI

**Comment by stephenmcgruer** [comment]
We are missing the information we need to proceed here, and nobody is looking at this. Marking backlog.

**Comment by stephenmcgruer** [comment]
Reading https://web-platform-tests.org/tools/certs/README.html, is this just a case of running `./wpt serve --config tools/certs/config.json` in a regular GitHub Action?

**Comment by Hexcles** [comment]
> Reading https://web-platform-tests.org/tools/certs/README.html, is this just a case of running ./wpt serve --config tools/certs/config.json in a regular GitHub Action?

I believe so. Then commit and create a PR.
