### ISSUE TITLE
html/semantics/embedded-content/the-object-element/object-attributes.html doesn't match the spec

### ISSUE THREAD

**Issue by pwombwell** [web-platform-tests/wpt#21980]
A subtest in the test dynamically changes/removes an HTMLObjectElement's name attribute, and then checks it is reflected by the contentWindow.name IDL attribute. This fails in Safari and Chrome as they retain the original name, which I believe is correct based on the current status of the spec. (Firefox fails a little earlier).

https://html.spec.whatwg.org/#the-object-element

> The name attribute, if present, must be a valid browsing context name. The given value is used to name the element's nested browsing context, if applicable, and if present when the element's nested browsing context is created.

ie. it isn't a live reflection, only a snapshot on creation.

I'll look into doing a PR, but for reference lines 29-34 are invalid:
  

>       obj1.setAttribute("name", "o1");
>       assert_equals(obj1.name, "o1", "The name of the object element should be 'o1'.");
>       assert_equals(obj1.contentWindow.name, "o1", "The contentWindow's name of the object element should be 'o1'.");
>       obj1.removeAttribute("name");
>       assert_equals(obj1.name, "", "The name of the object element should be empty string.");
>       assert_equals(obj1.contentWindow.name, "", "The contentWindow's name of the object element should be empty string.");

**Comment by zcorpan** [comment]
Fixed by #21981.
