### ISSUE TITLE
Possible issue with a `lh-rlh-on-root-001.html` testcase -- expect initial_l_h instead of initial_f_s?

### ISSUE THREAD

**Issue by twilco** [web-platform-tests/wpt#22055]
If I'm reading the spec correctly for the `lh` and `rlh` units (https://www.w3.org/TR/css-values-4/#lh), I think [this test](https://github.com/web-platform-tests/wpt/blob/master/css/css-values/lh-rlh-on-root-001.html#L80) should be (bolding mine):

<pre>
test(function() {
    window.document.documentElement.style="font-size: 2rlh; line-height: 142px;";
    f_s = get_root_font_size();
    assert_approx_equals( f_s, <b>initial_l_h</b> * 2, 1, "the rlh unit on the root element's font-size property actually works as a unit and doesn't merely cause a fallback that doesn't take the number of units into account");
}, "2rlh in font-size on root");
</pre>

instead of the current:

<pre>
test(function() {
    window.document.documentElement.style="font-size: 2rlh; line-height: 142px;";
    f_s = get_root_font_size();
    assert_approx_equals( f_s, <b>initial_f_s</b> * 2, 1, "the rlh unit on the root element's font-size property actually works as a unit and doesn't merely cause a fallback that doesn't take the number of units into account");
}, "2rlh in font-size on root");
</pre>

Relevant part of the spec is:

> When used in the value of the font-size property on the element they refer to, they [font-relative units] resolve against the computed metrics of the parent element—or against the computed metrics corresponding to the initial values of the font and line-height properties, if the element has no parent.

This testcase uses `rlh` units on the root element, meaning we need to defer to the computed metrics of the parent, but the root obviously has no parent, so we need to fall back to the initial value.  Since this is the `rlh` unit, I read this to mean the initial line-height value, rather than the initial font-size.

A similar set of issues was covered in https://github.com/web-platform-tests/wpt/issues/14160.

Am I correct in thinking this is problematic?

**Comment by TalbotG** [comment]
@twilco Tyler, 
After examining the last function (L77 to L82), I reach your conclusion.

> Am I correct in thinking this is problematic?

In my opinion, your finding and your solution are correct.

Notifying @frivoal Florian.
