### ISSUE TITLE
Allow lint tool to be used outside of this repo

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#2206]
I'd like to author web-platform-tests for jsdom and keep them in a to-upstream folder until they are upstreamed. Ideally, I'd like to be able to lint these tests in the to-upstream folder. However, the lint tool seems to be hard-coded to some kind of git listing.

It'd be great if any command line arguments passed to the lint tool were interpreted as files to lint.

**Comment by bobholt** [comment]
I agree all of our tools should be agnostic of where they're used. I'll look into it.

**Comment by foolip** [comment]
@domenic, is this still relevant? Putting on the backlog, but please close if you no longer need this.

**Comment by domenic** [comment]
Yes, this would still be nice.

**Comment by foolip** [comment]
Leaving on backlog then :) What have you already tried and what breaks when you try to lint files outside the repo?

**Comment by domenic** [comment]
Well, as far as I can tell, the lint tool is hard-coded to operate recursively from the directory it lives in. At least, that seemed true last time I tried it.

**Comment by foolip** [comment]
I guess that you just want to point it to a directory or files and have it recurse there?

FWIW, I've found it odd that I can't point it to a directory even with wpt, I have to enumerate all the files I want to check.

**Comment by domenic** [comment]
Yes, that would be ideal!

**Comment by jgraham** [comment]
This was fixed in #6207
