### ISSUE TITLE
Test changes to HTML's NavigatorID interface

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#2213]
There have been a few changes that need tests:
https://github.com/whatwg/html/pull/207
https://github.com/whatwg/html/pull/199
https://github.com/whatwg/html/pull/220

Also under consideration:
https://github.com/whatwg/html/issues/215

When this settles down, we should write tests for these to help engines to converge on the minimum differences that are known to be required for web compat.

**Comment by Honry** [comment]
Linking the fixed PR https://github.com/web-platform-tests/wpt/pull/3881 here, which have already addressed most changes, except whatwg/html#215 which it is still open.

**Comment by foolip** [comment]
Yep, that covers the spec changes I filed this issue for. I don't think I added anything for https://github.com/whatwg/html/issues/215, such tests would have to be added if we decide to add requirements.
