### ISSUE TITLE
No results from Safari Stable

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#22175]
We have not received results from Safari Stable for > 3 days: https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari
(STP is fine: https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=firefox&product=safari)

A few recent epoch commits:

* https://github.com/web-platform-tests/wpt/runs/496638309
  https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=43568&view=logs&jobId=e30964c2-2c6e-5f59-e489-a5a5f8e06cce&j=e30964c2-2c6e-5f59-e489-a5a5f8e06cce
* https://github.com/web-platform-tests/wpt/runs/494005679
  https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=43486&view=logs&jobId=e30964c2-2c6e-5f59-e489-a5a5f8e06cce

At first glance, the "all tests: Safari 3" job consistently fails, which suggests that some tests are crashing Safari as we've seen before. cc @foolip

**Comment by stephenmcgruer** [comment]
Did the version of Safari change? Looks like the last working run was against Safari 13.0.5, but I'm not sure where to find the version in Azure Pipelines...

The alternative is a change in WPT, the commit range for working --> broken is https://github.com/web-platform-tests/wpt/compare/d487329...bf43d14 . We'd probably need to bisect the list, maybe using trigger jobs if necessary.

**Comment by foolip** [comment]
One can throw in `safaridriver --version` in one of the steps Azure Pipelines .yml files to show what the Safari version in.

**Comment by Hexcles** [comment]
Sorry for the delay. I think I've found the culprit test: #21970 which is causing stable Safari to hang. I'm sending out a PR to exclude that test and see if it helps.

**Comment by Hexcles** [comment]
The immediate issue has been fixed by excluding this test on Safari stable, but we still don't know why this test is causing Safari to hang. Yet I don't want to spend too much time investigating it, because the test passes on STP so whatever issue has likely been fixed and the test will probably pass on a new Safari stable release.
