### ISSUE TITLE
[css-backgrounds] background-position-negative-percentage-comparison.html incorrect reference file 

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#22204]
@xiaochengh ,

[background-position-negative-percentage-comparison.html](http://wpt.live/css/css-backgrounds/background-position-negative-percentage-comparison.html)
uses
line 13: `background-position: min(0%, 100%) max(0%, 100%);`

and once parsed and resolved line 13 becomes

`background-position: 0% 100%;`

[CSS 2.2, background-position](https://www.w3.org/TR/CSS22/colors.html#propdef-background-position) states:
"
If at least one value is not a keyword, then the **first value** represents the **horizontal position** and the **second** represents the **vertical position**.
"

and

"
bottom
    Equivalent to '100%' for the vertical position. 
left
    Equivalent to '0%' for the horizontal position. 
"

The reference file 
[background-position-negative-percentage-comparison-ref.html](http://wpt.live/css/css-backgrounds/reference/background-position-negative-percentage-comparison-ref.html)
uses
line 9: `background-position: right top;`
when it **should use instead**
`background-position: left bottom;`
or even the safer
`background-position: 0% 100%;`

Another thing is there is no negative percentage anywhere in the test. I do not see why the adjective "negative" is in the filename of the test.

**Comment by xiaochengh** [comment]
Sorry for the delay.

I think the test is correct. In the test, `%` are resolved against negative values (as the background image is larger than the element), so we get `min(0%, 100%) = 100%`.

There are some discussions on whether we should change the behavior, though. See https://github.com/w3c/csswg-drafts/issues/4227.

**Comment by TalbotG** [comment]
Thank you for your comment. I will wait for a decision in 
https://github.com/w3c/csswg-drafts/issues/4227

**Comment by TalbotG** [comment]
[Issue 4227](https://github.com/w3c/csswg-drafts/issues/4227) was resolved without change. So, I'm closing this issue.
