### ISSUE TITLE
No way to fast-forward time in a test

### ISSUE THREAD

**Issue by chlily1** [web-platform-tests/wpt#22481]
I would like to test a feature with a timeout of 2 minutes, with different behavior before and after the timeout. It would probably work best to have a mock time that could be arbitrarily fast-forwarded, but unfortunately it seems there is no way to do this in a WPT.

**Comment by stephenmcgruer** [comment]
Seems like a dupe of https://github.com/web-platform-tests/wpt/issues/17489 ?

**Comment by chlily1** [comment]
Oh, yup. Thanks!
