### ISSUE TITLE
Missing Safari stable runs since April 1, 2020

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#22692]
No Safari stable run for 1 day so far: https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

SHA fd15aa3 is the run where Safari was missing. Here it is on Azure Pipelines: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=45005&view=logs&j=e8032fe0-b3da-5a76-081d-ec1db1bea50b

At first glance, the logs are showing: `CRITICAL Max restarts exceeded` which suggests there is a broken test that is hanging Safari (a similar recent case happened in #22373 

Next step is to try to identify the offending tests. Note that two test shards are affected here (Safari 2 and Safari 3)

**Comment by gsnedders** [comment]
13.1 release?

**Comment by gsnedders** [comment]
> 13.1 release?

No, unrelated. Same issue as previous Safari hangs: a context menu being opened. At least one of those cases is just #18995 occurring again, just on stable this time.

**Comment by gsnedders** [comment]
/pointerevents/pointerevent_pointercapture_in_frame.html needs ignored as well (c.f. #22175)
