### ISSUE TITLE
Add a test for the interchangeability of clearTimeout and clearInterval

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#2277]
Both in window and worker scope. See also https://github.com/whatwg/html/pull/282.

**Comment by zcorpan** [comment]
@nikkisquared are you also interested in writing a test case for this? I think it would be something like

    async_test(function(t) {
      var handle = setTimeout(t.step_func(function() {
        assert_unreached('Timeout was not canceled');
      }), 0);
      clearInterval(handle);
      setTimeout(function() {
        t.done();
      }, 100);
    });

and vice versa

**Comment by nikkisquared** [comment]
@zcorpan I would be interested in doing this! Where do I write test cases?

**Comment by jdm** [comment]
https://github.com/w3c/web-platform-tests#contributing has the high-level steps for contributing a change. https://github.com/w3c/web-platform-tests#finding-things suggests how to determine which directory to add the new test to. http://testthewebforward.org/docs/ has the full set of documentation that encompasses both of these.

**Comment by nikkisquared** [comment]
Thanks jdm! I'll read over all of these.

**Comment by nikkisquared** [comment]
Hello, sorry I haven't said anything here in the past three weeks. I've been trying to make time to get started on this, but it's just not happening. I'd rather say so then silently wait for inactivity to be assumed, so feel free to treat this as an open issue.
