### ISSUE TITLE
[hit-test][webxr] Floor transform is inverted in ar_hittest_subscription_refSpaces

### ISSUE THREAD

**Issue by Manishearth** [web-platform-tests/wpt#22900]
https://github.com/web-platform-tests/wpt/blob/f2e918abb4b8711afb28c8b98d98be3bffc9fa9a/webxr/hit-test/ar_hittest_subscription_refSpaces.https.html#L18-L22

https://github.com/web-platform-tests/wpt/blob/f2e918abb4b8711afb28c8b98d98be3bffc9fa9a/webxr/hit-test/ar_hittest_subscription_refSpaces.https.html#L27

This is incorrect, the testing API spec defines this as the origin of the floor, which means when represented as a transform it should be `(0, 0.25, 0)`, and should be equivalent to Chrome's `mojo_from_floor`, similarly to how viewerOrigin is `mojo_from_viewer`

cc @bialpio 

If Chrome passes this test, then there's a bug in their implementation cc @alcooper91

**Comment by alcooper91** [comment]
Hmm, If I invert our implementation such that the assigned values are mojo_from_floor
I get three tests that fail (e.g. are making the assumption that this floorOrigin is floor_from_mojo):
    external/wpt/webxr/hit-test/ar_hittest_subscription_refSpaces.https.html
    external/wpt/webxr/xrReferenceSpace_originOffsetBounded.https.html
    external/wpt/webxr/xrStationaryReferenceSpace_floorlevel_updates.https.html

Are you all running any of these tests? They'd likely have to be updated as well.

**Comment by Manishearth** [comment]
We currently don't do bounded/unbounded spaces. We fail the hit-test one and the floorlevel_updates one for this reason.

**Comment by alcooper91** [comment]
Thanks for the heads up. I filed https://crbug.com/1071630 to track the issue in Chrome, since it seems like you are correct.

**Comment by Manishearth** [comment]
https://github.com/web-platform-tests/wpt/pull/23272
