### ISSUE TITLE
[css-text-decor] Decoration in text-underline-position-from-font-variable specified on wrong element

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/wpt#22944]
The testcase text-underline-position-from-font-variable specifies `text-decoration: underline` on a `<div>`, then adjusts font settings on a child `<span>`, and expects the child's font settings to be reflected in the decoration line painted by its parent.

This works "as expected" in webkit-based browsers, but only because webkit handles inheritance and painting of decorations incorrectly per spec, as illustrated by the [`<u>A<sup>B</sup><big>C</big>D</u>` example in the spec](https://www.w3.org/TR/css-text-decor-3/#text-underline-position-property), which Safari and Chrome mis-render.

To correct the test, I suggest moving the `text-decoration: underline` property from the `test` class that is applied to the `<div>` to the `close_underline` and `far_underline` classes that are applied to the `<span>` elements; or apply the `close`/`far` classes directly to the `<div>` instead of to a child `<span>`.

@drott FYI, I'm working on a Firefox patch to respect variations applied to underline position/size metrics; will post in [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1629787) when ready. But your testcase still won't work as it stands because of this issue.

**Comment by drott** [comment]
Thanks for the suggestion, PR up.
