### ISSUE TITLE
Refactor and reorganize canvas 2d tests

### ISSUE THREAD

**Issue by mysteryDate** [web-platform-tests/wpt#22979]
Currently the folders `2dcontext` and `offscreen-canvas` have a ton of repeated tests and code. They each have a `/tools` folder that is _almost_ identical (stuff like [this](https://github.com/web-platform-tests/wpt/blob/master/offscreen-canvas/tools/gentest.py#L2) obviously isn't ideal). Each tools folder contains a 10,000 line `tests2d.yaml` file with auto-generated test code.
   A few things could be done to clean up:

1.  Create a top level `canvas` or `canvas2d` directory that contains the folders:
    * HTML
    * offscreen
    * tools
2.  Unify the tools directories.
3.  Split `tools/tests2d.yaml` into multiple files containing thematically similar tests.
4.  Many tests have been manually added and are not covered in the auto-generated tests, but could be. [For example](https://github.com/digitalbazaar/web-platform-tests/blob/master/2dcontext/compositing/canvas_compositing_globalcompositeoperation_001.htm). It would be good to move these to the same auto-generated flow.

Finally, offscreen canvas does not cover the case where [`transferControlToOffscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/transferControlToOffscreen) is used. Add those.

I'm going to begin this work in the chromium codebase.

cc: @fserb , @AmeliaBR , @annevk , @kenrussell

**Comment by mysteryDate** [comment]
Also, what about these tests: https://github.com/web-platform-tests/wpt/tree/master/html/semantics/embedded-content/the-canvas-element

I'd prefer to put everything in the new directory.

**Comment by fserb** [comment]
I'm not sure about calling the inner directory `HTML`. Maybe we could have all the top level types of tests as subdirectories (attached/element/dom, detached, offscreen, offscreen.worker, transferred, transferred.worker), instead of adding them on the test name.

Otherwise, I think this is a great idea.

Does anyone know if there's anything we should be looking for when moving a large number of tests like this?

Also adding @foolip to the thread.

**Comment by fserb** [comment]
I'd also be okey with keeping the `2dcontext` name as the top level one, moving OffscreenCanvas inside it, and moving the current subdirs one nested directory in.

**Comment by mysteryDate** [comment]
Ah, good point about the `html` subdirectory. 
I'm +1 for the subdirectory structure instead of the intensely long names. This would also be an obvious way to break up the `tests2d.yaml` files.

What do you mean by detatched? An HTMLCanvas that's not been added to the dom?

**Comment by annevk** [comment]
Overall this sounds great, thanks for taking this on!

I wonder if we should take this opportunity to move all of this into `/html/canvas/...` as it's technically part of the HTML Standard.

cc @domenic

**Comment by mysteryDate** [comment]
I'm for moving into `html/canvas`, it seems to be compatible with the guideline here: https://github.com/web-platform-tests/wpt/tree/master/html

In that case, I don't think it makes a ton of sense to keep these tests here: https://github.com/web-platform-tests/wpt/blob/master/2dcontext/tools/name2dir.yaml#L35

**Comment by guest271314** [comment]
> Does anyone know if there's anything we should be looking for when moving a large number of tests like this?

The automated tests should not be automated. An extra unecessary step when a test needs to be modified to look up and change or delete the automated test https://github.com/web-platform-tests/wpt/pull/19818, https://github.com/web-platform-tests/wpt/pull/21686. 

Last that checked `OffscreenCanvas` (and `transferControlToOffscreen()`) at Firefox is WIP https://bugzilla.mozilla.org/show_bug.cgi?id=1609238, https://bugzilla.mozilla.org/show_bug.cgi?id=1390089. 

The relevant specifications can clearly denote what a "broken" image is, and is not https://github.com/web-platform-tests/wpt/pull/21686.

How implenters of `createImageBitmap()` handle `Blob` input (and underlying image, re "broken", etc.) would be useful https://bugs.chromium.org/p/chromium/issues/detail?id=979890.

As an aside some form of test which measures the total duration of rendering using `createImageBitmap()`, et al. would be useful, as Chromium and Firefox implementations vary substantially in this regard https://github.com/fserb/canvas2D/issues/1, 

The above numbers were for incrementing currentTime by 1/60. seekToFrame() implementation at Nightly, Firefox appears to use 30 frames per second. Incrementing by 1/30 at rudimentary seekToNextFrame attempt at linked plnkr 

> Chromium 83
> 
> { originalVideoDuration: 41.582, elapsedTimeToSeekAllVideoFrames: 157.491 }
> 
> Nightly 76
> 
> { originalVideoDuration: 41.582, elapsedTimeToSeekAllVideoFrames: 40.4 }

https://bugs.chromium.org/p/chromium/issues/detail?id=1065675. E.g., running the code at https://plnkr.co/edit/k6Itrjzzj60vT2fC?preview takes observably more time at Chromium than Firefox for the "same" code (save for the Chromium `MediaRecorder` output issue where it is evidently not possible to seek to the "last" frame using `currentTime = duration` without calling `play()`).

To the extent applicable, a test to check the frame from `captureStream()` and `<MediaStream|MediaStreamTrack>.requestFrame()` is remotely similar to the frame passed when converting back to image data at `<canvas>`, or conclusively determine the limitations or if such an expectation for consistency is possible at all https://github.com/web-platform-tests/wpt/pull/22779.

**Comment by mysteryDate** [comment]
I'm not looking to change any tests with this PR, just re-organize them in hopefully a more helpful way.

> The automated tests should not be automated. An extra unecessary step when a test needs to be modified to look up and change or delete the automated test #19818, #21686.

Though I agree that it makes modification irritating, it does help a lot when we want to test the same behaviour for dom/detatched/offscreen/worker canvases, etc. Again, I don't really want to get into large scale test changes with this issue, just some reorganization/refactoring. 

What's bothersome is that there are some tests that are not autogen'd. I'll look into those later.

**Comment by foolip** [comment]
@web-platform-tests/wpt-core-team please note that some big renames are coming. I think this is a borderline case of needing the https://github.com/web-platform-tests/rfcs process but ultimately I'll not suggest it, since it only affects one (or two) features and is mainly a problem of handling the rename.

@stephenmcgruer @Hexcles is there any prep needed for this to roll smoothly into Chromium?

@jgraham how about Gecko?

@youennf how about WebKit? Also cc @grorg who I think has done a lot of work in canvas in WebKit, and might have thoughts.

**Comment by guest271314** [comment]
@foolip `OffscreenCanvas` is WIP in Firefox, currently not implemented that last time that checked.

**Comment by foolip** [comment]
I'll go ahead and merge https://github.com/web-platform-tests/wpt/pull/23070 now. If it does end up creating trouble for someone, please accept my apologies for not waiting longer. A huge PR like this will accumulate conflicts, so letting it sit for a long time also has its downsides. I'm confident from the positive reactions in this thread that the end result will be an improvement in everyone's eyes.
