### ISSUE TITLE
[webxr] Bug in webGLCanvasContext create xrcompatible

### ISSUE THREAD

**Issue by iBicha** [web-platform-tests/wpt#23030]
https://github.com/web-platform-tests/wpt/blob/c3c1ea4f28db4925e961b9b61fb079b98671b483/webxr/webGLCanvasContext_create_xrcompatible.https.html#L19

Should be `let offscreenGl = offscreenCanvas.getContext( `

**Comment by foolip** [comment]
@iBicha this should be a pretty simple fix, do you want to send a pull request?
