### ISSUE TITLE
[css-flexbox] justify-content: start/end/left/right not tested

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23059]
Going through https://css-tricks.com/snippets/css/a-guide-to-flexbox/ to learn me some basic flexbox (blush) this is the first thing I came across where I could get different rendering cross browser. Smallest case that shows it is:
```html
<div style="display:flex; justify-content: end">justify-content: end</div>
<div style="display:flex; justify-content: flex-end">justify-content: flex-end</div>
```
Try it at https://software.hixie.ch/utilities/js/live-dom-viewer/saved/7980

I've tested in recent Chrome, Edge 18, Firefox and Safari and found that only Firefox treats `justify-content: end` the same as `justify-content: flex-end`.

I don't know what behavior is correct because https://drafts.csswg.org/css-flexbox-1/#justify-content-property doesn't mention these keywords. But *some* behavior is correct and should be tested in WPT.

**Comment by foolip** [comment]
@tabatkins do you know what the correct behavior is?

**Comment by tabatkins** [comment]
'flex-end' is identical to either 'start' or 'end', depending on 'flex-direction'. In this case, it must be identical to 'end'.  (And when used outside of flex contexts, it's always equivalent to 'end'.

See <https://drafts.csswg.org/css-align/#valdef-self-position-flex-start> for definitions.

**Comment by foolip** [comment]
Thanks @tabatkins! If that's the case, then adding these missing tests should be quite trivial.

**Comment by meyerweb** [comment]
start/end are covered by #26404, but left/right are not (as per @davidsgrogan).  I’m planning to add left/right tests, potentially modeled on the start/end tests from #26404.

**Comment by meyerweb** [comment]
This seems to have been completed due to the merging of https://github.com/web-platform-tests/wpt/pull/28119.

**Comment by foolip** [comment]
Excellent, thank you @meyerweb! I see that the [added tests](https://wpt.fyi/results/css/css-flexbox?label=pr_head&max-count=1&pr=28119) fail in Chrome and Safari, so this will help get that fixed :)

**Comment by meyerweb** [comment]
@foolip Check again once my latest pull request is merged (https://github.com/web-platform-tests/wpt/pull/28152).  I messed up on the last PR, pushing incorrect test versions, and I don’t believe Chrome and Safari actually fail.  It’s Firefox that needs the work.
