### ISSUE TITLE
CSS transform and stacking contexts

### ISSUE THREAD

**Issue by frehner** [web-platform-tests/wpt#23099]
This is my first issue opened here - let me know if I missed anything or misunderstood anything.

### Issue
I've noticed different behavior between Firefox vs Safari/Chrome/Edge in the following situation:

If an element has `transform: translate` it [should create](https://www.w3.org/TR/2020/WD-css-transforms-2-20200303/#individual-transforms) a new stacking context without needing any other properties. 

Given two sibling elements, the first element has a `z-index: 2` which means that any overlapping content it has should be painted on top of the second element (which doesn't have a `z-index`)

Here is a codepen example https://codepen.io/afrehner/pen/oNjXWwm

From my understanding, the blue background div should be on top of the red background div

If what I wrote above is true, then Firefox is the only browser to correctly implement this behavior. For Safari/Chrome/Edge, the red background div is on top

### P.S. 

If all of this looks correct, I would love to write the test for this as well. I've been trying to get  involved in this repo but have yet to write a CSS test, so I may need a little direction on how to best proceed. Thank you :)

**Comment by stephenmcgruer** [comment]
cc @flackr and @kevers (Chromium animation team) who likely can determine the correct behavior for the codepen and whether there is (a) an existing Chrome bug for it, and (b) an existing WPT for it.

**Comment by birtles** [comment]
@hiikezoe has done a bunch of tests for stacking context behavior with regards to animations so he might know if there is an existing test for this.

**Comment by hiikezoe** [comment]
I haven't written such test cases ever. And it seems to me that the case is not related to animation stuff.  You can see the different behavior even if you replace the CSS animation style with `transform: translateX(0px)` or some such.

**Comment by birtles** [comment]
I was thinking of all the tests you did for stacking contexts in [CSS animations](https://searchfox.org/mozilla-central/source/layout/reftests/css-animations) and [Web Animations](https://searchfox.org/mozilla-central/source/layout/reftests/web-animations) but it looks like none of those ever made their way into WPT.

**Comment by frehner** [comment]
>I haven't written such test cases ever. And it seems to me that the case is not related to animation stuff. You can see the different behavior even if you replace the CSS animation style with transform: translateX(0px) or some such.

great point - that simplifies things a bit. I've updated the title and the description to reflect this. Thanks!

**Comment by birtles** [comment]
Should the title refer to transforms instead of transitions?

**Comment by hiikezoe** [comment]
> I was thinking of all the tests you did for stacking contexts in [CSS animations](https://searchfox.org/mozilla-central/source/layout/reftests/css-animations) and [Web Animations](https://searchfox.org/mozilla-central/source/layout/reftests/web-animations)

Sorry for the confusion. "Such cases" I meant is cases using "z-index".  To me the test is quite normal, what I've written are a bunch of corner cases on interactions with animations as you know.

> but it looks like none of those ever made their way into WPT.

Yeah. We have a plan to migrate our in-tree _pagination_ reftests into WPT, if I have enough time I will migrate some animation related reftests into WPT as well.

**Comment by stephenmcgruer** [comment]
I can find 5 tests in `css/css-transforms` which refer to stacking context in their name, all of which pass on both Chrome and Firefox: https://wpt.fyi/results/css/css-transforms?label=master&label=experimental&aligned&q=stacking

That said, there are definitely known bugs in Chromium for stacking context, e.g. https://bugs.chromium.org/p/chromium/issues/list?q=stacking%20context&can=2, and stacking context is a *big* topic. It may be worth just opening a Chromium bug with your reproduction (https://crbug.com/new), and see if the experts there can triage it to an existing case. This may also inform whether or not there is already coverage in WPT for such a case.

**Comment by kevers** [comment]
Not me y'all. Wrong person. Good luck though!

**Comment by flackr** [comment]
I'm not sure if Firefox's behavior here is correct to spec. The spec indicates that [z-index](https://www.w3.org/TR/CSS2/visuren.html#z-index) only applies to positioned elements but the element #one has not been positioned even though it is a stacking context.

**Comment by flackr** [comment]
Doing a quick scan of wpt/css/css-transform it looks like we don't have any tests which set z-index without also setting position to something other than static.

Curiously, if we look at the computed style of z-index, we can see some really inconsistent behaviors when [transform and z-index are applied](https://jsbin.com/jojacik/1/edit?html,css,js,output). 

getComputedStyle of z-index given input style:
|           | z-index | chromium | firefox | safari |
|-----------|--|----------|---------|--------|
| static    | 1 | auto     | 1       | auto   |
| transform | auto | auto        | auto       | 0      |
| transform | 1 | 0        | 1       | 0      |
| position  | 1 | 1        | 1       | 1      |

**Comment by frehner** [comment]
>Curiously, if we look at the computed style of z-index, we can see some really inconsistent behaviors when transform and z-index are applied.

ah interesting, good test. 

But I think I get different results than you do for safari?

|           | zindex | chrome 83.0.4103.14 | firefox 76.0b5 | safari 13.1 + STPreview 104 |
|-----------|--------|---------------------|----------------|-----------------------------|
| static    | 1      | auto                | 1              | 1                           |
| transform | auto   | auto                | auto           | auto                        |
| transform | 1      | 0                   | 1              | 1                           |
| position  | 1      | 1                   | 1              | 1                           |

**Comment by flackr** [comment]
Interesting, I tested on Safari 13.0.2, perhaps the behavior has changed quite recently.

**Comment by emilio** [comment]
getComputedStyle should be just the specified value, that is a chrome bug that Safari fixed. https://bugs.chromium.org/p/chromium/issues/detail?id=1023232

**Comment by hiikezoe** [comment]
> I'm not sure if Firefox's behavior here is correct to spec. The spec indicates that [z-index](https://www.w3.org/TR/CSS2/visuren.html#z-index) only applies to positioned elements but the element #one has not been positioned even though it is a stacking context.

I found there is [a bug in Gecko](https://bugzilla.mozilla.org/show_bug.cgi?id=1256980), it looks like the same root cause.

**Comment by frehner** [comment]
I created a PR to add a test for this. See #23663 

:)

**Comment by smfr** [comment]
Agreed that z-index should not apply to transformed elements that have static position.

**Comment by frehner** [comment]
It appears a test for this was added in #24406 . Closing this issue, and the linked PR I had created as well.
