### ISSUE TITLE
*.any.js global defaulting is confusing

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#23111]
It's not clear to me that folks reading or writing `global=worker,jsshell` expect this to also apply to `window`.

https://web-platform-tests.org/writing-tests/testharness.html#multi-global-tests is quite clear on this, but I would rather have folks explicitly state their expected environments.

I could see making an exception when the `global` keyword is missing entirely though.

**Comment by stephenmcgruer** [comment]
To clarify for anyone else reading this, I believe today the behavior is that you **always** run in the `default` (window and dedicated worker) scopes, unless you specify `!default`, `!window`, and/or `!dedicatedworker`.

Which is quite non-intuitive to me; if you write any `global=` then I think I'd expect it to run only in those cases. I can find *many* cases of `global=window,worker` in the codebase today, which I think implies others think like that too?

I think https://github.com/web-platform-tests/wpt/pull/6792 is what originally landed the behavior, I don't see much of a discussion on it over a quick skim.

I would be personally happy to see us switch to it being explicit if there's a `global=`, though it may be a medium-sized project (also, would it require an RFC?). There are ~300 cases of `META.*global` that I can find in the codebase today and each would need to be considered for the right behavior. Albeit there's only ~30 unique patterns so maybe we could just do large-scale replacements to maintain current behavior.

**Comment by annevk** [comment]
Yes, correct.

I think we should get rid of `default` and the `!` variants, and do a couple of replace operations as you suggest. If you omit all you still get `window,dedicatedworker` going forward.

I don't think this kind of cleanup should need an RFC, but happy to defer that question to @jgraham.

**Comment by Ms2ger** [comment]
This seems fine, but I do think it needs an rfc.
