### ISSUE TITLE
idlharness.js does not handle newly renamed extended attributes

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#23148]
WebIDL just renamed a bunch of attributes in https://github.com/heycam/webidl/pull/870, and the upstream changes have started rolling in:

- https://github.com/web-platform-tests/wpt/pull/23124
- https://github.com/web-platform-tests/wpt/pull/23128

Since idlharness doesn't know about these, these changes introduce errors.

My plan is to tackle the attributes as they appear in imported IDL files, rather than try to get ahead of them.

**Comment by stephenmcgruer** [comment]
So LegacyNoInterfaceObject is not supported still, but all the rest are and we have no specs that use `LegacyNoInterfaceObject`. I'm happy to leave that until we someday get a spec that uses it.

**Comment by foolip** [comment]
If no specs currently use `LegacyNoInterfaceObject` then probably none ever will. The only spec left in reffy-reports (ed) using `NoInterfaceObject` (the "legacy" name of `LegacyNoInterfaceObject` :D) is svg-paths.idl, being added in https://github.com/web-platform-tests/wpt/pull/23869. It'd probably be best to fix that at the source and then just drop support for `NoInterfaceObject` from WPT.

**Comment by foolip** [comment]
I've sent https://github.com/w3c/svgwg/pull/802 for that.
