### ISSUE TITLE
XHR and fetch tests for redirect-to-cors behaviour don't match

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#23156]
https://github.com/web-platform-tests/wpt/pull/5070 introduced tests for making an XHR to a cross-origin URL that redirects when there is a POST body with a non-default Content-Type present. These tests (in [xhr/send-redirect-to-cors.html](https://github.com/web-platform-tests/wpt/blob/master/xhr/send-redirect-to-cors.htm)) assert that the Content-Type remains unmodified after the redirection.

Following a long trail from https://github.com/whatwg/fetch/issues/609 (which was fixed by https://github.com/whatwg/fetch/pull/977) that introduced explicit behaviour to change POST to GET and remove any Content-Type value, I see https://github.com/web-platform-tests/wpt/pull/20596/ which added tests in [fetch/api/redirect/redirect-method.any.js](https://github.com/web-platform-tests/wpt/blob/master/fetch/api/redirect/redirect-method.any.js) that assert that the Content-Type is removed from the redirected request.

We are now in the strange situation where:
* all browsers [pass](https://wpt.fyi/results/xhr/send-redirect-to-cors.htm?label=master&label=experimental&aligned&q=send-redirect-to-cors.htm) send-redirect-to-cors.htm
* most browsers [pass](https://wpt.fyi/results/fetch/api/redirect/redirect-method.any.html?label=master&label=experimental&aligned&q=redirect-method) redirect-method.any.html
* the XHR specification delegates to the Fetch specification for the actual relevant behaviour

What do we do about this state of affairs? In Gecko's case the Fetch and XHR code paths are completely different which explains how both tests can pass; I don't know enough about other browsers to state if they're in the same boat.

cc @annevk

**Comment by annevk** [comment]
@rwlbuis @JuniorHsu @yutakahirano this might interest you. Safari is consistent in not stripping in either place. (This is a bug, but maybe once fixed it'll fix both at once.) Both Chrome and Firefox seem buggy in that they have different behaviors between fetch and XHR. I'll send a PR for the XHR test and file bugs.
