### ISSUE TITLE
Tests for URLSearchParams.

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#2322]
@mikewest promised to submit Gecko's tests

https://mxr.mozilla.org/mozilla-central/source/dom/base/test/test_urlSearchParams.html?force=1
https://mxr.mozilla.org/mozilla-central/source/dom/base/test/test_urlSearchParams_utf8.html?force=1
https://mxr.mozilla.org/mozilla-central/source/dom/base/test/test_bug1064481.html?force=1
https://mxr.mozilla.org/mozilla-central/source/dom/workers/test/test_urlSearchParams.html?force=1
Maybe https://mxr.mozilla.org/mozilla-central/source/dom/workers/test/test_bug1060621.html?force=1

**Comment by Ms2ger** [comment]
@mikewest submitted a bunch of tests in #2326; I should check if he covered everything at some point.

**Comment by mikewest** [comment]
I don't think it's everything, but it's a large chunk of what the Mozilla tests cover. https://mxr.mozilla.org/mozilla-central/source/dom/base/test/test_urlSearchParams_utf8.html?force=1 is missing, as is the `URL::searchParams` attribute.

**Comment by annevk** [comment]
@Ms2ger still interested in deduplicating this? I'm happy to add/write WPT tests if you can remove the Gecko-specific tests.

**Comment by GPHemsley** [comment]
What's the current status of this issue?

**Comment by annevk** [comment]
It hasn't changed, I think. All those files still exist in https://searchfox.org/mozilla-central/source/dom/url/tests/.

**Comment by annevk** [comment]
I'm going to close this. If someone at Mozilla wants to deduplicate this they should go for it, but I haven't seen reports of an implementation difference in the past eight years that makes that seem worth doing.
