### ISSUE TITLE
Use webdriver to mimic human interaction in tests

### ISSUE THREAD

**Issue by johanneswilm** [web-platform-tests/wpt#23261]
According to the list of test types [1], webdriver tests are only there to test the webdriver protocol. It's not possible to use webdriver to mimic human interaction to test other things. For Input Events and contenteditable, it would be very helpful if we could create webdriver tests to test whether browsers adhere to the relevant specification.

For example, I have written these automated tests for Input Events [2] that I cannot convert to WPT tests because there is no way to mimic human interaction, as far as I can tell.

Part of this issue was previously mentioned in another issue [3] that other than this seems to be largely resolved.

@marcoscaceres I believe this is the only issue that stops me from creating the needed WPT tests.

[1] https://web-platform-tests.org/writing-tests/index.html#test-type

[2] https://github.com/johanneswilm/input-events-testing/blob/master/tests/basic.test.js

[3] https://github.com/web-platform-tests/wpt/issues/13464

**Comment by stephenmcgruer** [comment]
You are correct that `wdspec` tests (which mostly live in `webdriver/`) exist to test WebDriver implementations in browsers.

[testdriver.js](https://web-platform-tests.org/writing-tests/testdriver.html) is our mechanism for allowing tests to use the WebDriver protocol to perform tasks that cannot be performed via web platform APIs, including human input. It either provides or can be extended to provide access to any of the spec'd and implemented WebDriver APIs.

Does testdriver.js cover your needs, or have I misunderstood your question?

**Comment by johanneswilm** [comment]
@stephenmcgruer Indeed, looking at that, it seems to do all we need. I'll close this issue and reopen only in case there is something missing. Thanks!
