### ISSUE TITLE
No way to add .headers for .any.js tests

### ISSUE THREAD

**Issue by RReverser** [web-platform-tests/wpt#23268]
I'm trying to add an `[testname].any.js` test that relies on certain headers set on the page, but struggling.

It seems that `[testname].any.js.headers` applies to `[testname].any.js` itself, and even manual expansions to `[testname].any.html.headers` and `[testname].any.worker.html.headers` are ignored even though match names of autogenerated HTMLs.

/cc @Ms2ger

**Comment by Ms2ger** [comment]
The autogenerated "files" are produced by `tools/serve`'s `WrapperHandler`, with headers added here: https://github.com/web-platform-tests/wpt/blob/896db568c3008976ce9754c0cfd8b3362f8ed9d9/tools/serve/serve.py#L74-L76

The `.headers` support is in `tools/wptserve`'s FileHandler here: https://github.com/web-platform-tests/wpt/blob/896db568c3008976ce9754c0cfd8b3362f8ed9d9/tools/wptserve/wptserve/handlers.py#L180-L206

It seems like it should not be an unreasonable amount of work to factor the latter code out of the `FileHandler` class (it doesn't depend on `self`) and make `WrapperHandler` use it.

**Comment by hiroshige-g** [comment]
Related to (and maybe fixed by): https://github.com/web-platform-tests/wpt/pull/26014

**Comment by Ms2ger** [comment]
Thanks for the pointer, looks like it's working indeed.
