### ISSUE TITLE
Not found (MISSING) textpath-selection-011 test 

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#23271]
@web-platform-tests/wpt-core-team 
Dear fellow wpt colleagues,

[textpath-selection-011 test result](https://wpt.fyi/results/css/css-pseudo/textpath-selection-011.html?label=experimental&label=master&aligned)
reports "MISSING" but
[textpath-selection-011.html](http://wpt.live/css/css-pseudo/textpath-selection-011.html)
[textpath-selection-011-ref.html](http://wpt.live/css/css-pseudo/textpath-selection-011-ref.html)
prove that the test and reference file exist. Test and reference file were merged thanks to 
https://github.com/web-platform-tests/wpt/pull/20033
So why the "MISSING" test result report? What am I doing wrong? What should I do to neutralize or counter the "MISSING" error message?

**Comment by stephenmcgruer** [comment]
The text appears to be missing a 'match' link element; see https://web-platform-tests.org/writing-tests/reftests.html#components-of-a-reftest 

So in this case, `textpath-selection-011.html` would need a link in it something like:

`<link rel="match" href="textpath-selection-011-ref.html">`

Without this, wpt infra cannot tell that this test is a reftest (or any type of test), so it doesn't attempt to run it.

**Comment by TalbotG** [comment]
@stephenmcgruer Thank you, thank you and thank you! I stared at this for hours and never saw the obvious. 
By the way, I am from Québec, Canada :)

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer Thank you, thank you and thank you! I stared at this for hours and never saw the obvious.

No problem - looking at the documentation I think it could be clearer (and I also discovered we have two pages for documenting writing reftests...). Documentation is such a tricky thing :)
