### ISSUE TITLE
Document tentative directories

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23300]
https://github.com/web-platform-tests/wpt/pull/7663 introduced the .tentative file name flag, and since then lots of files have begun to use this convention.

However, we also have 3 directories containing "tentative":
- [css/css-grid/masonry.tentative](https://github.com/web-platform-tests/wpt/tree/3320205a9d70636efc03cfff340edecd0bee4694/css/css-grid/masonry.tentative) added in https://github.com/web-platform-tests/wpt/pull/23286
- [custom-elements/state.tentative](https://github.com/web-platform-tests/wpt/tree/3320205a9d70636efc03cfff340edecd0bee4694/custom-elements/state.tentative) added in https://github.com/web-platform-tests/wpt/pull/21541
- [websockets/stream-tentative](https://github.com/web-platform-tests/wpt/tree/3320205a9d70636efc03cfff340edecd0bee4694/websockets/stream-tentative) added in https://github.com/web-platform-tests/wpt/pull/18335

This is obviously convenient when there are a lot of tentative tests in a group, but it's something we haven't documented, and the naming convention has already diverged.

@web-platform-tests/wpt-core-team FYI

**Comment by jgraham** [comment]
I don't think I mind these existing; I might start using the tentative flag to change the `implementation-status` default from `implementing` to `backlog` (which in practice will mean that gecko CI doesn't run the tests by default in try and on the pre-integration branches).

**Comment by stephenmcgruer** [comment]
I also recently instructed someone working on a large rework of a spec to use a `tentative` directory (in this case, I suggested `css/css-tables/tentative/`!) until they could get the spec changes in.

We should document *something*, though tentative is such a unique word (unlikely to be used by accident) that I'm tempted to just say "if 'tentative' is in the WPT-root-relative path at any point, the test is tentative" ;).

**Comment by jgraham** [comment]
The literal directory name `tentative` seems closest to the solutions we currently support for other things (e.g. support). But in that case we'd want to move the existing tests which are using the `foo.tentative` directories to `foo/tentative`

**Comment by stephenmcgruer** [comment]
> But in that case we'd want to move the existing tests which are using the foo.tentative directories to foo/tentative

Moving them SGTM; there are only 3 such directories today (the ones Philip mentioned) so it would be good to get out ahead of more being added. 

Do you think needs a short RFC @jgraham ?


(cc @MatsPalmgren @tkent-google @ricea as an FYI that we're discussing slightly renaming the tentative directories y'all recently added. Feel free to object :))

**Comment by Ms2ger** [comment]
Would we then end up with only a `tentative` folder in `css/css-grid/masonry/`, or have a `css/css-grid/tentative` that only contains masonry tests, or put masonry tests and random other tests directly in `css/css-grid/tentative`?

Perhaps it would make sense to keep the `foo/bar.tentative` dirs for a new `bar` feature in an existing `foo` spec, and also support `foo/tentative` for cases where `foo` doesn't specify its existing behaviour very well (like css-tables).

**Comment by ricea** [comment]
I support this. Either `websockets/stream/tentative/` or `websockets/tentative/` would be fine. I have a mild preference for the former as it is more explicit.

**Comment by domenic** [comment]
My minor preference is for directories with `.tentative` in their name. A lot of tests these days are being written by adding a directory with entirely `.tentative.html` tests. That could be cleaned up by allowing tentative directories, but I think `spec/feature.tentative` is simpler than `spec/feature/tentative` where `spec/feature/` is otherwise-empty.

So, I think I am seconding @Ms2ger.

**Comment by foolip** [comment]
`feature.tentative` sounds good to me. I'll send a PR to rename `websockets/stream-tentative`, but this still needs to be documented.

**Comment by stephenmcgruer** [comment]
In terms of infra changes; we currently use `tentative` in one file lint (I added it recently), and that is it for WPT. wpt.fyi does have an `is:tentative` search atom that would also need updated (cc @Hexcles ).

It seems like by force of @foolip caring to do something about it, we're settled on `foo/bar.tentative/`? Any objections to that being the *only* supported way to name tentative directories? (Or should we also support `foo/bar/tentative/`?)

**Comment by foolip** [comment]
I'd prefer just a single way to name tentative directories: `foo/bar.tentative/`

One doubt I have is whether we should allow top-level directories to be called `foo.tentative` in case there's not a single normative test inside.

**Comment by stephenmcgruer** [comment]
> I'd prefer just a single way to name tentative directories: foo/bar.tentative/

Sounds good to me. I'm happy to add a lint enforcing this (e.g. for all non-file components in a path, if it contains the word 'tentative' it must end with `.tentative`... which will allow `tentative.tentative` but I really don't care that much :p).

> One doubt I have is whether we should allow top-level directories to be called foo.tentative in case there's not a single normative test inside.

Let's just say 'sure' for now, and cross that bridge if we ever actually come to it. I suspect folks will generally shy away from such naming.

**Comment by stephenmcgruer** [comment]
Just noting that as https://github.com/web-platform-tests/wpt/pull/24114 has evolved, we've moved away from `foo.tentative` and towards `foo/tentative/`. The former uncovered strange pain like renaming `css-tables/tentative/` to `css-tables/tables.tentative/`, which seemed not great.
