### ISSUE TITLE
[testharness.js] Deferring timeouts while subtest results are being produced

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#23326]
Currently, testharness.js tests are labeled as "timed out" if they do not finish running subtests within one of [two possible durations: "normal" and "long"](https://github.com/web-platform-tests/wpt/blob/31da90bff3d6fd5cd8169b924125b3253b438ec4/resources/testharness.js#L22-L25). This has a couple negative consequences.

Actual testing durations are not as consistent as these two options suggest, and careful authors are likely to prefer the "long" option to avoid false negatives. At scale, this tendency may have a non-trivial impact on overall test execution times (where non-conforming browsers require more time to fail).

Some authors want to run many subtests organized under one logical test. Although the individual tests may be relatively quick, their number may push the test's execution time over the limit. Here, authors have to split their subtests across many files, creating subtests based on anecdotal evidence of what seems to be "fast enough" to satisfy the duration restriction in their environment. In the interest of limiting duplication, [this is sometimes implemented using methods which detract from readability](https://github.com/web-platform-tests/wpt/pull/11028).

I believe the spirit of the harness's restriction is to detect and recover from cases where testing has unexpectedly halted. However, the harness currently ignores a signal that testing is indeed active: the reporting of subtest results. If the harness extended the timeout following every subtest result, it would be no less capable of detecting timeouts, and authors would no longer need to manage this expectation. It would also reduce waste (since the contextual timeout value of "10 seconds after the last subtest" is likely shorter than the static timeout value of "60 seconds").

One risk comes to mind, specifically from procedurally-generated subtests. Bugs in test code (or in browser code) could cause more subtests to be produced than intended. This could cause the harness to wait far longer than intended (even indefinitely). We could avoid this by making the behavior opt-in and by requiring the specification of the expected number of subtests. One the surface, we'd be trading one kind of configuration ("normal" versus "long") with another (number of subtests), but the latter doesn't require any guesswork about subtest duration--authors would be configuring in terms that are objectively defined by the code they've written.

/cc @zcorpan @MikeWest @gsnedders @jgraham

**Comment by stephenmcgruer** [comment]
This feels like it should be an RFC issue (not important, we can transfer it there later if we want), but more importantly it feels like a /cc @web-platform-tests/wpt-core-team rather than an explicit list of folks :)

**Comment by zcorpan** [comment]
Why did we go with 10s / 60s originally? The proposal here seems more robust, and removes the need for splitting tests with many subtests.

We could still have the `long` indicator, for cases where a single subtest takes a long time.

To tackle the infinite subtests scenario, maybe there could be a fixed maximum timeout of a few minutes?

**Comment by jugglinmike** [comment]
Thanks for the advice, @stephenmcgruer. In the interest of promoting discussion (and starting the 1-week RFC process), I've submitted this as [RFC 53: Introduce more robust mechanism for testharness.js timeout detection](https://github.com/web-platform-tests/rfcs/pull/53). That makes this issue superfluous. (Not to worry, @zcorpan: I've carried over your feedback.)
