### ISSUE TITLE
Unrecognized type "Function" in my idlharness tests

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#23329]
In #22982, I have the IDL

```webidl
[Exposed=(Window,Worker,Worklet)]
interface CountQueuingStrategy {
  constructor(QueuingStrategyInit init);

  attribute unrestricted double highWaterMark;
  readonly attribute Function size;
};
```

but idlharness gives me

CountQueuingStrategy interface: new CountQueuingStrategy({ highWaterMark: 5 }) must inherit property "size" with the proper type | Unrecognized type Function
-- | --

errors. `Function` is [built in to Web IDL](https://heycam.github.io/webidl/#Function). How do I get idlharness to recognize it?

**Comment by stephenmcgruer** [comment]
Looks like this comes from `IdlArray.prototype.assert_type_is` - `Function` might not be in the big list of accepted types there. (I don't see it offhand). I can get to this sometime in the next week, or PRs welcome (though idlharness is quite intimidating, at least to me!)
