### ISSUE TITLE
Deployments are not cleaned up when they're taken down

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23335]
https://github.com/web-platform-tests/wpt/deployments lists many deployments for pull requests, some of which don't exist any more. For example:
![image](https://user-images.githubusercontent.com/498917/80687453-9c634600-8aca-11ea-8a8a-43e77855a937.png)

This links to https://wptpr.live/22524 which is 404.

This shows up as "254 environments" in https://github.com/web-platform-tests/wpt:
![image](https://user-images.githubusercontent.com/498917/80687336-6faf2e80-8aca-11ea-8df1-ca154b89b815.png)

@stephenmcgruer

**Comment by stephenmcgruer** [comment]
Tch, fun. [The deployment script](https://github.com/web-platform-tests/wpt/blob/master/tools/ci/pr_preview.py) in theory was meant to clean up after itself, though I must admit right now I am having trouble finding where...

Setting roadmap - I may not get to this until mid-May, but we should look at it. Let me know if there's an urgency to this I'm unaware of.

**Comment by foolip** [comment]
There's no urgency, it's just something I noticed.

**Comment by foolip** [comment]
@stephenmcgruer this came up on the rotation tool.

With the GitHub redesign I can't see a deployment count anywhere, but https://github.com/web-platform-tests/wpt/deployments still has a lot. It's also worth noting the many pending deployments, which aren't really pending, but cases where something went wrong.

**Comment by stephenmcgruer** [comment]
I wonder if https://github.com/web-platform-tests/wpt/pull/24768 may have fixed this? I see only ~30 deployments when I query the list-deployments API for wpt now, but I haven't dug further to confirm that everything is working correctly yet.

**Comment by stephenmcgruer** [comment]
Assuming fixed by https://github.com/web-platform-tests/wpt/pull/24768
