### ISSUE TITLE
idlharness.js's assert_type_is needs to be taught about each interface

### ISSUE THREAD

**Issue by inexorabletash** [web-platform-tests/wpt#23346]
As noted in e.g. https://github.com/web-platform-tests/wpt/pull/23323#issuecomment-621677647 the idlharness assertion `assert_type_is()` needs to be explicitly made aware of interfaces like Float32Array and DataView. If an interface isn't listed, it leads to unexpected failures. 

We likely haven't noticed this much because most idlharness tests are boilerplate and don't provide sample values. Even after the above PR, grepping for the error in blink's output, I found some geometry-related fails: `" Unrecognized type"` --> DOMRect, DOMRectReadOnly, DOMPointReadOnly, DOMMatrix

Can we update `assert_type_is()` to have `value instanceof self[type]` as the default case? (Honest question: I didn't look deeply enough to see what the downsides are)

cc: @foolip

**Comment by domenic** [comment]
This is similar to (but not quite the same as) https://github.com/web-platform-tests/wpt/issues/23329, in particular your reference to the built-in types like Float32Array.

Note that those types aren't interfaces, though.

**Comment by inexorabletash** [comment]
Yeah, cc: @stephenmcgruer too

**Comment by stephenmcgruer** [comment]
That seems like a reasonable default to me; I can own landing that change.
