### ISSUE TITLE
ruby-position tests upstreamed from Chromium are incorrect

### ISSUE THREAD

**Issue by upsuper** [web-platform-tests/wpt#23386]
The tests upstreamed in #23221 fails on Firefox, and after inspecting the test, I believe there are two tests that are actually incorrect.

According to the [spec](https://drafts.csswg.org/css-ruby-1/#rubypos), `ruby-position` only applies to ruby annotation containers, but there are two tests try to check it on `<rt>` which is ruby annotation, and thus should not be effective.

Please take a look, thanks.

cc @tkent-google @kojiishi

**Comment by tkent-google** [comment]
You're right.  it should be applied to ruby annotation **container** boxes (`<rtc>`), not ruby annotation boxes (`<rt>`).  I'll fix this.
