### ISSUE TITLE
class-string-named-properties-object.window.js using [DefineOwnProperty]

### ISSUE THREAD

**Issue by evilpie** [web-platform-tests/wpt#23391]
This test introduced with #23140 by @domenic seems to call `[[DefineOwnProperty]]` on the window named properties object. Per [this spec](https://heycam.github.io/webidl/#named-properties-object-defineownproperty) and the implementation in Firefox this will always throw.

```
Object.defineProperty(namedPropertiesObject, Symbol.toStringTag, { value: "NotWindowProperties" });
```

**Comment by domenic** [comment]
Thanks! I guess we should delete that test; sorry about that.

**Comment by evilpie** [comment]
Can someone open a Chrome bug for this? Seems like Chrome's implementation of tne named properties object doesn't follow the spec in some other places. Chrome apparently implements expando properties. ([per](https://phabricator.services.mozilla.com/D72179#inline-423307) @TimothyGu)

**Comment by domenic** [comment]
I think the first step would be to write (or find?) some web platform tests so we can get a more complete picture of browser behavior and what bugs there are on file...

**Comment by shvaikalesh** [comment]
> I think the first step would be to write (or find?) some web platform tests so we can get a more complete picture of browser behavior

#27970 attempts to do this, and also adds tests for https://github.com/heycam/webidl/pull/963, which argues that symbol properties should be allowed on named properties objects.
