### ISSUE TITLE
GitHub Actions manifest workflow occasionally fails to create merge_pr_* tags and upload manifest

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23426]
This is a continuation of https://github.com/web-platform-tests/wpt/issues/10572, which tracked the same issue occasionally happening with Travis. In https://github.com/web-platform-tests/wpt/pull/15781 the responsibility for tagging master and uploading manifests was moved to GitHub actions and it has been fairly reliable, but not 100%.

[check.js](https://gist.github.com/foolip/21391a51977d199fa0509b0c4dfdbe13) is a script checking for missing tags and manifests. It takes a long time to run, but it looks ~1-3% of tags are missing. Since it's caused by flaky infrastructure, it won't be evenly distributed in time.

Here are the 10 higher PR numbers with missing tags right now:
- https://github.com/web-platform-tests/wpt/pull/23385: no checks ran
- https://github.com/web-platform-tests/wpt/pull/23369: [run](https://github.com/web-platform-tests/wpt/runs/637380261) failed to find PR for commit
- https://github.com/web-platform-tests/wpt/pull/23367: [run](https://github.com/web-platform-tests/wpt/runs/637847696) failed because the duplicate https://github.com/web-platform-tests/wpt/pull/23366 was already merged
- https://github.com/web-platform-tests/wpt/pull/23330: [run](https://github.com/web-platform-tests/wpt/runs/631874933) failed to find PR for commit
- https://github.com/web-platform-tests/wpt/pull/23321: GitHub Actions didn't run, but other CI did
- https://github.com/web-platform-tests/wpt/pull/23308: [run](https://github.com/web-platform-tests/wpt/runs/630399327) failed to find PR for commit
- https://github.com/web-platform-tests/wpt/pull/23269: no checks ran
- https://github.com/web-platform-tests/wpt/pull/23247: [run](https://github.com/web-platform-tests/wpt/runs/627287369) failed to find PR for commit
- https://github.com/web-platform-tests/wpt/pull/23214: [run](https://github.com/web-platform-tests/wpt/runs/613474141) failed to find PR for commit
- https://github.com/web-platform-tests/wpt/pull/23193: [run](https://github.com/web-platform-tests/wpt/runs/612798199) failed to find PR for commit

So it's a mix of issues, but mostly "failed to find PR for commit". I checked 3 or 4 cases like [this](https://api.github.com/search/issues?q=type:pr+is:merged+repo:web-platform-tests/wpt+sha:f45a863ddfa513bdb3348eb8a9e095dfacc8b68b) and now the API does return a PR.

**Comment by stephenmcgruer** [comment]
@foolip I'm not clear scanning the original issue - what is the impact of these being missing?

**Comment by foolip** [comment]
The tags are used by `./wpt rev-list` so two things can happen there:
- If the commit was going to be the next points for an `epochs/*` branch, either a run will be missed, or an earlier commit will be used, depending on whether there have been other tagged commits since the last point. In either case, it's adding some amount of latency from commit to full results on wpt.fyi.
- When the tag is added, it will change what `./wpt rev-list` does, and so could trigger additional full runs (if added quickly) or later confuse metrics/monitoring (if added later)

The releases are used by `./wpt manifest`, so if enough manifests in a row are missed, it would start generating the manifest from scratch, which is very slow. This hasn't happened yet, and is not a major risk.

Finally, if we were going to use the manifests for wpt.fyi in the future, we'll be missing some.

All in all, the impact is minor, but backfilling when missing *might* have utility in the future.

Since I filed this issue I also rediscovered https://github.com/foolip/wpt-stats/runs/705095965?check_suite_focus=true#step:6:7 where I had written scripts to monitor this. That lists the PRs that have missing tags/manifests since I set that up.

**Comment by stephenmcgruer** [comment]
Thanks, that's a great overview of the problem!

**Comment by foolip** [comment]
I revived an old script (a `tools/ci/manifest_build.py` tweaked to live out-of-tree) to fill in missing tags and releases and ran that, so that we don't have any missing ones now.

A good way to assess the impact of this in the future is to take a look at https://github.com/foolip/wpt-stats/actions and see if more tags and releases are missing. Knowing that it's complete up to the present time should make it easier to state that it happens X% of the time.

**Comment by foolip** [comment]
This sort of thing can still happen, and I fixed a problem today in https://github.com/web-platform-tests/wpt/pull/28761, but there's no use in having an open issue for this. The problem won't be the same next time.
