### ISSUE TITLE
Eventsource tests are broken under python3

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#23436]
Judging by the comment in https://github.com/web-platform-tests/wpt/pull/23284 this is expected. It broke Servo's nightly sync, however, since we're running a small set of tests (/eventsource) under python3 to verify the rest of our test infrastructure still works.

**Comment by stephenmcgruer** [comment]
cc @Hexcles @jgraham as an FYI

This will eventually be fixed as we upgrade handlers to Python 3, but perhaps we could fix the `eventsource/` ones ahead of https://github.com/web-platform-tests/rfcs/pull/49 being ratified given that we're sort of regressing here?

@jdm - does it need to be those tests you run, or could you run some that don't depend on the python file handler support?

**Comment by jdm** [comment]
Running any small set of tests is fine for our purposes. I nearly have all of the handlers fixed to get the tests passing again, but there are a couple stragglers that do special things with encodings, of course.

**Comment by Hexcles** [comment]
@jdm has #24184 fixed this issue?

**Comment by jdm** [comment]
Yep.
