### ISSUE TITLE
tools/wpt/ tests failing on Python 3.6 and 3.8 on Windows

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23441]
I've seen this from time to time, it's probably been happening for weeks or months already.

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=47560&view=logs&jobId=b6659cb1-662e-592d-54c4-23e3f3bef39a&j=b6659cb1-662e-592d-54c4-23e3f3bef39a&t=10fc34cb-585f-5af5-e547-ad012e9553b8 (for https://github.com/web-platform-tests/wpt/pull/18830) shows this happening:
```
Generating script.
Script contents:
tox -c tools/wpt/ -e py36 -- --junitxml=results.xml
========================== Starting Command Output ===========================
"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "d:\a\_temp\0af6cff0-ee70-423f-b4f8-4ae2fa47f5ec.cmd""
py36 create: D:\a\1\s\tools\wpt\.tox\py36
ERROR: invocation failed (exit code 1), logfile: D:\a\1\s\tools\wpt\.tox\py36\log\py36-0.log
================================== log start ==================================
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 8: ordinal not in range(128)

=================================== log end ===================================
ERROR: InvocationError for command 'c:\hostedtoolcache\windows\python\2.7.18\x64\python.exe' -m virtualenv --no-download --python 'C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe' py36 (exited with code 1)
___________________________________ summary ___________________________________
ERROR:   py36: InvocationError for command 'c:\hostedtoolcache\windows\python\2.7.18\x64\python.exe' -m virtualenv --no-download --python 'C:\hostedtoolcache\windows\Python\3.6.8\x64\python.exe' py36 (exited with code 1)
```

So things don't get very far at all before failing. This job has both python 2 and 3 installed, and possibly there's some mixup happening here.

**Comment by foolip** [comment]
@stephenmcgruer would you consider this part of the Python 3 work? Is there someone who could try fixing it, or should we disable these jobs?

**Comment by stephenmcgruer** [comment]
Assigning to Ziran, who is currently working on Py3 support included Windows support currently.

cc @svillar who looked at this briefly

**Comment by svillar** [comment]
Is it a windows only failure @foolip ?

**Comment by foolip** [comment]
@svillar yes, I've seen this only on Windows.

**Comment by foolip** [comment]
To scratch another itch, that I suspected might affect this, I sent https://github.com/web-platform-tests/wpt/pull/23536. Seems like that passes, will verify the tests are actually running and then send out for review.

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/23536.
