### ISSUE TITLE
xrWebGLLayer_framebuffer_scale.https.html depends on chromium-only stuff

### ISSUE THREAD

**Issue by svillar** [web-platform-tests/wpt#23539]
It's currently using `fakeDeviceController.displayInfo_.webxrDefaultFramebufferScale` which is defined [here](https://github.com/web-platform-tests/wpt/blob/cdd4b43f2f89422f36d81546df70eb09f6aa8ed0/resources/chromium/webxr-test.js#L462) in `resources/chromium/webxr-test.js`. If we want other vendors to be able to run the test then we should either replace it or add new api to [the test API](https://immersive-web.github.io/webxr-test-api).

**Comment by foolip** [comment]
@Hexcles you were going to have a look at Mojo and WebXR this quarter, right?

**Comment by Hexcles** [comment]
Yes, I will.

**Comment by Hexcles** [comment]
This has been resolved by db9a10cb04de8883c4c04dd57683436f6bb47917.
