### ISSUE TITLE
Safari stable run timed out

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#23532]
Haven't seen such a failure recently so logging this bug just in case this is a real issue.

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=47829&view=results

The first shard of the Safari run executed for 3 hours and then was cancelled. Normally this seems to run in about half the time. Logs suggest the job was actively working (didn't seem to be stuck). Could it be that some tests got super slow? Or could just be transient.

Lets see if Safari runs succeed on the next scheduled run -- will close if they do, or follow-up here if they don't.

**Comment by LukeZielinski** [comment]
@foolip as FYI for now, lets see if tomorrow's run works. Unless you see something obviously wrong above.

**Comment by foolip** [comment]
@LukeZielinski I downloaded the raw logs of the "Run tests" step, and it ends like this:
```
2020-05-12T01:59:22.4900020Z InvalidArgumentException: invalid argument (400): Could not parse requested URL 'http://web-platform.test:8000/xhr/xmlhttprequest-timeout-worker-overridesexpires.html?timeout set to expiring value after load fires'
2020-05-12T01:59:22.4901200Z 95:00.24 INFO Closing logging queue
2020-05-12T01:59:22.4901570Z 95:10.24 INFO queue closed
2020-05-12T01:59:22.4901980Z 95:10.25 INFO Tolerating 29638 unexpected results
2020-05-12T03:21:17.6455630Z ##[error]The operation was canceled.
2020-05-12T03:21:17.6471860Z ##[section]Finishing: Run tests
```

So it look like `./wpt run` got through all of the tests, but then hanged until it was canceled.

I haven't seen this failure mode before.

**Comment by foolip** [comment]
Comparing that to a case that succeeded, there shouldn't be any more output after "INFO Tolerating 29638 unexpected results", so it's not clear that this got stuck inside `./wpt run`. It might have, but another possibility is some glitch on the Azure Pipelines side.

**Comment by foolip** [comment]
@LukeZielinski do we have numbers for how many of the last *n* daily Safari runs got posted to wpt.fyi? Eyeballing https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=safari it looks pretty good lately, but both May 11 and 12 were missed.

**Comment by LukeZielinski** [comment]
We do have numbers but they only go back to May 1. But agreed with your link, it's been good except for May 11 and 12.

Either way I think the issue was intermittent - today's safari run succeeded. So I'll close this.
