### ISSUE TITLE
Add another HTTPS port

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#23579]
I'd like to test that two different-port-same-host origins can be isolated from each other using [origin isolation](https://github.com/WICG/origin-isolation). Since this is a HTTPS-only feature, this requires two separate HTTPS ports.

Web platform tests only provides one, thus preventing me from writing these tests :(.

Some draft tests that fail for trying to access an out-of-bounds `{{ports[https][1]}}` at https://chromium-review.googlesource.com/c/chromium/src/+/2199550

**Comment by stephenmcgruer** [comment]
Sadly the js part of this was reverted in https://github.com/web-platform-tests/wpt/pull/24394 due to breaking Chromium's importer. What we need to do is roll the tooling into Chrome, and only then re-land the js part.

**Comment by sparkleholic** [comment]
If two different ports isolation of the same host origin feature is HTTPS only, why does wpt have two HTTP values?
