### ISSUE TITLE
pointer_tripleclick.py causes Safari runs to get stuck and fail

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#23630]
https://github.com/web-platform-tests/wpt/pull/23456 added webdriver/tests/perform_actions/pointer_tripleclick.py and both Safari stable and preview runs are now failing to run to completion:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=48148&view=logs&j=e30964c2-2c6e-5f59-e489-a5a5f8e06cce&t=6d7e717c-8e8e-5068-9023-6945313ee227&l=16586
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=48149&view=logs&j=42513d51-f539-5b97-080a-60c327907e2e&t=6bddcad2-158c-5a9c-742b-83e5496432ab&l=16614

After the test has timed out, we see a lot of SessionNotCreatedException until finally "Max restarts exceeded".

There's presumably something going wrong with safaridriver or Safari here, but also https://github.com/web-platform-tests/wpt/issues/19620 is about our failure to recover from such errors.

@burg FYI

**Comment by foolip** [comment]
Running the test locally with `./wpt run --channel preview safari webdriver/tests/perform_actions/pointer_tripleclick.py` (using STP 106) I see it get stuck like this:
![image](https://user-images.githubusercontent.com/498917/82043950-c1e87600-96ac-11ea-9daf-dfab9bbd553a.png)

That doesn't really provide much of a clue, however.

**Comment by foolip** [comment]
Running with `--webdriver-arg=--diagnose` produces a [safaridriver.81562.ptlpke.txt](https://gist.github.com/foolip/6fc12fb994c4cb39088ff477aecf3f5d). That also doesn't provide much of a clue, it just ends with the action command being received, and then nothing.

**Comment by burg** [comment]
I've created a radar to track investigation of this internally.

<rdar://63276006 <rdar://63276006>>

Some other click tests are failing/hanging due to some known issues, most notably clicking at absolute coordinates and clicking after implicitly scrolling. We are actively investigating these issues.

**Comment by foolip** [comment]
Thanks @burg, that's great! Please let me know if you need any additional info, if you're not able to reproduce locally.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/23631 worked, so this is no longer urgent in wpt.

**Comment by gsnedders** [comment]
Closing this as #27427 has meant we don't need to maintain a blocklist of tests; the rest of the issue here is a safaridriver one.
