### ISSUE TITLE
Add a test that input type=datetime is not supported.

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#2383]
Per https://github.com/whatwg/html/commit/80ba4fa24e5d3d81a10aa1bbd8a2f72f4bcc3f7c

**Comment by Ms2ger** [comment]
Also check if any other references to it remain after #2382.

**Comment by Honry** [comment]
Already fixed in https://github.com/web-platform-tests/wpt/pull/3770 and https://github.com/web-platform-tests/wpt/pull/3684, close it.
