### ISSUE TITLE
Saucelabs: remove custom selenium version for Microsoft Edge

### ISSUE THREAD

**Issue by zouhir** [web-platform-tests/wpt#23895]
Currently, there seem to be a check for when the `--sauce-browser` passed in the runner CLI args is MicrosoftEdge and it makes it use older selenium version, I am not aware of any issues preventing Chromium based MS Edge to work on `selenium@latest` so I believe it's safe to remove.

https://github.com/web-platform-tests/wpt/blob/d3ea88514a93b7b69687837de19b1ca6da15cf91/tools/wptrunner/wptrunner/browsers/sauce.py#L72

**Comment by stephenmcgruer** [comment]
@zouhir quick question - this code was developed when MicrosoftEdge meant EdgeHTML as far as I am aware. I assume Sauce now interprets 'MicrosoftEdge' as Chromium-based edge?

**Comment by zouhir** [comment]
@stephenmcgruer I confirm your assumption is correct. 


I found this good reference for the support matrix in Webdriver+Saucelabs: https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

*MicrosoftEdge* is used for both EdgeHTML and Chromium, the version decides which one to launch:
<img width="844" alt="Screen Shot 2020-06-01 at 3 18 03 PM" src="https://user-images.githubusercontent.com/5052316/83460442-406a4500-a41b-11ea-8ec1-a497103c62a5.png">
