### ISSUE TITLE
Unclear why infrastructure print reftest ref has specified height

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#23918]
https://github.com/web-platform-tests/wpt/blob/master/infrastructure/reftest/reftest_match-print-ref.html#L5-L6 specifies a div height of `180px` which is supposed to correspond to 2 inches on the printed paper. But a simple calculation of 96 pixels per inch x 2 suggests it ought to be `192px`. It's somewhat unclear what accounts for the the other `12px`.

**Comment by stephenmcgruer** [comment]
@jgraham - have you been able to determine any cause for this, particularly as I believe you've now ported some real print reftests over to WPT?

**Comment by jgraham** [comment]
I think it ended up being the default margin on body.
