### ISSUE TITLE
lint is super slow

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#23969]
In e29608a4345 (from #23239, by @stephenmcgruer) `check_unique_testharness_basenames` was added. However, because it calls `SourceFile.items` it results in files being parsed a second time (after `check_parsed`), which significantly increases the time taken to run the lint.

**Comment by stephenmcgruer** [comment]
I'm not sure how to solve this problem (maybe the solution is we remove the baselines check and go back to breaking Chromium and WebKit occasionally). When we landed the PR, we knew that it would be slow for `--all` but agreed that mostly only the CI runs that, and the speed impact for individual PRs that folks were working on would be minor (assuming anyone actually runs lint locally). 

We can't rely on the manifest in lint; generating that requires reading all the files anyway and would make all lints (even if they were only partial lints) very slow. We can't deduce if a file is a testharness file any other way than reading its contents, and when developing the conflicting-baseline PR we found hundreds of instances of non-testharness files that have conflicting baselines, and which shouldn't have to change.

We could preemptively create a SourceFile for all passed in paths and pass those around; that would at least cut down on the runtime by 1/2 (by re-using the cached manifest items). I'm happy to make that happen.

**Comment by gsnedders** [comment]
> So a ~1.5x slowdown from 'before'. I'm not sure how much more painful 9m16s is than 6m20s - I'm walking away from my laptop for either. But perhaps the slowdown isn't linear?

It looks like it should be linear, FWIW. We're dominated by html5lib anyway (but I'll make release soon that we can vendor in and get a decent speed bump). The other thing that should make a decent perf jump is moving to Py3.7+ (c.f. https://gist.github.com/gsnedders/89cb4852b0a0466287f4c45c9ce60462#file-html5lib_perf_2-md for html5lib perf in isolation compared with slightly older, but still more recent than we have, html5lib perf)

**Comment by foolip** [comment]
I came here to file an issue and found this existing one. I don't have anything to contribute about how to solve it, but adding another "too slow" comment for priority. In https://github.com/web-platform-tests/wpt/pull/24606 the lint took over 7 minutes, and I was still waiting for the lint to finish after the tests (including stability!) had already finished running. That seems somehow unreasonable.

**Comment by foolip** [comment]
Ping @stephenmcgruer, this came up in the rotation. Is this something that is on your radar?

**Comment by gsnedders** [comment]
If we loosen the guard from `type != "testharness"` to something that tries to statically determine the set of possible types without reading the file, we introduce 46 failures:

<details>
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_changed.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .svg, .xml, .xhtml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_changed.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .svg, .xml, .xhtml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_changed.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .svg, .xml, .xhtml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_changed.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .svg, .xml, .xhtml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_mathml.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_mathml.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_mathml.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_mathml.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/ParentNode-querySelector-All-content.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xht) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/ParentNode-querySelector-All-content.xht: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xht) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/svg.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .html, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/svg.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .html, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/svg.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .html, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/svg.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .html, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_svg.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .xml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_svg.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .xml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_svg.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .xml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_svg.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xhtml, .xml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_removed.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_removed.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_removed.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/xhtml_ns_removed.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_xhtml.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_xhtml.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_xhtml.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/bare_xhtml.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .html, .xhtml, .svg, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:svg/struct/reftests/reference/green-100x100.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:svg/struct/reftests/reference/green-100x100.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/mathml.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html, .xhtml, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/mathml.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html, .xhtml, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/mathml.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html, .xhtml, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/mathml.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .svg, .html, .xhtml, .xml) (DUPLICATE-BASENAME-PATH)
ERROR:lint:acid/acid3/empty.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:acid/acid3/empty.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/empty.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .xhtml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/empty.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .xhtml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/empty.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .xhtml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/empty.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .xhtml, .svg, .html) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/minimal_html.xml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html, .xhtml, .svg) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/minimal_html.html: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html, .xhtml, .svg) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/minimal_html.xhtml: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html, .xhtml, .svg) (DUPLICATE-BASENAME-PATH)
ERROR:lint:dom/nodes/Document-createElement-namespace-tests/minimal_html.svg: File has identical basename path (path excluding extension) as other file(s) (found extensions: .xml, .html, .xhtml, .svg) (DUPLICATE-BASENAME-PATH)
</details>

This also makes the check take ~3s v. 1m25s.

Note that almost all of these are in `dom/nodes/Document-createElement-namespace-tests/`. Those which aren't are: `acid/acid3/empty.html`/`empty.xml`, `svg/struct/reftests/reference/green-100x100.svg`/`green-100x100.html`, and `dom/nodes/ParentNode-querySelector-All-content.html`/`ParentNode-querySelector-All-content.xht`.

For this very small number of false positives, which are largely in one directory, I think we should simplify the logic here to avoid having to parse the files again?

**Comment by foolip** [comment]
That's a pretty huge difference, so paying some small cost for getting that speedup sounds like a great idea!
