### ISSUE TITLE
testharness itself may interfere the result of first contentful paint tests?

### ISSUE THREAD

**Issue by sefeng211** [web-platform-tests/wpt#24089]
Hello! 

I am debugging something related to contentful paint tests in Firefox and I think I might find a problem. 

The [assertFirstContentfulPaint](https://github.com/web-platform-tests/wpt/blob/dddc29524981e7b6c21b9ab403efc07c1d201a98/paint-timing/resources/utils.js#L28-L31) function uses `step` and `step_timeout`, which will invoke [show_status](https://github.com/web-platform-tests/wpt/blob/dddc29524981e7b6c21b9ab403efc07c1d201a98/resources/testharness.js#L3078) which will add some [text](https://github.com/web-platform-tests/wpt/blob/dddc29524981e7b6c21b9ab403efc07c1d201a98/resources/testharness.js#L3094-L3096) to the document. 

Wouldn't this trigger a contentful paint on the testing document? which means the tests may test something that is not our expectation? 

cc @npm1

**Comment by gsnedders** [comment]
> Ok, so presumably running the tests using Firefox's automated test runner it shouldn't be a problem?

Correct, there's no visual output by default in automation.

>  If you need more control here it might be possible to add some API surface to allow reenabling output later on, or something similar.

Making it possible to only output at the test end seems sane.

**Comment by sefeng211** [comment]
@npm1 hmm, I still think this is a problem. Does your test also invoke the `step` function call? 
Can you try this ?
```
    await promise_test(async t => {
      function checkFCP() {
        if (performance.getEntriesByName('first-contentful-paint').length === 1){
          resolve();
        } else {
          t.step_timeout(checkFCP, 0);
        }
      }
      t.step(checkFCP);
    }, "should timeout");
```
I tried the follow code by using the wpt runner on Chrome as `./wpt run --binary /usr/bin/chromium chrome <path>`, and it passed. 
```
    <!DOCTYPE html>
    <head>
    <style>
    </style>
    </head>
    <body>
    <script src="/resources/testharness.js"></script>
    <script src="/resources/testharnessreport.js"></script>
    <script>
      async function test_fcp_timeout() {
        await promise_test(async t => {
          function checkFCP() {
            if (performance.getEntriesByName('first-contentful-paint').length === 1){
              resolve();
            } else {
              t.step_timeout(checkFCP, 0);
            }
          }
          t.step(checkFCP);
        }, "should timeout");
      }
    ​
      test_fcp_timeout();
    </script>
    </body>
    </html>
```

**Comment by noamr** [comment]
Yea, I've encountered this... The oriignal commit didn't use `step_timeout` for this reason. @npm1 There was a later [commit](https://github.com/web-platform-tests/wpt/commit/4f3baa465e7f7eb460a5bf2f052ca78fbc1b50aa#diff-3813b6cfb75a0d2eab5b80577faf981a) that makes use of `step_timeout` again. I'm not sure how come it hadn't created the same issue (the output DIV triggering FCP).

I believe the right approach here would be to add a setting that only displays the output at the end of the test.

**Comment by npm1** [comment]
I do think we need to use either `step_timeout` to poll until found, because before it would assume that FCP must occur within a given timeframe, and that will produce flaky results. The alternative would be to use PerformanceObserver, but that's not supported in all major browsers yet.

**Comment by npm1** [comment]
> @npm1 hmm, I still think this is a problem. Does your test also invoke the `step` function call?
> Can you try this ?
> 
> ```
>         await promise_test(async t => {
>           return new Promise(resolve  => {
>             function checkFCP() {
>               if (performance.getEntriesByName('first-contentful-paint').length === 1) {
>                 console.log("FOUND CONTENTFUL PAINT");
>                 resolve();
>               } else {
>                 t.step_timeout(checkFCP, 0);
>               }
>             }
>             t.step(checkFCP);
>           });
>         }, "should timeout");
> ```
> 
> I tried the follow code by using the wpt runner on Chrome as `./wpt run --binary /usr/bin/chromium chrome <path>`, and it passed.
> 
> ```
>     <!DOCTYPE html>
>     <head>
>     <style>
>     </style>
>     </head>
>     <body>
>     <script src="/resources/testharness.js"></script>
>     <script src="/resources/testharnessreport.js"></script>
>     <script>
>       async function test_fcp_timeout() {
>         await promise_test(async t => {
>           return new Promise(resolve  => {
>             function checkFCP() {
>               if (performance.getEntriesByName('first-contentful-paint').length === 1) {
>                 console.log("FOUND CONTENTFUL PAINT");
>                 resolve();
>               } else {
>                 t.step_timeout(checkFCP, 0);
>               }
>             }
>             t.step(checkFCP);
>           });
>         }, "should timeout");
>       }
>     ​
>       test_fcp_timeout();
>     </script>
>     </body>
>     </html>
> ```
> 
> Edit: Sorry, there was a bug in my first post, I updated it, should be good now. And yeah, still passes.

Interesting, so with the runner in Chromium it times out but with wpt run it passes. This seems like incorrect behavior from wpt run.

**Comment by sefeng211** [comment]
I agree with @noamr that the right approach should be only displaying the test result at the end of test. 

I don't understand why it timed out in Chromium runner, perhaps it's configured to not display the test results when the test is running? 

This is might be a naive question,  which major browsers don't support `PerformanceObserver`? It seems well supported now.

**Comment by npm1** [comment]
Oh looking at https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver looks like I'm wrong? I'm happy to see the tests change to use `PerformanceObserver` instead of `step` and `step_timeout` if that's ok with everyone. Though such a test will use `step_func`or `step_func_done`.

**Comment by sefeng211** [comment]
Cool! I'll submit a PR to use `PerformanceObserver`, then we can discuss if there are other issues :)

**Comment by sefeng211** [comment]
So..I looked into the test a bit more and I am not sure if we can avoid calling `step` at all because `test`, `async_test` and `promise_test` all use `step` to invoke the test function underneath. Even if we've converted it ito `PerformanceObserver`, we'd still need to call `step` once. Although, in my local test, this `step` seemed fine because the [document hadn't loaded](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L3120-L3121) yet. 

What about we just add a new setup option as `setup({"notify_test_state": false})` to eliminate the side effect?

**Comment by noamr** [comment]
> So..I looked into the test a bit more and I am not sure if we can avoid calling `step` at all because `test`, `async_test` and `promise_test` all use `step` to invoke the test function underneath. Even if we've converted it ito `PerformanceObserver`, we'd still need to call `step` once. Although, in my local testing, this `step` seemed fine because the [document hadn't loaded](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L3120-L3121) yet.
> 
> What about we just add a new setup option as `setup({"notify_test_state": false})` to eliminate the side effect?

Yes I think that would be a good solution.
