### ISSUE TITLE
idlharness does not support async iterators

### ISSUE THREAD

**Issue by mkruisselbrink** [web-platform-tests/wpt#24174]
Currently idlharness seems to treat async iterator definitions the same as regular iterators, expecting a @@iterator rather than an @@asyncIterator. (this effects at least native-file-system/idlharness.https.any.js)

**Comment by domenic** [comment]
There are likely portions of https://github.com/web-platform-tests/wpt/blob/master/streams/readable-streams/async-iterator.any.js, especially toward the top of the file, that are amenable to being generalized and moved to idlharness.
