### ISSUE TITLE
print-reftest results missing from wpt.fyi?

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#24260]
https://wpt.fyi/results/?label=master&label=experimental&aligned&q=infrastructure%2Freftest%2Freftest_match-print.html currently shows no results, but running the same test locally in WPT I see it passing in Chrome at least.

We should figure out if its missing from our input data, or if we're dropping it on the client side somehow.

**Comment by Hexcles** [comment]
Need to schedule `print-reftest` in `tools/ci/tc/tasks/test.yml`

**Comment by stephenmcgruer** [comment]
> Need to schedule print-reftest in tools/ci/tc/tasks/test.yml

I can take care of this.

@Hexcles I did see we have a `TEST_TYPES` array in `webapp/views/wpt-results.js` for wpt.fyi, may be worth checking if that will be relevant in any way.
