### ISSUE TITLE
Missing WebKitGTK runs since June 22

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#24360]
As per https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk the last successful WebKitGTK run was June 22 (4 days ago).

Any idea what's going on?

**Comment by jdm** [comment]
This is the same as #24257:
```
 0:14.49 INFO Running print-reftest tests
 0:14.50 ERROR Unsupported test type print-reftest for product webkitgtk_minibrowser
 0:14.50 INFO Got 0 unexpected results
 0:14.50 SUITE_END
```

**Comment by clopez** [comment]
> This is the same as #24257:

Yes.. same issue.

We need to avoid failing the taskcluster CI run if the browser doesn't support the print-reftest tests (or skip those tests)

**Comment by stephenmcgruer** [comment]
To keep things synced - it seems like nobody currently owns https://github.com/web-platform-tests/wpt/issues/24257, so if there's a desire to get WebKitGTK back on wpt.fyi someone needs to step up and add 'skip if not supported' logic or something similar to that.

**Comment by clopez** [comment]
> To keep things synced - it seems like nobody currently owns #24257, so if there's a desire to get WebKitGTK back on wpt.fyi someone needs to step up and add 'skip if not supported' logic or something similar to that.

Thanks for the heads up. There is definitively a desire to get WebKitGTK back on wpt.fyi. I have a patch that I think it can work. .. will upload the PR now
