### ISSUE TITLE
Invite christianliebel as collaborator

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#24448]
@christianliebel is part of:

https://github.com/web-platform-tests/wpt/blob/master/appmanifest/META.yml

But he is not a collaborator of this repo at the moment. @sideshowbarker, could you add him?

**Comment by marcoscaceres** [comment]
Never mind... it works...

**Comment by marcoscaceres** [comment]
Actually, no... @christianliebel can't approve things.

**Comment by sideshowbarker** [comment]
Invitation sent

**Comment by christianliebel** [comment]
Works! Thank you, @sideshowbarker.
