### ISSUE TITLE
document-fullscreen-enabled.html is broken.

### ISSUE THREAD

**Issue by emilio** [web-platform-tests/wpt#24581]
It tests that `<iframe></iframe>` gets `document.fullscreenEnabled == false`, but per spec it should get fullscreen, as it is same-origin with the top document.

I was going to fix this test but it is annoying and it is actually superseded by `html/semantics/embedded-content/the-iframe-element/iframe-allowfullscreen.html`.

I was going to just remove the test, but I'm confused because the test was imported from blink in https://github.com/web-platform-tests/wpt/commit/32f59f6d823ebbf6d55b2840ab6da9996a04322f but it is failing in blink.

@foolip should we just get rid of this?

**Comment by foolip** [comment]
This test predates the changes to not require the `allowfullscreen` attribute in same-origin iframes. I've sent https://github.com/web-platform-tests/wpt/pull/25140 to trim the test down, to still have some coverage of `fullscreenEnabled` in the fullscreen/ directory.

**Comment by emilio** [comment]
Thank you!
