### ISSUE TITLE
Pin the major version of pip to 20 in Python 2

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#24636]
I noticed that pip would drop support for Python 2 starting from v21: https://github.com/pypa/pip/issues/6148

We've been seeing the deprecation warnings when running `wpt run` without `--py3`:
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support 

The timeline seems to be January 2021. And we need to pin the version of pip everywhere we run Python 2 (including the `wpt` frontend and various `tox` tests).

**Comment by stephenmcgruer** [comment]
At this point we're hoping to be Py3-first by Jan 2021, but we will likely have a few Py2 bots (infra/ tests, some unittests) to help with backwards compatibility, which will still have to be pinned.

Leaving this roadmap, because we'll want a reminder before the end of the year to get this done! :)

**Comment by foolip** [comment]
Here's the reminder before the year is over! Who should be assigned to this?

**Comment by stephenmcgruer** [comment]
cc @jgraham @gsnedders as folks who might want to know - based on https://github.com/pypa/pip/issues/9282#issuecomment-753301504 this will break in the very last week of us being Py2-compatible (pip is aiming to release on Jan 23/24).

I'm very tempted to declare we're moving the py3-only line forward by a week...

**Comment by jgraham** [comment]
I think I'm happy with spending the time to move stuff over to Py 3 where required rather than pinning pip.

**Comment by stephenmcgruer** [comment]
`pip21` was released this weekend. So far I haven't seen any breakages, so we might just get away with this ;)

**Comment by jgraham** [comment]
I'm going to say we can close this now.
