### ISSUE TITLE
Installing Ahem font on MacOS causes warnings for each installed font to appear in the log

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#24643]
When I run the web-platform-tests I can see a dozen of pages of warnings in the console when the Ahem font is getting installed. Entries that exist for each installed font on my system look like:

```
2020-07-17 07:47:45.516 system_profiler[89311:20944431] CoreText note: Client requested name ".SFNS-RegularG3", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
```

The [causing line](https://github.com/web-platform-tests/wpt/blob/master/tools/wptrunner/wptrunner/font.py#L80) is that one:

```
fonts = check_output(['/usr/sbin/system_profiler', '-xml', 'SPFontsDataType'])
```

That code has been added via PR #10983. @gsnedders or @jgraham any chance we can get rid o that warning output?

**Comment by gsnedders** [comment]
cc @litherum

**Comment by whimboo** [comment]
At some point this got fixed. I don't see it anymore nowadays. Maybe it was a MacOS problem and got fixed with the Big Sur update?
