### ISSUE TITLE
2d Canvas drawImage test correct?

### ISSUE THREAD

**Issue by aardgoose** [web-platform-tests/wpt#24659]
My reading of the current standard is that this case should not through an exception, just return without drawing anything. Is this an obsolete test or does the standard need correcting?

https://github.com/web-platform-tests/wpt/blob/master/html/canvas/element/drawing-images-to-the-canvas/2d.drawImage.zerosource.image.html

**Comment by arai-a** [comment]
dupe of https://github.com/web-platform-tests/wpt/issues/2835 I think
