### ISSUE TITLE
[wptserve] Remove ResponseWriter.flush() and explicit_flush

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#24719]
From https://github.com/web-platform-tests/wpt/pull/24617#pullrequestreview-449339779:

> I'd like to suggest dropping the `flush` method on `ResponseWriter` altogether to prevent any future confusion.
>
> Digging through stdlib, I don't think there's any need to call `flush` ever. In both Python 2 and 3, the base HTTP server inherits from `SocketServer.StreamRequestHandler` with the default `wbufsize = 0`.
> * In Python 2, `wfile.write()` calls `flush()` automatically if `wbufsize` is 0: https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/socket.py#L328
> * In Python 3, `wfile` in fact does not have a buffer at all and `flush()` is a no-op: https://github.com/python/cpython/blob/47a2955589bdb1a114d271496ff803ad73f954b8/Lib/socketserver.py#L791
>
> In both versions, `wfile.write()` ultimately calls `sock.sendall` which either succeeds sending all data or raises an exception: https://docs.python.org/3/library/socket.html#socket.socket.sendall
>
> So basically, the reliable way to detect aliveness of a socket is to check `wfile.write()`. `flush()` is either not necessary (in Python 2) or non-functional (in Python 3), and should be removed for clarity.

**Comment by Hexcles** [comment]
We'd need to
1. Add return statements to a few write* methods to surface caught errors from `_wfile.write`.
2. Change handlers to check the return values of write instead of flush. And drop the use of flush or explicit_flush.
3. Remove flush/explicit_flush from Response.

**Comment by foolip** [comment]
@Hexcles do you plan to work on this yourself? It's labeled roadmap priority, but with nobody assigned it seems unlikely anything will happen :) Perhaps it was already fixed by some of the PRs that landed in July?
