### ISSUE TITLE
[idlharness] Handling of interface changes between versions of a spec

### ISSUE THREAD

**Issue by kevers-google** [web-platform-tests/wpt#24789]
In the web-animations-1 spec Animation.timeline is readonly, whereas in web-animations-2 it is mutable. Timelines were previously mutable in v1 of the spec, but this feature got deferred.  Presently Firefox and Safari support mutable timelines behind a feature flag and Blink is expected to follow shortly.  How do we determine which version of the spec to use for generating the IDL?  Do we support IDL versioning?

**Comment by stephenmcgruer** [comment]
cc @domenic as my idl expert (:D) - Domenic, is what web-animations-2 is doing valid WebIDL?

https://drafts.csswg.org/web-animations-2/#the-animation-interface 
```
partial interface Animation {
               attribute AnimationTimeline?       timeline;
};
```

(Overriding https://drafts.csswg.org/web-animations-1/#the-animation-interface)

In any case, how to support this for idlharness is tricky... I wonder if the best way is to use https://web-platform-tests.org/writing-tests/idlharness.html?highlight=idlharness#add-untested-idls-idl-string (or extend it if necessary) to not test the `timeline` member in the `web-animations-1` idlharness test, and then test it in a `web-animations-2` idlharness test.

**Comment by domenic** [comment]
No, this is invalid. Level 2 specs should totally replace level 1 specs, not use partial interfaces to patch them.

**Comment by stephenmcgruer** [comment]
> No, this is invalid. Level 2 specs should totally replace level 1 specs, not use partial interfaces to patch them.

Oh, so the correct thing for a level 2 spec to do is include the entire level 1 spec, and then additional wording? That seems really difficult to keep in sync if the level 1 space changes :/. (And still doesn't solve the problem here of 'if you implement the level 2 spec correctly, you violate the level 1 spec').

**Comment by domenic** [comment]
Right, there should be only one version of a spec which browsers track, and that version should define the whole API. Older levels are process artifacts for IPR-collection purposes.

**Comment by stephenmcgruer** [comment]
@flackr @graouts @birtles as an FYI; this documentation is likely relevant to you as web-animations editors. It seems like if mutable timelines are becoming a thing that vendors agree on for Web Animations, it should either be brought into web-animations-1 or web-animations-2 should replace web-animations-1.

**Comment by birtles** [comment]
CSS commonly uses delta specs while the prior level is still stabilizing. Once it has stabilized (e.g. gone to CR) then we import the whole text into the next level so that it is no longer a delta spec. Ultimately web-animations-2 will replace web-animations-1 but for that we need to finish off web-animations-1.

**Comment by foolip** [comment]
I would consider this resolved by our use of [@webref/idl](https://www.npmjs.com/package/@webref/idl), pushing the decision about which specs to include to https://github.com/w3c/browser-specs and ensuring that the resulting IDL is consistent together before importing into WPT.

Currently the answer is that we have only the IDL from https://drafts.csswg.org/web-animations-1/, but there are other cases where we have both the base spec and a delta spec, like `css-animations.idl` + `css-animations-2.idl`.

Please file issues at https://github.com/w3c/webref/issues or https://github.com/w3c/browser-specs/issues if the IDL we're getting in WPT is not good.
