### ISSUE TITLE
Test expectation of css/css-pseudo/selection-intercharacter-011/012.html seems wrong

### ISSUE THREAD

**Issue by xiaochengh** [web-platform-tests/wpt#24791]
The test adds highlight only to the selected text, while the ref adds background color the entire `div`, including the empty part. See screenshot below.

<img width="898" alt="selection-intercharacter-011" src="https://user-images.githubusercontent.com/19384155/88730644-66def080-d0eb-11ea-9e12-1c7d4afda7c4.png">

The ref should be changed to highlight only the text.

**Comment by xiaochengh** [comment]
@TalbotG test author.

**Comment by xiaochengh** [comment]
Same for selection-intercharacter-012.html

**Comment by TalbotG** [comment]
@xiaochengh Xiaochengh ,

Thank you for reporting these 2 problems. I also noticed these 2 problems this week and noticed another problem with a reference in another test ( active-selection-031.html ). They (3 tests) were on my todo-list.

I want to come up with a correction for those 2 references in the next 24 hours. Again, thank you for reporting these, for including a screenshot and notifying me.

**Comment by TalbotG** [comment]
Xiaocheng, I have created 
https://github.com/web-platform-tests/wpt/pull/24794
Now, it is a matter of 
- waiting for Continuous Integration checks to succeed and then 
- waiting for a reviewer to approve the change.

**Comment by TalbotG** [comment]
Xiaocheng,
These 2 have now been fixed thanks to 
https://github.com/web-platform-tests/wpt/pull/24794

Therefore, closing this issue now. 

Thank you again for your reporting, screen shot and notifying me.

**Comment by xiaochengh** [comment]
Thanks for fixing!
