### ISSUE TITLE
css/css-pseudo/active-selection-018.html has wrong reference

### ISSUE THREAD

**Issue by xiaochengh** [web-platform-tests/wpt#24803]
@TalbotG 

The text in active-selection-018.html is "Test passes if each glyph of "Selected Text" is green and if there is no red".

Its reference in active-selection-011-ref.html says "Test passes if each glyph of "Selected Text" is green and not red while background color of each glyph of "Selected Text" is white."

**Comment by TalbotG** [comment]
Okay. I will correct this in a few min...

**Comment by TalbotG** [comment]
Correction is in
https://github.com/web-platform-tests/wpt/pull/24807
Now, it's a matter of waiting for 19 Continuous Integration checks to pass+succeed and then waiting for a reviewer to approve correction.

**Comment by xiaochengh** [comment]
Thanks for fixing!
