### ISSUE TITLE
css/css-pseudo/active-selection-031.html incorrect

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#24809]
http://wpt.live/css/css-pseudo/active-selection-031.html

http://wpt.live/css/css-pseudo/reference/active-selection-031-ref.html

**My goal is to adjust or fix this test and/or its reference before August 5th.**

I have already a correction for the reference:

http://www.gtalbot.org/BrowserBugsSection/CSS4Pseudo/reference/active-selection-031-ref-newest.html

but I need to figure out why the soft line break after "d" in the 2 `'text-orientation: upright'` are selected. This may or may not be related to the test itself or it may be a bug with vertical writing-mode and `'text-orientation: upright'`. I am not sure... I have not figure this out yet.

**Comment by TalbotG** [comment]
I have downloaded the latest nightly build of Firefox (Firefox 81.0a1 buildID=20200729213824) and Chromium 86.0.4217.0 and I must take a pause to examine more carefully the test and the reference. 

I may have to split this test into 6 smaller tests too...

I wish I would get rid of the wrapping div in the test...

**Comment by TalbotG** [comment]
I think both browsers highlight the vertical character advance when `'text-orientation: upright'` is declared and when a line-wrapping opportunity occurs. This has more to do with vertical writing-mode than with ::selection.

**Comment by TalbotG** [comment]
I can split the test into 6 smaller tests and also test with "Selected" instead of "Selected Text" which would work around the line-wrapping opportunity issue. After all, the submitted active-selection-031 test is strictly and solely aiming at testing `::selection` for vertical writing modes.

**Comment by fantasai** [comment]
Afaict the test is correct. If Chrome is failing because of a bug, that's their problem. Recommend to close no change.
