### ISSUE TITLE
Beginner question

### ISSUE THREAD

**Issue by PlayerMPark** [web-platform-tests/wpt#24847]
How do i run perform_actions? I keep getting ImportError

**Comment by stephenmcgruer** [comment]
@PlayerMPark - what command exactly are you trying to run, and from what directory? Also, please make sure you have followed the setup steps in https://web-platform-tests.org/running-tests/index.html

From your mention of `tests.perform_actions.support.refine`, that implies you are trying to run a webdriver test (it's the only place I can see that mentioned). These appear to work for me - to pick a random example:

```
$ ./wpt run --channel=dev chrome webdriver/tests/perform_actions/pointer_origin.py
Running 1 tests in web-platform-tests

Ran 1 tests finished in 6.9 seconds.
  • 1 ran as expected. 0 tests skipped.
```

**Comment by PlayerMPark** [comment]
> @PlayerMPark - what command exactly are you trying to run, and from what directory? Also, please make sure you have followed the setup steps in https://web-platform-tests.org/running-tests/index.html
> 
> From your mention of `tests.perform_actions.support.refine`, that implies you are trying to run a webdriver test (it's the only place I can see that mentioned). These appear to work for me - to pick a random example:
> 
> ```
> $ ./wpt run --channel=dev chrome webdriver/tests/perform_actions/pointer_origin.py
> Running 1 tests in web-platform-tests
> 
> Ran 1 tests finished in 6.9 seconds.
>   • 1 ran as expected. 0 tests skipped.
> ```

`

> {"error": {"message": "No module named perform_actions.support.mouse\nTraceback (most recent call last):\n  File \"C:\\Users\\Moises\\Desktop\\wpt-master\\wpt-master\\tools\\wptserve\\wptserve\\server.py\", line 277, in finish_handling\n    handler(request, response)\n  File \"C:\\Users\\Moises\\Desktop\\wpt-master\\wpt-master\\tools\\wptserve\\wptserve\\handlers.py\", line 313, in __call__\n    self._set_path_and_load_file(request, response, func)\n  File \"C:\\Users\\Moises\\Desktop\\wpt-master\\wpt-master\\tools\\wptserve\\wptserve\\handlers.py\", line 293, in _set_path_and_load_file\n    exec(compile(f.read(), path, 'exec'), environ, environ)\n  File \"C:\\Users\\Moises\\Desktop\\wpt-master\\wpt-master\\webdriver/tests/perform_actions/pointer_origin.py\", line 5, in <module>\n    from tests.perform_actions.support.mouse import get_inview_center, get_viewport_rect\nImportError: No module named perform_actions.support.mouse\n", "code": 500}}

is what gets to me

**Comment by stephenmcgruer** [comment]
You still have not provided us with the command you are running or the steps you are taking to get that error. I'm afraid without that information we will not be able to help.

**Comment by PlayerMPark** [comment]
> You still have not provided us with the command you are running or the steps you are taking to get that error. I'm afraid without that information we will not be able to help.

I did the instructions from [here](https://web-platform-tests.org/running-tests/from-local-system.html#windows-setup). I believe that `python wpt serve` worked fine because it gave me

> DEBUG:web-platform-tests:Going to use port 55695 to check subdomains
DEBUG:web-platform-tests:Going to use port 55956 for stash
DEBUG:web-platform-tests:Using ports: defaultdict(<type 'list'>, {'h2': [9000],
'http': [8000, 55694], 'wss': [55693], 'ws': [55692], 'https': [8443, 8444]})

and when i tried to run this script `python ./wpt run --channel=dev chrome webdriver/tests/perform_actions/pointer_origin.py` it gave me the option to install webdriver which i accepted but then it shut down

**Comment by PlayerMPark** [comment]
> You still have not provided us with the command you are running or the steps you are taking to get that error. I'm afraid without that information we will not be able to help.

Basically it cant do absolute imports

**Comment by stephenmcgruer** [comment]
Thank you for giving more complete reproduction steps. I am not sure why you closed this, but I see you opened https://github.com/web-platform-tests/wpt/issues/24864 so I am going to consider that new issue your current question.
