### ISSUE TITLE
Edge runs stuck since ~July 31st

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#24846]
Noticed yesterday when I tried to issue a trigger run on both Edge Stable and Edge Dev. All Edge runs appear to be stuck:

https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&view=branches

In all cases where the pipeline is meant to be running Edge, it just says "Queued" for the Edge runners.

Example runs:

* https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=52049&view=results
* https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=52059&view=results

![image](https://user-images.githubusercontent.com/153264/89122827-8a61bc80-d498-11ea-8a5a-666b6b4a54ac.png)

**Comment by stephenmcgruer** [comment]
This appears to no longer be stuck, so dropping to roadmap. Would love to know why it happened, but if we can't find that out then we should just close this.

**Comment by mustjab** [comment]
We schedule a weekly VM re-creation on a Sunday, which usually takes Edge runners down for 30 minutes or so. I've double checked our pipeline and it looks like that happened without errors.

**Comment by stephenmcgruer** [comment]
I guess we won't be able to see what happened then - it looks like the VM re-creation went back and caught up the old pending jobs too. Note that these were definitely pending *before* the VM re-creation, it was not the re-creation itself that caused the pending state

**Comment by mustjab** [comment]
The re-creation of VMs happens on Sunday at 9PM PST. I can disable it, if we don't think it's needed anymore. We should be cleaning up VM state after every run.
