### ISSUE TITLE
TPAC 2020 meeting for wpt

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#25007]
IRC discussion

https://w3.logbot.info/testing/20200811#c572981
https://w3.logbot.info/testing/20200812

I'm hearing "yes we should have a meeting". The deadline for group meetings was yesterday, but we're not a W3C group, and maybe it's still possible to schedule.

* [TPAC group meeting schedule](https://www.w3.org/2020/10/TPAC/group-schedule.html#schedule)
* [TPAC wiki to organize group meetings](https://www.w3.org/wiki/TPAC/2020/GroupMeetings)
* [wpt wiki page for TPAC 2019](https://github.com/web-platform-tests/wpt/wiki/TPAC-2019)
* [wpt 2020 priorities](https://docs.google.com/document/d/1gie7LFb6cAUfabY86MYuWM7m7ux_FaKhDkLdpz0zWkg/edit)

cc @web-platform-tests/wpt-core-team @web-platform-tests/moderators @dontcallmedom

**Comment by stephenmcgruer** [comment]
Wow, I find that scheduling page and wiki page really hard to understand -_-.

I assume we should aim for week of the 12-16th Oct? Albeit the only meetings on those pages so far are mostly on the 19th - 23rd which is sorta weird given the claims about when TPAC is...

**Comment by gsnedders** [comment]
> I assume we should aim for week of the 12-16th Oct? Albeit the only meetings on those pages so far are mostly on the 19th - 23rd which is sorta weird given the claims about when TPAC is...

AIUI:

* Individual group meetings to be happening throughout September/October _except_ 12th–16th and 26th–30th (though most are arranged for the week between them, 19th–23rd)
* Joint group meetings to be happening 12–16th October
* Breakout sessions to be happening 26th–30th October

Presumably therefore the question is whether we want to try and arrange something on the same week as most other groups (19th–23rd), which potentially is more difficult from the point-of-view of avoiding conflicts. I know there's some plan to have a Browser Tools & Testing meeting for TPAC (cc @AutomatedTester) but I don't think that's scheduled either…

The other question is how we want to schedule it; the experience of other WGs I'm in has been to split meetings over a larger number of days, limiting them to four-hours per day. Given we've in recent years had two nearly complete days this would imply splitting it over three or four days. That said, I'm not sure there's quite so much value in so much time when remote?

**Comment by jgraham** [comment]
I think there's value in meeting remotely, and TPAC provides a convenient excuse to do that. I think we should figure out what the most valuable sessions were from previous TPACs and try to prioritise those; I don't think anyone is going to want to do 16 hours of video calls, but a few hours of focused discussion on topics like 2021 priorities seem like they might be high value.

I also found the scheduling confusing. I think @sideshowbarker offered to help arrange something here.

**Comment by stephenmcgruer** [comment]
Coming back to this, I would suggest we do probably two 4-hour breakout sessions (with the caveat that we should draft an agenda and make sure that this is both enough and not too much time), and consider doing a single joint group meeting too **if** there is some other group that wants to engage with us for future planning (most likely the CSSWG, but perhaps other WGs will want to talk testing).

(Why breakout, and not group? Mainly because we're not a WG technically, I don't think it really matters otherwise. Our breakout sessions may lack the razor-focus that TPAC is aiming for, with multiple items on an agenda, but I don't think that matters tbh).

Unless @sideshowbarker is already working on it, I can own driving some scheduling and starting to put together a proposed agenda.

**Comment by sideshowbarker** [comment]
> Unless @sideshowbarker is already working on it, I can own driving some scheduling and starting to put together a proposed agenda.

I’ve not been working on the details — so if you’re able to make time to drive it, that’d be great

**Comment by stephenmcgruer** [comment]
My current proposal is:

* **Week of October 12th**: a joint meeting with interested WGs. (CSSWG?)
  * This is likely to be a short meeting, 1-2 hours in length.
  * Day/time will depend on the other WG.
* **October 19th and October 21st**, 1400-1730 UTC: WPT meetings.
  * These are intended to be the primary meetings for WPT business.
* **Week of October 26th**: ad-hoc organized breakout sessions, follow-ons for specific WPT topics that some folks may be interested in.
   * To be organized as needed during the week of October 19th.

I have also begun to draft a [WPT TPAC 2020 Agenda](https://docs.google.com/document/d/1XhUwVbitdV03eX2GefmokCliWjQdAxBgblwITwNqsgc/edit#) - please feel free to add suggested topics or leave comments on existing topics. I will use the proposed agenda to determine if two 3.5 hour sessions (3 hours of working time) will be sufficient for WPT.

**Comment by stephenmcgruer** [comment]
Two updates:

i. I have reached out to the CSSWG to see if they have any topics they wish to discuss in a joint meeting.
ii. I have added WPT to the 'Community Groups' section of https://www.w3.org/wiki/TPAC/2020/GroupMeetings, currently with an ON HOLD status for the dates described above.

Given there have been no objections to the dates, I intent to mark them CONFIRMED on **Monday September 14th**.

**Comment by stephenmcgruer** [comment]
The TPAC time-slots have now been marked CONFIRMED.

**Comment by zcorpan** [comment]
I've proposed an agenda item [in the doc](https://docs.google.com/document/d/1XhUwVbitdV03eX2GefmokCliWjQdAxBgblwITwNqsgc/edit#): Screen reader automation

**Comment by stephenmcgruer** [comment]
Reminder: WPT at TPAC is happening next week!

**When**: Monday 19th October and Wednesday 21st October, 14:00-17:30 UTC
(hopefully-correct calendar event attached)
**What**: [Agenda](https://docs.google.com/document/d/1XhUwVbitdV03eX2GefmokCliWjQdAxBgblwITwNqsgc/edit#)
**How**: IRC (#testing on irc.w3c.org) and video conferencing (link to be announced via IRC and on the agenda doc on Monday).

Looking forward to seeing you there :)

Thanks,
Stephen (he/him)

https://lists.w3.org/Archives/Public/public-test-infra/2020OctDec/0000.html

**Comment by stephenmcgruer** [comment]
A meeting link has now been added to the agenda.

**Comment by stephenmcgruer** [comment]
Thanks all for a very successful TPAC 2020 meeting! I have put together a summary document, which should be world-readable.

[WPT TPAC 2020 - Summary](https://docs.google.com/document/d/1RxENU4lhLyF9xtgUja9DbghmQmNX8ur0zF-1nHD7Ic4/edit#)

I have also created a wiki page: https://github.com/web-platform-tests/wpt/wiki/TPAC-2020
