### ISSUE TITLE
Allow hiding the page in WPT

### ISSUE THREAD

**Issue by npm1** [web-platform-tests/wpt#25233]
I would like to add a new API to expose the visibility state of the page to PerformanceObserver: see the [explainer](https://docs.google.com/document/d/1l5kHiJRkdQwEN-CYI5_mUNODhQVB5rCyjN4jHDdXDHA/edit#). But it looks like it's not possible to properly test hiding the test page in WPTs. I looked at existing tests for [page-visibility](https://github.com/web-platform-tests/wpt/tree/master/page-visibility) and they are either manual tests or use iframe removal as a way to trigger a visibility change. Is it possible to add support for hiding/minimizing the page, and for bringing it back into view on WPTs?

**Comment by Hexcles** [comment]
So there is a WebDriver command to [minimize window](https://w3c.github.io/webdriver/#minimize-window), but we need to expose it in `testdriver.js`.

There is the other question of whether our environment supports such window management -- at least on Taskcluster we use Fluxbox so we should be fine, but I'm not sure about Azure (Windows and macOS).

**Comment by stephenmcgruer** [comment]
@npm1 - fyi if you'd like to try contributing this yourself we do have [a guide](https://docs.google.com/document/d/18BpD41vyX1cFZ77CE0a_DJYlGpdvyLlx3pwXVRxUzvI/edit#). The testdriver.js side is explained [in this tutorial](https://web-platform-tests.org/writing-tests/testdriver-extension-tutorial.html).

**Comment by noamr** [comment]
I think this can be closed now. Added driver support for minimize/restore [here](https://github.com/web-platform-tests/wpt/pull/31326).

**Comment by npm1** [comment]
Nice, thanks
