### ISSUE TITLE
testharness.js: Promise check in test() is broken

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#25319]
The `test()` function fails when the function it runs returns a value. It then tries to determine if the value is a Promise to suggest using `promise_test()` instead. To do so, it checks if the returned value has an own property called "then".

This does not work correctly, as `then()` is defined in `Promise.prototype`, not `Promise` itself. Quick way to reproduce:

```js
test(async t => {
}, "my test");
```

The harness error is _"Test named "my test" inappropriately returned a value"_ rather than _"Test named "my test" inappropriately returned a value, consider using `promise_test` instead"_.

**Comment by rakuco** [comment]
Tentatively assigning to @jugglinmike because the code was introduced in #12958.

**Comment by stephenmcgruer** [comment]
I fixed this (I believe) in a drive-by in https://github.com/web-platform-tests/wpt/pull/25703
