### ISSUE TITLE
Edge Dev and Canary broken since September 3rd

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#25416]
There have been no successful Edge Dev or Canary runs since September 3rd ([wpt.fyi runs view](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk)). (In fact, I'm not clear when the last successful Edge Canary run was - can't get the wpt.fyi UI to show me one.

[This seems to be one of the failing runs in Azure Pipelines](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=53958&view=logs&jobId=fb986504-a3b0-5067-98f7-ae723bcc030f&j=2b376673-b6b7-55d3-67e2-e8305abf5c1e). (Safari also fails, which is yet another bug to file...)

From a [random log file](https://dev.azure.com/web-platform-tests/b14026b4-9423-4454-858f-bf76cf6d1faa/_apis/build/builds/53958/logs/178), it looks like there's a mismatch in the version of the edge driver vs the version of edge running:

```
2020-09-06T03:34:58.8271204Z  0:24.86 pid:9376 MSEdgeDriver was started successfully.
2020-09-06T03:34:59.2967628Z  0:25.33 INFO Starting runner
2020-09-06T03:35:02.5877283Z  0:27.81 WARNING Failed to start protocol connection
2020-09-06T03:35:02.5878700Z  0:27.81 WARNING Traceback (most recent call last):
2020-09-06T03:35:02.5879708Z   File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\protocol.py", line 47, in setup
2020-09-06T03:35:02.5880504Z     self.connect()
2020-09-06T03:35:02.5881265Z   File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 305, in connect
2020-09-06T03:35:02.5882099Z     self.webdriver.start()
2020-09-06T03:35:02.5882849Z   File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 437, in start
2020-09-06T03:35:02.5883672Z     value = self.send_command("POST", "session", body=body)
2020-09-06T03:35:02.5884543Z   File "C:\Agent\_work\1\s\tools\webdriver\webdriver\client.py", line 490, in send_command
2020-09-06T03:35:02.5885283Z     raise err
2020-09-06T03:35:02.5886218Z SessionNotCreatedException: session not created (500): session not created: This version of MSEdgeDriver only supports MSEdge version 84
2020-09-06T03:35:02.5887226Z 
```

Need to check how both are chosen, to see what might be broken.

**Comment by stephenmcgruer** [comment]
Based on https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=53958&view=logs&jobId=fb986504-a3b0-5067-98f7-ae723bcc030f&j=2b376673-b6b7-55d3-67e2-e8305abf5c1e&t=57b916e7-31b3-59d4-7b57-37a252ccf828, Edge 86 is being installed. This is done by `tools/ci/azure/install_edge.yml`, which installs it from https://go.microsoft.com/fwlink/?linkid=2069324&Channel=Dev&language=en-us

Edgedriver, on the other hand, should come from `tools/wpt/browser.py`, EdgeChromium class, `install_webdriver` method. It should hit https://msedgedriver.azureedge.net/LATEST_DEV (unless `channel` is wrong for some reason), which returns 86 today. So this should download msedgedriver 86 too.

However given that we don't see `Downloading MSEdgeDriver` in the logs, I suspect that we're finding a previously installed version of edgedriver (for 84) in the `_venv` and maybe this is from us not using a clean checkout on Azure Pipelines? (Plus the fact that we have serious problems reusing old stuff in `_venv`...).

Upside, this will hopefully fix itself when the VMs are refreshed today (I believe they are refreshed weekly on Sundays). Downside, we really should address the 'wrong webdriver' version problem with have with `_venv` - it hits Chromium too at the very least.

**Comment by stephenmcgruer** [comment]
Drat, I was hoping the VM refresh on Sunday would have made this go away for now, but it hasn't. Instead, I think we're going to need to land a proper fix that checks the edgedriver version and invalidates it if it doesn't match.

**Comment by stephenmcgruer** [comment]
A few runs have happened now, because I've been playing with the same VMs for another project and so have ended up clearing their `_venv`s for that. It is not a long term fix, and I expect this problem to reoccur shortly. (It's unclear to me why it hasn't bit us many times before.)

**Comment by stephenmcgruer** [comment]
Note: we're back to missing runs again, unsurprisingly.

**Comment by foolip** [comment]
@stephenmcgruer I see you're assigned and this is labeled urgent, so... ping :)

When I've had trouble with Edge in the past I've often gotten help from @mustjab.

**Comment by stephenmcgruer** [comment]
Yeah, this is in a weird semi-urgent state, where it will come and go as the VMs are re-created. There's no work for @mustjab here - we need to fix WPT to stop using incompatible msedgedriver versions. I have a chromedriver equivalent PR in the works atm, and a near identical version will be able to be used for msedgedriver too.

So, err, soon.
