### ISSUE TITLE
Firefox stable broken since September 1st

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#25415]
There have been no Firefox stable runs on wpt.fyi since September 1st ([list of runs](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk)).

Checking the `epochs/daily` branch, looks like all reftests fail; [latest run](https://community-tc.services.mozilla.com/tasks/groups/N-qzAWqJQV-StLOtoR3KIQ). 

Looking at [one log](https://community-tc.services.mozilla.com/tasks/XRXtY3VqQ7CyvnrZ--Kf6g/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FXRXtY3VqQ7CyvnrZ--Kf6g%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log), it looks like Firefox is failing to start:

```
 7:03.02 INFO Application command: /home/test/build/firefox/firefox --marionette about:blank -profile /tmp/tmp5d3txd
 7:03.03 pid:2456 Full command: /home/test/build/firefox/firefox --marionette about:blank -profile /tmp/tmp49Kkgv
pid:2456 console.error: SearchCache: "_readCacheFile: Error reading cache file:" (new Error("", "(unknown module)"))
 7:03.03 pid:2456 1599355969164	Marionette	INFO	Listening on port 54715
 7:03.03 INFO Starting runner
 7:03.19 INFO Browser exited with return code -15
 7:03.19 INFO PROCESS LEAKS None
 7:03.19 WARNING Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executormarionette.py", line 1025, in teardown
    self.executor.protocol.marionette._send_message("reftest:teardown", {})
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/decorators.py", line 36, in _
    m._handle_socket_failure()
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/marionette.py", line 654, in _handle_socket_failure
    reraise(exc_cls, exc, tb)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/decorators.py", line 26, in _
    return func(*args, **kwargs)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/marionette.py", line 594, in _send_message
    msg = self.client.request(name, params)
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/transport.py", line 276, in request
    return self.receive()
  File "/home/test/web-platform-tests/_venv2/lib/python2.7/site-packages/marionette_driver/transport.py", line 162, in receive
    raise socket.error("No data received over socket")
error: No data received over socket

 7:03.19 INFO Closing logging queue
 7:03.19 INFO queue closed
 7:03.19 CRITICAL Max restarts exceeded
 7:03.19 INFO PROCESS LEAKS None
 7:03.24 INFO Browser exited with return code -15
 7:03.24 INFO Got 0 unexpected results
 7:03.24 SUITE_END
```

This may be a new version of Firefox stable, or may be a change in WPT. Digging up the working --> failed commit range for the latter first.

**Comment by stephenmcgruer** [comment]
Regression range in WPT would be 7da1d06...17f8f00 .

As a random guess, https://github.com/web-platform-tests/wpt/commit/c911d7f3d04d090514119ae80011098df9f6add1 mentions marionette and seems like it could break things. I'll see if I can reproduce locally and try reverting that if so.

**Comment by stephenmcgruer** [comment]
Yep, able to reproduce with Firefox stable locally, and reverting https://github.com/web-platform-tests/wpt/commit/c911d7f3d04d090514119ae80011098df9f6add1 fixes it.

@jgraham - should we just revert that PR entirely, or would you like to pursue a different fix?

**Comment by emilio** [comment]
cc @whimboo

**Comment by jgraham** [comment]
Bleh. We removed an assert on the marionette side that's going to fail until that patch reaches stable. I think this requires a hack in wptrunner to just set the chrome context for older Firefox versions :(

**Comment by whimboo** [comment]
Sorry for having caused this trouble. But good to see that @jgraham has already a fix ready. I will remember to test with stable whenever I do changes to the marionette reftest harness.

**Comment by stephenmcgruer** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/25423
