### ISSUE TITLE
Sink task failing for unclear reason

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#25610]
I'm wondering if someone can check why the sink task is failing in:
https://github.com/web-platform-tests/wpt/pull/25560

The taskcluster log doesn't seem to provide anything actionable (at least that I can see :( ):
https://community-tc.services.mozilla.com/tasks/UKR9mDn2TRyaynTB1U17rQ/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FUKR9mDn2TRyaynTB1U17rQ%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by stephenmcgruer** [comment]
The `sink-task` is just how we make our dynamic task graph work with GitHub's requirement that we name a specific task as 'blocking' for PRs. (Sounds like I should document that clearer in the checks view!).

The actual failure will be the other failing Taskcluster checks. In your case, looks like that's `wpt-firefox-nightly-stability`. Clicking through to the [details](https://github.com/web-platform-tests/wpt/pull/25560/checks?check_run_id=1131659274), `payment-request/allowpayment/no-attribute-same-origin-bc-containers.https.html` flaked. Given that all you did (I think?) was rename a variable + move the file, I'd consider this existing flake and am happy to admin-merge the PR if you would like :)

**Comment by jgraham** [comment]
We should make the sink task produce an artifact that explains this and links to the actual failures.

**Comment by jgraham** [comment]
Oh you said that, never mind me.

**Comment by marcoscaceres** [comment]
@stephenmcgruer, thanks for clarifying - that makes sense. I didn't realize they were dependent on each other. Would appreciate the merge of #25560, as we've updated the HTML spec and Payment Request Spec already.
