### ISSUE TITLE
Error installing webkit2gtk-driver (stable) on Taskcluster

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#25653]
Example: https://community-tc.services.mozilla.com/tasks/ZLj3LIVnQ9iEGXOs7Wktvg/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FZLj3LIVnQ9iEGXOs7Wktvg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L752

> sudo apt-get -qqy -t bionic-wpt-webkit-updates install webkit2gtk-driver
> E: Unable to correct problems, you have held broken packages.

**Comment by Hexcles** [comment]
cc @clopez

**Comment by stephenmcgruer** [comment]
Assuming that this is blocking runs, marking `urgent`. Feel free to downgrade if it isn't.

**Comment by clopez** [comment]
This failed log is for the webkitgtk stable runs, not for the nightlies.

The packages for the stable channel we currently provide are deprecated (very likely not even working anymore on Ubuntu-20.04) and I intend to revamp that on PR #25263  

I'm currently on holidays until next Monday (28th sept). I will try to push that PR to land it as soon as I get back to work.. and this will get fixed once that PR lands.

You can close this and mark it as duplicated of that PR if you wish

**Comment by Hexcles** [comment]
#25263 has landed (woohoo!). Thanks, @clopez !

Please feel free to close this if anyone can verify that WebGTK reappears **tomorrow** on https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk (maybe cc @KyleJu )

**Comment by KyleJu** [comment]
> #25263 has landed (woohoo!). Thanks, @clopez !
> 
> Please feel free to close this if anyone can verify that WebGTK reappears **tomorrow** on https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk (maybe cc @KyleJu )

Yep, I will keep an eye on it tomorrow.

**Comment by KyleJu** [comment]
WebGTK is back running. I will close this bug @Hexcles
