### ISSUE TITLE
[Python3] encoding import error with threaded calls to Python file handlers

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#25678]
In investigating Python 3, @ziransun came across an interesting case where wptserve throws when trying to call `encode` in a Python file handler. The problem has been seen on Linux + Chrome, MacOS + Safari, and Windows + Edge, but I will stick to Linux + Chrome here as the easiest setup for me to test.

As it appears to be a threading issue, it is flaky to reproduce, but a failing run looks like:

```
$ ./wpt run --log-mach=- --channel=dev chrome html/infrastructure/urls/resolving-urls/query-encoding/utf-8.html?include=css
...
  File "/home/smcgruer/github/wpt/tools/wptserve/wptserve/handlers.py", line 351, in __call__
    rv = self.func(request, response)
  File "/home/smcgruer/github/wpt/html/infrastructure/urls/resolving-urls/query-encoding/resources/css-tmpl.py", line 7, in main
    return [(b"Content-Type", b"text/css; charset=%s" % encoding)], sheet.encode(isomorphic_decode(encoding))
  File "/home/smcgruer/miniconda3/lib/python3.8/encodings/__init__.py", line 98, in search_function
    mod = __import__('encodings.' + modname, fromlist=_import_tail,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 682, in _load_unlocked
KeyError: 'encodings.cp1252'
```

In discussions with @Hexcles , he suggested that that may have something to do with the way we play with the path and modules when executing Python file handlers: https://github.com/web-platform-tests/wpt/blob/master/tools/wptserve/wptserve/handlers.py#L287

```
        sys_path = sys.path[:]
        sys_modules = sys.modules.copy()
        try:
            environ = {"__file__": path}
            sys.path.insert(0, os.path.dirname(path))
            with open(path, 'rb') as f:
                exec(compile(f.read(), path, 'exec'), environ, environ)

            if func is not None:
                return func(request, response, environ, path)

        except IOError:
            raise HTTPException(404)
        finally:
            sys.path = sys_path
            sys.modules = sys_modules
```

His theory is that the `encoding` imports setup some sort of state that is being cached and not reset by the sys.path and sys.modules reset, but this is unproven yet.

**Comment by stephenmcgruer** [comment]
Note that historically speaking doing imports (including the implicit imports from calling `encode`) whilst threading was problematic in Python 2.7 - https://docs.python.org/2/library/threading.html#importing-in-threaded-code - but that this is meant to be resolved in Python 3. So there's a world where this is still a Python 3 bug, but I do give @Hexcles theory some credence.

**Comment by stephenmcgruer** [comment]
cc @jgraham @gsnedders

**Comment by jgraham** [comment]
Right, so I guess there are a couple of problems here. In multithreaded code it's pretty obviously unsafe to do the edit-and-restore thing with the caches. That's where @gsnedders suggestion of a mutex would help. But that's really problematic and I think is likely to lead to random timeouts in tests. A python handler that did e.g. `time.sleep(5)` would block any other handlers running. So we really can't do that. The second problem is that any additional caches that we don't handle here could still lead to a partially cached state for used modules.

I can see two options, neither of which is simple, so hopefully I'm missing something.
1. Run the handlers in a seperate process which then doesn't share global state with other handlers. This has the advantage that it's proper OS-level sandboxing and the disadvantage that it will have noticable performance overhead
2. Write a custom `__import__` function and use it in handlers in such a way that they don't share state. I'm still reading the details here, but this at least looks plausible.

**Comment by Hexcles** [comment]
Sigh, re `sys.modules`: "However, replacing the dictionary will not necessarily work as expected and deleting essential items from the dictionary may cause Python to fail." https://docs.python.org/3/library/sys.html#sys.modules

Reading https://docs.python.org/3/library/functions.html#exec, I wonder if we can pass a separate `globals` to `exec` (an empty one or perhaps a deep copy of `globals()`)?

**Comment by jgraham** [comment]
I think we're already passing in `globals`. I don't think that's enough.

**Comment by stephenmcgruer** [comment]
I don't know if I'm holding this wrong, but the copying/restoration of `sys.modules` doesn't seem to work for the simplest case I can think of today:

```python
$ cat css/myhandler.py 
from utils import return_hello

def main(request, response):
    response.headers.set(b"Cache-Control", b"no-cache")
    response.content = return_hello()
$ cat css/utils.py 
def return_hello():
    return 'hello\n'
$ cat html/myotherhandler.py 
from utils import return_hello

def main(request, response):
    response.headers.set(b"Cache-Control", b"no-cache")
    response.content = return_hello()
$ cat html/utils.py 
def return_hello():
  return 'surprise this is not hello!\n'
$ wget -q -O - http://localhost:8000/css/myhandler.py
hello
$ wget -q -O - http://localhost:8000/html/myotherhandler.py
hello
```

Did I do something silly here?

**Comment by stephenmcgruer** [comment]
Based on `find . -type d \( -path ./tools -o -path ./webdriver \) -prune -false -o -name '*.py' | xargs grep -rl "def main" | xargs grep -rh from.*import | sort | uniq -c | sort -n`, we seem to have exactly one relative-path imported file in the entire tree today, `cookies/resources/helpers.py`.

```
      1 from base64 import b64decode
      1 from base64 import decodestring
      1     from cgi import escape
      1 from datetime import datetime
      1     from genshi.template import MarkupTemplate
      1 from hashlib import sha512, sha256, md5
      1 from hashlib import sha512, sha384, sha256, md5
      1 from helpers import makeCookieHeader, readParameter, setNoCacheAndCORSHeaders
      1 from helpers import makeDropCookie, readParameter, setNoCacheAndCORSHeaders
      1 from helpers import setNoCacheAndCORSHeaders
      1     from html5lib.tests import support
      1     from html import escape
      1         from json import JSONEncoder
      1 from os import listdir
      1 from random import randint
      1 from six import range
      1 from six import text_type
      1 from six.moves import range
      1 from six.moves import xrange
      1 from six.moves.urllib import parse
      1 from six.moves.urllib.parse import parse_qs
      1 from six.moves.urllib.parse import parse_qs, quote
      1 from six.moves.urllib.parse import urlencode, urlparse
      1 from time import sleep
      1 from wptserve.handlers import HTTPException
      1 from wptserve import pipes
      1       import * as module from './imported-module-script.js';
      2 from base64 import b64encode
      2 from helpers import makeCookieHeader, setNoCacheAndCORSHeaders
      2 from os import path, listdir
      2 from .utils import return_hello
      2 from wptserve.handlers import json_handler
      3 from helpers import makeDropCookie, setNoCacheAndCORSHeaders
      3 from os import path
      3 from six import BytesIO
      4 from six import int2byte
      4 from six import PY3
      4 from six.moves.urllib.parse import unquote
      6 from __future__ import print_function
     12 from wptserve.utils import isomorphic_decode, isomorphic_encode
     37 from wptserve.utils import isomorphic_encode
     75 from wptserve.utils import isomorphic_decode
```

**Comment by stephenmcgruer** [comment]
So given the above, I think I would actually propose making it part of the contract that relative imports are known to collide, and solve this one of two ways:

* Allow relative imports in a python file handler, but acknowledge they might collide and have a PRESUBMIT to try to sniff out collision cases, **or**
* Allow relative imports in a python file handler, but only from a known directory that wptserve adds to its path, so that folks have to put their files there and collisions won't be possible.

I also wonder if it would be good to have the file handlers be imported by wptserve instead of `exec'd` in this proposed world, but that's a different conversation I think :).

**Comment by stephenmcgruer** [comment]
Argh, thanks to discussion with @jgraham I realize I was mixing up relative and absolute imports in my head. I am editing all my comments above to avoid confusion from this mistake -_-.

For clarity, this **is** a relative import: `from .utils import myfunc`. This is **not** a relative import: `from utils import myfunc`.

Based on this, I have a new proposal: ban relative imports entirely in Python helper scripts, and use my old option #2 for absolute imports of 'local' helpers:

> Allow local imports (i.e. `from utils import helper_func`) in a python file handler, but only from a known directory that wptserve adds to its path, so that folks have to put their files there and collisions won't be possible.

**Comment by jgraham** [comment]
If we do `from utils import helper_func` in two different directories, do they end up with different keys in sys.modules (i.e. will the second one end up trying to import `helper_func` from the `utils` module provided by the first)?

**Comment by jgraham** [comment]
Ah, I see, a global directory. The ergonomics of that seem pretty poor. Unless we made wpt itself a module and you could do something like `from wpt.css.images3 import my_helper`, which would mean having `__init__.py` files in lots of intermediate paths (unless there's some import hackery we could do to make that work).

**Comment by gsnedders** [comment]
> which would mean having `__init__.py` files in lots of intermediate paths (unless there's some import hackery we could do to make that work)

Does https://www.python.org/dev/peps/pep-0420/ not solve that (shipped Py 3.3 and later)?

**Comment by Hexcles** [comment]
It seems that the party has moved on to discussing restricting relative imports, etc., but I wanted to circle back to the original issue at hand: restoring `sys.modules`.

I found this [SO answer](https://stackoverflow.com/a/42147789) and verified that it's still true as of Python 3.9 (part of the import system is implemented in C and holds onto a reference to the original `sys.modules` so replacing it in Python land would cause problems).

However, deleting/popping items from `sys.modules` *should* work. It's not only widely used inside `importlib`, but also a part of a [documented hack](https://docs.python.org/3/reference/import.html#fnlo) that replaces an item in `sys.modules`.

So my proposal is: take a copy of `sys.modules`, exec the code, check `sys.modules` against the snapshot and pop any new items. Note that I'm less sure about inserting deleted items back into `sys.modules`, but let's hope custom handlers would never do that?

Replace
https://github.com/web-platform-tests/wpt/blob/5fcc1c2184a256ba8f684f4b12c6ec5543e62313/tools/wptserve/wptserve/handlers.py#L316-L318
with
```python
        finally:
            sys.path = sys_path
            for m in list(sys.modules.keys()):  # important to create a list as we'll modify the dict
                if m not in sys_modules:
                    sys.modules.pop(m)
```

**Comment by jgraham** [comment]
I fully support trying that approach; it seems simpler than anything else.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/26111 although I realised whilst I was writing it that it doesn't address the underlying problem that we have multiple threads making possibly conflicting changes to a shared data structure. But it does at least make the code work as it was originally intended to.

**Comment by stephenmcgruer** [comment]
> I found this SO answer and verified that it's still true as of Python 3.9 (part of the import system is implemented in C and holds onto a reference to the original sys.modules so replacing it in Python land would cause problems).

Wow, that's an amazing find! Great job on discovering why replacing sys.modules doesn't work.

> #26111 although I realised whilst I was writing it that it doesn't address the underlying problem that we have multiple threads making possibly conflicting changes to a shared data structure. But it does at least make the code work as it was originally intended to.

Right, this potentially makes things worse in the presence of threads because we've gone from a 'simple' variable assignment (not necessarily simple in Python!) to a more complex interaction. That said, if this change unblocks our Py3 move and we're still intending to address the wider broken situation we're in then I'd be ok to see it pursued.

**Comment by stephenmcgruer** [comment]
> That said, if this change unblocks our Py3 move and we're still intending to address the wider broken situation we're in then I'd be ok to see it pursued.

Based on @Hexcles comment in the PR, it unfortunately does not fix the original problem of *this* issue, which was the exception in Py3. It may still be an improvement worth landing because it (in theory) makes local absolute imports not incorrectly cache between handlers.

**Comment by stephenmcgruer** [comment]
This was fixed by https://github.com/web-platform-tests/wpt/pull/26328
