### ISSUE TITLE
No Edge runs scheduled since ~September 24th

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#25923]
This looks like an infra issue on the Azure Pipelines side. If you check the `epochs/three_hourly` and `epochs/daily` lists, every run since September 24th shows as 'pending' with all Edge Dev/Canary jobs listed as 'Queued'.

* https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=9077%2C9077
* https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=1091

Assigning to @mustjab since I think something on the Azure Pipelines side will need kicked.

**Comment by stephenmcgruer** [comment]
Note: for recovery, I'd be happy to cancel all old jobs and just skip it up to the most recent runs, rather than trying to catch up with a weeks worth of runs!

**Comment by mustjab** [comment]
Sorry about this, look like scheduled runs to rebuild Windows VMs didn't run for a few weeks and existing VM pool expired. I've kicked off run to re-create the VMs and will monitor runs to make sure they complete. I think it makes sense to cancel all of the old jobs and just focus on getting new Edge runs to complete.

**Comment by stephenmcgruer** [comment]
@mustjab It looks like things are running, but the old jobs weren't cancelled so its still churning through builds from about a week ago (and is likely to take a long time to catch-up). I tried to find a way to cancel jobs on Azure Pipelines but wasn't able to (perhaps I don't have the right permissions). Can you cancel all the old pending `epochs/three_hourly` and `epochs/daily` runs?

**Comment by mustjab** [comment]
Canceled all of the queued jobs that were waiting only on Edge run, see only two left, one that's still running and one that's queued but is still running non-Edge jobs, so left it alone.

**Comment by stephenmcgruer** [comment]
Thanks @mustjab , we appear to be at almost-HEAD now. Looks like we're processing a run from last night, with another one from this morning queued up.

I do wonder if we need to either increase the machine pool or lower Edge Dev runs to every-6-hours however; it feels like at best we are only *just* keeping up with runs each day, probably relying on quieter overnight periods to catch up... :/.

But for now, I'll close this since the bleeding has stopped. Thanks for your efforts here!
