### ISSUE TITLE
Update to more recent Safari?

### ISSUE THREAD

**Issue by svgeesus** [web-platform-tests/wpt#25933]
wpt.fyi reports that the Webkit tests are using **Safari 112 preview**, on macOS 10.15.

The current is **113 preview,** and [the release notes](https://developer.apple.com/safari/technology-preview/release-notes/) show a bunch of improvements in Web Audio API.

So, is it possible to get the version run by wpt.fyi updated?

**Comment by svgeesus** [comment]
Huh, the version number has updated to 113, but a few hours ago it was 112. Awesome!

**Comment by stephenmcgruer** [comment]
It's been 113 for ~3 weeks now (https://github.com/web-platform-tests/wpt/pull/25469). We update mostly-automatically (with human review), so we're generally not very far behind at all.

Looking at wpt.fyi's recent runs for Safari (https://wpt.fyi/runs?label=master&from=2020-09-24T00%3A00&product=safari), I don't see any 112 either (though it is a pain to mouseover for the tooltip!)

But glad its working for you :)
