### ISSUE TITLE
Re-write (parts of?) cookie directory test infrastructure

### ISSUE THREAD

**Issue by miketaylr** [web-platform-tests/wpt#26190]
Right now a large portion of cookies/http-state/ is broken due to clearing of cookies not working. And the domain and path tests just don't work as designed (because they are hard-coded for `example.org` domains). 

Rather than fix that, it seems nicer to just re-write them.

@annevk gave a nice suggestion for how this might be achieved

 > one thing I'd like to see is that instead of having a lot of little test
files, we instead have a JSON representation for input and expected
output so we can store all the tests in a single file (and easily add
new ones). And ideally the harness around that would support the full
data model of cookies, including non-UTF-8 bytes

Related issues: 
https://github.com/web-platform-tests/wpt/issues/23482 - dynamically add the domain attribute and location header to domain tests
https://github.com/web-platform-tests/wpt/issues/26055 - create testdriver API for clearing cookies
https://github.com/web-platform-tests/rfcs/pull/39/files - add a `.www` file name flag

**Comment by annevk** [comment]
One thing to keep in mind while designing this is that (if we end up standardizing on Chrome's model of cookies, which seems to be the most web-compatible) there are effectively two data models at play:

* `Set-Cookie`: takes bytes as per [header value](https://fetch.spec.whatwg.org/#concept-header-value). (Not entirely defined in detail.)
* `document.cookie`: takes a scalar value string and UTF-8 encodes that and gives it to `Set-Cookie` (more or less, not entirely defined either). (And the getter will not return cookies for which UTF-8 decode ends up failing as far as I can tell.)

The superset of this would be to always have bytes and only some of these are UTF-8 bytes (represented as JSON strings), but for convenience we might also want to support strings that we UTF-8 encode.

And then there's the question whether we put some logic in the harness for determining which APIs to test and how with the test input or whether to put that information with the test input itself. (I have a slight preference for logic to make test writing easier, but I know others prefer the other way around and I don't care strongly either way.)

**Comment by miketaylr** [comment]
I think we can close this -- I still want to re-write more things, but don't think this needs to be open forever.
