### ISSUE TITLE
`wpt run` fails on Python 3.9 on Windows, needs pillow 8.0.0

### ISSUE THREAD

**Issue by saschanaz** [web-platform-tests/wpt#26264]
```
  C:\Users\Kagami\AppData\Local\Temp\pip-install-gliq5ciq\pillow\setup.py:28: RuntimeWarning: Pillow does not yet support Python 3.9 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.
```

Currently WPT is using pillow 6.2.2 which only supports Python 3.8. Version 8.0.0 added 3.9 support: https://github.com/python-pillow/Pillow/issues/4953

**Comment by gsnedders** [comment]
Need to make the requirements  pin to <7 on Py2 and a bumpable, up-to-date version on Py3.
