### ISSUE TITLE
Azure Pipelines jobs being cancelled due to errors provisioning resources

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#26329]
This is affecting PRs, which aren't getting results for Safari.

Based on https://dev.azure.com/web-platform-tests/wpt/_settings/agentqueues?queueId=21&view=jobs, this started around 5:30am this morning. 

It also will be affecting full test-suite runs, e.g. the last four `three_hourly` runs have failed: https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&repositoryFilter=1&branchFilter=9077%2C9077%2C9077

@mustjab - is this something you can help resolve?

**Comment by mustjab** [comment]
Can you try to enable system.debug variable (set the value to true), then trigger a build to capture and share the complete logs.

This seems to happen every now and then: https://developercommunity.visualstudio.com/content/problem/946259/an-error-occurred-while-provisioning-resources-azu.html

Can you report this issue to Azure Pipelines on the developer community page. Let me know if you don't get a response and I can try to ping the team as well.

**Comment by stephenmcgruer** [comment]
@mustjab - debug PR is https://github.com/web-platform-tests/wpt/pull/26363, https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=56820&view=results is a reproduction with system.debug set to true. Doesn't seem to affect the logs I get.

Will file a developer report (though note that https://developercommunity.visualstudio.com/content/problem/946259/an-error-occurred-while-provisioning-resources-azu.html has a HSTS certificate error!) .

**Comment by stephenmcgruer** [comment]
Filed https://developercommunity.visualstudio.com/content/problem/1241184/an-error-occurred-while-provisioning-resources-azu-1.html

**Comment by mustjab** [comment]
There is a known incident with MacOS provisioning: https://status.dev.azure.com/_event/212096467

**Comment by stephenmcgruer** [comment]
The incident is marked resolved as of 2020/11/02 8pm EST. Most of our pipeline jobs are now running, but I see a few recently cancelled in https://dev.azure.com/web-platform-tests/wpt/_settings/agentqueues?queueId=21&view=jobs

Keeping this open for now to monitor, but will close later today if the pipeline continues to flow correctly.

**Comment by stephenmcgruer** [comment]
Everything looking good now, closing.
