### ISSUE TITLE
[css-flexbox] issue with the references for gap-006-*?

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#26326]
These are the tests in question: [gap-006-lr.html](https://wpt.fyi/results/css/css-flexbox/gap-006-lr.html?run_id=721050002&run_id=736480001&run_id=728600003&run_id=738380003&run_id=730670002&run_id=747840008), [gap-006-ltr.html](https://wpt.fyi/results/css/css-flexbox/gap-006-ltr.html?run_id=721050002&run_id=736480001&run_id=728600003&run_id=738380003&run_id=730670002&run_id=747840008), [gap-006-rl.html](https://wpt.fyi/results/css/css-flexbox/gap-006-rl.html?run_id=721050002&run_id=736480001&run_id=728600003&run_id=738380003&run_id=730670002&run_id=747840008), [gap-006-rtl.html](https://wpt.fyi/results/css/css-flexbox/gap-006-rtl.html?run_id=721050002&run_id=736480001&run_id=728600003&run_id=738380003&run_id=730670002&run_id=747840008)

I'm interested in the Firefox failure, but included WebKitGTK and Servo results in case they provide clues. Here are the (cropped) actual and expected for gap-006-ltr.html in Firefox:

![image](https://user-images.githubusercontent.com/498917/97564778-62c1b800-19e5-11eb-8438-17304a6da4b8.png)

![image](https://user-images.githubusercontent.com/498917/97564825-73722e00-19e5-11eb-8eed-c118380d245f.png)

I suspect the problem here is really with the reference here, because when I open https://wpt.live/css/css-flexbox/gap-006-ltr.html or https://wpt.live/css/css-flexbox/gap-006-ltr-ref.html in Chrome or Safari, they look like the *actual* Firefox rendering.

The reference also uses Flexbox, so there's probably an interop issue here, but actually not with gap?

@argyleink (test author) @davidsgrogan @aethanyc would any of you like to take a look?

**Comment by argyleink** [comment]
afaict, this is an interop issue that's unrelated to gap and is closer to flex alignment

**Comment by foolip** [comment]
Can the references here be turned into test (for flex alignment) in themselves and the references changes to use some other technique that will be consistent?

**Comment by davidsgrogan** [comment]
So what we need to do is

(1) Take the current gap-006-ltr reference, make it a separate wpt and figure out why engines don't render it the same.
(2) Change the gap-006-* tests to not be affected by this difference.

@argyleink do you want to do this or do you want me to?

**Comment by argyleink** [comment]
![image](https://user-images.githubusercontent.com/1134620/97628205-a0284480-19e9-11eb-8d42-e266af20dea2.png)

Firefox Nightly not showing the issue for me, and it should be right? I can't make any of my browser versions reproduce the issue shown in the WPT tests reference. Is anyone able to recreate the issue in a local environment?

**Comment by davidsgrogan** [comment]
Yeah, I see the problem in Firefox nightly. Maybe that means it's a text measurement thing that is environment dependent.
![Screen Shot 2020-10-29 at 2 15 37 PM](https://user-images.githubusercontent.com/1801875/97633461-5fccc480-19f1-11eb-970b-e1b89549c8e3.png)

**Comment by argyleink** [comment]
confirmed, i can reproduce only with Firefox Nightly on Linux

**Comment by argyleink** [comment]
![nightly-flexbox](https://user-images.githubusercontent.com/1134620/97639129-31ec7d80-19fb-11eb-8e4f-908982318d77.gif)

**Comment by foolip** [comment]
@stephenmcgruer is there a straightforward way to tell if this test has always been failing in Firefox, to rule out that it's just a regression in Nightly? (If it is then maybe the test could be left unchanged.)

**Comment by davidsgrogan** [comment]
I recall that this has always been failing, but I am interested to hear how to query for that info :)

**Comment by davidsgrogan** [comment]
And, I'm 99% sure this isn't a bug in Firefox, just an unfortunate effect of Chrome and Firefox giving the default font different sizes.

We'll fix the reference to work in both browsers.
