### ISSUE TITLE
"epochs", "pr-preview-sync",  "Regenerate WPT certificates" scheduled workflows disabled

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#26335]
@web-platform-tests/admins 

Dear fellow advanced GitHub colleagues,

I received today 3 short auto-generated emails notifying me of the disability of 3 scheduled workflows and inviting me to restart these, then to click a link: 

{
[GitHub] The "epochs" workflow in TalbotG/web-platform-tests has been disabled
From 	GitHub <noreply@github.com>
Date 	Today 09:51 AM

Scheduled workflows are disabled automatically after 60 days of repository inactivity.

If you would like the "epochs" workflow to continue running, click the link bellow.

[link snipped]

[GitHub] The "pr-preview-sync" workflow in TalbotG/web-platform-tests has been disabled
From 	GitHub <noreply@github.com>
Date 	Today 10:27 AM

Scheduled workflows are disabled automatically after 60 days of repository inactivity.

If you would like the "pr-preview-sync" workflow to continue running, click the link bellow.

[link snipped]

[GitHub] The "Regenerate WPT certificates" workflow in TalbotG/web-platform-tests has been disabled

From 	GitHub <noreply@github.com>
Date 	Today 01:14 PM

Scheduled workflows are disabled automatically after 60 days of repository inactivity.

If you would like the "Regenerate WPT certificates" workflow to continue running, click the link bellow.

[link snipped]
}

I have no idea what these are, what this means, where those scheduled are, who created them and why. Please advise.

Gérard

**Comment by stephenmcgruer** [comment]
These are all [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/introduction-to-github-actions) run on the WPT repository to perform various automated tasks.

Historically, GitHub has done a bad job of handling actions in forks of respositories - they often tried to run but broke (e.g. if they rely on [GitHub Secrets](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) that won't be available in the fork), or confused people who forked a repository (as you see here!).

I believe recently GitHub have been moving to make things 'easier' for forks with regards to actions, and possibly this auto-disable is part of it.

Generally I would advise ignoring these emails.

(Closing; please feel free to re-open if you have more questions about this :).)
