### ISSUE TITLE
Some tests in html/cross-origin-opener-policy/reporting/navigation-reporting reported "badly formed hexadecimal UUID string" 

### ISSUE THREAD

**Issue by ziransun** [web-platform-tests/wpt#26429]
Some test in html/cross-origin-opener-policy/reporting/navigation-reporting, e.g. 

```
report-only-same-origin-report-to.https.html
reporting-popup-same-origin.https.html
```

end with TIMEOUT due to `"badly formed hexadecimal UUID string" `

Traceback is as follow:

```
0:32.46 WARNING Traceback (most recent call last):
  File "/wpt/tools/wptserve/wptserve/handlers.py", line 368, in __call__
    rv = self.func(request, response)
  File "wpt/html/cross-origin-opener-policy/reporting/resources/dispatcher.py", line 14, in main
    queue = stash.take(uuid)
  File "wpt/tools/wptserve/wptserve/stash.py", line 180, in take
    internal_key = self._wrap_key(key, path)
  File "wpt/tools/wptserve/wptserve/stash.py", line 155, in _wrap_key
    return (isomorphic_encode(path), uuid.UUID(key).bytes)
  File "/usr/lib/python3.6/uuid.py", line 140, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
```
@Hexcles: Is this expected?

**Comment by Hexcles** [comment]
Based on https://wpt.fyi/results/html/cross-origin-opener-policy/reporting/navigation-reporting/reporting-popup-same-origin.https.html?label=master&label=experimental&aligned&q=html%2Fcross-origin-opener-policy%2Freporting%2Fnavigation-reporting, it seems that the test behaves well in Python 2 so this is a Py3-only issue.

It definitely shouldn't happen.

Could you log before this line what `key` is?
https://github.com/web-platform-tests/wpt/blob/54eccf7623b98c2242853e2c7939c787fdde6c2b/tools/wptserve/wptserve/stash.py#L166

**Comment by ziransun** [comment]
@Hexcles:

> Some test in html/cross-origin-opener-policy/reporting/navigation-reporting, e.g.
> 
> ```
> report-only-same-origin-report-to.https.html
> reporting-popup-same-origin.https.html
> ```
> 
> end with TIMEOUT due to `"badly formed hexadecimal UUID string" `

In my local runs, this happened in both Py2 and Py3. Tests passed though. 


> Could you log before this line what `key` is?
> 
> https://github.com/web-platform-tests/wpt/blob/54eccf7623b98c2242853e2c7939c787fdde6c2b/tools/wptserve/wptserve/stash.py#L166

For Python 3, I have 
```
0:21.12 INFO STDOUT: key is:
0:21.12 INFO STDOUT: b'7b48fe0f-bb39-49f7-bb38-69c29cba647b'
```

For Python 2, I have
```
0:29.72 INFO STDOUT: key is:
0:29.72 INFO STDOUT: de436f4d-2ec1-401f-9114-5fb72c5e7455

```

**Comment by ziransun** [comment]
@Hexcles: as you may see from above PR, the error is caused by assigning "5" as uuid, which fails at checks [here](https://github.com/python/cpython/blob/master/Lib/uuid.py#L173)

**Comment by ziransun** [comment]
Close the issue as it has been addressed at https://github.com/web-platform-tests/wpt/pull/26776
