### ISSUE TITLE
Edge Canary broken since Nov 4

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#26435]
There have been no successful Edge  Canary runs since Nov 4([view here](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk))

[The Azure Pipelines](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=57120&view=logs&j=2b376673-b6b7-55d3-67e2-e8305abf5c1e&t=898f303f-4a65-539a-fe97-199939e2aef1) have been failing consistently due to a pip error:

> pip is not recognized as an internal or external command

**Comment by KyleJu** [comment]
On a side note, it appears that https://dev.azure.com/web-platform-tests/wpt/_build?definitionId=1&_a=summary&view=runs requires login now but I can still view individual runs directly

**Comment by KyleJu** [comment]
cc @mustjab @stephenmcgruer

**Comment by mustjab** [comment]
This is due to python38 installer tests that we've been running on Windows machines. I've rebuilt the Windows images to clean state, which should resolve this issue.

**Comment by KyleJu** [comment]
Thanks for the quick reply! I will keep an eye on the run today

**Comment by KyleJu** [comment]
Runs are back. Closing this bug
