### ISSUE TITLE
Link to RFC process from testdriver extension tutorial

### ISSUE THREAD

**Issue by miketaylr** [web-platform-tests/wpt#26779]
Seems useful to prevent any surprises.

**Comment by stephenmcgruer** [comment]
Note that we don't currently tell people in that tutorial that they have to do an RFC at all. So rather than just link to the process, I think we'd need to explain our philosophy and requirements there too.

I can own this if it's too much work for a generous drive-by contribution :)

**Comment by miketaylr** [comment]
I'm happy to take a stab at it -- my current thinking was just a reminder that the process exists would have been useful for me, but I agree we could add a section somewhere in the doc explaining the how and why of RFCs. I don't think it would need to be that big.
