### ISSUE TITLE
Missing stable runs for Chrome and Firefox since Dec.5

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#26800]
Stable runs as of Dec. 8: https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

Azura/Safari ran yesterday at SHA [2a32848](https://github.com/web-platform-tests/wpt/commit/2a32848ae0f2bbc07ed046a6a343fd488aaf98d6)
The checks for this commit appear as "queued" in Github but clicking through to TaskCluster, they appear to have completed (https://community-tc.services.mozilla.com/tasks/groups/JMVKDMPoRnCMZLts29LAkA)

So maybe some kind of disconnect between the github checks and taskcluster?

**Comment by LukeZielinski** [comment]
...that said, there are experimental runs happening for Chrome and FF (https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) so it's possible this could resolve on its own on the next run, but still not clear what the disconnect is.

**Comment by LukeZielinski** [comment]
@jgraham any thoughts on this? Same thing happened for yesterday's daily run (SHA [d98e17b](https://github.com/web-platform-tests/wpt/commit/d98e17bd646fa0e5ca4e6a8ef9f4cf7b20c0ac53)) and I've seen a couple of export PRs get stuck on it as well.

**Comment by LukeZielinski** [comment]
Files https://github.com/taskcluster/taskcluster/issues/4074 against TaskCluster for help on their end.

**Comment by LukeZielinski** [comment]
The taskcluster bug was just fixed, lets see if stable runs come back tomorrow...

**Comment by LukeZielinski** [comment]
Still happening as of [5bde9c8](https://github.com/web-platform-tests/wpt/commit/5bde9c804c5518203cd4ed2fefafc7638a382ce5), following up on TC bug

**Comment by LukeZielinski** [comment]
Need to wait for next TC release (39.1.0) to pull in this fix.

**Comment by stephenmcgruer** [comment]
Seems recovered as of Dec 11th, tentatively closing .
