### ISSUE TITLE
/cors/basic.htm "Same domain basic usage" fails in the same way on all browsers

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#26849]
Behold: https://wpt.fyi/results/cors/basic.htm?run_id=5681964860309504&run_id=5636499091488768&run_id=5635783039909888&run_id=5195490306031616

In all browsers, it appears that this assert failed:

https://github.com/web-platform-tests/wpt/blob/6ea3164d34a632b16b857d7474985b93acd8de11/cors/basic.htm#L44

@annevk is it actually the test that is wrong here?

**Comment by yutakahirano** [comment]
The script returns a 500 response because origin is not give. Let me fix this.
