### ISSUE TITLE
Change automatic reviewer of Web Crypto

### ISSUE THREAD

**Issue by yacinehmito** [web-platform-tests/wpt#27111]
When I submitted a PR on the Web Crypto tests (#27105), this automatically assigned Jim Schaab (handle jimshaab) as reviewer, which in turn sent an automatic email.
I was quickly informed by his brother that he sadly passed away in October, and was prompted to "Unsubscribe".

I don't know who is leading the project and can take the appropriate steps to replace Jim Schaab with someone else in the list of automatic reviewers of the Web Crypto tests.

Not only are the Web Crypto tests left without an owner at the moment, but more importantly it wouldn't be polite to keep sending automatic emails that his family will have to process.

**Comment by stephenmcgruer** [comment]
Thanks for raising this @yacinehmito . I've sent https://github.com/web-platform-tests/wpt/pull/27113 to remove Jim from the META.yml file to stop sending emails to his family.

The spec (https://w3c.github.io/webcrypto/) unfortunately doesn't list many editors,  but let me cc a few authors whom have made recent commits: @dontcallmedom @plehegar @Manishearth ; hopefully one of them can suggest a suitable owner.

**Comment by yacinehmito** [comment]
Thank you for the swift response @stephenmcgruer.

**Comment by yacinehmito** [comment]
@stephenmcgruer Shall the issue stay open until a reviewer is assigned?

**Comment by stephenmcgruer** [comment]
> @stephenmcgruer Shall the issue stay open until a reviewer is assigned?

As WebCrypto now has no reviewers, I think it should. Again, I would really like to hear from one of the folks I tagged (@dontcallmedom  @plehegar @Manishearth) as to whether there is a suitable person to review WebCrypto changes.

**Comment by Manishearth** [comment]
I have only touched WebCrypto while propagating WebIDL changes, I know nothing of the spec

**Comment by Manishearth** [comment]
I have only touched WebCrypto while propagating WebIDL changes, I know nothing of the spec

**Comment by plehegar** [comment]
I don't know enough about the spec to review the test.

**Comment by sideshowbarker** [comment]
I can try to identify a suitable reviewer for Web Crypto tests

**Comment by plehegar** [comment]
@sideshowbarker , I believe you found someone. Can this be closed?

**Comment by sideshowbarker** [comment]
> @sideshowbarker , I believe you found someone. Can this be closed?

I found an editor to take responsibility for editing the spec, but I haven’t talked with him about also agreeing to take responsibility for reviewing tests. I’ll ask him.

**Comment by sideshowbarker** [comment]
@twiss Has agreed to be the suggested reviewer for tests in the WebCryptoAPI, so I’ve gone ahead and opened https://github.com/web-platform-tests/wpt/pull/29080 to make that so. As soon as that PR is reviewed and merged, it’ll auto-close this issue.
