### ISSUE TITLE
Question about DOMException constructor behavior testing

### ISSUE THREAD

**Issue by kt3k** [web-platform-tests/wpt#27151]
In the test of the error name table of DOMException in [this file](https://github.com/web-platform-tests/wpt/blob/master/WebIDL/ecmascript-binding/es-exceptions/DOMException-constructor-behavior.any.js), the error codes 2, 6, 16, 17 are omitted. Is this intended?

In the WebIDL, the error codes 1, 2, 6, 15, 16, and 17 are marked "Deprecated". https://heycam.github.io/webidl/#idl-DOMException-error-names

If the above 4 codes are intentionally omitted because of the deprecation, then should we keep testing about the error code 1 and 15?

**Comment by stephenmcgruer** [comment]
cc @domenic

**Comment by domenic** [comment]
We should test all of them. "Deprecated" means "don't use in future specs", but it's still part of the web platform and should still be tested.

**Comment by kt3k** [comment]
@domenic Thank you for your advice! So it seems that the current test cases are incomplete on testing these (deprecated) error code mappings. I'll send a PR for it.
