### ISSUE TITLE
'=' sign with in setCookie value cannot be skipped

### ISSUE THREAD

**Issue by rguuduru** [web-platform-tests/wpt#27208]
Unable to escape = sign in cookie value. 

setCookie http://www.test.com cookiekey=cookievalueprefix=cookievaluesuffix

**Comment by gsnedders** [comment]
What is the issue here? Are you trying to get help with using `Set-Cookie`? Is there some limitation affecting writing some tesT?

**Comment by foolip** [comment]
Closing due to no reply.
