### ISSUE TITLE
Missing stable Chrome/FF runs since Jan.13

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#27243]
Stable runs have been missing for several days (https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari)

Debugging the commit from Jan.17 (SHA 2b7cf00586), it appears that wpt.fyi received a call to `/api/webhook/taskcluster` but then got a 500 error from Github when requesting check runs (via URL https://api.github.com/repos/web-platform-tests/wpt/check-suites/1846108829/check-runs?per_page=100).

Loading the check-runs URL myself, it sometimes loads but frequently returns a Server Error.

**Comment by LukeZielinski** [comment]
@stephenmcgruer FYI

**Comment by stephenmcgruer** [comment]
Thanks Luke. I've filed a GitHub support request - and to my surprise discovered that they have added ticket support! (Which is great).

It appears to be a personal ticket, so nobody else will be able to see it, but for the record the URL is https://support.github.com/ticket/personal/0/989094 (whether that 989094 is a UUID or just unique for tickets-filed-by-my-account, I don't know).

I will update as and when I hear back from GitHub. For now I suggest we just let the runs fail, but if we need to address this we could try adding some retry logic to the call.

**Comment by stephenmcgruer** [comment]
Reply from GitHub:

```
Hi Stephen,

Thanks for reaching out. Yeah, I was able to reproduce that problem as well for that URL -- seems like the request is timing out. We have a limit on the execution time for all API requests and that limit is 10 seconds. If the execution of an API call takes longer than that, the request is terminated and you see that error. I've opened an internal issue for the engineering team to investigate these timeouts a bit more. I can't promise an ETA, but we'll followup as soon as there's any news.

In the meantime I wonder if you'd consider a workaround? Reducing the number of records you fetch from per_page=100 to per_page=30 or so should help, so you can use several requests which fetch fever records to get all the check runs in the suite.

Thanks again for the report!

Best,
Ivan
```


So they suggest we try loading fewer results at a time and seeing if that helps. Loading:

https://api.github.com/repos/web-platform-tests/wpt/check-suites/1846108829/check-runs?per_page=30

Is still very slow but does seem (from my limited testing) more reliable, so it may be a good idea. I think the wpt.fyi code supports paging arbitrary counts, but I need to double-check.

**Comment by stephenmcgruer** [comment]
With the reduction in check-runs per request, we have managed to get around the GitHub errors. Downgrading to roadmap, because I want a check-in point in a few months to see if the GitHub issue is resolved.

**Comment by LukeZielinski** [comment]
The previous fix worked.
