### ISSUE TITLE
Programmatically making time elapse

### ISSUE THREAD

**Issue by mfalken** [web-platform-tests/wpt#27324]
While triaging WPT failures, I discovered service-workers/service-worker/update-after-oneday.https.html.

This test requires a special preference:
` `

This was previously discussed here: https://github.com/web-platform-tests/wpt/issues/16455#issuecomment-532507904

More generally, it may be useful to have WPT infra to make time elapse inside of a test.

**Comment by stephenmcgruer** [comment]
Duplicate of https://github.com/web-platform-tests/wpt/issues/17489, I believe. Please re-open if I'm wrong.
