### ISSUE TITLE
Testing aria-labelledby and other accessibility features

### ISSUE THREAD

**Issue by josepharhar** [web-platform-tests/wpt#27374]
There isn't currently a way to test the functionality of the aria-labelledby attribute, right?
I was just asked to write a WPT which does so [here](https://github.com/w3ctag/design-reviews/issues/511#issuecomment-767932845).

In chromium, there is a proprietary way to test it via content_shell's accessibilityController, and there are a bunch of tests which use it for content-visibility [here](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/web_tests/wpt_internal/display-lock/css-content-visibility/accessibility/), which we won't be able to upstream to WPT without an equivalent of accessibilityController.
Is this something we could perhaps add to testdriver.js?

**Comment by stephenmcgruer** [comment]
@josepharhar - can you confirm whether this relates to https://github.com/web-platform-tests/wpt/issues/7753 ?

**Comment by josepharhar** [comment]
Yeah it looks like a dupe, thanks!

**Comment by cookiecrook** [comment]
Label testing is unblocked now with #38758. More coming soon.
