### ISSUE TITLE
Lack of fonts of some languages for ref tests

### ISSUE THREAD

**Issue by xiaochengh** [web-platform-tests/wpt#27539]
There are some ref tests that need correct rendering of characters in certain languages. Otherwise, the ref tests are just comparing tofu to tofu.

Example: Tests in css/css-counter-styles/ethiopic-numeric require an Ethiopic font

The problem is to find a font from a proper (safe) source without copyright issues, which I'm not familiar with. So I'm filing this issue for record.

**Comment by gsnedders** [comment]
c.f. #13203

**Comment by gsnedders** [comment]
Closing this in favour of #13203, to avoid splitting the discussion further.
