### ISSUE TITLE
css-sizing/image-min-max-content-intrinsic-size-change-00*html wrong?

### ISSUE THREAD

**Issue by davidsgrogan** [web-platform-tests/wpt#27810]
Even though Chrome and Firefox both pass, I think [these](https://wpt.fyi/results/css/css-sizing?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&q=image-min-max-content-intrinsic-size-change) are wrong, for the same reason as https://bugzilla.mozilla.org/show_bug.cgi?id=1670151.

For example, after script finishes, image-min-max-content-intrinsic-size-change-001.html is essentially
```html
<img src="/css/support/60x60-green.png" style="height: 30px; width: 30px; min-width: min-content;">
```
The test asserts that the image is 60x30 presumably because min-width:min-content is expected to be 60px.

But as https://bugzilla.mozilla.org/show_bug.cgi?id=1670151 says, min-width:min-content is specified to return 30px, so the final image size should be 30x30.

These people might have insight here:
@bfgeek because he recently [made](https://chromium-review.googlesource.com/c/chromium/src/+/2589039) these tests pass in Blink
@BorisChiou because he's been looking into https://bugzilla.mozilla.org/show_bug.cgi?id=1670151

Thoughts? If you agree these tests are wrong, I will fix them.

**Comment by BorisChiou** [comment]
Yes. I think these are wrong now. The natural ratio should affect the intrinsic size, based on https://github.com/w3c/csswg-drafts/issues/5032. (Though we miss the ability to use the natural size after this behavior change on replaced elements.)

Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1135287
cc @emilio
