### ISSUE TITLE
flex-aspect-ratio-026.html seems to misunderstand minimum sizes

### ISSUE THREAD

**Issue by cbiesinger** [web-platform-tests/wpt#27878]
https://github.com/web-platform-tests/wpt/blob/master/css/css-sizing/aspect-ratio/flex-aspect-ratio-026.html

In particular:
```html
  <div class="flexContainer">
    <!-- The border-box min-width 25px is transferred to the main axis,
         yielding a resolved min-height:auto of 200px. -->
    <div class="item" style="min-width: 25px; aspect-ratio: 1/8;"><div></div></div>
  </div>
```

This description of how minimum sizing works is incorrect. For min-height: auto, we do not look at min-width at all. In this case, since have an aspect ratio and this is a column flexbox, we transfer the definite cross size through the aspect-ratio and get 200px; but this happens because the box's width is 25px and not directly because of the min-width.

*Independent of that*, there is the minimum size transfer as defined by the css-sizing spec: https://drafts.csswg.org/css-sizing-4/#aspect-ratio-size-transfers
In this case, that yields the same result.

I would recommend updating the comment, also in the section below (line 66). It may also be good to add some testcases that set min-height: 0 to ensure that the min size transfer works even then.

(Depending on the outcome of https://github.com/w3c/csswg-drafts/issues/6069, the test may also be incorrect since the inner div has a 500px height)

cc @aethanyc as the test author and @fantasai to check that I am understanding the spec correctly

**Comment by aethanyc** [comment]
@cbiesinger Does the updated comment looks good to you? I can upload a patch to fix the comments in `flex-aspect-ratio-025.html` and `flex-aspect-ratio-026.html`, and change the test to match the spec resolution in https://github.com/w3c/csswg-drafts/issues/6069 (perhaps via shrinking the `height` in `.item > div`)

```
  <div class="flexContainer">
    <!-- The border-box width 25px (enforced by min-width) is transferred to the main axis,
         yielding a resolved min-height:auto of 200px. -->
    <div class="item" style="min-width: 25px; aspect-ratio: 1/8;"><div></div></div>
  </div>
```

> It may also be good to add some testcases that set min-height: 0 to ensure that the min size transfer works even then.

Good idea. I imagine we could add something like the following to turn off auto min size resolution of flexbox and test aspec-ratio's min-size transfer:
```
<!DOCTYPE html>
<div style="display: flex;">
  <div style="background: green; min-height: 100px;
              aspect-ratio: 1/1; min-width: 0px; flex-shrink: 0"></div>
</div>
```

**Comment by cbiesinger** [comment]
Yeah that comment sounds good to me.

For that test, I think you want to swap min-width and min-height? (Probably also give the flexbox a width:0 or something)

**Comment by aethanyc** [comment]
I update all tests on WPT (including `flex-aspect-ratio-{025,026}.html`) in 
https://phabricator.services.mozilla.com/D112830 to match the spec resolution https://github.com/w3c/csswg-drafts/issues/6069.

@cbiesinger Could you take a look?

> For that test, I think you want to swap min-width and min-height? (Probably also give the flexbox a width:0 or something)

Oh, the example is a row flex container, so I think we should use `min-width: 0px` to disable flexbox's auto min size resolution. Is you suggestion "swapping min-width and min-height" based on the item in a column flex container? Anyway, Firefox renders the testcase wrong (blink is correct). I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1696560, and the test (or a variant  column flex container) will be added there.
