### ISSUE TITLE
Edge not run since 19 Feb?

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#27877]
https://wpt.fyi/results/?label=experimental&label=master&aligned is showing 4c56f3e, from 19 Feb 2021, presumably as that's the last aligned run

https://wpt.fyi/runs?label=master&max-count=100&from=2021-02-18T00%3A00&product=edge shows the last Edge run at all was on the 20th, but Dev rather than Can.

**Comment by thejohnjansen** [comment]
Thanks for opening this. It should be resolved very soon. We had an expired cert in our pipeline which has now been renewed.

**Comment by mustjab** [comment]
The issue with Edge runs not happening should be resolved now, test run with the results for Stable Edge: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=61964&view=logs&j=fdc313d8-ec6e-5688-52ff-7ea62743dd58

We had expired certificates which prevented us from re-creating Windows machine pool. Is there anything we need to do now to re-enable Edge runs?

**Comment by stephenmcgruer** [comment]
> Is there anything we need to do now to re-enable Edge runs?

I don't believe so, they appear to be back now.
