### ISSUE TITLE
https://w3c-test.org appears to be down...

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#28113]
http://w3c-test.org works, but https doesn't. Cc @sideshowbarker

**Comment by sideshowbarker** [comment]
`https://w3c-test.org/` is working now

To fix it, all I did was restart wptserve; as is often the case with troubleshooting error with a persistent wptserve, it’s not clear what the cause was (even after looking through the logs).

**Comment by karfau** [comment]
Just found this issue because neither https nor http seems to currently work

**Comment by sideshowbarker** [comment]
Thanks for the heads up, and sorry about that — it should be working again now

The cause was that the python binary apparently changed, so I needed to re-run this:

```
setcap cap_net_bind_service=eip /usr/bin/python3.7
```
