### ISSUE TITLE
Test 'attr()' case-insensitivity in HTML

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#2831]
Convert tests in https://github.com/whatwg/html/issues/991 to web-platform-tests.

**Comment by wanghongjuan** [comment]
Quote [spec](https://html.spec.whatwg.org/multipage/semantics-other.html#case-sensitivity-of-the-css-'attr()'-function) here:
> When comparing the attribute name part of a CSS 'attr()' function to the names of namespace-less attributes on HTML elements in HTML documents, the name part of the CSS 'attr()' function must first be converted to ASCII lowercase. The same function when compared to other attributes must be compared according to its original case.

I find there are 4 tests in web-platform-tests, and I think the test coverage is enough, please take a look:

Test Purpose | Case link
------- | ------- 
If attribute (x) does not exist then an empty string is returned for the attr(x) value | [content-attr-001.htm](https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/generated-content/content-attr-001.xht)
The 'attr()' function can only retrieve data from the same element that is called from | [other-attribute-001.xht](https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/generated-content/other-attribute-001.xht)
Verify in XHTML that attr(x) does not select the attribute when the case does not match | [content-attr-case-002.xht](https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/generated-content/content-attr-case-002.xht)
Names specified in attr for a content property are case-insensitive in HTML documents | https://github.com/web-platform-tests/wpt/blob/master/css/css-content/attr-case-insensitive.html

**Comment by zcorpan** [comment]
I think probably new tests similar to https://github.com/web-platform-tests/wpt/blob/master/css/css-content/attr-case-insensitive.html but with these cases:

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4036 (should not match)
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4037 (only casematch should match)

**Comment by 123mansha** [comment]
hii!! I would like to work on this issue if it is still not assigned
i am a newbie and want you to guide me over this project

**Comment by zcorpan** [comment]
@123mansha great, thank you!

The documentation has a tutorial on how to write reftests that might help: https://web-platform-tests.org/writing-tests/reftest-tutorial.html

Ask in IRC if you get stuck: http://irc.w3.org/?channels=testing

**Comment by 123mansha** [comment]
okk sure!! Thanks @zcorpan
