### ISSUE TITLE
2d.drawImage.zerosource tests seem to be wrong

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#2835]
CC @zcorpan 

They expect an `INDEX_SIZE_ERR` from `drawImage`, but I can't find anything that throws those.

**Comment by zcorpan** [comment]
Right...

https://html.spec.whatwg.org/multipage/scripting.html#check-the-usability-of-the-image-argument

The spec says to do nothing in this case. Similarly for 2d.drawImage.zerocanvas.html
