### ISSUE TITLE
Timout on css/css-grid/grid-definition/grid-repeat-max-width-001.html

### ISSUE THREAD

**Issue by bfgeek** [web-platform-tests/wpt#28370]
As above:
http://wpt.live/css/css-grid/grid-definition/grid-repeat-max-width-001.html

Initial commit was bad:
https://github.com/web-platform-tests/wpt/commit/7e8d0819b98b4ec505a2de8d48119af0a34861e6

**Comment by tabatkins** [comment]
Oh, huh, is that because it's a reftest but I've still included the testharness libs? I think this is the first reftest I've written from scratch.

**Comment by gsnedders** [comment]
> Oh, huh, is that because it's a reftest but I've still included the testharness libs? I think this is the first reftest I've written from scratch.

Indeed. It waits for all the (JS) tests to run to completion, but none ever start, yet alone complete.

**Comment by tabatkins** [comment]
Ah, thanks. I'll merge #28386 once it greens.
