### ISSUE TITLE
flexbox_justifycontent-left-002.html and -right-002.html have the wrong expectation for the bottom half (for column-reverse)

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt#28378]
These WPT tests fail in Firefox:
https://wpt.fyi/results/css/css-flexbox/flexbox_justifycontent-left-002.html
https://wpt.fyi/results/css/css-flexbox/flexbox_justifycontent-right-002.html

These tests assume that the lower part of the tests (with "column-reverse") are bottom-aligned -- that's what happens in Chrome, but that's not correct, per spec.

The spec says that both these `left` and `right` keywords should behave like `start` (the writing-mode-dependent "start" side), if used in a vertical axis (as they are in these tests):
https://www.w3.org/TR/css-align-3/#valdef-justify-content-left
https://www.w3.org/TR/css-align-3/#valdef-justify-content-right

Chromium and WebKit haven't implemented the `start`/`end` keywords for the alignment properties, so it looks like they fall back to `flex-start` instead, which sounds like `start` but in fact does the opposite from what `start`/`end` mean in this `column-reverse` scenario.  So they get the test's lower part wrong (and these tests' expectations get them wrong as well, which means these engines pass the test but in fact have the wrong behavior).

CC @meyerweb who authored these tests -- if I'm not missing something, would you mind fixing this expectation in these tests?

**Comment by meyerweb** [comment]
I ran the tests past a few people who know some flexbox, and all our understanding was that `start` was equivalent to `flex-start` in this context—that the alignment box was dictated by the layout model, which here is flexible boxes, as opposed to the writing mode.  Does the writing mode always override the layout model?  If so, that’s not entirely clear to me from what I’ve read of the specifications (and it also calls for a much more complicated set of tests).

**Comment by meyerweb** [comment]
Forgot to tag in a few people for their analysis on this one: @mrego, @rachelandrew, @fantasai, @tabatkins.

**Comment by dholbert** [comment]
That's not correct.  In a flexbox, `start` and `flex-start` are definitely not equivalent.

* `start` is always the `direction`/`writing-mode`-dependent "start" side.
*  In a flexbox, `flex-start` is the flexbox axis "start" side (which means the `*-reverse` flexbox keywords do reverse it).  Outside of a flexbox, it behaves like `start`.

Right now, these tests are expecting `start` (the `left`/`right` value) to align to the *flexbox-axis-relative* start side, which is definitely not what `start` does.  It happens to be what Chrome does, but that's only because Chrome doesn't implement `start` at all, so it doesn't have any better options.

This is all defined in css-align-3 -- see:
https://www.w3.org/TR/css-align-3/#valdef-self-position-flex-start
https://www.w3.org/TR/css-align-3/#valdef-self-position-start
https://www.w3.org/TR/css-align-3/#alignment-container

I think @fantasai and @tabatkins can confirm what I'm saying here, though please correct me if I've missed some spec change or am misunderstanding what the spec is trying to say here...

**Comment by dholbert** [comment]
(er, wait - I thought Chrome didn't implement `start`/`end` at all, but they do seem to be parsing it correctly in a quick test that I just did to check my memory.  In that case, then I think this is just a Chrome bug with fallback behavior.)

**Comment by dholbert** [comment]
(Ah, it looks like Chrome supports **parsing** `start`/`end` values for `justify-content`, but they both behave as `flex-start` in layout i.e. the default value, so they're effectively unsupported, if I'm interpreting their behavior correctly. So my recollection was mostly-right. :) )

**Comment by rachelandrew** [comment]
my understanding matches that of @dholbert so `start` and `end` behave in the same way as in grid, `flex-start` and `flex-end` (in flex layouts only) account for the row or column reversing behavior.

**Comment by dholbert** [comment]
Looks like https://bugs.chromium.org/p/chromium/issues/detail?id=1011718 is the Chrome bug here (on supporting `start`/`end`, and presumably supporting the correct fallback-to-these-values behavior for `right`/`left`):

**Comment by meyerweb** [comment]
I (re-)read the references, and it’s still not clear to me which interpretation is correct.  A lot seems to turn on this phrasing:

> Aligns the alignment subject to be flush with the alignment container’s start edge in the appropriate axis. 

(And analogously for the end edge.)

In the tests, I take the alignment subject(s) to be the flex items, the alignment container to the be the flex container, and the appropriate axis to be… well, that’s where things are unclear.  Is the appropriate axis (which isn’t defined here) the inline axis of the writing mode?  Or is it the justification axis of the layout mode?  I haven’t yet found a clear explanation in the specs.  I haven’t even found a definition of “appropriate axis”; that is, which set of axes are being considered to determine which is appropriate.

**Comment by dholbert** [comment]
Yeah, I agree that that spec text could be clearer.

The high-level intent here, though, is that `start` and `end` are supposed to produce the same result (choose the same edge), consistently, regardless of the container type.  So: for a given writing-mode, `align-*:end` and `justify-*:end` should always choose the same side, regardless of container type (flex vs. "reverse-flex" vs. grid vs. eventually block when that's implemented).

If things worked the way you're interpreting them (if the flex axes were the "appropriate axes" for `start` to react to), then `flex-start` would have no reason to exist as an independently-specced term; it would just be an alias for `start`.

**Comment by dholbert** [comment]
I'll add my interpretation of the spec text here, for clarity -- though I should also say that I was very much involved with the discussions when this was specced, and I'm nearly certain that what I've described here is consistent with what @tabatkins and @fantasai intended the spec to say.  (Otherwise `flex-start` would have no reason to exist except as an alias, as I noted above.)  So: to the extent that the spec implies anything other than what I've said, that's a spec bug which needs fixing. :)

But anyway -- interpreting the spec text as-it-exists, to ground my assertions here in something concrete: here's the spec text for `start`:
> start (self, content)
>    Aligns the alignment subject to be flush with the alignment container’s start edge in the appropriate axis.

This is the reference to "appropriate axis" that you mentioned above about.  Here, it just means "whichever axis this property controls", which is defined elsewhere.  (Typically justify-* controls the inline axis, though for column-oriented flexbox, it controls the block axis.)  And the "start side" of that axis is unambiguously dependent on the writing-mode.  Note that it **does not say "the flex-start side"** -- it says "the start side".

Having said that: I think you make a good point that someone could interpret "the appropriate axis" as e.g. representing "the flex container's main axis" in this case, and interpret "the start side" as meaning the `main-start` axis.  That ambiguity is indeed unfortunate and is something that we should fix in the spec (separately).

**Comment by dholbert** [comment]
Also notably, the flexbox spec itself is careful never to refer to e.g. "the start side" when talking about a flex-relative side -- it uses `main-start` / `cross-start` , or generally `flex-start`, to refer to a flexbox-axis-relative side.

The term `start` is meant to unambiguously mean `{block|inline}-start` and only be `writing-mode`-dependent, as noted here:
https://www.w3.org/TR/css-writing-modes-3/#start
> Where contextually unambiguous or encompassing both meanings, the terms start and end are used in place of block-start/inline-start and block-end/inline-end, respectively.

**Comment by dholbert** [comment]
Filed https://github.com/w3c/csswg-drafts/issues/6186 on clarifying the spec here, to make this less ambiguous.

**Comment by dholbert** [comment]
(And @tabatkins confirmed my intereptation over there, FWIW.)

So: @meyerweb, would you mind correcting these two tests to expect `start`-alignment (i.e. top-alignment) for their lower portions (just as with their upper portions)?

**Comment by meyerweb** [comment]
Will do!  Thanks, @dholbert.

**Comment by meyerweb** [comment]
Please note: I only attempted to correct the tests in the PR; I did not expand them to include other writing modes.  Doing the latter will go on my to-do list after corrections of the current tests are approved and merged.

**Comment by meyerweb** [comment]
This is clear to be closed, yes?
