### ISSUE TITLE
How to deploy WPT to AWS EC2

### ISSUE THREAD

**Issue by victor-storozhenko-epam** [web-platform-tests/wpt#28458]
Hi team.
I'm looking for a guidance to deploy WPT to EC2. Simply following [running-tests/from-local-system](https://web-platform-tests.org/running-tests/from-local-system.html) helps to run server locally, but I server doesn't respond to requests from outside
`http://<ec2_public_ip>:8000/tools/runner/index.html`
could you point me to a guide of deployment of the project on AWS EC2?

**Comment by foolip** [comment]
@victor-storozhenko-epam hosting wptserve is a bit complicated, but the configuration for https://wpt.live/ might be useful. See https://github.com/web-platform-tests/wpt.live for that setup.

**Comment by victor-storozhenko-epam** [comment]
@foolip thanks! That really makes it clear
