### ISSUE TITLE
Empty formdata in response.formData()

### ISSUE THREAD

**Issue by jimmywarting** [web-platform-tests/wpt#28607]
This can return a empty FormData in firefox and works fine...

```js
new Response(new FormData()).formData()
```

Blink & Safari don't support it (if it's empty - need to append at least one item)
Maybe add a test for this?

**Comment by foolip** [comment]
cc @annevk

**Comment by annevk** [comment]
@jimmywarting are you willing to contribute a test? And file bugs against Chrome/Safari?

**Comment by jimmywarting** [comment]
> Are you willing to contribute a test? And file bugs against Chrome/Safari?

file bug report to chrome/safari would be easy - i can do that.

Any pointers for writing a test, like which file to write it in?

**Comment by annevk** [comment]
That's great, thanks!

You could add a new `.any.js` file covering this scenario to https://github.com/web-platform-tests/wpt/tree/master/fetch/api/body.

There's some existing tests in https://github.com/web-platform-tests/wpt/blob/master/fetch/api/response/response-consume.html and https://github.com/web-platform-tests/wpt/blob/master/fetch/api/request/request-consume.any.js but they're fairly large already.

**Comment by jimmywarting** [comment]
> file bugs against Chrome/Safari?

- https://bugs.webkit.org/show_bug.cgi?id=225238
- https://bugs.chromium.org/p/chromium/issues/detail?id=1204594
