### ISSUE TITLE
overflow-wrap-anywhere-001 seems incorrect

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#28614]
@aethanyc 

I believe there are problems in [overflow-wrap-anywhere-001](https://github.com/web-platform-tests/wpt/blob/master/css/css-text/overflow-wrap/overflow-wrap-anywhere-011.html):

* the div with the space and the div with the tab should indeed be the same size as the div with just an i, but that's not due to `overflow-wrap`. instead, it's due to `white-space: normal`. From [Phase II: Trimming and Positioning](https://drafts.csswg.org/css-text-3/#white-space-phase-2):
    > A sequence at the end of a line of collapsible spaces is removed […]

    That doesn't change the look of the test, but the assert is misleading as to why these lines should be short
* Unlike what the test claims, the div with the &amp;nbsp; should be the same width as the others (and twice as tall). From the definition of [`overflow-wrap:anywhere`](https://drafts.csswg.org/css-text-3/#valdef-overflow-wrap-anywhere)
    > An otherwise unbreakable sequence of characters may be broken at an arbitrary point if there are no otherwise-acceptable break points in the line. […] Soft wrap opportunities introduced by anywhere are considered when calculating min-content intrinsic sizes.
* I suggest using `font-family: monospace` instead of `font-family: Arial, Helvetica, sans-serif;`. That way, we can be sure that the second line which contains only the &amp;nbsp; isn't wider than the line that contains an `i`

**Comment by frivoal** [comment]
cc: @jfkthame, as the reviewer of the test.

Btw, chrome has the right behavior here (as of version 90).

**Comment by jfkthame** [comment]
> I believe there are problems in overflow-wrap-anywhere-001:

Typo (also in the issue title): I think you meant overflow-wrap-anywhere-011 (which is where the link points).

>     * Unlike what the test claims, the div with the &nbsp; should be the same width as the others (and twice as tall). From the definition of [`overflow-wrap:anywhere`](https://drafts.csswg.org/css-text-3/#valdef-overflow-wrap-anywhere)
>       > An otherwise unbreakable sequence of characters may be broken at an arbitrary point if there are no otherwise-acceptable break points in the line. […] Soft wrap opportunities introduced by anywhere are considered when calculating min-content intrinsic sizes.

The div with the &nbsp; is twice as tall, yes; but surely it is *not* expected to be the same width as the others if &nbsp; is wider than 'i' (which is the case for sans-serif fonts like Arial or Helvetica). The min-content width calculation will take account of the break between 'i' and &nbsp;, so the min-content width becomes the larger of the widths of those two characters. The test deliberately used sans-serif fonts so as to check that the &nbsp; contributes properly to min-content width here.

**Comment by frivoal** [comment]
Sorry for the typo in the title. As for the rest, yes, that makes sense now, thanks for clarifying the assert.
