### ISSUE TITLE
tools/wpt/ tests fail on Windows because Chrome Dev isn't installed

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#28745]
Happening on several PRs, include #28741 and #28652. The failing test doesn't have anything to do with these PRs.

Link to a typical error log: https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=64723&view=logs&j=775b4849-c968-5044-becb-3d45fabe691a&t=b3b63ffd-da0b-51fb-c375-a27ecd9b6f5a

Snip of the failing test:
```
____________________________ test_run_failing_test ____________________________

    @pytest.mark.slow
    @pytest.mark.remote_network
    def test_run_failing_test():
        """Failing tests should be reported with a non-zero exit status unless the
        `--no-fail-on-unexpected` option has been specified."""
        if is_port_8000_in_use():
            pytest.skip("port 8000 already in use")
        failing_test = "/infrastructure/expected-fail/failing-test.html"
    
        assert os.path.isfile("../../%s" % failing_test)
    
        with pytest.raises(SystemExit) as excinfo:
            wpt.main(argv=["run", "--yes", "--no-pause", "--channel", "dev",
                           "chrome", failing_test])
        assert excinfo.value.code != 0
    
        with pytest.raises(SystemExit) as excinfo:
            wpt.main(argv=["run", "--yes", "--no-pause", "--no-fail-on-unexpected",
                           "--channel", "dev", "chrome", failing_test])
>       assert excinfo.value.code == 0
E       assert 1 == 0
E        +  where 1 = SystemExit(1).code
E        +    where SystemExit(1) = <ExceptionInfo SystemExit tblen=2>.value

tests\test_wpt.py:201: AssertionError
```

**Comment by foolip** [comment]
@past FYI this is a fairly typical example of the kinds of problem WPT contributors can see, where a part of the CI that isn't required begins to fail, and you can't be sure if you caused it or not.

To investigate, I would head over to the Azure Pipelines logs and find my way to the failing step of the 3.6 job. Screenshot:
![image](https://user-images.githubusercontent.com/498917/116671451-3ccf9d00-a9a1-11eb-9062-88c1e5cd34ad.png)

So in addition to `test_run_failing_test` there's also a problem with `test_run_verify_unstable`.

Azure Pipelines actually has a hidden gem of a test results viewer for pytest results as well, here:
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=64723&view=ms.vss-test-web.build-test-results-tab

There one can quickly see the failing tests without digging through the logs.

As for actually fixing these tests, not sure yet :)

**Comment by foolip** [comment]
For this kind of problem, I keep https://github.com/web-platform-tests/wpt/pull/18830 around to trigger all tests without any other changes. I'll revive and rebase that now.

**Comment by foolip** [comment]
These tests require Chrome Dev specifically, and unfortunately `./wpt install --channel dev chrome browser` will hit this error:
https://github.com/web-platform-tests/wpt/blob/617067b0abeb9b11ddda5564df8f775890fbe0f3/tools/wpt/browser.py#L538-L539

What Taskcluster does is here:
https://github.com/web-platform-tests/wpt/blob/617067b0abeb9b11ddda5564df8f775890fbe0f3/tools/ci/run_tc.py#L257-L262

In other words, it's installation steps specific to the CI system and platform. We'd need to do something similar to Azure Pipelines on Windows for this to work.

Alternatively, we could make these tests not care what the Chrome channel is. These are tests for the `./wpt` CLI and not the browsers, so it's not very important what the browser is.

I think we should just stop running this job until this is fixed, it will provide zero value until fixed.

**Comment by foolip** [comment]
With https://github.com/web-platform-tests/wpt/pull/28713 this will be 3.6 + 3.9, but the problem remains.

**Comment by foolip** [comment]
I've skipped the tests and linked this issue in https://github.com/web-platform-tests/wpt/pull/28790, I'll rename it so that it's more specific about what's wrong.

**Comment by foolip** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/28790.
