### ISSUE TITLE
[css-values-3] attr-px-invalid-cast test

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#28794]
@FremyCompany François,

In [attr-px-invalid-cast.html test](http://wpt.live/css/css-values/attr-px-invalid-cast.html):

"
When the value of the referenced attribute is not a pixel value, the fallback value is used instead.
"
(...)
`width: attr(data-test px, 200);`

It seems that the fallback (here, 200) is invalid.

This is the reverse situation of [Issue 28765](https://github.com/web-platform-tests/wpt/issues/28765) !

In my humble opinion, the specification needs 2 or 3 examples ...

**Comment by FremyCompany** [comment]
Good catch! Most probably these two tests have swapped descriptions.

I don't recall the specifics but it seems likely.

**Comment by TalbotG** [comment]
François,
I can fix both tests then in an upcoming PR.

I will create an issue requesting for 2 or 3 additional examples in the [8.2. Attribute References: attr()](https://www.w3.org/TR/css-values-3/#attr-notation) section.

**Comment by TalbotG** [comment]
Based on PR28816, I am closing Issue 28794.
