### ISSUE TITLE
Update html5lib tests (for <isindex>)

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#2887]
I wanted to update html5lib tests (for https://github.com/html5lib/html5lib-tests/pull/74) and tried to follow the instructions in html/tools/update_html5lib_tests.py and expected at least `isindex.dat` to have changed but it seems it did not...

```
git status
On branch htmlpreelement
Your branch is up-to-date with 'origin/htmlpreelement'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

    modified:   syntax/parsing/html5lib_entities01.html
    modified:   syntax/parsing/html5lib_entities02.html
    modified:   syntax/parsing/html5lib_template.html
    modified:   syntax/parsing/html5lib_tests11.html
    modified:   syntax/parsing/html5lib_tests7.html
    modified:   syntax/parsing/html5lib_webkit01.html
    modified:   syntax/parsing/html5lib_webkit02.html
    modified:   ../resources (new commits)
    modified:   ../tools (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

    syntax/parsing/html5lib_innerHTML_foreign-fragment.html
    syntax/parsing/html5lib_innerHTML_math.html
    syntax/parsing/html5lib_innerHTML_webkit02.html
    syntax/parsing/html5lib_namespace-sensitivity.html
    syntax/parsing/html5lib_ruby.html
    tools/venv/

```

cc @jgraham

**Comment by zcorpan** [comment]
@gsnedders can you help?

**Comment by gsnedders** [comment]
No, all @jgraham's stuff. (And I'm going on holiday as soon as this delayed flight gets here…)

**Comment by foolip** [comment]
Is this issue still relevant? Have we not synced with html5lib in 2+ years?

**Comment by zcorpan** [comment]
I'm afraid so :-/

**Comment by foolip** [comment]
Alright, so as part of an upcoming documentation drive we should probably document what all of the third-party does are and how they are updated. Ideally we should have auto-updates from source like for interfaces/ now.

**Comment by gsnedders** [comment]
This would be easier to do if we had something to parse the tests in html5lib-tests. Say, like, as part of a linter https://github.com/html5lib/html5lib-tests/pull/83 (PR opened over two years ago!).

**Comment by zcorpan** [comment]
I guess this issue is fixed because `html/tools/build.sh` hardcodes the `html5lib-python` commit [d49afd3](https://github.com/html5lib/html5lib-python/commit/d49afd350c06339a8c59299664b8a73a3b2c3f64), at which point html5lib-python was using commit [71eebd5 of html5lib-tests](https://github.com/html5lib/html5lib-tests/tree/71eebd59772d1d39aced0c0582ae9c09acf3ce6e) which is newer than the isindex change from 2016.

I've created a new issue though because updating parser tests is ... not as easy as it could be: #27868
