### ISSUE TITLE
DockerHub webplatformtests org limited to 3 members

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#28903]
@stephenmcgruer has let me know:

> Was going through handover tasks and realized we have a bit of a tricky issue with DockerHub (which we use to host wpt.fyi and wpt container images). DockerHub at some point added a member limit of 3 members for free organizations, and we were grandfathered in with 6 members.
>
> The 6 members currently are:
>
> gsnedders
> harjgam
> hexcles
> lastontheboat
> smcgruer
> wptfyibuilder 
>
> I would suggest we go through https://www.docker.com/community/open-source/application and try to get an OSS override.

Unfortunately, Stephen didn't hear back on the application, so we (@web-platform-tests/wpt-core-team) need to figure something out here. Right now, it's not possible to remove enough members to make room for me or @past in case we need access.

As an alternative, we could look into using [GitHub's Docker registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry), which could probably be published to using GitHub Actions. But a risk is that Taskcluster needs to download these images, and who knows if GitHub is further away on the network, less reliable, or something...

**Comment by foolip** [comment]
Stephen got a reply to the open source application, but there are requirements and expectations I don't think we can meet. WPT is in some sense sponsored by commercial entities, but more importantly we'd have to link to Docker in various places and agree to (potentially) be part of marketing materials.

@jgraham what do you think about using GitHub's registry instead?

**Comment by jgraham** [comment]
I think being able to use the existing GitHub teams setup would be a big improvement, but I don't know what level of support taskcluster has for non-dockerhub registeries. I'll investigate.

**Comment by jgraham** [comment]
Turns out we can probably just put in the URL in the same format as `docker pull` uses, so that seems straightforward.

**Comment by OrKoN** [comment]
A test image has been published to Github Registry https://github.com/web-platform-tests/wpt/pkgs/container/wpt Who has permissions to make it public (see https://docs.github. com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility)? See a test PR using the new image https://github.com/web-platform-tests/wpt/pull/46279/files and the error log https://community-tc.services.mozilla.com/tasks/Xxhe2rhmQ4GP8hTKmSGOOg/runs/0/logs/public/logs/live.log

**Comment by foolip** [comment]
@OrKoN I have made the package public now, can you check if it worked?

**Comment by OrKoN** [comment]
I can pull it locally now. Restarted the PR, let's see if task cluster handles it.

**Comment by OrKoN** [comment]
There is a failure with unit tests:

https://github.com/web-platform-tests/wpt/pull/46279/checks?check_run_id=25049795377

It does look like some python dependency issue since the docker image was not updated for a few months:

ConftestImportFailure: TypeError: field() got an unexpected keyword argument 'alias' (from /home/test/web-platform-tests/tools/conftest.py)
