### ISSUE TITLE
Found some differences in Blob to File conversion in the FormData

### ISSUE THREAD

**Issue by jimmywarting** [web-platform-tests/wpt#28924]
```js
fd = new FormData
fd.set('a', new Blob)
fd.get('a') === fd.get('a') // false in chromium - true in FF & Safari (don't have IE on Mac)
```

Looks like there is no test to cover this senario: https://github.com/web-platform-tests/wpt/blob/e45a9f9e65d039c76817ee2a6a1ef02c9311a1cb/xhr/formdata/set-blob.any.js

I think `fd.get('a') === fd.get('a')` should be true

- [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1207298&q=FormData%20file%20blob&can=2) submitted by myself

**Comment by Chockzche** [comment]
<a href="http://www.freebiebitcoin.com">Earn free bitcoin</a>

**Comment by F3n67u** [comment]
I'd like to write this test.

**Comment by TCode110** [comment]
if it fails in chromium, try to update your chromium, and then check may be works.

**Comment by jimmywarting** [comment]
> if it fails in chromium, try to update your chromium, and then check may be works.

running 92.0.4515.159
says there is no updates available `fd.get('a') === fd.get('a')` is still false (two uniq files)

**Comment by TCode110** [comment]
you can try for clearing cache, reinstalling chromium, and then see, maybe work, but try!

**Comment by jimmywarting** [comment]
I'm not going to go trough that trouble of clearing cache and reinstall chrome, my [chromeium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1207298&q=FormData%20file%20blob&can=2) is still open, confirmed and unresolved.

I can install a fresh version of google chrome canary (don't have it right now but i use it sometimes)
doe but i'm betting it's still false. and i stay corrected... it's still false

So please, don't ask me to try this again, I will know when it have been resolved once the chromium bug is fixed.
