### ISSUE TITLE
Firefox TC runs failing

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#29108]
see e.g. https://community-tc.services.mozilla.com/tasks/TIgN3_YyRjKGgmmUsCo0Vw/runs/0/logs/public/logs/live.log

**Comment by jgraham** [comment]
Oh I think maybe mozrunner needs a new release

**Comment by KyleJu** [comment]
The outage started since https://github.com/web-platform-tests/wpt/pull/29075

**Comment by foolip** [comment]
@jgraham this was fixed, right?

**Comment by jgraham** [comment]
I believe so; a random run I looked at seemed to complete successfully.

**Comment by gsnedders** [comment]
This was ultimately fixed by https://github.com/web-platform-tests/wpt/pull/29223 and https://github.com/web-platform-tests/wpt/pull/29221 AFAICT.
