### ISSUE TITLE
Missing Firefox runs since May 21 (both Stable and Experimental).

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#29121]
Missing stable runs: https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

Missing experimental runs: https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk

**Comment by KyleJu** [comment]
https://github.com/web-platform-tests/wpt/issues/29108

**Comment by LukeZielinski** [comment]
Closing as duplicate (see above)
