### ISSUE TITLE
Missing edge runs on wpt.fyi since May 20

### ISSUE THREAD

**Issue by LukeZielinski** [web-platform-tests/wpt#29145]
See https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk

**Comment by LukeZielinski** [comment]
cc @mustjab to perhaps take a look

**Comment by mustjab** [comment]
I see this error when trying to run the tests, @jgraham is this related to this change: https://github.com/web-platform-tests/wpt/commit/3127e8302a3ee6e04518abebb6fc87ff5cb874fd#diff-932abf0967f624dea5849ea0a84c6b1a67b9ee05d0c9e046cf98099569fc4f8e

https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=66011&view=logs&j=2b376673-b6b7-55d3-67e2-e8305abf5c1e&t=74a04147-a139-56ed-eca1-af09b5915baa 
Traceback (most recent call last):
  File "C:\Agent\_work\1\s\wpt", line 11, in <module>
    wpt.main()
  File "C:\Agent\_work\1\s\tools\wpt\wpt.py", line 179, in main
    rv = script(*args, **kwargs)
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 848, in run
    rv = run_single(venv, **wptrunner_kwargs) > 0
  File "C:\Agent\_work\1\s\tools\wpt\run.py", line 855, in run_single
    return wptrunner.start(**kwargs)
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\wptrunner.py", line 416, in start
    rv = not run_tests(**kwargs) or logged_critical.has_log
  File "C:\Agent\_work\1\s\tools\wptrunner\wptrunner\wptrunner.py", line 288, in run_tests
    executor_kwargs = product.get_executor_kwargs(logger,
TypeError: executor_kwargs() missing 1 required positional argument: 'run_info_data'

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/29152

**Comment by KyleJu** [comment]
@mustjab Edge recovered for a few days but it appears to be stalling/queued on Azure. Would you mind taking another look?

e.g.
https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=66269&view=results

**Comment by mustjab** [comment]
This time it was due to failure on our end to re-create test VMs, pipeline job was failing. I've updated the pipeline and new agents are up and running now. Let me know if that doesn't resolve things.

**Comment by KyleJu** [comment]
@mustjab edge is back!
