### ISSUE TITLE
[css-ruby] Suggestions on empty-ruby-base-container-abs and empty-ruby-base-container-float tests

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#29515]
http://wpt.live/css/css-ruby/empty-ruby-base-container-abs.html

http://wpt.live/css/css-ruby/empty-ruby-base-container-float.html

http://wpt.live/css/css-ruby/empty-ruby-base-container-ref.html

@frivoal , @upsuper 

1-
Replace

`<title>Empty ruby base container</title>`

with

`<title>CSS Ruby Test: Empty abs. pos. ruby base container</title>`

in empty-ruby-base-container-abs

2-
Replace

`<title>Empty ruby base container</title>`

with

`<title>CSS Ruby Test: Empty floating ruby base container</title>
`

in empty-ruby-base-container-float

3-
Replace

`<title>Empty ruby base container</title>`
`<div style="font-size: 64px; line-height: 3">a<ruby><rb></rb><rt>b</rt></ruby>c</div>`

with

`<title>CSS Reference File</title>`
`<div style="font-size: 64px; line-height: 3">a<ruby><rb>&nbsp;</rb><rt>b</rt></ruby>c</div>`

in empty-ruby-base-container-ref.html

Finally, I think "empty" is not the best descriptive adjective to use for the title and filename since a non-breaking-space is a character that we do not normally see. If `background-color` was, say, orange and applying to the `<a>` element, or if `text-decoration: underline` was applying to the `<a>` element, then we would see it.

**Comment by upsuper** [comment]
Those tests should be renamed, I agree. They are not empty ruby base containers, but ruby base container with only floating / absolutely-positioned children. I believe @frivoal just copied the test case for empty ruby base but didn't update the titles.
