### ISSUE TITLE
[css-ruby] question on ruby-box-generation-001 test

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#29533]
@upsuper Xidorn,

http://wpt.live/css/css-ruby/ruby-box-generation-001.html

https://www.w3.org/TR/css-ruby-1/#anon-gen-anon-ruby

Since the `<ruby>` part and the `<p>` part are sharing the same content and since that test is about generation of an anonymous ruby container, then shouldn't the `<p>` part be rendered identically to the the `<ruby>` part?

**Comment by upsuper** [comment]
The answer is no, because elements between ruby boxes are not creating anonymous ruby boxes in the `<p>` part, but does in the `<ruby>` part.

**Comment by TalbotG** [comment]
Okay. Noted. Thank you for your diligent and instructive reply. :)
