### ISSUE TITLE
`postMessage` test suite: test finishes before assert_equals is triggered

### ISSUE THREAD

**Issue by Gabisampaio** [web-platform-tests/wpt#29536]
### Issue
I am working on the analysis of programs making use of the `postMessage` and `WebWorkers` APIs. When running [one of the tests](https://github.com/web-platform-tests/wpt/blob/master/webmessaging/with-options/one-arg.html) available in this repository, I noticed that the `onmessage` handler was not being triggered. This seems to be also the case when running the test in the Chrome and Firefox browsers. The test 'passes', but no assert is ran. I checked the browser result through this [link](https://wpt.live/webmessaging/with-options/one-arg.html). 

This seems to happen because in the `test` function provided by the [testharness](https://github.com/web-platform-tests/wpt/blob/master/resources/testharness.js#L575), the test phase is set to complete before the `onmessage` handler is triggered. 

### How to fix?
Assuming that this is not the intention (meaning that we want `assert_equals` to be triggered in this test), I am not sure the best way to fix. Is this the desired behaviour of the `test` function? If the harness is implemented correctly, one possible solution may be to change the call from `test` to `async_test`. This makes the  `onmessage` handler to be triggered, meaning that `assert_equals` would run.

More concretely, this is the current test:
```
test(function() {
  postMessage('');
  onmessage = this.step_func(function(e) {
    assert_equals(e.data, '');
    this.done();
  });
});
```

By using `async_test` instead of `test`, we have the following:
```
async_test(function() {
  postMessage('');
  onmessage = this.step_func(function(e) {
    assert_equals(e.data, '');
    this.done();
  });
});
```

**Comment by annevk** [comment]
Yeah, that seems like what it should be doing. Thanks for spotting this! (As per my comment in the other issue, slightly more modern syntax could be used in the eventual fix.)
