### ISSUE TITLE
`postMessage` test suite: purpose of webmessaging/without-ports/008.html

### ISSUE THREAD

**Issue by Gabisampaio** [web-platform-tests/wpt#29546]
I am running the entire `postMessage` test suite against my own implementation and found [this test](https://github.com/web-platform-tests/wpt/blob/master/webmessaging/without-ports/008.html). I was wondering if it would be worth making it more precise, as there is no `assert` check. What do we know if this test passed? Perhaps only that no errors were thrown? Would it make sense to confirm that the message sent arrived successfully with the correct data?

#### Suggestion
Checking that the message arrived successfully could make the test more precise and the modified test seems to pass when ran against both Chrome and Firefox browsers. This change could, however, make the test a duplicate of [this other test](https://github.com/web-platform-tests/wpt/blob/master/webmessaging/with-options/one-arg.html).

Original test:
```
test(function() {
  postMessage('');
  this.done();
 });
```

Modified test:
```
async_test(function() {
  postMessage('');
  onmessage = this.step_func(function(e){
  	assert_equals(e.data, '');
  	this.done();
  });
 });
```

**Comment by Kosoi12983** [comment]
- - - - - - [ ] Крутая чтука Ребза если бы я раньше знеал что так легко всё делаеться я бы раньше заморочился ну не точто легко но не напрягаешься!![image](https://user-images.githubusercontent.com/87102466/124903894-1a837c80-dfed-11eb-9258-e8258ceb7be3.jpeg)![image](https://user-images.githubusercontent.com/87102466/124903953-2a9b5c00-dfed-11eb-8ae5-e9399dbd2938.jpeg)](https://github.com/web-platfo![image](https://user-images.githubusercontent.com/87102466/124904024-3edf5900-dfed-11eb-9f2b-f7219bdb4ac2.jpeg)rm-tests/wpt/issues/29546)

**Comment by Kosoi12983** [comment]
![image](https://user-images.githubusercontent.com/87102466/124904134-574f7380-dfed-11eb-9caf-a61fa6204218.

**Comment by Kosoi12983** [comment]
![image](https://user-images.githubusercontent.com/87102466/124904292-8534b800-dfed-11eb-9569-8c6be94693ea.png)![image](https://user-images.githubusercontent.com/87102466/124904304-8960d580-dfed-11eb-817a-64d4e55bebf3.png)![image](https://user-images.githubusercontent.com/87102466/124904325-8e258980-dfed-11eb-9e20-75902dee8d36.png)![image](https://user-images.githubusercontent.com/87102466/124904351-97aef180-dfed-11eb-8e22-14ae9f7b14fd.png)

**Comment by annevk** [comment]
Yeah that seems fine to me. Thanks for suggesting that. Note that you can use modern syntax and `step_func_done`, as in:

```js
async_test(t => {
  postMessage('');
  onmessage = t.step_func_done(e => {
  	assert_equals(e.data, '');
  });
 });
```
(I prefer using the `t` parameter (which stands for "test") over `this` as it's a tad more explicit, but either works.)

**Comment by Gabisampaio** [comment]
Thank you for your feedback.
