### ISSUE TITLE
Edge dev runs missing on july 8

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#29626]
Edge dev runs are [missing](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) on Jule 8, due to the following errors:

`
##[error]There is not enough space on the disk. : 'C:\Agent\_diag\pages\97d50c23-74ea-4558-803f-8fd0b59c72d4_1.log'
,##[error]Error reported in diagnostic logs. Please examine the log for more details.
`

For more information, see [here](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=67484&view=logs&j=a83c93c4-e19d-55c0-9a01-d818d7882ed7)

**Comment by KyleJu** [comment]
@mustjab Unsure it is a transient issue but would you mind taking a look

**Comment by mustjab** [comment]
Yes, see the same disk space issue, do we do any cleanup of disk space between runs? I'll trigger a rebuild of agent VMs.

**Comment by lucacasonato** [comment]
This was resolved, correct? If so, the issue can be closed.

**Comment by mustjab** [comment]
Yes, I believe so, closing it out.
