### ISSUE TITLE
Problem with WebWorkers test: `workers/constructors/SharedWorker/interface-objects.html`

### ISSUE THREAD

**Issue by Gabisampaio** [web-platform-tests/wpt#29928]
I believe there is at least one issue with [this](https://github.com/web-platform-tests/wpt/blob/6b6a74e478f36b8039d448d8f44f86033dabefa3/workers/constructors/SharedWorker/interface-objects.html) test.

In the script of the HTML file we can see that the message coming from the `worker` thread is expected to be the empty String. This is clear from the following assert:
```
worker.port.onmessage = t.step_func_done(e => {
    assert_equals(e.data, '');
});
```

However, the [`Worker` script](https://github.com/web-platform-tests/wpt/blob/6b6a74e478f36b8039d448d8f44f86033dabefa3/workers/constructors/SharedWorker/interface-objects.js) never sends empty String as message. Below is the handler for the `onmessage` event of the `Worker` script:
```
const handleCall = e => {
  const log = [];
  for (let i = 0; i < e.data.length; ++i) {
    if (!(e.data[i] in self))
      log.push(e.data[i]);
  }
  prt.postMessage('These were missing: '+log.join(', '));
};
```

Even if no property is missing on the `Worker` side, we have the string `These were missing: ` as message, which makes the test to fail. One possible way to fix this would be to replace `prt.postMessage('These were missing: '+log.join(', '));` by `prt.postMessage(log.join(', '));`.

In addition to the fact that `These were missing: ` doesn't match empty String, the test also [fails](https://wpt.live/workers/constructors/SharedWorker/interface-objects.html) on both Chrome and Firefox because the `SharedWorker` seems to be missing on the `Worker` side. Chrome also reports the `Worker` property as missing. Is the browsers behaviour correct or actually the test should assume that there'd be no property missing?

**Comment by annevk** [comment]
Thank you for taking the time to review this test!

As per https://html.spec.whatwg.org/#shared-workers-and-the-sharedworker-interface `SharedWorker` is only exposed on the `Window` global object. As per https://html.spec.whatwg.org/#dedicated-workers-and-the-worker-interface `Worker` should be exposed though (except in service workers for the moment).

Would you be willing to create a pull request for it?

**Comment by Gabisampaio** [comment]
@annevk my pleasure to contribute. Thanks for providing the links to the specification. I will create the pull request.
