### ISSUE TITLE
Experimental Edge runs fail since Aug 5th

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#29938]
Something is wrong with Edge runs as one can see [here](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk). @mustjab could you take a look?

**Comment by mustjab** [comment]
Sorry, was out on vacation. Looks like Edge runs are working now, let me know if that's not the case.

**Comment by past** [comment]
Indeed, the problem was resolved.
