### ISSUE TITLE
wpt-chrome-dev-* tasks are failing

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/wpt#30090]
cc @foolip @KyleJu 

They're failing on all most recent PRs :( 

Example: https://github.com/web-platform-tests/wpt/pull/30074

**Comment by KyleJu** [comment]
@foolip it appears that the script cannot find the correct ChromeDriver URLs to download

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/913405/chromedriver_linux64.zip`

The previous working URL is `https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/913061/chromedriver_linux64.zip`

Should we pin it until we figure out the reason?

**Comment by foolip** [comment]
@KyleJu yes let's pin the version right away and then figure out what went wrong. Can you find the last time it was pinned and create a similar PR?

**Comment by foolip** [comment]
Hmm, in https://github.com/web-platform-tests/wpt/pull/28759 all jobs now pass. Perhaps the problem has been fixed on the Chromium side? I'll look at PRs that were blocked and see if I can get them unstuck.

**Comment by foolip** [comment]
Closing at this fixed itself. Presumably something was reverted in Chromium that fixed this.
