### ISSUE TITLE
Inconsistent pathname in URL constructor

### ISSUE THREAD

**Issue by jimmywarting** [web-platform-tests/wpt#30120]
was disappointed to see someone using a npm package (whatwg-url) instead of using the built `URL` instead...

the problem was the pathname
```js
new URL("bar://foo/baz").pathname
// FF = "//foo/baz"
// Safari = "/baz"
// chrome = "//foo/baz"
// node = "/baz"
// deno = "/baz"
```

is there a test case and a bug report for this?
also: what is the correct behaviour?

**Comment by lucacasonato** [comment]
Safari, Deno & Node have the correct behaviour. FF and Chrome are wrong.

This is also the wrong repo for this. WPT is the test suite for the test infrastructure for web platform tests, not for questions / discussions about individual specifications. For discussion regarding the URL spec: https://github.com/whatwg/url
