### ISSUE TITLE
URL spec test coverage report

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#3018]
FYI @annevk @Sebmaster @jasnell.

I managed to cobble this together:
- [URL state machine coverage report](https://dl.dropboxusercontent.com/u/20140634/url-spec-coverage/lib/url-state-machine.js.html): ~99%
- [URL object coverage report](https://dl.dropboxusercontent.com/u/20140634/url-spec-coverage/lib/URL-impl.js.html): ~94%

Areas of lacking coverage are:
- some origin serialization stuff (some purposefully untested)
- The href setter
- One early-return case in the hash setter
- One "else" branch in IPv4 parsing

**Comment by annevk** [comment]
Oh sweet, can you generate new reports? Would love to add more tests, in particular now with Safari actively implementing.

**Comment by domenic** [comment]
Yeah, it's just `npm run coverage` from within the whatwg-url project. I've generated a new report at the same URL and updated the OP. Coverage went from 90 -> 95 and 85 -> 94 for those two files.

**Comment by jasnell** [comment]
Very nice.

**Comment by domenic** [comment]
Updated the OP after #4882. Very nice.

**Comment by annevk** [comment]
Can we also get coverage on IDNA, which is just a single method in this library?

**Comment by GPHemsley** [comment]
@domenic The links here are dead. Is this something that we're still looking to have? (I'm guessing yes.) Does this issue serve that purpose?

**Comment by domenic** [comment]
I think we got to 100% coverage at some point. I'm no longer actively tracking this, but you can checkout jsdom/whatwg-url, run `npm install`, then `npm run coverage` to get a report. I'll close this now since this issue isn't too helpful.
