### ISSUE TITLE
[css-sticky] Failing tests on WebKit due to web font load timing

### ISSUE THREAD

**Issue by mrobinson** [web-platform-tests/wpt#30194]
Some tests like `css/css-position/sticky/position-sticky-inline.html` fail on WebKit because `createIndicatorForStickyElements` measures the size of a div before all web fonts (such as Ahem, which this test uses) are loaded.

See: https://wpt.fyi/analyzer?screenshot=sha1%3A4cd4143965e95a637f15df86978e2b510d453bdb&screenshot=sha1%3A703c91539642a8406336b8eceb847a2745ac819a

**Comment by foolip** [comment]
@mrobinson was this fixed by https://github.com/web-platform-tests/wpt/pull/30192?

**Comment by mrobinson** [comment]
Thanks for the reminder. This was fixed by #30211.
