### ISSUE TITLE
Please help: ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by vbzhu** [web-platform-tests/wpt#30275]
When I followed the direction [here ](https://web-platform-tests.org/running-tests/from-local-system.html) to do Windows Setup, after successful execution of "pip install virtualenv", I got error "ModuleNotFoundError: No module named 'tools'". Can you please help?

**Comment by foolip** [comment]
@vbzhu I've gone ahead and moved this issue to wpt, the repo that I think you're having issues with. Can you paste the error you get when trying to run `python wpt serve`? I'm wondering what line it happens on. I think it ought to be `from tools.wpt import wpt` in the `wpt` file in the root of the repo, but want to make sure and not guess.

**Comment by vbzhu** [comment]
Hi Philip,

Thank you for your followup! The error is "ModuleNotFoundError: No module, named 'tools'. Please review the screenshot below:
***@***.***

Regards,

Zili (Leo) Hu

**Comment by foolip** [comment]
@vbzhu sorry I missed your reply. Unfortunately, I don't see the screenshot, which I think is because you replied by email. Can you paste the screenshot in GitHub instead?

**Comment by past** [comment]
Closing as it has been more than a year without a response. Feel free to reopen when you can provide the requested information.
