### ISSUE TITLE
css-transforms/transform-origin/svg-origin* tests use invalid transform style

### ISSUE THREAD

**Issue by smfr** [web-platform-tests/wpt#30553]
There are lots of tests in css-transforms/transform-origin/ which use `transform="rotate(90deg)"` but this is not a supported value for `transform` when applied to SVG (https://www.w3.org/TR/css-transforms-1/#svg-transform-functions). These tests fail in all browsers.

I propose changing the test to use `rotate(90)`.

**Comment by smfr** [comment]
cc @dbaron @dirkschulze

**Comment by smfr** [comment]
There are also tests like `css/css-transforms/group/svg-transform-nested-005.html` that use `transform="scaleX(2)"` which is also not supported.

**Comment by dbaron** [comment]
Fixed in #30852 and #30867.
