### ISSUE TITLE
[workers] Issue in test `constructors/SharedWorker/setting-port-members.html`

### ISSUE THREAD

**Issue by Gabisampaio** [web-platform-tests/wpt#31125]
I think that there may be an issue with [this](https://github.com/web-platform-tests/wpt/blob/6b6a74e478f36b8039d448d8f44f86033dabefa3/workers/constructors/SharedWorker/setting-port-members.html) test. I checked the [result](https://wpt.live/workers/constructors/SharedWorker/setting-port-members.html) on both Chrome and Firefox browsers.

The test tries to assign an object containing the `handleEvent` property to `worker.port.onmessage` and expects the assignment not to take effect, by checking if `worker.port.onmessage` is set to `null` afterwards.
I include the specific part of the test code below:
```
...
worker.port.onmessage = {handleEvent:() => {}};
assert_equals(worker.port.onmessage, null, '{handleEvent:() => {}}');
...
```
The call to `assert_equals` fails and we see the following by running the test on both Chrome and Firefox browsers:
```
assert_equals: {handleEvent:() => {}} expected null but got object "[object Object]"
```
It makes sense to me that the test fails, as handlers are usually assigned this way (an object containing the `handleEvent` property). Would the test need to be fixed then? Perhaps of checking if `worker.port.onmessage` is set to `null`, we should check if it is set to the given object?

**Comment by annevk** [comment]
Well, `{ handleEvent() }` isn't considered a callback by IDL I think. However, `EventHandler` is annotated with [`[LegacyTreatNonObjectAsNull]`](https://webidl.spec.whatwg.org/#LegacyTreatNonObjectAsNull) which I think means that if you assign an object it gets wrapped into a callback (that ends up doing nothing). However, that also does not seem to be what implementations are doing.

E.g.,
```js
onblur = { handleEvent:() => { alert(1) } };
w(typeof onblur);
```
gives "object", not "function".

I'll ask some other people to chime in.
