### ISSUE TITLE
Vendored version of `hyper` is not compatible with Python 3.10

### ISSUE THREAD

**Issue by mitchhentges** [web-platform-tests/wpt#31315]
A bunch of classes were moved from `collections` to `collections.abc`. More details about that are documented [here](https://docs.python.org/3.9/library/collections.html#module-collections). In Python 3, the "compatibility" re-exports in `collections` were removed, so obsolete imports are now causing errors.

The current vendored `hyper` version isn't compatible with the new class location, as visible [here, for example](https://github.com/web-platform-tests/wpt/blob/master/tools/third_party/hyper/hyper/common/headers.py#L13).

Note that this [isn't fixed upstream](https://github.com/python-hyper/hyper/blob/development/hyper/common/headers.py#L13), and the project [is no longer maintained](https://github.com/python-hyper/hyper/blob/development/README.rst).

Note: I'm not personally seeing errors from this, but I'm not running WPT locally. Perhaps `hyper` isn't used in a way where it runs the obsolete code, I'm not sure (though I'd be surprised if that was the case).

**Comment by jgraham** [comment]
We only use hyper itself in unittests; I think we could trivially replace it with httpx. We use h2 and hyperframe on the server side, but I believe those are both still supported.

**Comment by foolip** [comment]
I sent https://github.com/web-platform-tests/wpt/pull/33112 to fix this.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/33113 is an alternative, if that can be made to work.
