### ISSUE TITLE
flexbox-min-width-auto-{005,006}.html might need to update to reflect a spec resolution

### ISSUE THREAD

**Issue by aethanyc** [web-platform-tests/wpt#31609]
I've been hacking Firefox's flexbox implementation in [bug 1735589](https://bugzilla.mozilla.org/show_bug.cgi?id=1735589) to match the spec resolution in https://github.com/w3c/csswg-drafts/issues/6693. The conclusion is basically that a flex item's stretched cross-size should be considered and can be transferred through aspect-ratio when computing the item's content size suggestion. 

I notice my patched Firefox starts to fail these two tests added in #27596:
http://wpt.live/css/css-flexbox/flexbox-min-width-auto-005.html
http://wpt.live/css/css-flexbox/flexbox-min-width-auto-006.html

Google Chrome also fails the two tests.

@davidsgrogan has changed some tests in https://github.com/web-platform-tests/wpt/pull/30900 to reflect the spec resolution.

@svillar Do you feel like the two tests are not reflect https://github.com/w3c/csswg-drafts/issues/6693, and should be updated?

**Comment by aethanyc** [comment]
For `flexbox-min-width-auto-005.html`, we can probably remove the `<br>` and its style because `br { margin: 50px; }` has effect only in gecko. Without the `<br>`, the test reference can be a green square `ref-filled-green-100px-square.xht`.

**Comment by davidsgrogan** [comment]
I agree that these min-with-auto tests assert incorrect behavior.

**Comment by davidsgrogan** [comment]
Oops didn't mean to close

**Comment by aethanyc** [comment]
I think the testcases has been fixed by #35362.
