### ISSUE TITLE
No Edge runs since Nov 15th

### ISSUE THREAD

**Issue by stephenmcgruer** [web-platform-tests/wpt#31680]
Currently the front-page of wpt.fyi is showing data from Nov 12th, as that is the last day that had aligned runs across Chrome, Edge, Firefox, and Safari. The culprit appears to be Edge; based on https://wpt.fyi/runs?label=master&from=2021-11-11T00%3A00 it hasn't had a run complete since Nov 15th (which happened to not be aligned, hence why wpt.fyi is on Nov 12th).

Looking at the [wpt.fyi API](https://wpt.fyi/api/runs?product=edge), it looks like there is maybe a large backlog here, as the latest Edge run is for 625a2df832 (which landed Nov 15th, as noted above), but the run wasn't actually created (according to the metadata) until Nov 18th, i.e. today!

If something was stuck, it's possible that these may work their way through and eventually catch up, but I wanted to raise this issue in case they aren't catching up.

**Comment by KyleJu** [comment]
Edge runs are still missing today and the last available run was on Nov 15th. Looking at the Azure, all edge runs appear to be stuck and in [`queued` status](https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=73763&view=results). @mustjab would you mind taking a look?

**Comment by mustjab** [comment]
We rebuild VMs every Monday morning and looks like runs are progressing now. Not sure what was blocking runs but let me know if that is still happening.

**Comment by KyleJu** [comment]
Runs are back. Thanks @mustjab!!
