### ISSUE TITLE
css/css-color/color-mix-basic-001.tentative.html incorrectly assumes results of color-mix(in srgb ...) are rgb() style colors

### ISSUE THREAD

**Issue by weinig** [web-platform-tests/wpt#31916]
css/css-color/color-mix-basic-001.tentative.html incorrectly assumes results of `color-mix(in srgb ...)` are `rgb()` style colors, but the spec states they should be of the form `color(srgb )`.

**Comment by nt1m** [comment]
Duplicate of #32065
