### ISSUE TITLE
CSS sizing fit-content doesn't need -moz prefix any more

### ISSUE THREAD

**Issue by robinmetral** [web-platform-tests/wpt#32014]
It looks like since Firefox 94,  there's no need for the `-moz` vendor prefix for the CSS `fit-content` size (bugfix: https://bugzilla.mozilla.org/show_bug.cgi?id=1732759).

Several tests are still using the prefix, should we remove them? Happy to submit a PR for this but I might need some help—is removing the prefix enough or would that be a test regression somehow?

**Comment by nt1m** [comment]
@robinmetral Please feel free to submit a PR to remove the prefix :)
