### ISSUE TITLE
color-mix-basic-001.html and color-mix-non-srgb-001.html have incorrect results

### ISSUE THREAD

**Issue by weinig** [web-platform-tests/wpt#32065]
The tests color-mix-basic-001.html and color-mix-non-srgb-001.html have incorrect results. The tests use a reference color of the form 'rgb()` for the results, but serialization of `color-mix()` only results in a `rgb()` color when mixing in the `hwb` or `hsl` color spaces, which the test isn't using. Instead, it the results should be in the form described by https://drafts.csswg.org/css-color-5/#serial-color-mix.

**Comment by nt1m** [comment]
cc @emilio @brennie who wrote those tests

**Comment by emilio** [comment]
Gecko doesn't parse color() so we don't serialize it either... Perhaps the test could be adjusted to allow both serializations for now? It'd be unfortunate for us to lose that test coverage

**Comment by weinig** [comment]
One option would be to convert this to a reference test, rather than a script driven test of serialization. As a reference test, gecko will still pass since the colors will be equivalent on render.

But in actually testing serialization, I think we should try to keep the tests to what is specified.

**Comment by weinig** [comment]
I put up a PR that makes the tests into ref tests - https://github.com/web-platform-tests/wpt/pull/32196. @Emilio, what do you think?

**Comment by svgeesus** [comment]
Converting this to a reftest helps with testing `color-mix()` but we do also need tests for serailizing it per-spec, as well.

**Comment by weinig** [comment]
> Converting this to a reftest helps with testing `color-mix()` but we do also need tests for serailizing it per-spec, as well.

We have quite a few serialization tests for `color-mix()` in css/css-color/parsing/color-mix-valid.html, css/css-color/parsing/color-mix-invalid.html and css/css-color/parsing/color-mix-computed.html.
