### ISSUE TITLE
Limit the use of www/www1 URLs

### ISSUE THREAD

**Issue by youennf** [web-platform-tests/wpt#3243]
There is reluctancy in WebKit community to require modifying etc/hosts to run WPT tests.
In WebKit test environment, there is the possibility to use localhost, 127.0.0.1, different ports, different schemes.

For most tests, having two different host names is good enough.
I have not yet seen tests using more than 3 different host names.

I am wondering whether we could not add a configuration option to have something like:
hosts = ["domain", "www.domain"...] for w3c environment and hosts = ["127.0.0.1", "localhost"...] for WebKit environment.

In lieu of writing "www." + {{host}} in tests, we could just write {{host[1]}}.

**Comment by jdm** [comment]
Servo's solution was to add in-application host replacement, so every time a network connection is about to be initiated we check if the host is present in a hashmap and replace it if necessary.

**Comment by youennf** [comment]
See https://github.com/w3c/web-platform-tests/pull/3302.

**Comment by annevk** [comment]
I wonder if we should move that utility library to `/common/` and use it in even more places...

**Comment by youennf** [comment]
get_host_info.sub.js is in /common/.
I plan to update web-platform-tests/cors to use it.
Except where hierarchical domains is meaningful, it makes sense to me to transition to this.

**Comment by annevk** [comment]
Cool, there might also be some tests in XMLHttpRequest that can use it. And I might have started using it already actually here and there in those directories. Do you want to keep this open as a tracking issue?

**Comment by youennf** [comment]
Closing in favor of https://github.com/web-platform-tests/wpt/issues/15692
