### ISSUE TITLE
cookies/attributes/secure-non-secure.html looks broken

### ISSUE THREAD

**Issue by johannhof** [web-platform-tests/wpt#32558]
See https://wpt.fyi/results/cookies/attributes/secure-non-secure.html?label=master&label=experimental&aligned

Most browsers are failing with `PROMISE_REJECT(object "Error: Tried to run in a non-testharness window without a call to set_test_context")` which doesn't seem intended?

I get the same results when running locally.

**Comment by miketaylr** [comment]
This used to work, but possibly broken by the move to delete_all_cookies, according to https://github.com/web-platform-tests/wpt/commits/master/cookies/attributes/secure-non-secure.html. @arichiv, thoughts?

**Comment by arichiv** [comment]
I’ll take a look tomorrow, *should* be a quick fix if it’s what I think.

**Comment by arichiv** [comment]
Looks good (the errors are of the normal variety now). Closing out https://wpt.fyi/results/cookies/attributes/secure-non-secure.html?diff&filter=ADC&run_id=5105431279042560&run_id=5156225038680064
