### ISSUE TITLE
wpt runner hits timeout after 30 seconds if a file has a lot of test cases

### ISSUE THREAD

**Issue by AutomatedTester** [web-platform-tests/wpt#32899]
When working on https://github.com/web-platform-tests/wpt/pull/32679 I was not able to create extensive test suite because the runner would hit a timeout after 30 seconds when I was trying to parameterise all the different combinations

**Comment by whimboo** [comment]
@AutomatedTester I assume we can get this closed? The issue was actually with chromedriver that it delayed each each navigation quite a lot and this caused a timeout even for just a handful of tests within a file.

If you feel otherwise, please reopen.
