### ISSUE TITLE
A few of the css/css-color tests are failing due to text anti-aliasing artifacts, not what the test is actually trying to test

### ISSUE THREAD

**Issue by weinig** [web-platform-tests/wpt#33058]
A few of the css/css-color tests are failing in some browsers due to text anti-aliasing artifacts, not what the test is actually trying to test.

- css/css-color/t422-rgba-a0.6-a.xht
- css/css-color/t425-hsla-basic-a.xht

Given that we don't define the specific of text anti-aliasing, I propose we convert these tests to use boxes instead.

**Comment by fred-wang** [comment]
This sounds like a "good first bug".

cc'ing Igalia's CE student @SirriCelles

**Comment by svgeesus** [comment]
I converted those two and was surprised to see a mismatch in `t425-hsla-basic-a.xht`.

I think some implementations are compositing used values in device RGB, so on a WCG screen they don't match.
See https://github.com/w3c/fxtf-drafts/issues/427#issuecomment-1650412640:

> there already exist some browsers on macOS which perform compositing in the display-p3 colourspace if the display is capable.
