### ISSUE TITLE
Tests for early hints

### ISSUE THREAD

**Issue by noamr** [web-platform-tests/wpt#33076]
Currently there is [one test](https://github.com/web-platform-tests/wpt/commit/13c0277fc067505432471ed693596a94461920a7#diff-9f5c00c0c13931bc28f13118192568ee1a6d8b2a6b2325f9c42491758e7a665c) for early hints.

To cover https://github.com/whatwg/html/pull/7675, the following scenarios need to be tested:
- [x] early preload fully loaded before the document
- [x] early preload starts loading, fully loaded before consumed
- [x] early preload still in flight when consumed
- [x] Early preload with CSP (allowed, denied)
- [x] Early preload without CSP, document CSP later denies it
- [x] Early preload without CSP, document CSP later allows it
- [x] Early preload with/without CSP, document starts while request in flight, later different CSP denies it
- [x] Multiple 103 before 200, some with CSP
- [x] Early hints to non-200 (e.g. 103 preloads an image -> a 404 page with that image)
- [x] 103 before same-origin redirect
- [x] 103 before cross-origin redirect
- [x] Sprinkled 103s with redirects (e.g. 103 -> 302 -> 103 -> 200)
- [x] 103 with invalid headers
- [x] 103 with unsupported headers (anything but preload links / CSP)
- [x] referrer policy in 103 match/doesn't match the one in the final response
- [x] COEP matches/doesn't match the final response

**Comment by bashi** [comment]
@noamr Could you elaborate the difference between the first task and the second task?

**Comment by noamr** [comment]
> @noamr Could you elaborate the difference between the first task and the second task?

Sure:
The sequence of events:

1. nav 103 -> start loading subresource -> finished loading subresource -> main resource 200, initialize document -> consume
2. nav 103 -> start loading subresource -> main resource 200, initialize document -> finished loading subresource -> consume

**Comment by bashi** [comment]
I've added these tests. @noamr Do you think we can close this, or do you have other test cases?

**Comment by noamr** [comment]
> I've added these tests. @noamr Do you think we can close this, or do you have other test cases?

Yes! Great work!
