### ISSUE TITLE
lint checker tool no longer fetchable, no longer found

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#33192]
@web-platform-tests/admins , @web-platform-tests/wpt-core-team 

There used to be a lint program inside a wpt folder at the root of my web-platform-tests working directory for checking css tests before actually submitting them. Now, there is no wpt folder and I can not find the lint checker anywhere.

[The lint documentation still is the same](http://web-platform-tests.org/writing-tests/lint-tool.html)

How am I supposed to check css tests before actually submitting them in a PR?

Thank you for your assistance,

Gérard

**Comment by foolip** [comment]
Do you mean there used to be a file (script) called `lint`? If that's the case, it's now a subcommand of `wpt` which per the docs you run as `./wpt lint` on the command line.

**Comment by foolip** [comment]
@TalbotG starting from your checkout of https://github.com/web-platform-tests/wpt, do you see a file called just `wpt` with this content?

https://github.com/web-platform-tests/wpt/blob/93068ae96dda375b249ec97434033077fba7c5a7/wpt#L1-L11

That's the script you should invoke as `./wpt lint`.

If you can't find the directory or the script at all, I suggest starting from a fresh checkout.

**Comment by TalbotG** [comment]
Philip,

With cat wpt, I can see that I have:

```
#!/usr/bin/env python

if __name__ == "__main__":
    import sys
    from tools.wpt import wpt
    args, extra = wpt.parse_args(sys.argv[1:])
    commands = wpt.load_commands()
    py3only = commands[args.command]["py3only"]

    if (args.py3 or py3only) and sys.version_info.major < 3:
        from subprocess import call
        try:
            sys.exit(call(['python3'] + sys.argv))
        except OSError as e:
            if e.errno == 2:
                sys.stderr.write("python3 is needed to run this command\n")
                sys.exit(1)
            else:
                raise
    else:
        wpt.main()
```

**Comment by TalbotG** [comment]
$ python --version
bash: python : commande introuvable

(translation: unknown command)

$ sudo apt install python
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Note : sélection de « python-is-python2 » au lieu de « python »
Les paquets supplémentaires suivants seront installés : 
  libpython2-stdlib python2 python2-minimal
Paquets suggérés :
  python2-doc python-tk
Les NOUVEAUX paquets suivants seront installés :
  libpython2-stdlib python-is-python2 python2 python2-minimal
(...cancelling installation...)

Philip,

Are those packages correct, appropriate? python-is-python2 is selected instead of python

**Comment by foolip** [comment]
@TalbotG you'll need Python 3 and Virtualenv, I'd suggest following the instructions in https://web-platform-tests.org/running-tests/from-local-system.html to make sure you have everything.

Since you mention python-is-python2, it's not important that `python --version` reports Python 3, it's the `python3` binary that's used.

If you install the python3 it will probably be fine, but make sure to avoid 3.10, since that doesn't work yet due to https://github.com/web-platform-tests/wpt/issues/31315.

**Comment by TalbotG** [comment]
Philip,

Thank you for your complete answer-reply.

I have installed virtualenv
https://packages.debian.org/bullseye/virtualenv

python3-pip (there is no python-pip for Linux Debian stable version)
https://packages.debian.org/stable/python/python3-pip

and python3 version 3.9.2-3
https://packages.debian.org/stable/python/python3

Calling the lint function appears to work now. I am resolving this issue.

Again, thank you for your complete and precise assistance in
fixing this issue for me.

Gérard
