### ISSUE TITLE
"Chrome Nightly" runs are failing after Chrome / Chromium split

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#33496]
After https://github.com/web-platform-tests/wpt/pull/32485 there was a failure in runs triggered by the epochs/daily branch when updated to https://github.com/web-platform-tests/wpt/commit/86a6f71391e48581aec60e6b9e25f9a80dc86a75. From https://community-tc.services.mozilla.com/tasks/Nn1LbgekRzKjooHdr8Ygtg/runs/0/logs/public/logs/live.log:

```
Traceback (most recent call last):
  File "./wpt", line 10, in <module>
    wpt.main()
  File "/home/test/web-platform-tests/tools/wpt/wpt.py", line 212, in main
    rv = script(*args, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 830, in run
    wptrunner_kwargs = setup_wptrunner(venv, **kwargs)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 796, in setup_wptrunner
    kwargs["binary"] = setup_cls.install(channel=channel)
  File "/home/test/web-platform-tests/tools/wpt/run.py", line 177, in install
    return self.browser.install(self.venv.path, channel)
  File "/home/test/web-platform-tests/tools/wpt/browser.py", line 892, in install
    raise NotImplementedError("Installing of Chrome browser binary not implemented.")
NotImplementedError: Installing of Chrome browser binary not implemented.
```

This is happening because of this config:

https://github.com/web-platform-tests/wpt/blob/7c8c4ea146b8f34bbda2f27dc9ec552396578b07/tools/ci/tc/tasks/test.yml#L168-L171

That was supposed to be testing Chromium, and previously was, but is now testing a non-existed Chromium Nightly config and failing.

@DanielRyanSmith can you check if running Chromium ToT here would work, and more importantly if we want to do that? I'm not sure if anyone is looking at the results triggered by these nightly runs. Digging into when they were added might reveal the user :)

**Comment by DanielRyanSmith** [comment]
Switching these tests to Chromium nightly ToT will work and would be using the same process, so that should not be a problem. In terms of if we want to do so, it seems that [the triggers for running this](https://github.com/web-platform-tests/wpt/pull/24904) were added a little over a year ago.
