### ISSUE TITLE
Add platform information to chrome_android wpt report

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#33794]
See https://github.com/web-platform-tests/wpt.fyi/pull/2842#discussion_r854718473 for the discussions. wpt.fyi requires the correct platform information to show platform icons next to the browser icons on UI. The platform information should be added to the WPT report.

**Comment by KyleJu** [comment]
@WeizhongX

**Comment by KyleJu** [comment]
You are right the platform icon is next to it. Chatted with Philip and we decided that a temporary mapping is fine for now. Thanks!

**Comment by WeizhongX** [comment]
Thanks for working on this.
