### ISSUE TITLE
`test_driver.click()` doesn't trigger click event handlers on mac

### ISSUE THREAD

**Issue by yoavweiss** [web-platform-tests/wpt#34092]
When trying to land a [Chromium CL](https://chromium-review.googlesource.com/c/chromium/src/+/3360889) with tests that rely on TestDriver driven clicks, I'm seeing [build failures](https://ci.chromium.org/ui/p/chromium/builders/try/mac-rel/999358/overview) related to the fact that the click is not triggering the related event handlers on Mac. Is this a known issue? Any known workarounds?

**Comment by gsnedders** [comment]
AFAIK, Chromium is still using its own implementation of the testdriver primitives, therefore there's nothing we can do here.
