### ISSUE TITLE
Infrastructure tests failing

### ISSUE THREAD

**Issue by jgraham** [web-platform-tests/wpt#34183]
It looks like Firefox is crashing running reftests. This is blocking all PRs that run infrastructure tests.

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/34199 has a workaround by this issue which is tracked as https://bugzilla.mozilla.org/show_bug.cgi?id=1771146

**Comment by whimboo** [comment]
@jgraham I assume we can close this issue given that the related crasher got fixed in Firefox Nightly. Shall we close/reopen all the blocked PRs now?

**Comment by gsnedders** [comment]
This clearly got fixed long ago and isn't urgent.
