### ISSUE TITLE
IDL Harness tests for ShadowRealms hanging after #33668

### ISSUE THREAD

**Issue by mgaudet** [web-platform-tests/wpt#34221]
I've been working on implementing ShadowRealms for Firefox, and recently went to re-test the web-platform IDL harness tests, and found they had stopped working, hanging until timeout.

After some investigation, I finally found that reverting #33668 caused them to start working again.

I can't figure out exactly what's going on -- as near as I can tell, with a bit of console.log debugging, for some reason [the completion callback](https://github.com/web-platform-tests/wpt/blob/c679ed0e6077b5ca963ca5376c300beaae770335/resources/idlharness-shadowrealm.js#L54-L55) is never getting invoked, which means that the promise never resolves.

**Comment by andreubotella** [comment]
cc @lucacasonato @jjgriego @Ms2ger

**Comment by Ms2ger** [comment]
#34250 should fix the side note, at least. Are you continuing to debug or should I try to look as well? (Not sure I'll get to it this week.)

**Comment by mgaudet** [comment]
Bisecting the revert patch a bit, root cause seeems to be the replacing of 

```js
if ('AbortController' in global_scope) {
```

with 

```js
if (global_scope.GLOBAL && global_scope.GLOBAL.isShadowRealm()) {
```

I expect that there's somewhere that's missed creating global_scope.GLOBAL, and so we're actually using ShellTestEnvironment inappropriately; unfortunately I've not been able to get much more feedback than that -- debugging across shadow realms isn't fun.

**Comment by mgaudet** [comment]
Prototype ShadowRealms support is in Firefox Nightly [now](https://bugzilla.mozilla.org/show_bug.cgi?id=1747059); we'll try to run the WebIDL harness tests once this bug is fixed. 

If anyone needs any help testing out a solution I can try patches.

**Comment by Ms2ger** [comment]
@mgaudet I think https://github.com/web-platform-tests/wpt/pull/36357 may have fixed this; could you take a look?

**Comment by mgaudet** [comment]
It does appear that #36357 has fixed this!
