### ISSUE TITLE
`test_driver.click()` does not fire mousemove/pointermove on Safari

### ISSUE THREAD

**Issue by saschanaz** [web-platform-tests/wpt#34456]
Context: https://github.com/web-platform-tests/wpt/pull/32381#issuecomment-1156872861

>WebKit does emit move events from physical click but somehow not from test_driver.click().

**Comment by saschanaz** [comment]
Per https://wpt.fyi/results/infrastructure/testdriver/actions/penPointerEvents.html?label=experimental&label=master&aligned Safaridriver seemingly ignores pointerMove before any pointerDown. 🤔

**Comment by gsnedders** [comment]
> Hmm, just checked the stable channel behavior. It initially fires pointermove as expected and then it again ignores as STP does 🤔. Maybe I should wait for the next STP, unless I find some way to get a nightly build. (wpt.fyi is showing STP, right?)

Yeah, I'm starting to question my original diagnosis here… too quick to attribute any click regression to that!

> Well, I think it's worth since Windows desktop certainly supports pen. (And probably others too if a stylus device is connected)

Oh, no, I mean Safari on macOS specifically! Safari on macOS has no reason to support pen input, and I thought it was behind the touch compile-time flag hence was expecting it to fail!

**Comment by gsnedders** [comment]
https://wpt.fyi/results/webdriver/tests/element_click/events.py?label=master&product=safari%5Bstable%5D&product=safari%5Bexperimental%5D shows mousemove firing in stable.

More recent (unreleased) Safari with the above regression fixed gives:

```
/webdriver/tests/element_click/events.py
  FAIL test_event_mousemove - AssertionError: assert [{'button': 0, 'buttons': 0, 'type': 'mousemove'},\n {'button': 0, 'buttons': 1, 'type': 'mousedown'},\n {'button': 0, 'buttons': 0, 'type': 'mouseup'},\n {'button': 0, 'buttons': 0, 'type': 'click'}] == [{'button': 0, 'buttons': 0, 'type': 'mousemove'},\n {'button': 0, 'buttons': 0, 'type': 'mousedown'},\n {'button': 0, 'buttons': 0, 'type': 'mouseup'},\n {'button': 0, 'buttons': 0, 'type': 'click'}]
session = <Session 74696842-C411-469E-8DED-D1CE03D1A839>, url = <function url.<locals>.url at 0x10f887670>

    def test_event_mousemove(session, url):
        session.url = url("/webdriver/tests/element_click/support/test_click_wdspec.html")
    
        element = session.find.css('#outer', all=False)
        response = element_click(session, element)
        assert_success(response)
    
        events = get_events(session)
        assert len(events) == 4
    
        expected = [
            {"type": "mousemove", "buttons": 0, "button": 0},
            {"type": "mousedown", "buttons": 1, "button": 0},
            {"type": "mouseup", "buttons": 0, "button": 0},
            {"type": "click", "buttons": 0, "button": 0},
        ]
        filtered_events = [filter_dict(e, expected[0]) for e in events]
    
>       assert expected == filtered_events
E       AssertionError: assert [{'button': 0, 'buttons': 0, 'type': 'mousemove'},\n {'button': 0, 'buttons': 1, 'type': 'mousedown'},\n {'button': 0, 'buttons': 0, 'type': 'mouseup'},\n {'button': 0, 'buttons': 0, 'type': 'click'}] == [{'button': 0, 'buttons': 0, 'type': 'mousemove'},\n {'button': 0, 'buttons': 0, 'type': 'mousedown'},\n {'button': 0, 'buttons': 0, 'type': 'mouseup'},\n {'button': 0, 'buttons': 0, 'type': 'click'}]
E         At index 1 diff: {'type': 'mousedown', 'buttons': 1, 'button': 0} != {'type': 'mousedown', 'buttons': 0, 'button': 0}
E         Full diff:
E           [
E            {'button': 0, 'buttons': 0, 'type': 'mousemove'},
E         -  {'button': 0, 'buttons': 0, 'type': 'mousedown'},
E         ?                           ^
E         +  {'button': 0, 'buttons': 1, 'type': 'mousedown'},
E         ?                           ^
E            {'button': 0, 'buttons': 0, 'type': 'mouseup'},
E            {'button': 0, 'buttons': 0, 'type': 'click'},
E           ]
```

…which matches what wpt.fyi has for stable.

**Comment by saschanaz** [comment]
Thanks!

And sorry, I was talking about #32381 in https://github.com/web-platform-tests/wpt/issues/34456#issuecomment-1161872026. Could you try #32381 and see what happens there in your nightly build? The minimum expected result is that the first two tests must never fail with initial `mousemove`.

**Comment by saschanaz** [comment]
Oh I see, thank you again!

`Trusted click on <input>, observed from <input>` also passes on stable channel, what I don't understand is that `Trusted click on <input>, observed from <body>` after that still fails with no mousemove. But maybe that's because the mouse pointer coordination will be same there? In that case I'm not sure how that passes on Gecko/Blink 🤔

Anyway, I'll take another look at that. Thanks!

**Comment by saschanaz** [comment]
Okay, I still think there's some issue on Safari, I'll cook a separate minimal infra test for this.

**Comment by gsnedders** [comment]
@saschanaz you might want to try re-triggering things now that STP 148 has shipped

**Comment by gsnedders** [comment]
I'm assuming this is fixed, as it seems to be.
