### ISSUE TITLE
WebKitGTK runs missing since june 11

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#34473]
[WebKitGTK runs missing since June 11](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk). @clopez would you mind taking a look?

**Comment by clopez** [comment]
It seems the [tests are timing out for an unknown reason](https://community.taskcluster-artifacts.net/RvfuW6U5Quuttg_7Qararg/0/public/logs/live_backing.log)

However the run 20th worked.

I keep and eye on this and will try to debug the issue. Thanks for the notice

**Comment by clopez** [comment]
The server generating the built-products was fixed on 26th of July. Since then, the runs have started to work back again.

**Comment by mcatanzaro** [comment]
So this can be closed?

**Comment by KyleJu** [comment]
Yup it can be closed. Thanks for the fix!
