### ISSUE TITLE
Missing tests for the legacy aliases of the compat spec

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#34493]
The compat spec has a section called [legacy name aliases](https://compat.spec.whatwg.org/#css-simple-aliases). These are the properties which are necessary to support for a browser to be able to work with the Web.

* [x] Do we have tests for each of these aliases?
* [x] Should they be in their own compat section? Or in each thematic individual section?
* [x] `-webkit-align-items` `align-items`
* [x] `-webkit-align-content` `align-content`
* [x] `-webkit-align-self` `align-self`
* [x] `-webkit-animation-name` `animation-name`
* [x] `-webkit-animation-duration` `animation-duration`
* [x] `-webkit-animation-timing-function` `animation-timing-function`
* [x] `-webkit-animation-iteration-count` `animation-iteration-count`
* [x] `-webkit-animation-direction` `animation-direction`
* [x] `-webkit-animation-play-state` `animation-play-state`
* [x] `-webkit-animation-delay` `animation-delay`
* [x] `-webkit-animation-fill-mode` `animation-fill-mode`
* [x] `-webkit-animation` `animation`
* [x] `-webkit-backface-visibility` `backface-visibility`
* [ ] `-webkit-background-clip` `background-clip`
* [x] `-webkit-background-origin` `background-origin`
* [x] `-webkit-border-bottom-left-radius` `border-bottom-left-radius`
* [x] `-webkit-border-bottom-right-radius` `border-bottom-right-radius`
* [x] `-webkit-border-top-left-radius` `border-top-left-radius`
* [x] `-webkit-border-top-right-radius` `border-top-right-radius`
* [x] `-webkit-border-radius` `border-radius`
* [x] `-webkit-box-shadow` `box-shadow`
* [x] `-webkit-box-sizing` `box-sizing`
* [x] `-webkit-flex` `flex`
* [x] `-webkit-flex-basis` `flex-basis`
* [x] `-webkit-flex-direction` `flex-direction`
* [x] `-webkit-flex-flow` `flex-flow`
* [x] `-webkit-flex-grow` `flex-grow`
* [x] `-webkit-flex-shrink` `flex-shrink`
* [x] `-webkit-flex-wrap` `flex-wrap`
* [x] `-webkit-filter` `filter`
* [x] `-webkit-justify-content` `justify-content`
* [x] `-webkit-mask` `mask`
* [x] `-webkit-mask-box-image` `mask-border`
* [x] `-webkit-mask-box-image-outset` `mask-border-outset`
* [x] `-webkit-mask-box-image-repeat` `mask-border-repeat`
* [x] `-webkit-mask-box-image-slice` `mask-border-slice`
* [x] `-webkit-mask-box-image-source` `mask-border-source`
* [x] `-webkit-mask-box-image-width` `mask-border-width`
* [x] `-webkit-mask-clip` `mask-clip`
* [x] `-webkit-mask-composite` `mask-composite`
* [x] `-webkit-mask-image` `mask-image`
* [x] `-webkit-mask-origin` `mask-origin`
* [x] `-webkit-mask-position` `mask-position`
* [x] `-webkit-mask-repeat` `mask-repeat`
* [x] `-webkit-mask-size` `mask-size`
* [x] `-webkit-order` `order`
* [x] `-webkit-perspective` `perspective`
* [x] `-webkit-perspective-origin` `perspective-origin`
* [x] `-webkit-transform-origin` `transform-origin`
* [x] `-webkit-transform-style` `transform-style`
* [x] `-webkit-transform` `transform`
* [x] `-webkit-transition-delay` `transition-delay`
* [x] `-webkit-transition-duration` `transition-duration`
* [x] `-webkit-transition-property` `transition-property`
* [x] `-webkit-transition-timing-function` `transition-timing-function`
* [x] `-webkit-transition` `transition`

**Comment by karlcow** [comment]
For example, in [CSS background](https://github.com/web-platform-tests/wpt/tree/master/css/css-backgrounds), I do not see anything related to `-webkit-`

**Comment by karlcow** [comment]
The second question is answered with https://github.com/web-platform-tests/wpt/tree/master/compat

**Comment by karlcow** [comment]
Let's check what is missing. 

Checking the correlation between the spec and the tests in https://github.com/web-platform-tests/wpt/blob/master/compat/css-style-declaration-alias-enumeration.html

This tests only that the webkit property exists… but not necessary that the right equivalent is associated with. 

| Property | Spec | Test |Comment|
|---------|------|------|----------|
| WebKitBackgroundSize | ❗️  | ✅ | [Issue #28](https://github.com/whatwg/compat/issues/28#issuecomment-1162702793) |
| WebKitBackgroundClip | ✅ | _ | Need to add test for this but taking into account that Chrome is not yet implementing text value without prefix. So we need to surface it. |
| WebKitBoxSizing | ✅ | _ |  has been forgotten in the tests? |



The tests in https://github.com/web-platform-tests/wpt/blob/9be1ef7ed0be09b72868528960317d3f0b1cfaae/compat/css-style-declaration-alias-enumeration.html#L42-L47

are indeed enumerated but the alias name is different. It would be probably be good to double check if the right property is modified.

**Comment by karlcow** [comment]
why `webKitMaskBoxImage` is listed in 

https://github.com/web-platform-tests/wpt/blob/9be1ef7ed0be09b72868528960317d3f0b1cfaae/compat/css-style-declaration-alias-enumeration.html#L42-L47


while https://compat.spec.whatwg.org/#css-simple-aliases gives for aliases `mask-border-*` which is not implemented at all from my preliminary tests.

Probably should open an issue on compat spec.
The addition was done in 2016

* https://github.com/whatwg/compat/issues/14


but 6+ years later, there is still no browser implementing `mask-border` or maybe experimental modes?
https://caniuse.com/mdn-css_properties_mask-border

hmmm no. 
I''ll open a new issue. 

* https://github.com/whatwg/compat/issues/202

**Comment by karlcow** [comment]
`-webkit-box-sizing` was added to the spec by @miketaylr in 2015.
https://github.com/whatwg/compat/issues/9

but no test exists for it on the alias enumeration.
We could add one and I check, this is supported everywhere with both `-webkit-box-sizing` and `box-sizing`

**Comment by Era-Islam** [comment]
> The compat spec has a section called [legacy name aliases](https://compat.spec.whatwg.org/#css-simple-aliases). These are the properties which are necessary to support for a browser to be able to work with the Web.
> 
> * [x] Do we have tests for each of these aliases?
> * [x] Should they be in their own compat section? Or in each thematic individual section?
> * [x] `-webkit-align-items` `align-items`
> * [x] `-webkit-align-content` `align-content`
> * [x] `-webkit-align-self` `align-self`
> * [x] `-webkit-animation-name` `animation-name`
> * [x] `-webkit-animation-duration` `animation-duration`
> * [x] `-webkit-animation-timing-function` `animation-timing-function`
> * [x] `-webkit-animation-iteration-count` `animation-iteration-count`
> * [x] `-webkit-animation-direction` `animation-direction`
> * [x] `-webkit-animation-play-state` `animation-play-state`
> * [x] `-webkit-animation-delay` `animation-delay`
> * [x] `-webkit-animation-fill-mode` `animation-fill-mode`
> * [x] `-webkit-animation` `animation`
> * [x] `-webkit-backface-visibility` `backface-visibility`
> * [x] `-webkit-background-clip` `background-clip`
> * [x] `-webkit-background-origin` `background-origin`
> * [x] `-webkit-border-bottom-left-radius` `border-bottom-left-radius`
> * [x] `-webkit-border-bottom-right-radius` `border-bottom-right-radius`
> * [x] `-webkit-border-top-left-radius` `border-top-left-radius`
> * [x] `-webkit-border-top-right-radius` `border-top-right-radius`
> * [x] `-webkit-border-radius` `border-radius`
> * [x] `-webkit-box-shadow` `box-shadow`
> * [x] `-webkit-box-sizing` `box-sizing`
> * [x] `-webkit-flex` `flex`
> * [x] `-webkit-flex-basis` `flex-basis`
> * [x] `-webkit-flex-direction` `flex-direction`
> * [x] `-webkit-flex-flow` `flex-flow`
> * [x] `-webkit-flex-grow` `flex-grow`
> * [x] `-webkit-flex-shrink` `flex-shrink`
> * [x] `-webkit-flex-wrap` `flex-wrap`
> * [x] `-webkit-filter` `filter`
> * [x] `-webkit-justify-content` `justify-content`
> * [x] `-webkit-mask` `mask`
> * [x] `-webkit-mask-box-image` `mask-border`
> * [x] `-webkit-mask-box-image-outset` `mask-border-outset`
> * [x] `-webkit-mask-box-image-repeat` `mask-border-repeat`
> * [x] `-webkit-mask-box-image-slice` `mask-border-slice`
> * [x] `-webkit-mask-box-image-source` `mask-border-source`
> * [x] `-webkit-mask-box-image-width` `mask-border-width`
> * [x] `-webkit-mask-clip` `mask-clip`
> * [x] `-webkit-mask-composite` `mask-composite`
> * [x] `-webkit-mask-image` `mask-image`
> * [x] `-webkit-mask-origin` `mask-origin`
> * [x] `-webkit-mask-position` `mask-position`
> * [x] `-webkit-mask-repeat` `mask-repeat`
> * [x] `-webkit-mask-size` `mask-size`
> * [x] `-webkit-order` `order`
> * [x] `-webkit-perspective` `perspective`
> * [x] `-webkit-perspective-origin` `perspective-origin`
> * [x] `-webkit-transform-origin` `transform-origin`
> * [x] `-webkit-transform-style` `transform-style`
> * [x] `-webkit-transform` `transform`
> * [x] `-webkit-transition-delay` `transition-delay`
> * [x] `-webkit-transition-duration` `transition-duration`
> * [x] `-webkit-transition-property` `transition-property`
> * [x] `-webkit-transition-timing-function` `transition-timing-function`
> * [x] `-webkit-transition` `transition`
