### ISSUE TITLE
Can we remove the jsshell annotations from the streams tests?

### ISSUE THREAD

**Issue by domenic** [web-platform-tests/wpt#34795]
I believe these were used mainly for Gecko which had a JS-shell-based streams implementation. But this has been removed. @evilpie @saschanaz maybe can confirm?

They make wpt.fyi rather unhelpful because of the bug at https://github.com/web-platform-tests/wpt.fyi/issues/2496 / https://github.com/web-platform-tests/wpt.fyi/issues/1469

**Comment by saschanaz** [comment]
c894f0086c99ab5efc37691ac60f33a2b37c2e7c removed it for readable stream tests but it somehow didn't cover others 👀

I see no reason not to remove them, so 👍 from me.
