### ISSUE TITLE
Azure pipeline error, Install Safari Technology Preview "no download for 10.16"

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#34926]
@foolip , @jcscottiii , @gsnedders , @whimboo 
Dear github admins and colleagues,

I am running again into this error in [PR34925](https://github.com/web-platform-tests/wpt/pull/34925) , just like in [issue 34752](https://github.com/web-platform-tests/wpt/issues/34752)
{
Check failure on line 30 in Build log
@azure-pipelines azure-pipelines / Azure Pipelines
Build log #L30
Bash exited with code '1'.

View raw log

Starting: Install Safari Technology Preview

Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line

Generating script.
 Starting Command Output 
/bin/bash --noprofile --norc /Users/runner/work/_temp/2aebd30f-ed7f-43f3-8a3d-c1f902896ae4.sh
+ ./wpt install --channel preview --download-only -d . --rename STP safari browser
INFO:install:Now installing safari browser...
INFO:install:Finding STP download URLs
INFO:install:Found STP URLs for macOS ==13.*, ~=12.3
Traceback (most recent call last):
  File "/Users/runner/work/1/s/./wpt", line 10, in <module>
    wpt.main()
  File "/Users/runner/work/1/s/tools/wpt/wpt.py", line 220, in main
    rv = script(*args, **kwargs)
  File "/Users/runner/work/1/s/tools/wpt/install.py", line 89, in run
    install(browser, kwargs["component"], destination, channel, logger=logger,
    raise ValueError(f"no download for {system_version}")
ValueError: no download for 10.16
##[error]Bash exited with code '1'.
Finishing: Install Safari Technology Preview
}

**Comment by TalbotG** [comment]
Trying to reach @web-platform-tests/admins , @web-platform-tests/wpt-core-team

**Comment by foolip** [comment]
I don't know exactly what's gone wrong here, but it's related to scraping https://developer.apple.com/safari/resources/ implemented in https://github.com/web-platform-tests/wpt/pull/34553.

**Comment by foolip** [comment]
@gsnedders what would you think of extracting the download URL into a file in the repo to pin it, so that we can keep running tests even when https://developer.apple.com/safari/resources/ changes?

**Comment by gsnedders** [comment]
@TalbotG  what is `echo $SYSTEM_VERSION_COMPAT`?

presumably you have something that is setting this such that macOS is pretending to be `10.16` to avoid breaking applications that assume macOS versions would begin with `10.x` for all eternity


> @gsnedders what would you think of extracting the download URL into a file in the repo to pin it, so that we can keep running tests even when https://developer.apple.com/safari/resources/ changes?

This is unlikely to work (as the outdated STPs cease being available), and regardless we need to know the system version (which is the problem here) to be able to know which URL to download.

**Comment by gsnedders** [comment]
Oh wait, this is Azure Pipelines again. Doh!

**Comment by foolip** [comment]
Hmm, old STP downloads get deleted? In 2021 we had a pinned version for months, so I guess this is new, or they get deleted only after a long time?

**Comment by gsnedders** [comment]
> Hmm, old STP downloads get deleted? In 2021 we had a pinned version for months, so I guess this is new, or they get deleted only after a long time?

It is… not perfectly consistent as to whether it actually happens. 🙃

**Comment by TalbotG** [comment]
Sam Sneddon , Philip Jägenstedt ,

A few min. ago, I have created [PR34943](https://github.com/web-platform-tests/wpt/pull/34943) and things appear to be okay, normal, as expected now.

Thank you for your assistance, your time and this fix.

Gérard
