### ISSUE TITLE
Test for the absence of Document.load

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#3519]

**Comment by kaixinjxq** [comment]
@Ms2ger, there is no `load` attribute in `Document` element ([spec](https://html.spec.whatwg.org/#the-document-object)), can we close the issue now?

**Comment by Ms2ger** [comment]
Exactly, that's why we test for its absence. According to this code, Gecko should fail that test: https://searchfox.org/mozilla-central/rev/a80651653faa78fa4dfbd238d099c2aad1cec304/dom/webidl/XMLDocument.webidl

**Comment by kaixinjxq** [comment]
`Document.load` is no longer existing in spec, so why not fix the issue in Gecko rather to add test to prove it is wrong?

**Comment by Ms2ger** [comment]
![Why not both?](https://user-images.githubusercontent.com/111161/42620819-54e11844-85bc-11e8-968c-2a722fa8ce82.jpg)

**Comment by kaixinjxq** [comment]
As we don't need test for those deprecated features, right?
![image](https://user-images.githubusercontent.com/3191205/42622361-cf81577c-85f2-11e8-90c5-e2ddbd0f88bf.png)

**Comment by Ms2ger** [comment]
I have no time to discuss this further, but yes, we do have a lot of tests that historical features are no longer supported, usually in files called `historical.html`.

**Comment by kaixinjxq** [comment]
Ooh, I didn't realize there is a `historical.html` file, many thanks for your clarification, I will add the tests.
