### ISSUE TITLE
Some css-ui tests incorrectly assume that <input type="search"> looks like <input type="text"> with auto appearance

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/wpt#35333]
@pxlcoder and I were looking into those in the context of Interop 2022:

* css/css-ui/compute-kind-widget-no-fallback-props-001.html
* css/css-ui/compute-kind-widget-fallback-props-revert-001.html

**Comment by nt1m** [comment]
Hit enter too early... oops.

These tests (and potentially more), assume that `<input type="search">` and `<input type="text">` look the same with `appearance: auto` (default). This is the case in Chrome & Firefox, but not Safari.

This is an `<input type="search">`:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1795135/182753204-f6568315-3ce2-4e76-ab97-fab9c9b8bc29.png">

This is an `<input type="text">`:

<img width="205" alt="image" src="https://user-images.githubusercontent.com/1795135/182755028-24dfe06f-9359-474d-a406-cabc57fca039.png">

While I agree we should aim `appearance: textfield` to make both look the same, I do not agree that the default styles should look the same.

@zcorpan What do you think?

**Comment by zcorpan** [comment]
Yeah this was a test bug. Thanks for fixing!
