### ISSUE TITLE
Chrome does not load a japanese font

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#35371]
Dear @web-platform-tests/admins fellow colleagues,

Visit 
[the test results for rbc-rtc-basic-001.html test page](https://wpt.fyi/results/css/css-ruby/rbc-rtc-basic-001.html?label=master&label=experimental&aligned&view=subtest)
click on the Compare link for Chrome 106
and you will notice that no japanese font (or no font capable of rendering japanese characters) is loaded for the test. Now, the test is sufficiently versatile and agile to show if the test is nevertheless passed or not by Chrome, despite the missing of a suitable japanese-capable-font resource. 

The other 3 browsers (Firefox, Safari, Edge) load a japanese font for such test.

Finally, I added 2 labels for this issue. I do not know if they are correct or if other labels should be added or if better ones should replace these 2.

Thank you for your time.

Gérard

**Comment by gsnedders** [comment]
This is, once again, #13203. Someone should really push that issue forward…
