### ISSUE TITLE
[css-color] css-color/color-function-parsing.html is incorrectly assuming color() functions should clamp non-alpha components

### ISSUE THREAD

**Issue by weinig** [web-platform-tests/wpt#35461]
The test css-color/color-function-parsing.html has a few subtests that incorrectly assume that color() functions should clamp non-alpha components. Specifically these four:

```
    testColorFunction("sRGB color with negative component should clamp to 0", "color(srgb -0.25 0.5 0.75)", "color(srgb 0 0.5 0.75)");
    testColorFunction("sRGB color with component > 1 should clamp", "color(srgb 0.25 1.5 0.75)", "color(srgb 0.25 1 0.75)");
    testColorFunction("Display P3 color with negative component should clamp to 0", "color(display-p3 0.5 -199 0.75)", "color(display-p3 0.5 0 0.75)");
    testColorFunction("Display P3 color with component > 1 should clamp", "color(display-p3 184 1.00001 2347329746587)", "color(display-p3 1 1 1)");
```

I believe the spec expects these to be preserved for parsing, and then gamut mapped on use.

**Comment by svgeesus** [comment]
These tests, after the big reorganization, no longer exist and the relevant tests are:

 - [/css/css-color/parsing/color-valid-color-function.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-color-function.html)
 - [/css/css-color/parsing/color-invalid-color-function.html](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-invalid-color-function.html)

The specific test case noted are no longer part of the tests, and there are explicit tests for the **absence** of clamping:

```js
    test_valid_value("color", `color(${colorSpace} 50% -160 160)`, `color(${colorSpace} 0.5 -160 160)`);
    test_valid_value("color", `color(${colorSpace} 50% -200 200)`, `color(${colorSpace} 0.5 -200 200)`);
```

So I think this issue can be closed.
