### ISSUE TITLE
Incorrect usage of `size-adjust` in css/css-fonts/system-ui-* tests

### ISSUE THREAD

**Issue by xiaochengh** [web-platform-tests/wpt#35543]
Per [spec](https://drafts.csswg.org/css-fonts-5/#size-adjust-desc), the `size-adjust` descriptor accepts only a percentage value.

However, the system-ui-* tests set `size-adjust: 0.5` (for example [here](https://github.com/web-platform-tests/wpt/blob/5a8a34738d5bf0e8e86dc581edf44cbf90d483a5/css/css-fonts/system-ui-ar.html#L14)).

I think they should all be changed to `size-adjust: 50%`?

@jfkthame

**Comment by jfkthame** [comment]
Oops -- you're totally right, of course. Please feel free to fix it! I was probably thinking of the `font-size-adjust` property, but that's different.

**Comment by xiaochengh** [comment]
Reopened due to https://github.com/web-platform-tests/wpt/pull/37567#discussion_r1061528681
