### ISSUE TITLE
[Clipboard API] async-navigator-clipboard-basics.https.html uses undefined method getPermission

### ISSUE THREAD

**Issue by EdgarChen** [web-platform-tests/wpt#35600]
See 
- https://github.com/web-platform-tests/wpt/blob/c7b6b577d1acce4df2752e9f666a52d3864bfc53/clipboard-apis/async-navigator-clipboard-basics.https.html#L89
- https://github.com/web-platform-tests/wpt/blob/c7b6b577d1acce4df2752e9f666a52d3864bfc53/clipboard-apis/async-navigator-clipboard-basics.https.html#L97

Tests are from https://bugs.chromium.org/p/chromium/issues/detail?id=1014310.
But the tests fail on Chrome, too, https://wpt.fyi/results/clipboard-apis/async-navigator-clipboard-basics.https.html?label=master&label=experimental&aligned.

Was it just an oversight? @snianu

**Comment by snianu** [comment]
@EdgarChen Ah thanks for reporting! This looks like a copy paste error :( I'll fix it asap, sorry for the inconvenience.

**Comment by EdgarChen** [comment]
Thanks for confirming! I just create a PR to fix this.

**Comment by tuckstarrydell** [comment]
#35628

**Comment by EdgarChen** [comment]
This issue is no longer valid after https://github.com/web-platform-tests/wpt/commit/e1202389f7de82a94db323c659a9ce131e3dee54.
