### ISSUE TITLE
Firefox/Chrome runs not reaching wpt.fyi

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#35625]
cc @past 

We seemingly haven't had a run reach wpt.fyi in ~24h; seemingly GitHub doesn't believe the runs have completed but TC shows them as having done so.

https://www.githubstatus.com/incidents/pmw828sz2w7k & https://www.githubstatus.com/incidents/v7x4r4mplb4t might be related?

**Comment by gsnedders** [comment]
More recently on Azure Pipelines I'm seeing:

`requests.exceptions.HTTPError: 404 Client Error: file(s) not found: testing/profiles for url: https://hg.mozilla.org/mozilla-central/archive/tip.zip/testing/profiles/`

Maybe @whimboo has some idea in @jgraham's absence? (Probably they've just moved?)

**Comment by whimboo** [comment]
@gsnedders do you have a link to such a broken job? I have a hard time to find one. By checking the reported URL from above the profiles archive is still at this location. Nothing has been changed. Maybe there were some network issues? Not sure if I would count these as degraded performance issues as references by the two incidents.

**Comment by gsnedders** [comment]
well that's weird, cos I had that URL return 404 locally too. oh well. seemingly things are back to normal now?

**Comment by whimboo** [comment]
Maybe there was an outage for hg.mozilla.org but I cannot tell this right now. So it's still all working fine? If yes, shall we close this issue?

**Comment by gsnedders** [comment]
TC is still frequently not reporting completion, which is causing https://wpt.fyi/runs to still have lots of gaps in it for Firefox and Chrome.

See, e.g., https://github.com/web-platform-tests/wpt/runs/8018823784 v. https://community-tc.services.mozilla.com/tasks/groups/WEJXB7LESbqFxMeDztEpoQ

**Comment by gsnedders** [comment]
Or, more recently, https://github.com/web-platform-tests/wpt/runs/8038756020 v. https://community-tc.services.mozilla.com/tasks/groups/UpZ7m6gNToyC6VsOYHBWiw

**Comment by whimboo** [comment]
But isn't that then an issue with a GitHub hook or something similar? In the taskcluster job I cannot see any failures, so it would be best to ask someone who actually knows how it's all connected. This is out of my knowledge. Sorry.

**Comment by past** [comment]
@whimboo is there anyone at Mozilla who understands the Community-TC Integration GitHub app and could help investigate?

**Comment by whimboo** [comment]
@jgraham is back and should be able to have a look I assume.

**Comment by jcscottiii** [comment]
Regarding the Github tasks not completing for WPT:
Looks like there is a problem with that particular version of taskcluster.
I put details for the Taskcluster team in this comment:
https://github.com/taskcluster/taskcluster/issues/5653#issuecomment-1234800720

**Comment by lotas** [comment]
Yeah, sorry :) bug was indeed introduced in latest release [44.19.1](https://github.com/taskcluster/taskcluster/releases/tag/v44.19.0).
We are working on a fix in https://github.com/taskcluster/taskcluster/pull/5654

**Comment by jcscottiii** [comment]
@lotas Thank you so much for keeping us updated. We will be monitoring on our side and report back our results. Will close this issue after we have verified.

**Comment by lotas** [comment]
@jcscottiii thanks! Please let us know, maybe there are still some rare conditions where this can happen

**Comment by jcscottiii** [comment]
@lotas 
I see that the new TaskCluster version has been deployed. Starting today, Firefox and Chrome runs are reporting back successfully now. 🎉

https://github.com/web-platform-tests/wpt/commits/master

https://wpt.fyi/runs?label=master&max-count=100&from=2022-08-30T00%3A00&view=subtest

Let's keep this open for the rest of the day. If there are no problems reported by tomorrow, I will close this.

**Comment by jcscottiii** [comment]
@lotas There is one run that seems stuck.
https://github.com/web-platform-tests/wpt/runs/8202440583

But the task is completed: https://community-tc.services.mozilla.com/tasks/NqSkFqu1Q9Cg1Qw6bxdQ2g

**Comment by lotas** [comment]
thanks @jcscottiii I see, yes, this is still happening. 
Interestingly, this task was started within split milliseconds after being created :) which caused another race-condition. Probably worker was about to pick up next task.. Anyways, thanks for this wonderful use case, we are going to figure out how to fix it before next release :)

**Comment by jcscottiii** [comment]
@lotas Thanks for the detailed explanation! Please keep us updated on the progress. Happy to provide any information needed from our side.

**Comment by lotas** [comment]
@jcscottiii took a bit longer to get through the testing and approval, but it was finally released today: https://github.com/taskcluster/taskcluster/releases/tag/v44.21.0
(Released to community already) 
Events are now handled in order and should not overlap each one creating unresolved states in tasks

**Comment by past** [comment]
Things have been stable for over a week now, so I am closing this issue. Thanks for your help!
