### ISSUE TITLE
Should workers be inheriting their CSP from the window?

### ISSUE THREAD

**Issue by codehag** [web-platform-tests/wpt#35641]
In https://github.com/web-platform-tests/wpt/commit/0a8c303a671503c076e49379fd9dda7b671bfcf8 the description of the patch states:

"Dedicated workers should populate their Content Security Policy from parsing their response headers."

However the patch has the following test: https://github.com/web-platform-tests/wpt/blob/master/workers/modules/dedicated-worker-import-csp.html

which has this comment for static imports:   
```
// Append CSP header to windowURL for static import tests since static import
// scripts should obey Window's CSP.
```
This seems contrary to the description of the patch. And I am not sure how it relates to this change in the specification: https://github.com/w3c/webappsec-csp/pull/513

Is this test testing the intended behavior? cc @evilpie

**Comment by evilpie** [comment]
I have been thinking about this more and I think the test is actually correct. I think I had the wrong mental model before.

If we want to block the creation/execution of a worker we have to deliver a Content-Security-Policy to the window that is going to create the worker. e.g. something like this will block all workers.

```
<meta http-equiv="Content-Security-Policy" content="worker-src 'none'">
<script>new Worker("worker.js");</script>
```

So in this case we are definitely following the windows' CSP. 

Now in the case of static imports we can think of those as just a more complex "main script" load that should also follow the CSP of the window.

**Comment by antosart** [comment]
My understanding matches @evilpie's last comment, so I agree the test seems correct to me.

**Comment by smaug----** [comment]
Why would static imports use window's csp, and not csp for the worker? static imports are external resources.
Parent document triggers main script load, but everything else should be controlled by the worker, no?

**Comment by codehag** [comment]
I believe this is resolved by https://github.com/w3c/webappsec-csp/issues/336#issuecomment-1273072329
