### ISSUE TITLE
tests failing with

### ISSUE THREAD

**Issue by fergald** [web-platform-tests/wpt#35721]
All of [these tests](https://wpt.fyi/results/html/browsers/browsing-the-web/remote-context-helper-tests) are failing on all browsers on wpt.fyi with

```
ERROR message: Uncaught SyntaxError: Identifier 'MessageQueue' has already been declared
```

The tests pass fine in chromium's repo and when manually running them on Chrome or Firefox. The error message seems like it might be coming from [testharnessreport.js](https://github.com/web-platform-tests/wpt/blob/7b0ebaccc62b566a1965396e5be7bb2bc06f841f/tools/wptrunner/wptrunner/testharnessreport.js#L1) getting included twice (after been transformed into `let MessageQueue = ...` ?) but I don't know why that would happen.

**Comment by foolip** [comment]
This was fixed in https://github.com/web-platform-tests/wpt/pull/36069, see the description there for why this happened.
