### ISSUE TITLE
order of values in background test

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#35740]
Should we put the `white` on line 38 in the first place.

Rationale:
That would test the serialization of multiple background, and not the [issue about canonical order in serialization](https://github.com/w3c/csswg-drafts/issues/6894) which is being  debated.

https://github.com/web-platform-tests/wpt/blob/1ebef47552fb17ccf8b78cb318cbf7118914e64c/css/css-backgrounds/parsing/background-shorthand-serialization.html#L35-L40

**Comment by karlcow** [comment]
Context: https://wpt.fyi/results/css/css-backgrounds/parsing/background-shorthand-serialization.html?label=experimental&label=master&aligned

**Comment by karlcow** [comment]
Ah maybe it was intentional
if I look at the pull request review
https://phabricator.services.mozilla.com/D155077

@Emilio would it be better to test those two separately? aka the canonical order and the way background is supposed to work.

**Comment by emilio** [comment]
That was done in https://bugzilla.mozilla.org/show_bug.cgi?id=743392, but actually given `<final-bg-layer>` has the `<background-color>` before rather than after (https://drafts.csswg.org/css-backgrounds/#typedef-final-bg-layer) I think WebKit and Blink follow the spec and Gecko is wrong, so we should probably fix Gecko.

**Comment by emilio** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1788582 for this.

**Comment by emilio** [comment]
Actually it's the other way around, Gecko is right. Why testing it separately?

**Comment by emilio** [comment]
I think the order is clear in the spec, but if you disagree please open a spec issue stating the case?

**Comment by karlcow** [comment]
> Actually it's the other way around, Gecko is right. Why testing it separately?

I think the order is right too. 

What I was thinking is isolating tests to make sure to avoid mixing two types of constraints. :) but it's ok as-is too. Just need to improve the serialization of WebKit. Thanks for the comment.
