### ISSUE TITLE
Color parsing rules are out of date

### ISSUE THREAD

**Issue by mirisuzanne** [web-platform-tests/wpt#35802]
CSS Color Level 4 now allows either percentage or number values for most color channels across most color spaces. The exceptions are:

- polar angle hue channels require an angle
- hsl & hwb only accept percentages in their non-hue channels

The tests for this (both `parsing/color-valid` and `parsing/color-invalid`) are currently too strict, requiring percentages for e.g. lch & oklch lightness.

I can try writing a PR for that, but wasn't sure if there are other related changes that need to be made at the same time.

**Comment by svgeesus** [comment]
Thanks for spotting these.

I wrote [`parsing/color-mixed-num-pct.html`](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-mixed-num-pct.html) to test mixtures of number, percentage and `none`.

But you are correct that the assumptions behind [`parsing/color-valid.html`](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid.html) and in particular [`parsing/color-invalid.html`](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-invalid.html) are out of date, a bunch of subtests need to be moved out of invalid to valid.

If you have time to write a PR I would be happy to review it.

These tests are [flagged for Interop2022](https://wpt.fyi/results/css/css-color/parsing?label=experimental&label=master&aligned) so it is important they be up to date.

**Comment by svgeesus** [comment]
In the invalid test, 

https://github.com/web-platform-tests/wpt/blob/a4b2c96c7456f24049376f3427c6775870211540/css/css-color/parsing/color-invalid.html#L49

is valid.

**Comment by mysteryDate** [comment]
Hahah, I JUST did this in chromium. 
https://chromium-review.googlesource.com/c/chromium/src/+/3868988
