### ISSUE TITLE
New release of `wptserve` on PyPI

### ISSUE THREAD

**Issue by salilmishra23** [web-platform-tests/wpt#35978]
The latest version of `wptserve v3.0.0` on PyPI [1] is pinned on `h2 v3.0.1` https://github.com/web-platform-tests/wpt/pull/22412, which is not compatible with Python 3.10, it would be great if a new release of `wptserve` is made.

It is required for `mozdownload` to support Python 3.10 https://github.com/mozilla/mozdownload/pull/623. 

Here is the link to the failing test. [2]

[1] - https://pypi.org/project/wptserve/3.0/
[2] - https://github.com/mozilla/mozdownload/actions/runs/3049402854/jobs/4915434407

**Comment by whimboo** [comment]
With https://github.com/web-platform-tests/wpt/commit/4d5a8894516a008acc73f44cb4ade98297f18d8a the dependency got lifted to a lower bound, which means we basically would only need a new release of the package to PyPI.

@jgraham could you please do such a release? Thanks!

**Comment by whimboo** [comment]
This is now finally blocking the work on mozdownload given that I can no longer make sure to support the latest releases of Python but only the security releases 3.8 and 3.9. I would really appreciate a new release of wptserve with updated dependencies.

**Comment by whimboo** [comment]
The minimal version of h2 that would be necessary is [4.1.0](https://github.com/python-hyper/h2/blob/master/CHANGELOG.rst#410-2021-10-05) which added support for Python 3.9 and 3.10. I assume that 3.11 and 3.12 will still work with this h2 release.

**Comment by whimboo** [comment]
FYI the new version has also been uploaded at https://pypi.org/project/wptserve/4.0/.

**Comment by whimboo** [comment]
> FYI the new version has also been uploaded at https://pypi.org/project/wptserve/4.0/.

We have to remove this version from pypi because it misses an import of `pywebsocket3`, and that package is not yet available on PyPI.

**Comment by whimboo** [comment]
Sadly this is still not done yet. The problem with the not yet released `pywebsocket3` package on PyPI is larger than expected. Now with wptserve 4.0.1 released on PyPI I see the following failure:

```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
wptserve depends on mod_pywebsocket@ https://github.com/GoogleChromeLabs/pywebsocket3/archive/50602a14f1b6da17e0b619833a13addc6ea78bc2.zip#sha256=4dadd116e67af5625606f883e1973178d4121e8a1dc87b096ba2bb43c692f958
```

@jgraham I assume that this means we have to get the Chrome folks to finally release the pywebsocket3 package?

**Comment by jgraham** [comment]
Or we vendor pywebsocket directly into wptserve rather than into wpt.

**Comment by whimboo** [comment]
For now I've created a PR to actually try to get `pywebsocket3` released on PyPI. Lets see if it gets accepted over the next days. I would rather try to use a publicly hosted package as having a submodule in wptserve.

**Comment by whimboo** [comment]
@jgraham the release of pywebsocket3 is done:
https://github.com/GoogleChromeLabs/pywebsocket3/releases/tag/v4.0.0

Sadly it's still not on PyPI and not sure if I'll get a reply for that. I wonder if we should - at least for now - use your proposed solution and vendor into wptserve if that would fix the issue?

**Comment by whimboo** [comment]
https://pypi.org/project/pywebsocket3/4.0.2/ is now available on PyPI! That means we won't have to vendor it as part of wptserve anymore.

@jgraham will you continue with your PR https://github.com/web-platform-tests/wpt/pull/45346/?

**Comment by whimboo** [comment]
I've created https://github.com/web-platform-tests/wpt/pull/45711 to upgrade pywebsocket3 to the latest release on PyPI. Once it's done we could release wptserve.

**Comment by whimboo** [comment]
The version bump for wptserve is done and it's now at 4.0.2. Sadly I do not have permissions to upload the package on PyPI.

@jgraham could you upload or make me a maintainer as well? Thanks.

**Comment by whimboo** [comment]
The new package is now available at https://pypi.org/project/wptserve/4.0.2/.
