### ISSUE TITLE
STP download code keeps breaking

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#36013]
The code to download Safari Technology Preview involves fetching the live https://developer.apple.com/safari/download/ and parsing the response:

https://github.com/web-platform-tests/wpt/blob/b20e8343ce5ff1eada39dc1487b8b28ed903fff6/tools/wpt/browser.py#L1527-L1619

When it breaks, all PRs are affected. This has happened a number of times after https://github.com/web-platform-tests/wpt/pull/34553:

- https://github.com/web-platform-tests/wpt/pull/34771
- https://github.com/web-platform-tests/wpt/issues/34875
- https://github.com/web-platform-tests/wpt/pull/36003

Can we maintain a pinned download URL that is used by default, with an option to get the new one "live"? This is the setup that we're shooting for with Chromium, which @DanielRyanSmith has worked on recently.

cc @web-platform-tests/wpt-core-team

**Comment by gsnedders** [comment]
> Can we maintain a pinned download URL that is used by default, with an option to get the new one "live"? 

As has also happened on several occasions, pinning the URL also didn't work as the old STP download URL was often removed when a new STP shipped.

With regards to fetching them live: having some small amount of difficulty in the short-term as we iterate on this doesn't seem too surprising; the question is whether we'll continue to have these problems longer term.

**Comment by foolip** [comment]
> pinning the URL also didn't work as the old STP download URL was often removed when a new STP shipped

Perhaps Apple could be a bit slower to remove old STP URLs? :)

Another solution to this would be a https://developer.apple.com/safari/technology-preview/something.json that Apple keeps up to date. This would help anyone who's trying to test STP in CI, not just WPT.

**Comment by gsnedders** [comment]
We literally haven't changed this code in nearly two years since https://github.com/web-platform-tests/wpt/pull/36003, so I think it's safe to say that it isn't as fragile as you made it out to be. 🙃 

Three fixups in the first few months after we first implemented the logic doesn't seem too bad, to me?
