### ISSUE TITLE
Compressed file ends unexpectedly and artifacts

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#36441]
To @web-platform-tests/admins , @web-platform-tests/wpt-core-team , @stephenmcgruer , @foolip 

I just created and submitted commit aa67a8b in https://github.com/web-platform-tests/wpt/pull/34811 . I do not understand why a check failed. I have no clue. I do not know why my commit failed. Please help.

Gérard

**Comment by jcscottiii** [comment]
This looks to be a transient error unrelated to this PR: 
```
bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.
```

Going to close and reopen the PR

**Comment by TalbotG** [comment]
@jcscottiii Thank you for you assistance, James. I am closing this issue since all of the contnuous integration check passed on the 34811 PR.

Cheers,
Gérard
