### ISSUE TITLE
font-variant-position-02.html and font-variant-position-03.html are not linked to any reference

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/wpt#36474]
https://github.com/web-platform-tests/wpt/tree/master/css/css-fonts/font-variant-position-02.html
https://github.com/web-platform-tests/wpt/tree/master/css/css-fonts/font-variant-position-02-ref.html
https://github.com/web-platform-tests/wpt/tree/master/css/css-fonts/font-variant-position-03.html
https://github.com/web-platform-tests/wpt/tree/master/css/css-fonts/font-variant-position-03-ref.html

These files exist but the test files are not linked with their reference.

@svgeesus can you please take a look? I'm not sure if you intentionally omitted the `<link rel=match>` given the complex description of what a test pass is in the paragraphs you wrote, but if that is the case, maybe the refs should be deleted and that test should either be a `-manual.html` test or a `rel=mismatch` test.

**Comment by svgeesus** [comment]
Right I remember these. I thought I could do a reftest, then realized possible passes were more complex.

I don't think `rel=mismatch` adequately covers it, will try with a couple of alternate references before giving up and renaming to `-manual`
