### ISSUE TITLE
Does the exit fullscreen actually consume user activation?

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#36481]
@mustaqahmed, in the user activation tests, there is the following util function that varies tests rely on:

https://github.com/web-platform-tests/wpt/blob/3768c854713937f4aa572ca4513ecaaa57236cae/html/user-activation/resources/utils.js#L25-L33

However, in the fullscreen spec, I don't see where it says "[consume user activation](https://html.spec.whatwg.org/#consume-user-activation)"? 

My understanding is that fullscreen doesn't consume user activation, it just requires it. 

cc @annevk

**Comment by marcoscaceres** [comment]
I'm thinking we might need to add something to Web Driver to consume user activation. Otherwise, we are going to be relying on APIs like Payment Request to consume it, which is not great.

**Comment by annevk** [comment]
There's discussion about this in https://github.com/whatwg/fullscreen/issues/152 that's unresolved. It does seem like Chrome has this, but there are special cases for Pointer Lock and perhaps other APIs?

**Comment by mustaqahmed** [comment]
Adding a WebDriver API for consumption is a great suggestion, thanks!  Otherwise, testing consumption is a big challenge.  All browsers consume user activation at `window.open()` but popup blocker assumptions interfere.  The only remaining option we have is `requestFullscreen()` but we don't have interop there!

**Comment by marcoscaceres** [comment]
Closing based on progress we made on https://github.com/whatwg/fullscreen/issues/152
