### ISSUE TITLE
Centralize garbage collection

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#36926]
Patch https://github.com/web-platform-tests/wpt/commit/b181b1cf64799f29527a4a0a1d5a2bfadb69c5d1 made a few improvements to how tests do garbage collection.  

@saschanaz suggested we centralize that somewhere... 

@domenic wrote 
Approving since this is a strict improvement, but some suggestions:

- Copy the more informative comments from streams/
- Use the self.garbageCollect = () => { } format since it makes it clearer that it's adding a global.
- Consolidate these all into /common/gc.js
- Fix the [others](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt%20%22function%20garbageCollect%22&type=code) found in permissions/ and fs/, and [the ones](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt+%22function+runGarbageCollection%22&type=code) found in webusb/ and bluetooth/, and finally [the one found in js/builtins](https://github.com/web-platform-tests/wpt/blob/0802d8bd01e17178d9cd2355e6fbaf3c098e7953/js/builtins/weakrefs/resources/maybe-garbage-collect.js#L13).
- Fix [various cases that aren't using this, to use this](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt+%22https%3A%2F%2Fgithub.com%2Fweb-platform-tests%2Fwpt%2Fissues%2F7899%29%22&type=code)

**Comment by gsnedders** [comment]
It would be good to reference ttps://github.com/web-platform-tests/wpt/issues/7899 here, given that's the… original issue about triggering GC?
