### ISSUE TITLE
Can we add CODEOWNERS?

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#36941]
Over on the WebKit repo, we are using CODEOWNERS file to allow individuals to monitoring certain directories: https://github.com/WebKit/WebKit/blob/main/.github/CODEOWNERS

Could we use the same mechanism here for some of the larger nested directories (e.g., in html/)? For instance, I'm interested in watching only some of the html/ directories - or can META.yml handle that too? 

Or, maybe CODEOWNERS could do away with META.yml entirely?

**Comment by gsnedders** [comment]
At least before it was the case that CODEOWNERS meant one of the people in the file _had_ to be the person to review, rather than needing some approved reviewer. And as soon as we put the export bots into the CODEOWNERS it feels like we've significantly lessened the benefit of that?

**Comment by marcoscaceres** [comment]
Sorry, I'm not following "we put the export bots into the CODEOWNERS"? My use case is just to follow some directories. I don't mind reviewing code there too.
