### ISSUE TITLE
Grant write access to makotokato

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#36976]
@sideshowbarker, could you please grant write access to @makotokato? 

@makotokato, also, would you be interested in being a reviewer for any particular set of specs? (e.g., screen orientation)

**Comment by makotokato** [comment]
> would you be interested in being a reviewer for any particular set of specs? (e.g., screen orientation)

I am turning on screen orientation again in Gecko, Yes.

**Comment by sideshowbarker** [comment]
Howdy Kato-san — you should now have an invitation waiting
