### ISSUE TITLE
Test for non-UTF-8 code point expects a non-standard percent-encoding

### ISSUE THREAD

**Issue by Gallaecio** [web-platform-tests/wpt#37010]
The test case below, introduced [here](https://github.com/web-platform-tests/wpt/commit/4e15edcc3ca51c72c3846133c7b175ecd94b3a9b), expects the U+D800 code point in the path and query to be percent-encoded as `%EF%BF%BD`, which is the percent-encoded UTF-8 representation of the replacement character, U+FFFD.

https://github.com/web-platform-tests/wpt/blob/9ba6aa59702548b87e99f6dc609734fb84ab9552/url/resources/urltestdata.json#L4668-L4682

However, I believe the URL living standard [expects %26%2355296%3B](https://url.spec.whatwg.org/#ref-for-ascii-digit), i.e. `&#55296;`, where 55296 is the base-10 representation of D800. The standard explicitly asks to use “encode or fail”, which uses the “fatal” error mode, rather than the “replace” error mode.

Is it a problem in the standard? (the replacement character seems more URL-friendly than `&#NNN;`, which only seems good for HTML) Is the expectation of the test case wrong? Or am I missing something?

**Comment by gsnedders** [comment]
cc @annevk @achristensen07?

**Comment by annevk** [comment]
You found a problem that I did not realize was there. The URL Standard doesn't explicitly say that it expects a scalar value string as parser input. The idea being that before you invoke the parser, you have already replaced lone surrogates (such as the U+D800 here) with U+FFFD.

All callers of the URL parser do account for that, but its signature should also be explicit about it. I'll create a PR.

Thanks @Gallaecio and thanks @gsnedders for looping me in.

**Comment by annevk** [comment]
@Gallaecio there's a PR up at https://github.com/whatwg/url/pull/719 now. It acknowledges you. Let me know if you have any thoughts.
