### ISSUE TITLE
Test expectation for Timeout tests does not work well

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#37260]
This is a copy to chomium crbug https://bugs.chromium.org/p/chromium/issues/detail?id=1394804.

The way we are using test expectations makes it difficult to specify test expectation for tests that randomly timeout.

If a test timeouts at subtest A, all the subtests running after A should all get a Timeout and Notrun expectation, as we only have one timeout value for the whole test.

For a test that would Timeout, can we ignore the timeout at subtest level, and simply say it runs as expected when it timeouts?

**Comment by jgraham** [comment]
That only works if the tests run in serial, which isn't the case. If we have tests A and B where A is intermittent pass/timeout and B always passes if run then B always running after A means the possible outcomes are A=PASS, B=PASS, test=OK or A=TIMEOUT, B=NOTRUN, test=TIMEOUT. But if A and B run in parallel then we can get A=TIMEOUT, B=PASS, test=TIMEOUT.

I don't think we have enough information to tell what situation we're in; although `promise_test` provides upfront registration of tests and ordering, you can also use `async_test` for tests running in parallel or with a strict ordering (by defining the next test in a completion callback for the current test). If we had this information for some subset of tests we don't currently have an easy way to pass it back to the harness.

**Comment by WeizhongX** [comment]
Thanks. I did not realize sub tests could run in parallel. I am trying to set up a chromium builder to run WPTs with wptrunner, and find it difficult to set up correct expectations for such tests, because there could be many different combinations.

So maybe the easiest way is to fix such test, or disable it before it is fixed. jgraham@, what would be the best practice in your opinion?

**Comment by WeizhongX** [comment]
@jgraham, some update on this: I made a change in #37364 to make any result against an expected NOTRUN an unexpected pass. I think we are good now.

Let me know if you have any thoughts on this. Or we can close this issue.
