### ISSUE TITLE
Remove or update `has-error-recovery` ?

### ISSUE THREAD

**Issue by romainmenke** [web-platform-tests/wpt#37421]
https://github.com/web-platform-tests/wpt/blob/6699aa7554add6df9c9fc23de808772a19dcfa34/css/selectors/has-error-recovery.html#L2-L4

@tabatkins This test was intended to verify that `:has()` takes a forgiving selector list and was created in parallel to existing tests for `:is()` and `:where()`/

Is it better to remove this test completely or to change it?

I saw that you already updated some tests so I think there are already some checks that `:has()` isn't forgiving.
https://github.com/w3c/csswg-drafts/issues/7676#issuecomment-1341347244

**Comment by tabatkins** [comment]
Ah indeed, I missed this one when I was doing a quick scan for :has() tests. Deleting now, thanks for the catch.

**Comment by romainmenke** [comment]
Thank you for doing all the edits 🙇
