### ISSUE TITLE
URL: setter test question

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#37555]
@TimothyGu @domenic I don't understand this `host` setter test:
```json
        {
            "comment": "Leading / is not stripped",
            "href": "sc://example.com/",
            "new_value": "///bad.com",
            "expected": {
                "href": "sc:///",
                "host": "",
                "hostname": ""
            }
        }
```
When I look at https://url.spec.whatwg.org/#host-state given `/` and not special I think we end up returning failure in step 3.4 which is before the host is modified. Why does this expect the host to end up as the empty string?

**Comment by domenic** [comment]
Step 3.3 performs the host parser given the empty string. That quickly goes into opaque-host parsing the empty string. Which itself returns the empty string. There's no failure here.
