### ISSUE TITLE
change to compare array instead of _assertSame

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#37922]
https://github.com/web-platform-tests/wpt/blob/7a0b0c285b91a0b1fa08da58c964b82e5cf40733/html/canvas/element/pixel-manipulation/2d.imageData.object.ctor.array.html#L28

This

```
_assertSame(imgdata.data, array, "imgdata.data", "array");
```

which ends up doing 

`imgdata.data === array`

but if the array has been created I a new object during the project, the test will fail. 
It fortunately pass on Chrome and Firefox, but fails in Safari, while 

`imgdata.data.toString() === array.toString()` works everywhere.

This should probably use `assert_array_equals`

**Comment by karlcow** [comment]
@Ms2ger what do you think?

**Comment by Ms2ger** [comment]
I don't understand the question. As far as I can tell, the spec requires that the exact same object is stored, so the test is correctly catching a bug in Safari.

**Comment by karlcow** [comment]
hmm… I'm reading this a bit differently.
https://html.spec.whatwg.org/multipage/canvas.html#initialize-an-imagedata-object

> To initialize an ImageData object imageData, given a positive integer number of rows rows, a positive integer number of pixels per row pixelsPerRow, an optional [ImageDataSettings](https://html.spec.whatwg.org/multipage/canvas.html#imagedatasettings) settings, an optional [Uint8ClampedArray](https://webidl.spec.whatwg.org/#idl-Uint8ClampedArray) source, and an optional [PredefinedColorSpace](https://html.spec.whatwg.org/multipage/canvas.html#predefinedcolorspace) defaultColorSpace:
>  
> 1. If source was given, then initialize the data attribute of imageData to source.
> 2. Otherwise (source was not given), initialize the [data](https://html.spec.whatwg.org/multipage/canvas.html#dom-imagedata-data) attribute of imageData to a new [Uint8ClampedArray](https://webidl.spec.whatwg.org/#idl-Uint8ClampedArray) object. The [Uint8ClampedArray](https://webidl.spec.whatwg.org/#idl-Uint8ClampedArray) object must use a new [Canvas Pixel ArrayBuffer](https://html.spec.whatwg.org/multipage/canvas.html#canvas-pixel-arraybuffer) for its storage, and must have a zero start offset and a length equal to the length of its storage, in bytes. The [Canvas Pixel ArrayBuffer](https://html.spec.whatwg.org/multipage/canvas.html#canvas-pixel-arraybuffer) must have the correct size to store rows × pixelsPerRow pixels.
>  
> If the [Canvas Pixel ArrayBuffer](https://html.spec.whatwg.org/multipage/canvas.html#canvas-pixel-arraybuffer) cannot be allocated, then rethrow the [RangeError](https://tc39.es/ecma262/#sec-native-error-types-used-in-this-standard-rangeerror) thrown by JavaScript, and return.

**Comment by Ms2ger** [comment]
> If source was given, then initialize the data attribute of imageData to source.

What's there to read differently?

**Comment by karlcow** [comment]
@Ms2ger Understood. I think the point is so explicit about it. 

> initialize the [data](https://html.spec.whatwg.org/multipage/canvas.html#dom-imagedata-data) attribute of imageData to a **new** [Uint8ClampedArray](https://webidl.spec.whatwg.org/#idl-Uint8ClampedArray) object.

That the first sentence didn't register to me as something where you **MUST NOT instantiate a new** [Uint8ClampedArray](https://webidl.spec.whatwg.org/#idl-Uint8ClampedArray) object.

Thanks for the clarification.
