### ISSUE TITLE
Pass an config specified in command line to wpt server

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#38075]
"wpt serve" currently accepts a parameter '--config'. But such option is not available if we run tests with 'wpt run'. 

In environment.py the current implementation would read overriding configs from config.json under the test root (see link below). We recently see a need to use different configs for different browsers, e.g. content shell v.s. chrome, so have such capability will be desired.

https://github.com/web-platform-tests/wpt/blob/8a99353217938b6f1da31a9a108da3d501cee58b/tools/wptrunner/wptrunner/environment.py#L177

**Comment by WeizhongX** [comment]
@jgraham, what would be your option on this? (I do agree we already get many parameters.)

**Comment by jgraham** [comment]
This seems likely to be OK, but afaik no one is using the override at the moment, so you should check if it actually solves your problems first.

**Comment by WeizhongX** [comment]
Thanks for the comment. I will close this issue for now. we will send over a PR for review if we decide to go that route.
