### ISSUE TITLE
webtransport_h3_server.py seems to return a malformed response

### ISSUE THREAD

**Issue by KershawChang** [web-platform-tests/wpt#38134]
Looking at the code [here](https://github.com/web-platform-tests/wpt/blob/f393fff3bd84a30092eb0e1017dd2f6ec76e806e/tools/webtransport/h3/webtransport_h3_server.py#L226), the response headers would be like:
```
{"server", "webtransport-h3-server"},
{"sec-webtransport-http3-draft", "draft02"},
{":status", "200" }
```
The above response is malformed according to the spec [here](https://www.rfc-editor.org/rfc/rfc9114.html#section-4.1.2-2.4): `pseudo-header fields after fields`.

We might want to insert `:status` to the front of the list, not append.

**Comment by bashi** [comment]
Good point. I'll send a PR to fix it.

**Comment by bashi** [comment]
Just noticed that f223ceb7ee02bfe4d21acf43dbc6a18d1e16cd10 fixed it.
