### ISSUE TITLE
Wpt report does not have expected field

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#38180]
From the code at line below, seems we should have "expected" fields in wpt report. But we did not see that in the wpt report generated at our side. Is there a bug or we should pass in additional parameters (does not seem to be the case)?

https://github.com/web-platform-tests/wpt/blob/6eb3a6aac07796553699bc4eab0e5d503f2291b5/tools/wptrunner/wptrunner/metadata.py#L445

**Comment by WeizhongX** [comment]
@jgraham can you pls advise?

@jonathan-j-lee

**Comment by jonathan-j-lee** [comment]
That's actually WAI as a optimization. Absence of `"expected"` implies an expected result (i.e., `test["expected"] == test["status"]`).

**Comment by WeizhongX** [comment]
I had been looking at a regressed test. I tried again and see that this time. Will monitor this.
