### ISSUE TITLE
/usr/bin/env: « python »: No file or directory of such type

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#38244]
@foolip , @jcscottiii , @gsnedders , @whimboo

Dear github admins and colleagues,

A few min., I tried to run lint on a committed test and I failed: 

```
web-platform-tests/css/css-values$ ../../wpt lint   
/usr/bin/env: « python »: No file or directory of such type

```

I have no idea how to fix this.

Please advise.

**Comment by TalbotG** [comment]
Okay. Please ignore this issue. I created another pull request and was able to trigger the lint function checks. So things are back to normal for me.

Cheers, 
Gérard

**Comment by foolip** [comment]
@TalbotG the error you were seeing suggests you don't have Python installed, or not in your PATH. If it happens again I'd suggest checking if just running `python` works. If it doesn't, you'll need to install Python 3 and make sure there's a `python` binary in your PATH.

**Comment by TalbotG** [comment]
@foolip 

Thank you Philip for replying to my issue.

1-
According to my package manager, I have python3 package installed.

I can also report:

```
/usr/bin$ ls pytho* -ahls
3,5M -rwxr-xr-x 1 root root 3,5M 14 jui  2021 python2.7
   0 lrwxrwxrwx 1 root root    9  5 avr  2021 python3 -> python3.9
5,3M -rwxr-xr-x 1 root root 5,3M 28 fév  2021 python3.9
   0 lrwxrwxrwx 1 root root   33 28 fév  2021 python3.9-config -> x86_64-linux-gnu-python3.9-config
   0 lrwxrwxrwx 1 root root   16  5 avr  2021 python3-config -> python3.9-config
4,0K -rwxr-xr-x 1 root root  960 23 déc  2020 python3-futurize
4,0K -rwxr-xr-x 1 root root  964 23 déc  2020 python3-pasteurize

```

2-
I have an `env` file in my `/usr/bin/ `folder:
```
/usr/bin$ ls env -ahls
48K -rwxr-xr-x 1 root root 48K 24 sep  2020 env
```

3-
My path is:
```
$ echo $PATH
/home/gerard/.local/bin:/home/gerard/.local/bin:/usr/local/bin:/usr/bin:/bin:usr/local/games:/usr/games
```

I see that `/usr/bin` is in my $PATH.

I tried to run lint on a **very old** (March 31st 2019) committed test (see [Pull Request 16168](https://github.com/web-platform-tests/wpt/pull/16168)). When I created another pull request (see [Pull Request 38245](https://github.com/web-platform-tests/wpt/pull/38245)), the lint function checks were triggered.

Again, thank you for looking at my issue.

Gérard
