### ISSUE TITLE
webnn/resources/test_data/reshape.json uses invalid -1 value

### ISSUE THREAD

**Issue by huningxin** [web-platform-tests/wpt#38272]
The WebNN reshape spec is updated to use `null` to indicate the dimension that needs to be calculated: https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reshape

However the WPT reshape test case still use old `-1` for that purpose which is outdated and invalid. e.g., https://github.com/web-platform-tests/wpt/blob/master/webnn/resources/test_data/reshape.json#L372

Please help fix that.

@BruceDai @Honry

**Comment by BruceDai** [comment]
Thanks @huningxin, I've submitted #38273 to fix it. PTAL, thanks.
