### ISSUE TITLE
webnn/conv2d.https.any.js should add conv2d filter as constant operand

### ISSUE THREAD

**Issue by huningxin** [web-platform-tests/wpt#38274]
The existing conv2d test cases only define conv2d filter as input operand. 

However, neural networks usually define the filter of conv2d operator as constant operand. And some implementation may only support constant filter operand.

With that, it would be helpful for implementers that add test cases that define conv2d filter as constant operand.

/cc @BruceDai @Honry

**Comment by BruceDai** [comment]
Thanks @huningxin. I will add such tests.
