### ISSUE TITLE
Test form data set with multiple submit buttons

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#3829]
From https://github.com/whatwg/html/issues/1821

html/semantics/forms/form-submission-0/ is probably the right place to put/extend tests.

Something like http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4517

Also file a bug against Edge.

cc @davidMuir

**Comment by zcorpan** [comment]
@kaixinjxq can you also file a bug against Edge?

**Comment by kaixinjxq** [comment]
The new bug https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/18707189/
