### ISSUE TITLE
[border-image-slice] If border-image-slice area is too wide or too tall, where begins the painting: left side (Firefox) or centre (Chrome)?

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#38588]
Please load this test

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-repeat-789-GT.html

in Firefox 110+ and in Chrome 110+.

The middle edge of the square is 2em wide or 2em tall. But the border-image that has been sliced can only fit one half of it. The question now becomes from which area should the slicing be done. Firefox starts from the top side and from left side. Chromium starts from the middle area. I think the specification is not utterly clear about this. 

Both implementations are possible ... albeit I think Firefox's implementation makes more sense, seems more logical and meeting better a web author's expectations.

1 other test (please load it in Firefox and in Chrome) highlighting the difference in implementation:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-repeat-456-GT.html

Finally, this test

http://wpt.live/css/css-backgrounds/css3-border-image-repeat-repeat.html

must be revisited and re-evaluated once this issue has been resolved.

**Comment by fantasai** [comment]
This is specified in https://www.w3.org/TR/css-backgrounds-3/#border-image-process

**Comment by TalbotG** [comment]
[CSS3 Backgrounds, § 5.6 Drawing the Border Image, parg 3.](https://www.w3.org/TR/css-backgrounds-3/#border-image-process) states:
"
Position the first tile.

   If the first keyword is repeat, the top, middle, and bottom 
images are centered horizontally in their respective areas.
"
