### ISSUE TITLE
[border-image-slice] 'fill' keyword and preserving middle part of border-image

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#38586]
The [border-image-slice section of CSS3 Backgrounds](https://www.w3.org/TR/css-backgrounds-3/#border-image-slice) states:
"
fill
    The fill keyword, if present, causes the middle part of the border-image to be preserved. (By default it is discarded, i.e., treated as empty.) 
"

What if the middle part of border-image is larger and taller than the content box of the element? There is no border-image-origin property or border-image-position property. Here is a test demonstrating that Firefox 112 and Chromium 110 differ:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-fill-special-GT.html

Chromium version 110.0.5481.77 chooses the vertical middle and the horizontal center of the middle part of the border-image. Epiphany 3.38.2 (using WebKitGTK 2.38.5) also chooses the vertical middle and the horizontal middle of the middle part of the border-image.

Firefox version 102.8.0esr and Firefox version 112.0a1 buildID=20230219095859 on the other hand choose the top+left area of the middle part of the border-image.

Both implementations are possible; none of them are intrinsically wrong or incorrect since the specification does not specify how (from which side or from which area) to start painting the middle part of the border image.

**Comment by fantasai** [comment]
This is specified in https://www.w3.org/TR/css-backgrounds-3/#border-image-repeat

Where it discusses tiling of the “middle” this refers not just to the edge pieces, but also the middle piece.

**Comment by TalbotG** [comment]
[CSS3 Backgrounds, § 5.5 Image Tiling: the border-image-repeat property](https://www.w3.org/TR/css-backgrounds-3/#border-image-repeat) states
"
The first keyword applies to the horizontal scaling and tiling of the top, middle and bottom parts, the second to the vertical scaling and tiling of the left, middle and right parts (...)
If the second keyword [regarding border-image-repeat] is absent, it is assumed to be the same as the first.
"

[CSS3 Backgrounds, § 5.6 Drawing the Border Image, parg 3](https://www.w3.org/TR/css-backgrounds-3/#border-image-process) states:
"
Position the first tile. 
If the first keyword is repeat, the top, middle, and bottom images are centered horizontally in their respective areas. (...)
If the second keyword is repeat, the left, middle, and right images are centered vertically in their respective areas.
"

**Comment by TalbotG** [comment]
I have been working on these 3 new tests related to this Issue which I hope to be able to submit very soon:

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-fill-001.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-fill-002.html

http://www.gtalbot.org/BrowserBugsSection/CSS3Backgrounds/border-image-slice-fill-003.html
