### ISSUE TITLE
Consider moving WebDriver HTTP wpt tests to “webdriver/tests/http”

### ISSUE THREAD

**Issue by whimboo** [web-platform-tests/wpt#38768]
Right now we have the WebDriver HTTP tests located under [`webdriver/tests`](https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/) and the ones for WebDriver BiDi under [`webdriver/tests/bidi`](https://github.com/web-platform-tests/wpt/tree/master/webdriver/tests/bidi/). This feels like BiDi is a subset of WebDriver. Given that both are different protocols I would suggest to also separate the tests.

* WebDriver HTTP: `webdriver/tests/http`
* WebDriver BiDi: `webdriver/tests/bidi`

This would also help with better fixture organization and interop tests using both protocols (eg window and element handles) could be at `webdriver/tests/http_bidi` or similar.

I'll add this as a discussion item for the next monthly meeting. But already CC'ing @sadym-chromium, @foolip, @jimevans, @patrickangle, @lutien, @juliandescottes, @jgraham.

**Comment by gsnedders** [comment]
"http" and "bidi" seem a bit odd—"http" and "websocket" would be logical equivalences here

the other option is moving "webdriver/tests/bidi" to "webdriver-bidi", though that means changing things in `tools` to pick up the Python files as tests and not support files

**Comment by whimboo** [comment]
Another option would be to use `classic` for the WebDriver HTTP tests. Then we have it unbundled from the underlying protocol in use.

I would avoid using completely different folders if possible so that we can share fixtures and more easily create interop tests between the two protocols as well. But maybe that would be doable with your suggestion as well. Lets discuss that in next weeks monthly meeting.

**Comment by sadym-chromium** [comment]
LGTM
* webdriver/tests/classic
* webdriver/tests/bidi

**Comment by whimboo** [comment]
This topic has been discussed yesterday in the monthly browser tools and testing WG meeting:
https://www.w3.org/2023/03/08-webdriver-minutes.html#t02

```
whimboo: this is not for the spec but for where we store the wpt tests
… and since we started tests for webdriver-bidi it was added as a subfolder
… so do we want to move the "classic" tests to a new subdirectory

automatedtester: why not have a new highlevel dir?

whimboo: there are some tests that are shared between like window handles etc and not sure how easy that will be to share them

jgraham: I don't have opinion on moving it. One technical issue is that we have 150 char limit on path lengths which is enforced by wpt
… about the TLD it would require a lot of work to get things working
… and it's a issue with the wpt module setup so would not like to touch this if it purely for aesthetics.

whimboo: for the path lengths... I don't think that this is going to be an issue because of the way we are structuring these things. It's more "http" vs "classic"

gsnedders: I have an opinion

simonstewart: I think that v1 would be better than classic

jgraham: I am against v1
… and it becomes very confusing as we are working on it

simonstewart: I think that http would be better

whimboo: http can cause confusion and I think classic would be better
```

Even it is not clear from those notes we finally agreed on `classic`.

I'll have a look over the next days in how we actually can get this done. There are probably some site-effects that we have to take into account as well.
