### ISSUE TITLE
WPT test references don't follow counter-style suffix/prefix fallback specification

### ISSUE THREAD

**Issue by vitorroriz** [web-platform-tests/wpt#38772]
Counter styles specification says at https://www.w3.org/TR/css-counter-styles-3/#counter-styles:

> Note: [prefix](https://www.w3.org/TR/css-counter-styles-3/#descdef-counter-style-prefix) and [suffix](https://www.w3.org/TR/css-counter-styles-3/#descdef-counter-style-suffix) don’t play a part in this algorithm. This is intentional; the prefix and suffix aren’t part of the string returned by the counter() or counters() functions. Instead, the prefix and suffix are added by the algorithm that constructs the value of the [content](https://www.w3.org/TR/css-content-3/#propdef-content) property for the [::marker](https://www.w3.org/TR/css-pseudo-4/#selectordef-marker) pseudo-element. **This also implies that the prefix and suffix always come from the specified counter-style, even if the actual representation is constructed by a fallback style**.

However, some related WPT tests (below) expects that the suffix and prefix come from the fallback style:
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/suffix-fallback.html
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/system-additive.html
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/system-alphabetic.html
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/system-extends.html
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/system-symbolic.html 
imported/w3c/web-platform-tests/css/css-counter-styles/counter-style-at-rule/fallback-cycle.html

I probably also need to issue a spec bug asking for this note to appear in the suffix/prefix section, since it just appears at the beginning of specification.

@jfkthame you might be interested on this issue since you were discussing it here https://github.com/web-platform-tests/wpt/commit/90a953f4c4f0235160e96c8dd27d4a5e7638511d

**Comment by jfkthame** [comment]
That's interesting ... and I think is a questionable feature.

See the Gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1808995 for an example where the reporter expected (quite reasonably, IMO) that the suffix should be taken from the fallback counter-style that is actually used to generate the representation. Not doing this seems unexpected/illogical, IMO.

**Comment by nt1m** [comment]
Given https://github.com/web-platform-tests/wpt/pull/39863, I'm closing this.
