### ISSUE TITLE
Support FAIL as expected result for Testharness test

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#39225]
The idea is that Testharness test should not produce a "FAIL" result, but can have "FAIL" expectation, which mean any subtest failure will be treated as expected.

This feature will be useful for ppl unfamiliar with the system (i.e. sheriffs) to easily suppress the failure. It would then be feature team's responsibility to update the metadata file to a more accurate format, and fix the failures later.

We previously support this through tag "blink_expect_any_subtest_status" in PR 20217. Could this be something generally supported in wptrunner?

**Comment by WeizhongX** [comment]
@jgraham I would like to know what is your opinions on this? Could you shed some light on how the sheriff is done in gecko CI?

**Comment by WeizhongX** [comment]
Another thing is that we can not have 'expected: Fail' in __dir__.ini. If all the tests can have Fail as expected results, we can also support this in __dir__.ini. 

Doing that will allow developers to specify all tests under a folder will fail.

**Comment by WeizhongX** [comment]
@foolip @jonathan-j-lee

**Comment by jonathan-j-lee** [comment]
web-platform-tests/wpt#37037 has some discussion on why inheriting `expected` from `__dir__.ini` doesn't work. (And given how large some test directories are, I think we could accidentally lose a ton of coverage that way, especially for newly imported tests under a directory.)

**Comment by WeizhongX** [comment]
Discussed offline, and also record that here.

Per the discussion in #37037 , seems jgramham@ supports the idea to add test expectations to __dir__.ini, just that such expectations should not apply to sub tests, which I totally agree.

As for "accidentally lose a ton of coverage that way", test expectations already worked this way. So it is really devs/reviewers' responsibility to keep it right.

**Comment by WeizhongX** [comment]
Looks I missed one point discussed in #37037. `PASS` is not a valid result for test harness test either, but probably we do not need to use `PASS` in `__dir__.ini`.

(Or is it possible we consolidate "OK" and "PASS" to "OKPASS", so all the tests at test level have same set of valid test expectations.)

**Comment by WeizhongX** [comment]
I will close this as not needed. We find a different solution to this problem.
