### ISSUE TITLE
WebTransport available in Firefox Nightly 113

### ISSUE THREAD

**Issue by jan-ivar** [web-platform-tests/wpt#39309]
WebTransport is now [enabled in Nightly-only builds](https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#12527,12529) as of Firefox 113. 🎉

But https://wpt.fyi/results/webtransport?label=experimental&label=master&aligned showing SKIP for Firefox, not green.

When I _"Run in your browser on wpt.live"_ e.g. https://wpt.live/webtransport/connect.https.any.html in Chrome, the tests run immediately (3 pass, 4 fail since there's no server when invoked this way). But in Firefox the tests never run, the page stalls for a few seconds and then times out.

Looks like some infrastructure needs updating.

**Comment by gsnedders** [comment]
FWIW: with @jgraham out, I'm landing https://github.com/web-platform-tests/wpt/pull/39345 as that just updates the metadata to match what the browser now does with no other changes, thus unblocking infrastructure PRs.

We probably want to land something close to @bashi's #39322 to actually start running the WebTransport server, but I'll leave that for Mozilla people to figure out what to do with all that.

**Comment by jesup** [comment]
This is great - I've been running the webtransport tests locally and passing almost all the WPTs in nightly for some time.  Thanks!
