### ISSUE TITLE
No STP builds on wpt.fyi

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#39402]
This appears to be showing up in the [processor](https://wpt.fyi/status) as:

> Conflicting 'version: [OS X 12.6.3, OS X 12.6.4], os_build: [21G419, 21G526]' found in the merged report

Not really anything we can do about Azure Pipelines vending us inconsistent VMs, alas.

**Comment by past** [comment]
I see builds now on Apr 7, 9 and 10. Maybe it was a transient issue?
