### ISSUE TITLE
ERROR:lint:service-workers/service-worker/

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#39443]
@foolip , @jcscottiii , @gsnedders , @whimboo

Dear github admins and colleagues,

A few min. ago, I submitted [Pull Request 39442](https://github.com/web-platform-tests/wpt/pull/39442) and the Continuous Integration checks state that lint checking fails. I get this 

"
./wpt lint --all --github-checks-text-file=/home/test/artifacts/checkrun.md
ERROR:lint:service-workers/service-worker/postMessage-client-worker.js:15: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/controlled-iframe-postMessage.https.html:38: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/controlled-iframe-postMessage.https.html:47: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/controlled-iframe-postMessage.https.html:56: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-worker-late-postMessage.js:1: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-worker-late-postMessage.js:4: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-worker-postMessage.js:2: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-frame-postMessage.html:16: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-frame-postMessage.html:21: setTimeout used (SET TIMEOUT)
ERROR:lint:service-workers/service-worker/resources/controlled-frame-postMessage.html:29: setTimeout used (SET TIMEOUT)
"

which makes no sense to me as I do not use any `setTimeout()` in my code.

Please advise.

Thank you,

Gérard

**Comment by TalbotG** [comment]
I now also get the same error message in [Pull Request 39444](https://github.com/web-platform-tests/wpt/pull/39444)

**Comment by jcscottiii** [comment]
@jonathan-j-lee can you verify again?
I reverted PR #39449 that caused the problem.

**Comment by jonathan-j-lee** [comment]
Thanks James! I'm waiting for the autoroller to create and submit a new CL without the problematic tests. Should take a few hours, but don't foresee any issues. I'll close this issue then.

**Comment by jonathan-j-lee** [comment]
[Import succeeded](https://chromium-review.googlesource.com/c/chromium/src/+/4412197), resolved.

**Comment by TalbotG** [comment]
@jcscottiii , @jonathan-j-lee ,
Jonathan, James,
What am I supposed to do now with #39442, #39444 and #39445 ? I just tried to re-run the lint checks and no improvements happen. I do get an email stating

* method:     rerunTask
* errorCode:  InsufficientScopes
* statusCode: 403
* time:       2023-04-10T21:05:13.088Z

Please advise.

Gérard

**Comment by jonathan-j-lee** [comment]
You should be able to rerun all checks by closing and reopening the PR. Unfortunately, the "Re-run" button, to my knowledge, has never worked; I will file an issue for this, if it doesn't exist already.

**Comment by TalbotG** [comment]
Jonathan,

I have close #39442 and I reopened it. Indeed, the Continuous Integration checks are reactivated ... [in progress]

> the "Re-run" button, to my knowledge, has never worked

Jesus!?!? ... why?? Please add my name to the issue for this.

Thank you for your time and your quick reply,

Gérard

**Comment by TalbotG** [comment]
> Jonathan,
> 
> I have closed #39442 , #39444 and #39445 and I reopened these. Indeed, the Continuous Integration checks are reactivated ... [in progress]

lint Successful in 3m — Community-TC (pull_request) 
and
All checks have passed
19 successful checks
in #39442 ! :)

**Comment by TalbotG** [comment]
Thank you, James, for your diligence and for your time. :)

Thank you, Jonathan, for your time and support. :)
