### ISSUE TITLE
What should computed role return for elements not in the a11y tree?

### ISSUE THREAD

**Issue by jcsteh** [web-platform-tests/wpt#39637]
Spun off https://github.com/web-platform-tests/wpt/pull/38941#pullrequestreview-1393145314.

https://github.com/web-platform-tests/wpt/blob/25cd6eb086db5977ac51f7dee7faafe6772dc9d7/wai-aria/role/synonym-roles.html#L16-L17

These tests (and perhaps others) set role=none/presentation and expect that the computed role will be "none". role="none" excludes the element from the a11y tree, so we can't get the computed role from the a11y engine. This raises the question: what are the expectations for computed role for nodes which aren't in the a11y tree?

Gecko currently returns null, but I can change that to anything: "", "none", whatever. However, it seems to me that there is a subtle difference between role="none" (one very specific way of removing an element from the a11y tree) vs the non-existence of an element in the a11y tree for one of several reasons (role="none", hidden, aria-hidden, ...). Could "none" lead people to think that this is specifically about role="none", when in reality, aria-hidden will return "none" as well?

That said, I don't want to bikeshed too much here. If WebKit and Chromium are happy with "none" for all cases of a11y non-existence, I can just change Gecko's WebDriver implementation to return "none" and move on. Nevertheless, I thought it'd be good to make a clear, documented decision here.

**Comment by cookiecrook** [comment]
This should move over to AOM (already), BTT, or some other W3C or WHATWG group with an IP Policy... Work like this doesn't happen in WPT. Alternatively I'm tracking this in AOM under this comment: https://github.com/WICG/aom/issues/197#issuecomment-1515783376 Once we have a plan in the incubator, we plan to take the requests to BTT.

**Comment by cookiecrook** [comment]
I suggest closing this WPT issue.

**Comment by jcsteh** [comment]
My apologies. I'm very new to WPT work.

**Comment by cookiecrook** [comment]
No apologies necessary.
