### ISSUE TITLE
 wptrunner should report skipped tests when interrupted

### ISSUE THREAD

**Issue by dev-ansung** [web-platform-tests/wpt#39950]
Currently, when wptrunner is interrupted by a terminal signal or keyboard interrupt, the remaining test results are lost. This can make it difficult to determine which tests were executed and which were skipped.

I propose that wptrunner should gather the remaining tests that were skipped and report them as "unexpectedly skipped" instead. This would allow developers to have a more accurate understanding of the test results and to determine the ratio of test cases executed prior to the runner failing.

Steps to Reproduce:
1. Run wptrunner with a test suite that contains a large number of tests.
2. Interrupt wptrunner with a terminal signal or keyboard interrupt.
3. Observe that the remaining test results are lost.

Expected Behavior:
* wptrunner should gather the remaining tests that were skipped and report them as "unexpectedly skipped".

Actual Behavior:
* The remaining test results are lost.

**Comment by foolip** [comment]
I see, so this is a feature in Chromium's `run_web_tests.py`, and you're looking for feature parity with wptrunner?

Is this important when running in CI, or only locally?

**Comment by WeizhongX** [comment]
It probably is not very useful when running locally. Developers should already know that when s/he interrupted the run. 

On the CI, it could help a little bit, but there are other ways to see a run is interrupted due to timeout for example.

**Comment by jonathan-j-lee** [comment]
https://crrev.com/c/4786911 implements this in Chromium's CI when the wrapper dynamically detects it's wired to Chromium's ResultDB. This keeps exiting local runs fast.
