### ISSUE TITLE
resources/ tests failing in Firefox

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#40013]
cc @jgraham @whimboo 

see e.g. https://community-tc.services.mozilla.com/tasks/a_atPhmLQxuvWEYzyaMQog/runs/0/logs/public/logs/live.log

```
E   webdriver.error.JavascriptErrorException: javascript error (500): Cyclic object value
E   
E   Remote-end stacktrace:
E   
E   RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
E   WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:183:5
E   JavaScriptError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:362:5
E   cloneObject@chrome://remote/content/marionette/json.sys.mjs:43:11
E   cloneJSON@chrome://remote/content/marionette/json.sys.mjs:193:12
E   cloneObject@chrome://remote/content/marionette/json.sys.mjs:58:30
```

**Comment by whimboo** [comment]
@gsnedders how do I exactly run those tests locally? It would be good to know what those tests are trying to return. As it looks like these are cyclic objects which WebDriver classic doesn't support.

**Comment by jgraham** [comment]
Run `tox` in `resources/test` (you may need to install tox from pypi first if you don't already have it).
