### ISSUE TITLE
No Edge runs since May 25 (requests not found)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#40300]
https://wpt.fyi/results/?run_id=4897960914059264 is the most recent Edge run of any configuration right now.

https://github.com/web-platform-tests/wpt/runs/13756307300 is the first run where Edge Dev started to fail. That's the very commit when https://github.com/web-platform-tests/wpt/pull/40130 was landed, so this must be a regression from that.

**Comment by foolip** [comment]
I tried a revert in https://github.com/web-platform-tests/wpt/pull/40303 but am afraid landing it will break more things. @jgraham I'm leaving this with you.

**Comment by jgraham** [comment]
This should now be fixed.
