### ISSUE TITLE
Do not restart browser when test type changes

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#40337]
Is it possible we do not restart browser when test type changes? This seems to be an implementation limit inside Wptrunner, and is not related with the goal of reducing flakiness.

This does not have a big performance impact previously as we do not have many test types, and we are running the same type of tests altogether before switching to a different type. This will not be the case once we support subsuite. A subsuite could have much less tests, so a restart caused by test type switch will be comparatively more costly.

**Comment by gsnedders** [comment]
It's not necessarily the case that all test types can be run interchangeably; `wdspec` tests run differently in Firefox, for example.

**Comment by WeizhongX** [comment]
Thanks! Maybe my question is what particular difference for `wdspec` tests makes it mandatory to restart the browser? I see `MarionetteWdspecExecutor` is using some different args. Is that the reason?

If that is the reason, it is still true whether to restart browser should not be based on test types, but args or prefs.

**Comment by WeizhongX** [comment]
Do you think if it will be ok if I add a new state to `_RunnerManagerState` called "reset"? Unlike a restarting state, it will not cause the browser or webdriver process be killed and restarted. Instead it will only kill the TestRunner and restart it with a different executor class/parameters. (Ideally there is no need to restart TestRunner either. The TestRunner should have a copy of all the supported executors, and pick the right one when running the tests. But I'd like to leave this to next step, assume restarting TestRunner will be cheap enough.)

Each browser implementation should provide a function telling if the browser instance can be reused upon a test type change.

@jgraham @foolip

**Comment by gsnedders** [comment]
I think I'd rather we don't add a new state; I'd rather we just added a new method to the browser like `needs_restart(self, old_test_type, new_test_type)`?

**Comment by WeizhongX** [comment]
This is fixed, close as completed.
