### ISSUE TITLE
Variants are not chunked

### ISSUE THREAD

**Issue by sagudev** [web-platform-tests/wpt#40384]
In [webgpu-cts](https://github.com/gpuweb/cts) there is only one file generated `cts.https.html`, that has all of ~1700 test variants. All of those test are not chunk-able. In Firefox this limitation is bypassed by [manually chunking `cts.https.html`](https://github.com/mozilla/gecko-dev/tree/master/testing/web-platform/mozilla/tests/webgpu/chunked).

**Comment by jonathan-j-lee** [comment]
Sounds like #40020 solves your use case?

**Comment by sagudev** [comment]
It's working.

Thank you.
