### ISSUE TITLE
Python 3.7 builds are failing on Mac

### ISSUE THREAD

**Issue by jcscottiii** [web-platform-tests/wpt#40525]
Related issues: https://github.com/actions/setup-python/issues/682

Something has happened recently with the version of python used by Azure pipelines. Azure updated to the patch version from 3.7.16 [1] to  3.7.17 [2]

[1] https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=101806&view=logs&j=cd4b0752-91ac-5ee3-1416-93dd445ec171&t=e044ee91-f3ba-5f12-7f7f-236b337ef538
[2] https://dev.azure.com/web-platform-tests/wpt/_build/results?buildId=102343&view=logs&jobId=cd4b0752-91ac-5ee3-1416-93dd445ec171&j=cd4b0752-91ac-5ee3-1416-93dd445ec171&t=e044ee91-f3ba-5f12-7f7f-236b337ef538

I wonder if one potential temporary workaround would be to pin the patch version to 3.7.16 in the [Azure pipeline](https://github.com/web-platform-tests/wpt/blob/5c82311872435e2239f41d66b9ce76c1bb512e14/.azure-pipelines.yml#L253) and the [GitHub Actions](https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt%20setup-python&type=code) YAMLs

Docs:
- https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-python-version-v0?view=azure-pipelines
- https://github.com/actions/setup-python

Log Message: `E   ModuleNotFoundError: No module named '_bz2'`

<details>
  <summary>Detailed Logs</summary>

```
Traceback:
../../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ci/tests/test_jobs.py:3: in <module>
    from tools.ci import jobs
ci/jobs.py:6: in <module>
    from ..wpt.testfiles import branch_point, files_changed
wpt/testfiles.py:11: in <module>
    from ..manifest import manifest
manifest/__init__.py:1: in <module>
    from . import item, manifest, sourcefile, update  # noqa: F401
manifest/update.py:9: in <module>
    from .download import download_from_github
manifest/download.py:2: in <module>
    import bz2
../../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/bz2.py:19: in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
E   ModuleNotFoundError: No module named '_bz2'
________________ ERROR collecting lint/tests/test_file_lints.py ________________
ImportError while importing test module '/Users/runner/work/1/s/tools/lint/tests/test_file_lints.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../../hostedtoolcache/Python/3.7.17/x64/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
lint/__init__.py:1: in <module>
    from . import lint  # noqa: F401

```

</details>

**Comment by gsnedders** [comment]
Apparently this is now fixed, but we need to make sure we don't have a bad cache: https://github.com/actions/setup-python/issues/682#issuecomment-1604319803

**Comment by past** [comment]
This has been resolved a while ago.

**Comment by gsnedders** [comment]
It hasn't fully, see e.g.:

https://github.com/web-platform-tests/wpt/blob/46476776fdbf0a62522621002ba8af68e4d478b6/.azure-pipelines.yml#L144-L145

We need to stop pinning the version.

**Comment by past** [comment]
@mustjab do you know if this issue has been resolved and whether we can now remove the pinning?

**Comment by mustjab** [comment]
Yes, it appears to have been resolved. Could you try schedule a run and let me know if it's not working for you?

**Comment by past** [comment]
Pin removed in #43382.
