### ISSUE TITLE
border-image-00{2/3/4}.html reference non-existent support images

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/wpt#40740]
@TalbotG can you please take a look?

These appear to be failing because of 404 references.

**Comment by nt1m** [comment]
https://wpt.fyi/results/css/css-backgrounds?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=not%20label%3Ainterop-2023-cssborderimage%20border-image

**Comment by TalbotG** [comment]
@ntim Tim,

First of all, thank you for notifying me about this issue.
Yes, I am aware of the missing images. 4 days ago, I created [Pull Request 40678](https://github.com/web-platform-tests/wpt/pull/40678) . If you can review and approve #40678, we can fix all this.
