### ISSUE TITLE
Print reftest documentation doesn't match reality?

### ISSUE THREAD

**Issue by mstensho** [web-platform-tests/wpt#40788]
I was looking into changing Chromium to behave as described in https://web-platform-tests.org/writing-tests/print-reftests.html when it comes to the page size - which means a default page size of 5 by 3 inches.

Chromium currently uses a page area size of 4 by 2 inches for WPT print reftests, assuming that there's a 0.5 inch margin on every side of a page box  with the size of 5 by 3 inches [1]. The WPT print reftest documentation says nothing about page margins, so I would think that we should simply use a 5 by 3 inch page area size. That said, there are quite a few existing WPT tests that go @page { size: 5in 3in; margin: 0.5in; }, so the hardcoded defaults in Chromium seemed like a reasonable quirk, as long as Chromium doesn't honor @page rules when running WPT print reftests. But that's precisely what I'm working on fixing, so I thought it would be a good time to start using 5x3.

However, then infrastructure/reftest/reftest_match-print.html would start failing, since that test is assuming a page area height 2 inches (192 CSS pixels). Since this test is also passing in Gecko, it has to mean that Gecko is also operating with a page area height of 2 inches, and not 3 inches, which is what the WPT documentation says.

What to do?

A: Fix Gecko and Chromium, and update the test
B: Fix https://web-platform-tests.org/writing-tests/print-reftests.html

[1] https://source.chromium.org/chromium/chromium/src/+/main:content/web_test/renderer/test_runner.cc;l=107-108;drc=dcee6b77444693128fa284cb3b33a8fbbbbbd6b2

**Comment by gsnedders** [comment]
cc @jgraham

**Comment by jwatt** [comment]
@mstensho 

> However, then infrastructure/reftest/reftest_match-print.html would start failing, since that test is assuming a page area height 2 inches (192 CSS pixels). Since this test is also passing in Gecko, it has to mean that Gecko is also operating with a page area height of 2 inches, and not 3 inches, which is what the WPT documentation says.

We're acting with a default of `@page { size: 5in 3in; margin: 0.5in; }` - so a page box of 5x3in and a page area of 4x2in. We defaulted to the 0.5in margin since that was in [the RFC](https://github.com/web-platform-tests/rfcs/blob/master/rfcs/print_test.md) I believe. (I'm going to move more from that RFC to the actual docs.)

So maybe best to just keep using the 0.5in margin in your test runner and close this issue?

**Comment by mstensho** [comment]
Thank you for confirming that Firefox uses 0.5in margins for WPT reftests. We'll now do this in Chromium as well:

https://chromium-review.googlesource.com/c/chromium/src/+/5067421

This issue should remain open as long as the documentation doesn't mention margins though, shouldn't it?

**Comment by jwatt** [comment]
> This issue should remain open as long as the documentation doesn't mention margins though, shouldn't it?

Yes. 89468ad6da3e653e72bb114e64ccdd0c736b541b updated the docs, and [the live docs](https://web-platform-tests.org/writing-tests/print-reftests.html) now reflect this change, so I think this can be closed now.

**Comment by mstensho** [comment]
Excellent! Yes, let's close this. Thank you!
