### ISSUE TITLE
`webdriver/tests/bidi/browsing_context/print /margin.py`: `test_margin_same_as_page_dimension` implementation is problematic with Chromium

### ISSUE THREAD

**Issue by thiagowfx** [web-platform-tests/wpt#40870]
The following test (https://github.com/web-platform-tests/wpt/blob/d6d5ddd2fc0c6ca545c74850ab84d5901c46c6b9/webdriver/tests/bidi/browsing_context/print/margin.py#L4):

```python
@pytest.mark.parametrize(
    "margin",
    [
        {"top": 27.94},
        {"left": 21.59},
        {"right": 21.59},
        {"bottom": 27.94},
        {"top": 27.94, "left": 21.59, "right": 21.59, "bottom": 27.94},
    ],
    ids=[
        "top",
        "left",
        "right",
        "bottom",
        "all",
    ],
)
async def test_margin_same_as_page_dimension(
    bidi_session,
    top_context,
    inline,
    assert_pdf_content,
    margin,
):
    page = inline("Text")
    await bidi_session.browsing_context.navigate(
        context=top_context["context"], url=page, wait="complete"
    )
    print_value = await bidi_session.browsing_context.print(
        context=top_context["context"],
        shrink_to_fit=False,
        margin=margin,
    )

    # Check that content is out of page dimensions.
    await assert_pdf_content(print_value, [{"type": "string", "value": ""}])
```

...tries to assert that setting the margin the same as the page dimension produces an empty PDF. This works on Firefox, but it does not work on Chromium.

On Chromium, it throws `webdriver.bidi.error.UnknownErrorException: unknown error (invalid print parameters: content area is empty)`, which is technically correct. Chromium cannot handle printing an empty content area.

This condition does not seem to be enforced by the Classic spec in any way (c.f. https://w3c.github.io/webdriver/#print-page), suggesting it's just an arbitrary test. BiDi mostly mirrors the classic spec for `print`.

Can we rewrite this test so that it does not try to generate a PDF for a 0x0 page? I mean, what is the utility of doing so anyway?

**Comment by thiagowfx** [comment]
Pingback https://github.com/web-platform-tests/wpt/commit/f9cd002c7c8a63d23c08c7916aefcbf4c50995a8

CC @whimboo @lutien

**Comment by thiagowfx** [comment]
Another possibility is to update the spec to throw `InvalidArgument` whenever the content area is empty.

**Comment by whimboo** [comment]
As per spec the test is valid and as I have already responded on the PR you probably want to mark the test as expected fail. Feel free to create WebDriver related issues to get it discussed if creating a PDF with 0x0 pixels should be allowed or not. Technically the PDF "spec" seems to allow it.

**Comment by thiagowfx** [comment]
Filed https://github.com/w3c/webdriver-bidi/issues/473.

I am going to close this to avoid fragmented discussions. Please redirect comments to the bidi repo.
