### ISSUE TITLE
WebGitGTK runs missing since May 31

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#40901]
We haven't had any [successful runs of WebKitGTK](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk) in the last month or so. CC @clopez since I haven't had the time to investigate yet.

**Comment by clopez** [comment]
Sorry for taking so much on this one.

I proposed a fix on the WebKit bugzilla, hopefully that will fix the problem with the runs here once it lands: https://bugs.webkit.org/show_bug.cgi?id=260496

**Comment by clopez** [comment]
The fix on the way of generating the binary bundles fixed the main issue on the CI.

But there is another recent issue related with the wpt tooling that is causing a `TypeError` python fatal error. I just submited a PR to fix that one at https://github.com/web-platform-tests/wpt/pull/41723
