### ISSUE TITLE
Chromium nightly daily runs are broken

### ISSUE THREAD

**Issue by dbaron** [web-platform-tests/wpt#41016]
#33863 previously reported that the Chromium nightly daily runs were broken.  This was supposed to be fixed by #34638.  However, if I look at [some nightly results](https://wpt.fyi/results/css/css-transforms?label=master&label=nightly) the Chromium results are still stuck in March of 2022.

cc @foolip @DanielRyanSmith

**Comment by DanielRyanSmith** [comment]
It's likely that this is caused as a side-effect of "Chrome nightly" being renamed to "Chromium nightly" in the daily runs. [The Chromium tests](https://github.com/web-platform-tests/wpt/runs/15926946926) are running as expected, but are not processed by wpt.fyi, as they are no longer "Chrome" test runs anymore. I'll work on making sure the results are ingested. 🙂  Sorry for the delay!

**Comment by dbaron** [comment]
Should they be showing up in views like https://wpt.fyi/results/css/css-transforms?label=master&label=nightly ?  That still appears to have the March 2022 data.

**Comment by past** [comment]
You have to add the Chromium product to see the new data.  Is that workable David?

**Comment by dbaron** [comment]
I guess that's workable, although it would be nice if chromium  were in the default product set for nightly...

It would be good if the Chrome data from over a year ago didn't show up, though.

**Comment by foolip** [comment]
It looks like the default products are currently hard coded and always the same:

https://github.com/web-platform-tests/wpt.fyi/blob/daba80eed49389539aad49362c114ffeb47c5ff0/shared/browsers.go#L9-L13

To make https://wpt.fyi/results/css/css-transforms?label=master&label=nightly use a different product set would be a matter of changing that code, and making it depend on the requested labels.

**Comment by past** [comment]
We have a Q4 goal of switching to Chrome Canary for Testing for automated runs, which should also fix the issue of the default product set for nightly not showing recent results.
