### ISSUE TITLE
[css-color-5] Relative color mix tests assume ranges for color keywords are mapped

### ISSUE THREAD

**Issue by mysteryDate** [web-platform-tests/wpt#41113]
The block of tests here:

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-relative-color.html#L420

Assume that passing and `alpha` of 1 into the lightness channel of an `lab` color would result in full lightness, which is a value of 100. The assumption being made here is that an inputs to relative colors should be normalized to their ranges. 

Currently I see nothing in the spec stating that this is the case:
https://csswg.sesse.net/css-color-5/#relative-colors
https://csswg.sesse.net/css-color-5/#relative-Lab

Also, the tests in question only test passing alpha values into the lightness channel for lab/oklab/lch/oklch directly. Assuming the underlying behavior is truly in place there are many, many untested cases:

Should this then get a lightness value of 50?
`lab(from magenta calc(alpha / 2) a b)` 

Hue is in the range [0, 360] degrees, so the following color should have a hue of 180?
`lch(from magenta l c calc(alpha / 2)`

Seeing as the spec is mum on this, I don't think these tests should exist. Or, we should not expect for inputs to be scaled to their ranges, i.e.:

`lab(from white alpha a b)` will result in almost black (lightness is 1%)
and
`lab(from white calc(alpha * 100) a b)` will actually give white

**Comment by svgeesus** [comment]
[close?](https://github.com/w3c/csswg-drafts/issues/9094#issuecomment-1781939812)

**Comment by mysteryDate** [comment]
Yes, both issues can be closed. The tests have been updated.
