### ISSUE TITLE
[css-color-5] Relative color tests assume gamut mapping that is no longer in spec

### ISSUE THREAD

**Issue by mysteryDate** [web-platform-tests/wpt#41115]
https://github.com/w3c/csswg-drafts/issues/8444#issuecomment-1542537362

> The CSS Working Group just discussed `[css-color-4] Allow out-of-gamut HSL/HWB colors (previously "Move gamut mapping to a future spec")`, and agreed to the following:
> 
> * `RESOLVED: Make color-mix() and RCS using rgb, hsl and hwb return round-trippable, unbounded results in color(srgb ...)`
> 
> The full IRC log of that discussion

These tests should thus not return gamut-mapped rgb, but the "round-trippable, unbounded results in color(srgb ...)" mentioned above:

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html#L38

**Comment by svgeesus** [comment]
So, I'm no longer seeing any tests with gamut-mapped results and also, I am seeing [round-tripping tests with out-of-gamut results](https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-relative-color.html#L590) so it seems this is all dealt with now and the issue can be closed?
