### ISSUE TITLE
deadline-max-rAF.html assumes UA to start an idle period even if there is a pending frame

### ISSUE THREAD

**Issue by rniwa** [web-platform-tests/wpt#41393]
[requestidlecallback/deadline-max-rAF.html](https://github.com/web-platform-tests/wpt/blob/master/requestidlecallback/deadline-max-rAF.html) asserts that the deadline is less than 16ms when there is a rAF scheduled prior to scheduling idle callback.

But this isn't necessarily true because UA can choose to delay idle callback until after the next rAF.

**Comment by rniwa** [comment]
Hm... now that I'm reading the spec more carefully, this might outright violate the spec. [In the spec](https://html.spec.whatwg.org/multipage/webappapis.html#window-event-loop), sub-steps of step 8 run only if `hasARenderingOpportunity` is false, meaning that it's a requirement for idle callbacks that no document associated with the event loop have a *rendering opportunity* when an idle period is started.

**Comment by noamr** [comment]
> Hm... now that I'm reading the spec more carefully, this might outright violate the spec. [In the spec](https://html.spec.whatwg.org/multipage/webappapis.html#window-event-loop), sub-steps of step 8 run only if `hasARenderingOpportunity` is false, meaning that it's a requirement for idle callbacks that no document associated with the event loop have a *rendering opportunity* when an idle period is started.

I don't understand, how does this violate the spec? If you have a scheduled rAF you wouldn't have a rendering opportunity for 16ms (if in a 60fps environment). Between scheduling the rAF and the next rendering opportunity there is plenty of time for very fast idle callbacks.

**Comment by noamr** [comment]
> [requestidlecallback/deadline-max-rAF.html](https://github.com/web-platform-tests/wpt/blob/master/requestidlecallback/deadline-max-rAF.html) asserts that the deadline is less than 16ms when there is a rAF scheduled prior to scheduling idle callback.
> 
> 
> 
> But this isn't necessarily true because UA can choose to delay idle callback until after the next rAF.

Delaying the idle callback until after the next rAF would be a different interpretation of the spec. I suggest to change the spec and the test to say this explicitly rather than rely on the clause that allows implementations to delay those callbacks for performance/power saving reasons. This is an incompatible observable behavior, not exactly an implementation specific optimization.

Btw do you mean "after the next rAF" or "after there are no more scheduled rAFs"? The former is legit. The latter is very likely to break existing web pages. rIB is very commonly used as a polyfill for setImmediate, so in pages where there is a continuous cycle of rAF this would delay the rIB callbacks indefinitely, causing incompatible behavior.

**Comment by noamr** [comment]
Think of this scenario, that demonstrates a real non-public project I've worked on a little over a year ago:

```js

let active = false;

// This function should take about 1ms, but is called many many times.
function updateModelFromLiveData(deadline) { ... }
function renderModelToView() { ... }
async function animationLoop() {
  while (active) {
    await new Promise(resolve => requestAnimationFrame(resolve));
    renderModelToView();
  }
}

async function modelUpdateLoop() {
  while (active) {
    const deadline = await new Promise(resolve => requestIdleCallback(resolve));
    updateModelFromLiveData(deadline);
  }
}

function start() {
  active = true;
  renderLoop();
  modelUpdateLoop();
}
```

This would be completely broken if a UA ships rIB with the behavior of deferring idle callback until after rAF callbacks.

**Comment by othermaciej** [comment]
If the spec allows multiple different behaviors, it’s wrong for a WPT test to assert only one of them.

**Comment by noamr** [comment]
> If the spec allows multiple different behaviors, it’s wrong for a WPT test to assert only one of them.

In that spirit we shouldn't have any WPT for `setTimeout`, because the spec allows deferring them indefinitely. Also the spec allows the UA to never have a rendering opportunity, yet WPTs test that content is rendered.

Back to this case, the spec allows delaying the idle callbacks in an implementation defined way for power saving/performance optimizations, not indefinitely as a consistent behavior when there is a continuous cycle of animation frames (if this is what webkit is going to ship, as I understand it). If it needs to be reworded to clarify that we can do so.

In any case, removing or changing this WPT is not the issue - it would make it look like all browsers are 100% "green" on the feature while obfuscating an interoperability bug that might break multiple pages out of the millions that use `requestIdleCallback` (or might not if we're all exceptionally lucky).

**Comment by rniwa** [comment]
> Think of this scenario, that demonstrates a real non-public project I've worked on a little over a year ago:
> 
> ```js
> let active = false;
> 
> // This function should take about 1ms, but is called many many times.
> function updateModelFromLiveData(deadline) { ... }
> function renderModelToView() { ... }
> async function renderLoop() {
>   while (active) {
>     await new Promise(resolve => requestAnimationFrame(resolve));
>     renderModelToView();
>   }
> }
> 
> async function modelUpdateLoop() {
>   while (active) {
>     const deadline = await new Promise(resolve => requestIdleCallback(resolve));
>     updateModelFromLiveData(deadline);
>   }
> }
> 
> function start() {
>   active = true;
>   renderLoop();
>   modelUpdateLoop();
> }
> ```
> 
> This would be completely broken if a UA ships rIB with the behavior of deferring idle callback until after rAF callbacks.

If that's the motivating use case, then we should be testing exactly that. Something like this (this uses WebKit's test.js but you get the point:
```js
didRanIdleCallback = false;
requestIdleCallback((deadline) => {
    window.deadline = deadline;
    shouldBeTrue('deadline.timeRemaining() <= 17');
    didRanIdleCallback = true;
});

let rafCount = 0;
function runRAF() {
    if (++rafCount <= 20)
        requestAnimationFrame(runRAF);
    else {
        shouldBeTrue('didRanIdleCallback');
        finishJSTest();
    }
}
runRAF();
```

**Comment by noamr** [comment]
> > Think of this scenario, that demonstrates a real non-public project I've worked on a little over a year ago:
> 
> > 
> 
> > ```js
> 
> > let active = false;
> 
> > 
> 
> > // This function should take about 1ms, but is called many many times.
> 
> > function updateModelFromLiveData(deadline) { ... }
> 
> > function renderModelToView() { ... }
> 
> > async function renderLoop() {
> 
> >   while (active) {
> 
> >     await new Promise(resolve => requestAnimationFrame(resolve));
> 
> >     renderModelToView();
> 
> >   }
> 
> > }
> 
> > 
> 
> > async function modelUpdateLoop() {
> 
> >   while (active) {
> 
> >     const deadline = await new Promise(resolve => requestIdleCallback(resolve));
> 
> >     updateModelFromLiveData(deadline);
> 
> >   }
> 
> > }
> 
> > 
> 
> > function start() {
> 
> >   active = true;
> 
> >   renderLoop();
> 
> >   modelUpdateLoop();
> 
> > }
> 
> > ```
> 
> > 
> 
> > This would be completely broken if a UA ships rIB with the behavior of deferring idle callback until after rAF callbacks.
> 
> 
> 
> If that's the motivating use case, then we should be testing exactly that. Something like this (this uses WebKit's `js-test.js` but you get the point:
> 
> ```js
> 
> didRanIdleCallback = false;
> 
> requestIdleCallback((deadline) => {
> 
>     window.deadline = deadline;
> 
>     shouldBeTrue('deadline.timeRemaining() <= 17');
> 
>     didRanIdleCallback = true;
> 
> });
> 
> 
> 
> let rafCount = 0;
> 
> function runRAF() {
> 
>     if (++rafCount <= 20)
> 
>         requestAnimationFrame(runRAF);
> 
>     else {
> 
>         shouldBeTrue('didRanIdleCallback');
> 
>         finishJSTest();
> 
>     }
> 
> }
> 
> runRAF();
> 
> ```

Does WebKit pass this? Seems reasonable to me. Want to submit a PR that changes the WPT to test in this way?
/cc @yoavweiss

**Comment by rniwa** [comment]
> Does WebKit pass this? Seems reasonable to me. Want to submit a PR that changes the WPT to test in this way?
/cc @yoavweiss

It doesn't right now but I can make it pass this case. The current test, not so much.

**Comment by noamr** [comment]
> > Does WebKit pass this? Seems reasonable to me. Want to submit a PR that changes the WPT to test in this way?
> > /cc @yoavweiss
> 
> It doesn't right now but I can make it pass this case. The current test, not so much.

Great. Would be happy to review a PR that changes this test.

Note that there's still a compat risk here if webkit heavily throttles rIB when there are rAFs happening. It would be spec compliant but I can't guarantee it won't break or slow down some pages (in the same way slowing down timeouts by x2 would be spec compliant and might break/slow down pages).
