### ISSUE TITLE
[Question] wai-aria/role/listbox-roles.html test

### ISSUE THREAD

**Issue by hs85jeong** [web-platform-tests/wpt#41577]
Hello @cookiecrook and @howard-e 

I'm preparing a [commit](https://chromium-review.googlesource.com/c/chromium/src/+/4790548) to fix the [test](https://wpt.fyi/results/wai-aria/role/listbox-roles.html?label=experimental&label=master&aligned
) that is failing on chromium.

If you can check the [ARIA Spec](https://w3c.github.io/aria/#option), there is no text related to the **User Agent** regarding the case where the option is orphaned.
Could you check the reason why this test was added and where it is specified?
I can apply the changes only when this is confirmed.

Thank you.

**Comment by cookiecrook** [comment]
Can you move (or refile) to the [ARIA spec issue tracker](https://github.com/w3c/aria/issues/)?

**Comment by hs85jeong** [comment]
> Can you move (or refile) to the [ARIA spec issue tracker](https://github.com/w3c/aria/issues/)?

Okay. I will close this issue and move it to the [ARIA spec issue tracker](https://github.com/w3c/aria/issues/)
