### ISSUE TITLE
webcodecs/videoFrame-serialization.crossAgentCluster.https.html is testing that transferring VideoFrames out of cluster is not working

### ISSUE THREAD

**Issue by youennf** [web-platform-tests/wpt#41635]
There are two tests that check via iframes that transferring VideoFrames out of cluster is not working.
The spec is not placing such constraints AFAIK so I do not think these tests are really valid.

Also, they are part of interop 2023, but, at least in Safari, they just exhibit that iframes are not in their own process.
I guess we can somehow try to fix this but given we might ultimately want to transfer over clusters, I wonder whether the following would not be better:
- Move the two tests in a separate file (to keep chrome coverage).
- Move the two test out of interop 2023.

@dalecurtis, @padenot thoughts?

**Comment by dalecurtis** [comment]
@ChunMinChang who authored these tests.

I don't really understand cross agent clusters, so will defer to the experts on this. Separate file plus removing from Interop 2023 seems okay to me though if there's no loss in security properties though.

@domenic

**Comment by domenic** [comment]
I agree there is no such restriction in the spec.

Agent cluster restrictions on transferring exist to avoid transferring dangerous capabilities, namely `SharedArrayBuffer`, outside of an agent cluster which has been blessed with that capability. Unless `VideoFrame` also gives you a dangerous capability (e.g. because it has shared memory somehow?) then such a restriction doesn't seem necessary. And indeed, flipping the test's pass condition might be better, to *require* that they be transferrable across agent clusters.

**Comment by dalecurtis** [comment]
`VideoFrame` doesn't provide write access and `VideoFrames` always copy or transfer if an input ArrayBuffer is provided. UAs would need to take care they don't accidentally allow zero-copy non-transferred `SharedArrayBuffer`s to back a `VideoFrame`, but that's likely to explode immediately for memory safety reasons.

You can use a transfer of `VideoFrame` to share an effective camera permission outside of the cluster, but that's also true of   `ImageBitmap`, `ImageData`, or even just a plan RGBA `ArrayBuffer`. 

The only other reason I can think that we shouldn't do this is if things like `ImageBitmap`, etc are supposed to be tainted when transferred across agent boundaries. `VideoFrame` doesn't have a tainting mechanism, so all data in it is considered same origin.

**Comment by youennf** [comment]
I'll prepare a PR to separate the tests.
I'll leave the tests unchanged for now but will add a comment about reversing the expectation that cross agent cluster transfer work.
 
@nt1m, we might want the new test file to move out of Interop 2023.

**Comment by youennf** [comment]
Trying to create a VideoFrame from a not-origin-clean source should probably throw, we then do not need to handle this check as part of transfer.

My understanding of the test was that it was covering a particular aspect of Chromium's implementation state.
Whether the spec will change to restrict to this implementation state or not can be discussed at https://github.com/w3c/webcodecs/issues/717.

Given the above issues and the merged PRs, I think we can close this issue and move the discussion to https://github.com/w3c/webcodecs/issues/717.
