### ISSUE TITLE
[css-grid] inheriting line names in subgrid/orthogonal-writing-mode-005.html

### ISSUE THREAD

**Issue by sgill26** [web-platform-tests/wpt#41831]
I was looking into `css/css-grid/subgrid/orthogonal-writing-mode-005.html` and have had some trouble figuring out what is going on in the "Named grid areas" section. I believe all of the tests in this section are similar, but here is just grid that is being tested in the file:

```
<!DOCTYPE HTML>
<html>
<head>
<style>
body {
  color:black; background-color:white; font:10px monospace; padding:0; margin:0; line-height:0;
}

.grid {
  display: inline-grid;
  grid-auto-columns: 15px;
  border: 1px solid;
  vertical-align: bottom;
}

.subgrid {
  display: grid;
  grid-template-columns: subgrid;
  grid-column: 3 / span 4;
  background: grey;
}

.grid > .subgrid > .subgrid {
  writing-mode: vertical-lr;
  grid-template-rows: subgrid;
  grid-template-columns: initial;
  grid-column: 1 / span 4;
  grid-auto-columns: 8px;
  grid-auto-flow: column;
}

.areas-1a { grid-template-areas: 'x x x x' }

.subgrid > .subgrid > :nth-child(2n)   {  background: black; }
.subgrid > .subgrid > :nth-child(2n+1) {  background: pink; }
.subgrid > .subgrid > * { writing-mode: horizontal-tb; }
</style>
</head>
<body>
<div class="grid"><div class="subgrid areas-1a"><div class="subgrid">
  <div style="grid-row:x-start"></div>
  <div style="grid-row:x"></div>
  <div style="grid-row:x-start / x-end"></div>
  <div style="grid-row:x-end"></div>
</div></div></div>
</body>
</html>
```

Currently ToT WebKit, Blink, and Gecko seem to have different renderings. Particularly ToT WebKit disagrees with both Blink and Gecko which have the same rendering. 

The inner most subgrid is orthogonal to both the outer subgrid and parent grid. I believe it should be able to inherit the implicit line names defined by the grid area when it comes to its rows (which are the columns of the parent subgrid). 

As a result, I believe an item placed at `grid-row: x-start` should be able placed in the inner subgrid's first row (outer subgrid's first column). All three engines seem to agree here. 

However, WebKit disagrees with the following two examples: 

1.) An item placed with `grid-row: x-start / x-end` should start at the inner subgrid's first row and span to the last row (start at the outer subgrid's first column and span to the last column). I think this should also be equivalent to `grid-row: x`

2.) An item placed with `grid-row: x-end` should be placed at the inner subgrid's last row (outer subgrid's last column)

Is there anything that I am not taking into consideration that is making WebKit's implementation incorrect in this case?  Below is what I believe is a logically equivalent test case without the orthogonal subgrid in which all three engines have the same rendering:

```
<!DOCTYPE HTML>
<html><head>
 <style>
body {
 color:black; background-color:white; font:10px monospace; padding:0; margin:0; line-height:0;
}

.grid {
 display: inline-grid;
 grid-auto-columns: 15px;
 border: 1px solid;
 vertical-align: bottom;
}

.subgrid {
 display: grid;
 grid-template-columns: subgrid;
 grid-column: 3 / span 4;
 background: grey;
}
.grid > .subgrid > .subgrid {

 grid-template-rows: initial;
 grid-template-columns: subgrid;
 grid-column: 1 / span 4;

 grid-auto-rows: 8px;
 grid-auto-flow: row;
}
.areas-1a { grid-template-areas: 'x x x x' }

.subgrid > .subgrid > :nth-child(2n)  { background: black; }
.subgrid > .subgrid > :nth-child(2n+1) { background: pink; }
.subgrid > .subgrid > * { 
 writing-mode: horizontal-tb;
 grid-column: x-end;
}
 </style>
</head>
<body>
<div class="grid"><div class="subgrid areas-1a"><div class="subgrid">
  <div style="grid-column:x-start"></div>
  <div style="grid-column:x"></div>
  <div style="grid-column:x-start / x-end"></div>
  <div style="grid-column:x-end"></div>
</div></div></div>
</body>
</html>
```

**Comment by sgill26** [comment]
CC @KurtCattiSchmidt

**Comment by nt1m** [comment]
cc @dholbert @bfgeek

**Comment by KurtCattiSchmidt** [comment]
Hi! This is a bit of a subtle issue that wasn't well tested, hence why I added the additional case.

"The inner most subgrid is orthogonal to both the outer subgrid and parent grid. I believe it should be able to inherit the implicit line names defined by the grid area when it comes to its rows (which are the columns of the parent subgrid)."

Blink and Gecko's behavior is to not only *inherit* the implicit line names, but also to *transpose* rows and column grid-area definitions for orthogonal subgrids. This is consistent between Blink and Gecko and is specifically what's being tested here. I believe this is also consistent with what authors would expect for orthogonal nested subgrids. This part of the spec implies this, but it doesn't outright state it for grid-areas:

"Line numbering and placement rules obey the [subgrid](https://www.w3.org/TR/css-grid-2/#subgrid)’s own [writing mode](https://www.w3.org/TR/css-writing-modes-4/#writing-mode), just as they would for a nested independent grid."
https://www.w3.org/TR/css-grid-2/#subgrid-indexing

If line numbers get transposed, it makes sense that the inherited grid-areas would be transposed as well.

Removing the orthogonal `writing-mode` for the nested subgrid doesn't transpose row/column grid-area's, which avoids this scenario entirely.

Hope that helps!

**Comment by sgill26** [comment]
Yeah I think that make sense, but I'm not quite sure how that translates to the output that I'm seeing. Here's a slightly modified version of that test case (main difference is that the nested sub grid is removed and the subgrid completely overlaps the parent grid):

```
!DOCTYPE HTML>
<html>
<head>
<style>
.grid {
  display: inline-grid;
  grid-auto-columns: 15px;
  border: 1px solid;
}

.subgrid {
  display: grid;
  writing-mode: vertical-lr;
  grid-template-rows: subgrid;
  grid-column: 1 / span 4;
  background: grey;
  grid-auto-columns: 8px;
  grid-auto-flow: column;
}

.areas-1a { grid-template-areas: 'x x x x' }

.subgrid >  :nth-child(2n)   {  background: black; }
.subgrid >  :nth-child(2n+1) {  background: pink; }
.subgrid >  * { writing-mode: horizontal-tb; }

</style>
</head>
<body>
<div class="grid areas-1a">
  <div class="subgrid">
    <div style="grid-row:x-start"></div>
    <div style="grid-row:x"></div>
    <div style="grid-row:x-start / x-end"></div>
    <div style="grid-row:x-end"></div>
  </div>
</div>
</body>
</html>
```

If I'm interpreting things correctly what should happen is something along the lines of:

1.) The sub grid inherits the named grid area (`"x x x x"`) from its parent
2.) It transposes it due to the writing mode change and so it effectively becomes:
```
"x",
"x",
"x",
"x"
```
I believe the important bit here is that the line names (implicit and explicit) keep their physical locations which is what I think the spec intends. The line names and their physical locations within the subgrid should then be exactly the same as in the parent grid. Does any of that seem incorrect to you?

**Comment by KurtCattiSchmidt** [comment]
Great question, and it would be helpful for someone to the working group to clarify expected behaviors here. 

> I believe the important bit here is that the line names (implicit and explicit) keep their physical locations which is what I think the spec intends. The line names and their physical locations within the subgrid should then be exactly the same as in the parent grid. Does any of that seem incorrect to you?

The physical locations of grid-areas may not map 1:1 to the parent grid - in cases where the subgrid only partially overlaps a grid-area from the parent grid, a 1:1 mapping won't be possible. For this situation, I added some logic to Blink to update the `-start` and `-end` implicit names to map the respective start and ends of the subset within the subgrid, as this was expected behaviors in other tests - in particular the last two cases of [line-names-005.html](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/css/css-grid/subgrid/line-names-005.html) and various cases in [line-names-006.html](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/css/css-grid/subgrid/line-names-006.html)

My understanding is that this behavior should carry over to orthogonal subgrids (except with flipped row/column values), and is perhaps the discrepancy you're seeing here. But it would be fantastic to get some clarification on expected behaviors from the working group, as my understanding (and Firefox's behavior) may be incorrect.

**Comment by sgill26** [comment]
Sure! Went ahead and opened a CSSWG discussion here: https://github.com/w3c/csswg-drafts/issues/9418

**Comment by nt1m** [comment]
Closing this in favor of the CSSWG issue.
