### ISSUE TITLE
Test harness regression from commit @0531410

### ISSUE THREAD

**Issue by allstarschh** [web-platform-tests/wpt#41846]
I found the WPT for /workers failed after the commit 
https://github.com/web-platform-tests/wpt/commit/0531410985f4a93b0859acfb9182fc6c6a0fe334

For example
Before 
https://wpt.fyi/results/workers/modules/dedicated-worker-import.any.html?sha=c01dec4d93&label=master&max-count=1&q=dedicated-worker-import.any.html

After
https://wpt.fyi/results/workers/modules/dedicated-worker-import.any.html?sha=0531410985&label=master&max-count=1

Those tests related to cross-origin requests all failed
Originally the test will fetch the worker script from www1,
but with the change in https://github.com/web-platform-tests/wpt/commit/0531410985f4a93b0859acfb9182fc6c6a0fe334, the scripts from the remote-origin cannot be fetched anymore.
(It doesn't use a new origin, still use the original origin)

@youennf, can you fix this or revert your change?

**Comment by youennf** [comment]
Oh right, I'll fix it asap

**Comment by allstarschh** [comment]
The issue still exists
https://wpt.fyi/results/workers/modules/dedicated-worker-options-credentials.html?label=master&label=experimental&product=chrome&product=firefox&product=safari&aligned&view=interop&q=label%3Ainterop-2023-modules

The failing test should use a remote origin (HTTP://www1), but it is still using the original origin.
