### ISSUE TITLE
Request to install at least one CJK font for Linux bots

### ISSUE THREAD

**Issue by kojiishi** [web-platform-tests/wpt#41851]
https://wpt.fyi/results/css/css-text/word-break/auto-phrase/word-break-auto-phrase-wbr-nobr-001.html?label=experimental&label=master&aligned
is failing for Chrome on Linux, because all Japanese characters are white boxes that are narrower than 1em. It passes for Edge on Windows because Windows has CJK fonts.

I can work around by using web fonts, it looks like we have `mplus-1p-regular.woff`, but results of tests that forget to do it are not reliable, even if they pass.

Is it reasonable to ask to install at least one font for C/J/K to Linux bots?

**Comment by gsnedders** [comment]
This is #13203 again, really.
