### ISSUE TITLE
support full parallel in Wptrunner

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#41870]
In chromium we have parameter '-f', '--fully-parallel' which chunks each individual tests into a separate group. Tests can then be run in parallel on a powerful work station, e.g. 50 cores.

When developers run tests locally, they typically only run tests from few directories. The current grouping method won't chunk them into small enough group so can not fully utilize the capability of the powerful work stations devs had.

chromium bug: crbug.com/1479850

**Comment by WeizhongX** [comment]
@jgraham thoughts on this? We plan to prepare a PR for review.

@foolip @jonathan-j-lee

**Comment by jonathan-j-lee** [comment]
We could use `--test-groups` to pass the one test per group, like `{"/path/to/test.html": ["/path/to/test.html"], ...}`.

**Comment by WeizhongX** [comment]
Yes, if we decided to not make this native to upstream.

Make this change at upstream can benefit non chromium devs.

**Comment by foolip** [comment]
Let's see if I understand. If we have 50 cores, `./wpt run --processes 50` doesn't work, because there aren't enough distinct test groups? How many are there by default? You say this will be used mostly run a small number of tests, but let's say we have 500 tests. Is 500 test groups still better (faster) than 50 test groups with 10 tests in each?

**Comment by WeizhongX** [comment]
Yes, the reason is that we are chunking tests by directory, and if these 500 tests are all in the same directory, they will all be put into one group, and even if we pass --processes 50, we would only actually launch one worker for that.

This is the case reported in crbug.com/1479850. There are 586 tests in this folder, and all put into one group.

If we can chuck tests into maximum test groups (defined by --processes) evenly, it probably will perform similar (or better due to less overhead) to fully parallel chunking, but would be something unnature to implement.

**Comment by gsnedders** [comment]
> Let's see if I understand. If we have 50 cores, `./wpt run --processes 50` doesn't work, because there aren't enough distinct test groups? How many are there by default? You say this will be used mostly run a small number of tests, but let's say we have 500 tests. Is 500 test groups still better (faster) than 50 test groups with 10 tests in each?

At least in the `run-webkit-tests` case, we restart the browser after each group (or "shard" in `webkitpy`), so there's isolation implied by 500-groups-of-1 that isn't by 50-groups-of-10. It also allows you to see when there is carryover state affecting tests.

The bigger problem, really, is "how do you form those groups of 10".

**Comment by WeizhongX** [comment]
Fixed in #41924 

Folks, feel free to leave a comment to the PR if you have a comment. Never too late, :-)
