### ISSUE TITLE
img.complete test has bogus loop thing

### ISSUE THREAD

**Issue by bzbarsky** [web-platform-tests/wpt#4195]
The test at html/semantics/embedded-content/the-img-element/img.complete.html does this:

    async_test(function(t) {
      assert_false(imageInstance.complete, "imageInstance.complete should be false");
      var startTime = Date.now();
      while (true) {
        if (Date.now() - startTime > 2000)
          assert_unreached('.complete didn\'t change to true');
        if (imageInstance.complete === true) break;
      }
      t.done();

This can't possibly pass, because the value of "complete" cannot change while in a busy-loop in JS.  I'm not sure what this test is trying to test, but it's bogus.

**Comment by bzbarsky** [comment]
Looks like @deniak committed this as part of "move TTWF tests".   No useful info on where it was moved from and why the test is trying to do this... :(

**Comment by jdm** [comment]
The spec claims that `complete` should reflect whether a particular task has been queued, which is how this is intended to pass: https://html.spec.whatwg.org/multipage/embedded-content.html#dom-img-complete

**Comment by bzbarsky** [comment]
That's ... not OK.  That information is not generally available and shouldn't be.  Filed https://github.com/whatwg/html/issues/2038

**Comment by foolip** [comment]
Spec bug is now https://github.com/whatwg/html/issues/1055.

**Comment by annevk** [comment]
Fixed by https://github.com/web-platform-tests/wpt/commit/dc2e245a955c832e88d24e6a1af5f718da5491bd.
