### ISSUE TITLE
Wptrunner needs to have a way to check exact text output for a match

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#42034]
One use case is about the subtest `[Partially-selected editable content: input event]` in editing/event.html. Even though the test is expecting 0 event to be fired, chromium is expecting 1, (possibly due to disagreement to the standard?). In chromium we would compare the test output of this subtest to `FAIL Partially-selected editable content: input event assert_equals: number of input events fired expected 0 but got 1` to ensure no regression to this test.

Is it possible that Wptrunner supports "match" for test harness subtests? For such expectations, Wptrunner will compare the test output with a string to decide if the test passed or failed.

One possible example format would be:
```
[event.html]
  [Partially-selected editable content]
    match: "assert_equals: number of input events fired expected 0 but got 1"
```
Any quotation mark in the output needs to be escaped first.

(Different mitigation plans have been discussed but rejected due to high maintanance cost.)

**Comment by WeizhongX** [comment]
@jgraham We'd like to know your opinion on this. Is it ok we proceed to create an RFC for this?

@foolip

**Comment by jonathan-j-lee** [comment]
Note that there's precedent for [vendor-specific metadata keys](https://web-platform-tests.org/tools/wptrunner/docs/expectation.html#web-platform-tests-metadata). For example, Firefox has `lsan-disabled: ...` and others:

https://github.com/web-platform-tests/wpt/blob/305d25f4dc74090c3eef1b5f1f069c2910ac3890/tools/wptrunner/wptrunner/browsers/firefox.py#L826-L829

Discussion Chromium-side: https://crbug.com/1481730

**Comment by jgraham** [comment]
wpt isn't really designed for this, and I don't quite see how it would work in practice. In particular there's no requirement that the output of a test be consistent over time, only the name. Also the automatic update situation seems problematic; you'd need to be able to automatically update the `match` text if the test changes, which means setting it to a string literal, which for practical reasons seems difficult in the current architecture (you'd have to store every output string in case you're updating across multiple configurations and want to match different strings in different configurations, which is going to have high memory overhead).

The `lsan_*` keys are at least designed to be solutions that could work for other browsers.

All that said, if you want to deal with the limitations here, that seems fine. I think it does require an RFC, and I would be opposed to anything that required test authors to ensure that the output of their asserts was consistent between runs; that seems like too high a burden on test authors (consider the case where the assert is a floating point number with some expected variation between runs, for example).

**Comment by WeizhongX** [comment]
Might be better to use `expected-fail-message` instead of `match`, if the message is only intended to be effective when result is `FAIL` or `PRECONDITION_FAILED `. This should not have an impact to other vendors if they do not use the tag in their metadata file.

One example metadata file will look like below:
```
[event.html]
  [Changing selection from handler: input event]
    expected: [FAIL, PASS]
    expected-fail-message: "something wrong"
```
@jgraham do we need to extend the metadata parser to support two keys for one subtests?

> ensure that the output of their asserts was consistent between runs
We does require the output to be consistent now due to the way we are running WPTs. We either need suppress such tests in chromium or somebody need to fix it. Once we support `*`, we will be able to accomandate that better.

**Comment by WeizhongX** [comment]
RFC approved, and issue fixed in https://github.com/web-platform-tests/wpt/pull/42406
