### ISSUE TITLE
how to add dns for iOS wptrunner

### ISSUE THREAD

**Issue by sj0602** [web-platform-tests/wpt#42209]
When I do locally test the ios wptrunner on my mac, I used this http://web-platform-tests.org/running-tests/from-local-system.html#hosts-file-setup and this give me the right result.
When I set up the CI builder, without the /etc/hosts file setup, no tests passed due to missing website.

I tried to add this flag --host-resolver-rules and it seems not working with iOS.
However when the CI builder runs, the python code does not have the sudo permission to set up the /etc/hosts file.
Is there any workaround here?

I also tried export HOSTALIASES=, but this is not working on Mac.

**Comment by WeizhongX** [comment]
This is not needed anymore.
