### ISSUE TITLE
background-blend-mode test probably needs to be extended and fixed

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#42496]
https://github.com/web-platform-tests/wpt/blob/1e1d4055cf9f4b361f8e7052c681a3f2776d214d/css/compositing/parsing/background-blend-mode-computed.html#L32-L34

Followup of discussions in https://bugs.webkit.org/show_bug.cgi?id=261552#c10

In https://drafts.fxtf.org/compositing-1/#background-blend-mode

> Defines the blending mode of each background layer.
> 
> Each background layer must blend with the element’s background layer 
> that is below it and the element’s background color. Background layers 
> must not blend with the content that is behind the element, instead 
> they must act as if they are rendered into an isolated group.

and

> The background-blend-mode list must be applied in the same order 
> as background-image [CSS3BG]. This means that the first element 
> in the list will apply to the layer that is on top. If a property 
> doesn’t have enough comma-separated values to match the number 
> of layers, the UA must calculate its used value by repeating the 
> list of values until there are enough.

The layering seems to be defined in 
https://drafts.csswg.org/css-backgrounds-3/#layering

It says:

> Each of the images is sized, positioned, and tiled according 
> to the corresponding value in the other background properties. 

Then (my emphasis)

> The lists are matched up from the first value: **excess values at the end are not used.** 

Then 

> If a property doesn’t have enough comma-separated values 
> to match the number of layers, the UA must calculate its used value 
> by repeating the list of values until there are enough.

The example in this section 

```
background-image: url(flower.png), url(ball.png), url(grass.png);
background-position: center center, 20% 80%, top left, bottom right;
background-origin: border-box, content-box;
background-repeat: no-repeat;
```

has exactly the same effect as this set with the extra position dropped and the missing values for background-origin and background-repeat filled in (emphasized for clarity):

```
background-image: url(flower.png), url(ball.png), url(grass.png);
background-position: center center, 20% 80%, top left;
background-origin: border-box, content-box, border-box;
background-repeat: no-repeat, no-repeat, no-repeat;
```

And we can see that for background-position where there is 4 values list with an extra `bottom right`, it drops it to make it a 3 values list.

So from this I would say the test as currently defined on WPT is wrong and probably the implementation of Gecko too. ( @Emilio )

the [background-blend-mode-computed.htm](http://wpt.live/css/compositing/parsing/background-blend-mode-computed.html)

could be fixed for multiple images for the last 3 tests 
Or maybe better add a new series of tests for specific case of multiple images and their relations to properties. dropping and repeating the values.

**Comment by karlcow** [comment]
Also opened a bug on Firefox.
https://bugzilla.mozilla.org/show_bug.cgi?id=1858591

**Comment by emilio** [comment]
"are not used" doesn't imply "are not part of the computed value". @karlcow can you revert your patch? Would've been nice to at least wait for comments from other engines before modifying the tests? There's existing discussion in the CSS working group about this and my recollection is that gecko was right.

**Comment by emilio** [comment]
https://github.com/w3c/csswg-drafts/issues/7164 has the latest discussion on these things. I forget the exact resolutions and today is a bank holiday for me, but I'm pretty sure dropping specified stuff from the computed value is not it.

**Comment by karlcow** [comment]
Ah! This sentence in 
https://github.com/w3c/csswg-drafts/issues/7164#issuecomment-1201340918

>  fantasai: Don't specifically say **the computed value is same as specified value, it's implied**. can be louder in the spec so it's obvious

So yup. I probably need to change again this patch. I think we should still add more tests to cover the different cases.

**Comment by karlcow** [comment]
And the update by @fantasai 
https://github.com/w3c/csswg-drafts/commit/dce5c9df4fdc6b1b94acbb8ceb09895c62924c18
aka https://drafts.csswg.org/css-values-4/#linked-properties


It says: 

> The [computed values](https://drafts.csswg.org/css-cascade-5/#computed-value) of the [coordinating list properties](https://drafts.csswg.org/css-values-4/#coordinating-list-property) are not affected by such truncation or repetition.

**Comment by annevk** [comment]
@emilio https://github.com/web-platform-tests/wpt/pull/42503 r?

**Comment by karlcow** [comment]
Created a new PR. Addressing @Emilio comments and giving context so the same mistakes are not not done in the future.
