### ISSUE TITLE
[css-color-4] Conversion of hsl(none none none) to srgb clarification.

### ISSUE THREAD

**Issue by tiaanl** [web-platform-tests/wpt#42677]
In the tests here:

https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-computed-color-mix-function.html#L80

There is a test with `color-mix(in hsl, hsl(none none none), hsl(none none none))` which should result in `hsl(none none none)` (and it does), but then of course will be converted to `srgb` for serialization.  That result is `color(srgb none none none)`, which I'm not sure how it is calculated.

Chrome passes the test, but that seems to be a bug. They never clear the none flags after conversion to `srgb`, so `color-mix(in hsl, hsl(30deg 40% none), hsl(30deg 40% none))` would result in `color(srgb 0 0 none)`, just because lightness was `none`.

I think we should change the test to `color(srgb 0 0 0)`?

**Comment by svgeesus** [comment]
From [“Missing” Color Components and the none Keyword](https://drafts.csswg.org/css-color-4/#missing) (my emphasis)

> For handling of [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) in color interpolation, see [§ 12.2 Interpolating with Missing Components](https://drafts.csswg.org/css-color-4/#interpolation-missing).

> For **all other purposes**, a [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) **behaves as a zero value**, in the appropriate unit for that component: 0, 0%, or 0deg. This includes rendering the color directly, **converting it to another color space,** performing computations on the color component values, etc.

So yes, when the [`color()` function is serialized](https://drafts.csswg.org/css-color-4/#serializing-color-function-values) is will have `0` not `none`.

**Comment by tiaanl** [comment]
Perfect, will update the test. Thank! :+1:

**Comment by mysteryDate** [comment]
So, the key verbiage here from the spec is "converting it to another color space"?

**Comment by mysteryDate** [comment]
Since RCS with hsl/hwb/legacy rgb involve color space conversion, would explicit "nones" become zeros here too? i.e.:

`hsl(from blue none none none)` = `color(srgb 0 0 0)`?

Does this look a little weird with legacy rgb?
`rgb(from blue none none none)` = `color(srgb 0 0 0)`?

And then, does this also apply to alpha?
`rgb(from blue r g b / none)` = `color(srgb 0 0 1 / 0)`?

while:
`color(srgb from blue r g b / none)` = `color(srgb 0 0 1 / none)`?
