### ISSUE TITLE
[css-color-4] Test whether system colors are actually supported

### ISSUE THREAD

**Issue by xaddict** [web-platform-tests/wpt#42674]
There are some tests that test for color values, color comparison and whether set colors stay set instead of disappear:
- https://github.com/web-platform-tests/wpt/blob/master/css/css-color/system-color-consistency.html
- https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid-system-color.html
- https://github.com/web-platform-tests/wpt/blob/master/css/css-color/parsing/color-valid.html
- https://github.com/web-platform-tests/wpt/blob/master/css/css-color/system-color-compute.html

But none of these tests checks whether setting a system color results in a color.

For example, the following:
```html
<div style="background: accentcolor; color: accentcolortext">I am text</div>
```
results in a colored text on a colored background in Firefox and Safari.

But Chrome (all the versions i have tested so far) doesn't support accentcolor or accentcolortext.

Asking for `el.style.color` however, DOES return 'accentcolortext' even though its not supported.

It would be neat if there was a test that takes the list of agreed-upon system colors (https://drafts.csswg.org/css-color/#css-system-colors) and tests whether those values result in colors.

That would also be a great test suite for Interop 2024 (I guess I'm too late for 2023 at this point)

**Comment by svgeesus** [comment]
> It would be neat if there was a test that takes the list of agreed-upon system colors (https://drafts.csswg.org/css-color/#css-system-colors) and tests whether those values result in colors.

It would. I guess setting to red, then to the system color, and pass is "not red" would work? Although, maybe also check that is is not the initial value of the color property, either.

**Comment by xaddict** [comment]
@svgeesus I was thinking setting the color to black and the system color and checking if not black, then setting to white and the system color and checking if not white. If one of the two passes the color works as expected?

```html
<div style="background-color: black; background-color: AccentColor;"></div>
<div style="background-color: white background-color: AccentColor;"></div>
```

It seems like a really simple test to write, but I would not know how to write this as test suite like the ones from csswg

**Comment by xaddict** [comment]
I'm gonna take a stab

**Comment by xaddict** [comment]
@svgeesus I've created a pull request which seems to fail on an unrelated Safari Technology preview thingie.

**Comment by svgeesus** [comment]
It seems to [pass everywhere](https://wpt.fyi/results/css/css-color/system-color-support.html?label=experimental&label=master&aligned)

**Comment by svgeesus** [comment]
Looks like this issue can be closed; the tests are good and everyone passes.

**Comment by xaddict** [comment]
The test does seem to pass in all the browsers being used on wpt. But that is mainly because chrome is being run only on Linux and Edge is being run only on Windows.

Chrome on macOS fails and Edge on macOS also fails. I might look for a way to improve the test.

Or maybe WPT can add support for running tests for browsers on more then just one platform? Chromium on Windows, Linux and macOS, and maybe mobile browsers like Safari, Samsung internet and chromium on Android? Maybe a sponsorship by BrowserStack? 😉

Met vriendelijke groet,
Luuk Lamers

**Comment by xaddict** [comment]
After some research it seems to only works in Chromium browser when experimental web features is on. I don't know whether for example Web Compat data could use this test to check for AccentColor support.
