### ISSUE TITLE
FR: Establish a default python formatter and enforce it via CI

### ISSUE THREAD

**Issue by thiagowfx** [web-platform-tests/wpt#42710]
So long as we do not agree on a default formatter for this repository, back-end-forth diff noise and bikeshedding keeps coming up ([e.g.](https://github.com/web-platform-tests/wpt/pull/42667#discussion_r1369685193)).

It would be the best to everyone, and for improved devex, to agree to use one and only one formatter.
Additionally, to ensure it sticks, we should add some CI job to enforce that no violations are introduced.

The status quo (at least within the realm of WebDriver BiDi) seems to be the following:

- Google / Chromium and the Chromium BiDi Mapper use `yapf v0.31.0`.
- Mozilla / Firefox uses `black`.

The following AIs should happen:

1. [ ] agree on which formatter to use: `yapf`, `black`, or something else?
2. [ ] globally format the codebase using it
3. [ ] add a (non-optional?) CI check to enforce it

Resources:

- yapf: https://github.com/google/yapf
- black: https://github.com/psf/black

cc @juliandescottes

**Comment by jgraham** [comment]
I think we should close this issue in favour of the RFC repo issue.
