### ISSUE TITLE
runner incorrectly thinks tests are manual

### ISSUE THREAD

**Issue by svgeesus** [web-platform-tests/wpt#42892]
I'm running some APNG tests locally to check them before making a pull request. The runner thinks they are manual tests, and I don't understand why.

> The current test requires manual result marking. Test and ref should compare equal

![image](https://github.com/web-platform-tests/wpt/assets/2506926/83b1369f-9fea-40d1-9108-66962a0d996f)

Although I do have a few manual tests in this batch, those are all using the `foo-manual.html` naming convention. This one does not have a filename like that, it includes a match, and `wpt lint` agrees that the reference file exists. Can someone tell me what is wrong with this file which makes the runner think it is manual?

```html
<!DOCTYPE html>
<html class="reftest-wait">
<meta charset="utf-8">
<title>PNG Third Edition: animated PNG, split fdAT</title>
<link rel="author" title="Chris Lilley" href="mailto:chris@w3.org">
<link rel="help" href="https://www.w3.org/TR/png-3/#apng-frame-based-animation">
<link rel=""help" href="https://www.w3.org/TR/png-3/#fdAT-chunk">
<link rel="match" href="apng-lime-rectangle-ref.html">
<meta name="assert" content="The compressed datastream is then the concatenation of the contents of the data fields of all the fdAT chunks within a frame. ">
<script>
    const el = document.querySelector(".reftest-wait");
    setTimeout(() => {
        el.classList.remove('reftest-wait');
        }, "2000");
</script>
<body>
    <p>Test passes if you see a lime green rectangle, and no red.</p>
    <div class="test"><img src="support/005.png" alt=""></div>
</body>
```
Or does it consider all reftests to need manual testing, instead of doing automatic pixel comparison?

**Comment by gsnedders** [comment]
The old web runner has no way to do reftests automatically (there's no way to screenshot an arbitrary page via web API). You want to use `wpt run` to actually run things automatically.

**Comment by svgeesus** [comment]
Thanks!
