### ISSUE TITLE
Meta: Give @Lightning00Blade 'Writer' access to the repository

### ISSUE THREAD

**Issue by thiagowfx** [web-platform-tests/wpt#42939]
Hi, could we give @Lightning00Blade 'Writer' access to this repository? He is actively working on writing and reviewing WebDriver BiDi spec tests, alongside @sadym-chromium, @OrKoN, @jrandolf and I.

The fact he is not currently a writer means that he cannot approve PRs. This slows us down (for example, I currently have 4 PRs waiting for review, and most people are OOO today).

@web-platform-tests/admins

(cc @mathiasbynens FYI)

**Comment by past** [comment]
I have sent him an invitation.
