### ISSUE TITLE
Easier to find `.headers` and `.sub` files documentations

### ISSUE THREAD

**Issue by yoavweiss** [web-platform-tests/wpt#4313]
I'm looking into writing wptserve based tests and the [easily findable documentation](https://github.com/w3c/web-platform-tests/blob/master/server-side.md) on that subject doesn't seem to mention `.headers` and `.sub` files which enable simpler conversion of existing Blink layout tests into wptserve tests. 

Would be great if those were mentioned there, with links towards appropriate documentation of those options.

**Comment by foolip** [comment]
@yoavweiss, is http://web-platform-tests.org/writing-tests/server-features.html any good?

@jgraham @gsnedders, I assume we should merge that stray server-side.md into the above?

**Comment by yoavweiss** [comment]
@foolip yeah, that looks good! Maybe merge the above into server-side.md, to make the content more findable?

**Comment by foolip** [comment]
Yes, that documentation is stray and should be consolidated. Assigning to @kereliuk who's signed up for at least some light consolidation this quarter.
