### ISSUE TITLE
Python 3.7 has reached end-of-life

### ISSUE THREAD

**Issue by bashi** [web-platform-tests/wpt#43143]
Python 3.7 reached [end-of-life](https://peps.python.org/pep-0537/) at 2023-06-27. Do we have a plan to deprecate Python 3.7?

Context is that the latest version of aioquic, 0.9.22, [dropped](https://github.com/aiortc/aioquic/commit/33b760951c6128831db211ce54ceb22bea96f024) Python 3.7 support. The WebTransport wpt infrastructure depends on aioquic, and I want to update aioquic to pull [my change](https://github.com/aiortc/aioquic/commit/2fe490a2f5a4fae8479760bb46fb15affcba52e3) so that we can increase test coverage for WebTransport.

See also https://github.com/web-platform-tests/wpt/pull/42984

**Comment by foolip** [comment]
@jgraham does Gecko infra use Python 3.7?

**Comment by jlaine** [comment]
@bashi ouch I had not realised WPT relied on Python 3.7, I would have considered holding off dropping Python 3.7 if I had known that. I'm not too keen on rolling back the change now that it's done though..

**Comment by bashi** [comment]
If we can drop Python 3.7 from wpt, that would be the best.

@jlaine How hard is it to roll back the change? If it's somewhat trivial and if you're fine with it, I could try to create a PR to roll back.

**Comment by jgraham** [comment]
Gecko still supports 3.7, and our CI still runs 3.7 in some cases: https://bugzilla.mozilla.org/show_bug.cgi?id=1843209

I don't think updating is going to be as slow as 3.6→3.7 was, but I also don't see much evidence it's got high priority.

**Comment by foolip** [comment]
Do you know what version you're upgrading to? It looks like 3.8, but bumping one version at a time means this will happen more often.

**Comment by bashi** [comment]
I'm targeting at 3.8, but I agree that it could be a pain to keep the version up to date.

I hope that the Python community could have some idea of long term support, but I don't think that could happen.

**Comment by jgraham** [comment]
Gecko is aiming for 3.8 and AIUI that's the most we can bump to for linux builds due to distro requirements. It is not impossible that we'll decouple the requirements on the build from the requirements from the test harnesses, but I don't know the detailed tradeoffs there.

**Comment by jgraham** [comment]
Apparently Gecko is on the cusp of updating the minimum supported version to 3.8 (and this bug is cited as a reason). But per @gsnedders Apple still require 3.7 support.

I believe WebKit doesn't currently support web transport, so one slightly awkward compromise would be to require 3.7 support only when webtransport is not enabled. We could update the CI to match (e.g. update the Linux infra tests to 3.8 and keep running Infra tests on mac in 3.7).

**Comment by bashi** [comment]
@jgraham Do you know what't the current status of Gecko regarding Python 3.8 upgrade?

**Comment by past** [comment]
@whimboo can we close this after #45575?

**Comment by whimboo** [comment]
Oh yes we can! Nothing runs with Python 3.7 anymore.
