### ISSUE TITLE
Color mix tests added in https://github.com/web-platform-tests/wpt/pull/42940 may ignore alpha premultiplication

### ISSUE THREAD

**Issue by mysteryDate** [web-platform-tests/wpt#43180]
Looking at the tests added here: https://github.com/web-platform-tests/wpt/pull/42940/files#diff-17d0bf90434793454df8bbbd34e081eef94d3697534f8ec2c433359700a6b985R368

Using this line as an example: `color-mix(in lab, lab(10 20 30 / 25%) 0%, lab(none none none / 0.5))`
with the expected value: `lab(10 20 30 / 0.5)`

And following https://csswg.sesse.net/css-color-4/#interpolation-alpha and https://csswg.sesse.net/css-color-5/#color-mix-with-alpha:

First we must premultiply the values of both colors, so the premultiplied colors are:
`lab(2.5 5 7.5 / 0.25)` and `lab(none none none / 0.5)`

The resulting, interpolated value, taking 0% of the left and 100% of the right, and respecting missing components:
`lab(2.5 5 7.5 / 0.5)`

Which, un-premultiplied with the interpolated alpha value is, dividing all components by `0.5`:
`lab(5 10 15 / 0.5)`

Which is the current result value in chromium. I believe these tests here omit the fact that the alpha used for premultiplication and un-premultiplication are different.

**Comment by foolip** [comment]
@mysteryDate would it be straightforward to update the test expectations here?

**Comment by mysteryDate** [comment]
Yeah, it would be.

Looking into the original change [here](https://github.com/web-platform-tests/wpt/pull/42940), I see the logic. Any number interpolated with "none" should result in no change, regardless of the alphas involved. I _really_ don't see anywhere in the spec where this is mentioned though. I would not be surprised at all if the spec does change.

So, should I change the test expectations to match what the spec says, or should I change chromium's behavior to match what the other UAs are doing and what I suspect the spec will eventually say explicitly?

**Comment by svgeesus** [comment]
> Any number interpolated with "none" should result in no change, regardless of the alphas involved. I really don't see anywhere in the spec where this is mentioned though. I would not be surprised at all if the spec does change.

From [12.2. Interpolating with Missing Components](https://drafts.csswg.org/css-color-4/#interpolation-missing):

> If a color with a carried forward [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is interpolated with another color which is not missing that component, the missing component is treated as having the other color’s component value.

and

> If the carried forward [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is alpha, the color must be premultiplied with this carried forward value, not with the zero value that would have resulted from color conversion.

and then from []():

> otherwise, each component which had been premultiplied is divided by the interpolated alpha value.

@mysteryDate  You are suggesting that carried forward values should not get un-premultiplied? But did, earlier, get premultiplied?

**Comment by svgeesus** [comment]
> The resulting, interpolated value, taking 0% of the left and 100% of the right, and respecting missing components:
`lab(2.5 5 7.5 / 0.5)`

Yeah but you didn't premultiply there, so the resulting, interpolated, _premultiplied_ value is `[1.25 2.5 3.75] [0.5]` and when you _un-premultiply_ you get `lab(2.5 5 7.5 / 0.5)`.

**Comment by mysteryDate** [comment]
Ah, I misundersood

> If a color with a carried forward [missing component](https://drafts.csswg.org/css-color-4/#missing-color-component) is interpolated with another color which is not missing that component, the missing component is treated as having the other color’s component value.

If you follow through my logic in https://github.com/web-platform-tests/wpt/issues/43180#issue-1995055234, I was making this subsitution after pre-multiplying (assuming `none * x = none`), so the result was different. Clearly the substitution should be made before premultiplying.

My misunderstanding:
`color-mix(in lab, lab(none 0 0), lab(100 0 0 / 0.6)`
Premultiply first: `lab(none 0 0)`, `lab(60 0 0 / 0.6)`
Interpolating and substituting missing components: `lab(60 0 0 / 0.8)`
Unpremultiply: `lab(62.5 0 0 / 0.8)`

Subsituting before premultiplying:
`color-mix(in lab, lab(none 0 0), lab(100 0 0 / 0.6)`
Substution first: `lab(100 0 0)`, `lab(60 0 0 / 0.6)`
Interpolating: `lab(80 0 0 / 0.8)`
Un-premultiplying: `lab(100 0 0 / 0.8)`

Perhaps it's worth noting in [12.2. Interpolating with Missing Components](https://drafts.csswg.org/css-color-4/#interpolation-missing) that pre-multiplication does not affect the result? i.e. if a component is missing in one color, but not missing in the other, the resulting value is equal to the non-missing value, regardless of alpha premultiplication. Or maybe give an example?

After a little bit of algebra it's now clear to me that `lerp(x * a1, x * a2, t) / lerp(a1, a2, t)` is always equal to `x`, but I certainly didn't see that at first!

> @mysteryDate You are suggesting that carried forward values should not get un-premultiplied? But did, earlier, get premultiplied?

No, I just mis-understood the order. Apologies for my mistake. I'll fix Chromium.

**Comment by svgeesus** [comment]
@mysteryDate 

> Clearly the substitution should be made before premultiplying.

Clarified in https://github.com/w3c/csswg-drafts/commit/f4e79df005c021995869824ec51d006f33d7c2f4

**Comment by mysteryDate** [comment]
Great! Thank you, that clears up any nits I have.
