### ISSUE TITLE
Umbrella bug for WebDriver BiDi Browser Permissions API tests

### ISSUE THREAD

**Issue by thiagowfx** [web-platform-tests/wpt#43305]
Spec: https://github.com/w3c/permissions/pull/425 (as an extension of: https://w3c.github.io/webdriver-bidi/)

cc @OrKoN @Lightning00Blade FYI

AI: Write wdspec tests for this new extension module.

**Comment by marcoscaceres** [comment]
cc @gsnedders and myself on this...
