### ISSUE TITLE
css/cssom/CSSStyleSheet-constructable-concat.html is both a testharness test _and_ a reftest

### ISSUE THREAD

**Issue by nt1m** [web-platform-tests/wpt#43303]
The test contains:

```
<script src="/resources/testharness.js"></script>
<script src="/resources/testharnessreport.js"></script>
```
_and_

`<link rel="match" href="CSSStyleSheet-constructable-concat-ref.html">`

We discovered this, because it trips up the WebKit test importer.

@mfreed7 Was this meant to be a testharness test or a reftest?

**Comment by mfreed7** [comment]
> @mfreed7 Was this meant to be a testharness test or a reftest?

Ugh, not sure what I was going for there. Looks like both. I think maybe I'll just convert to a reftest. Patch coming soon...

**Comment by mfreed7** [comment]
https://github.com/web-platform-tests/wpt/pull/43310
