### ISSUE TITLE
Problems with reference files for 8 css/css-backgrounds/background-origin/origin-* tests

### ISSUE THREAD

**Issue by TalbotG** [web-platform-tests/wpt#43329]
@foolip , @jcscottiii , @gsnedders , @whimboo

Dear github admins and fellow colleagues,

origin-border-box_with_position.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-border-box_with_position.html

origin-border-box_with_position.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-border-box_with_position.html

origin-border-box_with_position.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-border-box_with_position-ref.html

**Why the reference is not correct (or fully parsed and rendered) when the screenshot comparison occurs?**
Can you suggest a correction or improvement to overcome such issue?

I created the reference files for the 8 /css/css-backgrounds/background-origin/ tests.

Same question and issue with the following 7 other background-origin/origin-* tests and their respective associated reference files:

2
origin-border-box_with_size.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-border-box_with_size.html

origin-border-box_with_size.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-border-box_with_size.html

origin-border-box_with_size.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-border-box_with_size-ref.html

- - -

3
origin-border-box.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-border-box.html

origin-border-box.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-border-box.html

origin-border-box.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-border-box-ref.html

- - -

4
origin-content-box_with_position.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-content-box_with_position.html

origin-content-box_with_position.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-content-box_with_position.html

origin-content-box_with_position.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-content-box_with_position-ref.html

- - -

5
origin-content-box_with_size.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-content-box_with_size.html

origin-content-box_with_size.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-content-box_with_size.html

origin-content-box_with_size.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-content-box_with_size-ref.html

- - -

6
origin-padding-box_with_position.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-padding-box_with_position.html

origin-padding-box_with_position.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-padding-box_with_position.html

origin-padding-box_with_position.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-padding-box_with_position-ref.html

- - -

7
origin-padding-box_with_size.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-padding-box_with_size.html

origin-padding-box_with_size.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-padding-box_with_size.html

origin-padding-box_with_size.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-padding-box_with_size-ref.html

- - -

8
origin-border-box_with_radius.html test result:
https://wpt.fyi/results/css/css-backgrounds/background-origin/origin-border-box_with_radius.html

origin-border-box_with_radius.html test:
http://wpt.live/css/css-backgrounds/background-origin/origin-border-box_with_radius.html

origin-border-box_with_radius.html's reference:
http://wpt.live/css/css-backgrounds/reference/origin-border-box_with_radius-ref.html

**Comment by whimboo** [comment]
@jgraham do you have an idea what's wrong with those wpt reftests?

**Comment by TalbotG** [comment]
Now that I am looking at one of the reference file (the first one: origin-border-box_with_position-ref.html) with more distancing, the div class="light-blue-border" is "pushed" below (wrap around over to next line box) when the viewport width (window.innerWidth) is narrower than approx. 1035px ... which could well be
    div.image width = 514px
+
   div.light-blue-border = 482px
+
   scrollbar width

Okay... I am closing this issue right now, acknowledging that I must re-examine those reference files in light of 600px tall by 600px wide viewport dimensions. I am sorry for disturbing you all.
