### ISSUE TITLE
[scroll-animations-1] value of `scroll-timeline` shorthand with mismatching longhand value lists

### ISSUE THREAD

**Issue by graouts** [web-platform-tests/wpt#43336]
I'm working on implementing the Scroll-driven animations spec in WebKit ([bug 222295](https://bugs.webkit.org/show_bug.cgi?id=222295)). Working on the [`scroll-timeline` shorthand](https://drafts.csswg.org/scroll-animations-1/#scroll-timeline-shorthand) I came across these two tests which I'm puzzled by:

https://github.com/web-platform-tests/wpt/blob/b8302fc4707a4e65e1950954b10a66380134ccac/scroll-animations/css/scroll-timeline-shorthand.html#L100-L108

I'm looking at the spec on [Coordinating List-Valued Properties](https://drafts.csswg.org/css-values-4/#linked-properties) and it's not clear to me what dictates this. I expected the following:

- `--a inline, --b inline, --c inline` for the former where `inline` is repeated for the third entry without an explicit `scroll-timeline-axis` 
- `--a inline, --b inline` for the latter where the `scroll-timeline-axis` list is truncated to match the length of `scroll-timeline-name`

I see both Chrome and Firefox have the same behavior there so I expect I am in error, but would like to understand why.

Assigning to @BorisChiou since he is the author of that test in https://hg.mozilla.org/mozilla-central/rev/4cd86d3d1bb7.

**Comment by graouts** [comment]
Oh, actually Firefox does not implement the `scroll-timeline` properties (at least not without a flag) so the test passes by virtue of the property not being known, so maybe Firefox and Chrome disagree there.

**Comment by BorisChiou** [comment]
When writing this test, I expect `scroll-timeline-name` is the [**coordinating list base property**](https://drafts.csswg.org/css-values-4/#coordinating-list-base-property), per [spec](https://drafts.csswg.org/scroll-animations-1/#scroll-timelines-named).

Therefore, for the 1st example:
```
test_shorthand_contraction('scroll-timeline', { 
   'scroll-timeline-name': '--a, --b, --c', 
   'scroll-timeline-axis': 'inline, inline', 
 }, ''); 
```
Per spec, if a [coordinating list property](https://drafts.csswg.org/css-values-4/#coordinating-list-property) has too few values specified, its value list is repeated to add more [used values](https://drafts.csswg.org/css-cascade-5/#used-value).
-> So the result is `--a inline, --b inline, --c inline`, where `inline` is repeated for the third entry.

And the second example:
```
test_shorthand_contraction('scroll-timeline', { 
   'scroll-timeline-name': '--a, --b', 
   'scroll-timeline-axis': 'inline, inline, inline', 
 }, ''); 
```
Per spec, If a [coordinating list property](https://drafts.csswg.org/css-values-4/#coordinating-list-property) has too many values specified, excess values at the end of its list are not [used](https://drafts.csswg.org/css-cascade-5/#used-value).
-> So the result skip the 3rd `inline`.

**Comment by BorisChiou** [comment]
So, looks like there are something wrong on Firefox. Your comment should be what I expected.

**Comment by BorisChiou** [comment]
I notice the test was updated by `<dashed-ident>`. Firefox doesn't work well on this new ident type I guess.

**Comment by graouts** [comment]
OK, in that case I'll make a PR to update the expected value for these tests shortly.

**Comment by graouts** [comment]
This is being addressed in the WebKit project by https://github.com/WebKit/WebKit/pull/20898. Once that PR is reviewed, the change will be automatically upstreamed into the WPT repository with https://github.com/web-platform-tests/wpt/pull/43354.

**Comment by graouts** [comment]
This got fixed by https://github.com/web-platform-tests/wpt/commit/8008a70373f8c3febe2cc7e994115f387b5b651e.
