### ISSUE TITLE
Need a method to keep test metadata in sync with test when subtests are deleted or renamed.

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#43499]
When a subtest is deleted or renamed, the existence of the old subtest name in test metadata won't have an impact on the test result. The test could continue to pass and leave the test metadata out of sync with the tests.

We need a mechanism to properly trigger a test metadata update when a subtest name is deleted or changed.

**Comment by WeizhongX** [comment]
@jgraham do you have any suggestion on this? Thanks!

**Comment by gsnedders** [comment]
Is there not already a cron job on the metadata repo that tries to do this?

**Comment by WeizhongX** [comment]
Thanks for sharing the info, Sam! But I don't see how that is related, so do you mind elaborate a little bit? (Assume you meant https://github.com/web-platform-tests/wpt-metadata)

When I say test metadata, I mean .ini files. Currently if we have a non-existent subtest in test metadata, it won't cause any problem. But from engineering point of view, we want always keep the test metadata in sync with the test itself.

**Comment by WeizhongX** [comment]
Discussed this on last core meeting, and copied some of the important discussions below.

jgraham@ mentioned below:
1. not every config is guaranteed to run the same subtests. (on mobile might not see subtests that is running on desktop).
2. At gecko side when we import new tests, we run every tests on every configuration we have. Then the metadata update has a full flag that will delete orphan metdata  automically.
3. We don't require anything from developers. We don't store metadata if the tests passes everywhere. Since the default is PASS. When we do the INI update, we record the subtests that we see anywhere. Only update if there was an unexpected result. If a developer renames a test, could temporarily leave orphan metadata.

@jonathan-j-lee

**Comment by WeizhongX** [comment]
To rely on the importer to clean up stale data, I feel there might be a timing issue. The importer could be failing for several days. Even though keeping those stale data won't hurt anything, it would at least be confusing, and could waste engineering time unnecesarily.

**Comment by WeizhongX** [comment]
Our plan is to make such tests a failure on chromium's CI and then an update will be automatically triggered. No change in Wptrunner is needed.
