### ISSUE TITLE
[css-transitions] test for the `transition` shorthand assumes that all longhands are always serialized except for `transition-behavior`

### ISSUE THREAD

**Issue by graouts** [web-platform-tests/wpt#43574]
If you look at this test:

https://github.com/web-platform-tests/wpt/blob/c0ee9676e9c41a12d697e7ca2ee89287b59baa9e/css/css-transitions/parsing/transition-behavior.html#L16

You'll notice that it is expected that the `transition` shorthand serializes all longhand values, including those set to initial values. I was under the impression, although I don't have spec references handy, that serialization of shorthand would always try to yield the shortest value.

Interestingly, the new `transition-behavior` property seems to not follow the same rule, for instance:

https://github.com/web-platform-tests/wpt/blob/c0ee9676e9c41a12d697e7ca2ee89287b59baa9e/css/css-transitions/parsing/transition-behavior.html#L51-L53

Notice here that `transition-behavior` is only serialized in the `transition` shorthand when the non-initial value `allow-discrete` is specified.

What are the specs mandating this?

**Comment by graouts** [comment]
Cc @josepharhar who authored this test and @fantasai who I discussed this with previously.

**Comment by fantasai** [comment]
Afaict the only spec that applies here is https://drafts.csswg.org/cssom/#serializing-css-values as neither css-transitions-1 nor css-transitions-2 define any special serialization rules that I can find.

**Comment by nt1m** [comment]
Yeah I think the test is wrong and the shortest serialization rule is expected here. cc @emilio @BorisChiou

**Comment by emilio** [comment]
I agree. Assuming transition-behavior doesn't introduce ambiguities (which it shouldn't) I'd expect shortest serialization.

**Comment by graouts** [comment]
And this applies to both the specified value and the computed value, correct? If so, I'll file a patch tomorrow.

**Comment by nt1m** [comment]
Yeah I think so, I filed this bug to fix it in WebKit: https://bugs.webkit.org/show_bug.cgi?id=266234

**Comment by josepharhar** [comment]
I feel like there was some reason I did this, but looking through the [code review](https://chromium-review.googlesource.com/c/chromium/src/+/4679218) I didn't see anything obvious.

I have no issues changing the behavior in chrome. If @dbaron is ok with the proposed change I will implement it in chrome as well.

Thanks for looking at the tests and opening this issue!

**Comment by graouts** [comment]
Fixing in https://github.com/web-platform-tests/wpt/pull/43626.

**Comment by dbaron** [comment]
Yes, I think fixing the Chrome serialization to prefer shortest serialization sounds good, at least as long as at least one of WebKit or Gecko has been doing that all along.

**Comment by nt1m** [comment]
Closing as the WPTs have been changed. WebKit has newly adopted shortest serialization.

**Comment by dholbert** [comment]
@josepharhar hi! just checking in, is this still on your radar to implement for Chromium?

The following testcase shows that Chrome 126dev (on my system) still includes the trailing `0s` for `transition-delay` when serializing the computed style for `transition`, but Firefox & WebKit exclude it (which I think is correct per this issue).
```html
<!DOCTYPE html>
<style>
  #foo {
    transition: transform 1s linear 0s
}
</style>
<script>
  function report() {
    alert(getComputedStyle(foo).transition);
  }
</script>
<a id="foo" onclick="report()" href="#">
  Click me to show my serialized value for 'transition'
</a>
```
Live version: https://www.software.hixie.ch/utilities/js/live-dom-viewer/saved/12680

**Comment by dholbert** [comment]
I'm asking because we happened to just triage a bug report where a site happens to be depending on the behavior that Chrome still implements (for no particular reason), so it happens to work in Chrome right now, but the site a bit broken in Firefox/Safari. Details in https://github.com/webcompat/web-bugs/issues/136217

That's the only report I've seen since Firefox changed behavior and stopped serializing the `transition-duration` several months ago, so I suspect it's not indicative of a broader trend.  We should of course get this site fixed, but that's more likely to be effective if Chrome's also shipping the new behavior.

**Comment by dholbert** [comment]
> Yes, I think fixing the Chrome serialization to prefer shortest serialization sounds good, at least as long as at least one of WebKit or Gecko has been doing that all along.

To be clear, though, we aren't actually in the world where dbaron's "...at least..." requirement is satisfied. No browser has been doing this all along.

Specifically, looking at the alert()'ed transition serialization in my above-linked/quoted hixie.ch-hosted testcase:
* Safari 17.4.1 (Safari's current release version on macOS Sonoma) serializes `0s` at the end (for `transition-delay`).
* Firefox up through version 123 also serialized `0s` at the end.

But Firefox 124 and newer [current release is 125] and Safari Tech Preview both omit the `0s`.

So far we've only found one site that has a fragile dependency on the old serialization behavior and breaks as a result of the change, described in https://github.com/webcompat/web-bugs/issues/136217 .  I'm not sure whether Safari Tech Preview has run across any similar breakage (or when the change is slated to hit their release version).

**Comment by josepharhar** [comment]
I am implementing the behavior based on the webkit patch and WPT here: https://chromium-review.googlesource.com/c/chromium/src/+/5532568

I'll post back here if there are compat issues, but it will take a while for it to get released to stable for me to find out.
