### ISSUE TITLE
Request to Add @anonrig and @lemire as Collaborators to WPT Project

### ISSUE THREAD

**Issue by nomadtechie** [web-platform-tests/wpt#43580]
Hello folks, 

I'd like to request that we add @anonrig and @lemire as collaborators to the Web Platform Tests (WPT) project. Both individuals are  Node.js collaborators, while Yagiz is also a member of the Node.js Technical Steering committee. They are also co-authors, and maintainers of the widely used Ada URL parser project (https://github.com/ada-url/ada). Ada is a WHATWG spec-compliant URL parser that is not only utilized in Node.js but also adaptable for non-JavaScript server runtimes such as Rust and Python, for example https://github.com/ada-url/ada-python and https://github.com/ada-url/rust.

Yagiz and Daniel currently maintain an automated workflow for pulling in relevant WPT tests into the Ada project, see a recent upstream merge example [here](https://github.com/ada-url/ada/pull/565).

Both contributors have not only identified and reported bugs in existing tests but have also made substantial contributions to the Web Platform Tests repository. An exemplary contribution includes [additional tests](https://github.com/web-platform-tests/wpt/pull/38658) and fixes for issues within pre-existing tests, all stemming from their work on the Ada project.

Adding them as contributors to WPT formally would be a great step towards furthering more initiatives like Ada which enable interoperability and spec compliance for NodeJS, as Ada is now one of the consumers for WPT. 

I spoke with @zcorpan about this offline on Nov 30th 2023, and he said next steps would be to file a public issue. 😃 

Looking forward to seeing them both added as official contributors to this incredible project.

Best, 
Amal Hussein

**Comment by zcorpan** [comment]
SGTM, I can invite them to the reviewers team. Thanks, and welcome!

fyi @web-platform-tests/admins

**Comment by zcorpan** [comment]
Done, https://github.com/orgs/web-platform-tests/teams/reviewers

@anonrig, @lemire, you need to accept the invitation to the org.

**Comment by anonrig** [comment]
Thank you @zcorpan. Accepted the invitation.

**Comment by nomadtechie** [comment]
Wooohoo! Awesome - thanks for your help on this, Simon! Welcome and good luck, Daniel and Yagzi!!! 🥳

**Comment by lemire** [comment]
Thanks.
