### ISSUE TITLE
Stable runs for Safari are invalid since December 5th, 2023

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt#43695]
I believe people are already aware of this, but just for bookkeeping, [Safari stable runs are missing since Dec 5th](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari). The runs are being marked as invalid with the error: `Conflicting 'version: [OS X 13.6, OS X 13.6.1], os_build: [22G120, 22G313]' found in the merged report`. [See the "Invalid Runs tab here](https://wpt.fyi/status).

CC @gsnedders

**Comment by gsnedders** [comment]
Yeah, I was meaning on filing an issue on this earlier.

I do wonder if we're being overly strict there—we do after all run `sudo apt-get -qqy update && sudo gdebi -qn /tmp/google-chrome-unstable_current_amd64.deb` and similar for Chrome on Taskcluster which will install all (currently uninstalled) dependencies with their latest version, not necessarily giving identical versions across all shards. If we had some identifier for Chrome encompassing all package versions, like the macOS build version does, we'd have the same problem there.

Maybe we should just rely on browser version being the same?

**Comment by past** [comment]
https://github.com/web-platform-tests/wpt/issues/20613 is related and also https://github.com/web-platform-tests/wpt/issues/32608#issuecomment-1029941241.

**Comment by past** [comment]
i have a tentative [PR](https://github.com/web-platform-tests/wpt.fyi/pull/3636) to ignore the conflicting fields in the results processor if we decide to go that route.

**Comment by past** [comment]
Fixed by https://github.com/web-platform-tests/wpt.fyi/pull/3636.
