### ISSUE TITLE
mojojs.zip from chrome-wpt-mojom GS bucket is missing files

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#43875]
The mojojs.zip file served from the chrome-wpt-mojom bucket seems to differ from the one exported to the chromium-browser-snapshots bucket. https://storage.googleapis.com/chrome-wpt-mojom/122.0.6233.0/linux64/mojojs.zip, for example, is missing several files that have been added to `linux-archive-rel.json` in the past year (https://source.chromium.org/chromium/chromium/src/+/71a201a754dc885d2e2d595a612045feac69163a landed 10 months ago and its files are still absent, for example).

Comparing the contents of https://storage.googleapis.com/chrome-wpt-mojom/122.0.6233.0/linux64/mojojs.zip and https://storage.cloud.google.com/chromium-browser-snapshots/Linux_x64/1206981/mojojs.zip (1206981 is what https://storage.googleapis.com/wpt-versions/pinned_chromium_revision returns):

```diff
--- mojojs.txt	2024-01-08 11:08:42.496244273 +0100
+++ Linux_x64_1206981_mojojs.txt	2024-01-08 11:33:15.281430375 +0100
@@ -40,7 +40,11 @@
 mojojs/gen/mojo/public/mojom/base/uuid.mojom.m.js
 mojojs/gen/mojo/public/mojom/base/values.mojom.m.js
 mojojs/gen/mojo/public/mojom/base/version.mojom.m.js
+mojojs/gen/services/device/public/mojom/battery_monitor.mojom.m.js
+mojojs/gen/services/device/public/mojom/battery_status.mojom.m.js
 mojojs/gen/services/device/public/mojom/nfc.mojom.m.js
+mojojs/gen/services/device/public/mojom/pressure_manager.mojom.m.js
+mojojs/gen/services/device/public/mojom/pressure_update.mojom.m.js
 mojojs/gen/services/device/public/mojom/sensor.mojom.m.js
 mojojs/gen/services/device/public/mojom/sensor_provider.mojom.m.js
 mojojs/gen/services/device/public/mojom/serial.mojom.m.js
@@ -59,6 +63,7 @@
 mojojs/gen/third_party/blink/public/mojom/contacts/contacts_manager.mojom.m.js
 mojojs/gen/third_party/blink/public/mojom/content_index/content_index.mojom.m.js
 mojojs/gen/third_party/blink/public/mojom/idle/idle_manager.mojom.m.js
+mojojs/gen/third_party/blink/public/mojom/sensor/web_sensor_provider.mojom.m.js
 mojojs/gen/third_party/blink/public/mojom/serial/serial.mojom.m.js
 mojojs/gen/third_party/blink/public/mojom/sms/webotp_service.mojom.m.js
 mojojs/gen/third_party/blink/public/mojom/usb/web_usb_service.mojom.m.js
@@ -88,6 +93,7 @@
 mojojs/gen/ui/gfx/mojom/selection_bound.mojom.m.js
 mojojs/gen/ui/gfx/mojom/swap_result.mojom.m.js
 mojojs/gen/ui/gfx/mojom/swap_timings.mojom.m.js
+mojojs/gen/ui/gfx/mojom/traits_test_service.mojom.m.js
 mojojs/gen/ui/gfx/mojom/transform.mojom.m.js
 mojojs/gen/url/mojom/origin.mojom.m.js
 mojojs/gen/url/mojom/url.mojom.m.js
```

I couldn't find any file in Chromim Code Search that seems to upload archives to the chrome-wpt-mojom bucket, so I am assuming this is something that needs to be handled internally at Google.

**Comment by WeizhongX** [comment]
Did a search and find "wptdashboard/config.pbtxt" referenced chrome-wpt-mojom but was not sure what it actually does. Add @KyleJu as he recently made change to that file.

In `tools/wpt/browser.py` there is a function `_get_base_revision_from_version`. If we can get the correct revision from this function, we can then construct the url "https://storage.cloud.google.com/chromium-browser-snapshots/Linux_x64/<revision>/mojojs.zip" and get mojojs.zip for that version. `_get_base_revision_from_version` depends on omahaproxy, and seems that does not work now. Got error below when I tried the url:

"""
*** Service Permanently Offline ***

OmahaProxy has been turned down.
Please migrate to <https://chromiumdash.appspot.com>.
"""

(We do not need do this if we already have a way to automatically update https://storage.googleapis.com/chrome-wpt-mojom/<version>/linux64/mojojs.zip.)

**Comment by rakuco** [comment]
> (We do not need do this if we already have a way to automatically update https://storage.googleapis.com/chrome-wpt-mojom//linux64/mojojs.zip.)

Yeah, I thought of just making the code always use the chromium-browser-snapshots version, but I lack enough context for that decision. It's not clear why there's a separate chrome-wpt-mojom bucket and who currently maintains it (the commit adding it was created by Robert Ma, who's no longer at Google), and whether it's just a matter of making it include the missing files.

**Comment by past** [comment]
The  `chrome-wpt-mojom` bucket is regularly updated with the pretty simple job from [release-mojojs](https://github.com/Ecosystem-Infra/release-mojojs). I looked at the logs of the job and I don't see anything out of the ordinary. All invocations seem to complete successfully. I suspect that something might have changed in the Chrome CI infra that generates mojojs.zip or that something needs updating there.

**Comment by past** [comment]
I filed a ticket with the Chrome build infra team to investigate.

**Comment by past** [comment]
I landed a change to the internal Chrome infra that should fix this after the next Chrome build is released.

**Comment by rakuco** [comment]
I can confirm that https://storage.googleapis.com/chrome-wpt-mojom/123.0.6280.0/linux64/mojojs.zip contains the files in `services/device` and `third_party/blink` that were missing in the bug report.

The latest Chromium release seems to be 123.0.6280.1, but there doesn't a mojojs.zip for this release (yet?).

**Comment by rakuco** [comment]
> The latest Chromium release seems to be 123.0.6280.1, but there doesn't a mojojs.zip for this release (yet?).

Hmm, this only happened in a single run, https://googlechromelabs.github.io/chrome-for-testing/ does show that 123.0.6281.0 is the latest canary, so I think it's all fine. Thanks for fixing this!
