### ISSUE TITLE
Upgrade the Azure Pipelines VMs for macOS 14 (Sonoma)? Test failures caused by older OS.

### ISSUE THREAD

**Issue by svgeesus** [web-platform-tests/wpt#43940]
It has been reported that a specific PNG WPT is passing in Safari when run locally, but is failing for Safari on wpt.fyi

 https://wpt.fyi/results/png/cicp-chunk.html?label=experimental&label=master&aligned

This test is verifying that a Display P3 PNG image, labelled with Coding Independent Code Points (CICP) not an ICC profile, is decoded into Canvas 2D context in the correct colorspace. It is passed by Chrome (and Edge), and correctly fails on Firefox because they have not finished implementing CICP support.

It turns out that Safari is relying on platform support for CICP, and that this was added with macOS 14 (Sonoma), released [Sept 2023](https://en.wikipedia.org/wiki/MacOS_Sonoma). The WPT Azure pipeline is running macOS 13.6 (Ventura), also released [Sept 2023](https://en.wikipedia.org/wiki/MacOS_Ventura).

Has upgrading the VM image to macOS 14 been considered, or tested? If so did it work smoothly or were there issues? I'm aware there have been issues in the past such as

 - https://github.com/web-platform-tests/wpt/issues/21751

If there are no known problems, it would be great to see the VM upgraded. Safari seems to lean on native OS capabilities a fair bit (for example with text processing and glyph shaping) so there could well be other apparent test failures for Safari, caused by running on the older OS.

@foolip @gsnedders 

PNG-specific discussion at

 - https://github.com/w3c/PNG-spec/issues/312
 
 Display P3-related @jensimmons 
 
  - https://github.com/web-platform-tests/interop/issues/559

**Comment by svgeesus** [comment]
If I am reading [this list of available Azure images](https://github.com/actions/runner-images) correctly, depends on

 - https://github.com/actions/runner-images/issues/7508

and the previous (Ventura) image was not made available until 6 months after full release:

 - https://github.com/actions/runner-images/issues/6426

**Comment by foolip** [comment]
Looks like Azure Pipelines doesn't have macOS 14 yet:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

But I've sent https://github.com/web-platform-tests/wpt/pull/43944 to see if maybe it works anyway.

**Comment by svgeesus** [comment]
Thanks for checking, @foolip that was also what [I concluded](https://github.com/web-platform-tests/wpt/issues/43940#issuecomment-1887167222). Seems it might be a few months until Azure rolls out macOS 14.

I guess I will update this issue if I hear that they have done so.

**Comment by foolip** [comment]
Still no macOS 14 on Azure Pipelines however:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

https://github.com/web-platform-tests/wpt/pull/43944 still fails, so it's also not secretly supported without being documented, unfortunately.
