### ISSUE TITLE
webdriver/tests/bidi/browsing_context/traverse_history tests are flaky

### ISSUE THREAD

**Issue by OrKoN** [web-platform-tests/wpt#44062]
See a chrome-stability run for test run details https://github.com/web-platform-tests/wpt/pull/44046/checks?check_run_id=20579005479

The spec currently does not require implementations to wait for navigations to complete: https://w3c.github.io/webdriver-bidi/#command-browsingContext-traverseHistory

The tests currently do not seem to reflect that and expect the URL change as soon as the traverseHistory command is over https://github.com/web-platform-tests/wpt/blob/master/webdriver/tests/bidi/browsing_context/traverse_history/delta.py#L40

I think we could improve the test by either waiting for the URL to change or by waiting for some event that indicates that.

cc @sadym-chromium @whimboo

**Comment by whimboo** [comment]
Yes, that came also up on our side on https://bugzilla.mozilla.org/show_bug.cgi?id=1867779. Sadly we haven't had the time to fix this racy test. The suggestion sounds good.

**Comment by whimboo** [comment]
Fixed by https://github.com/web-platform-tests/wpt/pull/44286.

@OrKoN can you please check if that all works for you now as well?

**Comment by OrKoN** [comment]
@whimboo it looks like the stability check has timed out on that PR. Let's monitor it over time.

**Comment by whimboo** [comment]
> @whimboo it looks like the stability check has timed out on that PR. Let's monitor it over time.

That most likely happened because it tried to run all the WebDriver tests due to the fixture change.
