### ISSUE TITLE
Missing Firefox stable runs since January 23

### ISSUE THREAD

**Issue by past** [web-platform-tests/wpt#44366]
There haven't been any Firefox stable runs [since January 23](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari). No invalid runs in https://wpt.fyi/status, but I haven't had time to look any further yet.

/cc @jgraham

**Comment by jgraham** [comment]
It seems to be https://bugzilla.mozilla.org/show_bug.cgi?id=1877744

I did a trigger run without the websockets tests and the run completed.

**Comment by past** [comment]
@jgraham are you going to request for an uplift of the fix or should we expect to not have Firefox runs until 124 ships?

**Comment by jgraham** [comment]
Hmm, I was on PTO and I think we've missed the window to get this into 123 (it feels hard to justify putting it in a dot release) :/

**Comment by past** [comment]
Firefox results are back as of yesterday with version 124.
