### ISSUE TITLE
chrome-wpt-mojom mojojs.zip files should be published together with browser releases

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#44438]
This is a follow-up to #43875, which fixed the more general problem of the mojojs.zip file not containing the right files.

The fix for the bug above should have made the compute-pressure/ tests start passing on Chrome Canary in wpt.fyi, but the results are varying:
- Sometimes everything passes, as in https://wpt.fyi/results/compute-pressure?run_id=5116280230641664
- Sometimes the tests time out due to a harness error, as in https://wpt.fyi/results/compute-pressure/compute_pressure_basic.tentative.https.any.html?sha=9afbc09f4e&label=master&max-count=1&product=chrome%5Bexperimental%5D. This is different from the errors caused by #43875, which produced different error messages (and no timeouts) due to missing files.

As far as I can see, this seems to be caused by the fact that it seems to take a while for the mojojs.zip corresponding to a new Chrome for Testing release to be published in the chrome-wpt-mojom GS bucket.

I can reproduce this locally, for example, if I run `./wpt run --install-browser -y chrome compute-pressure/compute_pressure_basic.tentative.https.any.html`:
- The latest canary at the time of writing is 123.0.6286.0, so `wpt run` downloads https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/123.0.6286.0/linux64/chrome-linux64.zip.
- There's no mojojs.zip for 123.0.6286.0 in the chrome-wpt-mojom GS bucket, so `wpt run` falls back to downloading the mojojs.zip file from chromium-browser-snapshots whose version corresponds to [`_get_pinned_chromium_revision()`](https://github.com/web-platform-tests/wpt/blob/aee2a77919002424ba9ef9c302d0716ceff81ea2/tools/wpt/browser.py#L605), which is from October 2023.
- The Mojo interfaces have changed since then, leading to communication errors (the "Received unknown message" harness message from above).

I think this is bound to continue happening until the CfT release process also includes mojojs.zip, or the latter's publication is made to happen more quickly (reducing the window during which this can happen).

**Comment by past** [comment]
@mathiasbynens do you have any advice on how to proceed here? Can the CfT release also include mojojs.zip?

**Comment by mathiasbynens** [comment]
> @mathiasbynens do you have any advice on how to proceed here? Can the CfT release also include mojojs.zip?

I’ve filed https://crbug.com/324452573 for this.

**Comment by mathiasbynens** [comment]
Closing the loop here now that https://crbug.com/324452573 has been addressed — **`mojojs.zip` is available for every CfT release from now on**, starting with `123.0.6309.0`! 🥳 

I’ve created a patch documenting this here: https://chromium-review.googlesource.com/c/chromium/src/+/5307634 I’ll inline the relevant section below.

------------------

## Downloads

As of Chrome 123.0.6309.0, prebuilt MojoJS archives are available for download
via
[Chrome for Testing (CfT) infrastructure](https://developer.chrome.com/blog/chrome-for-testing).
For every user-facing Chrome release, a correspondingly-versioned ZIP file
containing the relevant MojoJS bindings can be downloaded at the following URL:

```
https://storage.googleapis.com/chrome-for-testing-public/123.0.6309.0/mojojs.zip
```

Replace `123.0.6309.0` with the exact Chrome version you need. Any version in
[CfT’s `known-good-versions.json`](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json)
greater than or equal to 123.0.6309.0 is guaranteed to have a corresponding
`mojojs.zip` download available.

------------------

This should enable you to simplify `tools/wpt/browser.py` accordingly, which should also resolve this version mismatch problem altogether. Let me know if I can help any further.
