### ISSUE TITLE
Running SSL tests is undocumented

### ISSUE THREAD

**Issue by jakearchibald** [web-platform-tests/wpt#4514]
It doesn't seem to be documented that an SSL server runs, or how it should/could be customised with `config.json`.

**Comment by gsnedders** [comment]
Yeah, huge amounts of "how to run these tests" is basically undocumented. :\

**Comment by foolip** [comment]
Is this about how to run tests that require HTTPS? @jakearchibald do you remember what you were trying to do? Seems like just `wpt run` like for all tests is the answer.

**Comment by jakearchibald** [comment]
The docs seem to have improved since I filed this. Seems pretty straight-forward now.
