### ISSUE TITLE
Test type detection code and document does not match

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#45268]
In the document (https://web-platform-tests.org/writing-tests/file-names.html) it says:
[1] (for test type)These flags must be the last element in the filename before the extension e.g. foo-manual.html will indicate a manual test, but foo-manual-other.html will not.
[2] (for test feature) These flags are preceded by a . in the filename, and must themselves precede any test type flag, but are otherwise unordered.

So according to this, for a manual tentative test, we should write ".tentative-manual.html", but we have plenty of tests named in the reverse order, e.g. "permissions-policy/experimental-features/vertical-scroll-main-frame-manual.tentative.html", "payment-method-basic-card/empty-data-manual.https.html".

In the code [3], it basically only fetch the type flag from the first component after "-".
https://github.com/web-platform-tests/wpt/blob/88149528a94fdf769c29e129f8979859e39c339c/tools/manifest/sourcefile.py#L207-L208

**Comment by WeizhongX** [comment]
Despite what the document says, looks like the common pattern ppl are using is "-<type flag>(.<any feature flag>)*.html", maybe because it will be more eye pleasing to put "-" always before ".", e.g. "vertical-scroll-main-frame-manual.tentative.html" is better than "vertical-scroll-main-frame.tentative-manual.html".

Should we update the document to accept this common practice?

**Comment by WeizhongX** [comment]
@jgraham WDYT?

**Comment by gsnedders** [comment]
This changed in https://github.com/web-platform-tests/wpt/commit/cb4fb70522058f8a828b6e7ce2f3a27305c3ead6; https://github.com/w3c/wpt-tools/issues/123 / https://github.com/w3c/wpt-tools/pull/124.

IMO, given it's been the behaviour for well over seven years, we should just change the docs.

**Comment by WeizhongX** [comment]
Thanks, uploaded https://github.com/web-platform-tests/wpt/pull/45696

**Comment by past** [comment]
@WeizhongX anything left to do here?

**Comment by WeizhongX** [comment]
> @WeizhongX anything left to do here?

No, and closed
