### ISSUE TITLE
geolocation-API: Cross-origin URL used in Permissions Policy tests is wrong

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#45379]
Tests such as `geolocation-API/enabled-by-permissions-policy.https.sub.html` are doing something like [this](https://github.com/web-platform-tests/wpt/blob/25fdec3c95e308d6c844022fedd2fcbb6b2b5703/geolocation-API/disabled-by-permissions-policy.https.sub.html#L14):

```js
    const cross_origin_src =
      "https://{{hosts[][]}}:{{ports[https][0]}}" + same_origin_src;
```

which basically evaluates to the same origin used in same-origin tests, "https://web-platform.test:8443".

**Comment by reillyeon** [comment]
I started looking at this but found a broader systemic issue with how these tests are running on the Chromium CI: https://crbug.com/331556923

I haven't tried running this with the upstream WPT runner.
