### ISSUE TITLE
geolocation-API: Cross-origin permissions policy tests need to set the "allow" attribute

### ISSUE THREAD

**Issue by rakuco** [web-platform-tests/wpt#45380]
Back in the Feature Policy days, one could set either the HTTP header or the "allow" attribute to get cross-origin access to work. With Permissions Policy, setting only the HTTP header is not enough and one needs to set the "allow" attribute as well (see https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md#header-and-allow-attribute-combine-differently).

In the Geolocation API tests, there are cross-origin tests like [this one](https://github.com/web-platform-tests/wpt/blob/25fdec3c95e308d6c844022fedd2fcbb6b2b5703/geolocation-API/enabled-by-permissions-policy.https.sub.html#L36) where the HTTP header is set to `*` but no "allow" attribute is set in the iframe, causing the test to still fail.

**Comment by reillyeon** [comment]
I started looking at this but found a broader systemic issue with how these tests are running on the Chromium CI: https://crbug.com/331556923

I haven't tried running this with the upstream WPT runner.

**Comment by marcoscaceres** [comment]
>  setting only the HTTP header is not enough and one needs to set the "allow" attribute as well

That... doesn't sound right? That seems like a foot gun. 

@clelland is that correct?

**Comment by marcoscaceres** [comment]
Wait, apologies, @rakuco...  I think I misread. Setting the allow attribute on the iframe makes sense. 

Setting the HTTP header only applies to the top level document, which makes perfect sense... it should inherit down to cross origin frames.
