### ISSUE TITLE
Firefox Android runs missing since April 3

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#45635]
Firefox Android runs have been missing [since April 3](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome_android&product=firefox_android&product=chrome_ios). Could you take a look @jgraham? Thanks!

**Comment by DanielRyanSmith** [comment]
We are now receiving intermittent results as of April 9th, so I think this is safe to close. 🙂
