### ISSUE TITLE
Numerous CSS tests are incorrectly marked as failing in Edge due to Ahem anti-aliasing on Windows

### ISSUE THREAD

**Issue by KurtCattiSchmidt** [web-platform-tests/wpt#45750]
Here is one example: https://wpt.fyi/results/css/css-overflow/scrollbar-gutter-dynamic-001.html?label=experimental&label=master&aligned&view=interop&q=label%3Ainterop-2024-scrollbar

...but there are many others:

[wpt /css/css-fonts](https://wpt.fyi/results/css/css-fonts?label=master&label=experimental&aligned&view=interop&q=label%3Ainterop-2024-font-size-adjust%20and%20chrome%3Apass%20and%20edge%3A%21pass)
: 3 tests

[wpt /css/css-grid/](https://wpt.fyi/results/css/css-grid?label=master&label=experimental&aligned&view=interop&q=%28label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2023-grid%20or%20label%3Ainterop-2022-subgrid%29%20%20and%20edge%3A%21pass%20and%20chrome%3Apass)
: 72 tests

[wpt /css/css-flexbox](https://wpt.fyi/results/css/css-flexbox?label=master&label=experimental&aligned&view=interop&q=%28label%3Ainterop-2021-flexbox%20or%20label%3Ainterop-2023-flexbox%20or%20label%3Ainterop-2021-grid%20or%20label%3Ainterop-2023-grid%20or%20label%3Ainterop-2022-subgrid%29%20%20and%20edge%3A%21pass%20and%20chrome%3Apass)
: 7 out of 9 failing tests

Total: ~84 interop-2024 tests - this number is probably much larger for all WPT tests.

These all pass locally in Edge and Chrome in Chromium's test harness, but are failing in the WPT test harness on Windows in both Edge and Chrome. Chrome is marked as a "Pass" in wpt.fyi since WPT published results are on Linux, which doesn't exhibit this behavior. 

I have narrowed the behavior in Chromium down to these lines:

```
    if (SystemParametersInfo(SPI_GETFONTSMOOTHING, 0, &enabled, 0) && enabled) {
      params_->antialiasing = true; // Removing this line gets the WPT runner to pass!
      params_->subpixel_positioning = true;
```

https://source.chromium.org/chromium/chromium/src/+/main:ui/gfx/font_render_params_win.cc;drc=aa4c079615ddd4eaa6113a13465d9819f0799d42;l=79

Since `SPI_GETFONTSMOOTHING` is on by default on Windows, users will get anti-aliasing, which is how the browser should behave. This behavior shouldn't change for customers, but I do think it's important to get accurate results for these tests.

I can think of a few solutions to this, but I'm not sure which is ideal. I'm happy to make changes in either Chromium/Skia (I have worked in this area before), or in WPT.

Here's what I have off the top of my head:

1) Disable anti-aliasing of the `Ahem` font in Chromium on Windows. This seems a little odd, but it might be an ideal solution, since this font is only used for testing. I would need to get signoff from Chromium font stakeholders, but I'm happy to make this change as well. I put together a rough version that gets these tests to pass in the WPT harness: https://chromium-review.googlesource.com/c/chromium/src/+/5458787. This comment implies that Firefox is already doing something similar: **https://github.com/web-platform-tests/wpt/issues/20058#issuecomment-549135881**

2) Disable anti-aliasing in Chromium behind a runtime flag. There doesn't appear to be a flag for this currently in Chromium. The WPT runner would then need to enable this flag for Chrome/Edge. I'm not very familiar to the WPT runner, but I don't see an option to add runtime parameters on the browsers being tested - perhaps this is intentional, so that results match user's settings?

3) Disable anti-aliasing in Chromium on Windows in headless mode - headless appears to be the default for WPT and wouldn't change behavior for end users, although it might have undesirable side effects for other users of headless mode. This would need signoff from Chromium stakeholders, but it should be fairly straightforward to implement.

...but I'm sure there are quite a few more ways to address this. Any other suggestions are welcome!

**Comment by KurtCattiSchmidt** [comment]
Thanks to @gastonrod for bringing this to my attention! CC @alisonmaher @bfgeek @drott

**Comment by dandclark** [comment]
Thanks @KurtCattiSchmidt!  WebKit has apparently also disabled anti-aliasing for `Ahem`: https://github.com/WebKit/WebKit/commit/605fceae5aa7ab120bd83f3df4c90e4f74a1083d. So I think it's reasonable to go with approach (1).

**Comment by drott** [comment]
Can we explore combining 1 and 2 more? Safari still [disables Ahem antialiasing without any flag guard](https://github.com/WebKit/WebKit/blob/38694a9a62607c8f9f4ad897d6c3257b57c2258a/Source/WebCore/platform/graphics/coretext/FontCoreText.cpp#L176). Firefox disables AA as [a combination of a preference setting and a family name match](https://searchfox.org/mozilla-central/source/gfx/thebes/gfxFont.cpp#993).

I would find generally enabling this by family name a surprising effect, I am okay doing a combination of 2 and 1 (like FF): Disabling antialiasing for Ahem, under a flag guard, even if that unfortunately means the WPT runner configuration would have to be adapter. 

@foolip, would you have any pointers as to where the WPT runner launch parameters for Edge on Windows can be configured?

**Comment by KurtCattiSchmidt** [comment]
Thanks @foolip, I will make these changes in WPT once my Chromium CL lands. This does indeed impact Chrome on Windows, so I'll make the change there too.

**Comment by foolip** [comment]
@KurtCattiSchmidt have you been able to see if the fix worked yet?

**Comment by KurtCattiSchmidt** [comment]
> @KurtCattiSchmidt have you been able to see if the fix worked yet?

Yes! I had to wait for the 126 release, which is now in Beta. The individual cases that I've been tracking are now marked as passing in Edge.

@foolip  - is there an easy to determine exactly how many passes are due to this change?
