### ISSUE TITLE
I looked at https://github.com/web-platform-tests/wpt/actions/workflows/epochs.yml and counted the number of workflow runs for "2 days ago, "3 days ago", etc. They were all 8. How often is one run missing?

### ISSUE THREAD

**Issue by BORNEO00** [web-platform-tests/wpt#45768]
I looked at https://github.com/web-platform-tests/wpt/actions/workflows/epochs.yml and counted the number of workflow runs for "2 days ago, "3 days ago", etc. They were all 8. How often is one run missing?

_Originally posted by @foolip in https://github.com/web-platform-tests/wpt/issues/36564#issuecomment-1383688461_

**Comment by BORNEO00** [comment]
Y

**Comment by foxrider598** [comment]
I looked at https://github.com/web-platform-tests/wpt/actions/workflows/epochs.yml and counted the number of workflow runs for "2 days ago, "3 days ago", etc. They were all 8. How often is one run missing?
