### ISSUE TITLE
Do not run tests for PRs still in draft mode

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#46122]
Currently chromium's WPT exporter is exporting PRs in draft mode, and change it to ready until it is ready to land. To not run tests for PRs in draft mode could potentially save a lot of test resources.

In the draft PR below, we can see the tests are actually run.
https://github.com/web-platform-tests/wpt/pull/46111

**Comment by past** [comment]
As discussed in #46124 we decided to pursue a different strategy to reduce resource usage.
