### ISSUE TITLE
Firefox Android runs missing since May 12

### ISSUE THREAD

**Issue by KyleJu** [web-platform-tests/wpt#46273]
Firefox Android runs have been missing [since May 12](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome_android&product=firefox_android&product=chrome_ios). Could you take a look @jgraham? Thanks!

**Comment by whimboo** [comment]
It appears that the Android job has run at least once, as the [latest test results are from June 20th](https://wpt.fyi/results/?label=master&label=experimental&product=firefox_android&product=chrome_android&aligned&view=subtest).

However, it is unclear how frequently these tests are run, as they seem to always be behind. This delay hinders our ability to verify bug fixes and assess whether new test jobs are passing.

**Comment by whimboo** [comment]
Latest run is now from today. So it's probably all fine now and some stuff was broken which got fixed? Closing issue for now but feel free to reopen in case it happens again.

**Comment by whimboo** [comment]
The last job on Firefox Android ([wpt.fyi](https://wpt.fyi/results/?label=master&label=experimental&product=firefox_android&view=subtest)) that was run was on July 29th for: https://github.com/web-platform-tests/wpt/commit/716f5fded5

Since then we are missing test results.

**Comment by whimboo** [comment]
Based on the latest wpt.fyi results the latest run did happen on August 25th. I have no idea if something happened in between now and my last comment from around 2 weeks ago.

**Comment by whimboo** [comment]
We have again missing builds for Android since February 10th:
https://wpt.fyi/results/webdriver/tests?label=master&label=experimental&product=firefox_android&view=subtest

@jgraham could you please take a look?

**Comment by whimboo** [comment]
The current issue with Firefox on Android is tracked in https://github.com/web-platform-tests/wpt/issues/57838.
