### ISSUE TITLE
[python style] gentestutilsunion.py gives the WebKit style checker hiccup

### ISSUE THREAD

**Issue by karlcow** [web-platform-tests/wpt#46508]
While WebKit should ignore these hiccups, It could be good to fix them here too. 
https://github.com/web-platform-tests/wpt/blob/2fba14f69a332fcfbd95abbccc3a3b1633362804/html/canvas/tools/gentestutilsunion.py#L4

**Comment by gsnedders** [comment]
What's the error here?

**Comment by karlcow** [comment]
What a bad bug report. 🤦‍♂️ 

The stylechecker of the WebKit project was complaining about this python script. 

```
% git webkit pr            
From github.com:WebKit/WebKit
 * branch                      main       -> FETCH_HEAD
Current branch 274304-wpt-html-canvas is up to date.
ERROR: Unexpected diff format when parsing a chunk: '100" height="&#xD;'
ERROR: Unexpected diff format when parsing a chunk: '100"><p class="fallback">FAIL (fallback content)</p></canvas>'
ERROR: LayoutTests/imported/w3c/web-platform-tests/html/canvas/tools/gentestutilsunion.py:386:  too many blank lines (2)  [pep8/E303] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/html/canvas/tools/gentestutilsunion.py:484:  continuation line with same indent as next logical line  [pep8/E125] [5]
ERROR: LayoutTests/imported/w3c/web-platform-tests/html/canvas/tools/gentestutilsunion.py:580:  continuation line over-indented for hanging indent  [pep8/E126] [5]
Total errors found: 3 in 1020 files
style-checker failed, continue uploading pull request?
Retry will amend the commit with your changes. (Yes/Retry/[No]): 
```

It has been "fixed" on the WebKit side by stopping worrying about these style issues in 
https://bugs.webkit.org/show_bug.cgi?id=274407
https://github.com/WebKit/WebKit/pull/34427


but so much code has changed in the last couple of months, that might probably be solved by now.  I think we can close.

**Comment by gsnedders** [comment]
It seems unlikely WPT will start enforcing the same code style rules as all other projects consuming us (and I expect between mozilla-central/Chromium/WebKit there are contradictory style rules).
