### ISSUE TITLE
how to handle exceptions thrown in testdriver

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#46624]
There are some exceptions thrown in testdriver-extra.js [1]. As the exceptions are thrown inside the browser, will they cause test to fail

[1] https://source.chromium.org/search?q=f:third_party%2Fwpt_tools%2Fwpt%2Ftools%2Fwptrunner%2Fwptrunner%2Ftestdriver-extra.js%20%22throw%20new%22&ss=chromium%2Fchromium%2Fsrc

**Comment by WeizhongX** [comment]
Background: this is brought up when we discuss a crashtest(html/semantics/popovers/popover-dialog-crash.html) that uses testdriver.js. The crashtest is show as passed on wpt.fyi.

**Comment by WeizhongX** [comment]
@foolip @jgraham

**Comment by WeizhongX** [comment]
Maybe the exception is ignored only when run crashtests, but as we do not care about success or failure for crash tests, this is not a problem?

**Comment by WeizhongX** [comment]
@mfreed7 What is your opinion for my question in the above comment?

**Comment by jgraham** [comment]
Note that crashtests currently aren't allowed to use testdriver and it won't work on the shared infra (unlike in Google's CI).

**Comment by WeizhongX** [comment]
> Note that crashtests currently aren't allowed to use testdriver and it won't work on the shared infra (unlike in Google's CI).

This is true. But I think we should eventually make testdriver work with both reftests and crashtests.
