### ISSUE TITLE
CSS color-contrast() tests are testing the version of color-contrast() remove from the spec

### ISSUE THREAD

**Issue by weinig** [web-platform-tests/wpt#46640]
The CSS color-contrast tests():

css/css-color/color-contrast-001.html
css/css-color/parsing/color-computed-color-contrast-function.html
css/css-color/parsing/color-invalid-color-contrast-function.html
css/css-color/parsing/color-valid-color-contrast-function.html

are testing the version of color-contrast() that is no longer in the spec (with vs.)

@svgeesus @LeaVerou is that syntax coming back? Or should we remove these?

**Comment by LeaVerou** [comment]
They may or may not come back, the syntax of the L6 version is in flux. At the very least we should comment them out. They should definitely not be part of the public testsuite.
