### ISSUE TITLE
[css-transitions] transition-behavior: allow-discrete; work incorrectly in Safari 17.5 and Firefox Nightly with 100% test passing

### ISSUE THREAD

**Issue by alkorlos** [web-platform-tests/wpt#46753]
Recently browsers has been active work on implementing the property `transition-behavior` with the value `allow-discrete`. Six tests have been [written](https://github.com/web-platform-tests/wpt/blob/master/css/css-transitions/transition-behavior.html) for this property, all of which [pass](https://wpt.fyi/results/css/css-transitions/transition-behavior.html?label=master&label=stable&aligned) in stable versions of Chrome and Safari, [as well](https://wpt.fyi/results/css/css-transitions/transition-behavior.html?label=experimental&label=master&aligned) as in Firefox Nightly.

This property allows specifies transitions for discrete properties, with the most obvious example being `display: none;`. Despite achieving 100% test passing, the [example](https://codepen.io/web-dot-dev/pen/poQMLrN) (from [chrome blog](https://developer.chrome.com/blog/entry-exit-animations#the_transition-behavior_property)) for `display: none;` does not work correct in Safari 17.5 and Firefox Nightly. Is it possible that more tests are needed?

**Comment by graouts** [comment]
I filed a [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=275994) to look into this. If it is indeed a bug, a fix _will_ include a WPT test.

**Comment by nt1m** [comment]
Fixed by #46944, this should be fixed in WebKit now too

Fwiw, the example is not working in Firefox, because Firefox doesn't support `display` interpolation which WPT has separate tests for.
