### ISSUE TITLE
Can wpt.fyi indicate results of WebNN API Conformance tests by Chrome and Edge browsers enabled WebNN API flag

### ISSUE THREAD

**Issue by BruceDai** [web-platform-tests/wpt#46807]
Visit https://wpt.fyi/results/webnn/conformance_tests?label=experimental&label=master&aligned, almost WebNN Conformance tests are FAIL since the testing Chrome and Edge browsers didn't enable WebNN API flag.

![image](https://github.com/web-platform-tests/wpt/assets/1531742/c018902a-7f66-4395-8d67-b892e3616b95)

Can `wpt.fyi` indicate results of WebNN API Conformance tests by Chrome and Edge browsers enabled WebNN API flag?

Thanks.

**Comment by jonathan-j-lee** [comment]
I think you want to add `--enable-features=WebMachineLearningNeuralNetwork` to the default `chrome` arguments like so:

https://github.com/web-platform-tests/wpt/blob/8289fd3dd37e19918fceb83c6d2c46c4ced3cbc8/tools/wptrunner/wptrunner/browsers/chrome.py#L115-L117

The wpt.fyi results are running under `--enable-experimental-web-platform-features`, which should enable [`MachineLearningNeuralNetwork` on the Blink side](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/runtime_enabled_features.json5;l=2420;drc=c01d8f45bd2466194ba7a1c6bd6c5a6b02dc71e2;bpv=0;bpt=0), but it seems the browser-side feature also needs to be enabled.

([This document](https://chromium.googlesource.com/chromium/src/+/main/third_party/blink/renderer/platform/RuntimeEnabledFeatures.md#relationship-between-a-chromium-feature-and-a-blink-feature) explains the relationship between Blink-side and browser-side features.)

**Comment by BruceDai** [comment]
Thanks @jonathan-j-lee !
I've submitted a pr #46891 to add this flag.
