### ISSUE TITLE
Safari runs are often missing since June 20th, 2024

### ISSUE THREAD

**Issue by jrobbins** [web-platform-tests/wpt#46899]
There have been no stable Safari runs recorded for the past four days:
https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari

CC @gsnedders

**Comment by DanielRyanSmith** [comment]
It looks like we've received 3 runs since then, but the results are only coming in intermittently.

**Comment by past** [comment]
We've been getting some Safari runs [occasionally](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari). @gsnedders is [working](https://github.com/web-platform-tests/wpt-notes/blob/master/minutes/2024-08-06.md#safari-runs-missing) on it.

**Comment by gsnedders** [comment]
This also applies to STP.

This is effectively a regression from #46737 (migrating to macOS Sonoma), and we're seeing comparable Azure Pipelines issues to what we saw last year after migrating to macOS Ventura (https://github.com/web-platform-tests/wpt/issues/40085).

Downgrading to macOS Ventura isn't an option, as it is no longer supported by Safari Technology Preview.

Given the many-months delay last year for Azure Pipelines to resolve any of this, and the reduction in Azure Pipelines capacity from next month, with ongoing work to migrate away from Azure Pipelines before then, there's likely little we can do except "hit the 'rerun failed builds' button".

**Comment by past** [comment]
Safari runs are now producing results consistently after the migration from Azure Pipelines to GitHub Actions.
