### ISSUE TITLE
Consider removing url test containing utf16 surrogates

### ISSUE THREAD

**Issue by Wuelle** [web-platform-tests/wpt#46941]
`urltestdata.json` contains the following test:
```json
{
    "input": "http://example.com/\uD800\uD801\uDFFE\uDFFF\uFDD0\uFDCF\uFDEF\uFDF0\uFFFE\uFFFF?\uD800\uD801\uDFFE\uDFFF\uFDD0\uFDCF\uFDEF\uFDF0\uFFFE\uFFFF",
    "base": null,
    "href": "http://example.com/%EF%BF%BD%F0%90%9F%BE%EF%BF%BD%EF%B7%90%EF%B7%8F%EF%B7%AF%EF%B7%B0%EF%BF%BE%EF%BF%BF?%EF%BF%BD%F0%90%9F%BE%EF%BF%BD%EF%B7%90%EF%B7%8F%EF%B7%AF%EF%B7%B0%EF%BF%BE%EF%BF%BF",
    "origin": "http://example.com",
    "protocol": "http:",
    "username": "",
    "password": "",
    "host": "example.com",
    "hostname": "example.com",
    "port": "",
    "pathname": "/%EF%BF%BD%F0%90%9F%BE%EF%BF%BD%EF%B7%90%EF%B7%8F%EF%B7%AF%EF%B7%B0%EF%BF%BE%EF%BF%BF",
    "search": "?%EF%BF%BD%F0%90%9F%BE%EF%BF%BD%EF%B7%90%EF%B7%8F%EF%B7%AF%EF%B7%B0%EF%BF%BE%EF%BF%BF",
    "hash": ""
  }
```
The interesting part here is the `\uD801\uDFFE`  - that's a UTF-16 surrogate.

The behaviour in this case is undefined as per the URL specification[^5], where the input to the url parsing algorithm is a scalar value string[^2] (meaning a string containing neither leading nor trailing surrogate characters).

`url/README.md` states:
> `resources/urltestdata.json` contains URL parsing tests suitable for any URL parser implementation.

Therefore, the suite should *only* test behaviour defined in the url specification[^4].

I would like to hear the thoughts of more qualified people on this before I make a PR for it (:

[^1]: https://262.ecma-international.org/6.0/#sec-ecmascript-language-types-string-type
[^2]: https://infra.spec.whatwg.org/#scalar-value-string
[^3]: https://github.com/json5/json5-spec/issues/12
[^4]: https://url.spec.whatwg.org
[^5]:https://url.spec.whatwg.org/#url-parsing

**Comment by 0xg0nz0** [comment]
I reported this issue with nlohmann-json, which breaks on loading this particular test case:

https://github.com/nlohmann/json/issues/4417

I think this test case should be removed. If the JSON file is not loadable by someone strictly validating the Unicode because of it, I am not sure how valuable it is as a test.
