### ISSUE TITLE
Tests are run the last time on 4th of July? 

### ISSUE THREAD

**Issue by Frosne** [web-platform-tests/wpt#47107]
![image](https://github.com/user-attachments/assets/bb4d968f-288b-4ddb-9e90-d1ca40d8f8ef)

**Comment by jgraham** [comment]
@gsnedders @foolip 

We seem to be in a situation where STP runs are very flaky and Firefox nightly runs are slightly flaky and the combination of those two means that we don't have any recent aligned runs for the experimental channel.

**Comment by Frosne** [comment]
It looks like everything is back to normal. 

Thank you so much! Closing the issue.
