### ISSUE TITLE
Chrome stable and experimental runs missing as of August 5th

### ISSUE THREAD

**Issue by DanielRyanSmith** [web-platform-tests/wpt#47544]
No Chrome runs have been detected this week for both [the stable channel](https://wpt.fyi/runs?label=master&label=stable&max-count=100&product=chrome&product=firefox&product=safari) as well as [the experimental channel](https://wpt.fyi/runs?label=master&label=experimental&max-count=100&product=chrome&product=edge&product=firefox&product=safari&product=webkitgtk).

cc @foolip

**Comment by past** [comment]
Fixed in #47589.
