### ISSUE TITLE
wpt.live links to a directory, it should link to a service to run wpt live in your browser

### ISSUE THREAD

**Issue by stubbornella** [web-platform-tests/wpt#47691]
[wpt.live](wpt.live) is mentioned in the readme, but it links to a directory rather than a service.

> [wpt.live](https://wpt.live/): a public deployment of the test suite, allowing anyone to run the tests by visiting from an Internet-enabled browser of their choice

**Comment by jonathan-j-lee** [comment]
Most WPTs are HTML pages served by [wptserve], so you "run" a test by navigating to its file linked from the directory listing (e.g., https://wpt.live/animation-worklet/stateful-animator.https.html).

wpt.live is not as sophisticated as wptserve though, so tests that are generated (#7191) or that depend on an external WebDriver (#40315) are known to be broken in the former.

Tentatively closing as WAI, but feel free to reopen if I've misunderstood the original issue.

[wptserve]: https://web-platform-tests.org/tools/wptserve/docs/index.html
