### ISSUE TITLE
cicp-display-p3.png is an invalid PNG

### ISSUE THREAD

**Issue by LucasChollet** [web-platform-tests/wpt#48107]
In `png/support/cicp-display-p3.png` the chunk order is the following:
-IHDR
-PLTE
-cICP
-IDAT
-IEND

However, according to [this](https://www.w3.org/TR/png-3/#5ChunkOrdering) section of the spec, the ordering is incorrect.
To also quote [11.3.2.6 cICP Coding-independent code points for video signal type identification](https://www.w3.org/TR/png-3/#cICP-chunk) exactly:
> The cICP chunk MUST come before the [PLTE](https://www.w3.org/TR/png-3/#11PLTE) and [IDAT](https://www.w3.org/TR/png-3/#11IDAT) chunks.

---
@ProgramMax you might be interested.
I'll open a PR to fix that.

**Comment by ProgramMax** [comment]
Good catch. Thank you.
I've attached a corrected PNG. I simply swapped the locations of the PLTE and cICP chunks.

Feel free to create a PR using this and I'll approve it.
![cicp-display-p3](https://github.com/user-attachments/assets/3cb718a6-555c-4a19-b73f-1b149d81a9cb)

**Comment by LucasChollet** [comment]
You can thank jbowler, he's the one who caught that.

I did not use your image, but they are byte-identical.

**Comment by ProgramMax** [comment]
Well then, thank you @jbowler
