### ISSUE TITLE
reftest-wait support for visual tests?

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#4813]
This is probably a good idea, and given we collectively don't maintain any runner is quite easy for us to implement! Opinions? @jgraham @Ms2ger

**Comment by Ms2ger** [comment]
No particular objection.

**Comment by foolip** [comment]
@gsnedders, can you expand on what this means? Aren't visual tests and reftests the same thing?

**Comment by gsnedders** [comment]
@foolip visual tests are the ones that are done by pixel-comparison to some per-platform pre-rendered screenshots (i.e., Chromium's pixel tests)

**Comment by foolip** [comment]
Do these tests exist inside css/? Do any of them actually run anywhere?

**Comment by gsnedders** [comment]
@foolip There's thousands inside `css/`; Edge runs them AIUI.

**Comment by foolip** [comment]
@patrickkettner @thejohnjansen, how does that work for Edge? Do you store the baselines out of band, and how do you know when to regenerate them?
