### ISSUE TITLE
This is causing my device interactions all types of trouble 

### ISSUE THREAD

**Issue by ghost** [web-platform-tests/wpt#48166]
Why aren't I receiving and able to send web messages from various individuals I've texted with prior days ago. It something you guys are doing that's changing the strip strings or whatever else it could be. I have no idea. All I know is I want basic dns enable with capabilities to receive all calls text and notifications to my phone. I do not appreciate these changes taking place. Why aren't I able t have consistent dialogue via text. Only Google sponsored apps are running.why aren't my background apps running constantly freely

**Comment by Psychpsyo** [comment]
Calls, texts, DNS, and phone notifications are not covered by web platform tests, so I don't think you are in the right place.
