### ISSUE TITLE
Update README.md to account for https://web-platform-tests.org/

### ISSUE THREAD

**Issue by frivoal** [web-platform-tests/wpt#4835]
We now have nice and up to date documentation  living at https://w3c.github.io/web-platform-tests/, but there's also a good chunk information in the repo's README.

We should:
* Make the README point to https://w3c.github.io/web-platform-tests/ instead of http://testthewebforward.org/ (and make the link to  more prominent, probably by putting it at the top)

* Stop having too places to document things, and just use https://w3c.github.io/web-platform-tests/. If the README still has information that's not in the docs, then we should fix the docs, but generally, we should replace the readme with a short intro that just says what this repo is for, and points to the doc for more details.

@gsnedders

**Comment by gsnedders** [comment]
This should actually be http://web-platform-tests.org/

**Comment by gsnedders** [comment]
So the links from the README now all auto-redirect to the right URL.

As for duplication between the README and the documentation, this has been discussed on a number of occasions; we're far from the only project with such things (indeed, it's quite typical on GitHub to have basic setup info in your README, both how to build and how to run tests, anything needed for someone to jump in immediately without reading thousands of lines of documentation).

**Comment by foolip** [comment]
@web-platform-tests/wpt-core-team should we change the http://irc.w3.org/?channels=testing link at the top of https://github.com/web-platform-tests/wpt to https://web-platform-tests.org/?

The README still does not link to the documentation site, and https://github.com/web-platform-tests/wpt/issues/5289 is a related issue.

**Comment by sideshowbarker** [comment]
> @web-platform-tests/wpt-core-team should we change the http://irc.w3.org/?channels=testing link at the top of https://github.com/web-platform-tests/wpt to https://web-platform-tests.org/?

Yes

**Comment by Ms2ger** [comment]
Done.

**Comment by jugglinmike** [comment]
We just landed gh-18328, which promotes link to the documentation site to the opening of the readme. There's still some duplication between the readme and the documentation site, but since gh-5289 describes that problem specifically, I think we can use that to track the work that remains.
