### ISSUE TITLE
WPT has a redundant utility script to define `checkLayout`

### ISSUE THREAD

**Issue by dholbert** [web-platform-tests/wpt#48705]
WPT has two utility scripts that define a `checkLayout()` utility-function:
(1) `check-layout-th.js`, referenced in in 800+ files (note, "th" here is short for "testharness" I think):
https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt%20check-layout-th.js&type=code

(2) `check-layout.js`, referenced  in 1 file:
https://github.com/search?q=repo%3Aweb-platform-tests%2Fwpt%20check-layout.js&type=code
(This `check-layout.js` script itself is [here](https://github.com/web-platform-tests/wpt/blob/2ab788df7f0d2ee35d67511348ce5eb4162c12d5/resources/check-layout.js) and its one usage is [here](https://github.com/web-platform-tests/wpt/blob/b90753123dc42eb95b140828dacd0a52235a32ec/css/css-sizing/replaced-fractional-height-from-aspect-ratio.html#L4).)

It looks like the latter script (the one with only one usage) was added perhaps by accident in https://github.com/web-platform-tests/wpt/pull/31891 a few years back.

@josepharhar @bfgeek could you remove the `check-layout.js` file that's only used once, and update its sole usage to use the other one?

**Comment by dholbert** [comment]
(pinging you two in particular since you've got git-blame for the file itself and for the sole-usage, respectively. :)  So you're likely to know if there's a reason for the file to exist, though I suspect there isn't.)

**Comment by josepharhar** [comment]
I'm on it, thanks for finding this! And sorry for accidentally adding the duplicate, I can clearly see that I didn't even use it in the patch I added.

**Comment by josepharhar** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/5947328

**Comment by josepharhar** [comment]
Looks like my patch passes all tests in chromium, it should be merged soon and then automatically upstreamed here.

**Comment by dholbert** [comment]
Thanks!
