### ISSUE TITLE
Documentation: how to require HTTPS

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#4922]
Presumably this is a thing that we have now because of service workers and secure contexts. It's missing from http://web-platform-tests.org/writing-tests/server-features.html however.

**Comment by dominickng** [comment]
Is there any progress here? I'd like to write some web-platform-tests to follow up on https://github.com/whatwg/notifications/issues/93, which proposes restricting notifications API use to secure origins.

**Comment by annevk** [comment]
I think the idea is that you use `.https.` in the filename before the extension as part of the dot-delimited metadata. @jgraham is there anything more to it?

If that's correct I can probably add it to the documentation.

**Comment by gsnedders** [comment]
#5699 partly covers this.

**Comment by jugglinmike** [comment]
gh-5699 has since been merged, so the requested documentation is now available (although not on the "Server Features" page itself as suggested by @annevk).
