### ISSUE TITLE
Containment tests for `container-type` don’t adequately cover layout containment

### ISSUE THREAD

**Issue by knowler** [web-platform-tests/wpt#49776]
First of all, according to the spec both the `inline-size` _and_ `size` value for `container-type` should cause layout containment (https://www.w3.org/TR/css-contain-3/#container-type), however, the current test only states it’s for the `inline-size` `container-type`.

https://github.com/web-platform-tests/wpt/blob/e24bf6f9c47b861f59c34fdd4d20fe36646f8f41/css/css-conditional/container-queries/container-type-containment.html#L33-L37

Additionally and unfortunately, [using `float:left` on a sibling element](https://github.com/web-platform-tests/wpt/blob/e24bf6f9c47b861f59c34fdd4d20fe36646f8f41/css/css-conditional/container-queries/container-type-containment.html#L29-L32) to test if a containment is applied doesn’t seem to be the best test of layout containment as it’s not covering if a _fixed positioning containing block_ has been created (https://www.w3.org/TR/css-contain-2/#containment-layout). I have [a reduced test case](https://knowler.dev/demos/ybomgkl) that differs in Chromium/Gecko and WebKit (expected: the “fixed” element stays within the box; actual: element becomes fixed to viewport in Chrome/Gecko; element is correct in Safari).

Do we need an additional test for this or can we make some modifications to the existing test to cover this?

**Comment by knowler** [comment]
It looks like Safari Technology Preview 210 matches Chromium/Gecko behaviour (which is incorrect).

**Comment by knowler** [comment]
Sounds like the spec is outdated and perhaps the container becoming a fixed positioning containing block is no longer expected: https://front-end.social/@mia/113680203304516206

**Comment by bfgeek** [comment]
The resolution to change the spec was: https://github.com/w3c/csswg-drafts/issues/10544#issuecomment-2248438355 (and @mirisuzanne just has to change the spec :) ).

 - (FWIW its quite common for browsers to ship a change like this before the spec has been updated - sorry for the confusion).

**Comment by mirisuzanne** [comment]
The spec has been updated. I think this can be closed?
