### ISSUE TITLE
Accessibility: Input with multiple explicit label elements associated

### ISSUE THREAD

**Issue by giacomo-petri** [web-platform-tests/wpt#49825]
Example:

```
<label for="test">This</label>
<label for="test">is</label>
<label for="test">a</label>
<label for="test">test</label>
<input type="text" id="test">
```

Browsers handle the calculation of the accessible name for the input inconsistently:
- Chrome concatenates the strings "This is a test"
- Safari uses only the first label, "This"
- Firefox concatenates the strings "This is a test"

Per [html-aam](https://www.w3.org/TR/html-aam-1.0/#input-type-text-input-type-password-input-type-number-input-type-search-input-type-tel-input-type-email-input-type-url-and-textarea-element-accessible-name-computation)

> Otherwise use the associated label element or elements [accessible name(s)](https://www.w3.org/TR/accname-1.2/#dfn-accessible-name) - if more than one label is associated; concatenate by DOM order, delimited by spaces.

it should resolve in "This is a test".

Creating WPT test

Edit: 
I was testing an old version of Safari. Safari is working as expected!

**Comment by cookiecrook** [comment]
Can a WPT admin please move this issue to the Interop-accessibility repo?
