### ISSUE TITLE
Support typedefs (and union return values for attributes) in idlharness.js

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#5034]
From https://github.com/w3c/web-platform-tests/pull/4992#discussion_r103633262

> TODO: Test when we actually have something to test this on

Apart from webvtt there is https://fetch.spec.whatwg.org/#body-mixin used by fetch and XHR; HTML uses various typedefs and unions...

**Comment by ayg** [comment]
I poked at this a bit.  Is there an example of a test that currently fails in a browser but should pass or vice versa?  I don't understand the code (or spec) well enough to work on this without something concrete to test on.

**Comment by zcorpan** [comment]
http://w3c.github.io/webvtt/#typedefdef-lineandpositionsetting
Test: webvtt/api/interfaces.html

In e.g. Safari TP `line` returns something like -1 when it should return "auto" and setting to "auto" throws an exception. Works per spec in Chromium.
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4992

Some other things using unions with maybe varying support:
https://xhr.spec.whatwg.org/#dom-xmlhttprequest-send-body-body
https://xhr.spec.whatwg.org/#dom-formdata-get-name-name
https://fetch.spec.whatwg.org/#dom-requestinit-headers
https://fetch.spec.whatwg.org/#dom-requestinit-body
https://fetch.spec.whatwg.org/#dom-request-request-input-init-input
https://html.spec.whatwg.org/#dom-media-srcobject
https://html.spec.whatwg.org/#dom-context-2d-drawimage

**Comment by ayg** [comment]
Okay, I have a PR to support unions.  If that gets reviewed, maybe I'll do typedefs too.  Note that it's not possible to automatically test setting or attribute default values or such based on the IDL, so that Safari bug needs an actual manually-written test of the spec.

**Comment by saschanaz** [comment]
It seems the PRs are merged. Is this issue fixed now?

**Comment by zcorpan** [comment]
Yes
