### ISSUE TITLE
Deprecate some requirement flags

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5293]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6 by @frivoal on 09 Jan 2017, 01:19 UTC:

> The [list of requirement flags](https://gsnedders.github.io/wpt-docs/writing-tests/css-metadata#requirement-flags) looks like it lists all of the historical ones.
> 
> We should keep on documenting the old ones, so that when people run into them they know what they mean, but we should move these to a "historical" subsection, and only keep the ones we actually expect people to in the main section.
> 
> Based on previous discussions, I believe we had agreed that the following ones could be deprecated:
> * ahem: treat ahem as a requirement for the entire test suite, and stop flagging individual tests
> * animated: no need to distinguish from manual tests flagged as "interact"
> * dom: can be inferred from the test using javascript
> * image / svg: modern UAs all support this, and it can be inferred form the test itself anyway
> * userstyle: no need to distinguish from manual tests, unless we also adopt a convention for linking to the user style sheet that automated tests runners can use to pick up the test file, in which case we will also not need the flag. For instance we could require the use of something like `Prior to running this test, <a rel="user-style-sheet" href="path/to/style-sheet.css">this user style sheet </a> must be <a href="doc/to/how-to-use/user/style-sheets/">installed</a>`.
> * 32bit: historical, inconsistently used anyway
> * 96dpi: required by the specs anyway.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6#issuecomment-271199189 by @frivoal on 09 Jan 2017, 01:57 UTC:

> Actually, we can also deprecate this one:
> * interact: redundant with the `*-manual` extension if test file names, presuming we start applying it systematically for CSS tests as well.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6#issuecomment-271295292 by @gsnedders on 09 Jan 2017, 14:19 UTC:

> We got no resolution and no real agreement as to what could be dropped, AIUI, hence I simply haven't touched the table yet.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6#issuecomment-271302301 by @frivoal on 09 Jan 2017, 14:47 UTC:

> Let's try and propose one again. Does the list above seem good do you, or do you think I missed something? I know we had another list at some point, but I'm too lazy to go look for it.

**Comment by gsnedders** [comment]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/6#issuecomment-271303443 by @gsnedders on 09 Jan 2017, 14:52 UTC:

> userstyle was used by the Presto import to not disable them automatically and find the files which needed a user stylesheet set, so in a sense it has some function. In reality, I don't think anyone else has automated them? Should check with Edge people.

**Comment by foolip** [comment]
Current URL is https://web-platform-tests.org/writing-tests/css-metadata.html#requirement-flags

**Comment by foolip** [comment]
Are the flags extracted by some tool, so that we could generate a table of which are used how many times? Presumably we can just remove a bunch of them.

**Comment by foolip** [comment]
I was thinking we'd just rename/remove the flags in old tests. If we can find the flags to begin with, then we can also do that. (Not sure we can find them with existing code though.)

**Comment by frivoal** [comment]
At least for  `animated`, `interact`, `font` and `userstyle`, you cannot remove then without renaming the file to match manual tests naming conventions, and renames are considered disruptive.

For the rest, I don't know. The flags are not very useful, but they're also not wrong. Also, if that invalidates many stored results in shepherd, that's not the end of the world, but if we can avoid that, that's better. But maybe the maintenance / cognitive burden justifies the short term annoyance. Not sure.

**Comment by foolip** [comment]
Oh, there's no "manual" flag to collapse these into? I guess then I'd pick one and use that for all of them.

Renames outside of css/ are fine, although huge ones can create a bit of trouble. Is it the results in shepherd that makes things different for CSS?

**Comment by frivoal** [comment]
> Oh, there's no "manual" flag to collapse these into? I guess then I'd pick one and use that for all of them.

Either than, or rename every foo-001.html into foo-001-manual.html

> Renames outside of css/ are fine, although huge ones can create a bit of trouble. Is it the results in shepherd that makes things different for CSS?

For css, I think renaming of changing the content of the test has the same effect: the test is considered new/different, and old results don't apply. This is not necessarily a blocker, so we can do it, but we should not do it for no reason, as there is a cost.

However, I had heard that renames were bad in general, not due to css tooling, but because some vendors had internal systems where metadata about tests was stored based on filenames. @gsnedders should know more about that.

**Comment by foolip** [comment]
Renames have caused trouble in the past, but the import systems of Blink and Gecko now handle them just fine, and I think WebKit's will too as it's based on Blink's.

But links to wpt.fyi and such can still break, so renames should have *some* benefit.

**Comment by gsnedders** [comment]
> Oh, there's no "manual" flag to collapse these into? I guess then I'd pick one and use that for all of them.

In principle it was up to each vendor as to what they wanted to run manually (e.g., with a small amount of manual work the userstyle tests could all be automated, the print tests are really just a variant of the normal test you just need to opt-in to a different rendering codepath and then do everything the same).
