### ISSUE TITLE
Additional hyperlinks

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5294]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/11 by @frivoal on 09 Jan 2017, 01:49 UTC:

> Once #10 is solved, it would be good for the [be-self-describing](https://gsnedders.github.io/wpt-docs/writing-tests/general-guidelines#be-self-describing) section to link to these guidelines.

**Comment by foolip** [comment]
@gsnedders, is this about cross-linking some bits of documentation? Which bits?

**Comment by gsnedders** [comment]
Yes. http://web-platform-tests.org/writing-tests/general-guidelines#be-self-describing to http://web-platform-tests.org/writing-tests/rendering.html, AIUI

**Comment by vatsalanarang** [comment]
I am interested in solving this issue.how can I do this?

**Comment by foolip** [comment]
@gsnedders can you give guidance?
