### ISSUE TITLE
Server-side scripting

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5300]
Originally posted as https://github.com/gsnedders/wpt-docs/issues/19 by @gsnedders on 18 Jan 2017, 16:47 UTC:

> We don't really have any documentation about writing server-side scripts for w-p-t. The wptserve documentation is a bit too generic, not being written under the assumption that it only applies to wpt.

**Comment by foolip** [comment]
http://web-platform-tests.org/writing-tests/server-features.html would be the place to write that, I guess?

**Comment by jugglinmike** [comment]
gh-17039 got us part of the way there, but it could still use a little more detail. I've opened gh-17386 in the hopes of resolving this.
