### ISSUE TITLE
Stability checker should run for reference changes

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#5319]
cc/ @jgraham  @jugglinmike

**Comment by bobholt** [comment]
@gsnedders: can you elaborate on this? Sounds like it was parrt of a discussion I missed.

**Comment by gsnedders** [comment]
Given a reftest a.html with `<link rel=match href=a-ref.html>`, the stability checker will run the test if there is a change to a.html, but won't run the test if there is a change to a-ref.html.

**Comment by gsnedders** [comment]
(Of course the problem is harder than that because of the possibility of chaining references, where a-ref.html would have another `<link rel=match>`.)

**Comment by foolip** [comment]
@lukebjerring is this something you could look into as part of your work on https://github.com/w3c/web-platform-tests/issues/7475? I'm calling this roadmap on the assumption that will make sense.

**Comment by JKereliuk** [comment]
@lukebjerring any update on this?

**Comment by lukebjerring** [comment]
No, I haven't looked at it yet, will assign to self though (it's in the pile)

**Comment by JKereliuk** [comment]
@lukebjerring have you had a chance to look at this yet?

**Comment by lukebjerring** [comment]
Not as yet.

**Comment by alijuma** [comment]
Re-ping about an update since this has prioirty:roadmap.

**Comment by lukebjerring** [comment]
Dropping that label; this is a side-issue barely related to a P2 OKR.

**Comment by foolip** [comment]
@gsnedders given changes in the manifest format since this issue was filed, is this now easier to implement?

**Comment by gsnedders** [comment]
Not sure. It's been a long time since I've touched the code that finds how we find affected tests.

**Comment by foolip** [comment]
It looks like this has been fixed actually. Here's how I tried it:
```sh
echo >> css/css-grid/table-grid-item-dynamic-001-ref.html
git commit -a -m bla
./wpt tests-affected HEAD~
```

That lists `css/css-grid/table-grid-item-dynamic-001.html` as affected!
