### ISSUE TITLE
Video srcObject test uses wrong start date accessor

### ISSUE THREAD

**Issue by alvestrand** [web-platform-tests/wpt#5384]
web-platform-tests/mediacapture-streams/MediaStream-MediaElement-srcObject.https.html queries the "startDate" property of a video element.
The spec says it doesn't have a "startDate" property, it has a "getStartData()" accessor.

**Comment by alvestrand** [comment]
(was crbug.com/412342)

**Comment by dontcallmedom** [comment]
this got fixed in #13084
