### ISSUE TITLE
[css-writing-modes-3] bidi-003 has slight offset from the reference file

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5460]
Originally posted as https://github.com/w3c/csswg-test/issues/794 by @kojiishi on 06 Jul 2015, 15:24 UTC:

> The test and the ref are slightly off on Gecko, Blink, and Trident.
> 
> Is it possible for you to double-check if the test is correct?

**Comment by frivoal** [comment]
I believe the text is correct. The implementation bug seems to be that browsers ignore this requirement from [CSS2](https://www.w3.org/TR/CSS2/text.html#white-space-model) (which is also in [CSS-TEXT-3](https://drafts.csswg.org/css-text-3/#white-space-phase-1)):

> For each inline element (including anonymous inline elements), the following steps are performed, **treating bidi formatting characters as if they were not there**: 
> ...

Check this example: http://jsbin.com/locakid/edit?html,output
Browsers do bidi white space collapsing correctly when markup / css is creating the bidi situation, but not when it is created with bidi control characters. That's a pretty clear spec violation.

**Comment by frivoal** [comment]
Note: either way, reglardless of whether the bug is in browsers or the spec, it's a CSS2 / CSS-Text-3 bug, What's in scope for CSS-Writing-modes (bidi reordering itself) is working as intended.

**Comment by fantasai** [comment]
Florian filed the spec issue at https://github.com/w3c/csswg-drafts/issues/2233 fwiw.
