### ISSUE TITLE
More CSS Fonts tests

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5475]
Originally posted as https://github.com/w3c/csswg-test/issues/1000 by @Ms2ger on 28 Dec 2015, 12:59 UTC:

> Suggested tests to write for CSS Fonts at Test the Web Forward Tokyo:
> 
> Simple tests:
> 
> Test parsing of the `@font-face` rule (chapter 4). Try various combinations of descriptors, and get them using JavaScript. (E.g. using `document.styleSheets[0].cssRules[0].cssText`).
> 
> Moderate tests:
> 
> Look in https://github.com/mozilla/mozilla-central/tree/master/layout/reftests/ and https://github.com/mozilla/mozilla-central/tree/master/layout/style/test (search for "font") for Mozilla tests that can be converted to W3C tests to check the spec.
> 
> Difficult tests:
> 
> Chapter 6-7 about Font Features.
> 
> Notes:
> 
> In Mozilla's repository, layout/style/test/property_database.js has a property reference you can use instead of reading the spec.

**Comment by svgeesus** [comment]
> Difficult tests:
> Chapter 6-7 about Font Features.

I'm adding tests for these now.
https://github.com/w3c/web-platform-tests/issues?utf8=%E2%9C%93&q=label%3Acss-fonts-3%20

**Comment by svgeesus** [comment]
> Simple tests:
> Test parsing of the @font-face rule (chapter 4). Try various combinations of descriptors, and get them using JavaScript. (E.g. using document.styleSheets[0].cssRules[0].cssText).

These would be useful tests to have, now the Font OM part of css-fonts-3 aligns with implementations

**Comment by foolip** [comment]
@svgeesus was this work finished, or is there more to do in this issue?

**Comment by svgeesus** [comment]
@foolip the tests I wrote were merged to WPT. The @font-face OM stuff was moved to CSS Fonts 4, and still needs tests.I think this old tracking issue/wishlist can be closed now.

**Comment by foolip** [comment]
Thanks @svgeesus!
