### ISSUE TITLE
css21/borders/border-color-005-ref.xht is broken

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5483]
Originally posted as https://github.com/w3c/csswg-test/issues/1096 by @hrj on 11 Jul 2016, 05:24 UTC:

> If I am not mistaken, the intermixing of `px` and `em` units breaks the widths and alignments.
> 
> Chromium screenshot:
> 
> ![border-color-005-ref](https://cloud.githubusercontent.com/assets/345879/16720612/aaccda9c-4755-11e6-87a1-6c115ca83030.png)
> 
> Firefox is similar.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1096#issuecomment-231645013 by @hrj on 11 Jul 2016, 05:26 UTC:

> cc @rhauck (original commiter).

**Comment by TalbotG** [comment]
@wpt-issue-mover and @hrj

Please take note that there is no minimum font size for tests and reference files. 

If the minimum font size is set to none (or to less than 11px) in your browser, then the reference file is correct.

Please close this issue.

**Comment by hrj** [comment]
@TalbotG 

Thanks for looking. Since I am not the creator of the issue (in this repo), I don't have the rights to close. Someone with the rights, please do the honors.

**Comment by TalbotG** [comment]
Okay, I am closing this issue now.
