### ISSUE TITLE
matchMedia.html uses assert_inherits to test a global property

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5493]
Originally posted as https://github.com/w3c/csswg-test/issues/1131 by @jdm on 26 Sep 2016, 17:27 UTC:

> This looks wrong, since properties of the global are expected to be own properties, unlike every other kind of DOM object.
> 
> ```
> test(function(){
>     assert_inherits(window, "matchMedia");
> }, "window.matchMedia exists");
> ```

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1131#issuecomment-249638350 by @gsnedders on 26 Sep 2016, 17:28 UTC:

> This is `cssom-view-1/matchMedia.xht`.

**Comment by csswg-test-issue-mover** [comment]
Originally posted as https://github.com/w3c/csswg-test/issues/1131#issuecomment-249638722 by @gsnedders on 26 Sep 2016, 17:30 UTC:

> Really much of this file should just be replaced with something using `idlharness`, and then that fixes this.

**Comment by foolip** [comment]
Recent results are at https://wpt.fyi/results/css/cssom-view/matchMedia.xht and this is still a problem.

The failing subtest and probably more are already tested in https://wpt.fyi/results/css/cssom-view/interfaces.html, as "Window interface: operation matchMedia(CSSOMString)"

**Comment by shvaikalesh** [comment]
This was fixed by #19841 (please see https://github.com/web-platform-tests/wpt/pull/19841#discussion_r338567740).

//cc @jdm
