### ISSUE TITLE
Check for wide Python build in build-css-testsuites.sh

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#5504]
Originally posted as https://github.com/w3c/csswg-test/issues/1245 by @gsnedders on 22 Mar 2017, 17:48 UTC:

> At least according to <https://wiki.csswg.org/test/css2.1/harness> the build system needs this.

**Comment by foolip** [comment]
Since csswg-test is now merged, I assume this is no longer relevant.

**Comment by gsnedders** [comment]
Nah, we still have the build system here, and we probably want this for the sake of people who care about the CSS test harness.

**Comment by gsnedders** [comment]
(It's also a few lines if someone sits down and fixes it!)
