### ISSUE TITLE
web-platform-tests.org doesn't seem to link to this github repository

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#5839]
A link should probably be in the footer and on the home page.

**Comment by xfq** [comment]
@tobie Do you mean something like this: https://xfq.github.io/test-pages/

**Comment by tobie** [comment]
I'd put it in the footer, but ymmv

**Comment by jugglinmike** [comment]
wpt.org is currently owned and operated by Wisconsin Public Television, so I believe this issue is no longer relevant.

**Comment by xfq** [comment]
I guess what it meant was web-platform-tests.org?

**Comment by jugglinmike** [comment]
Resolved via gh-18328
