### ISSUE TITLE
Update README to account for new review process

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#5943]
* getting an approved review now mandatory to allow merge
* fix terminology (which is downstream, which is upstream?)

**Comment by foolip** [comment]
Do you mean https://github.com/w3c/web-platform-tests/blob/master/README.md#test-review?

There are some funny lies there, like "But we look at all of them".

And in this documentation it's perhaps best to avoid upstream/downstream terminology. I always call this repo on GitHub the upstream, but don't really call Chromium downstream (or upstream).

**Comment by jugglinmike** [comment]
See gh-18343 for an attempt to resolve this. It doesn't change anything about that "funny lie," but replacing that text with something useful/honest seems to require a bit of research. For that, we have gh-17370.
