### ISSUE TITLE
Formalize policy for usage of new language features

### ISSUE THREAD

**Issue by jugglinmike** [web-platform-tests/wpt#6266]
The usage of new ECMAScript features has been a topic of discussion in a few recent pull requests. Currently, there does not seem to be consensus around in what contexts it is appropriate to use such features in WPT. Having clarity here would help everyone involved with this project: contributors (so they could have some confidence that their stylistic choices would be accepted), reviewers (so they wouldn't have to resolve discrepancies between the preferences of different contributors), and consumers (so they would have a realistic expectation about when they might start to fail tests due to orthogonal issues in their JS runtime).

Unfortunately, the desires of those audiences is somewhat at odds. Test contributors will tend to want to use all the tools that are available to them. On the other hand, implementers will generally prefer to avoid practices that could prevent them from executing tests. (For their part, maintainers probably just want clarity--the specific decision doesn't effect them as much.)

This tension might be partially addressed by **a "contextual" policy**. Maybe new ECMAScript features are acceptable in tests written against specifications that are similarly new. Along these lines, new features would also be barred from shared utilities such as those found in the `common/` and `resources/` top-level directories (since those files may be included by any test and would therefore be a lowest-common-denominator). Defining, documenting, and enforcing this kind of policy is a little tricky, though, because it assumes familiarity with the publication history of various specifications.

Under **a "blanket" policy**, WPT would simply declare, "any test may use any language feature that was standardized at least X years prior to the current date." For example, setting up a blanket policy of 1 year would today translate to: "you may use the exponentiation operator, but you may not use async functions." This would be easier to follow in practice, although it might also needlessly shut some consumers out from tests that would otherwise help them ensure conformance.

I would love to get input on this topic from members of all three audiences. My goal is to amend [`docs/_writing-tests/assumptions.md`](https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/assumptions.md) and/or [`docs/_writing-tests/general-guidelines.md`](https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/general-guidelines.md) with a policy by Friday June 23.

**Comment by tobie** [comment]
Quoting @jgraham in https://github.com/w3c/web-platform-tests/pull/6246#issuecomment-309443074:

> So to be clear, the general standard here is "should work in the latest stable releases of major browser engines i.e. Firefox, Safari, Edge, Chrome, prefereably Servo". testharness.js has been held to a slightly higher standard which is something like "no gratuitous breakage in older browsers", although the satndard here is a little fuzzy; something like "don't break the entire harness for trivial reasons and if some feature inevitably introduces breakage try to scope it to tests that actually use that feature".

**Comment by domenic** [comment]
I think that higher standard should be relaxed as it places an unnecessary burden on those attempting to contribute to testharness.js. Instead those wishing to use testharness in older browsers should maintain their own fork.

But I haven't contributed to testharness.js (and, with such a policy in place, am unlikely to) so the above is just an outsider opinion, not something I'm pushing strongly. I just wanted to throw it up for discussion.

**Comment by jugglinmike** [comment]
(Replying to @jgraham here since this issue is intended to facilitate the discussion outside of the context of any given patch.)

I'm worried that the standard you've described may be a little too vague for some contributors. Although we could reference [the popular "ECMAScript compatibility tables"](https://kangax.github.io/compat-table), Servo support in particular is hard to discover.

Servo depends on SpiderMonkey, but this does not imply equivalency to Firefox. The version each browser uses may be different, and I'm learning that due to the way these components are integrated, even the same version of SpiderMonkey may behave differently in each browser.

So while [I've made the suggestion to include Servo in the ECMAScript compatibility tables](https://github.com/kangax/compat-table/issues/831#issuecomment-309488985), this seems like a non-trivial effort. I think we'd all benefit from more clarity in the short term. I'm wondering if @bzbarsky has any suggestions for how we can help contributors be sure they aren't breaking support for Servo... beyond "go bug @bzbarsky in #servo on irc.mozilla.org" :)

**Comment by bzbarsky** [comment]
I don't have any great suggestions for avoiding problems due to missing functionality in an engine you can't test...

**Comment by jugglinmike** [comment]
That does sound like a hard problem! For our purposes here, though, I think a
simple "supported feature" document would go a long way for potential
contributors. I haven't been able to find such a document in the Servo
repository, in MDN, or on the web a large, though; do you know if anyone
maintains a document like that?

**Comment by bzbarsky** [comment]
I don't know offhand, but maybe someone who's more actively involved in servo like @jdm does....

**Comment by jdm** [comment]
I really don't think there's much useful info that we can provide. The things that cause us the most difficulties are recent ES6 features, since Servo is currently trapped on a version of SpiderMonkey from early 2016.

**Comment by jugglinmike** [comment]
It's the 23rd, so I've followed up with a patch for the project documentation: https://github.com/w3c/web-platform-tests/pull/6333

Thanks, everyone!

**Comment by filmaj** [comment]
I've been using this repo to test adherence to various W3C specifications on various mobile platforms (in particular some WebView implementations on Android/iOS). Just wanted to report that the `idlharness.js` file uses ES6 features which, for example, is not supported natively in iOS 9.3.

In terms of increasing the applicability of these tests, I would vote for keeping the tests and test framework in older versions of ECMAScript - I would think that would make this test suite more useful.

My $0.02.

Keep up the great work!

P.S. I am happy to contribute rewriting the particular sections of `idlharness.js` that are getting in my way, if that is deemed to be beneficial.

**Comment by tobie** [comment]
> P.S. I am happy to contribute rewriting the particular sections of idlharness.js that are getting in my way, if that is deemed to be beneficial.

Can you outline how big of a rewrite that would be?

If it's reasonable, I'm happy to merge it. Especially now that we're finally setup to run tests for the lib itself.

**Comment by filmaj** [comment]
Not much, frankly. A quick scan shows removing arrow functions and array dereferencing. I will happily send a PR whenever I have the tests working once more on iOS 9.3.

**Comment by filmaj** [comment]
@tobie PR up here in case you are interested: #6664 6664

**Comment by foolip** [comment]
One very concrete way of going about this is to say that if anyone is able to add a test to https://github.com/w3c/web-platform-tests/tree/master/infrastructure/assumptions and get it passing on all the configurations tested by wpt.fyi, then it's OK to use it. At least that is how I'd go about it.

**Comment by foolip** [comment]
Oh, that's pretty much what https://github.com/w3c/web-platform-tests/pull/6333 amounts to :)
