### ISSUE TITLE
Things I'm not sure how to do and I'd love to see in the documentation

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#6268]
* What's a python virtual env and how to use it. (e.g. pointer to http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/)
* How do I run the underlying python server (wpt serve?) so I can run tests in the browser when developing them (e.g. similar to : `$ python -m SimpleHTTPServer 5000`)?
* How do I setup wpt runner in a virtual env?
* How do I run a single test using wpt runner?
* How do I run all the tests in a directory? (using tox?)

I think @jgraham CLI tool is going to help answer most of these shortly, but think it's still useful to collect the kind of questions I've been facing while getting setup.

**Comment by foolip** [comment]
Just to answer the questions without documenting it anywhere:

> What's a python virtual env and how to use it. (e.g. pointer to http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/)

https://github.com/w3c/web-platform-tests/issues/6565

> How do I run the underlying python server (wpt serve?) so I can run tests in the browser when developing them (e.g. similar to : $ python -m SimpleHTTPServer 5000)?

`./wpt serve` then visit http://web-platform.test:8000/

> How do I setup wpt runner in a virtual env?

Do you mean using virtualenv, or a VM or something that doesn't contaminate your system?

> How do I run a single test using wpt runner?

`./wpt run firefox dom/historical.html`

How do I run all the tests in a directory? (using tox?)

`./wpt run firefox dom`

**Comment by dotnetCarpenter** [comment]
To run https (you have to accept the unknown certificate) `./wpt serve` then visit https://web-platform.test:8443/

**Comment by foolip** [comment]
@jugglinmike can you check if everything here has been documented, file issues for anything substantial left and then close this issue?

**Comment by jugglinmike** [comment]
@foolip Sure. You've already answered the questions; I'll add pointers to the existing documentation.

> - What's a python virtual env and how to use it. (e.g. pointer to http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/)

This is today documented in [Running Tests from the Local System](https://web-platform-tests.org/running-tests/from-local-system.html):

> Install pip. On many systems, this can be achieved with the command `python -m ensurepip`. If this is not possible, use your system’s package manager to install the `python-pip` package.
>
> Next, install `virtualenv` using the following command:
>
>     pip install virtualenv

See gh-16670 for the surprising amount of research necessary to produce that.

> - How do I run the underlying python server (wpt serve?) so I can run tests in the browser when developing them (e.g. similar to : $ python -m SimpleHTTPServer 5000)?

This is covered on the same page referenced above, under the heading "Via the browser"

> The test environment can then be started using
>
>     ./wpt serve
>
> This will start HTTP servers on two ports and a websockets server on one port. [...]

> - How do I setup wpt runner in a virtual env?

The CLI manages a Python virtual environment internally, so this does not need to be documented.

> - How do I run a single test using wpt runner?
> - How do I run all the tests in a directory? (using tox?)

Same page, section titled "Via the command line":

> Many tests can be automatically executed in a new browser instance using
>
>     ./wpt run [browsername] [tests]

By my reading, this issue has been resolved.

**Comment by foolip** [comment]
Thanks @jugglinmike!
