### ISSUE TITLE
charade package used by html5lib no longer exists

### ISSUE THREAD

**Issue by jdm** [web-platform-tests/wpt#6269]
It's been marked unmaintained for a long time, and has now been removed from PyPi entirely. We should replace it with chardet [according to the author](https://github.com/sv24-archive/charade).

**Comment by foolip** [comment]
@jdm, is this a problem for working with wpt in some context, or just something you happened to notice?

**Comment by jdm** [comment]
It's something that I happened to notice.

**Comment by foolip** [comment]
html5lib no longer depends on charade after https://github.com/html5lib/html5lib-python/pull/252.
