### ISSUE TITLE
Support a way to automatically merge on all-green

### ISSUE THREAD

**Issue by zcorpan** [web-platform-tests/wpt#6296]
I sometimes approve a PR but also re-run a failed check, or review a new PR before checks have completed. Then I leave the tab and it can go an unknown amount of time until I or someone else gets back to it to merge, or the PR author pings the PR asking why it's not merged yet, which is unfortunate.

I've requested a feature to do this to github some months ago, but it's not there yet. But it should be possible to do this per-repo with Travis CI, I think? For example, we could support having a label "auto-merge on all-green", which maybe squashes and merges if there are several commits, and rebases and merges if there's a single commit, if all checks are green (and there's an approved review).

Thoughts?

cc @tobie

**Comment by tobie** [comment]
Happy to work on this if someone is willing to fund that work.

**Comment by jgraham** [comment]
@bobholt is this on your radar? Seems like it oculd be added to the wptdash, perhaps?

**Comment by bobholt** [comment]
@jgraham: Yeah, I could look into that.

**Comment by zcorpan** [comment]
-> https://github.com/web-platform-tests/wpt-pr-bot/issues/33
