### ISSUE TITLE
Reftests take screenshot too early in Edge

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#6327]
Similar to https://github.com/w3c/web-platform-tests/issues/5412. https://github.com/w3c/csswg-drafts/issues/1088 is the issue that causes issues here. Notably, wptrunner needs to:

- [ ] Block screenshots on fonts loading. (Unclear we can do this through JS or through WebDriver in any way given Edge doesn't support the [Font Loading API](https://drafts.csswg.org/css-font-loading/).)
- [ ] Block screenshots on background images, list item images, etc. loading. (Unclear we can do this through JS or WebDriver in any way.)

Both of these are really problems web developers would hit if they wanted to do any screenshot-based testing over WebDriver, so I'd hope there's some way to work around them!

cc/ @patrickkettner @thejohnjansen

**Comment by thejohnjansen** [comment]
I am looking at the best solution that isn't just a hack for this. Internally we have a function that we call that tells us it's likely OK to take a screenshot. That is currently internal, though. I'm investigating making it external vs. possibly finding a better way. Currently the solutions I've found are all hacky, and we should avoid being hacky when it comes to stability jobs if possible.

**Comment by jgraham** [comment]
Can't WebDriver wait on that to take a screenshot? I'm happy to lobby for a spec change to make it official that you are exepcted to wait for a stable state after load before taking a screenshot. Otherwise we should add another load strategy to WebDriver for this purpose.

**Comment by gsnedders** [comment]
@jgraham See https://github.com/w3c/webdriver/issues/893 wrt that.

**Comment by bobholt** [comment]
Looks like @gsnedders fixed the font issue for wpt, but the other still pending resolution of https://github.com/w3c/webdriver/issues/893

**Comment by gsnedders** [comment]
@bobholt Uh, that commit message seems totally wrong. That commit shouldn't have changed anything in Edge, given Edge doesn't support the Font Loading API (currently "Under Consideration" on the Edge platform status page).

**Comment by foolip** [comment]
@thejohnjansen, do you have any update on https://github.com/w3c/web-platform-tests/issues/6327#issuecomment-312008545, something we could use both for the Travis CI runs and for wpt.fyi?

And does anyone know how widespread this issue? https://wpt.fyi/css/css-overflow/input-scrollable-region-001.html is one reftests that's passing in Edge and it's easy to find more, so at least not all reftests are failing.

**Comment by foolip** [comment]
This is about EdgeHTML, so should we close this issue? I'm guessing nobody will even run WPT against Edge 18 again...

**Comment by thejohnjansen** [comment]
I think it's fine to close this one out.
