### ISSUE TITLE
Document virtualenv setup steps

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#6565]
Trying to run "./wptrun firefox payment-request" yields the following error: 

```Bash
./wptrun firefox payment-request                                                                              
Traceback (most recent call last):
  File "./wptrun", line 5, in <module>
    wptrun.main()
  File "/Users/marcos/temp/web-platform-tests/tools/wptrun.py", line 304, in main
    venv = virtualenv.Virtualenv(os.path.join(wpt_root, "_venv_%s") % platform.uname()[0])
  File "/Users/marcos/temp/web-platform-tests/tools/browserutils/virtualenv.py", line 15, in __init__
    raise ValueError("virtualenv must be installed and on the PATH")
ValueError: virtualenv must be installed and on the PATH
```

The README seems to be missing documentation for "virtualenv".

**Comment by marcoscaceres** [comment]
`pip install virtualenv` is the fix - but should be somewhere or happen automagically.

**Comment by foolip** [comment]
I ran into this today as well when doing `wpt run edge` on Windows, and it was the only thing where the documentation is totally silent.

@gsnedders, trying to fix this myself, I ran into the duplication between README.md and introduction.md. Which one should be decommissioned?

**Comment by jgraham** [comment]
They are in different places. One is on the website and the other is displayed in GitHub. It would be nice if we could avoid this duplication, but  it's not clear how to do that.

**Comment by jgraham** [comment]
(I think installing this if it's missing is a better solution).

**Comment by foolip** [comment]
Can't README.md point to the installation instructions on web-platform-tests.org?

**Comment by xfq** [comment]
Perhaps this can be discussed in #5289?

**Comment by foolip** [comment]
Ran into it again on a Mac. @gsnedders, it's the duplication of documentation that makes this non-trivial to fix, so assigning to you :)

**Comment by alijuma** [comment]
This has priority:roadmap. Is this something that is going to be worked on this quarter?

**Comment by foolip** [comment]
@kereliuk, when you've come up with a bucket of documentation issues you think we should do in Q2, can you downgrade what remains to backlog?

**Comment by gsnedders** [comment]
@foolip Does this need the `infra` label? I guess we might want to make the exception message clearer and point to docs?

**Comment by kereliuk** [comment]
@foolip Yep, I'll do that as cleanup after I go through everything :)

**Comment by foolip** [comment]
@gsnedders, keeping infra labels seem fine :)

**Comment by zcorpan** [comment]
@nomadtechie is working on a fix here FYI.

**Comment by Hexcles** [comment]
@nomadtechie any progress here?

**Comment by foolip** [comment]
Unassigning again. @nomadtechie, please feel free to send a PR still if you like. (Came here by doing the issue triage in https://foolip.github.io/ecosystem-infra-rotation/.)

**Comment by marcoscaceres** [comment]
Got a new Mac! 🎉 But now after I tried:

```bash
pip install virtualenv
./wpt run safari payment-request/change-shipping-option-manual.https.html
```

I get:

```Bash
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/wpt.py", line 108, in main
    venv = setup_virtualenv(main_args.venv, props)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/wpt.py", line 86, in setup_virtualenv
    venv.install(name)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/virtualenv.py", line 50, in install
    call(self.pip_path, "install", *requirements)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/utils.py", line 44, in call
    return subprocess.check_output(args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I get the same error for all "browser" arguments.

**Comment by gsnedders** [comment]
@marcoscaceres 

Hmm. That implies `pip` isn't callable. What do you get as `which pip`?

**Comment by foolip** [comment]
FWIW, I'm having trouble with this myself right now. `pip install virtualenv` tells me "Requirement already satisfied: virtualenv in /usr/local/lib/python2.7/site-packages".

Aside: I think things are complicated by the fact that I installed python@2 in brew once, to see if that might fix https://github.com/web-platform-tests/wpt/issues/9007, and now... I don't know what's going on :)

**Comment by foolip** [comment]
So, it's not from a freshly installed Mac, but here's what worked after I got rid of my brew Python:
```sh
sudo easy_install pip
pip install --user virtualenv
```

Then add `$HOME/Library/Python/2.7/bin` to path. I think that last part is the bit that doesn't just happen automatically. With `sudo pip install virtualenv` I'm not sure where it ends up.

@marcoscaceres how did you install `pip`, and after that how `virtualenv`?

**Comment by marcoscaceres** [comment]
> That implies pip isn't callable, which implies something is wrong with the virtualenv. Did you copy the WPT tree over? 

No. Fresh clone. 

> You could just try deleting _venv at the root of the wpt working copy?

Can try.

**Comment by foolip** [comment]
> I can’t recall if this is part of the README’s setup instructions?

It's not. Figuring out how to best install it and documenting this is this issue. @gsnedders, can we also check if `virtualenv` is in the path and if not point to the documentation?

**Comment by beaufortfrancois** [comment]
Note that https://github.com/web-platform-tests/wpt/issues/6565#issuecomment-427498278 worked nice for me from a fresh install.

**Comment by foolip** [comment]
Thanks for confirming, @beaufortfrancois! Let's have that in the documentation, then :)

**Comment by marcoscaceres** [comment]
Ok, it's still busted for me... but important to do:

```
pip uninstall virtualenv
```

Before:
```
pip install --user virtualenv
```

Otherwise, "$HOME/Library/Python/2.7/bin" won't point to the right thing. 

Now I get (good... I guess):
```
$ pip install --user virtualenv
Requirement already satisfied: virtualenv in /Users/mcaceres/Library/Python/2.7/lib/python/site-packages (16.0.0)
```

But still busted:

```
$ ./wpt run firefox payment-request/rejects_if_not_active.https.html
Traceback (most recent call last):
  File "./wpt", line 5, in <module>
    wpt.main()
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/wpt.py", line 108, in main
    venv = setup_virtualenv(main_args.venv, props)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/wpt.py", line 86, in setup_virtualenv
    venv.install(name)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/virtualenv.py", line 50, in install
    call(self.pip_path, "install", *requirements)
  File "/Users/mcaceres/dev/web-platform-tests/tools/wpt/utils.py", line 44, in call
    return subprocess.check_output(args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 216, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Halp? I'm stuck as now I can run any tests that require marionette 😭

**Comment by foolip** [comment]
Reassigning since Bocoup will be doing a documentation overhaul and this is one of the things that are hard for newcomers to the project.

**Comment by foolip** [comment]
This came up in triage, but there's a recent PR in https://github.com/web-platform-tests/wpt/pull/16670 so this ought to soon be resolved.

**Comment by marcoscaceres** [comment]
Hit this again on a fresh macOs install... fixed it by using `brew install virtualenv` after trying with pip.
