### ISSUE TITLE
css-backgrounds-3/background-size-035.html

### ISSUE THREAD

**Issue by tgraham-antenna** [web-platform-tests/wpt#6604]
See https://test.csswg.org/harness/test/css-backgrounds-3_dev/single/background-size-035/

`background-size-035.html` uses an image of a sheep as the background image of a `div`.  The reference page indicates that the tested background image shows the entire image.  AFAICT, the test is testing the background image when it is scaled to fit the initial containing block and, as such, the `div` with the background can be expected to only show a portion of the image, at best.

The applicable parts of the test are:

````
    .backgroundSize{
        width:295px;
        height:289px;

        background-image:url(support/bg.jpg);
        background-repeat:no-repeat;
        background-size:cover;
        background-attachment:fixed;
    }
...
        <!-- This is the box that should only contains an image if the test passes -->
        <div class="backgroundSize">
        </div>
````

`background-attachment` is `fixed`.  The definition of `background-origin` (https://www.w3.org/TR/css3-background/#the-background-origin) includes:

> If the ‘background-attachment’ value for this image is ‘fixed’, then this property has no effect: in this case the background positioning area is the initial containing block [CSS21].

https://www.w3.org/TR/CSS21/visudet.html#containing-block-details includes:

> The containing block in which the root element lives is a rectangle called the initial containing block. For continuous media, it has the dimensions of the viewport and is anchored at the canvas origin; it is the page area for paged media.

`background-size` is `cover`, which is defined (https://www.w3.org/TR/css3-background/#the-background-size) as:

> Scale the image, while preserving its intrinsic aspect ratio (if any), to the smallest size such that both its width and its height can completely cover the background positioning area.

So the background image is positioned relative to the viewport/page and scaled to cover the viewport/page as best it can.  The background of the `div`, therefore, is most likely to show only a portion of the sheep's rump.

**Comment by tgraham-antenna** [comment]
I am just the (English speaking) messenger, but I'm glad that we agree.

**Comment by TalbotG** [comment]
Tony,
This one is on my radar now. 
Right now, I do not know how to delete an existing test with github and in a pull request but I will ask about it.

**Comment by TalbotG** [comment]
I think the command that I will need to use eventually is:
`git rm background-size-035.html`
but I will ask about it to be sure.

**Comment by TalbotG** [comment]
Tony,
All 9 Continous Integration checks have passed over at [Pull Request 17605](https://github.com/web-platform-tests/wpt/pull/17605). So now, it is a matter of waiting for 2 reviewers to approve the removal of background-size-035.html test.

**Comment by TalbotG** [comment]
I am closing this issue now that [Pull Request 17605](https://github.com/web-platform-tests/wpt/pull/17605) has been reviewed and approved.
