### ISSUE TITLE
Document different assertion types

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#6615]
Maybe this is somewhere... but it would be nice if there was a table that listed all the `assert_*` that are available - as I keep finding useful ones, that I'd wished I'd know about earlier. 

For each, it would be nice to and the right time to use each. 

<table>
  <caption>asserts</caption>
  <tr>
    <td>assert_true(actual, description)</td>
    <td>Literal check if `actual === true` (no type coercion).</td>
    <td><pre class="js">assert_true(true, "expected true");</pre></td>
  </tr>
  <tr>
    <td>assert_false(actual, description)</td>
    <td>Literal check if `actual === false` (no type coercion).</td>
    <td><pre class="js">assert_false(false, "expected false");</pre></td>
  </tr>
  <tr>
    <td>assert_equals(actual, expected, description)</td>
    <td>Test if two primitives are unequal or two objects are different objects.</td>
    <td><pre class="js">
      assert_equals(1, 1, "expect 1 to equal 1.");
      const obj = { test: "hi" };
      assert_equals(obj, obj, "expect `obj` to be same reference to `obj`.");
    </pre></td>
  </tr>
  <tr>
    <td>assert_not_equals(actual, expected, description)</td>
    <td>Test if two primitives are unequal or two objects are different objects.</td>
    <td><pre class="js">
      assert_not_equals(1, 2, "expect 1 to not equal 2.");
      const obj1 = { test: "1" };
      const obj2 = { test: "2" };
      assert_not_equals(obj1, obj2, "expect `obj1` to not equal `obj2`.");
    </pre></td>
  </tr>
  <tr>
    <td>assert_in_array(actual, expected, description)</td>
    <td>Tests that `actual` is in `expected`. Expected is an array.</td>
    <td>
      <pre class="js">
      const testArray = [5,4,3,2,1];
      assert_in_array(1, testArray, "The value `1` should be in `testArray`");
      // Similarly
      const obj = {};
      const objArray = ["hi", obj, 123];
      assert_in_array(obj, objArray, "");
      </pre>
    </td>
  </tr>
  <tr>
    <td>assert_object_equals(actual, expected, description)</td>
    <td>Tests if two objects have both the properties, and if those properties have the same values.</td>
    <td><pre class="js">
      const obj1 = {
        prop: "hello",
        listOfThings: [1, 2, 3],
      };
      const obj2 = {
        prop: "hello",
        listOfThings: [1, 2, 3],
      };
      assert_object_equals(obj1, obj2, "expected and actual have same property values");
    </pre></td>
  </tr>
  <tr>
    <td>assert_array_equals(actual, expected, description)</td>
    <td>Tests that actual and expected are the same length and have the same values in the same order</td>
    <td><pre class="js">
      const array1 = [ 1, 2, 3, 4 ];
      const array2 = [ 1, 2, 3, 4 ];
      assert_array_equals(array1, array2, "the two arrays are the same");
    </pre></td>
  </tr>
  <tr>
    <td>assert_approx_equals(actual, expected, epsilon, description)</td>
    <td>Test if two primitive numbers are equal within +/- epsilon.</td>
    <td><pre class="js">
        const gvt = {
          x, 0,
          y: 0,
          z: 1.622, // Moon gravity
        }
        assert_approx_equals(gvt.x, .5, 1, "Tolerance of (+/-)1");
        assert_approx_equals(gvt.y, .5, 1, "Tolerance of (+/-)1");
        // Moon gravity will cause this to fail
        assert_approx_equals(gvt.z, 9.81, 1.5, "Expected earth gravity");
    </pre></td>
  </tr>
  <tr>
    <td>assert_less_than(actual, expected, description)</td>
    <td>Test if a primitive number is less than another (exclusive!).</td>
    <td><pre class="js">
      assert_less_than(3, 5, "Expect 3 to be less than 5");
    </pre></td>
  </tr>
  <tr>
    <td>assert_greater_than(actual, expected, description)</td>
    <td>Test if a primitive number is less than another (exclusive!).</td>
    <td><pre class="js">
      assert_less_than(5, 3, "Expect 5 to be greater than 3");
    </pre></td>
  </tr>
  <tr>
    <td>assert_between_exclusive(actual, lower, upper, description)</td>
    <td>Test if a primitive number is between two others.</td>
    <td><pre class="js">
      assert_between_exclusive(4, 0, 10, "expect 4 to be between 0 and 10");
      // this would fail
      assert_between_exclusive(4, 4, 10, "4 can't be between 4 and 10.");
    </pre></td>
  </tr>
  <tr>
    <td>assert_less_than_equal(actual, expected, description)</td>
    <td>Test if a primitive number is less than or equal to another (inclusive)</td>
    <td><pre class="js">
      assert_less_than_equal(3, 5, "expect 3 to be less than 5");
      assert_less_than_equal(5, 5, "expect 5 to be less or equal to 5");
    </pre></td>
  </tr>
  <tr>
    <td>assert_greater_than_equal(actual, expected, description)</td>
    <td>Test if a primitive number is greater than or equal to another (inclusive)</td>
    <td><pre class="js">
      assert_greater_than_equal(10, 5, "expect 10 to be greater than 5");
      assert_greater_than_equal(5, 5, "expect 5 to be greater or equal to 5");
    </pre></td>
  </tr>
  <tr>
    <td>assert_between_inclusive(actual, lower, upper, description)</td>
    <td>Test if a primitive number is between to two others or equal to either of them.</td>
    <td><pre class="js">
      const value = 5;
      assert_between_inclusive(value, 0, 10, "value is either 0, 10, or somewhere in between");
    </pre></td>
  </tr>
  <tr>
    <td>assert_regexp_match(actual, expected, description)</td>
    <td>Test if a string (actual) matches a regexp (expected)</td>
    <td><pre class="js">
      const value = "PaSs";
      assert_regexp_match(value, /^pass$/i, "value equals the string 'pass'(case insensitive)");
    </pre></td>
  </tr>
  <tr>
    <td>assert_class_string(object, class_string, description)</td>
    <td>Test for the "brand" of an object (e.g., `[object Object]`).</td>
    <td><pre class="js">
      const link = document.createElement("link");
      assert_class_string(link, "HTMLLinkElement", "is a HTMLLinkElement object");
    </pre></td>
  </tr>
  <tr>
    <td>assert_not_exists(object, property_name, description)</td>
    <td>Test if `object` doesn't having its own property `property_name`. Note that this is not a "deep" check: it does not traverse the prototype chain. </td>
    <td><pre class="js">
      const obj = {
        foo: "",
      };
      assert_not_exists(obj, "bar", "Expect obj to not have 'bar' property");
      function Car(){
        this.speed = 0;
      }
      Car.prototype = {
        type: "Vehicle"
      };
      const car = new Car();
      // 🚨 This will pass, because it's in the prototype!
      assert_not_exists(car, "type");
      // This will error, type will be found!
      assert_not_exists(Object.getPrototypeOf(car), "type", "type is in the prototype");
    </pre></td>
  </tr>
  <tr>
    <td>assert_inherits(obj, property_name)</td>
    <td>Test to see if an object inherits a `property_name`.</td>
    <td><pre class="js">
      function Car(){
        this.speed = 0;
      }
      Car.prototype = {
        type: "Vehicle"
      };
      const car = new Car();
      // This passes, because type is indeed inherited
      // from the prototype.
      assert_inherits(car, "type");
      // 🚨 this errors, because "speed" is not inherited.
      assert_inherits(obj, "speed");
    </pre></td>
  </tr>
  <tr>
    <td>assert_readonly(object, property_name, description)</td>
    <td>Checks if a property is readonly.</td>
    <td><pre class="js">
      const obj = {
        get thisIsReadOnly(){
          return true;
        },
        normalProp: "writable"
      }
      assert_readonly(obj, "thisIsReadOnly", "Expect thisIsReadOnly to be read only");
      // 🚨 error! This normalProp is writable
      assert_readonly(obj, "normalProp", "Expect thisIsReadOnly to be read only");
      // Works with IDL attributes too
      assert_readonly(document.body, "classList", "Readonly IDL attribute");
    </pre></td>
  </tr>
  <tr>
    <td>assert_throws(error, func, description)</td>
    <td>Given a function `func`, tests if an JS Error (TypeError, SyntaxError, etc.)
      or DOM Exception is thrown when the `func` is called.
      The `error` can be either an instance of an error (e.g., `new TypeError()`),
      the code name (e.g., "INVALID_STATE_ERR"),
      or the name (e.g., "DataError")</td>
    <td><pre class="js">
      // These are roughly equivalent
      // Legacy style
      assert_throws("INDEX_SIZE_ERR", () => {
        throw new DOMException("", "IndexSizeError")
      }, "Expected IndexSizeError");
      // Modern style
      assert_throws("IndexSizeError", () => {
        throw new DOMException("", "IndexSizeError")
      }, "Expected IndexSizeError");
      // This works... but it's mostly redundant (use the above modern option)
      assert_throws(new DOMException("", "IndexSizeError"), () => {
        throw new DOMException("", "IndexSizeError")
      }, "Expected IndexSizeError");
      // these are equivalent, but useful for testing non-DOMExceptions
      assert_throws(new TypeError(), () => {throw new TypeError()}, "Expected TypeError");
      assert_throws(TypeError(), () => {throw TypeError()}, "Expected TypeError");
    </pre>
    </td>
  </tr>
  <tr>
    <td>assert_unreached(description)</td>
    <td>Tests that code that should never be reached has been reached. This is useful for
      testing unexpected exceptions, for instance.
    </td>
    <td><pre class="js">
      try {
        new Thing();
      } catch(err) {
        assert_unreached("Oh no! this should never ever happen!")
      } finally {
        assert_true(true, "expected to get here");
      }
    </pre></td>
  </tr>
  <tr>
    <td>???</td>
    <td>assert_any(assert_func, actual, expected_array)</td>
    <td><pre class="js">
    </pre></td>
  </tr>
</table>

**Comment by marcoscaceres** [comment]
@sideshowbarker, where would it be best to put this... also... I couldn't come up with a good explanation for `assert_any`.  I saw it was only used in a few tests by Opera.

**Comment by marcoscaceres** [comment]
Aaaaaand found it... https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/testharness-api.md ... yay, I wasted ~2 hours.

Well, at least I know now for my own sanity what each does.

**Comment by sideshowbarker** [comment]
These are documented somewhat in https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/testharness-api.md#list-of-assertions

The specific doc for `assert_any` is at https://github.com/w3c/web-platform-tests/blob/master/docs/_writing-tests/testharness-api.md#assert_anyassert_func-actual-expected_array-extra_arg_1--extra_arg_n

> ### `assert_any(assert_func, actual, expected_array, extra_arg_1, ... extra_arg_N)`
> asserts that one `assert_func(actual, expected_array_N, extra_arg1, ..., extra_arg_N)`
> is true for some `expected_array_N` in `expected_array`. This only works for `assert_func`
> with signature `assert_func(actual, expected, args_1, ..., args_N)`. Note that tests
> with multiple allowed pass conditions are bad practice unless the spec specifically
> allows multiple behaviours. Test authors should not use this method simply to hide
> UA bugs.

As far as where the docs for the `assert_*` methods should rightly best be, and what format it should take, I think we should get @gsnedders to weigh in

**Comment by marcoscaceres** [comment]
@gsnedders, maybe we can take the examples above? WDYT?

**Comment by foolip** [comment]
@jugglinmike what's the state of this now?

**Comment by jugglinmike** [comment]
The list of assertions referenced above is available online at: https://web-platform-tests.org/writing-tests/testharness-api.html#list-of-assertions

In keeping with our recent efforts to reduce duplication and avoid rot, it would be nice to generate this information from the testharness.js source code itself. We could do that with a tool like [sphinx-js](https://pypi.org/project/sphinx-js/). That has a hard dependency on Node.js, which might be acceptable for the specific task of documentation generation.

**Comment by foolip** [comment]
I think that'd be OK, but as the first node dependency we should probably ask widely.

**Comment by gsnedders** [comment]
I think adding whatever dependencies in the container we use for the documentation generation is fine.

**Comment by marcoscaceres** [comment]
Closing as stale... treating as adequately documented.
