### ISSUE TITLE
Run continuous Travis checks (edit: Make failing status more obvious?)

### ISSUE THREAD

**Issue by qyearsley-zz** [web-platform-tests/wpt#6776]
Right now I think it's possible to introduce lint failures (or Python unit test failures) by committing directly without Travis checks ([example](https://github.com/w3c/web-platform-tests/commit/99f333d0822e6788e200b8fae3cb758be99211ff)).

AFAICT, we're not currently continuously running these tests for the master branch, but I've seen for other GitHub repos that they can have a current build status indicator (https://docs.travis-ci.com/user/status-images/).

Is this right? If so, how hard is it to enable continuous runs for some things? (I imagine stability checks would take way too long, but lint and Python tests might be reasonable?)

@gsnedders @bobholt

**Comment by gsnedders** [comment]
> Right now I think it's possible to introduce lint failures (or Python unit test failures) by committing directly without Travis checks (example).

Admins can push without passing Travis checks, though we rarely do. We could potentially just require admins to pass Travis checks first? It's sufficiently rarely used it's unlikely to make much difference. @jgraham?

> AFAICT, we're not currently continuously running these tests for the master branch, but I've seen for other GitHub repos that they can have a current build status indicator (https://docs.travis-ci.com/user/status-images/).

We do already run tests on master (indeed, it's the default Travis setup). We just rarely act on it failing. See https://travis-ci.org/w3c/web-platform-tests/branches.

**Comment by qyearsley** [comment]
Ah, neat! Do you think the reason why people don't act on it failing (which is rare) is partly because it's not obvious?

Maybe we could put the little build status badge thing on https://github.com/w3c/web-platform-tests/blob/master/README.md or maybe https://pulls.web-platform-tests.org/?
