### ISSUE TITLE
webrtc/RTCRtpTransceiver-setDirection.html expects currentDirection to be 'recvonly' when it should be 'inactive'

### ISSUE THREAD

**Issue by docfaraday** [web-platform-tests/wpt#7055]
This test case creates a recvonly transceiver, and then negotiates with an RTCPeerConnection with no transceivers. The spec says that the other side should create a new transceiver with a direction of "recvonly". When each side is in recvonly, SDP negotiation will result in an inactive media section, causing the currentDirection to be 'inactive'.

**Comment by rwaldron** [comment]
I'm trying to understand this, but the only place I'm seeing explicit steps to setting direction to _inactive_ is step 11 of [**removeTrack**](https://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-removetrack): 

> If transceiver's [[Direction]] slot is sendonly, set transceiver's [[Direction]] slot to inactive.

Can you point to whatever context I'm missing?

**Comment by docfaraday** [comment]
That's an SDP negotiation thing. See https://tools.ietf.org/html/rfc3264 section 6.1:

> If a media stream is listed as recvonly in the offer, the answer MUST be marked as sendonly or inactive in the answer.

Since the answerer doesn't want to send anything, it is going to choose inactive. Basically, when negotiating, the "send bit" in the answer is only going to be set if the offerer wants to receive, and the answerer wants to send. Similarly, the "recv bit" in the answer is only going to be set if the offerer wants to send, and the answerer wants to receive.

**Comment by dontcallmedom** [comment]
fixed in #13914
