### ISSUE TITLE
./wpt run should find browsers on macOS

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7125]
Currently, `./wpt run` just looks in `$PATH` (or `%PATH%` on Windows); on macOS, browsers are almost always installed in `/Applications` or `$HOME/Applications` and we should search these too.

**Comment by foolip** [comment]
@youennf maybe you know how one would go about this?

**Comment by gsnedders** [comment]
I think we just need a list of paths to check in `/Applications` and `$HOME/Applications`? I'm pretty sure there isn't a better way of doing this than hardcoding those paths and hardcoding a list of Application bundle names (like we already do for `firefox`, etc., on Linux), though that probably mean parsing the `Info.plist` to get the actual binary path which is a bit of a pain (Python 2's `plistlib` only supports the XML serialisation) though given we only need to do this on macOS we should be able to rely on the `psutil` tool to convert them to XML and then parse them.

**Comment by qiuzhong** [comment]
@gsnedders , PR #9806 was submitted to fix this and had been merged long ago. Can we close this issue now?

**Comment by gsnedders** [comment]
Yeah, this works for most browsers now.
