### ISSUE TITLE
Document how to run tools/wptrunner/test/testdata/

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7133]
Originally posted as https://github.com/w3c/wptrunner/issues/160 by @Ms2ger on 10 Nov 2015, 14:45 UTC:

> I wasted at least 45 minutes to try and get them running, with no success.

**Comment by foolip** [comment]
This directory still exists in tools/wptrunner/test/testdata/, and I think the answer is to run `tox` in tools/wptrunner/.

**Comment by foolip** [comment]
Do you mean it's another directly, or that these tests actually aren't run by `tox`?

**Comment by jgraham** [comment]
I think the answer is "set up an environment somehow and run `test.py` in `tools/wptrunner/test`". But I also don't think anyone has run these tests for ages and the functionality is mostly subsumed by the infrastructure tests. Created https://github.com/web-platform-tests/wpt/pull/29043 for that.

**Comment by foolip** [comment]
Closed by https://github.com/web-platform-tests/wpt/pull/29043
