### ISSUE TITLE
Feature request - simpler TypeError testing

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7153]
Originally posted as https://github.com/w3c/testharness.js/issues/62 by @sof on 29 Mar 2014, 19:20 UTC:

> The common way to test for TypeError currently appears to be
> 
>   assert_throws(new TypeError(), fun);  // or, minimally, {name: "TypeError"}.
> 
> Testing for TypeError isn't uncommon when writing API coverage tests, wanting to check if the type conversion & input value is handled as required by WebIDL and underlying spec. So, how about providing a simpler way to assert for TypeError (and other native errors, possibly)? The above form isn't as succinct as it could be, I'd argue.
> 
> If this has already been considered and decided against, my apologies.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/62#issuecomment-39007437 by @jgraham on 29 Mar 2014, 20:12 UTC:

> Yeah. You can write assert_throws(TypeError(), f) which is a bit shorter. Although maybe people will try to break that pattern in the future. Do you have a concrete suggestion for a syntax you'd prefer?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/62#issuecomment-39023251 by @sof on 30 Mar 2014, 11:30 UTC:

> That's not bad, I should have remembered that Error is callable as a function. I think it would be a worthy improvement & acceptable solution if that form was mentioned in the documentation for assert_throws() as the way to assert for native exceptions.
> 
> If it assumes too much to know your native exceptions/errors from your DOM exceptions, and read the documentation, then allowing native exception names as a (string) first argument would help test writers the most, I reckon.

**Comment by Ms2ger** [comment]
Ref: #11726

**Comment by domenic** [comment]
This is now `assert_throws_js(TypeError, fun)`, as of https://github.com/web-platform-tests/wpt/commit/993b25d482cb0e76458f384f4a23541506a10563!
