### ISSUE TITLE
`idlharness.js` incorrectly tests that `Promise<>`-returning methods throw.

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7164]
Originally posted as https://github.com/w3c/testharness.js/issues/164 by @mikewest on 20 Nov 2015, 11:16 UTC:

> Given an IDL like:
> 
> ```
> interface Whatever {
>     Promise<boolean> method(...);
> };
> ```
> 
> `idlharness` checks that `Whatever::method()` throws `TypeError` when it's called with incorrect parameters. It should instead check that the returned `Promise` is rejected with a `TypeError`.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/164#issuecomment-158401420 by @jgraham on 20 Nov 2015, 13:20 UTC:

> https://github.com/w3c/testharness.js/pull/161 perhaps?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/164#issuecomment-289381391 by @zhaoming0 on 27 Mar 2017, 08:01 UTC:

> @jgraham when we test http://w3c-test.org/webrtc/rtcpeerconnection/rtcpeerconnection-idl.html `RTCPeerConnection interface: operation setLocalDescription(RTCSessionDescription,VoidFunction,RTCPeerConnectionErrorCallback)`
> 
> The Promise attribute has throw:
>  `assert_throws: calling operation with this = null didn't throw TypeError function "function () { fn.apply(obj, args); }" did not throw`
> 
> Promise parsed "operation.idlType.generic == null"  
> ![screenshot from 2017-03-27 15-55-29](https://cloud.githubusercontent.com/assets/19921092/24346340/72e710ac-1306-11e7-97cf-bbf7fc7caaee.png)
> 
> Could you help to check it thanks

**Comment by Ms2ger** [comment]
Seems to be fixed.
