### ISSUE TITLE
Add assert_throws_exactly/promise_rejects_exactly

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7165]
Originally posted as https://github.com/w3c/testharness.js/issues/165 by @domenic on 23 Nov 2015, 22:40 UTC:

> In streams tests, there is a lot of tests that a given error is caught and turned into an appropriate promise rejection, or that an error is re-thrown from the appropriate place. For these, it would be very helpful to have a version of assert_throws/promise_rejects that tests not against the .name property, but against the exact object identity of the thrown error.
> 
> Would a pull request adding this function be accepted?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/165#issuecomment-159237447 by @Ms2ger on 24 Nov 2015, 11:32 UTC:

> There's some tests that use
> 
> ``` js
>   var test_error = { name: "test" };
> ```
> 
> for that purpose. Not entirely satisfying, though.
> 
> @jgraham wdyt?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/165#issuecomment-159353730 by @domenic on 24 Nov 2015, 17:47 UTC:

> One benefit I just noticed is that it would allow you to test that non-objects are rethrown/propagated, e.g. `undefined` or `5`.

**Comment by Ms2ger** [comment]
Ref: #11726

**Comment by domenic** [comment]
This now exists as of https://github.com/web-platform-tests/wpt/commit/993b25d482cb0e76458f384f4a23541506a10563!
