### ISSUE TITLE
Support stringifier attributes

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7167]
Originally posted as https://github.com/w3c/testharness.js/issues/171 by @Ms2ger on 29 Dec 2015, 15:12 UTC:

> Right now, we only check stringifier _operations_ (methods).

**Comment by foolip** [comment]
This was fixed in https://github.com/web-platform-tests/wpt/commit/484fd841a6fcec5dd00efbc7d420bbd9e7dcbd89.
