### ISSUE TITLE
'assert_readonly' implementation is problematic

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7169]
Originally posted as https://github.com/w3c/testharness.js/issues/177 by @DLehenbauer on 19 Jan 2016, 22:32 UTC:

> @AlexeyKor recently noticed unexpected results from 'assert_readonly()' and dug into why.  He found that the current implementation tests for readonly by attempting to set the current value and inspecting the property afterward to see if the value changed:
> 
> ``` javascript
> function assert_readonly(object, property_name, description)
> {
>     var initial_value = object[property_name];
>     try {
>         //Note that this can have side effects in the case where
>         //the property has PutForwards
>         object[property_name] = initial_value + "a"; //XXX use some other value here?
>         assert(same_value(object[property_name], initial_value),
>                    "assert_readonly", description,
>                    "changing property ${p} succeeded",
>                    {p:property_name});
>     } finally {
>         object[property_name] = initial_value;
>     }
> }
> ```
> 
> This is problematic, as `initial_value + 'a'` is not guaranteed to be valid value for the property, in which case the set attempt might throw, or be silently ignored even if the property is writable.  (This is particularly true if the property doesn't accept strings.)
> 
> I'm guessing this code predates ES5, and now should be updated to inspect the property's descriptor.  We can potentially go a step further, and ensure that attempting to set the property in a 'use strict' block throws the proper error.
> 
> If this seems uncontroversial, @AlexeyKor or I are happy to implement.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-173144646 by @Ms2ger on 20 Jan 2016, 09:33 UTC:

> I'm not sure how useful that function is anyway. Do you know if it's widely used?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-173167739 by @jgraham on 20 Jan 2016, 10:42 UTC:

> I think it is used, and I'm happy to see a better implementation (this was originally written when ES3.1 was the latest thing).

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-173259640 by @zqzhang on 20 Jan 2016, 16:24 UTC:

> Yes, a better implementation is appreciated.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-173442456 by @gsnedders on 21 Jan 2016, 03:49 UTC:

> I remember some discussion a while ago (perhaps from me immediately after testharness.js was written?) about this, and @jgraham voicing concerns as to the accuracy of property descriptors for host objects (or rather whatever they're called in ES2015 now :)), which really was justified in the days before WebIDL implementations became widespread. Perhaps we can change this now, though I certainly feel like we should have _some_ tests somewhere that host objects behave correctly wrt property descriptors.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-173443743 by @gsnedders on 21 Jan 2016, 03:52 UTC:

> For comparison, see [opjsunit's assertReadOnly](https://github.com/operasoftware/presto-testo/blob/master/core/standards/scripts/opjsunit/harness/opjsunit.js#L253) which was likely originally related.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-174045434 by @DLehenbauer on 22 Jan 2016, 20:59 UTC:

> Thanks.  The opjsunit implementation looks fundamentally like the right thing to do.  The only thing I intentionally omitted was the comparison with the initial value since, _technically_, the value of a readonly property can still change (e.g., a get accessor that returns Date.now().)

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-174193729 by @gsnedders on 23 Jan 2016, 15:27 UTC:

> Looking at this again, I'm wondering what this is actually meant to be testing: are we testing `ReadOnly` in the ES3 sense, or `readonly` in the WebIDL sense, given that would alter the expected behaviour? From memory I want to say it's meant to be the former?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-174196309 by @gsnedders on 23 Jan 2016, 16:03 UTC:

> A brief look makes it look like it's only really used in the WebIDL sense, regardless of the original intention (which I want to say was the ES3 sense, but this was obviously many years ago!). I'd push for moving current usage over to `idlharness.js` (which does a far better test of property descriptors), and drop `assert_readonly`, I think. @jgraham, thoughts?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-174196431 by @gsnedders on 23 Jan 2016, 16:05 UTC:

> @Ms2ger: usage is
> 
> ```
> ./ambient-light/DeviceLightEvent_tests.js:    assert_readonly(event, 'value', 'readonly attribute value');
> ./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'root');
> ./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'whatToShow');
> ./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'filter');
> ./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'referenceNode');
> ./dom/traversal/NodeIterator.html:    assert_readonly(iter, 'pointerBeforeReferenceNode');
> ./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'root');
> ./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'whatToShow');
> ./dom/traversal/TreeWalker-basic.html:    assert_readonly(walker, 'filter');
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./html/semantics/scripting-1/the-template-element/template-element/content-attribute.html:    assert_readonly(template, 'content',
> ./IndexedDB/idbcursor-direction.htm:                assert_readonly(cursor, 'direction');
> ./IndexedDB/idbcursor-direction.htm:                assert_readonly(cursor, 'direction');
> ./IndexedDB/idbcursor-key.htm:                assert_readonly(cursor, 'key');
> ./IndexedDB/idbcursor-primarykey.htm:                assert_readonly(cursor, 'primaryKey');
> ./IndexedDB/idbcursor-source.htm:            assert_readonly(cursor, 'source');
> ./pointerevents/pointerevent_support.js:                assert_readonly(event.type, name, event.type + "." + name + " cannot be changed");
> ./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'value', 'readonly attribute value');
> ./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'min', 'readonly attribute min');
> ./proximity/DeviceProximityEvent_tests.js:        assert_readonly(event, 'max', 'readonly attribute max');
> ./proximity/UserProximityEvent_tests.js:        assert_readonly(event, 'near', 'readonly attribute near');
> ```
> 
> So only 11 files in all of w-p-t…

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/testharness.js/issues/177#issuecomment-176675116 by @Ms2ger on 29 Jan 2016, 09:59 UTC:

> I would be happy to remove it, but will leave the decision to @jgraham. We should probably also check CSS tests.

**Comment by rwaldron** [comment]
@gsnedders what is the action item here? It it just "fix 'assert_readonly'". I looked at https://github.com/operasoftware/presto-testo/blob/master/core/standards/scripts/opjsunit/harness/opjsunit.js#L253 and compared it to test262's [`isWritable(...)`](https://github.com/tc39/test262/blob/c23ea89fe254a498b47fa6efdec908aa1551971d/harness/propertyHelper.js#L122-L150) which is used to implement [`verifyNotWritable(...)`](https://github.com/tc39/test262/blob/c23ea89fe254a498b47fa6efdec908aa1551971d/harness/propertyHelper.js#L169-L177) and most of the important parts of the logic are sound. Is it appropriate to just assign myself?

**Comment by gsnedders** [comment]
@rwaldron Pretty sure it is just fix `assert_readonly`. Go ahead and assign yourself!

**Comment by gsnedders** [comment]
Rereading the above, I think the concern is WebIDL objects that have custom [[Set]] or [[DefineOwnProperty]] behaviour (or just getter/setters) and only allow assignment of certain types? Therefore, unlike `opjsunit` or the current `testharness.js` behaviour you really need a way to set a custom value.

**Comment by rwaldron** [comment]
> Therefore, unlike opjsunit or the current testharness.js behaviour you really need a way to set a custom value.

Yes, test262 has a similar requirement.

**Comment by csnardi** [comment]
I just ran into this on a CSSOM test, fixed with https://crrev.com/c/989407. Perhaps if this isn't going to be changed soon, there should be some documentation that `assert_readonly` can have side-effects it's an IDL object with the `[PutForwards]` attribute, as that mystified me for a while.

**Comment by Ms2ger** [comment]
Would it be a problem if we changed it to something like `assert(Object.getOwnPropertyDescriptor(o, p).writable)`? It seems unnecessarily surprising for one of the `assert_` functions to try to mutate its argument, and not particularly likely to find additional bugs.

**Comment by jgraham** [comment]
That seems reasonable to me.

**Comment by csnardi** [comment]
I don't think `Object.getOwnPropertyDescriptor()` would work for IDL properties, since `hasOwnProperty` returns `false`.

**Comment by gsnedders** [comment]
@Ms2ger @csnardi Yeah, it couldn't be just that, we'd have to walk the prototype chain until we found a property descriptor.

**Comment by gsnedders** [comment]
See also: https://github.com/web-platform-tests/wpt/blob/bb5b9decf3acfe01670b8296ed79b63e921bc7c5/resources/idlharness.js#L1464-L1465

https://github.com/web-platform-tests/wpt/blob/bb5b9decf3acfe01670b8296ed79b63e921bc7c5/dom/interface-objects.html effectively duplicates what idlharness _could_ test if it actually went beyond `getOwnPropertyDescriptor`.

(Also, as a historical aside, I'm pretty sure `assert_readonly` is ultimately derived from [opjsunit's `assertReadOnly`](https://github.com/operasoftware/presto-testo/blob/3edb42b3d6f647a8ece431ac39cadd841c946b0f/core/standards/scripts/opjsunit/harness/opjsunit.js#L253-L289), which clearly later _did_ also check descriptors.)
