### ISSUE TITLE
Update html5lib

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7200]
Originally posted as https://github.com/w3c/wpt-tools/issues/138 by @jdm on 03 Nov 2016, 14:11 UTC:

> It's out of date, and relying on python packages that are unmaintained.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wpt-tools/issues/138#issuecomment-260723167 by @gsnedders on 15 Nov 2016, 18:22 UTC:

> I thought we wanted to keep the vendored packages stable for the sake of tests that rely on them (e.g., the WebDriver tests). @jgraham?

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wpt-tools/issues/138#issuecomment-260896797 by @jgraham on 16 Nov 2016, 09:29 UTC:

> I don't think the webdriver tests rely on html5lib.

**Comment by foolip** [comment]
All open PRs now have a failing check called pyup.io/safety-ci that says "html5lib 0.9999999 has known security vulnerabilities."

How would we actually go about upgrading it?

**Comment by foolip** [comment]
@jgraham, did you enable this check?

**Comment by foolip** [comment]
Per https://github.com/html5lib/html5lib-python/blob/master/CHANGES.rst it looks like the latest release, the only one we could upgrade to, drops support for Python 2.6. Now what?

**Comment by foolip** [comment]
Oh, there's Python 2.7, ignore me.

**Comment by jgraham** [comment]
I (think I have) disabled this check now

**Comment by jgraham** [comment]
Oh and re:  this specific issue; it's the copy used by the css build system and @gsnedders claims we can't just update it because there's a bug in build system that means it's relying on a specific release.

I'm basically always happy to break the CSS build system, but maybe that's not the best way forward :)

**Comment by foolip** [comment]
@gsnedders, can you elaborate a bit on what it'd take, and if there would be any benefit from doing so?

**Comment by gsnedders** [comment]
Honestly I'd rather just avoid touching the CSS build system and leave it with its own, specific, outdated dependencies and not bother trying to update it. If it's broken as is, it's all the more reason for people to not depend on it, but making it more broken is unlikely to make us popular with people around CSS land.

**Comment by gsnedders** [comment]
https://lists.w3.org/Archives/Public/public-css-testsuite/2018Feb/0001.html fixes the w3ctestlib side; we can update it here once that lands.

**Comment by gsnedders** [comment]
The above seems really confused, the original issue was about `tools/html5lib`, which is totally unrelated to what the CSS testsuite build system does.
