### ISSUE TITLE
Add recursive option to lint

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#7209]
Originally posted as https://github.com/w3c/wpt-tools/issues/184 by @gsnedders on 14 Mar 2017, 17:24 UTC:

> `./lint -r html` should lint everything within `html`; the current mess of needing something like `find html -type f -print0 | xargs -0 ./lint` should go away.

**Comment by foolip** [comment]
It's recursive by default now, I introduced a lint error and could see it listed with `./wpt lint fullscreen`.
