### ISSUE TITLE
"Build PENDING" emails are confusing

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#7255]
As comments from @w3c-bots are edited in place, contributors are sent a "Build PENDING" email, but never get a "Build COMPLETED" email.

I understand why this is happening as I'm familiar with the underlying infra, but I doubt all contributors are.

Could we fix this by avoiding to send an email at all? For example by editing the original post instead of creating a new comment?

**Comment by foolip** [comment]
I think that the long-ish term fix here would be that the status checks by themselves are useful and we don't need a separate comment. The remaining case would be FYI comments like https://github.com/w3c/web-platform-tests/issues/7475, but those would happen once the results are done and useful.

@jgraham, do you recall why we've decided to not update the original comment?

**Comment by foolip** [comment]
These emails myst have been from Travis, closing.
