### ISSUE TITLE
HTTP/2 tests for statusText

### ISSUE THREAD

**Issue by annevk** [web-platform-tests/wpt#7274]
HTTP/2 doesn't have a HTTP's reason phrase concept and doesn't really define what it should be in legacy APIs either... So in https://github.com/whatwg/fetch/issues/599 I decided to side with Chrome and make it the empty byte sequence. However, that cannot really be tested at the moment.

**Comment by foolip** [comment]
Removing infra label until there's a suggestion for how to fix it that involves infra.

**Comment by annevk** [comment]
We need a HTTP/2 backend for this. Basically a new use case for #8371. I guess we can dupe against that.

**Comment by annevk** [comment]
Actually reopening as it's useful to track this against fetch/xhr.
