### ISSUE TITLE
Automating fullscreen tests

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7281]
Even after #6897 lands we won't be able to automate fullscreen tests; we run testharness.js tests with two windows, where WebDriver has the parent window as the current browsing context and the test window is an auxiliary browsing context of that.

To enter fullscreen, we need a user-initiated click. With #6897, we do this by switching the current browsing context to the window that wants the click, clicking, then switching back to the parent window. However, in current implementations the OS focus follows the current top-level browsing context (AFAICT), and therefore when we change back to the parent window we move out of fullscreen (because on at least some platforms you can't have another window having focus while something is fullscreen). This makes testing fullscreen currently impossible.

cc/ @foolip

**Comment by foolip** [comment]
@JKereliuk, this is the issue I mentioned.

**Comment by foolip** [comment]
What would a fix for this have to look like? What is the fundamental reason that it matters for WebDriver which window has focus?

**Comment by JKereliuk** [comment]
Whoops I missed this, I am going to take closer look at these tests

**Comment by foolip** [comment]
After https://github.com/web-platform-tests/wpt/pull/13419 it's probably possible to use `test_driver.bless` to automate some fullscreen tests, at least the ones that don't involve iframes.
