### ISSUE TITLE
Be able to send complex pointer-events interactions

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7435]
This should be based on https://w3c.github.io/webdriver/webdriver-spec.html#actions and probably expose an API similar to http://searchfox.org/mozilla-central/rev/2ef8bd8a46a02c68ddbb1d5f25fa254dd7be1fbd/testing/marionette/client/marionette_driver/marionette.py#200

cc/ @NavidZ

**Comment by foolip** [comment]
@kereliuk this is still on track for "soon", right? (Doing the rotation.)

**Comment by foolip** [comment]
@kereliuk, was this resolved already?

**Comment by gsnedders** [comment]
Doesn't appear to be anything in testdriver.js for it.

**Comment by foolip** [comment]
There's some WIP in https://github.com/web-platform-tests/wpt/pull/11931

**Comment by foolip** [comment]
@NavidZ @SummerLW should this be assigned to one of you?

**Comment by NavidZ** [comment]
Sure. Keep it assigned to me. I guess I need to add some documentation about the synthetic pointer actions as well. I remember there was a test driver documentation some where around here.

**Comment by foolip** [comment]
Documentation is at https://web-platform-tests.org/writing-tests/testdriver.html

**Comment by mdittmer** [comment]
Friendly ecosystem infra rotation nudge to @NavidZ. Any updates on adding documentation?

**Comment by NavidZ** [comment]
@jgraham I was planning to only explain the builder API directly to make sure people hopefully use that instead of directly calling in action_sequence. Are you okay with that?

**Comment by jgraham** [comment]
Yes, for sure.

**Comment by lukebjerring** [comment]
@NavidZ - any updates?

**Comment by NavidZ** [comment]
I did update the documentation. I guess I did it inline and forgot to mention it in this bug.
