### ISSUE TITLE
Get rid of copies of Ahem in css/vendor-imports/mozilla/mozilla-central-reftests/

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7437]
cc/ @jgraham @dbaron 

Continuation of #7372, and the remainder of #7352.

**Comment by dbaron** [comment]
This is a bit of a pain...

**Comment by foolip** [comment]
Can we fold this into into a "get rid of css/vendor-imports/" issue? Seems like there's not much point in just consolidating Ahem here.

**Comment by foolip** [comment]
Found https://github.com/web-platform-tests/wpt/issues/8615, closing in favor of that.
