### ISSUE TITLE
Consolidate Payment Request valid/invalid data

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#7459]
Now that the test suite for Payment Request is mostly written, we should consolidate the valid/invalid data inputs into a single file, as they are basically the same across all the tests. 

This would not only reduce the tests significantly, it would give us a central point from which to send good an bad data into the tests (progressively making tests data more evil if need be :)).

**Comment by marcoscaceres** [comment]
We could also do fun things, like automatically fuzz object's getters.

**Comment by foolip** [comment]
@marcoscaceres does this still need doing? (Looking through old issues...)

**Comment by marcoscaceres** [comment]
No, we can do this internally for each engine. For WPT, we will just stick to showing interoperability.
