### ISSUE TITLE
Wrong messages for table integrity checks in messages.josn

### ISSUE THREAD

**Issue by dd8** [web-platform-tests/wpt#7539]
The conformance-checkers/messages.json file seems to have incorrect messages for some of the the table integrity checks:

Previously the messages.json file contained messages about table integrity:

-    "html/elements/table/integrity/Alexis_of_Russia-novalid.html": "The \u201calign\u201d attribute on the \u201ctable\u201d element is obsolete. Use CSS instead.",
-    "html/elements/table/integrity/Feodor_I_of_Russia-novalid.html": "The \u201calign\u201d attribute on the \u201ctable\u201d element is obsolete. Use CSS instead.",
-    "html/elements/table/integrity/Naser_al-Din_Shah_Qajar-novalid.html": "An \u201cimg\u201d element must have an \u201calt\u201d attribute, except under certain conditions. For details, consult guidance on providing text alternatives for images.",

Now messages.json expects an error message about rel=copyright for html/elements/table/integrity

+    "html/elements/table/integrity/Alexis_of_Russia-novalid.html": "Bad value \u201ccopyright\u201d for attribute \u201crel\u201d on element \u201clink\u201d: Bad list of link-type keywords: The keyword \u201ccopyright\u201d for the \u201crel\u201d attribute should not be used. Consider using \u201clicense\u201d instead.",
+    "html/elements/table/integrity/Feodor_I_of_Russia-novalid.html": "Bad value \u201ccopyright\u201d for attribute \u201crel\u201d on element \u201clink\u201d: Bad list of link-type keywords: The keyword \u201ccopyright\u201d for the \u201crel\u201d attribute should not be used. Consider using \u201clicense\u201d instead.",
+    "html/elements/table/integrity/Naser_al-Din_Shah_Qajar-novalid.html": "Bad value \u201ccopyright\u201d for attribute \u201crel\u201d on element \u201clink\u201d: Bad list of link-type keywords: The keyword \u201ccopyright\u201d for the \u201crel\u201d attribute should not be used. Consider using \u201clicense\u201d instead.",

Best
Mark

**Comment by dd8** [comment]
I think was fixed in this commit
https://github.com/validator/tests/commit/5a844ada90f534e950383d5b632c1f1c9ca2f61d

**Comment by sideshowbarker** [comment]
Closing per https://github.com/web-platform-tests/wpt/issues/7539#issuecomment-408689282
