### ISSUE TITLE
Consider adding a lint for files with the same basename in the same directory

### ISSUE THREAD

**Issue by Ms2ger** [web-platform-tests/wpt#7570]
This causes issues for Blink/WebKit at this time; see https://github.com/w3c/web-platform-tests/pull/7569. I'd argue it's not a very good idea in general anyway.

**Comment by foolip** [comment]
This is creating trouble in https://bugs.chromium.org/p/chromium/issues/detail?id=764662, so giving this the roadmap label, so that it doesn't stay unfixed forever. (A weak promise, yes.)

**Comment by foolip** [comment]
@Hexcles, can you take a peek at the Chromium-side issue to see if fixing that is at all feasible? I think a lint here should be pretty easy to do, since `check_css_globally_unique` already does something more complicated.

**Comment by Hexcles** [comment]
@foolip Thanks for the pointer. The Chromium-side issue seems rather complicated. Dir + basename are used as the names of tests in **many** places, including but not limited to run-webkit-tests, result merger/viewer, rebaseline tools, bots, etc. To fix it, we need to have a major refactor over the whole Layout Test infra, which is likely a multi-quarter effort. WebKit is on the same boat.

**Comment by foolip** [comment]
OK, so adding a lint for it in wpt seems like the right choice, then.

**Comment by gsnedders** [comment]
See also: https://github.com/w3c/wpt-tools/pull/40

**Comment by foolip** [comment]
@Hexcles, in terms of Blink infra work, this sounds a bit similar to the assumptions made in https://crbug.com/800570 about variants. Is this a similar case, that we can/should fix in Blink, or would it be better to just have a lint as suggested?

**Comment by Hexcles** [comment]
@foolip after the refactor done in https://crbug.com/800570, it's indeed a bit easier to change the code to include extensions in test names. However, changing the naming scheme as such would require renaming all existing baselines. And someone still needs to fix WebKit infra, too.

**Comment by foolip** [comment]
@youennf, any thoughts on what we should do here?

@thejohnjansen is this creating trouble for EdgeHTML's use of WPT?

**Comment by jgraham** [comment]
So the change here would be to add a lint to the `all_paths_lints` set in `tools/lint/lint.py` that checks if there are any paths  in which `os.path.splitext(path)[0]` has multiple identical values.

**Comment by jgraham** [comment]
It's possible that the lint will initially fail; if it does we may need to rename some things to make it pass.

**Comment by kriti21** [comment]
I want to work on this.

**Comment by stephenmcgruer** [comment]
Incidentally, this hit us again the other day in Chrome with `dom/nodes/Document-createCDATASection.xhtml` and `dom/nodes/Document-createCDATASection.html`.
