### ISSUE TITLE
Add support for namespaces in idlharness

### ISSUE THREAD

**Issue by tobie** [web-platform-tests/wpt#7583]
See: #7551.

**Comment by bzbarsky** [comment]
At this point is this more or less blocking tests being created for https://github.com/w3c/csswg-drafts/pull/437 and to some extent UAs updating to that spec change...

**Comment by lukebjerring** [comment]
Blocking https://github.com/web-platform-tests/wpt/pull/11768

**Comment by lukebjerring** [comment]
FYI, I'm taking a stab at this.
