### ISSUE TITLE
No way to test paged media

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7760]
CSS has quite a lot of properties to control paged media (most obviously `page-break-before`/`-after`, etc.), and we currently have no way of testing these. We should probably have some sort of reftests that test print behaviour, probably by printing to PDF and then comparing. We may want to just reuse the Mozilla `reftest-print` class for this.

**Comment by JKereliuk** [comment]
@gsnedders Do you know any manual tests for these?

**Comment by gsnedders** [comment]
@JKereliuk see every test with the CSS metadata flag of "paged", so currently:

```
css/CSS2/backgrounds/background-attachment-010.xht
css/CSS2/box-display/containing-block-024.xht
css/CSS2/box-display/containing-block-025.xht
css/CSS2/cascade/at-import-008.xht
css/CSS2/margin-padding-clear/margin-collapse-160.xht
css/CSS2/page-box/at-page-rule-001.xht
css/CSS2/page-box/at-page-rule-002-a.xht
css/CSS2/page-box/at-page-rule-002-b.xht
css/CSS2/page-box/at-page-rule-002-c.xht
css/CSS2/page-box/first-page-selectors-001.xht
css/CSS2/page-box/first-page-selectors-002.xht
css/CSS2/page-box/first-page-selectors-003.xht
css/CSS2/page-box/first-page-selectors-004.xht
css/CSS2/page-box/page-box-000.xht
css/CSS2/page-box/page-container-000.xht
css/CSS2/page-box/page-container-001.xht
css/CSS2/page-box/page-container-002.xht
css/CSS2/page-box/page-container-003.xht
css/CSS2/page-box/page-container-004.xht
css/CSS2/page-box/page-container-005.xht
css/CSS2/page-box/page-container-006.xht
css/CSS2/page-box/page-container-007.xht
css/CSS2/page-box/page-container-008.xht
css/CSS2/page-box/page-container-009.xht
css/CSS2/page-box/page-container-010.xht
css/CSS2/page-box/page-container-011.xht
css/CSS2/page-box/page-grammar-001.xht
css/CSS2/page-box/page-grammar-002.xht
css/CSS2/page-box/page-margin-000.xht
css/CSS2/page-box/page-margin-001.xht
css/CSS2/page-box/page-margin-002.xht
css/CSS2/page-box/page-props-100-a.xht
css/CSS2/page-box/page-props-100-b.xht
css/CSS2/page-box/page-props-101.xht
css/CSS2/page-box/page-props-102.xht
css/CSS2/page-box/page-props-103.xht
css/CSS2/page-box/page-selectors-001.xht
css/CSS2/page-box/page-selectors-002.xht
css/CSS2/page-box/page-selectors-003.xht
css/CSS2/page-box/page-selectors-004.xht
css/CSS2/page-box/page-selectors-006.xht
css/CSS2/pagination/allowed-page-breaks-001a.xht
css/CSS2/pagination/allowed-page-breaks-001b.xht
css/CSS2/pagination/allowed-page-breaks-001c.xht
css/CSS2/pagination/allowed-page-breaks-002.xht
css/CSS2/pagination/allowed-page-breaks-003.xht
css/CSS2/pagination/allowed-page-breaks-004.xht
css/CSS2/pagination/allowed-page-breaks-005.xht
css/CSS2/pagination/allowed-page-breaks-006.xht
css/CSS2/pagination/allowed-page-breaks-007a.xht
css/CSS2/pagination/allowed-page-breaks-007b.xht
css/CSS2/pagination/forced-page-breaks-000.xht
css/CSS2/pagination/forced-page-breaks-001.xht
css/CSS2/pagination/orphans-001.xht
css/CSS2/pagination/orphans-002.xht
css/CSS2/pagination/orphans-003.xht
css/CSS2/pagination/orphans-004a.xht
css/CSS2/pagination/orphans-004b.xht
css/CSS2/pagination/page-break-after-000.xht
css/CSS2/pagination/page-break-after-001.xht
css/CSS2/pagination/page-break-after-002.xht
css/CSS2/pagination/page-break-after-003.xht
css/CSS2/pagination/page-break-after-004.xht
css/CSS2/pagination/page-break-after-005.xht
css/CSS2/pagination/page-break-after-007.xht
css/CSS2/pagination/page-break-after-008.xht
css/CSS2/pagination/page-break-after-009.xht
css/CSS2/pagination/page-break-after-010.xht
css/CSS2/pagination/page-break-before-000.xht
css/CSS2/pagination/page-break-before-001.xht
css/CSS2/pagination/page-break-before-002.xht
css/CSS2/pagination/page-break-before-003.xht
css/CSS2/pagination/page-break-before-004.xht
css/CSS2/pagination/page-break-before-005.xht
css/CSS2/pagination/page-break-before-006.xht
css/CSS2/pagination/page-break-before-007-b.xht
css/CSS2/pagination/page-break-before-007.xht
css/CSS2/pagination/page-break-before-008.xht
css/CSS2/pagination/page-break-before-009.xht
css/CSS2/pagination/page-break-before-010.xht
css/CSS2/pagination/page-break-before-011.xht
css/CSS2/pagination/page-break-before-020.xht
css/CSS2/pagination/page-break-inside-000.xht
css/CSS2/pagination/page-break-inside-001.xht
css/CSS2/pagination/page-break-inside-002.xht
css/CSS2/pagination/page-break-inside-003.xht
css/CSS2/pagination/page-break-inside-004.xht
css/CSS2/pagination/page-break-inside-005.xht
css/CSS2/pagination/page-break-inside-006.xht
css/CSS2/pagination/page-break-margins-001.xht
css/CSS2/pagination/page-break-margins-002.xht
css/CSS2/pagination/page-break-margins-003.xht
css/CSS2/pagination/page-break-margins-004.xht
css/CSS2/pagination/page-breaks-100.xht
css/CSS2/pagination/page-breaks-101.xht
css/CSS2/pagination/widows-001.xht
css/CSS2/pagination/widows-002.xht
css/CSS2/pagination/widows-003.xht
css/CSS2/pagination/widows-004a.xht
css/CSS2/pagination/widows-004b.xht
css/CSS2/positioning/abspos-paged-001.xht
css/CSS2/positioning/abspos-paged-002.xht
css/CSS2/positioning/position-fixed-004.xht
css/CSS2/positioning/position-fixed-005.xht
css/CSS2/tables/table-footer-group-004.xht
css/CSS2/tables/table-header-group-004.xht
css/CSS2/ui/overflow-print-001.xht
css/css-flexbox/interactive/flexbox_interactive_break-after-column-item.html
css/css-flexbox/interactive/flexbox_interactive_break-after-column-lastitem.html
css/css-flexbox/interactive/flexbox_interactive_break-after-container.html
css/css-flexbox/interactive/flexbox_interactive_break-after-item.html
css/css-flexbox/interactive/flexbox_interactive_break-after-line-order.html
css/css-flexbox/interactive/flexbox_interactive_break-after-line.html
css/css-flexbox/interactive/flexbox_interactive_break-after-multiline.html
css/css-flexbox/interactive/flexbox_interactive_break-before-column-firstitem.html
css/css-flexbox/interactive/flexbox_interactive_break-before-column-item.html
css/css-flexbox/interactive/flexbox_interactive_break-before-container.html
css/css-flexbox/interactive/flexbox_interactive_break-before-item.html
css/css-flexbox/interactive/flexbox_interactive_break-before-multiline.html
css/css-flexbox/interactive/flexbox_interactive_break-natural.html
css/css-flexbox/interactive/flexbox_interactive_paged-overflow-2.html
css/css-flexbox/interactive/flexbox_interactive_paged-overflow.html
css/css-gcpm/leader-001.html
css/css-gcpm/leader-002.html
css/css-gcpm/leader-003.html
css/css-gcpm/string-set-001.html
css/css-gcpm/string-set-002.html
css/css-gcpm/string-set-003.html
css/css-gcpm/string-set-004.html
css/css-gcpm/string-set-005.html
css/css-gcpm/string-set-006.html
css/css-gcpm/string-set-007.html
css/css-gcpm/string-set-008.html
css/css-gcpm/string-set-009.html
css/css-gcpm/string-set-010.html
css/css-gcpm/string-set-011.html
css/css-gcpm/string-set-012.html
css/css-gcpm/using-strings-001.html
css/css-gcpm/using-strings-002.html
css/css-gcpm/using-strings-003.html
css/css-gcpm/using-strings-004.html
css/css-gcpm/using-strings-005.html
css/css-page/forced-page-breaks-002.xht
css/css-page/page-background-000.xht
css/css-page/page-borders-000.xht
css/css-page/page-counters-000.xht
css/css-page/page-margin-003.xht
css/css-page/page-name-000.xht
css/css-page/page-properties-000.xht
css/css-page/page-size-000.xht
css/css-page/page-size-001.xht
css/css-page/page-size-002.xht
css/css-page/page-size-003.xht
css/css-page/page-size-004.xht
css/css-page/page-size-005.xht
css/css-page/page-size-006.xht
css/css-page/page-size-007.xht
css/css-page/page-size-008.xht
css/css-page/page-size-009.xht
css/css-page/page-size-010.xht
css/css-writing-modes/first-page-vlr-003.xht
css/css-writing-modes/first-page-vrl-002.xht
css/css-writing-modes/page-flow-direction-002.xht
css/css-writing-modes/page-flow-direction-003.xht
css/css-writing-modes/page-flow-direction-slr-005.xht
css/css-writing-modes/page-flow-direction-srl-004.xht
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-10.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-11.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-12.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-13.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-14.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-15.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-2.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-3.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-4.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-5.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-6.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-7.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-8.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-block-page-break-inside-avoid-9.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-2.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-3.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-4.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-5.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-6.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-7.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-8.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-float-page-break-inside-avoid-9.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-inline-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-row-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-row-page-break-inside-avoid-2.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-2.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-3.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-4.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-5.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-6.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-7.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-rowgroup-page-break-inside-avoid-8.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-1.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-2.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-3.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-4.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-5.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-6.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-7.html
css/vendor-imports/mozilla/mozilla-central-reftests/css21/pagination/moz-css21-table-page-break-inside-avoid-8.html
css/vendor-imports/mozilla/mozilla-central-reftests/multicol3/moz-multicol3-column-balancing-break-inside-avoid-1.html
```

**Comment by fantasai** [comment]
Antenna House has tooling to compare PDFs, which they use for regression testing. Just talked to their AC rep, Michael Miller `mike@antennahouse.com`; he says they'd be willing to license the tool in exchange for publicity. If we can get the browser engines to spit out PDFs (which they can all do, just not sure about programmatically), should be possible to set up automated reftests for print that way.

Note - We'll want to set up the default page size to match what Mozilla uses for its print reftests.

**Comment by fantasai** [comment]
This would also mean that we can set up CSS-to-PDF engines to run reftests in general, fwiw.

**Comment by jgraham** [comment]
@emilio had to write gecko-specific reftests for overflow media queries because we don't have this c.f. https://bugzilla.mozilla.org/show_bug.cgi?id=1422235

**Comment by gsnedders** [comment]
I don't think adding support for this in Firefox would be overly hard, at least if we're happy to accept an array of PNGs (and really I think that's fine).

Don't know about Chromium (@Hexcles? @LukeZielinski?); IIRC the current testing there relies on `testRunner.setPrinting()` which doesn't exist in Chromium builds.

**Comment by gsnedders** [comment]
I think we should at least agree how we're going to label these so we can rename everything in #5381 and not have things bounce between different filenames.

I think we've had two suggestions:

 * `:root.reftest-paged` class
 * `.paged.` meta flag

I don't think I have a strong opinion here.

**Comment by jgraham** [comment]
The former is how gecko does things but doesn't really match any pattern we have; the design in wpt is that we use functional elements to identify test types where possible and metadata in filenames where it isn't. In this case I don't think there's an appropriate functional element to use, so filename metadata is the consistent design.

**Comment by fantasai** [comment]
> I don't think adding support for this in Firefox would be overly hard, at least if we're happy to accept an array of PNGs (and really I think that's fine).

Firefox is able to generate PDFs through the print dialog, at least here on Linux. I think it'd be better if we can hook things up with PDFs, because then we can get a lot more CSS engines into WPT.

I don't have an opinion about how to flag these tests in WPT. I do have an opinion that the Firefox reftest convention for default page sizes and margins is the one we want to use.

**Comment by gsnedders** [comment]
> Firefox is able to generate PDFs through the print dialog, at least here on Linux.

Firefox can certainly generate PDFs, but it's harder to implement generally given all the reftest tooling assumes PNGs.

> I think it'd be better if we can hook things up with PDFs, because then we can get a lot more CSS engines into WPT.

I guess the question is whether we gain much by using the actual PDFs, assuming PDF->PNG conversion is deterministic (which I'd hope most rasterisers are?). It doesn't really matter what the actual output from the UA is provided we can convert it.

**Comment by jugglinmike** [comment]
For these tests to be automated, we'll need to generate reference PDFs. Is that possible for features like paged media? Or will we be limited to `rel=mismatch`?

**Comment by gsnedders** [comment]
@jugglinmike Why would they be any different to any other reftest? We just have another HTML file as a reference, also rendered in print mode (to PDFs or PNGs or whatever). (We already have a fair number in the CSS test suite, though they aren't currently run anywhere as far as I'm aware.)

**Comment by jugglinmike** [comment]
@gsnedders With reftests for screen rendering, we generally write reference documents that simulate advanced features using simpler/older features (e.g. simulating flexbox layout with absolutely-positioned elements).

I don't know how we can simulate something like `break-before`. If we're able to control for enough aspects of the printed page, can absolute positioning be used to simulate this, too?

**Comment by gsnedders** [comment]
@jugglinmike Right, so I think it's true we can't test the *really* simple case (note that we have the same problem elsewhere; we don't ever actually test that color: green outputs something in green, because we'd need some external reference format). In practice, relying on manual testing for a few super-simple cases is good enough.

**Comment by MatsPalmgren** [comment]
It makes me sad that we can't write print mode WPTs to test UA interoperability in this area.
Given that both Chrome and Firefox are currently actively working on improving fragmentation support in general it would really benefit both teams if it would be possible to write WPTs for this.
CC @dbaron

**Comment by jgraham** [comment]
As documented in this thread, @gsnedders has a plan. I don't know what their schedule looks like, but if this is a priority for gecko layout developers we should talk because I think we could plan to do the work early next year.

**Comment by gsnedders** [comment]
From my point of view: I have a plan, it's not a priority as far as those funding me are currently concerned (as print remains relatively niche and not a significant interop issue for users, and other fragmentation cases like multicol can be tested with those features), and therefore it's likely to remain a plan for the foreseeable future unless someone pays me to do it.

**Comment by dbaron** [comment]
I should note that the Gecko reftest harness renamed what used to be called `reftest-print` to [`reftest-paged`](https://searchfox.org/mozilla-central/rev/131338e5017bc0283d86fb73844407b9a2155c98/layout/tools/reftest/README.txt#650-679) to avoid confusion with a newer [print testing mechanism](https://searchfox.org/mozilla-central/rev/131338e5017bc0283d86fb73844407b9a2155c98/layout/tools/reftest/README.txt#304-348).

**Comment by gsnedders** [comment]
> a newer [print testing mechanism](https://searchfox.org/mozilla-central/rev/131338e5017bc0283d86fb73844407b9a2155c98/layout/tools/reftest/README.txt#304-348).

That makes it sound like we probably want to have *both* paged and print output tests?

**Comment by dbaron** [comment]
I think the newish print testing mechanism is currently used mainly for pretty implementation-specific things... although that's also because it's currently pretty limited in how it does comparisons.  It's likely possible to design a single mechanism that has the advantages of both.

**Comment by jwatt** [comment]
I was going to make this comment on RFC #41, but I'll put it here for wider feedback.

For visual comparison print/pagination tests, I think it would be desirable for the **format/metadata** to be agnostic about whether or not the implementation actually generates a PDF, or whether it has the ability to snapshot the pages from the laid out document prior to the point when the PDF would be created (similar to Mozilla's current reftest-paged implementation).

My rational here is that by far the most common bugs that Mozilla has related to printing is in the pagination code (it is fairly rare for things to go wrong between that point and the user getting their print output). Actually creating a PDF is going to be considerably slower (at least in Mozilla) than doing the paginated layout, so for most pagination tests (or perhaps for most of the CI runs) we we may want to avoid slowing down CI/increasing service costs by skipping the PDF generation step.

However, we do sometimes want to test the structure of the print/PDF output as opposed to its visual output for some combinations of web platform features (for which Mozilla has the 'print' tests, as opposed to the 'reftest-paged' tests). We have had fidelity issues related to content that should be output as print/PDF **vector** commands (text/rounded borders/SVG paths), but has ended up being pre-rasterized and inserted into the print/PDF output as an image instead. That has then resulted in things like the barcodes on printed boarding passes being unreadable by the readers, or things just visually looking bad on paper (given the high DPI nature of printing), or pixilation when zooming into PDFs. To avoid this it's useful to be able to write tests to examine the internal structure of a PDF to check for the presense of specific strings, or that a certain number of a specific type of path commands exist.

It may make most sense if a given test can be used for both visual and structural testing. I.e. for it to be possible for a given test to have both a series of references (one per page) **and/or** a file with a list of assertions about the internal structure of the PDF file that should be generated from the test.

Another thing to consider is whether the per-page references should be static images or HTML files. I'm guessing HTML files.

Finally, we may find that long term it is too restrictive to have a single page size. A mechanism to be able to specify things like the page size and the margins that should be used for a test may be useful.

**Comment by gsnedders** [comment]
@jwatt I guess one relevant question wrt the format is whether we expect `@page` to apply? I _think_ the answer for `reftest-paged` is that it does?

> For visual comparison print/pagination tests, I think it would be desirable for the format/metadata to be agnostic about whether or not the implementation actually generates a PDF, or whether it has the ability to snapshot the pages from the laid out document prior to the point when the PDF would be created (similar to Mozilla's current reftest-paged implementation).

I think we're unlikely to define the format to be more than "generate the print version of two documents and compare them pixel-for-pixel page-by-page"? In general we've been kinda fuzzy about defining these things beyond wptrunner's implementation (which will almost certainly use PDFs in the first instance, given that's what's exposed over Marionette & CDP currently).

> To avoid this it's useful to be able to write tests to examine the internal structure of a PDF to check for the presense of specific strings, or that a certain number of a specific type of path commands exist.

I wonder how useful and how fragile such tests would be cross-browser? (Does this seem something we can address after the visual side?)

> Another thing to consider is whether the per-page references should be static images or HTML files. I'm guessing HTML files.

CSS has way too much undefined behaviour for the answer to be static images. :(

**Comment by dbaron** [comment]
I'd note there are a few different options for references:
* test and reference are both things that paginate, and must produce the same output (perhaps just the same output within the first N pages, e.g., in the Firefox harness it uses a fixed page size and fits three pages at that size; differences in later pages don't affect the result just like differences outside the screenshot area in regular reftests don't)
* test is something that paginates, but there's then one reference per page (this seems to be mentioned above, but I hadn't thought about it before that comment, and I worry a little bit that it might be rather fragile)

I'd probably lean towards some variant of the first, although I might be missing some advantage of the second.

**Comment by jgraham** [comment]
I agree with @gsnedders assessment of the PDF-vs-just-rendering-paginated-to-a-canvas; it doesn't seem likely that we'll directly expose the output data, just the pass-vs-fail information. So optimising this by not producing PDFs should be possible, but I expect the most straightforward implementation to involve creating PDFs, so I'm likely to look at that first (assuming I work on this). That said, I'd prefer not to require different test types for "run this as a reftest" and "assert this output document contains the following strings" (which AIUI is the current approach to testing that we don't rasterize things that we shouldn't), so depending on how often that's used, it may be easier to always generate actual PDFs? We can wait and see.

I think it's relatively easy to add a feature to specify the page dimensions; `<meta name='page-size' content=3x2>` or something.

As for whether references should be a single document or a set of documents, one concern I had is whether there are enough ways to generate multipage documents with the necessary level of control that we can use different codepaths in the test and the ref. If that's hard then using one document per reference page may make it easier to write refs that are independent of the test. But maybe it's not a concern?

**Comment by dbaron** [comment]
If you know the page size, I think it's easy enough to generate multipage documents with the required amount of control.

**Comment by jwatt** [comment]
> @jwatt I guess one relevant question wrt the format is whether we expect `@page` to apply? I _think_ the answer for `reftest-paged` is that it does?

> > To avoid this it's useful to be able to write tests to examine the internal structure of a PDF to check for the presense of specific strings, or that a certain number of a specific type of path commands exist.
> 
> I wonder how useful and how fragile such tests would be cross-browser? (Does this seem something we can address after the visual side?)

Yes, the visual side is more important.

**Comment by jwatt** [comment]
> I'd note there are a few different options for references:
> 
>     * test and reference are both things that paginate [snip]
> 
>     * test is something that paginates, but there's then one reference per page [snip]
> 
> I'd probably lean towards some variant of the first, although I might be missing some advantage of the second.

The concern I had in mind is that both the test and the reference may not paginate correctly and having separate files per page enables enforcing strict pagination of the reference. You may be right that that could cause more problems (or friction) than it solves though.

**Comment by dbaron** [comment]
That sounds a bit like a general objection to the concept of reftests (which was raised frequently when I originally proposed the format), but I don't think it's been enough of a problem in practice to counteract the advantages of the format.  (There are also a bunch of ways to get pretty reliable pagination, e.g., one containing div per page that's exactly the right height and probably sets `page-break-inside`.)

**Comment by jwatt** [comment]
Yeah, that's fair. To be clear I'm happy to have single ref perf test.

**Comment by gsnedders** [comment]
I'm strongly in favour of a single reference page, FWIW.
