### ISSUE TITLE
Source IDL for idlharness.js tests should be auto-synced from latest draft specs

### ISSUE THREAD

**Issue by mdittmer** [web-platform-tests/wpt#7784]
This should be relatively straightforward, given that https://github.com/GoogleChrome/webidl-diff already contains code for locating specs, extracting IDL, and verifying it (by parsing it).

**Comment by foolip** [comment]
This came up in bit.ly/ecosystem-infra-rotation today. This work is planned for this quarter so the priority label is actually correct, see details in [Changes to Web IDL in specs automatically propagate to wpt PRs](https://docs.google.com/document/d/1ojlLDiRruI4e95Z7JQ10JQPRMiQHd_40rBkYCL6IJqw/edit#heading=h.4tiwxmm3syiq).

**Comment by mdittmer** [comment]
@dontcallmedom talked about getting [reffy](https://github.com/tidoust/reffy) to output these IDL snippets, because its analysis needs to parse and interpret the IDL anyway. Dom**inique**, when do you think publishing the IDL snippets could be integrated into report generation?

**Comment by foolip** [comment]
This is in progress, see the linked project.

**Comment by foolip** [comment]
I have something in progress in https://github.com/foolip/wpt-idl-importer.

**Comment by foolip** [comment]
Suggesting in https://github.com/tidoust/reffy-reports/issues/20 to trigger the updates from reffy-reports directly instead.

**Comment by foolip** [comment]
This is now done, PRs will be automatically created to reflect any changes that happen in reffy-reports.
