### ISSUE TITLE
./wpt run --log-mach-level debug should output ERROR messages

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#7847]
Given ERROR represents a test runner error, when debugging we probably want the message that comes with it.

**Comment by foolip** [comment]
I'll call this backlog, any objections?

**Comment by jgraham** [comment]
FWIW I don't understand this issue. It works like that. It's possible we are catching specific errors that ought to be surfaced, but I'd need a demonstration that there's a general problem.

**Comment by gsnedders** [comment]
@jgraham make `run_screenshot` in the executor just be `raise Exception('foobar')`. How do I get the message and traceback for that exception?

**Comment by qiuzhong** [comment]
@gsnedders , do you mean we should add `logger.debug()` statements so the logger can records the detailed message and traceback when there're errors happened in test runner?

**Comment by gsnedders** [comment]
This has got resolved at some point.
