### ISSUE TITLE
[css-flex][spec-rec] Write more tests containing images

### ISSUE THREAD

**Issue by gregwhitworth** [web-platform-tests/wpt#7957]
We need more testing around images in particular as this is one of the primary reasons the section of https://drafts.csswg.org/css-flexbox-1/#min-size-auto

**Comment by gregwhitworth** [comment]
Reference: https://drafts.csswg.org/css-flexbox-1/#min-size-auto

**Comment by davidsgrogan** [comment]
We've added 49 test files, some having many subtests. I think we can call this done.

```
~/web-platform-tests/css/css-flexbox(master)$ git log --diff-filter=A --name-status --since=2018-01-01 -- *img* *image* |grep ^A\\s |wc -l
49
```
