### ISSUE TITLE
XMLHttpRequest/event-error-order.sub.html is incorrect per spec (and browser-compat).

### ISSUE THREAD

**Issue by wisniewskit** [web-platform-tests/wpt#8049]
The test expects a "headers received" event, but I see no way for that to be fired given the spec-text.
The only place it would be fired is in the "process response" steps of the `send()` method, and because the response is an error we will never reach that step.

According to the [wpt.fyi](https://wpt.fyi/results/xhr/event-error-order.sub.html?label=stable&aligned=true), Firefox is currently firing the event, but Edge, Blink, and Safari do not (I confirmed manually in Blink and Safari).

**Comment by wisniewskit** [comment]
@annevk, what do you think here?

**Comment by annevk** [comment]
Hmm yeah, you're correct. It probably makes sense that it terminates before that even is a thing as headers received is a success signal of sorts. Do you want to fix or should I?

**Comment by wisniewskit** [comment]
I won't have time to fix it right in the next couple of days, so feel free to beat me to it :)

**Comment by annevk** [comment]
I created a PR, but it turns out other browsers still have other issues and I didn't have time to verify whether those failures are against the standard.
