### ISSUE TITLE
allowpaymentrequest-attribute-same-origin-bc-containers.https.html needs review

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#8070]
I think allowpaymentrequest-attribute-same-origin-bc-containers.https.html might need to be checked... seems to halt on multiple browsers, so I suspect there might be a bug in the test itself. 

links:

* [ ] https://github.com/w3c/web-platform-tests/blob/master/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-same-origin-bc-containers.https.html
* [ ] https://github.com/w3c/web-platform-tests/blob/master/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-cross-origin-bc-containers.https.html

**Comment by marcoscaceres** [comment]
I think it might be the same with allowpaymentrequest-attribute-cross-origin-bc-containers.https.html

**Comment by miketaylr** [comment]
links:

* [ ] https://github.com/w3c/web-platform-tests/blob/master/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-same-origin-bc-containers.https.html
* [ ] https://github.com/w3c/web-platform-tests/blob/master/payment-request/allowpaymentrequest/allowpaymentrequest-attribute-cross-origin-bc-containers.https.html

**Comment by marcoscaceres** [comment]
@zcorpan, any chance you could recheck these?

**Comment by marcoscaceres** [comment]
Moved @miketaylr's links to the top, and removed his comment.

**Comment by marcoscaceres** [comment]
These have been fixed up.
