### ISSUE TITLE
Add automation API for WebDriver actions

### ISSUE THREAD

**Issue by kereliuk** [web-platform-tests/wpt#8152]
Ref: #8151

**Comment by kereliuk** [comment]
Yep, I am working on something that this is part of currently and plan to be finished before the end of the quarter.

**Comment by alijuma** [comment]
Should this still be priority:roadmap?

**Comment by foolip** [comment]
@kereliuk, this came up in priority:roadmap triage again today. Is this what you mentioned this week you've begun to work on?

**Comment by kereliuk** [comment]
#11931 is a PR for the non-protocol specific portions (will unblock testdriver-vendor workflows).

**Comment by foolip** [comment]
This is a dupe of https://github.com/web-platform-tests/wpt/issues/7435.
