### ISSUE TITLE
Travis check_stability crashes when log contains Unicode characters

### ISSUE THREAD

**Issue by Hexcles** [web-platform-tests/wpt#8285]
This was originally a comment in #5998, but I realized it's actually a separate issue.

Chromium developer @bsittler reported the case: https://travis-ci.org/w3c/web-platform-tests/jobs/281056652#L2086

I took a quick look and `check_stability.py` is the culprit, in particular this line: https://github.com/w3c/web-platform-tests/blob/b45fe4ae15ce4b7c2b28d41fd7a01fd258d9b8b1/tools/ci/check_stability.py#L79

The root cause is this line essentially assumes the provided `msg` is an un-encoded string (a `unicode` type, or a `str` with only ASCII characters, which is an unfortunate mess in Python 2). If `msg` is already encoded (and the encoded result contains high bytes), an exception is thrown:

```python
s = u'世界'
msg = s.encode('utf8')
print msg.encode('utf8')
----
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128)
```

This line encodes and decodes the message (to and from UTF-8). It seems to me the sole purpose is to get `backslashreplace`. If that's the case, some other approaches may be better. Otherwise, we need to test if `msg` is already encoded (it may or may not be, depending on the call site).

**Comment by foolip** [comment]
@Hexcles, do you know what the fix would be for this?

**Comment by Hexcles** [comment]
Supposedly the right fix is to dig through the code base and ensure encode
only happens once. If that proves to be infeasible (because of the size of
code base, third party libraries, whatever), there's also a hacky monkey
patching "fix"...

I haven't got time to look into it.

**Comment by foolip** [comment]
@bsittler, is this affecting you still? Not sure if I should call it roadmap or backlog...

**Comment by Hexcles** [comment]
It doesn't seem to be a blocker, at this in this example. As you can see, the Travis job was green despite the crash in the middle.

**Comment by foolip** [comment]
Backlog then, maybe Python 3 will come around sooner than we get to this :)

**Comment by Hexcles** [comment]
For reference, this Chromium infra issue https://crbug.com/787531#c10 has some very useful Unicode strings that we can use as a smoke test.

```
ABC~‾¥≈¤･・•∙·☼★星🌟星★☼·∙•・･¤≈¥‾~XYZ
```

**Comment by stephenmcgruer** [comment]
@Hexcles Is this relevant anymore? We no longer use Travis, but not sure if it's still applicable to Taskcluster or Azure Pipelines.

**Comment by Hexcles** [comment]
I don't think this is relevant anymore.
