### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by wpt-issue-mover** [web-platform-tests/wpt#8371]
Originally posted as https://github.com/w3c/wptserve/issues/110 by @annevk on 09 Jan 2017, 10:25 UTC:

> It would be good to also have tests that go over HTTP/2. There are a couple of subtle differences with HTTP/1 and if HTTP/2 is on the rise it would be good to start covering it.
> 
> Differences I'm aware of:
> 
> * Header casing can matter in HTTP/1
> * WebSocket only works in HTTP/1
> * Chunked encoding is only in HTTP/1 (this will matter when Fetch gets "upload streams")

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/110#issuecomment-271281757 by @gsnedders on 09 Jan 2017, 13:16 UTC:

> See also: #80. I think realistically that's only ever going to get resolved by supporting HTTP/2.

**Comment by wpt-issue-mover** [comment]
Originally posted as https://github.com/w3c/wptserve/issues/110#issuecomment-271282983 by @annevk on 09 Jan 2017, 13:23 UTC:

> Well, we need to test #80 without HTTP/2 as well ideally. We'd cover a lot less potential failure paths otherwise.

**Comment by annevk** [comment]
I learned from @jyasskin that HTTP/2 header values can contain 0x0A (and presumably 0x0C and 0x00 too). It'd be good to have tests to see what that does.

https://github.com/w3c/web-platform-tests/issues/7274 is another thing I'd like to test, though that's mostly about what happens to HTTP/1 features that HTTP/2 dropped in APIs that support both.

**Comment by foolip** [comment]
Now we do :)
