### ISSUE TITLE
Need additional test cases for ResourceTiming.initiatorType

### ISSUE THREAD

**Issue by plehegar** [web-platform-tests/wpt#8408]
See
  https://github.com/w3c/resource-timing/issues/130

**Comment by akansha2608** [comment]
Hi @gsnedders @plehegar i would like to work on it , can you please guide me how to go ahead?

Thanks

**Comment by plehegar** [comment]
I believe this case was addressed in https://github.com/web-platform-tests/wpt/commit/dbab6933d28f439e745bd526d9a4a768f9200ab1#diff-f073c159cbd93b1bcf143c6fd7e6034b

It's now testing the video/source and audio/source case.
