### ISSUE TITLE
Get rid of web-platform.test references

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8420]
From #6868:

- [ ] clear-site-data/support/test_utils.sub.js
- [ ] content-security-policy/base-uri/report-uri-does-not-respect-base-uri.sub.html
- [ ] content-security-policy/generic/generic-0_8.sub.html
- [ ] content-security-policy/generic/generic-0_8_1.sub.html
- [ ] content-security-policy/nonce-hiding/script-nonces-hidden-meta.tentative.html
- [ ] content-security-policy/nonce-hiding/svgscript-nonces-hidden-meta.tentative.html
- [ ] fetch/api/request/request-structure.html
- [ ] html/browsers/origin/relaxing-the-same-origin-restriction/document_domain_setter.html
- [ ] html/semantics/embedded-content/the-iframe-element/cross_origin_parentage.html
- [ ] html/semantics/forms/the-label-element/label-attributes.html
- [ ] longtask-timing/longtask-in-childiframe-crossorigin.html
- [ ] longtask-timing/longtask-in-sibling-iframe-crossorigin.html
- [ ] navigation-timing/nav2_test_attributes_values.html
- [ ] navigation-timing/nav2_test_instance_accessors.html
- [ ] service-workers/service-worker/update-bytecheck.https.html
- [ ] webdriver/tests/cookies/add_cookie.py
- [ ] webdriver/tests/cookies/get_named_cookie.py
- [ ] webrtc/RTCPeerConnection-getIdentityAssertion.html
- [ ] webrtc/identity-helper.js

**Comment by jugglinmike** [comment]
I'm on the case

**Comment by jugglinmike** [comment]
Resolved via gh-11011.
