### ISSUE TITLE
`before_install.sh` throwing Python error didn't mark build as ERROR

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8525]
In https://travis-ci.org/w3c/web-platform-tests/jobs/309588422#L503 we see the script throwing a Python exception, however the build PASSED.

Per the Travis documentation:

> If before_install, install or before_script return a non-zero exit code, the build is errored and stops immediately.

We should have `before_install.sh` distinguish between the test job not matching and Python throwing an exception.

**Comment by gsnedders** [comment]
So the big problem here is `./wpt` exits with 1 if the test-job doesn't match and also exits with 1 if Python throws an exception. @jgraham ideas to fix this? I guess we need to not let the interpreter deal with the exception but instead deal with it ourselves so we can exit with 254 or something when an exception is thrown.

**Comment by gsnedders** [comment]
(I think we can get the same output as the interpreter gives from https://docs.python.org/2.7/library/traceback.html#traceback.print_exception)

**Comment by jgraham** [comment]
Or use something other than the status to determine which jobs to run. But maybe it's fine to just catch all exceptions and change the exit status to be not 1 in that case.

**Comment by omkar-dsd** [comment]
@jgraham I'll take up this issue. Need to do some manual handling of exceptions and return status.

**Comment by jgraham** [comment]
Fixed by #11139
