### ISSUE TITLE
device-aspect-ratio-001.html and -005.html assumes device aspect ratio of 1280/1024

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#8547]
These tests are failing everywhere:
https://wpt.fyi/css/mediaqueries/device-aspect-ratio-001.html
https://wpt.fyi/css/mediaqueries/device-aspect-ratio-005.html

(They also fail if imported into Chromium and run against content_shell.)

The tests are from https://github.com/w3c/web-platform-tests/commit/b8f3492dabeca1d7eb239c680f6cf549390d3c54.

@xinliux, can you investigate?

**Comment by nt1m** [comment]
I'll remove them, since they're bogus.
