### ISSUE TITLE
Get codecov for tools/ working again

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8613]
We used to have code coverage reports for tools/. We should get these working again.

**Comment by alijuma** [comment]
This has priority:roadmap. Is there any work planned for this quarter?

**Comment by gsnedders** [comment]
#9545 ran into problems with codecov.io's own behaviour; we should at least report those issues.

**Comment by foolip** [comment]
@jgraham removed what remains in de9cb9f69e677cd8098cdbb4680f4f3888efd9ee, closing.
