### ISSUE TITLE
Merge tests from css/vendor-imports into appropriate directories in css/

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#8615]
cc/ @jgraham @dbaron 

At the moment, the tests in `css/vendor-imports/mozilla/mozilla-central-reftests/` cause a certain amount of confusion: they often get omitted when people are trying to run all tests for a certain module, and they often don't get noticed when people are looking to see if tests for a certain feature exists.

**Comment by gsnedders** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423971 is a Mozilla bug for this.

**Comment by foolip** [comment]
Looking at https://wpt.fyi/interop/css/vendor-imports/mozilla/mozilla-central-reftests, at the 3/4 column for tests that are failing only in one engine and thus would be highly valuable, I see:
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/shapes1 -- many Chrome-only failures
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/images3 -- many Edge-only failures (@thejohnjansen FYI)
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/flexbox -- Chrome-only, Edge-only and Safari-only failures
https://wpt.fyi/results/css/vendor-imports/mozilla/mozilla-central-reftests/variables -- Edge-only failures

@dbaron, does this move need to happen from within the Gecko repo? Who would be able to do it?

**Comment by MatsPalmgren** [comment]
@foolip I'm [told](https://bugzilla.mozilla.org/show_bug.cgi?id=1490969#c1) that we're blocked on WPT reftests not working on Android.

**Comment by foolip** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1490969 was resolved about two months ago, deleting the original copy of these tests in Gecko, and updating [/css/vendor-imports/mozilla/mozilla-central-reftests/README](https://github.com/web-platform-tests/wpt/blob/13bade5077c754d3d42183606772a060f54cbe29/css/vendor-imports/mozilla/mozilla-central-reftests/README) to say:

> This directory is the remains of an earlier wpt sync system.
>
> Tests should be moved into the correct directory under css/.
>
> In the meantime, feel free to fix any test bugs in the usual way.

So it looks like it's now possible to do what this issue suggests directly as PRs in this repository: Merge tests from css/vendor-imports into appropriate directories in css/!

**Comment by dbaron** [comment]
Have the tests *already* been moved?  Maybe they've been copied but not deleted from the original location?  It looks like my sync script broke when the directory was removed in mozilla-central, so it's possible the right thing to do here is to delete the directory rather than move anything.

**Comment by dbaron** [comment]
Oh, never mind, it looks like the end of the removal process was done differently from the rest of it.

**Comment by foolip** [comment]
I tried a small and simple move in https://github.com/web-platform-tests/wpt/pull/26722. If that doesn't result in something blowing up I'll probably try to move some more.

**Comment by nt1m** [comment]
There are 7 dirs left:
* counter-styles-3
* masking
* ruby
* selectors4
* text-decor-3
* text3
* writing-modes-3

https://github.com/web-platform-tests/wpt/tree/master/css/vendor-imports/mozilla/mozilla-central-reftests

**Comment by foolip** [comment]
@nt1m I moved a bunch but don't have any of the remaining 7 in flight. Are you interested in moving some of these?

**Comment by nt1m** [comment]
@foolip I moved 3 recently (36021fc67e2c2eb7805ad15fc9a8141515d209ec, b609eb7f53336e4cc9de98c255314a46c8576e89, 9ba2976ae0b5ced23ff312a752fc78d0bd557f9c). 

I'd love to move the rest whenever I have free time, but some questions that linger in my mind are: how to rename them, whether there are redundant tests to delete, which subfolders to pick, when relevant. It's not always obvious.

**Comment by foolip** [comment]
I agree it's not always easy to decide. I would say that as long as you can find a destination folder (feel free to ask if not sure) then just moving all tests without renaming or deduplication is fine. A reviewer might ask for some cleanup, but then they will have also helped you pinpoint what to clean up.

**Comment by nt1m** [comment]
There's only one directory left: https://github.com/web-platform-tests/wpt/tree/master/css/vendor-imports/mozilla/mozilla-central-reftests

It's only generated tests.

Feel free to take it.

**Comment by jgraham** [comment]
@nt1m Not all heros wear capes! But for all I know you may be wearing a cape right now, so it's impossible to say if that's a relevant fact or not ;)
