### ISSUE TITLE
[css-text] white-space-collapsing-* tests refer to a property that isn't spec'd

### ISSUE THREAD

**Issue by jfkthame** [web-platform-tests/wpt#8961]
There are three test files css/css-text/white-space/white-space-collapsing-*.xht that appear to be testing a property `white-space-collapsing`, and point to http://www.w3.org/TR/css-text-3/#white-space-collapsing as the definition of the property.

However, there doesn't appear to be any such property in that spec (nor could I find it in older drafts that I checked, though perhaps it was there at one time). A little more digging suggests that it has been pushed to css-text-4, and is now (tentatively?) renamed and split into `text-space-collapse` and `text-space-trim`.

As such, the white-space-collapsing-*.xht tests look totally invalid, afaics.

**Comment by frivoal** [comment]
These tests have been removed.
