### ISSUE TITLE
RTCStats-helper.js's validateStatsReport assumes video track

### ISSUE THREAD

**Issue by henbos** [web-platform-tests/wpt#9010]
I used validateStatsReport() with a report containing a "track" stats for video, and got expect failure because the track - which was an audio track - did not contain frameWidth (a video track stat) as an unsigned long.

We need to expect different entries depending if kind == "audio" or "video".

Also, I would like a helper function for validating a single stats object, basically doing this:
```
const validator = statsValidatorTable[stats.type];
if(validator) {
  validator(statsReport, stats);
}
```

Can you take a look @soareschen ?

**Comment by dontcallmedom** [comment]
This was fixed in https://github.com/web-platform-tests/wpt/commit/4aede5ca1de5a2b7dd7a35839b5e75ff8d5bfbe8#diff-6fd1a98df4ca8b89a0df8497fd62ab39
