### ISSUE TITLE
RTCRtpContributingSource's audioLevel member should be double (asserted to be byte)

### ISSUE THREAD

**Issue by foolip** [web-platform-tests/wpt#9108]
These bits are out of sync with the spec:
https://github.com/w3c/web-platform-tests/blob/524bea1dd8d0ad58733072bd4e8b8044042f589e/webrtc/RTCRtpReceiver-getSynchronizationSources.https.html#L64
https://github.com/w3c/web-platform-tests/blob/524bea1dd8d0ad58733072bd4e8b8044042f589e/webrtc/RTCRtpReceiver-getContributingSources.https.html#L77

Changed to double here:
https://github.com/w3c/webrtc-pc/pull/1736

There are a few other occurrences of "audioLevel" too which probably should be updated.

**Comment by dontcallmedom** [comment]
the tests with regard to type were aligned in https://github.com/web-platform-tests/wpt/commit/a7ddc6843713e6eae15c9b1ac32a7ad23ef42d9e
