### ISSUE TITLE
[WebRTC] RTCDtlsTransport-getRemoteCertificates.html : dependency on SctpTransport

### ISSUE THREAD

**Issue by aboba** [web-platform-tests/wpt#9110]
The purpose of https://github.com/w3c/web-platform-tests/blob/master/webrtc/RTCDtlsTransport-getRemoteCertificates.html  is to test the RTCDtlsTransport interface. However, because it depends upon support for the RTCSctpTransport interface, on a browser that does not support RTCSctpTransport, but does support RTCDtlsTransport, the tests will fail, regardless of how the RTCDtlsTransport interface is implemented.

A better design would be to first test for support of the RTCDtlsTransport object, and then if it is supported, test for support of other objects (e.g. RtpSender, RtpReceiver, SctpTransport). Based on these results, a DtlsTransport could be obtained so to allow other tests to be run. For example, on a browser that supports DtlsTransport and RtpReceiver, receiver.transport could be used to obtain access to a DtlsTransport.

**Comment by dontcallmedom** [comment]
given that this would have only provided different results in old Edge, and unless it becomes clear it would help with Firefox or Safari, I'm inclined to close this issue
