### ISSUE TITLE
[WebRTC] RTCIceTransport.html : dependency on SctpTransport

### ISSUE THREAD

**Issue by aboba** [web-platform-tests/wpt#9111]
The purpose of https://github.com/w3c/web-platform-tests/blob/master/webrtc/RTCIceTransport.html is to test the RTCIceTransport interface.  However, because it depends upon support for the RTCSctpTransport interface, on a browser that does not support RTCSctpTransport, but does support RTCIceTransport, the tests will fail, regardless of how the RTCIceTransport interface is implemented. 

A better design would be to first test for support of the RTCIceTransport object, and then if it is supported, test for support of other objects (e.g. DtlsTransport, RtpSender, RtpReceiver, SctpTransport).  Based on these results, an IceTransport could be obtained so to allow other tests to be run.  For example, on a browser that supports IceTransport, DtlsTransport and RtpReceiver, receiver.transport.transport could be used to obtain access to an IceTransport.

**Comment by dontcallmedom** [comment]
given that this would have only provided different results in old Edge, and unless it becomes clear it would help with Firefox or Safari, I'm inclined to close this issue

**Comment by aboba** [comment]
Safari supports IceTransport but not SctpTransport. So this is a potentially misleading test. Chrome and new Edge pass.
