### ISSUE TITLE
Lint can regress on master because CSS-COLLIDING-* lints don't get all paths

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#9171]
```
ERROR:lint:css/css-grid/alignment/support/100x100-green.png: The filename support/100x100-green.png is shared by: css/css-flexbox/support/100x100-green.png, css/css-grid/alignment/support/100x100-green.png, css/css-grid/grid-items/support/100x100-green.png (CSS-COLLIDING-SUPPORT-NAME)
```

This seems to have started failing with 1f69b4225e6c424b85b7a90b3851a72bf8915b60 from https://github.com/w3c/web-platform-tests/pull/9089 (where CI passed, including lint).

The underlying cause of this is that in CI we call lint with only the changed paths, and the CSS-COLLIDING-* lints need to know all filenames to consider whether they collide or not.

cc/ @jgraham

**Comment by gsnedders** [comment]
One obvious solution could just be to make `css/` all get linted any time a thing in `css/` changes.

**Comment by belaeifert** [comment]
Hello, I could not replicate this error.
Could you tell how to replicate?

Thank you

**Comment by gsnedders** [comment]
This really is just a special case of #10021?
