### ISSUE TITLE
RTCRtpSender.get/setParameters() test coverage

### ISSUE THREAD

**Issue by Orphis** [web-platform-tests/wpt#9395]
We currently have no coverage for RTCRtpSender.getParameters() and little for setParameters(). We should have better coverage.

**Comment by Orphis** [comment]
I don't find the coverage satisfactory. We should have more tests, for example that calling getParameters() after a setParameters() call return a similar struct.

**Comment by foolip** [comment]
Yeah, that makes sense. setParameters() returns a promise, so there should be test verifying *when* the new parameters are returned from getParameters(). The way the spec is written, they shouldn't take effect immediately, at least.
