### ISSUE TITLE
Get rid of reviewable?

### ISSUE THREAD

**Issue by marcoscaceres** [web-platform-tests/wpt#9664]
Can we get rid of the `reviewable` integration? I don't think anyone is using it, and it's definitely not working (it just adds empty comments).

Every time I want to update a pull request description, it trashes what I write... which equals 😾.

**Comment by foolip** [comment]
I've had that edit conflict too. Who can turn it off? @jgraham?

**Comment by sideshowbarker** [comment]
It’s @jgraham’s call. We’ve had this discussion before, and the last time it came up, I recall that he indicated he wanted to keep it on for reviews of some infrastructure resources other than test cases — I think the testharness.js sources at least, and maybe the `wpt` sources and such.
